### PR TITLE
Don't include noop in etcd_common

### PR DESCRIPTION
**Pull request by mtnbikenc**
Bug [1464025](https://bugzilla.redhat.com/show_bug.cgi?id=1464025)

### CODE REVIEW

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
[test]

**Comment by ingvagabund** [comment]
`etcd_upgrade` uses the following vars from the `etcd_common` role:
* etcdctlv2
* etcd_service
* etcd_service_file

So the dependency can not be removed.

**Comment by ingvagabund** [comment]
For some reason, creating empty `noop.yaml` under `etcd_common/tasks` helps.

**Comment by mtnbikenc** [comment]
`etcdctlv2` is already in `etcd_upgrade/vars/main.yml`

Why run an entire role nine additional times if only two variables need to be set?

**Comment by ingvagabund** [comment]
> etcdctlv2 is already in etcd_upgrade/vars/main.yml

Right.

> Why run an entire role nine additional times if only two variables need to be set?

Since the two variables would get duplicated otherwise. Instead, we should get rid of the `openshift_repos` role. Than, it will not matter.

**Comment by sdodson** [comment]
[test]

**Comment by ingvagabund** [comment]
the `etcdctlv2` that is defined in `vars/main.yml` needs:
* etcd_peer_cert_file
* etcd_peer_key_file
* etcd_peer_ca_file
* etcd_peer
* etcd_client_port
which are defined in the `etcd_common`. 

Given https://github.com/openshift/openshift-ansible/pull/4770 just merged, the `etcd_common` can stay where it is.

**Comment by ingvagabund** [comment]
The CI Failure failed on:
```
[Fail] [Feature:ImageLookup] Image policy [It] should perform lookup when the pod has the resolve-names annotation 
```

which failed due to:

```
  ! error: Import failed (InternalError): Internal error occurred: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/ef/efe10ee6727fe52d2db2eb5045518fe98d8e31fdad1cbdd5e1f737018c349ebb/data?Expires=1502833908&Signature=YbPLhhJYnvrg~oKHSzuszp9a1UKEqZWSMUl0S2Pk3h4lZU0KSMBFPeFEDLCFNJjThHWBItS79TQyGGM~0zEPagK3fh0j8p9-wWVazOQDPB4aORE7NfWpmCJR4xmYpAASINo9CR7fu4XvQ-51aXtdLrluG7ASzIAQsu6fNBDEtFA_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: EOF
      Less than a second ago

error: tag latest failed: Internal error occurred: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/ef/efe10ee6727fe52d2db2eb5045518fe98d8e31fdad1cbdd5e1f737018c349ebb/data?Expires=1502833908&Signature=YbPLhhJYnvrg~oKHSzuszp9a1UKEqZWSMUl0S2Pk3h4lZU0KSMBFPeFEDLCFNJjThHWBItS79TQyGGM~0zEPagK3fh0j8p9-wWVazOQDPB4aORE7NfWpmCJR4xmYpAASINo9CR7fu4XvQ-51aXtdLrluG7ASzIAQsu6fNBDEtFA_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: EOF
```

does not look like something related to the PR (cause the remaining Jenkins Jobs passed).

**Comment by ingvagabund** [comment]
@mtnbikenc I would stick with creating empty `etcd_common/tasks/noop.yml` file. Then update the `etcd_common` once we have the action based role design pattern thoroughly documented.

**Comment by dav1x** [comment]
@ingvagabund @mtnbikenc I root caused the issue in my own environment as well. 

https://github.com/openshift/openshift-ansible/blob/master/roles/etcd_common/tasks/main.yml#L9

Changed to this: 
when: '"noop" not in r_etcd_common_action'  

This changes lets everything work fine. In my case, im using tags in my ansible playbook calling the installation. The issue appears to have to do with tagging in general.

**Comment by mtnbikenc** [comment]
PR updated.  I'll address the role dependencies in a later PR.

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
[merge]

**Comment by sdodson** [comment]
[merge]

**Comment by ingvagabund** [comment]
> Changed to this:
when: '"noop" not in r_etcd_common_action'

Hmm, I am wondering what is the difference.

Thanks for figuring that out.

**Pull request merged**
