### PR TITLE
[devel-40] deploy_cluster_40: bootkube service no longer removes itself

### PR DESCRIPTION
**Pull request by vrutkovs**
bootkube service now properly stops instead of removing itself

### CODE REVIEW

**Comment by sdodson** [comment]
/lgtm cancel
```
  msg: 'The conditional check ''ansible_facts.services[''bootkube.service''].status == ''stopped'''' failed. The error was: error while evaluating conditional (ansible_facts.services[''bootkube.service''].status == ''stopped''): ''dict object'' has no attribute ''status'''
```

**Comment by vrutkovs** [comment]
Right, pushed a commit to change `status` -> `state`

**Comment by vrutkovs** [comment]
Flake: DesiredStateNotYetAchieved in openshift-cluster-openshift-controller-manager-operator

/retest

**Comment by mtnbikenc** [comment]
@vrutkovs Is this PR blocked on another PR getting merged?  I see the failures on 'parse ignition file' which seem unrelated to this particular change.

**Comment by vrutkovs** [comment]
This was a fix for RHEL control plane setup, no longer needed

**Pull request closed without merging**
