### PR TITLE
Reference deployment_type instead of hardcoding origin

### PR DESCRIPTION
**Pull request by codificat**
The Vagrantfile hardcodes "origin" as the deployment type, should use the env variable value instead.

### CODE REVIEW

**Comment by detiber** [comment]
Nice catch, we may want to error out if deployment_type != origin at this point though, since the boxes specified are centos.  Eventually, we'd want to support a vagrant based Enterprise install as well.  I'm not sure an Online install would ever be valid for Vagrant though (since it wouldn't have access to the online repositories).

**Comment by codificat** [comment]
Instead of failing if deployment_type != origin, added some additional changes that allow you to deploy enterprise using vagrant.

For enterprise the box should be manually downloaded beforehand though, so added some docs for that.

Registration builds upon the registration changes from #264 so it references the same environment variables.

If the changes look fine they should probably be rebased to current master; however, a quick attempt at that resulted in some errors related to #331 that I haven't investigated yet.

**Comment by brenton** [comment]
@twiest, do you know of anyone else would should review this?  I'm curious if there's any reason why the Vagrant file didn't previously include the master as a node.  Without the master running the SDN it won't be able port-forward to PODs or any other APIs that require access to the Pod network.

**Comment by twiest** [comment]
@brenton I don't know of anyone else should review it. I agree, that is weird.

**Comment by brenton** [comment]
@twiest I ask mainly because I don't know who is relying on the Vagrantfile in this repo.  We don't use it in OSE officially and we don't test it.

**Comment by twiest** [comment]
@brenton same for ops (at least right now). We may use it more in the future.

**Comment by detiber** [comment]
@brenton @twiest It was something that I created due to user demand, it hasn't been maintained very well, hence the master not being a node and this issue.

**Comment by twiest** [comment]
@detiber so, +1 from you?

**Comment by detiber** [comment]
@twiest indeed :+1: from me

**Pull request merged**
