### PR TITLE
Bug 1611840 - Correctly set console replicas

### PR DESCRIPTION
**Pull request by spadgett**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1611840

/assign @vrutkovs 
@sdodson fyi

### CODE REVIEW

**Comment by vrutkovs** [comment]
/lgtm

3 masters have created 3 console replicas

**Comment by sdodson** [comment]
Should this be a daemonset rather than a deployment? I thought that was the model for something that we'd want to deploy on all masters and not have to set the number of replicas.

**Comment by vrutkovs** [comment]
@sdodson its similar to routers - the default is to deploy one router per a node in nodeselector, but the amount can be overridden. Not sure if DaemonSet is a better solution for this

**Comment by spadgett** [comment]
@sdodson Good question. DaemonSet is possible since the admin console uses rolling deployments. I plan to raise this in the next architecture call.

cc @jwforres

**Pull request merged**
