### PR TITLE
Router wildcard certificate created by default

### PR DESCRIPTION
**Pull request by enoodle**
I suggest setting this parameter default to `True`. Since https://github.com/openshift/openshift-ansible/pull/3821 It seems more useful then using arbitrary hostnames.

cc @kwoodson @simon3z

### CODE REVIEW

**Comment by enoodle** [comment]
ping @kwoodson @jcantrill PTAL

**Comment by kwoodson** [comment]
@mtnbikenc @abutcher,  do you see any reason as to why we should or shouldn't do this?

**Comment by jcantrill** [comment]
@enoodle I don't have an opinion on why we would or would not do this.

**Comment by abutcher** [comment]
@kwoodson @enoodle My only worry would be that defaulting `openshift_hosted_router_create_certificate=true` would stomp a user provided `openshift_hosted_router_certificate`.

**Comment by kwoodson** [comment]
@abutcher, @enoodle, That's my fear as we don't use the default router certs on our operations team.  We supply real certificates and would get default ones which would break our installs unless specifying `openshift_hosted_router_create_certificate=false`. 

I understand the desire to have a default be turned on since a lot of installs do not require real certificates.  I guess this is just a matter of preference unless someone has a good argument to update it.

**Comment by abutcher** [comment]
We could probably default this if that linked section didn't create the default wildcard certificate when `openshift_hosted_router_certificate` was provided.

**Comment by enoodle** [comment]
@abutcher I have added a condition on `openshift_hosted_router_certificate` being empty, PTAL

**Comment by enoodle** [comment]
@abutcher @kwoodson   I have added a condition on openshift_hosted_router_certificate being empty, Can you take another look?

**Comment by abutcher** [comment]
@enoodle The conditional looks great thanks.

I did not notice that the wildcard cert will contain SANs for `*.openshift_master_default_subdomain` and `openshift_master_default_subdomain` without any defaults, so base install is `""`, `"*."`. If this is always on I think we should have a default for this like `*.router.default.svc.cluster.local`. @sdodson @kwoodson sound okay?

**Comment by kwoodson** [comment]
@enoodle, sorry for the slow response.  We've been locked down working on 3.6.

@abutcher, That sounds fine.

**Comment by enoodle** [comment]
@kwoodson @abutcher I have added a default value for the certificate paths. Can you take another look?

**Comment by abutcher** [comment]
aos-ci-test

**Comment by abutcher** [comment]
bot, test this please

**Comment by sdodson** [comment]
[merge]

**Comment by enoodle** [comment]
"Error from server (NotFound): namespaces \"logging\" not found"
"/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/scheduling/predicates.go:73
I0726 01:51:51.623994   17300 request.go:782] Error in request: resource name may not be empty"
 - I am not sure what jenkins is testing there exactly but it doesn't seem connected.

**Comment by abutcher** [comment]
flake https://github.com/openshift/origin/issues/15356

**Comment by abutcher** [comment]
[merge]

**Pull request merged**
