### PR TITLE
create container.yaml for odcs multi-arch build

### PR DESCRIPTION
**Pull request by jeffdyoung**
create container.yaml for odcs multi-arch build
@dorzel @adammhaile Please review.

Backports: https://github.com/openshift/openshift-ansible/pull/10168

### CODE REVIEW

**Comment by michaelgugino** [comment]
@jeffdyoung 
> It can't be cherrypicked from master, because this file looks to be different between releases.

I don't know what you mean.  Workflow is typically make changes to master, backport to other branches (with changes as necessary).

**Comment by jeffdyoung** [comment]
@michaelgugino in this case what is in master is probably for building the openshift-ansible container for  OCP 4.0, and what I'm submitting in this branch is for building the openshift-ansible container for OCP 3.10.  Keep me honest @adammhaile

**Comment by adammhaile** [comment]
@jeffdyoung gets the points :) 100% correct.

**Comment by michaelgugino** [comment]
@jeffdyoung @adammhaile 

I see what's going on here.  You are picking https://github.com/openshift/openshift-ansible/pull/10168 and making changes.

In the future, be sure to git cherry-pick -x locally, make you edits, and push up a PR that references the PR.

**Comment by dorzel** [comment]
+1

**Comment by sdodson** [comment]
@jeffdyoung @adammhaile Why is the content here different than that in release-3.11 and master branches? Shouldn't it be the same?

**Comment by sdodson** [comment]
From past discussions with @adammhaile I think we were told that if the package doesn't exist for a given arch it's simply ignored. Which sounds error prone to me, and a bit like this file is a mild suggestion for what we need rather than a well defined set of requirements, but whatevz.

**Comment by dorzel** [comment]
The packages in this file for this commit were generated by querying the buildroot (rhaos-3.10-rhel-7-ppc64le-container-build) for the package name. Every package that existed in the buildroot was added to the file. The reason a package would be excluded is if it wasn't in the buildroot (looks to be the case for the excluded packages) or was only installed on x86. There is no container.yaml in the rhaos-3.10-rhel-7 branch on dist-git for this image, so I had to generate my own.

**Comment by jeffdyoung** [comment]
Dropping this. We won't be doing odcs builds in the near future. Thanks!

**Pull request closed without merging**
