### PR TITLE
[WIP] initial module framework

### PR DESCRIPTION
**Pull request by detiber**

### CODE REVIEW

**Comment by detiber** [comment]
@dgoodwin Here is the rough start to the config upgrade module. Wanted to get the bits I've finished out there before I head out for DevOpsDays tomorrow.

One question that I have is how are we currently handling the config directory changes between 3.0 and 3.1, are we simply re-writing all the configs in the new locations when running the config playbook currently? I didn't see anything in your PR that was doing directory migrations.

**Comment by dgoodwin** [comment]
Afraid I'm not familiar, what are these config directory upgrades?

**Comment by detiber** [comment]
@dgoodwin The ones I'm aware of off the top of my head:

- /etc/openshift -> /etc/origin
- /var/lib/openshift -> /var/lib/origin

@sdodson would probably know the full set off the top of his head.

**Comment by sdodson** [comment]
@detiber The following code sets openshift.common.config_base and openshift.common.data_dir based on the deployment type. Ansible is mostly oblivious to the change and when we install the newer packages they create symlinks if the old paths exist, ansible would however update all the contents of the files to point at the new paths, which would be symlinks when upgrading from 'enterprise' to 'openshift-enterprise'.

```
        if 'config_base' not in facts['common']:
            config_base = '/etc/origin'
            if deployment_type in ['enterprise', 'online']:
                config_base = '/etc/openshift'
            facts['common']['config_base'] = config_base
        if 'data_dir' not in facts['common']:
            data_dir = '/var/lib/origin'
            if deployment_type in ['enterprise', 'online']:
                data_dir = '/var/lib/openshift'
            facts['common']['data_dir'] = data_dir
```

**Comment by detiber** [comment]
@sdodson ah, nice, I was worried that we'd have to handle the migration within the upgrade.

We shouldn't have to worry about Ansible updating the configs, since we are planning on skipping the config step in favor of modifying the configs using the module I'm building for this PR.

**Comment by dgoodwin** [comment]
I've added those two symlinks to the manual upgrade etherpad.

@detiber if it's ok I'll pick this up and see if I can get something for the end of day builds we're targeting.

**Pull request merged**
