### PR TITLE
Remove quick installer

### PR DESCRIPTION
**Pull request by sdodson**
We don't intend to support the quick installer any longer. If you have a cluster that's been previously installed or managed via the quick installer you should have a .config/openshift/hosts file which can be used by ansible-playbook directly following the `Advanced installer` documentation.

### CODE REVIEW

**Comment by sdodson** [comment]
Need to update CI tooling to use 'openshift-ansible' rather than 'atomic-openshift-utils'. :-(

**Comment by mtnbikenc** [comment]
@sdodson Thoughts on coming back to this and getting it done?

**Comment by mtnbikenc** [comment]
@sdodson Where do we stand on this?

**Comment by sdodson** [comment]
> @sdodson Where do we stand on this?

We have to meet with PM and CE&E to determine a solution that fills the need. I think a simplified all in one inventory like https://github.com/openshift/openshift-ansible/pull/6129 will likely suffice but we need to make sure those parties are bought in. I'll arrange a meeting.

**Comment by sdodson** [comment]
We'll flatten everything down to just one package in the near future.

**Pull request merged**
