### PR TITLE
[KIECLOUD-369] - Update RHPAM and RHDM templates and imagestreams on …

### PR DESCRIPTION
**Pull request by spolti**
…OpenShift Service Catalog for release 7.7.0

Signed-off-by: spolti <fspolti@redhat.com>

### CODE REVIEW

**Comment by spolti** [comment]
@mtnbikenc @jstuever can you please take a look?
Thanks.

**Comment by spolti** [comment]
@gabemontero Hi, do you mind to take a look on this as well?

**Comment by spolti** [comment]
Looks like the errors are not related, can you please review?

**Comment by gabemontero** [comment]
> Looks like the errors are not related, can you please review?

Yeah 3.11 openshift-ansible isn't my domain

pull in @vrutkovs or @jstuever to see if they know some overall status of things or can help decipher the failures

**Comment by spolti** [comment]
Hi @vrutkovs @jstuever, any news?

**Comment by vrutkovs** [comment]
/hold

@mtnbikenc ^ PTAL, some image build error

**Comment by spolti** [comment]
Hi all, any updates?

**Comment by mtnbikenc** [comment]
Images job is fixed.
/hold cancel
/retest

**Pull request merged**
