### PR TITLE
Use region and zone labels added by cloudprovider for scheduling

### PR DESCRIPTION
**Pull request by irozzo-1A**
Retrofit of #7381 for OpenShift v3.7

### CODE REVIEW

**Comment by DanyC97** [comment]
thanks a bunch for doing this @irozzo-1A  !

**Comment by DanyC97** [comment]
@michaelgugino any chance you can wave your magic wand and wake up bot? :)

**Comment by aveshagarwal** [comment]
The default priority SelectorSpreadPriority already does spreading based on in-built labels `failure-domain.beta.kubernetes.io/zone and failure-domain.beta.kubernetes.io/region` and there is no need to have 2 different priority functions, SelectorSpreadPriority and ServiceAntiAffinity working on the same labels.

**Comment by irozzo-1A** [comment]
Closing as it is not required as explained in @aveshagarwal comment.

**Pull request closed without merging**
