### PR TITLE
Require pyOpenSSL

### PR DESCRIPTION
**Pull request by sdodson**
required by oo_filters

Fixes
```
import OpenSSL.crypto
No module named OpenSSL.crypto
```

### CODE REVIEW

**Comment by sdodson** [comment]
@thoraxe FYI

@detiber PTAL

**Comment by detiber** [comment]
:+1:

**Comment by sdodson** [comment]
Hmm, should we also ensure that it's installed on the remote host via openshift_facts? I don't know if the filters are run on the ansible host or the target host.

**Comment by abutcher** [comment]
@sdodson They run on the ansible host.

Similar to netaddr requirement for the ipaddr filter http://docs.ansible.com/ansible/playbooks_filters_ipaddr.html.

"To use this filter in Ansible, you need to install netaddr Python library on a computer on which you use Ansible (it is not required on remote hosts). It can usually be installed either via your system package manager, or using pip."

**Comment by sdodson** [comment]
@brenton ready to go

**Pull request merged**
