### PR TITLE
images: set atomic.run=once label

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by codificat** [comment]
@giuseppe openshift/playbook2image#3 is about to merge, and after that the openshift-ansible image will inherit system container support (including the atomic.run=once label) from playbook2image... therefore, adding this label will be redundant soon.

On the other hand, we might want to remove other [soon to become] redundant system-container bits from openshift-ansible as they will be already part of the base image... what do you think?

**Comment by giuseppe** [comment]
@codificat that is great!  The only question is if we want the "oneshot" feature for every container that uses `playbook2image`, are there playbooks where it is desiderable to run more than once (e. g., some replacement for cloud-init?).  If that is not an issue, I can close this PR if you are fine with it.

**Comment by codificat** [comment]
I don't really see a use case where you'd prefer the non-oneshot approach... but if there is, one can always use the `docker build` approach to playbook2image and remove that label... the suggestion in the p2i PR was to have *run once* by default and see if there's feedback that suggests we should change it.

So, if you're ok with that let's close this PR, and if playbook2image later changes to remove the "oneshot by default" we can add it to openshift-ansible.

**Comment by giuseppe** [comment]
yes sure, I am fine with it.  Thanks for the help.

**Pull request closed without merging**
