### PR TITLE
[3.7] test docker 1.13 excluder

### PR DESCRIPTION
**Pull request by sosiouxme**

### CODE REVIEW

**Comment by sosiouxme** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/7312/test_pull_request_openshift_ansible_logging_37/1/
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/7312/test_pull_request_openshift_ansible_extended_conformance_install/5729/
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/7312/test_pull_request_openshift_ansible_extended_conformance_install_crio/2920/
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/7312/test_pull_request_openshift_ansible_extended_conformance_install_system_containers/5521/

All failed for reasons other than checks. Not sure this is working. Let's try again.

/retest

**Comment by sosiouxme** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible_extended_conformance_install/5732/consoleFull#-94036117958b6e51eb7608a5981914356 and https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible_extended_conformance_install_crio/2924/consoleFull#-200658162358b6e51eb7608a5981914356 seem to indicate that the excluders are not actually enabled at the time that the checks run. Either that, or the 3.7 docker excluder isn't excluding docker-1.13, but from the output I don't see where it's actually installed.

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/7312/test_pull_request_openshift_ansible_logging_37/2/ failed way too early and I suspect https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/7312/test_pull_request_openshift_ansible_extended_conformance_install_system_containers/5525/ did not get to the point where it ran checks.

@michaelgugino @sdodson I'm not sure what's the best path forward. We would like to know up front if the install is going to fail for package reasons, but if we don't have a read on what will be excluded, that's basically impossible to determine. It may be necessary to remove docker from the check and either check for it independently after yum config is complete, or just let things fail during the course of installation (docker being one of the earliest things installed).

**Comment by michaelgugino** [comment]
@sosiouxme @sdodson I think we can remove the docker part of the check.  That's a prerequisite for <= 3.7 anyway.

If they have an incompatible version of docker installed, it's too late for us to do anything about it.

**Comment by sosiouxme** [comment]
@michaelgugino Actually, if the wrong docker is already installed, complaining about that should be legit. This check is complaining about the version it expects to be installed in the future, which is less certain. I think it would be possible to only remove the latter.

**Comment by michaelgugino** [comment]
@sosiouxme that wouldn't be a package availability check, IMO, we would need to see if it's installed and complain if we see the wrong thing.

That would probably simplify the logic for this.

**Comment by sosiouxme** [comment]
close in favor of https://github.com/openshift/openshift-ansible/pull/7347

**Pull request closed without merging**
