### PR TITLE
Add vsphere provider

### PR DESCRIPTION
**Pull request by dav1x**
Add vsphere cloud provider support

Resolves bz - https://bugzilla.redhat.com/show_bug.cgi?id=1494447

### CODE REVIEW

**Comment by cooktheryan** [comment]
@sdodson based on our conversation last week

**Comment by sdodson** [comment]
bot, test this

**Comment by cooktheryan** [comment]
@sdodson can you run this through the bot again?

**Comment by sdodson** [comment]
bot, test this please

**Comment by sdodson** [comment]
bot, test pull request

**Comment by sennerholm** [comment]
Hi!

I also think that you need to update roles/openshift_facts/library/openshift_facts.py so it add vsphere to kubelet_args, controller_args and api_server_args. I have a diff working for 3.7 (with this changes backported). 

It seems like some parts need rewrite for master
--------------------------------------------------
diff --git a/roles/openshift_facts/library/openshift_facts.py b/roles/opens=
hift_facts/library/openshift_facts.py
index ade5e28..71c5b9c 100755
--- a/roles/openshift_facts/library/openshift_facts.py
+++ b/roles/openshift_facts/library/openshift_facts.py
@@ -1080,6 +1080,9 @@ values provided as a list. Hence the gratuitous use o=
f ['foo'] below.
                 if facts['cloudprovider']['kind'] == 'gce':
                     kubelet_args['cloud-provider'] = ['gce']
                     kubelet_args['cloud-config'] = [cloud_cfg_path + '/g=
ce.conf']
+                if facts['cloudprovider']['kind'] == 'vsphere':
+                    kubelet_args['cloud-provider'] = ['vsphere']
+                    kubelet_args['cloud-config'] = [cloud_cfg_path + '/v=
sphere.conf']

         # Automatically add node-labels to the kubeletArguments
         # parameter. See BZ1359848 for additional details.
@@ -1125,6 +1128,10 @@ def build_controller_args(facts):
                 if facts['cloudprovider']['kind'] == 'gce':
                     controller_args['cloud-provider'] = ['gce']
                     controller_args['cloud-config'] = [cloud_cfg_path + =
'/gce.conf']
+                if facts['cloudprovider']['kind'] == 'vsphere':
+                    controller_args['cloud-provider'] = ['vsphere']
+                    controller_args['cloud-config'] = [cloud_cfg_path + =
'/vsphere.conf']
+
         if controller_args != {}:
             facts = merge_facts({'master': {'controller_args': controlle=
r_args}}, facts, [], [])
     return facts
@@ -1147,6 +1154,9 @@ def build_api_server_args(facts):
                 if facts['cloudprovider']['kind'] == 'gce':
                     api_server_args['cloud-provider'] = ['gce']
                     api_server_args['cloud-config'] = [cloud_cfg_path + =
'/gce.conf']
+                if facts['cloudprovider']['kind'] == 'vsphere':
+                    api_server_args['cloud-provider'] = ['vsphere']
+                    api_server_args['cloud-config'] = [cloud_cfg_path + =
'/vsphere.conf']
         if api_server_args != {}:
             facts = merge_facts({'master': {'api_server_args': api_serve=
r_args}}, facts, [], [])
     return facts

------------------------------------------------------------

**Pull request merged**
