### PR TITLE
Bug 1746143: Add CA to system trust

### PR DESCRIPTION
**Pull request by jcpowermac**
This originally existed in 3.9 but was removed.
Caused various BZs the last few months.
Tried to replace with node sync pod but
unable to restart the container runtime after
update-ca-trust extract is a problem.

### CODE REVIEW

**Comment by jcpowermac** [comment]
I need to test to see if this happens early enough that the container runtime is restarted to get around having to restart it again.

**Comment by jcpowermac** [comment]
Tested:
- 3.11 install
- 3.11 upgrade
Testing:
- 3.11 install
- 3.11 recreate ca
- 3.11 recert

**Comment by jcpowermac** [comment]
Tested:
3.11 install
3.11 recreate ca
3.11 recert

**Comment by jcpowermac** [comment]
Find the cluster ip of the registry
```
[root@ip-172-18-5-183 ~]# oc get service
NAME               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                   AGE
docker-registry    ClusterIP   172.30.197.177   <none>        5000/TCP                  14h
kubernetes         ClusterIP   172.30.0.1       <none>        443/TCP,53/UDP,53/TCP     14h
registry-console   ClusterIP   172.30.5.50      <none>        9000/TCP                  14h
router             ClusterIP   172.30.198.1     <none>        80/TCP,443/TCP,1936/TCP   14h
```

Extract the token from the builder secret
```
[root@ip-172-18-5-183 ~]# oc extract secret/builder-token-djkld
namespace
service-ca.crt
token
ca.crt
```
Use the token to log into the registry using the cluster ip
```
[root@ip-172-18-2-152 ~]# docker login 172.30.197.177:5000
Username: builder
Password:
Login Succeeded
[root@ip-172-18-2-152 ~]#
```
Result: no certificate errors

**Comment by stove-panini** [comment]
This PR causes a fresh install w/ containerized GlusterFS to fail. The restart playbook imported in `playbooks/openshift-node/private/join.yml` attempts to check Gluster health, but will always fail due to running before the Gluster cluster is deployed:
https://github.com/openshift/openshift-ansible/commit/8a5e9113f9d4d93f7d2d737e5aa561177eb8fbda

**Comment by jcpowermac** [comment]
Thanks @stove-panini working on a fix now

**Pull request merged**
