### PR TITLE
Revert "Make SDN read config file from sysconfig"

### PR DESCRIPTION
**Pull request by smarterclayton**
This reverts commit 5c6f01c7018c3068c985bdd8e6b6530dc932d080.

https://bugzilla.redhat.com/show_bug.cgi?id=1590918

There is no scenario where CONFIG_FILE is allowed to be changed

### CODE REVIEW

**Comment by vrutkovs** [comment]
First run - PASS - https://s3.amazonaws.com/aos-ci/ghprb/openshift/openshift-ansible/84feab4a9f7b8f38748753fad560bf5c81450321.0.1528908736416874110/index.html

**Comment by vrutkovs** [comment]
bot, retest this please

**Comment by vrutkovs** [comment]
bot, retest this please

**Comment by vrutkovs** [comment]
bot, retest this please

**Comment by smarterclayton** [comment]
Let’s get this tagged

**Pull request merged**
