### PR TITLE
Clean up lib_utils

### PR DESCRIPTION
**Pull request by mtnbikenc**
Removing unused code

### CODE REVIEW

**Comment by mtnbikenc** [comment]
```
Failing tests:

[Feature:Platform] Managed cluster should have no crashlooping pods in core namespaces over two minutes [Suite:openshift/conformance/parallel]
[sig-api-machinery] Namespaces [Serial] should ensure that all pods are removed when a namespace is deleted [Conformance] [Suite:openshift/conformance/serial/minimal] [Suite:k8s]
```
/retest

**Comment by mtnbikenc** [comment]
```
Failing tests:

[Conformance][Area:Networking][Feature:Router] The HAProxy router should expose the profiling endpoints [Suite:openshift/conformance/parallel/minimal]
[Feature:Builds][Conformance] remove all builds when build configuration is removed  oc delete buildconfig should start builds and delete the buildconfig [Suite:openshift/conformance/parallel/minimal]
[sig-cli] Kubectl client [k8s.io] Kubectl create quota should create a quota with scopes [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Pre-provisioned PV (default fs)] subPath should support readOnly file specified in the volumeMount [Suite:openshift/conformance/parallel] [Suite:k8s]
```
/retest

**Comment by mtnbikenc** [comment]
```
level=error msg="Error: Error applying plan:"
level=error
level=error msg="1 error occurred:"
level=error msg="\t* module.vpc.aws_route_table_association.private_routing[2]: 1 error occurred:"
level=error msg="\t* aws_route_table_association.private_routing.2: timeout while waiting for state to become 'success' (timeout: 5m0s)"
```
/retest

**Comment by mtnbikenc** [comment]
```
Failing tests:

[Conformance][Area:Networking][Feature:Router] The default ClusterIngress should support default wildcard reencrypt routes through external DNS [Suite:openshift/conformance/parallel/minimal]
[Feature:DeploymentConfig] deploymentconfigs keep the deployer pod invariant valid [Conformance] should deal with config change in case the deployment is still running [Suite:openshift/conformance/parallel/minimal]
[Feature:Platform] Managed cluster should have no crashlooping pods in core namespaces over two minutes [Suite:openshift/conformance/parallel]
```

**Comment by vrutkovs** [comment]
```
fatal: [localhost]: FAILED! => 
  msg: 'The conditional check ''svc.results.results[0].status.loadBalancer.ingress | length > 0'' failed. The error was: error while evaluating conditional (svc.results.results[0].status.loadBalancer.ingress | length > 0): ''dict object'' has no attribute ''ingress'''
```
ssh bastion playbook should retry until ingress is set

**Comment by mtnbikenc** [comment]
#325

```
Failing tests:

[Feature:Platform] Managed cluster should have no crashlooping pods in core namespaces over two minutes [Suite:openshift/conformance/parallel]

```
/retest

**Comment by mtnbikenc** [comment]
[#330](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/11197/pull-ci-openshift-openshift-ansible-devel-40-e2e-aws-scaleup/330/build-log.txt)
```
atal: [localhost]: FAILED! => 
  msg: 'The conditional check ''svc.results.results[0].status.loadBalancer.ingress | length > 0'' failed. The error was: error while evaluating conditional (svc.results.results[0].status.loadBalancer.ingress | length > 0): ''dict object'' has no attribute ''ingress'''
```
Need #11236

**Pull request merged**
