### PR TITLE
azure: write blobs with vhd suffix to name

### PR DESCRIPTION
**Pull request by jim-minter**

### CODE REVIEW

**Comment by jim-minter** [comment]
@sdodson please could you merge this? also I don't seem to be able to approve despite an OWNERS file - is that because we're on the release-3.9 branch?

**Comment by jim-minter** [comment]
@kwoodson fyi

**Comment by jim-minter** [comment]
@michaelgugino commit title updated, apologies.  It is unorthodox, but we are tracking and working on "forward porting" all the azure-related commits we are making to release-3.9, to get them into master.  @sdodson is aware.  Thanks.

**Comment by sdodson** [comment]
> @sdodson please could you merge this? also I don't seem to be able to approve despite an OWNERS file - is that because we're on the release-3.9 branch?

I'm not sure why that happened. The OWNERS file in playbooks/azure should've set you and kwoodson up for review.  @kargakis ideas?

**Comment by kargakis** [comment]
Yes, there is a bug that makes prow read OWNERS from master cc
@stevekuznetsov

https://github.com/kubernetes/test-infra/issues/7881

**Comment by sdodson** [comment]
flakes

**Pull request merged**
