### PR TITLE
Bug 1536253: Pass `--config` flag on oc commands when installing console

### PR DESCRIPTION
**Pull request by spadgett**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1536253

/assign @sdodson 
/kind bug

@jupierce cc

### CODE REVIEW

**Comment by spadgett** [comment]
@bparees @jim-minter Looks like TSB has the same problem:

https://github.com/spadgett/openshift-ansible/blob/7d7499efb48b00a320148d71e915193635707ea6/roles/template_service_broker/tasks/install.yml#L44-L56

I haven't tried to fix it in this PR.

**Comment by bparees** [comment]
thanks, tsb version here:
https://github.com/openshift/openshift-ansible/pull/6800

**Pull request merged**
