### PR TITLE
[wip] Get accurate count of total user pods in a clusterCountuser ansible

### PR DESCRIPTION
**Pull request by BlueShells**
someone please help me check if I missed something ,I can get the through a mock script from the zagg-client

### CODE REVIEW

**Comment by BlueShells** [comment]
@twiest

**Comment by twiest** [comment]
@BlueShells is this the PR you're working on? If so, please rebase it to the latest. There are merge conflicts according to github.

**Comment by jaryn** [comment]
Can one of the admins verify this patch?

**Comment by jaryn** [comment]
Can one of the admins verify this patch?

**Comment by arilivigni** [comment]
Testing job has been triggered.

**Comment by arilivigni** [comment]
Internal Jenkins error during triggering.
 No test results found.

**Comment by tbielawa** [comment]
This PR has been inactive for quite some time. Please update, fix any conflicts, and reopen this PR if this is still a priority you would like to see action on.

**Pull request closed without merging**
