### PR TITLE
Consolidate etcd migrate role

### PR DESCRIPTION
**Pull request by ingvagabund**
The PR is based on top of https://github.com/openshift/openshift-ansible/pull/5371 and https://github.com/openshift/openshift-ansible/pull/5451. Once both PRs are merged, I will rebase.

### CODE REVIEW

**Comment by michaelgugino** [comment]
This is a large patch set.  Some comments around your approach in some areas would be helpful, unless everything is pretty much straight forward.

**Comment by giuseppe** [comment]
did you mean #5451?

**Comment by ingvagabund** [comment]
> did you mean #5451?

right, updated, thanks

**Comment by ingvagabund** [comment]
Just rebasing on top of the master branch and re-lgtm

**Pull request merged**
