### PR TITLE
Fix hostname default when valid hostname not found on system

### PR DESCRIPTION
**Pull request by detiber**
This should fix https://github.com/openshift/openshift-ansible/issues/293

### CODE REVIEW

**Comment by detiber** [comment]
@maxamillion you'll need to do the following before re-running to ensure that the certificates and configs are regenerated properly: `rm -rf /etc/openshift /var/lib/openshift/*`

**Comment by maxamillion** [comment]
:+1: 

Confirmed, this resolves https://github.com/openshift/openshift-ansible/issues/293

Thank you!

**Comment by detiber** [comment]
@twiest @wshearn fixes an issue where the hostname is set to an empty string for a non-cloud host with hostname localhost.localdomain

**Comment by wshearn** [comment]
:+1:

**Comment by twiest** [comment]
:+1:

**Pull request merged**
