### PR TITLE
azure: format data disk for docker use

### PR DESCRIPTION
**Pull request by jim-minter**

### CODE REVIEW

**Comment by jim-minter** [comment]
@kwoodson ptal

**Comment by sdodson** [comment]
@jim-minter I wonder if the bot is randomly finding someone else because there's only two folks in playbooks/azure/OWNERS and you're the author of the PR? Is there a third person we could add to OWNERS?

**Comment by jim-minter** [comment]
@sdodson sure

**Comment by kwoodson** [comment]
@jim-minter, remove WIP when ready for merge.

**Comment by jim-minter** [comment]
https://github.com/Azure/acs-engine/pull/3082 must be merged before this PR

**Pull request merged**
