### PR TITLE
Docker on master aws

### PR DESCRIPTION
**Pull request by menren**
PR related to this issue : https://github.com/openshift/openshift-ansible/issues/916

Anyone can confirm that is working ?

### CODE REVIEW

**Comment by detiber** [comment]
I tested with the minor tweaks that I made in the PR I submitted to your fork.

Thank you for getting this together so quickly.

**Comment by menren** [comment]
@detiber I merged your PR on my branch.
Thank you

Who can check that's working ?

**Comment by detiber** [comment]
@menren passed my tests yesterday.

@twiest ptal

**Comment by twiest** [comment]
ok to test

**Comment by twiest** [comment]
merging based on comments above.

**Pull request merged**
