### PR TITLE
Normalizing groups.

### PR DESCRIPTION
**Pull request by kwoodson**

### CODE REVIEW

**Comment by kwoodson** [comment]
aos-ci-test

**Comment by kwoodson** [comment]
[merge]

**Comment by kwoodson** [comment]
@sdodson, any ideas on this failure?
```
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "elapsed": 601, 
    "failed": true, 
    "generated_timestamp": "2017-05-02 11:18:10.758363", 
    "msg": "Timeout when waiting for 172.18.4.202:22"
}
	to retry, use: --limit @/var/lib/jenkins/origin-ci-tool/e33d742ece97905d80ae8022c42b9eda26908af5/lib/python2.7/site-packages/oct/ansible/oct/playbooks/provision/aws-up.retry
```

I couldn't find a flake.  Seems like it died during provisioning.

**Comment by sdodson** [comment]
flake on https://github.com/openshift/origin/issues/13827
[merge]

**Pull request merged**
