### PR TITLE
add 3.8 templates for gluster ep and svc

### PR DESCRIPTION
**Pull request by mjudeikis**
Resolves ##6353

cc: @jarrpa @sosiouxme

### CODE REVIEW

**Comment by mjudeikis** [comment]
just to make it easier to merge it faster.
My idea for https://github.com/openshift/openshift-ansible/pull/6368  was IF we want to use `openshift.hosted.registry.storage.glusterfs.endpoints` instead of `openshift_hosted_registry_storage_glusterfs_endpoints` we need to rework some logic in how these particular values are set. And if we want this, we can do it as PR, and not a bug.

**Comment by sosiouxme** [comment]
/lgtm

crio failure looks unrelated, and not sure it's blocking but anyway:
/retest

fedora/27/atomic failure looks like an infra flake

**Comment by sosiouxme** [comment]
bot, refresh this please

**Comment by sosiouxme** [comment]
bot, retest this please

**Comment by sosiouxme** [comment]
you can ignore the crio test for now; known problem that won't block the merge.

**Comment by mjudeikis** [comment]
@jarrpa @sdodson please merge this. flakes :)

**Comment by jarrpa** [comment]
@mjudeikis Just FYI, I don't have merge rights on this repo. ;)

**Comment by sosiouxme** [comment]
patience, the merge test is under way :)

**Comment by sdodson** [comment]
Can you create them for 3.9 as well?

**Comment by sosiouxme** [comment]
`[Fail] [Conformance][Area:Networking][Feature:Router] openshift routers The HAProxy router [It] should override the route host with a custom value [Suite:openshift/conformance/parallel]` is a flake.

Added the same thing in 3.9. Don't see a need to put through another round of tests.

**Comment by sdodson** [comment]
yup yup

**Pull request merged**
