### PR TITLE
Ha port fixes

### PR DESCRIPTION
**Pull request by detiber**
Builds upon https://github.com/openshift/openshift-ansible/pull/1070 and https://github.com/openshift/openshift-ansible/pull/1117

### CODE REVIEW

**Comment by detiber** [comment]
@spinolacastro @abutcher please take a look

I still need to do quite a bit more testing to verify it works for all of the deployment types we hit:
- single master
- containerized single master
- pacemaker ha
- native ha
- containerized native ha

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
aos-ci-test

**Comment by abutcher** [comment]
@detiber looks good so far is this good to start testing with?

**Comment by detiber** [comment]
@abutcher yeah, it should be good to go...  I haven't tested pacemaker based HA or non-HA with it yet.

**Comment by detiber** [comment]
aos-ci-test

**Comment by abutcher** [comment]
aos-ci-test

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
@spinolacastro I've tested native ha, single master and @abutcher has tested against pacemaker ha. Can you verify that the additional changes I've made do not break your use case?

**Comment by spinolacastro** [comment]
LGTM, i've tested the alternative api/console  port  and everything works as expected.

**Comment by detiber** [comment]
@abutcher mind giving this another look with the squash?

**Comment by abutcher** [comment]
LGTM @brenton

**Comment by brenton** [comment]
Is this needed for 3.1.1?

**Comment by detiber** [comment]
@brenton No, it can definitely wait until after 3.1.1

**Comment by detiber** [comment]
@brenton ping any objections to merging this now?

**Pull request merged**
