### PR TITLE
[wip] Add redeploy certificates playbook for asb and tsb

### PR DESCRIPTION
**Pull request by jcpowermac**
- Modifies redeploy-certificates.yml importing playbooks
if asb or tsb installed
- Adds playbook for asb and tsb certificate recreate.

Bug 1715322 - https://bugzilla.redhat.com/show_bug.cgi?id=1715322

### CODE REVIEW

**Comment by jcpowermac** [comment]
Need to test then I will remove WIP.

**Comment by vrutkovs** [comment]
Not sure if these playbooks are required, see https://github.com/openshift/openshift-ansible/pull/9585#pullrequestreview-148124147

**Comment by jcpowermac** [comment]
@vrutkovs strange...take a look at 3.11 branch it must have been removed at some point.

**Comment by jcpowermac** [comment]
> @vrutkovs strange...take a look at 3.11 branch it must have been removed at some point.

nm...I see what you were referencing.  The service signing certificate still will need to be updated if redeploy-certificates.yml is ran since it will update `/etc/origin/master/service-signer.crt`

I am looking at your original PR to modify for 3.11.

**Comment by vrutkovs** [comment]
> The service signing certificate still will need to be updated if redeploy-certificates.yml is ran since it will update /etc/origin/master/service-signer.crt

This should be done by master controllers and happen automatically as far as I know. There was a bug where the annotation had to be changed, but I think it was fixed

**Comment by jcpowermac** [comment]
Closing in favor for https://github.com/openshift/openshift-ansible/pull/11681

**Pull request closed without merging**
