### PR TITLE
Fix loopback cluster name, context name, and user

### PR DESCRIPTION
**Pull request by detiber**
This PR fixes the loopback config for a multi-master setup, where previously it was still using the internal clustered DNS name. 

Currently blocked on the following bug: https://bugzilla.redhat.com/show_bug.cgi?id=1306011

Will need to be conditionalized to not use the loopback config unless the version includes the fix from the above BZ.

### CODE REVIEW

**Comment by detiber** [comment]
Origin PR: https://github.com/openshift/origin/pull/7197

**Comment by detiber** [comment]
@abutcher ptal

**Comment by detiber** [comment]
@aos-ci-test

**Comment by abutcher** [comment]
aos-ci-test

**Comment by abutcher** [comment]
@brenton lgtm

**Pull request merged**
