### PR TITLE
Add support for setting default node selector

### PR DESCRIPTION
**Pull request by detiber**

### CODE REVIEW

**Comment by detiber** [comment]
@sdodson @wshearn mind giving this a once over?

**Comment by sdodson** [comment]
How do you feel about actually setting the default of 'region=primary' and adding the default to all nodes that don't have labels specified?

I feel like we're half-way opinionated about how scheduling should work by deploying a scheduler config that defines region and zone but not doing anything with them in our default config.

**Comment by detiber** [comment]
@sdodson good point.  That brings us to an important discussion related to how much we want to box in the scheduler config in openshift-ansible.

I think I would rather default to be less opinionated regarding the scheduler, with maybe only adding the region/zone stuff if set by the user.

thoughts?

**Comment by sdodson** [comment]
Sorry, I'm backtracking here, if we're not setting region or zone labels on nodes then the scheduler config we're currently deploying is inconsequential. I think this PR is good to merge as is, we can be more opinionated in the installer where we'd actually have users define infra nodes, then we'd label all other nodes primary and set the default node selector.

LGTM

**Comment by detiber** [comment]
@twiest mind giving this a review?

**Comment by ryanj** [comment]
I gave this a try as well.  looks good :+1:

**Comment by twiest** [comment]
:+1:

**Pull request merged**
