### PR TITLE
Increase logging levels

### PR DESCRIPTION
**Pull request by sdodson**
trying to figure out why the master is restarting during [test]

### CODE REVIEW

**Comment by sdodson** [comment]
[test]

**Comment by sdodson** [comment]
[test]

**Comment by sdodson** [comment]
flake on https://github.com/openshift/origin/issues/14523 in https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible/287/

**Comment by michaelgugino** [comment]
Closing due to inactivity.

**Pull request closed without merging**
