### PR TITLE
Fixing invalid param to storageclass.  Allowing variable to be passed for default.

### PR DESCRIPTION
**Pull request by kwoodson**

### CODE REVIEW

**Comment by kwoodson** [comment]
@sdodson, running an install with these settings.

**Comment by kwoodson** [comment]
@sdodson, i was able to successfully deploy a cluster with these settings.

**Comment by kwoodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
Whenever you're fixing a bug can you make sure to put a link to the bug in the PR description.

**Comment by kwoodson** [comment]
@sdodson, yes, was going to run one more test before I considered it completed.

**Comment by kwoodson** [comment]
@sdodson, 2nd test completed successfully.

**Comment by sdodson** [comment]
[merge][severity:blocker]

**Comment by kwoodson** [comment]
[merge][severity:blocker]

**Pull request merged**
