### PR TITLE
fixes for node scheduleability

### PR DESCRIPTION
**Pull request by brenton**
@detiber, PTAL

### CODE REVIEW

**Comment by brenton** [comment]
I was getting ready to say that creating openshift.common.scheduleable wasn't working but I think I should have called it openshift.node.sheduleable.  Let me try that real quick.

**Comment by detiber** [comment]
@brenton, indeed...  since we set the local_facts using the node role, it would be openshift.node.scheduleable

**Comment by brenton** [comment]
I still can't get openshift.node.scheduleable to work as I would expect it.  I'll have to try tomorrow.

**Comment by brenton** [comment]
@dlbewley, if anything this PR should help you right now.

**Comment by detiber** [comment]
@brenton :+1: on the current change set though, we can address adding the scheduleable fact as a separate PR.

**Comment by dlbewley** [comment]
@brenton closer? now i see

```
PLAY [Set scheduleability] ****************************************************

GATHERING FACTS ***************************************************************
ok: [master]

TASK: [set_fact ] *************************************************************
ok: [master]

TASK: [openshift_manage_node | Handle unscheduleable node] ********************
skipping: [master]

TASK: [openshift_manage_node | Handle scheduleable node] **********************
failed: [master] => (item=ose3-node1.example.com) => {"changed": true, "cmd": ["oadm", "manage-node", "ose3-node1.example.com", "--schedulable=true"], "delta": "0:00:00.361148", "end": "2015-06-30 21:59:50.381907", "item": "ose3-node1.example.com", "rc": 1, "start": "2015-06-30 21:59:50.020759", "warnings": []}
stderr: error: No nodes found
failed: [master] => (item=ose3-node2.example.com) => {"changed": true, "cmd": ["oadm", "manage-node", "ose3-node2.example.com", "--schedulable=true"], "delta": "0:00:00.350009", "end": "2015-06-30 21:59:50.999706", "item": "ose3-node2.example.com", "rc": 1, "start": "2015-06-30 21:59:50.649697", "warnings": []}
stderr: error: No nodes found

FATAL: all hosts have already failed -- aborting
```

```
$ vagrant ssh master
Last login: Tue Jun 30 21:59:50 2015 from 10.0.2.2
[vagrant@ose3-master ~]$ oc get nodes
NAME      LABELS    STATUS
[vagrant@ose3-master ~]$ oc get all
NAME      TYPE      SOURCE
NAME      TYPE      STATUS    POD
NAME      DOCKER REPO   TAGS      UPDATED
NAME      TRIGGERS   LATEST VERSION
CONTROLLER   CONTAINER(S)   IMAGE(S)   SELECTOR   REPLICAS
NAME      HOST/PORT   PATH      SERVICE   LABELS
NAME            LABELS                                    SELECTOR   IP(S)        PORT(S)
kubernetes      component=apiserver,provider=kubernetes   <none>     172.30.0.2   443/TCP
kubernetes-ro   component=apiserver,provider=kubernetes   <none>     172.30.0.1   80/TCP
NAME      READY     REASON    RESTARTS   AGE
```

**Comment by brenton** [comment]
@dlbewley, that's pretty strange.  At that point in the playbook `oc get nodes` should definitely return the nodes.  The self registration should have already happened.  Something else if breaking for you in this case.

**Comment by brenton** [comment]
@dlbewley, I'm investigating your error by the way.  Still trying to reproduce it.

**Comment by detiber** [comment]
@dlbewley What do the logs on the node instances say?  I would expect to see some errors when attempting to self register...  `journalctl -u openshift-node -l`

**Comment by detiber** [comment]
@brenton I suspect that the node is trying to register itself differently than the generated certificate.

**Comment by brenton** [comment]
My guess is that somehow the certificates on the Master and Nodes are out of sync.

**Comment by dlbewley** [comment]
- provision

```
for n in node1 node2 master; do vagrant destroy -f $n; done
vagrant up --no-provision
vagrant provision
...
PLAY [Set scheduleability] ****************************************************

GATHERING FACTS ***************************************************************
ok: [master]

TASK: [set_fact ] *************************************************************
ok: [master]

TASK: [openshift_manage_node | Handle unscheduleable node] ********************
skipping: [master]

TASK: [openshift_manage_node | Handle scheduleable node] **********************
failed: [master] => (item=ose3-node1.example.com) => {"changed": true, "cmd": ["oadm", "manage-node", "ose3-node1.example.com", "--schedulable=true"], "delta": "0:00:00.352540", "end": "2015-07-01 16:46:05.512587", "item": "ose3-node1.example.com", "rc": 1, "start": "2015-07-01 16:46:05.160047", "warnings": []}
stderr: error: No nodes found
failed: [master] => (item=ose3-node2.example.com) => {"changed": true, "cmd": ["oadm", "manage-node", "ose3-node2.example.com", "--schedulable=true"], "delta": "0:00:00.351471", "end": "2015-07-01 16:46:06.134439", "item": "ose3-node2.example.com", "rc": 1, "start": "2015-07-01 16:46:05.782968", "warnings": []}
stderr: error: No nodes found

FATAL: all hosts have already failed -- aborting
```

- logging

```
vagrant ssh node1
[vagrant@ose3-node1 ~]$ journalctl -u openshift-node -l
No journal files were found.
```

Sorry, busy day starting up now, I will try to dig a little deeper tonight. Let me know what other obvious debugging info I can provide.

**Comment by detiber** [comment]
@dlbewley you'll probably need to run the journalctl command using sudo (or as root).

**Comment by dlbewley** [comment]
DUH! Sorry. Was running to a meeting. Yea lots more output that way. I'll try to pastebin when I get a break in meetings.

**Comment by dlbewley** [comment]
I did another test.

- [Master journalctl -f](https://gist.github.com/dlbewley/3d5ebd7be78adf9cf87d)
- [Node1 journalctl -u openshift-node -l](https://gist.github.com/dlbewley/53c0b85f8e922788a125)

And the ansible output:

```
TASK: [openshift_manage_node | Handle scheduleable node] **********************
failed: [master] => (item=ose3-node1.example.com) => {"changed": true, "cmd": ["oadm", "manage-node", "ose3-node1.example.com", "--schedulable=true"], "delta": "0:00:00.340332", "end": "2015-07-05 02:06:18.814211", "item": "ose3-node1.example.com", "rc": 1, "start": "2015-07-05 02:06:18.473879", "warnings": []}
stderr: error: No nodes found
failed: [master] => (item=ose3-node2.example.com) => {"changed": true, "cmd": ["oadm", "manage-node", "ose3-node2.example.com", "--schedulable=true"], "delta": "0:00:00.330596", "end": "2015-07-05 02:06:19.413222", "item": "ose3-node2.example.com", "rc": 1, "start": "2015-07-05 02:06:19.082626", "warnings": []}
stderr: error: No nodes found
```

**Comment by dlbewley** [comment]
Nodes seem to have broken networking. Vagrant misconfig? _Did this ever work?_

```
[vagrant@ose3-node1 node]$ ip addr ls
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:89:34:17 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic enp0s3
       valid_lft 82836sec preferred_lft 82836sec
    inet6 fe80::a00:27ff:fe89:3417/64 scope link
       valid_lft forever preferred_lft forever
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:73:38:ef brd ff:ff:ff:ff:ff:ff
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN
    link/ether 56:84:7a:fe:97:99 brd ff:ff:ff:ff:ff:ff
    inet 172.17.42.1/16 scope global docker0
       valid_lft forever preferred_lft forever
[vagrant@ose3-node1 node]$ ip route ls
default via 10.0.2.2 dev enp0s3  proto static  metric 100
10.0.2.0/24 dev enp0s3  proto kernel  scope link  src 10.0.2.15  metric 100
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.42.1
[vagrant@ose3-node1 node]$ ping -c1 10.0.2.2
PING 10.0.2.2 (10.0.2.2) 56(84) bytes of data.
64 bytes from 10.0.2.2: icmp_seq=1 ttl=63 time=0.068 ms
...
```

- dns works, but routing does now

```
[vagrant@ose3-node1 node]$ ping ose3-master.example.com
PING ose3-master.example.com (192.168.100.100) 56(84) bytes of data.
From 10.0.2.2 icmp_seq=4 Destination Net Unreachable
From 10.0.2.2 icmp_seq=5 Destination Net Unreachable
```

- log

```
Jul 05 02:49:31 ose3-node1.example.com openshift-node[15757]: I0705 02:49:31.363112   15757 kubelet.go:1615] Periodic sync
Jul 05 02:49:31 ose3-node1.example.com openshift-node[15757]: E0705 02:49:31.363187   15757 kubelet.go:1524] error getting node: node ose3-node1.example.com not found
Jul 05 02:49:31 ose3-node1.example.com openshift-node[15757]: I0705 02:49:31.363298   15757 kubelet.go:1311] Desired: []*api.Pod(nil)
Jul 05 02:49:31 ose3-node1.example.com openshift-node[15757]: I0705 02:49:31.365176   15757 kubelet.go:1343] Skipping deletes, sources aren't ready yet.
Jul 05 02:49:31 ose3-node1.example.com openshift-node[15757]: E0705 02:49:31.893145   15757 reflector.go:133] Failed to list *api.Service: Get https://ose3-master.example.com:8443/api/v1/services: dial tcp 192.168.100.100:8443: network is unreachable
```

**Comment by detiber** [comment]
@dlbewley ah, I suspect that the way the Vagrantfile is trying to configure the networking is breaking w/ VirtualBox, the only testing I've done has been using the vagrant-libvirt provider.

I don't currently have a way to test and reproduce the VirtualBox issue, if you are familiar with Vagrant and VirtualBox networking, I'd love to hear any suggestions you have for fixing the networking config.

**Comment by detiber** [comment]
@twiest This is needed to address https://github.com/openshift/openshift-ansible/issues/324 

@sdodson after this is merged, we'll want to coordinate QE testing and get a new OSE tag out there ASAP.  Do you know if we are referencing the tags in the advanced installation docs?

**Comment by sdodson** [comment]
It doesn't look like we're referencing a tag in the current versions of either origin or enterprise content. However the outdated content on customer portal references v3.0.0. I'll check with Alex on when portal will be updated, i think it was real soon now (tm).

https://docs.openshift.org/latest/admin_guide/install/advanced_install.html
https://access.redhat.com/beta/documentation/en/openshift-enterprise-30-administrator-guide/chapter-1-installation

**Comment by twiest** [comment]
:+1:

**Comment by dlbewley** [comment]
@detiber I finally figured out that NetworkManager is controlling enp0s3 and vagrant statically configures enp0s8.

unless you restart NetworkManager it will not realize enp0s8 has been configured that way and it will remove the IP when DHCP fails for that interface.

if you restart NetworkManager or reboot the node before proceeding then networking sticks as expected. i finally understand why things seemed to half work previously.

At this point I still see:

```
PLAY [Set scheduleability] ****************************************************

GATHERING FACTS ***************************************************************
ok: [master]

TASK: [set_fact ] *************************************************************
ok: [master]

TASK: [openshift_manage_node | Handle unscheduleable node] ********************
skipping: [master]

TASK: [openshift_manage_node | Handle scheduleable node] **********************
failed: [master] => (item=ose3-node1.example.com) => {"changed": true, "cmd": ["oadm", "manage-node", "ose3-node1.example.com", "--schedulable=true"], "delta": "0:00:00.359376", "end": "2015-07-07 23:28:36.050071", "item": "ose3-node1.example.com", "rc": 1, "start": "2015-07-07 23:28:35.690695", "warnings": []}
stderr: error: No nodes found
failed: [master] => (item=ose3-node2.example.com) => {"changed": true, "cmd": ["oadm", "manage-node", "ose3-node2.example.com", "--schedulable=true"], "delta": "0:00:00.354480", "end": "2015-07-07 23:28:36.698472", "item": "ose3-node2.example.com", "rc": 1, "start": "2015-07-07 23:28:36.343992", "warnings": []}
stderr: error: No nodes found

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/dlbewley/config.retry

localhost                  : ok=5    changed=0    unreachable=0    failed=0
master                     : ok=59   changed=27   unreachable=0    failed=1
node1                      : ok=46   changed=20   unreachable=0    failed=0
node2                      : ok=46   changed=20   unreachable=0    failed=0
```

Even though this works:

```
[vagrant@ose3-master ~]$ oc get nodes
NAME                     LABELS                                          STATUS
ose3-node1.example.com   kubernetes.io/hostname=ose3-node1.example.com   Ready
ose3-node2.example.com   kubernetes.io/hostname=ose3-node2.example.com   Ready
[vagrant@ose3-master ~]$ oadm manage-node ose3-node2.example.com --schedulable=true
NAME                     LABELS                                          STATUS
ose3-node2.example.com   kubernetes.io/hostname=ose3-node2.example.com   Ready
[vagrant@ose3-master ~]$ oadm manage-node ose3-node1.example.com --schedulable=true
NAME                     LABELS                                          STATUS
ose3-node1.example.com   kubernetes.io/hostname=ose3-node1.example.com   Ready
```

**Pull request merged**
