### PR TITLE
Restore missing etcd_image fact.

### LINKED ISSUE #2251: etcd_image has no attribute
After #1953 was merged Pull etcd container is failing 

```
TASK [etcd : Pull etcd container] **********************************************
fatal: [master1]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute 'etcd_image'"}
```

### PR DESCRIPTION
**Pull request by abutcher**
Fixes #2251

### CODE REVIEW

**Comment by abutcher** [comment]
aos-ci-test

**Comment by abutcher** [comment]
aos-ci-test

**Comment by abutcher** [comment]
@sdodson ptal

**Comment by sdodson** [comment]
LGTM

**Pull request merged**
