### PR TITLE
clean rpm conf for preinstalled packages

### LINKED ISSUE #8579: OCP3.7 configuration fails when OpenShift packages are preinstalled
#### Description

The byo/config.yml playbook fails when atomic-openshift-master package is preinstalled on hosts.

##### Version

```
  ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/openshift/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

  openshift-ansible-3.7.39-1-177-g012dd4b8a
```

##### Steps To Reproduce
1. Prepare the hosts as described [here](https://docs.openshift.com/container-platform/3.7/install_config/install/host_preparation.html#installing-base-packages), and pre-install as well atomic-openshift-node and atomic-openshift-master (i.e. yum install atomic-openshift-master).
2. Launch `byo/config.yml` playbook

##### Expected Results

boy/config.yml playbook completes successfully.

##### Observed Results

```
2018-05-18 14:21:40,019 p=471 u=me |  TASK [openshift_master : command] ****************************************************************************************************************************************************************************************************
2018-05-18 14:21:40,020 p=471 u=me |  task path: /home/me/openshift-ansible/roles/openshift_master/tasks/set_loopback_context.yml:9
2018-05-18 14:21:40,103 p=471 u=me |  Using module file /usr/lib/python2.7/site-packages/ansible/modules/commands/command.py
2018-05-18 14:21:40,146 p=471 u=me |  Escalation succeeded
2018-05-18 14:21:40,413 p=471 u=me |  fatal: [master-0.irozzo.cluster.local]: FAILED! => {
    "changed": true, 
    "cmd": [
        "oc", 
        "config", 
        "set-cluster", 
        "--certificate-authority=/etc/origin/master/ca.crt", 
        "--embed-certs=true", 
        "--server=https://master-0.irozzo.cluster.local:8443", 
        "master-0-irozzo-cluster-local:8443", 
        "--config=/etc/origin/master/openshift-master.kubeconfig"
    ], 
    "delta": "0:00:00.156497", 
    "end": "2018-05-18 14:21:38.727010", 
    "invocation": {
        "module_args": {
            "_raw_params": "oc config set-cluster --certificate-authority=/etc/origin/master/ca.crt --embed-certs=true --server=https://master-0.irozzo.cluster.local:8443 master-0-irozzo-cluster-local:8443 --config=/etc/origin/master/openshift-master.kubeconfig", 
            "_uses_shell": false, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "warn": true
        }
    }, 
    "msg": "non-zero return code", 
    "rc": 1, 
    "start": "2018-05-18 14:21:38.570513", 
    "stderr": "error: could not read certificate-authority data from /etc/origin/master/ca.crt: open /etc/origin/master/ca.crt: no such file or directory", 
    "stderr_lines": [
        "error: could not read certificate-authority data from /etc/origin/master/ca.crt: open /etc/origin/master/ca.crt: no such file or directory"
    ], 
    "stdout": "", 
    "stdout_lines": []
}
```

##### Additional Information

The same problem has been reported here [here](https://bugzilla.redhat.com/show_bug.cgi?id=1498592), but I do not agree with the conclusion that it is not a bug and just a bad image. I think that it should be possible to use images with pre-installed packages as it was the case for previous versions.

### PR DESCRIPTION
**Pull request by jkhelil**
fixes #8579

### CODE REVIEW

**Comment by vrutkovs** [comment]
Does this replace #8677?

**Comment by vrutkovs** [comment]
bot, test pull request

**Comment by jkhelil** [comment]
not working

**Pull request closed without merging**
