### PR TITLE
Bug 1557909 - Remove openshift_management beta acknowledgement

### PR DESCRIPTION
**Pull request by mtnbikenc**
CFME-4.6 is GA and is fully supported

Bug https://bugzilla.redhat.com/show_bug.cgi?id=1557909

### CODE REVIEW

**Comment by mtnbikenc** [comment]
Tox tests were failing due to an old version of pyOpenSSL.

**Comment by mtnbikenc** [comment]
Tox fixes: https://github.com/openshift/openshift-ansible/pull/7571

**Comment by sdodson** [comment]
bot, retest this please

**Pull request merged**
