### PR TITLE
Bug 1826213: Update version check to support semver change

### PR DESCRIPTION
**Pull request by mtnbikenc**

### CODE REVIEW

**Comment by mtnbikenc** [comment]
@sdodson Confirmed this change on a local dev cluster install for 4.5.

Versions generated:
```
"name": ["cri-o-1.18.*", "openshift-clients-4.5*", "openshift-hyperkube-4.5*"]
```

Installed:
```
  cri-o.x86_64 0:1.18.0-3.dev.rhaos4.5.git2cef6c3.el7                           
  openshift-clients.x86_64 0:4.5.0-202004202137.git.1.7e76c39.el7               
  openshift-hyperkube.x86_64 0:4.5.0-202004211317.git.1.a70523b.el7             
```

**Comment by sdodson** [comment]
/lgtm
/hold
I think this change is good regardless of whether the build versioning changes as was proposed and reverted. Feel free to clear the hold or close the PR, up to you.

**Comment by mtnbikenc** [comment]
Pushed new commit for rebase.

**Comment by mtnbikenc** [comment]
Moving forward with this change to support flexibility in build version compatibility.
/hold cancel

**Pull request merged**
