### PR TITLE
Merge of 4.1 development

### PR DESCRIPTION
**Pull request by mtnbikenc**
Merge devel-40 branch to master

### CODE REVIEW

**Comment by mtnbikenc** [comment]
Needs https://github.com/openshift/machine-config-operator/pull/483

**Comment by mtnbikenc** [comment]
Updated with #11368.

**Comment by vrutkovs** [comment]
https://github.com/openshift/machine-config-operator/pull/483 merged

/retest

**Comment by vrutkovs** [comment]
https://github.com/openshift/machine-config-operator/pull/549 merged
/retest

**Comment by vrutkovs** [comment]
VMs could not be reached before provisioning

/retest

**Comment by vrutkovs** [comment]
"waiting for Kubernetes API: context deadline exceeded"
/retest

**Comment by vrutkovs** [comment]
https://github.com/openshift/machine-config-operator/pull/564 should fix the remaining issue

/hold
to avoid retests for now

**Comment by vrutkovs** [comment]
https://github.com/openshift/machine-config-operator/pull/564 merged
/hold cancel
/retest

**Comment by vrutkovs** [comment]
`"failed to initialize the cluster: timed out waiting for the condition"`
/retest

**Comment by jstuever** [comment]
/retest
```
Failing tests:

[Conformance][Area:Networking][Feature:Router] The HAProxy router should serve the correct routes when scoped to a single namespace and label set [Suite:openshift/conformance/parallel/minimal]
[Feature:DeploymentConfig] deploymentconfigs rolled back [Conformance] should rollback to an older deployment [Suite:openshift/conformance/parallel/minimal]
[Feature:DeploymentConfig] deploymentconfigs with test deployments [Conformance] should run a deployment to completion and then scale to zero [Suite:openshift/conformance/parallel/minimal]
[Feature:Prometheus][Conformance] Prometheus when installed on the cluster should start and expose a secured proxy and unsecured metrics [Suite:openshift/conformance/parallel/minimal]
[sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should provide basic identity [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-cli] Kubectl client [k8s.io] Update Demo should do a rolling update of a replication controller  [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s]
```

**Pull request merged**
