### PR TITLE
Add kube service ipaddress to no_proxy list

### PR DESCRIPTION
**Pull request by sdodson**
Computed as the first ip address in the portal_net

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1511870

### CODE REVIEW

**Comment by michaelgugino** [comment]
@sdodson Let's merge this.  I was planning on converting the no_proxy code into a filter, there's not a great way to do this in ansible.

**Comment by ganhuang** [comment]
@sdodson Did a quick test, it would failed as following:

```
FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to host-8-241-70.host.centralci.eng.rdu2.redhat.com closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_youkya/ansible_module_openshift_facts.py\", line 2436, in <module>\r\n    main()\r\n  File \"/tmp/ansible_youkya/ansible_module_openshift_facts.py\", line 2423, in main\r\n    protected_facts_to_overwrite)\r\n  File \"/tmp/ansible_youkya/ansible_module_openshift_facts.py\", line 1796, in __init__\r\n    protected_facts_to_overwrite)\r\n  File \"/tmp/ansible_youkya/ansible_module_openshift_facts.py\", line 1857, in generate_facts\r\n    facts = set_proxy_facts(facts)\r\n  File \"/tmp/ansible_youkya/ansible_module_openshift_facts.py\", line 1522, in set_proxy_facts\r\n    common['no_proxy'] = ','.join(sort_unique(common['no_proxy']))\r\nTypeError: sequence item 0: expected string, IPv4Address found\r\n", "msg": "MODULE FAILURE", "rc": 0}
```

```
>>> portal_net="172.30.0.0/16"
>>> kube_svc_ip = ipaddress.ip_network(unicode(portal_net))[1]
>>> type(kube_svc_ip)
<class 'ipaddress.IPv4Address'>
>>> kube_svc_ip
IPv4Address(u'172.30.0.1')
```

**Comment by sdodson** [comment]
Rebased and pulled in https://github.com/sdodson/openshift-ansible/pull/5

**Comment by sdodson** [comment]
> What about installing python-ipaddress if distro != Fedora? Was that merged in another patch?

Nope, lost that in the rebase, updated to add it back in.

**Pull request merged**
