### PR TITLE
Updating size suffix for metrics in role

### PR DESCRIPTION
**Pull request by ewolinetz**
Small update to match the examples in the docs for https://github.com/openshift/openshift-ansible/issues/4112

### CODE REVIEW

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
registry.ops.*.* had v3.6.67 but the puddle didn't, rebuilding the puddle to match.

CC @jupierce

**Comment by jupierce** [comment]
Sorry -- still working on getting a 3.6 build out.

**Comment by ewolinetz** [comment]
this is only a tiny docs change, so we shouldn't have to wait on getting a puddle built for this PR specifically

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
[merge]

**Pull request merged**
