### PR TITLE
Use an ASB image tag appropriate for the version of Origin

### PR DESCRIPTION
**Pull request by jmontleon**

### CODE REVIEW

**Comment by jmontleon** [comment]
@fabianvf @sdodson I don't know if you have a suggestion or a better way to do this. We have upstream tags 'v3.9', 'v3.10', 'v3.11', but I believe the openshift_image_tag can be v3.10.45-1, for example, and this would not match anything in our upstream repo.

This also needs to be cherry-picked back to previous versions, as v3.10 and v3.9 will not work with the latest image. I believe there's a cherry-pick robot, but unsure if I need to interact with it via labels, etc?

**Comment by jmontleon** [comment]
@vrutkovs For origin the version will always be in the format v3.10 and not something like, for example v3.10.45-1?

**Comment by vrutkovs** [comment]
@jmontleon it would use `openshift_image_tag` same as in OCP, but in Origin's case its a user misconfiguration

**Comment by vrutkovs** [comment]
Master branch is closed! A major refactor is ongoing in devel-40. Changes for 3.x should be made directly to the latest release branch they're relevant to and backported from there.

**Pull request closed without merging**
