### PR TITLE
set openshift_release if openshift_pkg_version is set

### PR DESCRIPTION
**Pull request by ingvagabund**
Prerequisite for requiring the `openshift_release` to be set

### CODE REVIEW

**Comment by ingvagabund** [comment]
@michaelgugino @sdodson just noticed we don't check if the `openshift_pkg_version` comply to a regex so it can be set to any value. E.g. `openshift_pkg_version = 3.6` which will result in `openshift_release` set to `.6`. Which is basically the same as it would be set by a user. We don't even check the `openshift_release` is in a proper form.

**Comment by ingvagabund** [comment]
Failed on ``[Conformance][templates] templateservicebroker end-to-end test should pass an end-to-end test [Suite:openshift/conformance/parallel]``

**Comment by michaelgugino** [comment]
I don't think we need to do this.  Our example inventory says:
```
# openshift_release must be specified. 
```

I think we should stick to that.

**Comment by ingvagabund** [comment]
> I don't think we need to do this.  Our example inventory says:
> ```
> # openshift_release must be specified. 
> ```
> 
> I think we should stick to that.

From a certain wicked point of view it does not say the `openshift_release` must be specified directly in the inventory file. Anything that can set the variable could be considered valid. I agree that the `openshift_pkg_version` is not an inventory variable that could watch a footbal game from the same VIP seats as the `openshift_release`. However, if it is set, it already caries an information about intended version of the OCP deployment/upgrade. Don't you think?

**Comment by michaelgugino** [comment]
I view the variables as completely independent.  I think the less 'magic transformation' to derive one variable from another, the better.

openshift_release = What major version of openshift do you want? X.Y

openshift_pkg_version = Inside of that release, do you want a specific package version?  IE, X.Y.Z.

Personally, I don't think openshift_pkg_version should be user accessible.  We should let openshift_release contain the entire version level, and X.Y should mean any package level in that version, or match whatever is on the master.

I don't think the relationship should go the other direction, which is deriving openshift_release from openshift_pkg_version.  I think openshift_release should be our one source of truth.

**Comment by ingvagabund** [comment]
> openshift_release = What major version of openshift do you want? X.Y
> 
> openshift_pkg_version = Inside of that release, do you want a specific package version? IE, X.Y.Z.

Expected assumption, not necessarily valid. If the `openshift_pkg_version` is set by a user, no check is perform to verify the assumption holds.

> Personally, I don't think openshift_pkg_version should be user accessible. We should let openshift_release contain the entire version level, and X.Y should mean any package level in that version, or match whatever is on the master.

It is and it needs to be in cases where a user wants a different version of atomic-openshift-* rpms and docker images. Sometimes versions of docker images and rpms diverge (e.g. rpms are ahead of docker images). So there is no other way than to set both `openshift_pkg_version` and `openshift_image_tag`. I can think of the following combinations:

* both `openshift_pkg_version` and `openshift_image_tag` are set: here we are pretty sure what version of OCP is required (there is only one valid value for `openshift_release`)
* only `openshift_pkg_version` is set in rpm based deployment: (there is only one valid value for `openshift_release`)
* only `openshift_pkg_version` is set in containerized deployment:
  * either ignore `openshift_pkg_version` and set `openshift_image_tag` to the latest
  * or, construct a tag that has the same version as `openshift_pkg_version` does

  In both cases, the is only one valid value for `openshift_release`.
* only `openshift_image_tag` is set: if the tag is set to "3.6.1", the `openshift_pkg_version` can be 3.6.1.3-???, 3.6.1.4-???, 3.6.1.?-??? so it does not make sense to try to construct the `openshift_pkg_version` (it needs to be detected from the available rpms), followed by construction of  `openshift_release`.

So for me all three vars (`openshift_pkg_version`, `openshift_release` and `openshift_image_tag`) are valid ways how to set the OCP version. I understand the importance of the `openshift_release`. However, if `openshift_pkg_version` can be set, it no longer make much sense to set `openshift_release` cause there is only one valid value for it then if you assumption is about to hold.

**Comment by sdodson** [comment]
I think given that `openshift_release` is cross cutting across rpm and containerized installations I think that we need to take a firm stance that it's required. I can help you update the CI jobs to ensure this is set.

**Pull request closed without merging**
