### PR TITLE
Use IP4_NAMESERVERS rather than DHCP4_DOMAIN_NAME_SERVERS

### LINKED ISSUE #1882: No upstream DNS for dnsmasq for static IP configuration
In the NetworkManager dispatcher 99-origin-dns.sh there is an issue with configuring upstream DNS resolvers in case of static IP configuration.

If the IP address and DNS servers are configured statically, the variable DHCP4_DOMAIN_NAME_SERVERS is empty and no upstream servers are stored in /etc/dnsmasq.d/origin-upstream-dns.conf as upstream DNS resolvers. This leads to no DNS name resolution for statically configured network settings.

I've created a patch for the dispatcher that looks also for the DNS servers in the variable IP4_NAMESERVERS. With this change, DNS resolution is working in both cases - DHCP configured network settings and static configuration.

### PR DESCRIPTION
**Pull request by sdodson**
- Switches to IP4_NAMESERVERS
- Does not update resolv.conf if IP4_NAMESERVERS is undefined as it's not safe to do so

Fixes #1882

### CODE REVIEW

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by detiber** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Pull request merged**
