### PR TITLE
Remove lots of dead code in tests

### PR DESCRIPTION
**Pull request by rhcarvalho**
This is more clean up of test code like #3563 was.

### CODE REVIEW

**Comment by rhcarvalho** [comment]
aos-ci-test

**Comment by detiber** [comment]
@rhcarvalho looks like a rebase is needed, otherwise lgtm

**Comment by rhcarvalho** [comment]
> @rhcarvalho looks like a rebase is needed, otherwise lgtm

Oh yeah, #3535 just merged...

**Comment by rhcarvalho** [comment]
Updated, @sdodson could you please merge this on green from Travis?

**Pull request merged**
