### PR TITLE
[3.8] Playbook Consolidation - byo/config.yml

### PR DESCRIPTION
**Pull request by mtnbikenc**
Backports https://github.com/openshift/openshift-ansible/pull/6361

### CODE REVIEW

**Comment by sdodson** [comment]
We're working to get 3.8 deployed to the online clusters with what's currently in release-3.8 then I had intended to merge all changes from master back into release-3.8. Should we just wait for that or is this a critical change that can't wait for that?

**Comment by mtnbikenc** [comment]
This PR needs https://github.com/openshift/openshift-ansible/pull/6440 merged.

**Comment by mtnbikenc** [comment]
@sdodson Not all of the playbook consolidation PRs were on 3.8 and I was gettings issues from QE on their testing.  Fine with me to wait, just keep in mind not all the playbooks are rearranged.

**Comment by mtnbikenc** [comment]
Closing in favor of https://github.com/openshift/openshift-ansible/pull/6452

**Pull request closed without merging**
