### PR TITLE
Fix backward compat for osm_default_subdomain

### PR DESCRIPTION
**Pull request by detiber**

### CODE REVIEW

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
@sdodson ptal

**Comment by detiber** [comment]
@abutcher ptal

**Comment by detiber** [comment]
aos-ci-test

**Comment by sdodson** [comment]
Sorry I meant to mention LGTM.

**Pull request merged**
