### PR TITLE
Regex anchors changed to match protocol start and ports.

### PR DESCRIPTION
**Pull request by kwoodson**
This is a follow up fix for this pr: https://github.com/openshift/openshift-ansible/pull/5264

Fix for this bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1482903

### CODE REVIEW

**Comment by kwoodson** [comment]
I'm going to run through a cluster provision using this PR to ensure my `corsAllowedOrigins` look correct and behave as well.

**Comment by liggitt** [comment]
LGTM, pending test run

**Comment by ashcrow** [comment]
Unrelated to this change:

```
[ERROR] Can not determine install and upgrade version for the `atomic-openshift-utils` package
```

**Comment by ashcrow** [comment]
Atomic fails on template service broker:

```
    "stderr": "Error: unknown shorthand flag: 'f' in -f\n\n\nUsage:\n  oc auth [options]\n\nAvailable Commands:\n  can-i       Check whether an action is allowed\n\nUse \"oc <command> --help\" for more information about a given command.\nUse \"oc options\" for a list of global command-line options (applies to all commands).", 
    "stderr_lines": [
        "Error: unknown shorthand flag: 'f' in -f", 
```

**Comment by sdodson** [comment]
Upgrade job is assumed to have been fixed now.
/retest

**Comment by kwoodson** [comment]
Was able to successfully go to the console.

```
corsAllowedOrigins:
- (?i)//127\.0\.0\.1(:|\z)
- (?i)//localhost(:|\z)
- (?i)//172\.31\.52\.3(:|\z)
- (?i)//kubernetes\.default(:|\z)
- (?i)//api\.<clusterid>\.openshift\.com(:|\z)
- (?i)//kubernetes\.default\.svc\.cluster\.local(:|\z)
- (?i)//kubernetes(:|\z)
- (?i)//openshift\.default(:|\z)
- (?i)//ip\-172\-31\-52\-3\.us\-east\-2\.compute\.internal(:|\z)
- (?i)//openshift\.default\.svc(:|\z)
- (?i)//172\.30\.0\.1(:|\z)
- (?i)//openshift\.default\.svc\.cluster\.local(:|\z)
- (?i)//kubernetes\.default\.svc(:|\z)
- (?i)//openshift(:|\z)
- (?i)//console\.<clusterid>\.openshift\.com(:|\z)
- (?i)//api\.<clusterid>\.openshift\.com(:|\z)
```
I did not attempt the port test case but this was successful.  I removed a few of the other IPs or hostnames with direct instance reference.

**Pull request merged**
