### PR TITLE
Set AWS_CA_BUNDLE via openshift_cloudprovider_aws_ca_bundle

### PR DESCRIPTION
**Pull request by sdodson**
Copies the local file to /etc/origin/{master,node}/aws_ca_bundle.crt
as appropriate.

### CODE REVIEW

**Comment by cuppett** [comment]
Lgtm.

**Comment by cuppett** [comment]
@ampsight does this cover your needs for configuring the low side bundle?

**Comment by mbach04** [comment]
> @ampsight does this cover your needs for configuring the low side bundle?

@cuppett I've been knees deep with the auto-scaler, but this coming week I should be able to dig into this and report back on the likelihood of success in disconnected regions.

**Pull request merged**
