### PR TITLE
oc_secret: allow use of force for secret type

### PR DESCRIPTION
**Pull request by jarrpa**
Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>

### CODE REVIEW

**Comment by sdodson** [comment]
Looks like the tests need to be updated with the new parameter.

**Comment by ashcrow** [comment]
@jarrpa you can run the tests locally if you'd like to verify via:

## Python 2
```
tox -e py27-unit
```

## Python 3
```
tox -e py35-unit 
```

**Comment by jarrpa** [comment]
I can't run them, I get the following errors:

```
py27-unit runtests: commands[1] | pytest
Traceback (most recent call last):
  File "/home/jrivera/projects/github/openshift/openshift-ansible/.tox/py27-unit/lib/python2.7/site-packages/_pytest/config.py", line 362, in _importconftest
    mod = conftestpath.pyimport()
  File "/home/jrivera/projects/github/openshift/openshift-ansible/.tox/py27-unit/lib/python2.7/site-packages/py/_path/local.py", line 680, in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
ImportMismatchError: ('conftest', '/home/jrivera/projects/github/openshift-ansible/conftest.py', local('/home/jrivera/projects/github/openshift/openshift-ansible/conftest.py'))
ERROR: could not load /home/jrivera/projects/github/openshift/openshift-ansible/conftest.py

ERROR: InvocationError: '/home/jrivera/projects/github/openshift/openshift-ansible/.tox/py27-unit/bin/pytest'

py35-unit runtests: commands[1] | pytest
Traceback (most recent call last):
  File "/home/jrivera/projects/github/openshift/openshift-ansible/.tox/py35-unit/lib/python3.5/site-packages/_pytest/config.py", line 325, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/home/jrivera/projects/github/openshift/openshift-ansible')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/jrivera/projects/github/openshift/openshift-ansible/.tox/py35-unit/lib/python3.5/site-packages/_pytest/config.py", line 356, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/home/jrivera/projects/github/openshift/openshift-ansible/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/jrivera/projects/github/openshift/openshift-ansible/.tox/py35-unit/lib/python3.5/site-packages/_pytest/config.py", line 362, in _importconftest
    mod = conftestpath.pyimport()
  File "/home/jrivera/projects/github/openshift/openshift-ansible/.tox/py35-unit/lib/python3.5/site-packages/py/_path/local.py", line 680, in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
py._path.local.LocalPath.ImportMismatchError: ('conftest', '/home/jrivera/projects/github/openshift-ansible/conftest.py', local('/home/jrivera/projects/github/openshift/openshift-ansible/conftest.py'))
ERROR: could not load /home/jrivera/projects/github/openshift/openshift-ansible/conftest.py

ERROR: InvocationError: '/home/jrivera/projects/github/openshift/openshift-ansible/.tox/py35-unit/bin/pytest'
```

**Comment by jarrpa** [comment]
Updated to fix the test.

**Comment by sdodson** [comment]
[merge]

**Comment by ashcrow** [comment]
```
[ERROR] Status 'aos-ci-jenkins/OS_3.6_NOT_containerized' is required but was not found on this pull request.
[ERROR] Status 'aos-ci-jenkins/OS_3.6_NOT_containerized_e2e_tests' is required but was not found on this pull request.
[ERROR] Status 'aos-ci-jenkins/OS_3.6_containerized' is required but was not found on this pull request.
[ERROR] Status 'aos-ci-jenkins/OS_3.6_containerized_e2e_tests' is required but was not found on this pull request.
[ERROR] Status 'aos-ci-jenkins/OS_3.5_NOT_containerized' is required but was not found on this pull request.
[ERROR] Status 'aos-ci-jenkins/OS_3.5_NOT_containerized_e2e_tests' is required but was not found on this pull request.
[ERROR] Status 'aos-ci-jenkins/OS_3.5_containerized' is required but was not found on this pull request.
[ERROR] Status 'aos-ci-jenkins/OS_3.5_containerized_e2e_tests' is required but was not found on this pull request.
```

**Comment by ashcrow** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Pull request merged**
