### PR TITLE
Remove RBAC console template

### PR DESCRIPTION
**Pull request by spadgett**
The console is changing to discover if the template service broker is
running by looking at the service classes on the client. This means the
console no longer needs the RBAC template. It also no longer needs to
manually trigger a rollout after the template service broker is
installed or removed.

Requires:

https://github.com/openshift/origin-web-console-server/pull/31
https://github.com/openshift/origin-web-console/pull/2800
https://github.com/openshift/origin-web-catalog/pull/642

Corresponding origin PR:

https://github.com/openshift/origin/pull/18580

This will fail tests until the origin-web-console image is updated with the changes in the origin-web-console-server PR.

/assign @sdodson 
@deads2k cc

### CODE REVIEW

**Comment by spadgett** [comment]
The origin-web-console-server and origin changes have merged. @sdodson PTAL

/retest
/hold cancel

**Comment by sdodson** [comment]
/lgtm
Is there any clean up to do in environments that had the old code applied?

**Comment by sdodson** [comment]
Not obvious to me why the console failed in that job, seems like it may've been crashlooping.

**Comment by spadgett** [comment]
> Is there any clean up to do in environments that had the old code applied?

Ideally you would remove the role binding and cluster role we were previously creating, although they won't break anything if they're there. It just gives the console a little more access than it needs (read permission on cluster service brokers).

> Not obvious to me why the console failed in that job, seems like it may've been crashlooping.

Yeah, me either. Is it possibly using an old origin-web-console image?

#7132 would help :/

**Comment by spadgett** [comment]
Rebased to pick up #7132 for debugging the test failures

**Comment by spadgett** [comment]
@sdodson The containerized tests are failing because they're using an old image: `docker.io/openshift/origin-web-console:v3.9.0-alpha.4`

**Comment by sdodson** [comment]
Ok, so CI is setting the image tag for containerized installs, it'd be fixed if we overrided to 'latest' tag in CI or we tag a new image. @smarterclayton do you know when we'll next tag next?

**Comment by spadgett** [comment]
On the bright side, what we log now on console failures is extremely useful

**Comment by spadgett** [comment]
@sdodson We've switching to pushing to a v3.9 tag, so I don't think there will be any more v3.9.0-alpha tags

**Comment by spadgett** [comment]
@sdodson Following up on this... It seems to me the tests should be using the v3.9 tag if possible.

**Comment by sdodson** [comment]
@spadgett Got the CI changes that force image tag of 'latest' on master branch PR CI jobs, can you rebase?

**Comment by sdodson** [comment]
https://github.com/openshift/aos-cd-jobs/commits/master

**Comment by sdodson** [comment]
https://github.com/openshift/aos-cd-jobs/pull/1147

**Comment by spadgett** [comment]
@sdodson thanks, rebased

**Comment by spadgett** [comment]
@sdodson Can you tag this for merge again? It lost the tag when I rebased.

**Pull request merged**
