### PR TITLE
router/registry: look for the oc executable in /usr/local/bin and ~/bin

### PR DESCRIPTION
**Pull request by giuseppe**
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1463131

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by sdodson** [comment]
`{{ openshift.common.client_binary }}` could probably be used.

**Comment by giuseppe** [comment]
yes thanks, that works.

I had to do the same change for the registry as I encountered the same issue while installing to RHELAH.

**Comment by giuseppe** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Comment by sdodson** [comment]
None of those failures are related to this change, merging.

**Pull request merged**
