### PR TITLE
Remove several unused vars

### PR DESCRIPTION
**Pull request by vrutkovs**
This removes vars from `roles/*/defaults/main.yml` which are not used in tasks anymore and simplifies some vars

### CODE REVIEW

**Comment by vrutkovs** [comment]
bot, retest this please

**Comment by smarterclayton** [comment]
This failed consistently on GCP (has never passed).  Why did we merge it?

**Comment by smarterclayton** [comment]
Please revert everything in this PR to get the GCP jobs passing again (or do selective reverts if you think you know why this is broken).

Please do not merge if you have never seen the GCP jobs pass.

**Comment by vrutkovs** [comment]
>This failed consistently on GCP (has never passed).  Why did we merge it?

The install finished correctly multiple times and failed on e2e test due to flakes. It did break one usecase - haproxy loadbalancer setup, fixed in #9499 - but afaik GCP tests don't set it up.

**Pull request merged**
