### PR TITLE
[1.5] Backport py3 support fixes

### LINKED ISSUE #4815: openshift_facts module inside openshift_facts role causes runtime error on python3 host
#### Description

The module `openshift_facts` inside the `openshift_facts` role causes a python runtime error in python3 mode, which is now required for a Fedora installation.

##### Version

* Ansible version per `ansible --version`

```
ansible 2.3.1.0
  config file = /root/openshift-ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

* The output of `git describe` -> `openshift-ansible-3.5.101-1`

##### Steps To Reproduce
1. `ansible-playbook playbooks/byo/config.yml -i path/to/inventory` against Fedora 26 hosts using Python3 

##### Expected Results

The playbook to not error.

##### Observed Results

```
TASK [openshift_facts : Gather Cluster facts and set is_containerized if needed] **************************************
task path: /root/openshift-ansible/roles/openshift_facts/tasks/main.yml:71
Using module file /root/openshift-ansible/roles/openshift_facts/library/openshift_facts.py
<osbs-master01.stg.phx2.fedoraproject.org> ESTABLISH SSH CONNECTION FOR USER: root
<osbs-master01.stg.phx2.fedoraproject.org> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/dbbd3b6aef osbs-master01.stg.phx2.fedoraproject.org '/bin/sh -c '"'"'/usr/bin/python3 && sleep 0'"'"''
Using module file /root/openshift-ansible/roles/openshift_facts/library/openshift_facts.py
<osbs-node01.stg.phx2.fedoraproject.org> ESTABLISH SSH CONNECTION FOR USER: root
<osbs-node01.stg.phx2.fedoraproject.org> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/f265a6ea1f osbs-node01.stg.phx2.fedoraproject.org '/bin/sh -c '"'"'/usr/bin/python3 && sleep 0'"'"''
Using module file /root/openshift-ansible/roles/openshift_facts/library/openshift_facts.py
<osbs-node02.stg.phx2.fedoraproject.org> ESTABLISH SSH CONNECTION FOR USER: root
<osbs-node02.stg.phx2.fedoraproject.org> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/a893e1f1b4 osbs-node02.stg.phx2.fedoraproject.org '/bin/sh -c '"'"'/usr/bin/python3 && sleep 0'"'"''
<osbs-master01.stg.phx2.fedoraproject.org> (1, '', 'Traceback (most recent call last):\n  File "/tmp/ansible_47dtpzw8/ansible_module_openshift_facts.py", line 2491, in <module>\n    main()\n  File "/tmp/ansible_47dtpzw8/ansible_module_openshift_facts.py", line 2478, in main\n    protected_facts_to_overwrite)\n  File "/tmp/ansible_47dtpzw8/ansible_module_openshift_facts.py", line 1899, in __init__\n    for (k, v) in self.system_facts.items():\nRuntimeError: dictionary changed size during iteration\n')
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_47dtpzw8/ansible_module_openshift_facts.py", line 2491, in <module>
    main()
  File "/tmp/ansible_47dtpzw8/ansible_module_openshift_facts.py", line 2478, in main
    protected_facts_to_overwrite)
  File "/tmp/ansible_47dtpzw8/ansible_module_openshift_facts.py", line 1899, in __init__
    for (k, v) in self.system_facts.items():
RuntimeError: dictionary changed size during iteration

fatal: [osbs-master01.stg.phx2.fedoraproject.org]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_47dtpzw8/ansible_module_openshift_facts.py\", line 2491, in <module>\n    main()\n  File \"/tmp/ansible_47dtpzw8/ansible_module_openshift_facts.py\", line 2478, in main\n    protected_facts_to_overwrite)\n  File \"/tmp/ansible_47dtpzw8/ansible_module_openshift_facts.py\", line 1899, in __init__\n    for (k, v) in self.system_facts.items():\nRuntimeError: dictionary changed size during iteration\n",
    "module_stdout": "",
    "rc": 1
}

MSG:

MODULE FAILURE

<osbs-node01.stg.phx2.fedoraproject.org> (1, '', 'Traceback (most recent call last):\n  File "/tmp/ansible_8w3_0w4b/ansible_module_openshift_facts.py", line 2491, in <module>\n    main()\n  File "/tmp/ansible_8w3_0w4b/ansible_module_openshift_facts.py", line 2478, in main\n    protected_facts_to_overwrite)\n  File "/tmp/ansible_8w3_0w4b/ansible_module_openshift_facts.py", line 1899, in __init__\n    for (k, v) in self.system_facts.items():\nRuntimeError: dictionary changed size during iteration\n')
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_8w3_0w4b/ansible_module_openshift_facts.py", line 2491, in <module>
    main()
  File "/tmp/ansible_8w3_0w4b/ansible_module_openshift_facts.py", line 2478, in main
    protected_facts_to_overwrite)
  File "/tmp/ansible_8w3_0w4b/ansible_module_openshift_facts.py", line 1899, in __init__
    for (k, v) in self.system_facts.items():
RuntimeError: dictionary changed size during iteration

fatal: [osbs-node01.stg.phx2.fedoraproject.org]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_8w3_0w4b/ansible_module_openshift_facts.py\", line 2491, in <module>\n    main()\n  File \"/tmp/ansible_8w3_0w4b/ansible_module_openshift_facts.py\", line 2478, in main\n    protected_facts_to_overwrite)\n  File \"/tmp/ansible_8w3_0w4b/ansible_module_openshift_facts.py\", line 1899, in __init__\n    for (k, v) in self.system_facts.items():\nRuntimeError: dictionary changed size during iteration\n",
    "module_stdout": "",
    "rc": 1
}

MSG:

MODULE FAILURE

<osbs-node02.stg.phx2.fedoraproject.org> (1, '', 'Traceback (most recent call last):\n  File "/tmp/ansible_p7vpddi8/ansible_module_openshift_facts.py", line 2491, in <module>\n    main()\n  File "/tmp/ansible_p7vpddi8/ansible_module_openshift_facts.py", line 2478, in main\n    protected_facts_to_overwrite)\n  File "/tmp/ansible_p7vpddi8/ansible_module_openshift_facts.py", line 1899, in __init__\n    for (k, v) in self.system_facts.items():\nRuntimeError: dictionary changed size during iteration\n')
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_p7vpddi8/ansible_module_openshift_facts.py", line 2491, in <module>
    main()
  File "/tmp/ansible_p7vpddi8/ansible_module_openshift_facts.py", line 2478, in main
    protected_facts_to_overwrite)
  File "/tmp/ansible_p7vpddi8/ansible_module_openshift_facts.py", line 1899, in __init__
    for (k, v) in self.system_facts.items():
RuntimeError: dictionary changed size during iteration

fatal: [osbs-node02.stg.phx2.fedoraproject.org]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_p7vpddi8/ansible_module_openshift_facts.py\", line 2491, in <module>\n    main()\n  File \"/tmp/ansible_p7vpddi8/ansible_module_openshift_facts.py\", line 2478, in main\n    protected_facts_to_overwrite)\n  File \"/tmp/ansible_p7vpddi8/ansible_module_openshift_facts.py\", line 1899, in __init__\n    for (k, v) in self.system_facts.items():\nRuntimeError: dictionary changed size during iteration\n",
    "module_stdout": "",
    "rc": 1
}

MSG:

MODULE FAILURE

```

##### Additional Information

```
NAME=Fedora
VERSION="26 (Twenty Six)"
ID=fedora
VERSION_ID=26
PRETTY_NAME="Fedora 26 (Twenty Six)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:26"
HOME_URL="https://fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=26
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=26
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
```

### PR DESCRIPTION
**Pull request by abutcher**
Backports #4062
Fixes #4815

### CODE REVIEW

**Comment by abutcher** [comment]
@maxamillion I think backporting these commits may fix your issue. Lmk if you're able to test it out, thanks!

**Comment by ashcrow** [comment]
@abutcher Is https://github.com/openshift/openshift-ansible/pull/4062#issuecomment-299644309 still an issue?

**Comment by abutcher** [comment]
@ashcrow I think that subsequent issue was unrelated to the fixes in #4062 but it may still be a problem

**Comment by maxamillion** [comment]
@abutcher it does fix the issue. I had applied `fb16c946f7ec37c615e976faadf726151b75d386` to my local git clone on top of `openshift-ansible-3.5.101-1` and it worked. Thanks again.

**Comment by sdodson** [comment]
aos-ci-test

**Comment by thijsschnitger** [comment]
Since this merge, creating a multi-master cluster using RHEL7 on AWS fails for me with the following error: 

```
TASK [openshift_master : Start and enable master api all masters] **************
Friday 21 July 2017  11:01:22 +0000 (0:00:15.155)       0:10:37.362 ***********
skipping: [master01]
FAILED - RETRYING: TASK: openshift_master : Start and enable master api all masters (1 retries left).
FAILED - RETRYING: TASK: openshift_master : Start and enable master api all masters (1 retries left).
fatal: [master02]: FAILED! => {"attempts": 1, "changed": false, "failed": true, "msg": "Unable to start service atomic-openshift-master-api: Job for atomic-openshift-master-api.service failed because the control process exited with error code. See \"systemctl status atomic-openshift-master-api.service\" and \"journalctl -xe\" for details.\n"}
fatal: [master03]: FAILED! => {"attempts": 1, "changed": false, "failed": true, "msg": "Unable to start service atomic-openshift-master-api: Job for atomic-openshift-master-api.service failed because the control process exited with error code. See \"systemctl status atomic-openshift-master-api.service\" and \"journalctl -xe\" for details.\n"}
```

Relevant piece from journalctl on one of the masters:

```
-- Unit atomic-openshift-master-api.service has begun starting up.
Jul 21 12:11:18 base atomic-openshift-master-api[11617]: I0721 12:11:18.654671   11617 start_api.go:104] Using a listen address override "0.0.0.0:443"
Jul 21 12:11:18 base atomic-openshift-master-api[11617]: W0721 12:11:18.656074   11617 start_master.go:291] Warning: auditConfig.auditFilePath: Required value: audit can now be logged to a separate file, master start will continue.
Jul 21 12:11:18 base atomic-openshift-master-api[11617]: Invalid MasterConfig /etc/origin/master/master-config.yaml
Jul 21 12:11:18 base atomic-openshift-master-api[11617]: assetConfig.servingInfo.certFile: Invalid value: "/etc/origin/master/master.server.crt": could not read file: stat /etc/origin/master/master.server.crt: no such file or directory
Jul 21 12:11:18 base atomic-openshift-master-api[11617]: assetConfig.servingInfo.keyFile: Invalid value: "/etc/origin/master/master.server.key": could not read file: stat /etc/origin/master/master.server.key: no such file or directory
Jul 21 12:11:18 base atomic-openshift-master-api[11617]: servingInfo.certFile: Invalid value: "/etc/origin/master/master.server.crt": could not read file: stat /etc/origin/master/master.server.crt: no such file or directory
Jul 21 12:11:18 base atomic-openshift-master-api[11617]: servingInfo.keyFile: Invalid value: "/etc/origin/master/master.server.key": could not read file: stat /etc/origin/master/master.server.key: no such file or directory
Jul 21 12:11:18 base systemd[1]: atomic-openshift-master-api.service: main process exited, code=exited, status=255/n/a
Jul 21 12:11:18 base systemd[1]: Failed to start Atomic OpenShift Master API.
```

It appears the master.server.crt and .key are not available on 2 of the 3 masters.

**Comment by abutcher** [comment]
@thijsschnitger Thanks for the heads up, corrected with an extra backport in https://github.com/openshift/openshift-ansible/pull/4821

**Comment by thijsschnitger** [comment]
@abutcher it's working again. Thanks!

**Pull request merged**
