### PR TITLE
Proposal: Template Flexibility

### PR DESCRIPTION
**Pull request by michaelgugino**
This proposal is intended to address user concerns about
the flexibility or lack thereof of certain configuration
templates.

### CODE REVIEW

**Comment by ingvagabund** [comment]
Based on the architecture meeting discussion I agree that only the `openshift_master` role should be touching the `master-config.yml` file a.k.a. only a single role should be able to create/modify a configuration file (no matter if it is template based or not).

**Comment by ingvagabund** [comment]
@twiest

**Comment by michaelgugino** [comment]
@ewolinetz @ingvagabund 
I agree that only one role should touch a config file; it's the only way to ensure idempotency.  However, I think that should be documented in another proposal as this method is neutral to that approach.

**Comment by kwoodson** [comment]
Thanks for bringing up the proposal @michaelgugino.  I think recognizing openshift-ansible's lack of flexibility when managing configuration is definitely something we need to address.  The architecture meeting demonstrated the need for the team to come together on direction, tooling, and general understanding of our customer's needs.

@sdodson, were you able to determine whether or not configuration management was one of the major goals for openshift-ansible?  I think this was one conversation that was needed in order to help us in our decision making.

In my opinion, customers will need to make changes to their master-config.yaml file.  These changes are a necessary part of supplying them with a complex software and meeting their needs for their environments.  

As a team, cluster lifecycle has made great strides to improve the user experience around our repository.  We have improved upon efficiency, reduced dependencies, increased idempotency, and with the current efforts we are increasing modularity.  All of these are going to improve customer experience, decrease the time it takes to develop new features and test them, and allow users to consume the parts they need to be able to accomplish their tasks.

Here are my overall thoughts regarding this proposal:
- I'm **in favor** of using tools that provide more flexibility and more functionality.  If `config_template` helps us achieve that then I'm in favor of that.  I would like to see the implementation of the `a.b.c = 3` functionality as its very difficult to patch the entire dictionary of `a` when I only care to surgically insert a single value inside of a larger structure with little to no side effects.
- I **do not** like having a single role that manages all of the options for all of the different technologies.  This generally requires a lot of logic that might be unnecessary if only a few of the desired technologies are required.
- In general, a template file must support all options or knobs available to the user to tweak.  This will require constant management and maintenance.  If we as a team decide to go this route, then we must also understand this responsibility.  I understand that the `config_template` model allows user overrides but this template still must be very detailed.
- I prefer having the configs localized to the roles that require them.  This allows us to be able to consume single roles without many dependencies in an idempotent way.  If each change is idempotent the overall idempotency is maintained.
- As our repository **stands today**, running openshift-ansible also introduces more risk of having unintended changes, unnecessary code running, and requires openshift-ansible compatible inventory settings.  I think that requiring users to run openshift-ansible to make changes to configuration files is too strict.  If other IT shops are already managing the config file via puppet, chef, or other means then requiring them to run our code base seems unnecessary outside of installation or upgrade.  Stating that they are in an unsupported state seems a bit harsh if they have made a change to their settings for their environment.
- There probably needs to be some more detail about how this will integrate into the repository.  If this lives inside of openshift-master then the user is required to load all of the necessary facts, dependencies, tools to run the openshift-master when in reality I only need to place the value of `3` in a specific `a.b.c` key.  We need to keep in mind the overhead of our decisions on users wanting to accomplish these small types of tasks.  If openshift_facts, openshift_version, and some other roles are required then we have the unintended consequences of installing docker, determining the openshift version which also requires a valid rpm repository or docker container queries, reading and writing facts files on the host, etc.

Sorry for the wall of text but this decision is an important one that we need to make as a team.   I have requested reviews by @mwoodson @twiest and @smarterclayton so they can weigh in.

**Comment by michaelgugino** [comment]
>As our repository stands today, running openshift-ansible also introduces more risk of having unintended changes, unnecessary code running, and requires openshift-ansible compatible inventory settings. I think that requiring users to run openshift-ansible to make changes to configuration files is too strict. If other IT shops are already managing the config file via puppet, chef, or other means then requiring them to run our code base seems unnecessary outside of installation or upgrade. Stating that they are in an unsupported state seems a bit harsh if they have made a change to their settings for their environment.

I specifically used 'unknown configuration' rather than 'unsupported configuration.'  I do not mean to imply that users are out in the cold using some of the options mentioned; rather the burden is on the user to ensure the configuration modifications necessary to transition from version to version (upgrades) and other operational elements (rolling upgrades, scaling the cluster).

The only way we can ensure a 100% successful (and that's being optimistic due to the fast moving nature of the software) during some things like upgrades is to have control over the configuration templates in openshift-ansible.  This proposal offers users the flexibility to use whatever templates they wish, or not use templates at (you could easily pass in pre-generated configs with the template source variable).

> I prefer having the configs localized to the roles that require them. This allows us to be able to consume single roles without many dependencies in an idempotent way. If each change is idempotent the overall idempotency is maintained.

I'm not proposing or in any way in favor of a 'templates_role' that handles a bunch of configuration file, if that's what you're implying.

I prefer that 1 configuration file is managed by 1 role.  IE, master.yaml is only configured by openshfit_master role.  This is the only way to ensure idempotent changes.  If two roles are managing one file, there will be flip-flopping changes when the roles are run again.

> There probably needs to be some more detail about how this will integrate into the repository. If this lives inside of openshift-master then the user is required to load all of the necessary facts, dependencies, tools to run the openshift-master when in reality I only need to place the value of 3 in a specific a.b.c key. 

That is how ansible works.  There's no way we can dynamically generate the master config file with out gathering a lot of facts about how the environment is configured unless that information is supplied via the user through inventory/group_vars/host_vars.  Running openshift_master should be relatively painless; at this stage, I don't think that is the case, and that's where we are trying to get with entry points.  If you want to change master.yml, you use the new entry point play, and it should be finished in a couple minutes at most.

> If openshift_facts, openshift_version, and some other roles are required then we have the unintended consequences of installing docker, determining the openshift version which also requires a valid rpm repository or docker container queries, reading and writing facts files on the host, etc.

We are actively working to alleviate the docker problem.  I have a large patch set that pulls docker out of the meta dependencies.  We just need to find a place for it to live.  Right now, openshift version depends on it; I'd like to see that dependency go away; I believe we can accomplish this with skopeo, but I haven't tried it.  In any case, docker role probably only needs to be run once when first initializing the cluster, and then you can forget about it until you want to upgrade docker.

Much of openshift_version appears to be skip-able if the right values are defined in inventory/group_vars/host_vars.  Some variables are non-optional for the proper operation of the cluster, such as openshfit_version.

If there isn't enough flexibility in openshift_version for your environment, we should discuss some modifications to that role.

> I'm in favor of using tools that provide more flexibility and more functionality. If config_template helps us achieve that then I'm in favor of that. I would like to see the implementation of the a.b.c = 3 functionality as its very difficult to patch the entire dictionary of a when I only care to surgically insert a single value inside of a larger structure with little to no side effects.

I agree, this seems like a useful pattern.  If we can get config_template implemented, then we can modify it to include this a.b.c = 3 functionality.  That functionality combined with 'bring your own template' will cover just about any use case I can think of.

**Comment by mwoodson** [comment]
I won't spend too much time arguing here, it probably won't do much good.

I am not a fan of templates, in general.  I like to use line editing (lineinfile, inifile, yedit) when possible.  It feels way more flexible:

Templates have to have all known info for a file, and have access to it.  Then the logic needs to be kept inside the template to keep it maintained.  Maintaining this long term is a nightmare.

I will admit, I don't understand the config_template stuff.  It kinda feels like another way to do lineinefile/yedit type edits.  I would love to see a demo of it.

I also strongly disagree that all edits of a config file should be done in a on role.  This is a pattern that makes things very monolithic and goes bad very quickly by growing and growing.

Here is an example.  @ewolinetz wrote this code, and I fully support this pattern.

In installing openshift logging, logging is setup in it's openshift project.  It does all sorts of things.  One of the things that logging needs to do is set 1 (just 1) config value in the master-config.yaml.  It needs to turn on the logging URL in the web UI.

The code for that is here:

https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_logging/tasks/update_master_config.yaml

The way this is implemented (and we use and LOVE in ops), is that I can call one role (openshift_logging), and it will set up my logging.  It needs to make one call to edit the config file of master-config.yaml, and it has one specific value it needs to set.  It does this in that role, with the yedit call.

Now, the alternative would be, if I understand this correctly, the openshift_logging role would either need to depend on the openshift_master role, or it would have to be called in the same playbook.  At that point, the playbook would have to know (or have access to) EVERY config options that we want in the master-config.yaml.  This has many disadvantages.  One, the role isn't portable.  I can't just use the openshift_logging role like I do today without having the openshift_master role. (BTW, we do use the openshift_logging role in Ops, and it works very well for us).  Then, we probably need to pull in dependencies for all of openshift_master at that point.  All I want to do is add logging to the cluster!

Now, we could argue that openshift as a product move to a .d type config structure, where files can be dropped into to a .d dir and then the configs take place.  In that case, openshift_loggign role would drop a file into the appropriate .d dir and things would pick up that config.  To me, the lineinfile/yedit method is using the same methodology as the .d config style that so many projects are moving to.  Each section of code (logging in this example) is concerned about it's piece and makes the appropriate edits.

**Comment by twiest** [comment]
I agree with @mwoodson and @kwoodson.

We have to remember that what's being written here is the OpenShift installer and upgrader.

I've never installed a piece of software on Linux where I wasn't allowed to edit the config file directly.

In fact, if this proposal represented the normal software installation and upgrade pattern on Linux:

* How would config management systems exist? Weren't they built on the premise of admins being able to change config files independent of software installers / upgraders?
* Why are config files text instead of binary?
* Why did RH fund the writing of Augeas which enables entities other than the original installer / upgrader to modify config files?

Are we really going to tell our customers that they must re-run the installer to change values in the config file?

This proposal seems like a nightmare for our customers (including OPS). It is not going to be intuitive to them that they must re-run the installer to change config file values, which is going to lead to a their config files getting stomped.

This is a -1 from OPS.

**Comment by michaelgugino** [comment]
> Templates have to have all known info for a file, and have access to it. Then the logic needs to be kept inside the template to keep it maintained. Maintaining this long term is a nightmare.

It's true that we are plagued by some large monolithic configuration files.  You see a "big confusing mess" and I see "everything is in one place".  I can look at that one template file, and figure out what is happening in my configuration.  Typical use case:  I want to troubleshoot x.  I look into x's configuration file by ssh'ing into the host.  A particular key looks out of place.  I go to the template, see what variable and logic surround that key, and I am close to figuring out what I need to adjust.

Abstracting a configuration file into possibly hundreds of disjoined tasks that operate independently on some condition is a bigger nightmare.  What happens when we need to remove/deprecate a key from one version to the next?  We would have to make a series of tasks that un-sets a bunch of values.

> I will admit, I don't understand the config_template stuff. It kinda feels like another way to do lineinefile/yedit type edits. I would love to see a demo of it.

config_template allows users to specify anything that is missing from the template.  It also allows items to be overriden that already exist in the template.

I included an example usage here: https://github.com/michaelgugino/config-template-example

You can clone that, and run p.yml from the root of that project to see how it works.

> I also strongly disagree that all edits of a config file should be done in a on role. This is a pattern that makes things very monolithic and goes bad very quickly by growing and growing.

Unfortunately, some of our configs don't support conf.d directories at this time.  For me, it makes sense to put all of one service's possible configuration file details in one template.  As a user, I want to be able to go to one place to see how my config file is generated.

I'm open to, on a case-by-case basis, using the assemble module:  http://docs.ansible.com/ansible/latest/assemble_module.html

This would allow us to let various roles place 'fragments' of a monolithic config file in a directory together.  The fragments are assembled in aphabetical order.

In the case of a large config file like openshift_master, we could do something like follows:
```yaml
# master play
- include_role:
    name: openshift_master
    tasks_from: install.yml
- include_role:
    name: openshift_master
    tasks_from: generate_config_frags.yml
- include_role:
    name: openshift_master
    tasks_from: assemble_config.yml

....
# logging play
- include_role:
    name: hosted_logging
      tasks_from: install.yml
- include_role:
    name: hosted_logging
    tasks_from: generate_config_frags.yml
- include_role:
    name: openshift_master
    tasks_from: assemble_config.yml
```

The net result is that generate_config_frags from each role operate on different files, thus both will be idempotent.  assemble_config in master doesn't know or care what the underlying fragments contain, just that if it takes all the fragments from the directory and assembles them into one file, does that equal what is currently assembled?

This pattern could work for sub-elements of a dictionary as follows:

```yaml
# master_config_frag0.yaml
### BEGIN FRAG ###
some_thing:
  child_1:
    - key1
### END OF FRAGMENT
```
```yaml
# master_config_frag1.yaml # generated by logging role
    - key2
    - key3
### END OF FRAGMENT
```

This will require careful planning and coordination among the various pieces.

In any case, all of this is outside the scope of this proposal, and would require it's own proposal.

The point of this proposal is 'making templates flexible'.  This is a drop-in solution to what we already have that provides more flexibility.  Dropping templates altogether is a whole other can of worms.

**Comment by michaelgugino** [comment]
> This proposal seems like a nightmare for our customers (including OPS). It is not going to be intuitive to them that they must re-run the installer to change config file values, which is going to lead to a their config files getting stomped.

This is not characteristic of this proposal.  The boolean section of this proposal allows for users, including ops, to never have to modify the configuration files via templates after initial install.

The purpose of this proposal is not to try to modify existing user patterns, but to facilitate them, whatever they may be.  This proposal continues present use of templates, but adds more flexibility.

If you don't want to re-run the installer to modify config files, don't.  Then, during upgrades, switch those template boolean values to true, and we won't touch your configs.

**Comment by stevekuznetsov** [comment]
v

**Comment by mwoodson** [comment]
>It's true that we are plagued by some large monolithic configuration files. You see a "big confusing mess" and I see "everything is in one place". I can look at that one template file, and figure out what is happening in my configuration. Typical use case: I want to troubleshoot x. I look into x's configuration file by ssh'ing into the host. A particular key looks out of place. I go to the template, see what variable and logic surround that key, and I am close to figuring out what I need to adjust.

It all depends on our perspective on looking at the code base.   I can't say you are wrong, I will just say you are looking at it differently than how I have learned to look at config management.

The "everything is in one place" can turn out to be very confusing, as you mentioned on larger config files (like master-config.yaml).  In my experience, going to the place where the technology is located gives me more benefits than a big template.  In this case, openshift_logging, if I am dealing with a logging setting, I  am ok knowing that this setting will be in the openshift_logging role.  The benefits I get from breaking out the technologies from one big file outweigh the benefit of having everything in one place.

I do understand templates, and I have used templates extensively in the past.  But after experiencing template hell and the "big confusing mess" as you described, I have found that breaking things out by technology is, in my opinion, a better and more flexible way to run config management.

**Comment by smarterclayton** [comment]
I think it's important to step out and describe the broader context of
where we are going on config.

We are going to move master-config.yaml into etcd potentially (in the next
few releases).  Various parts of it are going to be split into their own
config objects.  node-config will no longer be placed on nodes and will
instead be served out of the API as part of node-bootstrapping.  Any
cluster component that is not intrinsically and totally incapable of
running inside a container (i.e. the kernel and perhaps some select kernel
drivers) will run as daemon sets.

So in general, we are going to gradually take away and remove cluster level
config from being placed as files on disk.  Furthermore, we are going to
need to break apart the core cluster install (which sets up masters that
can then run more containers) from many of the infrastructure and component
service installs (registries, routers, networking, storage, etc etc etc)
into *completely* separate and distinct playbooks / roles that are invoked
after a cluster is configured.  If the cluster needs to react dynamically
when someone sets the default router subdomain, we will do so by having
components look at their core config.  In general though, we need to split
those couplings out of master config - there is no reason you have to
restart the masters to install a router.

We need to start talking about this in terms of "class of configuration"
(node, cluster, component) and also start bringing the actual deployable
objects into that story (the YAML files that define a router are just as
much part of their config as the master-config).  We need more rather than
less hard boundaries between layers, and openshift-ansible needs to be
smaller, not larger.  We need to reduce the amount of things that the core
install playbook influences, rather that more.

Yes, there may be a top level playbook that sets up a "standard cluster".
But we need to be more focused on having cluster "components" that are all
able to be installed completely independently of each other, which means
that it would be inappropriate for some of the core config files to be
generated from a single template in the long run.  And in that world, when
we look at already installed clusters it is very unlikely that we will have
a single "rerun everything" script that is allowed to touch all components
(other than as something put in place by a CD team).

**Comment by ashcrow** [comment]
> We are going to move master-config.yaml into etcd potentially (in the next few releases). Various parts of it are going to be split into their own config objects.

❤️ ❤️ ❤️ 

Given that, over time, configuration of master and possibly other things will end up in etcd I think it makes sense to have remaining templates follow this proposal.

👍

**Comment by sdodson** [comment]
@michaelgugino @abutcher @ewolinetz @ingvagabund @kwoodson @tbielawa @mtnbikenc I'd like to make a decision on whether or not we pursue this, please provide either positive or negative review indicating your position.

**Pull request closed without merging**
