### PR TITLE
Backport 1.4: Tox and test dependency changes

### PR DESCRIPTION
**Pull request by abutcher**

### CODE REVIEW

**Comment by detiber** [comment]
travis failures are for test coverage in utils

**Comment by detiber** [comment]
@abutcher not sure how easy it would be to backport the test coverage fixes I did for utils

**Comment by abutcher** [comment]
@detiber also seeing `ERROR: InterpreterNotFound: python3.5`

**Comment by detiber** [comment]
@abutcher the interpreter failures are ignored, for travis we test 3.5 separate from 2.7

**Comment by detiber** [comment]
aos-ci-test

**Pull request merged**
