### PR TITLE
Fix broken link to Docker image instructions

### PR DESCRIPTION
**Pull request by rhcarvalho**
And document that one needs to install dependencies before running playbooks.

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@sdodson @sosiouxme PTAL, I noticed the link to the container image README was missing an extra `../`. Since touching it, also added a note about dependencies.

**Comment by rhcarvalho** [comment]
@sdodson could we get this in without aos-ci-test?

**Comment by sdodson** [comment]
sure

**Comment by sosiouxme** [comment]
Good catch, thanks.

Since it can now be installed as a system container we don't even have to limit it to "anywhere docker runs" :) I should probably take a pass at origin docs for various tweaks like that...

**Pull request merged**
