### PR TITLE
Metrics: grant hawkular namespace listener role

### PR DESCRIPTION
**Pull request by mwringe**
An update to the Hawkular component requires that it be able to list and listen on namespace events.

This will create a new cluster role and grant it to the hawkular service account

### CODE REVIEW

**Comment by mwringe** [comment]
@sdodson @jcantrill could someone review this please? We need this for to fix a blocker issue.

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
[merge]

**Comment by ewolinetz** [comment]
@mwringe is this required for 3.6 as well?

**Comment by mwringe** [comment]
@ewolinetz yes, its required for 3.6, I will submit a pr for the 3.6 branch. I usually try and get this in master before backporting to older versions

**Comment by mwringe** [comment]
The 3.6 backport is available here: https://github.com/openshift/openshift-ansible/pull/4865

**Comment by ewolinetz** [comment]
merge flaked on https://github.com/openshift/origin/issues/15356
[merge]

**Comment by mwringe** [comment]
Is the test failures something wrong with the CI?
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check/878/console
"rm: cannot remove ‘/tmp/etcd/member’: Permission denied"

**Comment by ewolinetz** [comment]
merge flaked on https://github.com/openshift/origin/issues/15356
[merge]

**Pull request merged**
