### PR TITLE
Propose adding ManageIQ service account by default

### PR DESCRIPTION
**Pull request by enoodle**
Signed-off-by: enoodle <efreiber@redhat.com>

### CODE REVIEW

**Comment by detiber** [comment]
:+1: from me.

@twiest @wshearn

**Comment by twiest** [comment]
I'll let @wshearn weigh in here, I'm not sure how this would affect his process.

**Comment by enoodle** [comment]
For easy reference, ManageIQ service accounts were added in https://github.com/openshift/openshift-ansible/pull/983

**Comment by simon3z** [comment]
@wshearn can you review?

**Comment by wshearn** [comment]
It shouldn't be too much of an impact for us.

Though shouldn't this be set to true inside openshift_facts.py instead for consistency?(It is where we enable sdn, flannel, fluentd, etc)

**Comment by enoodle** [comment]
@wshearn You are right, I fixed that.

**Comment by detiber** [comment]
ok to test

**Comment by detiber** [comment]
@wshearn @twiest This should be ready for merge.

**Comment by simon3z** [comment]
@enoodle please rebase.

**Comment by detiber** [comment]
@wshearn please merge.

**Pull request merged**
