### PR TITLE
Install cockpit, logrotate and fluentd unless host is atomic.

### PR DESCRIPTION
**Pull request by abutcher**
@sdodson PTAL

https://bugzilla.redhat.com/show_bug.cgi?id=1299335
https://bugzilla.redhat.com/show_bug.cgi?id=1299331
https://bugzilla.redhat.com/show_bug.cgi?id=1299333

### CODE REVIEW

**Comment by detiber** [comment]
lgtm

**Comment by abutcher** [comment]
aos-ci-test

**Comment by sdodson** [comment]
LGTM

**Comment by abutcher** [comment]
@brenton :point_up:

**Pull request merged**
