### PR TITLE
Service retries

### PR DESCRIPTION
**Pull request by sdodson**
- Adds retries around many stop/start/restart services items
- Adds retries around drain operations
- Dumps 100 lines of node service logs if it fails

### CODE REVIEW

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
repo flake

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge][severity:blocker]

**Comment by ashcrow** [comment]
😕 

```            "msg": "openshift_release is \"v3.5\" which is not a valid version string.\nPlease set it to a version string like \"3.4\"."
```

**Comment by sdodson** [comment]
Is that supposed to be valid? I've updated the jobs not to include the v.

**Comment by sdodson** [comment]
aos-ci-test

**Comment by ashcrow** [comment]
@sdodson true, no, it's not valid but we supposedly sanitize it in ``openshift_version``

```
# Normalize some values that we need in a certain format that might be confusing:
- set_fact:
    openshift_release: "{{ openshift_release[1:] }}"
  when:
  - openshift_release is defined
  - openshift_release[0] == 'v'
```

Though it looks like it gets caught in ``roles/openshift_sanitize_inventory/tasks/main.yml`` first.

In any case removing the ``v`` should work.

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge][severity:blocker]

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge][severity:blocker]

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
merged as the only test failure was the job status check and those checks had subsequently passed.

**Pull request merged**
