### PR TITLE
[KIECLOUD-336] - Update RHPAM and RHDM templates and imagestreams on …

### PR DESCRIPTION
**Pull request by spolti**
…OpenShift Service Catalog for release 7.5.1

Signed-off-by: Filippe Spolti <fspolti@redhat.com>

### CODE REVIEW

**Comment by spolti** [comment]
@adambkaplan @gabemontero Hi, can you guys please take a look?

**Comment by gabemontero** [comment]
neither @adambkaplan nor I have permission to merge this @spolti 

see the IDs in https://github.com/openshift/openshift-ansible/blob/release-3.11/OWNERS and assign it to someone per the instructions in https://github.com/openshift/openshift-ansible/pull/12046#issuecomment-562226090

I'm assuming this is the equivalent of https://github.com/openshift/library/pull/197 and that you want those changes in 3.11.x in addition to 4.x, correct ?

**Comment by spolti** [comment]
@gabemontero thahs for the info.
Correct.

**Comment by spolti** [comment]
@vrutkovs Thanks!

**Pull request merged**
