### PR TITLE
Replace has_key in new modules

### PR DESCRIPTION
**Pull request by ashcrow**
The dict.has_key has been removed in Python 3. However, both Python 2
and 3 support:

    if needle in dict

See: #3396

### CODE REVIEW

**Comment by detiber** [comment]
@ashcrow I know pylint has a py3 mode that will only test for py3 compatibility issues. I wonder if that would have caught this error. Either that or possibly a flake8 plugin that could do the same.

**Comment by detiber** [comment]
arrgh, it looks like `pylint --py3k` only complains about `no-absolute-import`

**Comment by detiber** [comment]
Even worse than that, it looks like we are disabling pylint tests that would help catch these types of things:
- https://github.com/ashcrow/openshift-ansible/blob/d4a424e51e4cce0e3a5a4618f696800ebe655d25/.pylintrc#L63

**Comment by ashcrow** [comment]
@detiber While this tests I'm going to see if we can use ``2to3`` as part of testing.

**Comment by ashcrow** [comment]
aos-ci-test

**Comment by ashcrow** [comment]
@detiber ``2to3`` looks like it will work :smile:

**Comment by detiber** [comment]
@ashcrow I'm just wondering if there is an existing tool we can leverage instead of adding yet another tool :)

**Comment by ashcrow** [comment]
@detiber good point. Do you know if we have ``python-tools`` installed?

```
$ rpm -q --whatprovides /usr/bin/2to3 
python-tools-2.7.13-1.fc24.x86_64
```

**Comment by detiber** [comment]
@ashcrow it looks like we do have it installed, I'm more concerned with adding additional test invocations.

For 'linting', we currently run:
- pylint
- flake8
- yamllint
- generate_validation

If 2to3 is the best way to do it, then we can always add it to the list, we set the deps for the test environments. It'd be nice to be able to leverage one of the existing tools if at all possible instead, though

**Comment by detiber** [comment]
Really, I would like to see if we could consolidate on either pylint or flake8 instead of running both, or at least tweak our configs to avoid running the same tests with both.

**Comment by detiber** [comment]
@ashcrow ah, looks like pylint would have caught these issues, but we are disabling the `no-member` check which would have caught it.

**Comment by ashcrow** [comment]
@detiber 

```
$ grep -ri 'no-member' . | grep -v tox | wc -l
246
```

Wooo, that will be interesting :sweat_smile:

**Comment by detiber** [comment]
@ashcrow excluding the generated modules, it brings the count down to 23

**Pull request merged**
