### PR TITLE
set etcd working directory for embedded etcd

### PR DESCRIPTION
**Pull request by ingvagabund**
ssia

### CODE REVIEW

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[test]

**Comment by ingvagabund** [comment]
Something is still missing, investigating

**Comment by ingvagabund** [comment]
aos-ci-test

**Comment by ingvagabund** [comment]
With the patch applied, the upgrade finishes without an error.

**Comment by ingvagabund** [comment]
aos-ci-test

**Comment by ingvagabund** [comment]
[test]

**Pull request merged**
