### PR TITLE
switch imagestreams to registry.redhat.io

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@sdodson ptal

note that the upstream content is *not* updated yet, so if you rerun the example sync script, you'll undo these changes.  please don't :)  (or at least don't commit these files if you run it).  the upstream changes are pending but we wanted to get this in QEs hands sooner.

**Comment by sdodson** [comment]
Thanks for the heads up about not running sync script.

/lgtm

**Comment by sdodson** [comment]
Though now it's merged upstream too, so we're safe to sync again.

**Comment by bparees** [comment]
> Though now it's merged upstream too, so we're safe to sync again.

@sdodson the xpaas content isn't updated upstream, only the origin content, so you'll still revert the xpaas content if you run the script and commit those files.

**Comment by bparees** [comment]
[(5) Tolerate auth-enabled redhat registry [builds]](https://trello.com/c/Howwzs2c/1492-5-tolerate-auth-enabled-redhat-registry-builds)

**Pull request merged**
