### PR TITLE
Allow for overriding scheduler config

### PR DESCRIPTION
**Pull request by detiber**
- introduce openshift_master_scheduler_predicates and
  openshift_master_scheduler_priorities to override the default scheduler
  predicates and priorities

- switch default scheduler priorities to use SelectorSpreadingPriority instead
  of ServiceSpreadingPriority

resolves https://github.com/openshift/openshift-ansible/issues/476

### CODE REVIEW

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
@brenton this should be ready to go pending test results.

**Comment by brenton** [comment]
aos-ci-test

**Comment by brenton** [comment]
Something seems stuck with the ci jobs.  It looks like Stage RHN might have been having problems when the containerized prep job ran.  I'm not sure why the normal 3.0 and 3.1 jobs never appear to have started.  @arilivigni, do you have any ideas?

**Comment by arilivigni** [comment]
The context here got messed up but I can fix that but if you go to the Jenkins all your runs failed for openshift-ansible.  So the context thing I can fix

**Comment by arilivigni** [comment]
@brenton ^^^

**Comment by arilivigni** [comment]
aos-ci-test

**Comment by arilivigni** [comment]
@brenton I will cleanup the context here but all of the 3.1 container and non containerized and 3.0 failed

**Comment by arilivigni** [comment]
@brenton nothing stuck so anyone can debug away on the failures.

aos-ci-jenkins/OS_3.1_containerized
aos-ci-jenkins/OS_3.1_NOT_containerized
aos-ci-jenkins/OS_3.0_NOT_containerized

Are the links to follow

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
@brenton

**Pull request merged**
