### PR TITLE
[3.3] Remove Jinja delimiters from when conditions

### PR DESCRIPTION
**Pull request by mtnbikenc**

### CODE REVIEW

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
Flake:
```
"No package matching 'atomic-openshift-docker-excluder-3.3.1.46.11*' found available, installed or updated"
```

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
@sdodson Twice failed on docker-excluder.  Is there a bigger problem here with package availability?

**Comment by sdodson** [comment]
Yeah probably, looking into it.

**Pull request merged**
