### PR TITLE
bug 1685618. Modify default_md for logging cert generation

### PR DESCRIPTION
**Pull request by jcantrill**
Fixes: 
* https://bugzilla.redhat.com/show_bug.cgi?id=1685618
* https://bugzilla.redhat.com/show_bug.cgi?id=1685655

### CODE REVIEW

**Comment by ewolinetz** [comment]
@jcantrill can you also add the similar changes from https://github.com/openshift/cluster-logging-operator/pull/111 here?

**Comment by jcantrill** [comment]
@ewolinetz updated

**Comment by ewolinetz** [comment]
we also need to update this tasks/generate_pems.yaml -- similar to this line: https://github.com/openshift/openshift-ansible/blob/d51be443ed8d1389e6823b407fcf256e9a00b989/roles/openshift_logging/tasks/generate_pems.yaml#L22

**Comment by sdodson** [comment]
/close
checking to see if closing and re-opening clears the `Red Hat CI` context.

**Pull request merged**
