### PR TITLE
Add origin version upgrade mappings for 1.5

### PR DESCRIPTION
**Pull request by sdodson**

### CODE REVIEW

**Comment by jfchevrette** [comment]
This patch fixed the issue I had upgrading from origin 1.4 to 1.5

Thanks @sdodson !

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[test]

**Comment by jfchevrette** [comment]
@sdodson FYI had to make similar changes in branch release-1.4 to allow upgrading a 1.3 cluster to 1.4. Issue #4604

**Pull request merged**
