### PR TITLE
Bz 1758552: set arp_announce=2

### PR DESCRIPTION
**Pull request by fbac**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1758552 for OCP 3.

### CODE REVIEW

**Comment by jmencak** [comment]
@squeed , can you provide feedback from the networking side? Thanks!

**Comment by squeed** [comment]
seems reasonable. @dcbw, can you give this a check ( see the bz for more background).

**Comment by jmencak** [comment]
Also @fbac, does this need to be in the `openshift` profile or would `openshift-node` be a better to put this (assuming the problem surfaces only on application nodes)?

**Comment by rjhowe** [comment]
@jmencak openshift profile, as masters and infra nodes do not use the openshift-node profile but still require this.

**Comment by fbac** [comment]
As rhowe stated, we need this in every node/master/infra in the cluster.

**Comment by sdodson** [comment]
/approve
@dcbw PTAL, need final decision whether this is safe to apply to masters,infra, and node.

**Comment by jmencak** [comment]
Just a note [this](https://github.com/openshift/cluster-node-tuning-operator/pull/81) seems to be running fine on 4.3 for nearly 2 weeks now.

**Comment by fbac** [comment]
@dcbw PTAL

**Comment by abhat** [comment]
@fbac this lgtm. you probably should still get a blessing from @dcbw.

**Comment by squeed** [comment]
@jmencak I think this is good to go in. Not sure why I tagged dcbw.

**Pull request merged**
