### PR TITLE
RC2 Merge

### PR DESCRIPTION
**Pull request by sdodson**
I've tested with https://copr.fedoraproject.org/coprs/sdodson/origin/build/99785/

I'll squash before merging

### CODE REVIEW

**Comment by sdodson** [comment]
@jwhonce @wshearn This should bring everything up to date with RC2. If you guys could re-build https://sdodson.fedorapeople.org/openshift-0.6.1-0.git.4109.63cf207.el7.src.rpm into maxamillion/origin-next copr we should be ready to make RC2 for origin available with this merge.

**Comment by sdodson** [comment]
@twiest any chance we can get this reviewed and packages for rc2 built today?

**Comment by jwhonce** [comment]
LGTM

**Comment by twiest** [comment]
Looks good to me as well.

@tdawson @detiber @wshearn @jwhonce Any objection to merging this now?

**Comment by sdodson** [comment]
Shall I squash things first?

**Comment by twiest** [comment]
@sdodson that'd be fine by me.

**Comment by twiest** [comment]
@tdawson @detiber @wshearn @jwhonce I'm going to merge this tomorrow morning EDT unless someone says not to.

**Comment by detiber** [comment]
:+1:

**Comment by twiest** [comment]
Merging. :+1:

**Pull request merged**
