### PR TITLE
Use 'openshift3/' as IMAGE_PREFIX for enterprise logging and metrics

### PR DESCRIPTION
**Pull request by sdodson**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1326446

Minimal fix, still need to address upstream enterprise content source for metrics or we'll just re-introduce the problem at a later date.

### CODE REVIEW

**Comment by sdodson** [comment]
@mwringe @sosiouxme mind taking a quick look?

**Comment by sosiouxme** [comment]
LGTM

**Comment by sdodson** [comment]
@brenton ready to merge

**Comment by mwringe** [comment]
The IMAGE_PREFIX is a template parameter that can be used when using the deployer. You wouldn't need to actually modify the template file, just specifying the parameter would be enough.

So if I create a user in docker hub called 'openshift3' and for some reason registry.access.redhat.com is down, does that mean it could potentially bring in a compromised container instead?

**Comment by sdodson** [comment]
Yes, I think that's the case. I'd have to test to be sure.

**Comment by detiber** [comment]
@sdodson we may want to start thinking about how to make the templates more customizable on deployment. This will be more of an issue when it comes to disconnected installs.

**Comment by sdodson** [comment]
I've always assumed that people would utilize the --additional-registry flag for such environments.

**Comment by brenton** [comment]
I think we're going to have move away from relying on --add-registry in a number of places actually.  This will require more of the product relying on image streams and then making sure they are using the fqdn's of the registry so that the Kubelet docker auth keyring works correctly.

**Comment by sdodson** [comment]
I'll revert back to the fully qualified IMAGE_PREFIX for now.

**Comment by sdodson** [comment]
@brenton reverted back to fully qualified image names, only the metrics IMAGE_PREFIX needed to be fixed.

**Comment by brenton** [comment]
If this missed today's puddle I'll tag/build the package and give the brew link to QE.

**Pull request merged**
