### PR TITLE
Default to port 80 when deploying cockpit-ui

### PR DESCRIPTION
**Pull request by smunilla**
This should save first-time users some pain.

Fixes BZ#1371031

### CODE REVIEW

**Comment by aweiteka** [comment]
LGTM

**Comment by sdodson** [comment]
not currently tested by CI, merging without tests.

**Comment by detiber** [comment]
Do we not configure SSL by default? Or are we handling it with an edge termination route?

**Comment by liggitt** [comment]
also, does this mean config will need undoing once the registry is secured?

**Pull request merged**
