### PR TITLE
allow NFS to be used for registry without marking cluster unsupported

### PR DESCRIPTION
**Pull request by bparees**
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1589137

### CODE REVIEW

**Comment by bparees** [comment]
this is currently failing with: https://gist.github.com/bparees/3b71500bbb31a3191df081bd9ae31da0

@mtnbikenc is looking into it.

**Comment by vrutkovs** [comment]
@bparees warnings from `installer_checkpoint` would be resolved by #9259

**Comment by bparees** [comment]
> @bparees warnings from installer_checkpoint would be resolved by #9259

well i don't want the warning filtered out, i want my message to be printed...so it seems like my stats usage is somehow incorrect(which results in the warning) and i'm looking for help on how to fix that.

**Comment by mtnbikenc** [comment]
@bparees I think there was just terminology confusion above.  An unrelated playbook had a typo in it that caused the installer_checkpoint plugin to fail.  @vadim fixed that typo, and also improved the plugin so it would fail in this particular way.  Your warning message should now display correctly.

**Comment by bparees** [comment]
cool, with a cherry-pick of https://github.com/openshift/openshift-ansible/pull/9259 the output looks good:

```
INSTALLER STATUS *************************************************************************
Initialization              : Complete (0:00:32)
        [DEPRECATION WARNING]: The following are deprecated variables and will be no longer be used in the next minor release. Please update your inventory accordingly.
        openshift_node_labels
Health Check                : Complete (0:00:33)
Node Bootstrap Preparation  : Complete (0:06:22)
etcd Install                : Complete (0:02:03)
Master Install              : Complete (0:06:18)
Master Additional Install   : Complete (0:01:28)
Node Join                   : Complete (0:00:29)
Hosted Install              : Complete (0:01:45)
        The use of NFS for the core OpenShift Container Platform components is not recommended, as NFS (and the NFS Protocol) does not provide the proper consistency needed for the applications that make up the OpenShift Container Platform infrastructure.
Web Console Install         : Complete (0:00:38)
Console Install             : Complete (0:00:23)
metrics-server Install      : Complete (0:00:00)
Service Catalog Install     : Complete (0:02:43)
```

/hold cancel

**Comment by bparees** [comment]
@sdodson guessing this will need manual merge due to the fedora failures

**Comment by gpei** [comment]
Hi @bparees @sdodson do we have plan to backport this to 3.10 and 3.9 branch? Thanks.

**Comment by bparees** [comment]
@gpei not at present, no.

**Comment by gpei** [comment]
@bparees ok, thanks

**Pull request merged**
