### PR TITLE
Bug 1633506: Possibility to define nodeSelector for hawkular-metrics-schema job

### PR DESCRIPTION
**Pull request by jmartisk**
see https://bugzilla.redhat.com/show_bug.cgi?id=1633506
@rubenvp8510 please take a look

### CODE REVIEW

**Comment by mtnbikenc** [comment]
This PR has become stale and the bug referenced has been closed deferred.  Please reopen this PR if the change is still required.

**Comment by jmartisk** [comment]
We have customers asking about this. Who could help get this reviewed and merged? @vrutkovs ?

**Comment by rubenvp8510** [comment]
I reviewed this and looks good, unfortunately I don't have the rights for merge it.

**Pull request merged**
