### PR TITLE
[3.6] GlusterFS: enable modprobe in pods that manage bricks

### PR DESCRIPTION
**Pull request by DanyC97**
Backports #7831
@jarrpa pls help review

### CODE REVIEW

**Comment by jarrpa** [comment]
/lgtm
/ok-to-test
bot, test pull request

**Comment by DanyC97** [comment]
@sdodson master branch PR reference is https://github.com/openshift/openshift-ansible/pull/7831

**Comment by DanyC97** [comment]
@sdodson PR description updated as suggested, thx

**Comment by DanyC97** [comment]
@jarrpa @sdodson any idea holds this PR ?

**Comment by DanyC97** [comment]
@jarrpa gentle reminder ;)

**Pull request merged**
