### PR TITLE
Sync 1.5 excluders with master

### PR DESCRIPTION
**Pull request by ingvagabund**
Updating excluders in 1.5 so they are in sync with master.
- Rework openshift_excluder role: https://github.com/openshift/openshift-ansible/pull/4176
Supporting PRs:
- upgrade refactoring https://github.com/openshift/openshift-ansible/pull/4038
- run excluders only over selected hosts: https://github.com/openshift/openshift-ansible/pull/3879
- excluder-free rpm version detection: https://github.com/openshift/openshift-ansible/pull/4065
- refactor initialize groups: https://github.com/openshift/openshift-ansible/pull/3895

This will require a lot of testing:
* [x] - test 3.3 deployment 
* [x] - test 3.4 deployment 
* [x] - test 3.5 deployment 
* [x] - test 3.3 -> 3.4 upgrade
* [x] - test 3.3 -> 3.4 upgrade (node only)
* [x] - test 3.3 -> 3.4 upgrade (control plane only)
* [x] - test 3.4 -> 3.5 upgrade
* [x] - test 3.4 -> 3.5 upgrade (node only)
* [x] - test 3.4 -> 3.5 upgrade (control plane only)
* [x] - test 3.5 -> 3.5 upgrade
* [x] - test 3.5 -> 3.5 upgrade (node only)
* [x] - test 3.5 -> 3.5 upgrade (control plane only)
* [x] - test 3.3 node scale up
* [x] - test 3.4 node scale up
* [x] - test 3.5 node scale up
* [x] - test 3.3 master scale up
* [x] - test 3.4 master scale up
* [x] - test 3.5 master scale up

Questions:
* [ ] - do we have python-ruamel-yaml in 3.3 and 3.4 repos?

Issues to open:
* [ ] - extend repoquery to cover dnf as well (currently, it is yum based systems only)
* [ ] - docker excluder is not correctly upgraded from 3.3 to 3.4 (3.3 docker excluder excludes 1.12, once it gets updated to 3.4, the `docker*1.12*` is still left inside `/etc/yum.conf` even if 3.4 docker excluder excludes from 1.13. The docker-excluder needs to be unexcluded before it is upgraded and then re-excluded back). This needs to be catched in the CI for various upgrade scenarious (3.d -> 3.d, 3.3 -> 3.4, 3.4 -> 3.5)

### CODE REVIEW

**Comment by ingvagabund** [comment]
aos-ci-test

**Comment by ingvagabund** [comment]
aos-ci-test

**Comment by ingvagabund** [comment]
@sdodson once atomic-openshift 3.3 is built with updates spec files, I will remove `disable docker-excluder during its upgrade` commit.

**Comment by ingvagabund** [comment]
[merge]

**Comment by ingvagabund** [comment]
I will integrate #3938 in a separate PR. I believe there will be more improvements to backport to 1.5 and lower branches.

**Comment by sdodson** [comment]
That's a defect in the CI jobs.

**Pull request merged**
