### PR TITLE
OCPBUGS-29561: Install ose-aws-ecr-image-credential-provider

### PR DESCRIPTION
**Pull request by patrickdillon**
This is a new package required since 4.14.11

/jira cherry-pick OCPBUGS-29527

### CODE REVIEW

**Comment by patrickdillon** [comment]
/hold 

Need to fix base branch

**Comment by sdodson** [comment]
Applying all necessary labels for this fix which needs to be backported to 4.14. it would ideally also make 4.15 GA but RHEL workers are small percentage of fleet and likely that this problem goes unnoticed in 4.15 for a while

**Pull request merged**
