### PR TITLE
add persistent versions of quickstarts

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@sdodson @luciddreamz ptal

**Comment by sdodson** [comment]
Did we want to get rid of the ephemeral examples too? I lost track of the intention of the email.

**Comment by sdodson** [comment]
aos-ci-test

**Comment by bparees** [comment]
> Did we want to get rid of the ephemeral examples too? I lost track of the intention of the email.

no, we need to keep ephemeral around because we want something to work out of the box when you may not have persistent volumes available.

**Pull request merged**
