### PR TITLE
Use empty default for storage labels

### PR DESCRIPTION
**Pull request by simon3z**
Just as #4514 also this needs to be fixed.

cc @ewolinetz @sdodson

### CODE REVIEW

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
[merge][severity: blocker]

**Comment by sdodson** [comment]
flake on https://github.com/openshift/origin/issues/14043 in https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_openshift_ansible/630/
[merge][severity:blocker]

**Comment by ewolinetz** [comment]
this addresses https://bugzilla.redhat.com/show_bug.cgi?id=1463055

**Comment by ewolinetz** [comment]
flaked on https://github.com/openshift/origin/issues/14043
[merge][severity:blocker]

**Pull request merged**
