### PR TITLE
Contiv backports from master

### PR DESCRIPTION
**Pull request by nbartos**

### CODE REVIEW

**Comment by nbartos** [comment]
@sdodson and @srampal, these are simple cherry pick backports from master.  Can you PTAL?  Thanks!

**Comment by sdodson** [comment]
bot, test pull request
/ok-to-test

**Comment by sdodson** [comment]
bot, test this please

**Comment by sdodson** [comment]
yup, no problem

**Comment by nbartos** [comment]
Thanks!

**Pull request merged**
