### PR TITLE
Bug 1749024: Update minimum required kernel version

### LINKED ISSUE #11883: The kernel version check comparison is not correct
#### Description

We tried installing a new OCP cluster using release-3.11 branch master and it failed with the following error 

```
Failure summary:


  1. Hosts:    ci-ocp-3-11-z-ocs-3-11-4-cns-compute-0, ci-ocp-3-11-z-ocs-3-11-4-cns-infra-0, ci-ocp-3-11-z-ocs-3-11-4-cns-master-0, ci-ocp-3-11-z-ocs-3-11-4-cns-storage-1, ci-ocp-3-11-z-ocs-3-11-4-cns-storage-2, ci-ocp-3-11-z-ocs-3-11-4-cns-storage-3
     Play:     Install packages necessary for installer
     Task:     Ensure minimum kernel version
     Message:  The installed kernel version does not meet the required minimum for RHEL 7.7.
               Please update the kernel before continuing.
               Minimum Kernel Version: 3.10.0-1062.el7
               Installed Kernel Version: 3.10.0-1062.1.1.el7.x86_64
               Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1749024

```

Provide a brief description of your issue here. For example:
Installation of OCP 3.11 fails.

##### Version
3.11

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Operating system is RHEL 7.7

Looks like this could be because of https://github.com/openshift/openshift-ansible/pull/11881

### PR DESCRIPTION
**Pull request by mtnbikenc**
Remove trailing distribution tag from version.

Fixes #11883

### CODE REVIEW

**Comment by mtnbikenc** [comment]
Still testing.
/hold

**Comment by mtnbikenc** [comment]
My testing shows this resolved the issue.
/hold cancel
/retest

**Comment by aliartiza75** [comment]
hi @mtnbikenc, I am using `release-3.11.146-1` version but still getting the same error.

**Pull request merged**
