### PR TITLE
Append playbook to install metrics only #2723

### LINKED ISSUE #2723: Suggest: append playbooks or tags to install only metrics
https://github.com/openshift/openshift-ansible/blob/master/playbooks/adhoc/metrics_setup/playbooks/install.yml will be deleted, see: #2717

Suggest: append playbooks or tags to install only metrics https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_metrics

@vnugent @sdodson 

Best regards,
Stéphane

### PR DESCRIPTION
**Pull request by harobed**
Append playbook to install metrics only

Fixes #2723

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@harobed thanks for the PR! Could you please update the PR description to include "fixes #\<issue-number\>"?

https://github.com/blog/1506-closing-issues-via-pull-requests

This way, whenever your PR gets merged the issue will be closed automatically.

**Comment by rhcarvalho** [comment]
@jcantrill FYI, I think your team is working on metrics installation playbooks?

**Comment by jcantrill** [comment]
@bbguimaraes can you evaluate what this means against https://github.com/openshift/openshift-ansible/pull/2873 

This will also require changes to be incorporated based on https://github.com/openshift/openshift-ansible/pull/2881  /cc @sdodson

**Comment by rhcarvalho** [comment]
Here're the new metrics playbooks: https://github.com/openshift/openshift-ansible/pull/2873

@jcantrill, is this PR useful for existing installations?

**Comment by jcantrill** [comment]
@rhcarvalho prior to 3.4 the role will need to be changed. 3.4+ looks like this would still be useful

**Comment by bbguimaraes** [comment]
@jcantrill: this is something that was already suggested for our logging PR, if
I remember correctly.  And it works for both the current (deployer-based)
installation and the new one, so it is useful.

**Comment by harobed** [comment]
Fixed by: https://github.com/openshift/openshift-ansible/blob/master/playbooks/byo/openshift-cluster/openshift-metrics.yml

**Pull request closed without merging**
