### PR TITLE
Refactored Calico and updated playbooks to reflect self-hosted Calico installs only

### PR DESCRIPTION
**Pull request by mgleung**
* Moved the `calico` role to `calico_node`
* Removed outdated commands in the `calico_node` (formerly `calico`) role
* Moved the `calico_master` role to `calico`
* Updated `openshift.master.sdn_cluster_network_cidr` usage to `openshift_cluster_network_cidr`
* Removed node selectors which were used for upgrading Calico running as a systemd service to a container

These changes follow the changes made in https://github.com/openshift/openshift-ansible/pull/9435 as well as add the new changes with `calico_node`.

### CODE REVIEW

**Comment by vrutkovs** [comment]
Seems `openshift start network` was deprecated and no longer present in 4.0 builds. @danwinship what's the new replacement for this command?

**Comment by danwinship** [comment]
@vrutkovs for now, if you just want proxy+dns, I believe `openshift start network` works. I'm not sure if that's going to change again before 4.0.

**Comment by danwinship** [comment]
er, except that it doesn't, which is what you just said. um...

**Comment by danwinship** [comment]
@vrutkovs For OpenShift SDN, the stuff that used to be `openshift start network` is now in a separate `openshift-sdn` binary. I'm not sure if you're supposed to use that binary to get proxy/dns for non-openshift-sdn plugins as well, though it probably will work as long as you have `networkPlugin` set appropriately (to a non-OpenShift plugin name) in `node-config.yaml`.

I think long term, the plan is that you should just be using upstream kube-proxy and DNS. I think?

**Comment by vrutkovs** [comment]
Right, that doesn't seem to be related to this PR, however it breaks non-openshift plugins.

I'll check if this also happens in 3.11

**Pull request merged**
