### PR TITLE
Use openshift.common.hostname when verifying API port available.

### PR DESCRIPTION
**Pull request by tremble**
$SSIA - inventory_hostname isn't guaranteed to be usable

### CODE REVIEW

**Comment by ingvagabund** [comment]
aos-ci-test

**Comment by ingvagabund** [comment]
@tremble is there any special policy to follow when back-porting changes from master branch? I see this is picked from https://github.com/openshift/openshift-ansible/pull/3032.

**Comment by tremble** [comment]
Unfortunately I don't know, I work for IT rather than Engineering.  Our self-service platform is using a dynamic inventory so we hit this during upgrades.

**Comment by sdodson** [comment]
> @tremble is there any special policy to follow when back-porting changes from master branch? I see this is picked from #3032.

Significant bug fixes should be backported to release-1.4 and release-1.3. Whereas release-1.2 only receives critical fixes at this point.

Will let @abutcher review and merge, I feel like we've flip flopped this code a bit so i'm not sure what the latest thinking is.

**Pull request merged**
