### PR TITLE
bug 1439451. Kibana memory limits

### PR DESCRIPTION
**Pull request by jcantrill**
(cherry picked from commit 66315ebbfcfda72d6f501c441359d92ec71af7d2)

### CODE REVIEW

**Comment by jcantrill** [comment]
aos-ci-test

**Comment by ingvagabund** [comment]
Why `736Mi` amd `96Mi`? :)

**Comment by sdodson** [comment]
[merge]

**Comment by jcantrill** [comment]
@ingvagabund Those defaults come from what the ops team is using in their environments.

**Comment by jcantrill** [comment]
[merge]

**Comment by ewolinetz** [comment]
merge flaked on https://github.com/openshift/origin/issues/14161

**Comment by ewolinetz** [comment]
[merge]

**Pull request merged**
