### PR TITLE
Ensure openshift_node variables adhere to naming standard.

### PR DESCRIPTION
**Pull request by jstuever**
This change renames openshift_node40 to openshift_node and ensures all of the variables adhere to a standard naming convention.

https://jira.coreos.com/browse/BYOH-232

### CODE REVIEW

**Comment by vrutkovs** [comment]
https://github.com/openshift/machine-config-operator/pull/549 should fix scaleup regression

**Comment by vrutkovs** [comment]
VMs could not be reached before provisioning

/retest

**Comment by vrutkovs** [comment]
/hold cancel
https://github.com/openshift/machine-config-operator/pull/564 fixes it

**Comment by vrutkovs** [comment]
Scaleup finally passes \o/

**Comment by stevekuznetsov** [comment]
So I am not really sure how that job ever ran on this PR -- it is configured to run against `master` but not `devel-40` -- @vrutkovs has something changed recently in your config?

**Comment by vrutkovs** [comment]
@stevekuznetsov nope, https://github.com/openshift/release/pull/3125 was the only touched it. Maybe its due to a removed `tag:` there?

**Comment by stevekuznetsov** [comment]
No, that only changes promotion. HRM. Is this happening on all PRs?

/override ci/prow/e2e-aws-scaleup-rhel7

**Comment by jstuever** [comment]
Going to wait and merge to master after #11358

**Comment by mtnbikenc** [comment]
Keep progressing on devel-40 until we have things settled with master.
/hold cancel

**Comment by mtnbikenc** [comment]
/retest
```
Failing tests:

[sig-cli] Kubectl Port forwarding [k8s.io] With a server listening on localhost [k8s.io] that expects a client request should support a client that connects, sends NO DATA, and disconnects [Suite:openshift/conformance/parallel] [Suite:k8s]
```

**Pull request merged**
