### PR TITLE
Fix templating issue with logging role

### PR DESCRIPTION
**Pull request by detiber**
resolves https://github.com/openshift/openshift-ansible/issues/1838

### CODE REVIEW

**Comment by abutcher** [comment]
There are a few more commands that need fixing. https://github.com/abutcher/openshift-ansible/commit/3bf12300f648d645d7ffbb816b7a8b9808f3d443

**Comment by detiber** [comment]
@abutcher think I've gotten all of those now.

**Comment by abutcher** [comment]
lgtm

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
@jayunit100 do you mind giving this a test?

**Comment by detiber** [comment]
aos-ci-test

**Comment by jayunit100** [comment]
This appears to fix the issue , thanks @detiber ,  just tested

**Pull request merged**
