### PR TITLE
Logging external config

### PR DESCRIPTION
**Pull request by ewolinetz**
These two commits are to help allow the ops team to have a centralized logging solution where there may be two different aggregated logging stacks installed.

@wshearn @jcantrill

### CODE REVIEW

**Comment by ewolinetz** [comment]
bot, retest this please

**Comment by ewolinetz** [comment]
Looks like the logging test passed successfully: 
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible_logging/7920

**Comment by ewolinetz** [comment]
@jcantrill @wshearn should we also cherrypick this to 3.9?

**Comment by jcantrill** [comment]
@ewolinetz yes

**Pull request merged**
