### PR TITLE
examples: include logging and metrics infrastructure

### PR DESCRIPTION
**Pull request by sosiouxme**

### CODE REVIEW

**Comment by sosiouxme** [comment]
@sdodson / @detiber / @abutcher feedback would be appreciated on whether this is the right approach.

**Comment by sdodson** [comment]
Looks like a fine approach to me.

**Comment by abutcher** [comment]
Looks good to me

**Comment by detiber** [comment]
I think this is a good path for the current supported approach (where we are not configuring the logging infrastructure for the user)

Once we move to deploying the infrastructure we might want to refactor a bit and not use openshift_examples as the base. But we can tackle that bridge when we get there.

**Comment by sosiouxme** [comment]
Cool, well then [merge] if you don't mind... any chance of this getting into the 3.1 RPM?

**Comment by abutcher** [comment]
@brenton

**Comment by detiber** [comment]
@sosiouxme 3.1 won't be an issue...  just waiting for @brenton to merge :)

**Pull request merged**
