### PR TITLE
Bug 2035494: Set keyfile to be the primary NetworkManager plugin

### PR DESCRIPTION
**Pull request by pliurh**
Be consistant with RHCOS

### CODE REVIEW

**Comment by pliurh** [comment]
This PR is to fix the regression introduced by https://github.com/openshift/machine-config-operator/pull/2742

**Comment by patrickdillon** [comment]
Thank you for opening this PR.

> Be consistant with RHCOS

openshift-ansible is only accepting critical bug fixes, particularly those that block upgrades and/or block a customer. https://bugzilla.redhat.com/show_bug.cgi?id=2035494 targets 4.X. 

If you think this fix fits those criteria can you explain, preferably in a BZ, why this is important for 3.X.

If not, I think we should close this as we are minimizing changes to 3.X.

**Comment by patrickdillon** [comment]
Please ignore my earlier comment (which I deleted, but you probably received an email notification of). I mistook this for a 3.X contribution.

**Comment by pliurh** [comment]
@patrickdillon The CI jobs keep failing. But I don't think it is caused by this PR. Do you have any comments to the code change?

**Comment by patrickdillon** [comment]
unit test is broken with: https://bugzilla.redhat.com/show_bug.cgi?id=2040488

workers test is broken with: https://bugzilla.redhat.com/show_bug.cgi?id=2038405

/approve
/override ci/prow/e2e-aws-workers-rhel7
/override ci/prow/e2e-aws-workers-rhel8
/override ci/prow/unit

**Pull request merged**
