### PR TITLE
[WIP] Implement multiline aggregation

### PR DESCRIPTION
**Pull request by AlessandroMenti**
This PR implements multiline log aggregation and is meant to be merged with the following PRs:

* [`openshift-docs`](https://github.com/openshift/openshift-docs/pull/11642)
* [`origin-aggregated-logging`](https://github.com/openshift/origin-aggregated-logging/pull/1302)

The PR also requires that the relevant packages added in the Dockerfiles are added to the upstream repositories (SRPMs and SPECs can be found at https://github.com/AlessandroMenti/openshift-kafka-for-fluentd-rpms).

### CODE REVIEW

**Comment by richm** [comment]
We would prefer to have all of the separate config files in the image itself (in origin-aggregated-logging/fluentd).  If you rename the files to be `filter-post-*` then the `@include filter-post-*.conf` will pick them up.  The files will be processed in US-ASCII order.  Then you could withdraw this PR.

**Comment by richm** [comment]
@AlessandroMenti Right, they need to be user editable.  There are other places in logging where we need to do the same thing.  It's kind of hacky, and we should probably completely redo the fluent.conf to accommodate user define configuration, but this is how we do it: https://github.com/openshift/origin-aggregated-logging/blob/master/fluentd/run.sh#L103

Basically, copy the files provided with the image into the right place, and if the user has provided any files in the configmap, use those files instead.

**Comment by AlessandroMenti** [comment]
@richm Done.

**Comment by vrutkovs** [comment]
Master branch is closed! A major refactor is ongoing in devel-40. Changes for 3.x should be made directly to the latest release branch they're relevant to and backported from there.

**Comment by AlessandroMenti** [comment]
@vrutkovs Sorry for the late reply, I'll make a new PR against that branch then.

**Pull request closed without merging**
