### PR TITLE
Bug 2105056: CI 4.11 backport

### PR DESCRIPTION
**Pull request by barbacbd**
Merged in:
#12411 
#12399 
#12405 
#12407

### CODE REVIEW

**Comment by barbacbd** [comment]
@yselkowitz should we cancel the cherry pick approved above so it does not go back too far ?

**Comment by patrickdillon** [comment]
> @yselkowitz should we cancel the cherry pick approved above so it does not go back too far ?

I switched the target release on the bz to 4.11.z instead 

/bugzilla refresh

**Comment by yselkowitz** [comment]
pause automation until code freeze lifts and we can proceed
/hold

**Review by jstuever — APPROVED** [review]
/approve

**Pull request merged**
