### PR TITLE
Bug 1874324: Update playbook to install and activate openvswitch2.13

### PR DESCRIPTION
**Pull request by dcbw**
Replaces https://github.com/openshift/openshift-ansible/pull/12216

Mike is on PTO so I'll take this bit over.

@trozet @mccv1r0

### CODE REVIEW

**Comment by mtnbikenc** [comment]
Looks like you are running into a package dependency problem.
```
Error: Package: openvswitch2.13-2.13.0-29.el7fdp.x86_64 (rhel-7-server-ose-4.6-devel-rpms)
           Requires: openvswitch-selinux-extra-policy
```

That package appears to be in the fast-datapath channel which we don't currently have configured for CI.  Fast-datapath should be added to the mirror in https://mirror.openshift.com/enterprise/reposync/ci-deps/ and then we would need to update the rhel repo config in the release repo.

**Comment by dcbw** [comment]
> That package appears to be in the fast-datapath channel which we don't currently have configured for CI. Fast-datapath should be added to the mirror in https://mirror.openshift.com/enterprise/reposync/ci-deps/ and then we would need to update the rhel repo config in the release repo.

@mtnbikenc who is responsible for making that available to CI? It's already availble for all other OpenShift CI. If it's a change to openshift/ocp-build-data or openshift/release, cna you point me to the files that would enable those repos?

**Comment by mtnbikenc** [comment]
> > That package appears to be in the fast-datapath channel which we don't currently have configured for CI. Fast-datapath should be added to the mirror in https://mirror.openshift.com/enterprise/reposync/ci-deps/ and then we would need to update the rhel repo config in the release repo.
> 
> @mtnbikenc who is responsible for making that available to CI? It's already availble for all other OpenShift CI. If it's a change to openshift/ocp-build-data or openshift/release, cna you point me to the files that would enable those repos?

You say it's already available.  Could you point to where?

This is how repos on the hosts are configured.  This is where we would make changes to point to new locations.
https://github.com/openshift/release/blob/master/ci-operator/step-registry/workers-rhel7/repos/workers-rhel7-repos-commands.sh

**Comment by dcbw** [comment]
@mtnbikenc I was corrected by @jupierce . This PR should add them to the mirrors: https://github.com/openshift/ocp-build-data/pull/637

**Comment by mtnbikenc** [comment]
@dcbw I'll open the release PR to get the repos on the host.

**Comment by dcbw** [comment]
https://github.com/openshift/ocp-build-data/pull/637 merged, FWIW

**Comment by mtnbikenc** [comment]
Waiting for the new repo to show up here, https://mirror.openshift.com/enterprise/reposync/ci-deps/

**Comment by mtnbikenc** [comment]
Release PR for adding the fast-datapath repo, https://github.com/openshift/release/pull/11632

**Comment by mtnbikenc** [comment]
Release repo PR merged.
/retest

**Review by mtnbikenc — APPROVED** [review]
/lgtm

**Comment by yigitpolat** [comment]
Hello, 
I was trying to install RHEL worker nodes with the playbook and got the below error. I could fix it by removing the specific version declared in main.yml. Finally it installed openvswitch2.19 and worked as expected. I couldn't be sure if it is a bug but playbook didn't work without this modification. Best regards.
error

**Pull request merged**
