### PR TITLE
redhat-ci: use requirements.txt

### PR DESCRIPTION
**Pull request by jlebon**
Use requirements.txt rather than hardcoding the ansible version here.
Also update the comment re. `rpm-ostree status`.

### CODE REVIEW

**Comment by jlebon** [comment]
@rhcarvalho This PR addresses concerns raised in #4005. Mind reviewing it and the sister PR https://github.com/openshift/openshift-ansible/pull/4012? I'd like to get those testers fixed so we can build confidence and work towards gating on them.

**Comment by rhcarvalho** [comment]
Why do we name the files "redhat-\*" and the CI job is "fedora/\*"?

**Comment by jlebon** [comment]
> Why do we name the files "redhat-*" and the CI job is "fedora/*"?

It's more a convention that developed of naming it after the platform on which the test is done. E.g. we might later on add a second `fedora/26/atomic` tester. I'm open to other naming schemes if you'd like.

> Would you mind documenting these files and tests / test environment / CI jobs as appropriate?

Ahh nice. Yup, will do.

**Comment by jlebon** [comment]
The files themselves are named `.redhat-ci.*` because they're used by the redhat-ci framework: https://github.com/jlebon/redhat-ci (which is what actually runs the tests).

**Comment by ashcrow** [comment]
aos-ci-test

**Comment by rhcarvalho** [comment]
I created #4078 to track documenting the CI jobs. We can [merge] this.

**Comment by ashcrow** [comment]
[merge]

**Pull request merged**
