### PR TITLE
logging set memory request to limit

### PR DESCRIPTION
**Pull request by richm**
resubmitting https://github.com/openshift/openshift-ansible/pull/5119
@jcantrill @sdodson @portante ptal

### CODE REVIEW

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[test]

**Comment by jcantrill** [comment]
[merge]

**Comment by richm** [comment]
flake?  tests passed but cleanup failed?
```
Ginkgo ran 1 suite in 11m46.267450711s
Test Suite Passed
[INFO] [CLEANUP] Beginning cleanup routines...
[INFO] [CLEANUP] Removing docker containers
Error response from daemon: You cannot remove a running container cbb7dbcbecf79d55435cd231350fdb1feee136f714f9c8763941e573878cd72d. Stop the container before attempting removal or use -f
...
[INFO] [CLEANUP] Pruning etcd data directory
rm: cannot remove ‘/tmp/etcd/member’: Permission denied
[ERROR] test/extended/conformance.sh exited with code 1 after 00h 44m 31s
make: *** [test-extended] Error 1
++ export status=FAILURE
```

**Comment by richm** [comment]
[merge]

**Comment by sdodson** [comment]
[merge]

**Comment by sdodson** [comment]
@richm does that failure look related or no? I'm not sure what the expectations of the logging job are today, seems a bit flaky.

**Comment by jcantrill** [comment]
[merge] flake?  Looking at a few other jobs since this failure, this test is passing

**Pull request merged**
