### PR TITLE
Enable htpasswd by default in the example hosts file.

### PR DESCRIPTION
**Pull request by aveshagarwal**

### CODE REVIEW

**Comment by aveshagarwal** [comment]
@detiber

**Comment by detiber** [comment]
:+1: @brenton pls2merge

**Comment by brenton** [comment]
What was the default before?  Deny?  I'm assuming this is technically the same.  Admins can still auth via certificates.  Everyone else will still be denied until they have an entry in the htpasswd file.

**Comment by aveshagarwal** [comment]
Upto beta4, the hosts file https://github.com/openshift/training/blob/master/deprecated/beta4/ansible/hosts had it enabled by default. 

And also atomic-enterprise-ansible, by default:
https://github.com/projectatomic/atomic-enterprise-ansible/blob/master/inventory/byo/hosts

I think the reason to enable it by default is that the first thing AE or openshift training guide asks is to enable htpasswd auth:

https://github.com/openshift/training/blob/master/03-Auth-Projects-and-Web-Console.md

And it reads: "...Ansible was configured to edit the oauthConfig's identityProviders stanza so that it looks like the following.." and that sounds like ansible enables it by default even though the guide asks to perform the same steps next.

And it saves atleast following steps: a) reconfiguring master config, b) restarting master

**Comment by brenton** [comment]
I'm including this PR in a batch to be tested by QE.

**Comment by aveshagarwal** [comment]
@brenton any update?

**Comment by brenton** [comment]
@detiber, I was planning to wait until the AEP merge landed but since that needs additional work I'll just merge this now.  QE already verified there were no regressions with this change.

**Pull request merged**
