### PR TITLE
docker: Move enterprise registry from pkg to main

### PR DESCRIPTION
**Pull request by ashcrow**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1503860

### CODE REVIEW

**Comment by ashcrow** [comment]
flake https://github.com/openshift/origin/issues/14228

**Comment by ashcrow** [comment]
flake https://github.com/openshift/origin/issues/14228

**Comment by ganhuang** [comment]
@ashcrow The PR doesn't seems to fix the issue. IMO it should be an incorrect usage. 

In the bug we still need `openshift_docker_additional_registries` set.

**Comment by ganhuang** [comment]
Oh, anyway `openshift_docker_ent_reg: 'registry.access.redhat.com'` should be added to `additional_registries` by default. LGTM

**Pull request merged**
