### PR TITLE
Add UDP 4789 firewall rule when using the SDN

### LINKED ISSUE #632: Cannot pull from Docker Registry on other node
I have one master-server, a node1-server and a node2-server. They're all on CentOS instances of AWS. I've created my docker registry on my master-machine. After a while I saw the registry was put on node 1. I don't know if this is normal. After that I want to create my first project and app. Also on the master-machine but it was all in containers on my node1. When I tried to create more pods (than one) I did the following command: 
```
oc scale rc test-1 --replicas=4
```
After that the're were created 4 pods. 2 of the pods are on the node1 (where the registry is), the other 2 on node2. The pods on node1 are running fine but the pods on node2 are unable to find the image.

```
[root@ip-10-0-0-135 centos]# oc get pods
NAME           READY     STATUS          RESTARTS   AGE
test-1-6oz3v   1/1       Running         0          1h
test-1-8zt9q   1/1       Running         0          1h
test-1-build   0/1       ExitCode:0      0          1h
test-1-fkvas   0/1       no such image   0          1h
test-1-or31p   0/1       API error (500): invalid registry endpoint "http://172.30.26.202:5000/v0/". HTTPS attempt: unable to ping registry endpoint https://172.30.26.202:5000/v0/
v2 ping attempt failed with error: Get https://172.30.26.202:5000/v2/: read tcp 172.30.26.202:5000: connection reset by peer
 v1 ping attempt failed with error: Get https://172.30.26.202:5000/v1/_ping: read tcp 172.30.26.202:5000: connection reset by peer. HTTP attempt: unable to ping registry endpoint http://172.30.26.202:5000/v0/
v2 ping attempt failed with error: Get http://172.30.26.202:5000/v2/: read tcp 172.30.26.202:5000: connection reset by peer
 v1 ping attempt failed with error: Get http://172.30.26.202:5000/v1/_ping: read tcp 172.30.26.202:5000: connection reset by peer
```
```
NAME      DOCKER REPO                    TAGS      UPDATED
test      172.30.26.202:5000/test/test   latest    About an hour ago
```
I think they can not access the docker registry but I don't know why. Is there a solution for this?

### PR DESCRIPTION
**Pull request by sdodson**
Maybe fixes #632 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1273129

CC: @thoraxe

### CODE REVIEW

**Comment by sdodson** [comment]
@thoraxe `git pull https://github.com/sdodson/openshift-ansible sdn-iptables` to verify this sets the rule?

**Comment by jaryn** [comment]
Can one of the admins verify this patch?

**Comment by thoraxe** [comment]
```
-A OS_FIREWALL_ALLOW -p udp -m state --state NEW -m udp --dport 4789 -j ACCEPT
```

LGTM.

**Comment by jaryn** [comment]
Can one of the admins verify this patch?

**Comment by sdodson** [comment]
@brenton QE verified the referenced bug, i think this is good to merge now.

**Comment by detiber** [comment]
@sdodson :+1:  for the change, previously the sdn would open the port itself, so I would expect there to be a change upstream that introduced the change in behavior.

**Pull request merged**
