### PR TITLE
Issue361 - MatchNodeSelector should be first

### LINKED ISSUE #361: Scheduler config does not include MatchNodeSelector
The `MatchNodeSelector` predicate should be first in the list of predicates in the scheduler configuration file, or the scheduler will not honor the pod nodeSelector field:
```
{
  "predicates": [
    {"name": "MatchNodeSelector"},
    ...
}
```

### PR DESCRIPTION
**Pull request by sdodson**
Fixes #361

### CODE REVIEW

**Comment by sdodson** [comment]
@detiber PTAL

**Comment by liggitt** [comment]
I'd like @abhgupta or @ncdc to double check this as well... I tested it, but am new to the scheduler bits

**Comment by ncdc** [comment]
At quick glance it seems reasonable, but I would like more input from those more familiar with the scheduler.

cc @derekwaynecarr @smarterclayton

**Comment by detiber** [comment]
@sdodson lgtm

**Comment by liggitt** [comment]
I just confirmed the MatchNodeSelector is in the default scheduler predicate set when running without a config file, and is the predicate expected to restrict pods from getting scheduled on nodes that don't match. Can wait for an ok from @smarterclayton if you want, but I'm more sure of this fix now

**Comment by smarterclayton** [comment]
This is LGTM

On Jul 17, 2015, at 7:22 PM, Jordan Liggitt <notifications@github.com>
wrote:

I just confirmed the MatchNodeSelector is in the default scheduler
predicate set when running without a config file, and is the predicate
expected to restrict pods from getting scheduled on nodes that don't match.
Can wait for an ok from @smarterclayton <https://github.com/smarterclayton>
if you want, but I'm more sure of this fix now

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/openshift-ansible/pull/362#issuecomment-122444630>
.

**Comment by abhgupta** [comment]
LGTM

**Pull request merged**
