### PR TITLE
Setting defaults on openshift_hosted even when not installing.

### PR DESCRIPTION
**Pull request by kwoodson**

### CODE REVIEW

**Comment by kwoodson** [comment]
@abutcher @sdodson 

When @mwoodson attempted to install 3.5 using the byo today we ran into undefined variables in the router.yml role when setting the variables to false.
```
openshift_hosted_manage_router=false
openshift_hosted_manage_registry=false
```

I reran with these fixes and it was able to get passed the undefined failures.

**Comment by kwoodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
@abutcher will this be problematic?

**Comment by kwoodson** [comment]
aos-ci-test

**Comment by kwoodson** [comment]
@sdodson, @stevekuznetsov, 

```    error: package directory 'taskrunner' does not exist```

This was from the containerized failure.  I'm not sure what this means.

**Comment by abutcher** [comment]
aos-ci-test

**Comment by abutcher** [comment]
[merge]

**Pull request merged**
