### PR TITLE
Add openstack docs about swift/ceph rados gw backed registry

### PR DESCRIPTION
**Pull request by tzumainn**

### CODE REVIEW

**Comment by tomassedovic** [comment]
The content looks good, but the formatting is off:

https://github.com/tzumainn/openshift-ansible/blob/e309b226cc652b44a70ff1290ccaecd86e685daa/playbooks/openstack/configuration.md#swift-or-ceph-rados-gw-backed-registry-configuration

each bullet point seems to be missing the second backtick that closes the code formatting.

**Comment by tomassedovic** [comment]
@tzumainn I just had a look at this again and the formatting is still broken. Is it possible you've missed my previous comment?

**Comment by tzumainn** [comment]
@tomassedovic I totally did miss your first comment, sorry! I'll fix that

**Comment by tzumainn** [comment]
@tomassedovic should be fixed now!

**Pull request merged**
