### PR TITLE
Fixes #1729 fix xpaas example syntax

### LINKED ISSUE #1729: Typo for "Kind" and "Name" in xpass image stream template file
Met below errors when installing ose 3.2 with ansible:

"stderr: Error from server: ImageStream "jboss-eap70-openshift" is invalid: [spec.tags[1.3-Beta].from.name: Invalid value: "": must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[1.3-Beta].from.name: Required value: name is required, spec.tags[1.3-Beta].from.kind: Required value: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag']
Error from server: ImageStream "redhat-sso70-openshift" is invalid: [spec.tags[1.3-TP].from.name: Invalid value: "": must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[1.3-TP].from.name: Required value: name is required, spec.tags[1.3-TP].from.kind: Required value: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag']"

The keywords name should be "kind" and "name", but not "Kind" / "Name"

Typo locations:
[1] https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/files/examples/v1.2/xpaas-streams/jboss-image-streams.json#L155-L156

[2] https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/files/examples/v1.2/xpaas-streams/jboss-image-streams.json#L262-L263

### PR DESCRIPTION
**Pull request by jeremyeder**
Hit this as well.  Below changes fixes it for me.

### CODE REVIEW

**Comment by jeremyeder** [comment]
Fixes #1729

**Comment by detiber** [comment]
unrelated test failure.

lgtm @brenton

**Comment by detiber** [comment]
@jeremyeder I think the fixes statement needs to be in the description and not a comment for the auto-close to work correctly.

**Comment by sdodson** [comment]
#1728 already did this, why isn't github detecting this as a merge conflict?

**Comment by sdodson** [comment]
@jeremyeder this can be closed, right?

**Comment by sdodson** [comment]
@jeremyeder this can be closed, right?

**Pull request closed without merging**
