### PR TITLE
[BZ 1497408] delete config map, dameon set, and cluster role

### PR DESCRIPTION
**Pull request by jsanda**
This needs to get merged into the 3.7 branch as well.

### CODE REVIEW

**Comment by jsanda** [comment]
@ewolinetz or @sdodson can you please review this? Thanks.

**Comment by mburke5678** [comment]
@jsanda @sdodson @ewolinetz Does this playbook need to be executed manually? Came across this issue when reviewing doc bugs for the 3.9 release/

**Comment by ewolinetz** [comment]
@mburke5678 it's the normal metrics playbook, however this task is executed when `openshift_metrics_install_hawkular_agent=false`

**Pull request merged**
