### PR TITLE
Refactor upgrade

### PR DESCRIPTION
**Pull request by detiber**

### CODE REVIEW

**Comment by detiber** [comment]
@dgoodwin At this point, I've split the playbooks into two. Will continue refactoring to remove duplication on Monday

**Comment by dgoodwin** [comment]
I will prep the atomic-openshift-installer to call these in separate branch for now.

**Comment by dgoodwin** [comment]
For consideration, could we boil it down to just a v3_0 and v3_1 playbook or do you feel there will be separate playbooks for minor upgrades that couldn't easily meld together? As a guy choosing a playbook to run it's be slightly nicer to just pick the "get me to 3.1" playbook.

**Comment by detiber** [comment]
@dgoodwin I think as we start getting more advanced with the upgrades, we'll want to have flags for enabling certain features for certain versions. Also, we can expect major upgrades to require more complicated logic than minor upgrades.

At least for testability, I think we should probably keep them separate. Otherwise I fear that we could easily cause.

One thing we can do to make upgrades easier to consume from a playbook is to have a single playbook wrapper that can call the write upgrade script based on the current running version and the available version. I'll plan to work something up for that.

**Comment by dgoodwin** [comment]
That sounds good to me.

We could also possibly lean on atomic-openshift-installer for handling that
logic.

**Comment by detiber** [comment]
@brenton @abutcher @dgoodwin Could use some extra eyes here.
- Split the playbooks into 2, one for the v3.0 minor upgrades
- Moved the upgrade playbooks to playbooks/common/openshift-cluster
- Created a wrapper around the common playbooks for byo
- Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1279733
- Addresses https://github.com/openshift/openshift-ansible/issues/853 ( just lifted @abutcher's changes wholesale for this)

**Comment by abutcher** [comment]
Pacemaker HA upgrade ran flawlessly.

**Comment by brenton** [comment]
This also fixes https://bugzilla.redhat.com/show_bug.cgi?id=1279736.

**Comment by brenton** [comment]
Appears to also fix https://bugzilla.redhat.com/show_bug.cgi?id=1280230

**Pull request merged**
