### PR TITLE
Updated container to be able to build from CentOS Container Pipeline.

### PR DESCRIPTION
**Pull request by mohammedzee1000**
This is for the purpose of building this container from CentOS Container Pipeline.

Signed-off-by: mohammedzee1000 <mohammed.zee1000@gmail.com>

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
@codificat @aweiteka Any more action needed on this?

**Comment by codificat** [comment]
@mohammedzee1000 thanks for the reminder and apologies for the delay.

Also: I'm sorry but I just noticed I already changed the `FROM` in the Dockerfile in commit 32b7b0ab while changing references to images... this will cause a conflict with your commit, sorry :( .

If you can remove that line change in the `Dockerfile` we can then add the `.cccp.yml` file... thanks again.

**Comment by mohammedzee1000** [comment]
@codificat so is image name going to be openshift-ansible or origin-ansible?

**Comment by codificat** [comment]
Sorry should have ellaborated more.

The image has been renamed to `openshift/origin-ansible`. This is to address the use case of `oc cluster up` that will use the image to deploy logging and metrics, and it needs it to fit `imageConfig.format` like the rest of platform images (e.g. `openshift/origin-deployer` etc).

The commit I mentioned does that rename (and associated references/scripts).

**Comment by mohammedzee1000** [comment]
@codificat i have rebased and updated the name :)

**Comment by codificat** [comment]
aos-ci-test

**Comment by mohammedzee1000** [comment]
@codificat i dont see anything wrong in the cccp.yml.

**Comment by codificat** [comment]
@mohammedzee1000 yeah, it's quite picky but... yamllint is complaining about a trailing space in lines 1 and 3 (the comment!) and warning about the missing start of YAML doc - you can see the [details link next to the continous-integration/travis-ci/pr](https://travis-ci.org/openshift/openshift-ansible/jobs/242271949#L390-L402) failed check...

**Comment by mohammedzee1000** [comment]
@codificat i corrected the same errors but there still sames to be failure

**Comment by codificat** [comment]
Right, I forgot to mention it in the last comment but you can see it in travis' output:
```
  9:1       warning  missing document start "---"  (document-start)
```
So, you need to add that to the file...

**Comment by codificat** [comment]
aos-ci-test

**Comment by codificat** [comment]
@mohammedzee1000 this should finally pass :)  I'd only suggest squashing the 4 commits into one...

**Comment by mohammedzee1000** [comment]
Doing the same

**Comment by mohammedzee1000** [comment]
@codificat squashed

**Comment by codificat** [comment]
aos-ci-test

**Comment by mohammedzee1000** [comment]
@codificat any idea how long these tests will take.

**Comment by codificat** [comment]
aos-ci-test

**Comment by codificat** [comment]
While not technically a bug, [merge][severity: bug] as this is unrelated to devcut

**Comment by codificat** [comment]
flake: openshift/origin#14743

**Comment by mohammedzee1000** [comment]
@codificat any update on this?

**Comment by codificat** [comment]
@mohammedzee1000 so sorry for the delays here - this unfortunately hit issues during testing and merging processes, and right now we're in stage cut and only release blockers should merge.

Would it be ok to wait a few more days until the normal merge queue opens up again?

I know this small change should not cause any troubles, but we'd have to bypass the normal merge process to merge this right now, just checking if you'd be ok to wait just a bit more.

**Comment by mohammedzee1000** [comment]
@codificat understood, yea its ok

**Comment by michaelgugino** [comment]
Closing due to inactivity.

**Pull request closed without merging**
