### PR TITLE
bug 1568361. Modify persistent directory for logs

### PR DESCRIPTION
**Pull request by jcantrill**
Partially addresses: https://bugzilla.redhat.com/show_bug.cgi?id=1568361

### CODE REVIEW

**Comment by ewolinetz** [comment]
/hold
I'd like to see changes being made in https://github.com/openshift/origin-aggregated-logging/pull/1108 moved into here

**Comment by jcantrill** [comment]
@ewolinetz logging success: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/8125/test_pull_request_openshift_ansible_logging/8123/

**Pull request merged**
