### PR TITLE
Configure HAProxy helath check for Master HA

### PR DESCRIPTION
**Pull request by esevan**
This commit adds health check configuration to haproxy of loadbalancer node.

Signed-off-by: Eunsoo Park <esevan.park@samsung.com>

### CODE REVIEW

**Comment by esevan** [comment]
PTAL folks! review please~

**Comment by DanyC97** [comment]
@sdodson @michaelgugino @vrutkovs i guess this is a nice to have improvement, thoughts ?

**Comment by vrutkovs** [comment]
This would be HAProxy healthcheck, which would work, but it won't be reported anywhere afaik.

Maybe @simonpasquier knows if this even gets reported to Prometheus and can be properly monitored?

**Comment by michaelgugino** [comment]
@vrutkovs my main concern is 'would this break anything we do currently' or is this safe to use in all cases?

**Comment by esevan** [comment]
L4 health check is good, but in a sense of L7, it cannot monitor the API server is broken down. Of course API server does not say all of its health status, but at least we can flow traffic to another API server than the  API server which is saying "I'm not healthy..." to HAProxy.

It is a problem about API server health check algorithm if this is not safe to current working cluster.

**Comment by vrutkovs** [comment]
Master branch is closed! A major refactor is ongoing in devel-40. Changes for 3.x should be made directly to the latest release branch they're relevant to and backported from there.

**Pull request closed without merging**
