### PR TITLE
update byo hosts

### PR DESCRIPTION
**Pull request by scotthesterberg**
set deployment_type=origin, commented out enterprise repos openshift_additional_repos= and oreg_url=docker-buildvm-

### CODE REVIEW

**Comment by detiber** [comment]
@scotthesterberg I'm a bit hesitant to allow for PRs specifically for the byo hosts file, since it is only meant to be an example. The exception would be if there were parameters missing that needed to be added to show how to use it.

I'm tempted to actually rename the file and add playbooks/byo/hosts to the .gitignore to avoid having a functional byo hosts file present.

@twiest thoughts?

**Comment by scotthesterberg** [comment]
I believe  that has already been done, as hosts is no longer in playbook, I edited the file in inventory. 
bluf: with 1.0.0 you could copy the hosts file over from playbook/byo to /etc/ansible/hosts add in your hosts with a sed script and away you go. This was broken when hosts removed from playbook. I wanted to enable the same with the hosts in inventory. Probably a non-issue

It can be left as is, but it would be more usable, for origin, hosts file. 
I wanted to make it work better for scripted installs. Reason being, it is fine that there is a working example embedded in README_origin.md, but if someone wants to script the install without having to manually create the hosts file and source it elsewhere it’s much nicer to have a usable form come down with the git pull, like it did with the 1.0.0 release.

I have written a sed script that also fixes the inventory hosts file that could be added into the README_origin.md documentation:
sed -i -e 's/deployment_type=enterprise/deployment_type=origin/g' -e 's/oreg_url=docker-buildvm/#oreg_url=docker-buildvm/g' -e 's/^openshift_additional_repos=/#openshift_additional_repos=/g' ~/openshift-ansible/inventory/byo/hosts

**Comment by detiber** [comment]
@scotthesterberg Ah, I meant inventory/byo/hosts instead of playbooks/byo/hosts. We plan on extending the installer wrapper for OpenShift Enterprise to also support Origin installs, which would account for the scripted install process, and the long term goal there is to have the installer wrapper included within openshift-ansible repo itself as well.

Long term, I expect that the only people who will be invoking the playbooks directly using ansible-playbook will be those that explicitly want to use ansible to manage their environments, and I would expect that they would manage their openshift hosts alongside the rest of their infrastructure.

**Comment by twiest** [comment]
@detiber I don't do much with byo, so I'll defer to your judgement. What you propose seems reasonable to me.

Let me know what you'd like done with this PR.

**Comment by detiber** [comment]
@twiest I have a PR incoming that will make the existing inventory/byo/hosts inventory/byo/hosts.example with the goal of making it more explicit that it is intended to be an example to be modified rather than a file to be consumed.

**Comment by twiest** [comment]
@detiber ok, sounds good. In the mean time what should we do with this PR?

**Comment by detiber** [comment]
@twiest I say close this PR, the changes I have in mind will add a bit more documentation to the comments of the example file as well.

**Comment by twiest** [comment]
Closing per comment.

**Pull request closed without merging**
