### PR TITLE
[1.5] oo_collect: Allow list elements to be lists of dict

### PR DESCRIPTION
**Pull request by abutcher**

### CODE REVIEW

**Comment by abutcher** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by abutcher** [comment]
[merge][severity:bug]

**Comment by abutcher** [comment]
flake https://github.com/openshift/origin/issues/14752

**Comment by abutcher** [comment]
[merge][severity:bug]

**Comment by abutcher** [comment]
[merge][severity:bug]

**Pull request merged**
