### PR TITLE
Switch to origin-1.x branch names

### PR DESCRIPTION
**Pull request by sdodson**
Prepare to switch from `enterprise-3.x` to `origin-1.x` branch names.

### CODE REVIEW

**Comment by sdodson** [comment]
@maxamillion @elyscape thoughts on this? We decided that a public github project should more closely align with the project than downstream product. Though maybe `stable-1.x` or `release-1.x` (used by origin repo) is better now that I think about it.

**Comment by elyscape** [comment]
Either option sounds good to me!

**Comment by detiber** [comment]
@sdodson release-1.x is preferable to me than stable-1.x.

**Comment by maxamillion** [comment]
This is great! Thanks all involved. :+1:

**Comment by sdodson** [comment]
release-1.x it is, i'll prep our CI jobs for this today and duplicate branches after that's done and then purge the enterprise-3.x branches soon thereafter

**Pull request merged**
