### PR TITLE
[WIP] Vagrantfile updates

### PR DESCRIPTION
**Pull request by detiber**
Working on fixing up the Vagrantfile to support ha deployments and to also address other outstanding issues.

TODO:
- work out issue with VirtualBox networking
  - the default host-only network interferes with inter-host connectivity, and adding  second private network only seems to compound the issues.
- infra_nodes, nfs host are resolving to unqualified hostname master1 for an all-in-one deployment, I believe because it is using the inventory_hostname and not openshift_hostname

### CODE REVIEW

**Comment by detiber** [comment]
@abutcher do you have a machine with virtualbox laying around that you can use to help troubleshoot with?

**Comment by abutcher** [comment]
@detiber Yeah, I'll give it a run through.

**Comment by detiber** [comment]
@abutcher the issues in the PR description and the TODOs in the Vagrantfile in the PR are all outstanding issues as well.  I *almost* have a working all-in-one instance.

**Comment by abutcher** [comment]
Copying here:

Single master working pretty well. The registry PV came up with `master1` as the server -- we probably need to set `openshift_hosted_registry_storage_host` to ensure it gets the right value.

```
15m       5m        46        docker-registry-2-jpplm   Pod                 Warning   FailedMount   {kubelet openshift-master1.example.com}   Unable to mount volumes for pod "docker-registry-2-jpplm_default(bf884194-0721-11e6-ad44-525400b263eb)": Mount failed: exit status 32
Mounting arguments: master1:/exports/registry /var/lib/origin/openshift.local.volumes/pods/bf884194-0721-11e6-ad44-525400b263eb/volumes/kubernetes.io~nfs/registry-volume nfs []
Output: mount.nfs: Failed to resolve server master1: No address associated with hostname
```

**Comment by detiber** [comment]
@abutcher I rebased these changes and am giving it a quick once through. If a quick smoke test works I'm planning on merging even with the outstanding issues, to avoid having a Vagrantfile that is completely broken.

**Comment by detiber** [comment]
Okay, so the rebase is suffering from a bug.

On an all-in-one host, the master is trying to access etcd using a hostname, which is currently resolving to 127.0.0.1, which etcd is not listening on.

**Comment by tbielawa** [comment]
We no longer support vagrant in `openshift-ansible`. The vagrant file was removed in https://github.com/openshift/openshift-ansible/pull/2654 Please see https://github.com/openshift/openshift-ansible-contrib for vagrant support.

**Pull request closed without merging**
