### PR TITLE
add link to persistent storage config docs for docker-registry

### PR DESCRIPTION
**Pull request by maxamillion**

### CODE REVIEW

**Comment by maxamillion** [comment]
https://github.com/openshift/openshift-ansible/issues/403

**Comment by detiber** [comment]
:+1: @wshearn @twiest

**Comment by wshearn** [comment]
I am in favor of having persistent storage by default for the registry.

**Comment by detiber** [comment]
@wshearn The only issue I see with persistent storage by default for the registry, is that we do not know what type of persistent storage the user wants to configure if any.

**Comment by twiest** [comment]
:+1:

**Pull request merged**
