### PR TITLE
[BZ 1599241] Set UID,fsGroup and Linux options to cassandra RC's

### PR DESCRIPTION
**Pull request by rubenvp8510**

### CODE REVIEW

**Comment by vrutkovs** [comment]
Why not start with a PR to `master` and then cherrypick it back to 3.9?

**Comment by rubenvp8510** [comment]
@vrutkovs actually, this is a backport of https://github.com/openshift/openshift-ansible/pull/8831 which is already on master. 

This is the associated BZ https://bugzilla.redhat.com/show_bug.cgi?id=1599241

**Comment by vrutkovs** [comment]
ah, okay

/ok-to-test

**Comment by vrutkovs** [comment]
bot, test pull request

**Pull request merged**
