### PR TITLE
Define proxy settings for node services

### PR DESCRIPTION
**Pull request by sdodson**
Fixes Bug 1375031

### CODE REVIEW

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
@abutcher PTAL

**Comment by abutcher** [comment]
lgtm

**Comment by sdodson** [comment]
Included in https://github.com/openshift/openshift-ansible/pull/2542

**Comment by deanpeterson** [comment]
I have a master and node behind a proxy server. When I try to restart my node, i get atomic-openshift-node.service start operation timed out. I've set the http_proxy settings when installing via ansible. Am I being affected by this bug? Do I need to do something with proxy setting further to get the node back up and running?

image

**Pull request merged**
