### PR TITLE
Remove hidden tag for latest Fuse builders #11292

### PR DESCRIPTION
**Pull request by apupier**
it will allow to use them with odo

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

NOTICE
======

Master branch is closed! A major refactor is ongoing in devel-40.
Changes for 3.x should be made directly to the latest release branch they're
relevant to and backported from there.

### CODE REVIEW

**Comment by apupier** [comment]
@patrickdillon There are some failures in previous job. i tried to trigger a rebuild but seems that no new job has been triggered.
I don't understand very well the error test report so can't be sure that it is due to my PR or not. As it is really a simple PR, I would expect that it is not related.
Can you help me please?

**Comment by mtnbikenc** [comment]
Consecutive jobs flaked on different tests.
/override ci/prow/gcp
/override ci/prow/gcp-major-upgrade

**Pull request merged**
