### PR TITLE
GlusterFS: Recreate config directories for external uninstall

### PR DESCRIPTION
**Pull request by jarrpa**
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1651311

Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>

### CODE REVIEW

**Comment by sdodson** [comment]
/lgtm
/hold

@jarrpa LGTM, just setting a hold due to age, wanted you to take a quick look to make sure this still makes sense before it merges, if you want it just clear the hold with `/hold cancel`

**Comment by jarrpa** [comment]
@sdodson Somehow lost track of this one. Rebased to take into account recent changes.

**Comment by jarrpa** [comment]
@vrutkovs Test passed, could I get an LGTM?

**Pull request merged**
