### PR TITLE
Make the number of service catalog retries configurable

### PR DESCRIPTION
**Pull request by dyasny**
Fix for https://github.com/openshift/openshift-ansible/issues/8681

### CODE REVIEW

**Comment by sdodson** [comment]
/ok-to-test
bot, test pull request

**Comment by smarterclayton** [comment]
I asked in the issue to figure out what is wrong.

There is no reason crio should take longer than docker.  Please root cause this instead of putting in hacks.

**Comment by smarterclayton** [comment]
10m to start up service cat on crio is a bug in crio.

**Comment by dyasny** [comment]
I'll be happy to give access to my deployment, just ping me on IRC

**Pull request merged**
