### PR TITLE
Updating to use openshift.master.etcd_hosts for etcd servers for apis…

### PR DESCRIPTION
**Pull request by ewolinetz**
…erver

Should address https://bugzilla.redhat.com/show_bug.cgi?id=1466727
We will instead use the list of etcd_hosts which should resolve to actual hostnames not just the IP of the master

### CODE REVIEW

**Comment by sdodson** [comment]
I think if we're calling this playbook on its own we may need to add a dependency on openshift_master_facts. Which way did you test it? playbooks/byo/config.yml or playbooks/byo/openshift-cluster/service-catalog.yml?

**Comment by ewolinetz** [comment]
will add in fix for https://bugzilla.redhat.com/show_bug.cgi?id=1466233 on here since the same files are touched

**Comment by ewolinetz** [comment]
@sdodson i tested it with config.yml since that's the current intended path... i'll double check with the bolt on playbook as well

**Comment by ewolinetz** [comment]
second commit addresses bz1466233

**Comment by ewolinetz** [comment]
@sdodson verifying the bolt-on scenario now

**Pull request merged**
