### PR TITLE
[1537946] Correct conditional check for GlusterFS IPs

### PR DESCRIPTION
**Pull request by mtnbikenc**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1537946

### CODE REVIEW

**Comment by mjudeikis** [comment]
did you tested it? solves the issue?

**Comment by mtnbikenc** [comment]
I don't have an environment for testing glusterfs configurations.  The default is a list, which is what we should expect.
https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_facts/defaults/main.yml#L42

**Comment by mjudeikis** [comment]
k, I can test this later today in my aws lab... just need to get home. ETA 2-3 hours. But it should sort this out.

**Comment by mtnbikenc** [comment]
/hold
Pending further testing by @mjudeikis or @jarrpa

**Comment by mjudeikis** [comment]
rerun the prerequisites playbooks and seeing the same issue.. 
Inventory servers: 
```
        "glusterfs": [
            "54.175.161.104", 
            "54.204.175.93", 
            "34.204.88.26"
        ], 
        "glusterfs_registry": [
            "34.207.106.181", 
            "34.229.181.41", 
            "54.210.201.13"
        ], 

        "infra": [
            "35.153.127.249"
        ], 
        "masters": [
            "54.147.195.115"
        ], 
```
And suggested changes solves the issue...
Didn't ran full e2e install, as its kinda late where I am... 

Will test e2e install tomorrow while traveling, but this one particular looks good.

**Comment by mtnbikenc** [comment]
@mjudeikis @jarrpa  Any update on your testing?  This is a QE testblocker.

**Comment by mjudeikis** [comment]
From my side all good. Still didnt do full install but when it comes to pre-reqs playbooks it looks fine.

**Comment by jarrpa** [comment]
I couldn't get a proper test environment up before I went on PTO, so don't wait on me.

**Comment by mtnbikenc** [comment]
/hold cancel
@sdodson Can you lgtm?

**Comment by mjudeikis** [comment]
manage to do e2e tests. I started to see some other issues where Pods is being deployed to default namespace, instead of glusterfs... but this might be my env (as I kinda did cherry-picked glusterfs plays)... I suggest to merge and leave this for testing team, as things covered in this PR is all green

**Pull request merged**
