### PR TITLE
Don't pull cli image when we're not containerized

### PR DESCRIPTION
**Pull request by sdodson**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1336202

### CODE REVIEW

**Comment by sdodson** [comment]
aos-ci-test-extended

**Comment by sdodson** [comment]
@dgoodwin PTAL

**Comment by detiber** [comment]
@sdodson lgtm, is this ready to go?

**Comment by sdodson** [comment]
@detiber yup, good to go

**Pull request merged**
