### PR TITLE
Nuage service account handling by single master

### PR DESCRIPTION
**Pull request by vishpat**
@detiber @abutcher Handle Nuage service account creation on a single master

### CODE REVIEW

**Comment by detiber** [comment]
@vishpat Travis job error is for a yamllint failure related to trailing whitespace: https://travis-ci.org/openshift/openshift-ansible/jobs/210733645#L313-L330

You can run the tests locally by installing [tox](http://tox.readthedocs.io/en/latest/) and running `tox`

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
[merge]

**Comment by abutcher** [comment]
[merge]

**Comment by abutcher** [comment]
@sdodson @stevekuznetsov "No package matching 'origin-docker-excluder' found available, installed or updated"

**Comment by stevekuznetsov** [comment]
What do you mean, I don't see any failures? :)

**Pull request merged**
