### PR TITLE
Docker storage role.

### PR DESCRIPTION
**Pull request by kwoodson**

### CODE REVIEW

**Comment by twiest** [comment]
Looks great! :+1:

**Comment by detiber** [comment]
@kwoodson just curious, why not use docker-storage-setup?  It will be shipped with upstream RHEL and we will be shipping it in our beta4 repo in the interim.

**Comment by kwoodson** [comment]
@detiber I didn't know about docker-storage-setup.

**Comment by twiest** [comment]
@detiber would we use docker-storage-setup just on launch, or is it idempotent?

I'm not that familiar with it.

**Comment by detiber** [comment]
@twiest it'll only run once, the service will fail if run a second time (since the device(s) specified in the config file will already be in use).  There is an example of it's usage aws/openshift-cluster playbooks, with docker-storage setup being installed and enabled in templates/user_data.j2.

A few notes I've seen:
- for small storage configs, the metadata will run out of space, which will probably occur with the config in this PR as well.
- the docker-storage-setup service fails to start automatically before the docker service, it might have to do with the way we are invoking the docker service, but I haven't verified.
- I'd say it would probably be best to just invoke it once after instance creation

This shouldn't be a huge imposition to only be able to configure the docker storage config on instance boot, since we are moving towards the cattle model with v3 anyway.

**Comment by twiest** [comment]
Ok, interesting. We're using this on a generic RHEL7 box (not a master or node), so we don't intend on installing the COPR repos. So once that package is included in RHEL7, we'll switch it to docker-storage-setup and remove this role.

@kwoodson any objections to that plan?

@detiber Sound good?

**Comment by detiber** [comment]
@twiest sounds good.

**Pull request merged**
