### PR TITLE
add php 7.2 into 3.11 cause cuppet says 7.1 will no longer work with sclorg/cakephp-ex

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees @cuppett per Steve's recent findings in working https://github.com/sclorg/cakephp-ex this is an update so that php / cakephp is functional, minimally in 3.11 PR e2e's 

WDYT?

@adambkaplan FYI

### CODE REVIEW

**Comment by bparees** [comment]
/unassign

(I don't seem to have approval rights here)

**Review by mtnbikenc — APPROVED** [review]

**Pull request merged**
