### PR TITLE
replace samples with ones from origin v3.10

### PR DESCRIPTION
**Pull request by bparees**
https://bugzilla.redhat.com/show_bug.cgi?id=1600679

### CODE REVIEW

**Comment by bparees** [comment]
@sdodson ptal, fixes https://bugzilla.redhat.com/show_bug.cgi?id=1600679

**Comment by bparees** [comment]
this was the PR that pulled in 3.11 content: https://github.com/openshift/openshift-ansible/commit/fc2c2316ea08d0c59775b50daaeefcca9278d1a9

note that i did not revert any of the xpaas related changes, i am assuming they are still going to be ok, but if there wasn't a specific need to update the content for 3.10, it might make sense to just revert that entire commit.

**Comment by sdodson** [comment]
Can you change the branch that we source this from so it doesn't happen again? https://github.com/openshift/openshift-ansible/blob/release-3.10/roles/openshift_examples/examples-sync.sh#L12

**Comment by bparees** [comment]
> Can you change the branch that we source this from so it doesn't happen again? https://github.com/openshift/openshift-ansible/blob/release-3.10/roles/openshift_examples/examples-sync.sh#L12

done.

**Comment by bparees** [comment]
missed one change in jenkins-persistent template.  updated and re-lgtmed

**Comment by sdodson** [comment]
gcp-upgrade failed when installing 3.9 because it used ansible 2.6 and old code. Merging.

**Pull request merged**
