### PR TITLE
[release-3.10] Approve node CSRs during restart

### PR DESCRIPTION
**Pull request by mtnbikenc**
* Remove conditional associated with skipping checks during incremental
upgrades
* Use new oc_csr_approve

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1618659

### CODE REVIEW

**Comment by adammhaile** [comment]
/me watching... need to rebuild this ASAP

**Comment by mtnbikenc** [comment]
`operator Instantiate the template e2e-gcp into the operator namespace and wait for any pods to complete`
/test gcp

**Comment by sdodson** [comment]
These fixes are time critical and upgrades are not exercised by these tests.

**Pull request merged**
