### PR TITLE
dist.iteritems() no longer exists in Python 3.

### PR DESCRIPTION
**Pull request by adelton**
Fixes https://github.com/openshift/openshift-ansible/issues/6255.

### CODE REVIEW

**Comment by adelton** [comment]
@michaelgugino, it looks like the cherry picks to 3.7 and 3.6 failed. Should I file separate cherry pick pull requests?

**Comment by michaelgugino** [comment]
@adelton 
That would be great, thanks.

**Comment by adelton** [comment]
Cherry pick to 3.7: https://github.com/openshift/openshift-ansible/pull/6308.

Cherry pick to 3.6: https://github.com/openshift/openshift-ansible/pull/6309.

**Pull request merged**
