### PR TITLE
Support setting imagePolicyConfig JSON in inventory.

### PR DESCRIPTION
**Pull request by dgoodwin**
For flexibility this is another pure JSON field to translate directly to
yaml in the master config.

Also updated to more safely handle JSON inventory variables as this
uncovered a bug with booleans where you end up with a string containing
json in your yaml.

### CODE REVIEW

**Comment by dgoodwin** [comment]
aos-ci-test

**Comment by detiber** [comment]
@arilivigni test result links don't appear to be working.

**Comment by dgoodwin** [comment]
I mentioned to Ari as well, he's already got it fixed. :)

**Comment by arilivigni** [comment]
@detiber I already fixed it just add openshift after the https://aos-ci.s3.amazonaws.com/openshift-ansible/jenkins-openshift-ansible-run-e2e-tests-134/e60cc19e61e52292eae9f6ce0060d2d6b51b7b92.txt

ex.
https://aos-ci.s3.amazonaws.com/openshift/openshift-ansible/jenkins-openshift-ansible-run-e2e-tests-134/e60cc19e61e52292eae9f6ce0060d2d6b51b7b92.txt

**Comment by dgoodwin** [comment]
aos-ci-test

**Comment by detiber** [comment]
@dgoodwin can you add comments to the example inventory files to show how to set this and how to override the values if needed.

**Comment by dgoodwin** [comment]
Good idea, updated including a link to https://godoc.org/github.com/openshift/origin/pkg/cmd/server/api#ImagePolicyConfig, which is not totally in line with other links in there but it's the only thing available afaict, and is probably better than nothing, let me know if I should remove them though.

**Comment by dgoodwin** [comment]
@detiber @brenton could we get this one in today? @dak1n1 is asking, hoping to do another dev preview int build today.

**Comment by detiber** [comment]
@brenton lgtm

**Comment by dgoodwin** [comment]
@brenton nope just updates to the example inventories, should be good to go.

**Pull request merged**
