### PR TITLE
BZ 1442942: Fix paths for file includes

### PR DESCRIPTION
**Pull request by mtnbikenc**
`ansible-playbook --syntax-check` revealed path issues which are fixed.

Fixes 1442942

### CODE REVIEW

**Comment by sdodson** [comment]
Can we make this a CI job?

**Comment by mtnbikenc** [comment]
@sdodson Already have something in the works for automating checks for all entry point playbooks.  (which is how I found this one)

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
[merge]

**Comment by mtnbikenc** [comment]
Flake https://github.com/openshift/origin/issues/13067 oc new-app [It] should succeed with a --name of 58 characters
Flake https://github.com/openshift/origin/issues/13705 Dumping container logs

**Comment by kwoodson** [comment]
flake https://github.com/openshift/origin/issues/13516

**Comment by sdodson** [comment]
flake https://github.com/openshift/origin/issues/13386

**Comment by sdodson** [comment]
[merge]

**Comment by mtnbikenc** [comment]
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1442942

**Comment by mtnbikenc** [comment]
Failed on https://github.com/openshift/origin/issues/13806 Not a git repository
Failed on https://github.com/openshift/origin/issues/13271 Driver devicemapper failed

**Comment by sdodson** [comment]
[merge]

**Comment by mtnbikenc** [comment]
Flake https://github.com/openshift/origin/issues/13705 Dumping container logs
Flake https://github.com/openshift/origin/issues/13271 Driver devicemapper failed
re[merge]

**Comment by mtnbikenc** [comment]
known flake? "chmod: cannot access ‘/etc/origin/’: No such file or directory"

**Comment by mtnbikenc** [comment]
Merging based on temporary merge queue rules.

**Pull request merged**
