### PR TITLE
Backport to 3.6 - Bug 1471322: logging roles based image versions

### PR DESCRIPTION
**Pull request by wozniakjan**
Allowing to specify an image version for each logging component

https://bugzilla.redhat.com/show_bug.cgi?id=1471322

cc: @jcantrill , @portante

### CODE REVIEW

**Comment by ewolinetz** [comment]
Similar question here regarding the availability of `__openshift_logging_image_prefix` being available to `defaults/main.yml`

**Comment by wozniakjan** [comment]
it appears to be set correctly to `docker.io/openshift/origin-` when testing the `origin` deployment type and setting neither `openshift_logging_image_prefix`, nor `openshift_logging_*_image_prefix` vars in the inventory.

**Comment by jcantrill** [comment]
[merge]

**Comment by sdodson** [comment]
aos-ci-test

**Comment by wozniakjan** [comment]
@sdodson  I am not sure why the tests are failing, I don't see anything related to my changes, could you please take a look or re-run the tests? It's a backport of already merged https://github.com/openshift/openshift-ansible/pull/5044? I was told this is wanted in the following release. Thanks!

**Pull request merged**
