### PR TITLE
Make openshift_web_console_prefix defaults like other components

### PR DESCRIPTION
**Pull request by sdodson**
Other components are like 'registry.access.redhat.com/ose-' or
'openshift/origin-' based on OCP versus Origin.

Similar to #6752

### CODE REVIEW

**Comment by spadgett** [comment]
@mffiedler fyi

**Comment by sdodson** [comment]
flake

**Comment by sdodson** [comment]
@jupierce BTW, this will change how you're specifying the console prefix in the next 3.9 build.

**Pull request merged**
