### PR TITLE
Fix cluster creation with `bin/cluster` when there’s no glusterfs node

### PR DESCRIPTION
**Pull request by lhuard1A**

### CODE REVIEW

**Comment by abutcher** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by lhuard1A** [comment]
The error of the `aos-ci-jenkins/OS_3.6_containerized` job is:
```
TASK [openshift_excluder : Install docker excluder] ****************************
fatal: [10.8.169.137]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'atomic-openshift-docker-excluder-3.6.49*' found available, installed or updated", "rc": 126, "results": ["No package matching 'atomic-openshift-docker-excluder-3.6.49*' found available, installed or updated"]}
fatal: [10.8.169.141]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'atomic-openshift-docker-excluder-3.6.49*' found available, installed or updated", "rc": 126, "results": ["No package matching 'atomic-openshift-docker-excluder-3.6.49*' found available, installed or updated"]}
fatal: [10.8.169.132]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'atomic-openshift-docker-excluder-3.6.49*' found available, installed or updated", "rc": 126, "results": ["No package matching 'atomic-openshift-docker-excluder-3.6.49*' found available, installed or updated"]}
	to retry, use: --limit @/home/jenkins/workspace/openshift-ansible-test-matrix/CONTAINERIZED/_containerized/OSE_VER/3.6/PYTHON/System-CPython-2.7/TOPOLOGY/openshift-cluster-containerized/TargetBranch/master/nodes/openshift-ansible-slave/openshift-ansible/playbooks/byo/config.retry

PLAY RECAP *********************************************************************
10.8.169.132               : ok=89   changed=7    unreachable=0    failed=1   
10.8.169.137               : ok=88   changed=7    unreachable=0    failed=1   
10.8.169.141               : ok=92   changed=8    unreachable=0    failed=1   
localhost                  : ok=7    changed=0    unreachable=0    failed=0   
```

Not sure this missing `atomic-openshift-docker-excluder` package error is linked to the changes of this PR. ;-)

**Comment by abutcher** [comment]
[merge]

**Comment by abutcher** [comment]
@lhuard1A I'd wager it's not :smile_cat:

**Comment by sdodson** [comment]
aos-ci-test

**Comment by abutcher** [comment]
[merge]

**Pull request merged**
