### PR TITLE
atomic-openshift-installer: Remove HA hint for 3.0 install

### PR DESCRIPTION
**Pull request by smunilla**
Small update to remove the hint for multiple masters if we are doing
a 3.0 installation.

For https://bugzilla.redhat.com/show_bug.cgi?id=1289920

### CODE REVIEW

**Comment by abutcher** [comment]
@brenton

**Comment by brenton** [comment]
Looks good to me!  Can you try adding a test?

**Comment by smunilla** [comment]
I'm not sure if we can test for output in the middle of a run, but I'll give it a shot.

**Comment by smunilla** [comment]
Turns out we can and pretty easily!

**Pull request merged**
