### PR TITLE
[3.7] Only automatically restart if cluster is in yellow or green state

### PR DESCRIPTION
**Pull request by ewolinetz**
Manual cherry-pick for https://github.com/openshift/openshift-ansible/pull/6734 on to release-3.7

### CODE REVIEW

**Comment by ewolinetz** [comment]
bot, retest this please

**Comment by smarterclayton** [comment]
The GCP job shouldn't be running, fixing in https://github.com/openshift/release/pull/565

**Comment by ewolinetz** [comment]
left in an `include_tasks` instead of changing it to `include` for 3.7...

**Comment by ewolinetz** [comment]
bot, retest this please

**Pull request merged**
