### PR TITLE
[KIECLOUD-493] - Update RHPAM and RHDM templates and imagestreams on OpenShift Service Catalog for 7.11.0 release

### PR DESCRIPTION
**Pull request by msmagnanijr**
See: https://issues.redhat.com/browse/KIECLOUD-493

Signed-off-by: Mauricio Magnani <msmagnanijr@gmail.com>

### CODE REVIEW

**Comment by msmagnanijr** [comment]
Hi @mtnbikenc could you please take a look? thanks!

**Comment by msmagnanijr** [comment]
> /ok-to-test

thanks! I think this time everything is ok.

**Review by mtnbikenc — APPROVED** [review]
/lgtm

**Pull request merged**
