### PR TITLE
[DO NOT MERGE] Testing labels

### PR DESCRIPTION
**Pull request by tdawson**
Trying to automatically get nodes labeled.

### CODE REVIEW

**Comment by detiber** [comment]
@tdawson how is this change shaping up?

**Comment by wshearn** [comment]
Troy is at Flock but he should be able to base this off of https://github.com/openshift/openshift-ansible/pull/416 and get it working next week or so.

**Comment by jaryn** [comment]
Can one of the admins verify this patch?

**Comment by jaryn** [comment]
Can one of the admins verify this patch?

**Comment by arilivigni** [comment]
Testing job has been triggered.

**Comment by tdawson** [comment]
This is totally out of date and doesn't apply anymore.  Closing.

**Pull request closed without merging**
