### PR TITLE
Add EAP CD 13 imagestream and templates.

### PR DESCRIPTION
**Pull request by luck3y**
This update adds EAP CD 13 and associated templates into v3.11.

See: https://issues.jboss.org/browse/CLOUD-2555
and: https://errata.devel.redhat.com/advisory/34873

Signed-off-by: Ken Wills <kwills@redhat.com>

### CODE REVIEW

**Comment by luck3y** [comment]
For these, is it usual to open up a seperate PR for 3.10 if we wanted to add them in there too, or does that generally not happen?

**Comment by vrutkovs** [comment]
bot, retest this please

**Comment by luck3y** [comment]
@vrutkovs I'm not sure about that cherry pick ... I'd already opened one for 3.10 here: https://github.com/openshift/openshift-ansible/pull/9073

Sorry for the confusion.

**Pull request merged**
