### PR TITLE
Add masterCA to ServiceAccountConfig

### LINKED ISSUE #333: new master-config.yaml value
https://github.com/openshift/origin/pull/3622 adds `serviceAccountConfig.masterCA`.  This value is used to create a new piece of data in the automounted SA secret that includes a CA that can be used to confirm that you're communicating with the API server.  If it is not present, then the automounted SA secret will not contain that information.

### PR DESCRIPTION
**Pull request by sdodson**
Fixes #333

### CODE REVIEW

**Comment by sdodson** [comment]
@deads2k I assume this should point at the default master's ca.crt, correct?

**Comment by deads2k** [comment]
correct.

**Comment by detiber** [comment]
:+1:

**Comment by sdodson** [comment]
@brenton mind merging this when you get a minute?

**Pull request merged**
