### PR TITLE
line 8: restorecon needs absolute path

### PR DESCRIPTION
**Pull request by funixz**
otherwise it fails on the scaleup.yml in some scenarios.

### CODE REVIEW

**Comment by sdodson** [comment]
It's problematic in scenarios where the absolute paths are different
between Fedora and RHEL.

**Comment by funixz** [comment]
Yet couldn't we argue that openshift-ansible for enterprise would only ever be on RHEL, and openshift origin would be the one running on Fedora?
Maybe there's some differentiation due instead?

**Comment by vrutkovs** [comment]
Absolute paths would be nice, especially for such important binaries as `restorecon`.

Fedora should be supported, probably using `ansible_distribution` and `ternary` operators

**Comment by sdodson** [comment]
Yeah, we rely on PATH including relevant binaries in many places and we've said the proper solution is to update the PATH. I feel like relying on PATH for security is probably not a good pattern to follow.

**Comment by sdodson** [comment]
@funixz For reference here's the docs change where we've said that these paths need to be set. What do you think about having an early task that verifies that those paths are in the user's PATH variable?

https://github.com/openshift/openshift-docs/pull/7869/files

**Comment by funixz** [comment]
@sdodson yea, the verification of user paths is a good compromise of the situation.

**Comment by vrutkovs** [comment]
Master branch is closed! A major refactor is ongoing in devel-40. Changes for 3.x should be made directly to the latest release branch they're relevant to and backported from there.

**Pull request closed without merging**
