### PR TITLE
Mod startup script to publish all frontend binds

### PR DESCRIPTION
**Pull request by cwilkers**
Fix for [issue 5954 Containerized load balancer does not publish additional ports properly](https://github.com/openshift/openshift-ansible/issues/5954)

### CODE REVIEW

**Comment by sdodson** [comment]
Looks good, you've tested this yourself? Just interested in making sure the template evaluates as you expect.

**Comment by cwilkers** [comment]
@sdodson Thanks, and yes, I have tested for my case, but it occurs to me that a simple test of the default case (only console port, no extras) would be a good idea. I'll work on that.

**Comment by cwilkers** [comment]
Default case LGTM:

Relevant line when omitting any `openshift-loadbalancer-*-frontends` parameters: 

`ExecStart=/usr/bin/docker run --rm --name openshift_loadbalancer   -p 8443:8443   -v /etc/haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg:ro --entrypoint=haproxy openshift3/ose-haproxy-router:v3.6.173.0.49 -f /etc/haproxy/haproxy.cfg`

**Comment by cooktheryan** [comment]
@sdodson any update on this?

**Comment by sdodson** [comment]
bot, test this please

**Pull request merged**
