### PR TITLE
Refactoring the add-scc-to-user logic

### PR DESCRIPTION
**Pull request by brenton**

### CODE REVIEW

**Comment by brenton** [comment]
@sdodson, @abutcher, one of you guys mind taking a look?  This is @detiber's suggestion and I think it cleans things up a bit.

**Comment by abutcher** [comment]
@brenton lgtm

**Comment by abutcher** [comment]
@brenton actually couldn't we use the results of `test if scc needs to be updated` on the legacy include too?

**Comment by brenton** [comment]
aos-ci-test

**Comment by brenton** [comment]
@abutcher, PTAL

**Comment by abutcher** [comment]
@brenton :+1:

**Pull request merged**
