### PR TITLE
Clear ansible when statement warning in upgrade plays

### PR DESCRIPTION
**Pull request by tremble**
[WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: {{ (openshift_http_proxy is defined or
openshift_https_proxy is defined) and openshift_generate_no_proxy_hosts |
default(True) | bool }}

### CODE REVIEW

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[test]

**Comment by sdodson** [comment]
aos-ci-test

**Comment by tremble** [comment]
[test]

**Comment by sdodson** [comment]
aos-ci-test

**Comment by abutcher** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
Closing this PR as the `when:` condition updates have been handled in other PRs.  Please rebase or open a new PR if you find this still to be an issue.

**Pull request closed without merging**
