### PR TITLE
[3.9] GlusterFS: enable modprobe in pods that manage bricks

### PR DESCRIPTION
**Pull request by DanyC97**
Backports #7831
@jarrpa pls help review

### CODE REVIEW

**Comment by jarrpa** [comment]
/lgtm
/ok-to-test
bot, test pull request

**Comment by sdodson** [comment]
Is this a backport? If so please reference the master branch PR that this backports.

**Comment by DanyC97** [comment]
@sdodson sure and that is https://github.com/openshift/openshift-ansible/pull/7831

**Comment by sdodson** [comment]
> @sdodson sure and that is #7831

ok, can you make sure to put that in the description of your PRs, i've updated this one.

**Comment by DanyC97** [comment]
@jarrpa @michaelgugino fyi, thanks

**Pull request merged**
