### PR TITLE
Migrate old master env files to new location

### PR DESCRIPTION
**Pull request by michaelgugino**
This commit adds a custom module to migrate old master
env file to new location.  Some values present in
previous version were allowed to have unquoted, spaced strings.
Unquoted spaced strings break openshift in the new file location.

The custom module will attempt to quote unescaped, spaced strings,
strings with an escaped new line "\n".  The module will not
quote escaped strings + escaped new lines, those are unsupported.

### CODE REVIEW

**Comment by michaelgugino** [comment]
@sdodson module name is ConfigParser in python 2.7; fedora has 'backports' for configparser.  That might be the problem here.  This all worked for me locally, no lint errors.

**Comment by sdodson** [comment]
The 2.7 version of ConfigParser lacks SectionProxy.
```
TASK [openshift_control_plane : Migrate old master env file to new location] ***
Tuesday 12 June 2018  22:35:14 +0000 (0:00:00.282)       0:16:27.393 ********** 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'module' object has no attribute 'SectionProxy'
fatal: [prtest-c4a8d93-1634-ig-m-bdfl]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_F2yj5a/ansible_module_master_env_config_migrate.py\", line 201, in <module>\n    main()\n  File \"/tmp/ansible_F2yj5a/ansible_module_master_env_config_migrate.py\", line 197, in main\n    run_module()\n  File \"/tmp/ansible_F2yj5a/ansible_module_master_env_config_migrate.py\", line 190, in run_module\n    create_file(src, dest)\n  File \"/tmp/ansible_F2yj5a/ansible_module_master_env_config_migrate.py\", line 164, in create_file\n    config.readfp(open(src))\n  File \"/usr/lib64/python2.7/ConfigParser.py\", line 324, in readfp\n    self._read(fp, filename)\n  File \"/tmp/ansible_F2yj5a/ansible_module_master_env_config_migrate.py\", line 85, in _read\n    self._proxies[sectname] = configparser.SectionProxy(self, sectname)\nAttributeError: 'module' object has no attribute 'SectionProxy'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

**Comment by michaelgugino** [comment]
bot, retest this please

**Comment by michaelgugino** [comment]
bot, retest this please

**Pull request merged**
