### PR TITLE
Fix update master config for v1.5

### PR DESCRIPTION
**Pull request by chinacoolhacker**
To fix bug on installation v1.5 from master scripts

https://github.com/openshift/openshift-ansible/issues/5941

### CODE REVIEW

**Comment by michaelgugino** [comment]
@chinacoolhacker 

I think we should only use the boolean for the items that are not present in both versions.  Currently, it's confusing to determine what's in one version and what's in another.

**Comment by chinacoolhacker** [comment]
@michaelgugino changed to version comparsion for kubernetesMasterConfig.apiServerArguments.runtime-config value

**Comment by michaelgugino** [comment]
@chinacoolhacker 

Looks like we have already tagged 3.7, so master is now pointing to 3.8.  We only keep code in master for n-2, so this is not likely to merge.

I think since 3.6 release branch has the best support for 1.5, you should probably use 1.5+glusterfs from there until you can upgrade.

**Pull request closed without merging**
