### PR TITLE
openshift-checks: add role symlink

### PR DESCRIPTION
**Pull request by sosiouxme**
fixes bug 1487548
https://bugzilla.redhat.com/show_bug.cgi?id=1487548

### CODE REVIEW

**Comment by sosiouxme** [comment]
aos-ci-test

**Comment by rhcarvalho** [comment]
Wait, I thought we were intently *removing* the symlinks?
@mtnbikenc could you please take a look, how does this relate to your effort to remove the symlinks?

**Comment by sosiouxme** [comment]
@rhcarvalho yes we'd like to, but that's too disruptive to do right now. For the moment... symlinks galore :(

**Comment by sosiouxme** [comment]
[merge][severity: blocker]

**Pull request merged**
