### PR TITLE
Adding default value for openshift_hosted_logging_storage_kind

### PR DESCRIPTION
**Pull request by ewolinetz**
Detected in 
https://ci.openshift.redhat.com/jenkins/job/test-origin-aggregated-logging/1509/console

### CODE REVIEW

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
cc @sdodson in case we can skip the ci-tests since they don't test logging and its currently blocking the origin-integration-services CI tests

**Comment by sdodson** [comment]
Once travis comes back i'll merge it.

**Comment by sdodson** [comment]
Travis is delayed in processing jobs. We'll ask for forgiveness instead.

**Pull request merged**
