### PR TITLE
Adding assert to check for python-passlib on control host

### PR DESCRIPTION
**Pull request by ewolinetz**
to address #4111

### CODE REVIEW

**Comment by ewolinetz** [comment]
@sdodson

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
@ewolinetz see travis report

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
per #4111 only `python-passlib` will work. will need to revert this commit back to only checking for that

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
[merge]

**Comment by metal3d** [comment]
I suggest to make the command:

```
python -c 'import passlib' 2>/dev/null || echo not installed
```

**Pull request merged**
