### PR TITLE
Gracefully handle OpenSSL module absence

### LINKED ISSUE #2869: error because pyOpenSSL is not installed
I get an error because pyOpenSSL is not installed when I run this from an f25 system (the host where ansible is installed). 

```
TASK [Verify Ansible version is greater than or equal to 2.1.0.0] **************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'not ansible_version.full | version_compare('2.1.0.0', 'ge')' failed. The error was: No module
 named OpenSSL.crypto\n\nThe error appears to have been in '/sharedfolder/code/github.com/openshift/openshift-ansible/playbooks/common/openshift-cluster/verify_ansible_vers
ion.yml': line 8, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n  - name: Verify Ansi
ble version is greater than or equal to 2.1.0.0\n    ^ here\n"}
```

After I install pyOpenSSL everything works fine. Maybe that is a dep that should get installed by the rpm. Maybe not. If not, we should give a better error message to the users of openshift-ansible. 

##### Version
Working from 90fb07f and using `ansible-2.2.0.0-3.fc25.noarch.rpm` on fedora 25. No pyOpenSSL is installed.

### PR DESCRIPTION
**Pull request by mscherer**
Should fix #2869

### CODE REVIEW

**Comment by mscherer** [comment]
aos-ci-test

**Comment by dustymabe** [comment]
This is not working for me. I don't have the module and it is not complaining.

**Comment by mscherer** [comment]
It should only complain when we use oo_parse_named_certificates, which is done around openshift master deployment. 

How did you tested, with a full deployment ?

**Comment by detiber** [comment]
aos-ci-test

**Comment by dustymabe** [comment]
@detiber I reported earlier that the code in this PR actually didn't result in an "error" being shown to the user, can someone else confirm the behavior of this PR when the pyOpenSSL rpm does not exist on your system?

**Comment by dustymabe** [comment]
I guess the reason I'm not seeing an "error" message any longer is because when I run the code I don't ever hit the `oo_parse_named_certificates()` function which is where the exception would get raised. I don't know why my code path would not hit this function. I guess I don't have any issue with this PR.

**Pull request merged**
