### PR TITLE
DO NOT MERGE -- Logging metrics true

### PR DESCRIPTION
**Pull request by sdodson**
just testing to see that CI passes with logging and metrics on

### CODE REVIEW

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
added missing variable to CI jobs

**Comment by sdodson** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
seems we need to cherry pick the htpasswd stuff

**Comment by sdodson** [comment]
Ok, I'll try to pull that stuff in but tied up with other things right now. Feel free to merge it and push to my branch if you have time.

**Comment by ewolinetz** [comment]
htpasswd pick is https://github.com/openshift/openshift-ansible/pull/4071

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by sdodson** [comment]
http-tools not installed on control host, fixed that.

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Pull request closed without merging**
