### PR TITLE
Ansible role graph script

### PR DESCRIPTION
**Pull request by abutcher**
First take on an ansible role graph script which has been useful for debugging.

Example graphs:
- internal svg http://file.rdu.redhat.com/abutcher/generated-ansible-role-graph.svg
- external png http://i.imgur.com/nWVUnWZ.png

```
./bin/ansible-role-graph --format pdf --engine dot --roles-path ~/openshift-ansible/roles/
```

Depends on #2132

### CODE REVIEW

**Comment by abutcher** [comment]
@tbielawa @detiber @sdodson ptal

**Comment by tbielawa** [comment]
This bothers me

```
$ python ./bin/ansible-role-graph -h
Error: no such option: -h
```

**Comment by abutcher** [comment]
@tbielawa that bothers me too, hold up

**Comment by tbielawa** [comment]
LDTM :+1: 

only problems I found were ones I intentionally created (using invalid option values).

**Comment by tbielawa** [comment]
The only other things that come to mind are short options flags for the gnu-style (--wordy) option flags. I'd probably add these:

* `--dont-show` → `-n`
* `--open` doesn't really need a short option, it's default
* `--output-format` → `-o`
* `--roles-path` → `-r`

**Comment by abutcher** [comment]
@tbielawa I changed them around like this. Went with `--show/--dont-show` since that seems more intuitive.

* `--dont-show` → `-n`
* `--show` → `-s`
* `--format` → `-f`
* `--roles-path` → `-r`
* `--engine` → `-e`

**Comment by abutcher** [comment]
aos-ci-test

**Comment by detiber** [comment]
:+1:

**Comment by tbielawa** [comment]
@detiber , @abutcher and I were considering shoving this into https://github.com/openshift/openshift-ansible-contrib instead of in here.

Thoughts folks? There's also a zsh completion script I'd like to include in with this: https://gist.github.com/tbielawa/bdea9b61ef6f6563cef3231583d916a1

**Comment by detiber** [comment]
@tbielawa @abutcher :+1: to contrib

**Pull request closed without merging**
