### PR TITLE
Bug 1278245 - Failed to add node to existing env using atomic-openshift-installer

### PR DESCRIPTION
**Pull request by brenton**

### CODE REVIEW

**Comment by brenton** [comment]
The test failure looks like something unrelated is broken.

@detiber, can you take a quick look at this?  I pulled in your PR.  The last thing I had to work through was making sure `openshift_deployment_type` was set for the node run.

**Comment by detiber** [comment]
@breanton My pr should be superfluous at this point. Since openshift_node_certificates has a dependency on openshift_facts, I don't think it was ever needed.

**Comment by detiber** [comment]
:+1: from me outside of the comment about 93408fe not being needed.

**Comment by brenton** [comment]
Ok, let me try without that PR real quick.

**Comment by brenton** [comment]
@detiber, you were right.  It wasn't needed.  I'm merging this.

**Pull request merged**
