### PR TITLE
Do not update the hostname

### PR DESCRIPTION
**Pull request by detiber**

### CODE REVIEW

**Comment by sdodson** [comment]
:+1: I think I'm already skipping this for containerized installs, once it merges i'll rebase

**Comment by abutcher** [comment]
:+1: @twiest @wshearn

**Comment by twiest** [comment]
I'm pretty sure we rely on this behavior. Right now, I believe this sets our hostnames to the IP address of the machine, which is then used when registering the node with the master. This is important, because we're not using DNS for the nodes (cattle).

So, unless the behavior is changed when registering (that it can / will register the IP addr too), I think we need this still.

@wshearn will this PR break us?

**Comment by twiest** [comment]
@detiber ok, sounds good. I'd still like @wshearn to weigh in, so that he at least knows that before we merge this.

**Comment by detiber** [comment]
@wshearn ping

**Comment by wshearn** [comment]
This shouldn't break us, in reality we don't care what the nodes host name are.

**Comment by xiama** [comment]
@brenton @wshearn  Pls refer to bug#1275395.

**Comment by detiber** [comment]
@xiama @brenton I think I'm going to need to put a conditional in place. For earlier versions (sometime in the 3.0.z series) the sdn code did not rely on the values provided by the config, so I'll submit a PR to make it conditional based on version instead.

**Pull request merged**
