### PR TITLE
Bugfix for extra --add-registry in docker config

### PR DESCRIPTION
**Pull request by detiber**
Addresses: https://github.com/openshift/openshift-ansible/issues/514

### CODE REVIEW

**Comment by detiber** [comment]
Still working out some edge cases here

**Comment by detiber** [comment]
Fix works with my testing now.

**Comment by detiber** [comment]
@thoraxe This fixes the issue with my minimal testing.

@lhuard1A can you verify that I didn't break your usage of these variables?

**Comment by lhuard1A** [comment]
@detiber I’ve just tested that PR with my use case. It works for me. :+1:
Thanks for the fix and sorry for the bug!

**Comment by detiber** [comment]
@wshearn This fix is needed to asap

**Pull request merged**
