### PR TITLE
Update CloudForms templates for CF 4.5/CF 4.2

### PR DESCRIPTION
**Pull request by simaishi**
Updated templates for CloudForms 4.5 release for v1.5.  The updates for v1.4 is pending decision on what will be supported on v1.4..

cc  @bazulay @fbladilo

### CODE REVIEW

**Comment by sdodson** [comment]
@simaishi can you also update the content in v3.6? I assume this is compatible there?

**Comment by sdodson** [comment]
CC: @tbielawa

**Comment by simaishi** [comment]
I'm not sure if this is compatible with v1.6.  I thought
```
apiVersion: apps/v1beta1
   kind: "StatefulSet"
```
is only for v1.5? @bazulay @fbladilo please clarify

**Comment by tbielawa** [comment]
https://kubernetes.io/docs/concepts/workloads/controllers/petset/
> Warning: Starting in Kubernetes version 1.5, PetSet has been renamed to StatefulSet. To use (or continue to use) PetSet in Kubernetes 1.5, you must migrate your existing PetSets to StatefulSets. For information on working with StatefulSet, see the tutorial on how to run replicated stateful applications.
>
> This document has been deprecated, but can still apply if you’re using Kubernetes version 1.4 or earlier.


https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
> StatefulSets are a beta feature in 1.5. This feature replaces the PetSets feature from 1.4. Users of PetSets are referred to the 1.5 Upgrade Guide for further information on how to upgrade existing PetSets to StatefulSets.
>
> A StatefulSet is a Controller that provides a unique identity to its Pods. It provides guarantees about the ordering of deployment and scaling.

**Comment by fbladilo** [comment]
@simaishi Correct, 1.4 = PetSets (alpha) , 1.5 StatefulSets (beta) and I'm not quite sure if statefulsets will get out of beta for 1.6 , perhaps @tbielawa has more info.

**Comment by simaishi** [comment]
Marking as WIP as I might need to change the registry name.

**Comment by tbielawa** [comment]
I have no insight into the future development or support status of the `petset`/`statefulset` objects. Sorry

**Comment by simaishi** [comment]
Confirmed with Product Mgmt that CF 4.2 for v1.4 and CF 4.5 for v1.5.  Updated both v1.4 and v1.5 templates to point to the correct images in the registry.

CF 4.5 isn't tested with v1.6 and I don't have confirmation from PM about adding v1.6 templates. I'll open a followup PR if  v1.6 templates are needed. cc @Loicavenel

**Comment by Loicavenel** [comment]
We will add v1.6 later

**Comment by simaishi** [comment]
@bazulay @fbladilo please review

**Comment by fbladilo** [comment]
@simaishi 👍 I like the specific release repos, rest looks as it should for those releases.

**Pull request merged**
