### PR TITLE
Remove deprecated online playbooks/roles

### PR DESCRIPTION
**Pull request by detiber**
Removal of some deprecated playbooks and roles that were limited to the 'online' deployment_type.

### CODE REVIEW

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
@mwoodson as we discussed in IRC.

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
@abutcher @joelddiaz ptal

**Comment by abutcher** [comment]
LGTM

**Comment by joelddiaz** [comment]
LGTM

**Pull request merged**
