### PR TITLE
bug 1487573. Bump the allowed ES versions

### PR DESCRIPTION
**Pull request by jcantrill**
This PR fixes 1487573

* Bumps the available versions for which the role is relevent
* Bumps the latest version

### CODE REVIEW

**Comment by jcantrill** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
you may want to do this for all the other components too. otherwise LGTM

**Comment by jcantrill** [comment]
@ewolinetz updated

**Comment by jcantrill** [comment]
[merge]

**Comment by sdodson** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Comment by jcantrill** [comment]
[merge][severity:blocker]

**Pull request merged**
