### PR TITLE
Rename system container vars and add example to inventory

### PR DESCRIPTION
**Pull request by ashcrow**

### CODE REVIEW

**Comment by ashcrow** [comment]
aos-ci-test

**Comment by ashcrow** [comment]
``CA certificate /etc/origin/master/ca.crt doesn't exist on CA host``

Unrelated failure. No flake found.

**Comment by ashcrow** [comment]
aos-ci-test

**Comment by ashcrow** [comment]
[merge][kind: bug]

**Comment by ashcrow** [comment]
flake https://github.com/openshift/origin/issues/13731

**Comment by ashcrow** [comment]
[merge][kind: bug]

**Comment by sdodson** [comment]
[merge][severity: blocker]

**Pull request merged**
