### PR TITLE
Remove bin/cluster and playbooks/{aws,gce,libvirt,openstack}

### PR DESCRIPTION
**Pull request by sdodson**
These playbooks were never supported and have been moved to
openshift-ansible-contrib. Related https://github.com/openshift/openshift-ansible-contrib/pull/646

CC: @tomassedovic

### CODE REVIEW

**Comment by sdodson** [comment]
aos-ci-test

**Comment by cooktheryan** [comment]
@sdodson ill merge the code into contrib then you can merge this removal whenever ci is finished

**Comment by mtnbikenc** [comment]
@sdodson It looks like `playbooks/{aws,gce,libvirt,openstack}/openshift-cluster/cluster_hosts.yml` were left in place (with a couple of other files).  Was this intended?  Also, can we clean up the unused vars as well, such as `cluster_id`, `num_masters`, `num_etcd`, etc.?  I opened a card for this earlier today but I guess it could happen earlier than I thought

https://trello.com/c/vdpG1vkE/514-move-bin-cluster-to-openshift-ansible-contrib

**Comment by tomassedovic** [comment]
One question about this: do you know whether anyone actually uses this? The openstack provisioning work in -contrib should obsolete at least the openstack part of the cluster script & playbooks.

Would be nice to talk to the existing users to try and move them over and/or see what would block them from doing so.

**Comment by sdodson** [comment]
The folks at Amadeus were using it but I don't think they are any longer, they were fine with removing it from openshift-ansible. The main users are new people that start looking at the repo and see a script that offers them the world. It's unfortunate that we don't have someone who can actively maintain this but it's not good for people to assume it's supported.

I wasn't expecting the openshift-ansible-contrib pr to merge so quickly, I was hoping for a bit more discussion and I'm sorry I didn't hi-light that when I opened the PR.

**Comment by michaelgugino** [comment]
We should send a note on the users mailing list if we haven't already.

**Comment by mtnbikenc** [comment]
@sdodson Do you want me to run with this effort?  I can update the other aspects of this removal such as READMEs as well as collapse some of my other PRs for removing legacy files.

**Comment by sdodson** [comment]
@mtnbikenc yeah if you have time to work on it feel free to either push new commits to this pr or open a new one.

**Comment by mtnbikenc** [comment]
Closing in favor of #5201

**Pull request closed without merging**
