### PR TITLE
Sync latest image-streams and templates

### PR DESCRIPTION
**Pull request by alexcern**
This mainly adds the python 3.6 image-stream following openshift/origin#17281

### CODE REVIEW

**Comment by michaelgugino** [comment]
/ok-to-test

@sdodson does this look okay to you?

**Comment by sdodson** [comment]
Yup, looks fine.
/lgtm

**Comment by alexcern** [comment]
@sdodson thanks for the review. 

I'm not sure what to do next: tests are green except a note about "Required Github CI test is not green: fedora/27/atomic" but it looks like that particular test is missing altogether in this PR (while it's present in other PRs I checked). My last /retest command did not seem to help with this. Any suggestion to unblock the situation?

**Pull request merged**
