### PR TITLE
Adding uninstall support for Atomic Host

### PR DESCRIPTION
**Pull request by brenton**

### CODE REVIEW

**Comment by brenton** [comment]
@detiber, what do you think about this?  It somewhat affects the work Devan is working on since he'll need to make use the atomic-openshift-installer calls the right playbook depending on whether or not the environment is running the containerized installation.

**Comment by brenton** [comment]
@detiber, OK, you can ignore that last comment.  I followed the work Scott was doing on the containerized branch and just checked for existence of `/run/ostree-booted`.  I tried this on both a rhel 7 and atomic host system.

**Comment by brenton** [comment]
@detiber, mind taking a look to see if we could get this in?  I'd love to make it idempotent eventually but for now it's really aimed at being a convenience for people running the quick installer.

**Comment by detiber** [comment]
@brenton :+1: from me

**Pull request merged**
