### PR TITLE
Sdn restart

### PR DESCRIPTION
**Pull request by zhiwliu**

### CODE REVIEW

**Comment by joelddiaz** [comment]
@zhiwliu is this PR really supposed to pull in the other commit (Automatic commit of package [openshift-ansible] release [3.0.35-1]. 6a386dd)?

**Comment by kwoodson** [comment]
ok to test

**Comment by kwoodson** [comment]
ok to test

**Comment by kwoodson** [comment]
ok to test

**Comment by zhiwliu** [comment]
@joelddiaz, no, this is just a test pr, I close it

**Pull request closed without merging**
