### PR TITLE
Fix cockpit image name if checked out from a private registry

### PR DESCRIPTION
**Pull request by abessifi**
This PR is a fix of the issue #5767.

### CODE REVIEW

**Comment by abessifi** [comment]
This will lead to code duplication and make the `Deploy registry-console` task confusing:

```yaml
- name: Deploy registry-console
     command: >
       {{ openshift.common.client_binary }} new-app --template=registry-console
      {% if openshift_cockpit_deployer_prefix is defined  %}-p IMAGE_PREFIX="{{ openshift_cockpit_deployer_prefix }}"{% endif %}
      {% if openshift_cockpit_deployer_name is defined  %} -p IMAGE_NAME="{{ openshift_cockpit_deployer_name }}"{% endif %}
      {% if openshift_cockpit_deployer_version is defined  %}-p IMAGE_VERSION="{{ openshift_cockpit_deployer_version }}"{% endif %}
[...]
```

On the other hand, the `IMAGE_PREFIX` seems never existed in the template file that describes the registry-console.

**Comment by michaelgugino** [comment]
It looks like origin supports "IMAGE_NAME" and enterprise supports "IMAGE_PREFIX"

@abessifi if you can add a when condition to detect each deployment type, that would work.  Keep both versions of this command, and run only the one that matches the correct deployment type.

**Comment by michaelgugino** [comment]
@sosiouxme Didn't you work on something similar to this?

**Comment by sosiouxme** [comment]
@abessifi I did not see this PR before working on https://github.com/openshift/openshift-ansible/pull/6114 which makes the situation more consistent between enterprise/origin. Does that fulfill the need to your satisfaction? If not, your concerns are welcome, this can be reopened if needed.

**Comment by abessifi** [comment]
Thank you @sosiouxme.
No problem, this is ok for me.

**Pull request closed without merging**
