### PR TITLE
add pre-flight checks to ugrade path

### PR DESCRIPTION
**Pull request by juanvallejo**
Followup to https://github.com/openshift/openshift-ansible/pull/4923

cc @rhcarvalho @sosiouxme

### CODE REVIEW

**Comment by juanvallejo** [comment]
[test]

**Comment by rhcarvalho** [comment]
aos-ci-test

**Comment by juanvallejo** [comment]
@sosiouxme @mtnbikenc thanks for your feedback; moved health checks `include` after call to `upgrades/init.yml`

**Comment by juanvallejo** [comment]
re[test]

**Comment by rhcarvalho** [comment]
The test failure in https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check/943/ were:

- Liveness probe-related, flake https://github.com/openshift/origin/issues/12072
- Something s2i-related, looks like flake https://github.com/openshift/origin/issues/14929

@juanvallejo did you identify the original problem? Was there anything related to the order of the includes in `init.yml`?

**Comment by rhcarvalho** [comment]
Let's squash the commits, re-run all tests and line up for merge.

**Comment by juanvallejo** [comment]
@rhcarvalho 
> did you identify the original problem? Was there anything related to the order of the includes in init.yml?

After talking with @mtnbikenc and @sosiouxme , looks like the most likely cause was calling the checks (which brought in the openshift_version dependency) too early

**Comment by sosiouxme** [comment]
tests looked good except aos-ci-test didn't run yet on this commit.

**Comment by sosiouxme** [comment]
aos-ci-test

**Comment by juanvallejo** [comment]
@sosiouxme seems to still be failing [with "check other job statuses" error](https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check/949/consoleFull#118321978658b6e51eb7608a5981914356), but have not seen the initial upgrade issue happen again

**Comment by sdodson** [comment]
So the aos-ci-test statuses get cleared as soon as new commits are pushed. So you must run those after you're done making changes and those results must be green before you issue a merge or it will fail. If the queue is empty you can race the two and hope for the best but that rarely works out well so unfortunately for now we just have to make sure that aos-ci-test is done before the merge attempt.

**Comment by sdodson** [comment]
[test]

**Comment by juanvallejo** [comment]
[merge]

**Comment by rhcarvalho** [comment]
bravo! :clap:

**Pull request merged**
