### PR TITLE
Add missing task that got dropped in a refactor

### PR DESCRIPTION
**Pull request by sdodson**
Removed in 28b254886bf17251e973bfdad4dd4c89e26187fc
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1532973

### CODE REVIEW

**Comment by jarrpa** [comment]
Why was this removed from the hosted registry playbook? And where does the tempdir delete happen?

**Comment by sdodson** [comment]
@michaelgugino removed it in a refactor because it wasn't obvious that it was used elsewhere. I'll update the PR to add the removal too, thanks.

**Comment by sdodson** [comment]
@jarrpa Updated to remove the tempdir as it did before 28b254886bf17251e973bfdad4dd4c89e26187fc

**Pull request merged**
