### PR TITLE
Openstack add master and infra to node security group

### PR DESCRIPTION
**Pull request by jdnieto**
Replace PR [#1414](https://github.com/openshift/openshift-ansible/pull/1414)

### CODE REVIEW

**Comment by detiber** [comment]
ok to test

**Comment by detiber** [comment]
@jdnieto would it not be better to add the node-secgrp to the master hosts, since the master is a node?

**Comment by jdnieto** [comment]
Yes, of course, but I was thinking in a way to reuse some common ports, and
also to secure environment restricting access only for system in the same
security group.

El vie., 19 feb. 2016 19:10, Jason DeTiberus <notifications@github.com>
escribió:

> @jdnieto <https://github.com/jdnieto> would it not be better to add the
> node-secgrp to the master hosts, since the master is a node?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/openshift-ansible/pull/1423#issuecomment-186337993>
> .
>
-- 

Un saludo.
-------------------------------------------
José David Martín Nieto
RHCE, RHCJA, RHCJD, RHCoE-PaaS, RHCoE-Hibernate, RHCI, RHCX
#110-442-589

Public Key 2048R/24C474E5 C8B9 5589 9C19 1453 1184  EEAE A642 701E 24C4
74E5 @pool.sks-keyservers.net

**Comment by jdnieto** [comment]
Ok, reviewed and modified. Restored 4789 port in node-secgroup. Added master_nodes to  node-secgroup. Deleted common-secgroup

**Comment by detiber** [comment]
@jdnieto looks good, thanks. Can you squash the commits?

**Comment by jdnieto** [comment]
@detiber Done!

**Comment by detiber** [comment]
@jdnieto thanks!

@brenton :+1: from me

**Pull request merged**
