### PR TITLE
Update boto version

### PR DESCRIPTION
**Pull request by michaelgugino**
This commit updates the boto version to be compatible with
ansible 2.4.0.

### CODE REVIEW

**Comment by sdodson** [comment]
We'll need to ensure that this version of boto is available and make sure that openshift-ansible.spec requires it.

**Comment by mtnbikenc** [comment]
I checked Errata Tool and it looks like 2.34 is the latest shipped version.  @michaelgugino could you link to the Ansible doc where boto 2.48 is required for Ansible 2.4?

**Comment by michaelgugino** [comment]
@mtnbikenc @sdodson 

I'm not sure how this is put together on the RPM side.  In ansible's requirement files: https://github.com/ansible/ansible/tree/stable-2.4/test/runner/requirements

boto and boto3 are specified without version.  This leads me to believe that they develop against the head of boto.

My setup is as follows:

F26, python3 venv, pip install -r requirements.txt.  In my environment, installing just requirements.txt and using the ansible ec2 module is broken.

**Comment by sdodson** [comment]
Looks like RHEL has never shipped boto on its own and the only versions of boto that we've used are those that come from our repos which is boto-2.34, botocore-1.4.43, and boto3-1.4.0

**Pull request closed without merging**
