### PR TITLE
Contiv backports from master

### PR DESCRIPTION
**Pull request by nbartos**

### CODE REVIEW

**Comment by nbartos** [comment]
@sdodson and @srampal, these are simple cherry pick backports from master.  Can you PTAL?  Thanks!

**Comment by nbartos** [comment]
@sdodson could I please get a /ok-to-test & /lgtm for this backport?  It's the same as the https://github.com/openshift/openshift-ansible/pull/6655 backport that you've already weighed in on.  Thanks!

**Comment by sdodson** [comment]
bot, test pull request
/ok-to-test

**Comment by nbartos** [comment]
Hmm, looks like the CI build slaves are out of disk space :(

**Pull request merged**
