### PR TITLE
bug 1428249. Use ES hostmount storage if it exists

### PR DESCRIPTION
**Pull request by jcantrill**
Seems like this could be done without the use of the filter, but given the approach I took, using tasks directly would seem to require us to jump through a bunch of hoops.  Thoughts?

### CODE REVIEW

**Comment by jcantrill** [comment]
@sdodson I defer to @ewolinetz  but I think we want this for 3.5 if the installer code is still open

**Comment by sdodson** [comment]
> @sdodson I defer to @ewolinetz but I think we want this for 3.5 if the installer code is still open

That's fine with me.

**Comment by ewolinetz** [comment]
@jcantrill we were able to confirm with manual testing this works, correct?

**Comment by jcantrill** [comment]
Confirmed PVC is applied when initially EmptyDir.
Confirmed reuses hostmount if initially setup hostmount

**Comment by ewolinetz** [comment]
@jcantrill i think a PR should also be opened against release-1.5

**Comment by jcantrill** [comment]
[merge]

**Comment by sdodson** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
This was in the merge logs
```
22:13:23 [ERROR] Status 'aos-ci-jenkins/OS_3.4_NOT_containerized' is required but was not found on this pull request.
22:13:23 [ERROR] Status 'aos-ci-jenkins/OS_3.4_NOT_containerized_e2e_tests' is required but was not found on this pull request.
22:13:23 [ERROR] Status 'aos-ci-jenkins/OS_3.4_containerized' is required but was not found on this pull request.
22:13:23 [ERROR] Status 'aos-ci-jenkins/OS_3.4_containerized_e2e_tests' is required but was not found on this pull request.
22:13:23 [ERROR] Status 'aos-ci-jenkins/OS_3.5_NOT_containerized' is required but was not found on this pull request.
22:13:23 [ERROR] Status 'aos-ci-jenkins/OS_3.5_NOT_containerized_e2e_tests' is required but was not found on this pull request.
22:13:23 [ERROR] Status 'aos-ci-jenkins/OS_3.5_containerized' is required but was not found on this pull request.
22:13:23 [ERROR] Status 'aos-ci-jenkins/OS_3.5_containerized_e2e_tests' is required but was not found on this pull request.
22:13:23 [ERROR] Status 'aos-ci-jenkins/OS_unit_tests' is required but was not found on this pull request.
```

**Comment by sdodson** [comment]
A new commit was pushed after aos-ci-test was run invalidating the previous results.

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Pull request merged**
