### PR TITLE
[Glusterfs]: Bring down the number of retries attempted for upgrade p…

### PR DESCRIPTION
**Pull request by SaravanaStorageNetwork**
…laybook.

Fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=1728184
https://bugzilla.redhat.com/show_bug.cgi?id=1726608

Signed-off-by: Saravanakumar Arumugam <sarumuga@redhat.com>

### CODE REVIEW

**Comment by vrutkovs** [comment]
Why not update default `openshift_storage_glusterfs_health_timeout`?

**Comment by SaravanaStorageNetwork** [comment]
> Why not update default `openshift_storage_glusterfs_health_timeout`?

The tasks from cluster_health.yml is imported in other roles too (which refers glusterfs_health_timeout).
If I update the default value(openshift_storage_glusterfs_health_timeout) it will implication at other places.

I want to have this restricted for upgrade playbook alone.

**Comment by SaravanaStorageNetwork** [comment]
@vrutkovs @jarrpa   AWS Test keep failing - could you help to get this merged

**Comment by vrutkovs** [comment]
/hold

Needs https://github.com/openshift/release/pull/4533

**Pull request merged**
