### PR TITLE
Changing include_tasks to include for release-3.7

### PR DESCRIPTION
**Pull request by ewolinetz**

### CODE REVIEW

**Comment by ewolinetz** [comment]
Should address https://github.com/openshift/openshift-ansible/issues/6740

**Comment by ewolinetz** [comment]
Keep hitting the recursion depth error here @sdodson @mtnbikenc

**Comment by mtnbikenc** [comment]
@ewolinetz A possible workaround for the recursion depth problem is to add `static: false` to each of the `include_role:` directives in your openshift_logging role.  I have been attempting to test this but have had issues with my test environment.  Could you try that out?

**Comment by mtnbikenc** [comment]
@ewolinetz The other part of this is that our CI is using Ansible 2.4.2 and the 3.7 branch should really be run with Ansible 2.3.  The recursion problem seems to have cropped up 2.4.1+, however, there are other problems which the `static: false` should fix if using 2.3.

**Comment by ewolinetz** [comment]
@mtnbikenc looks like it didn't like `static: false` on the `include_role`s

**Comment by mtnbikenc** [comment]
@ewolinetz the `static` directives need to be outdented one level.

**Comment by mtnbikenc** [comment]
Logging test hung at the recursion error again.

**Comment by maxamillion** [comment]
Why is `static: false` needed on all of these?

**Comment by mtnbikenc** [comment]
@ewolinetz, @maxamillion and I discussed this and the recommendation is to use `static: true` to fix this problem.  Please update the PR again.  Apologies for the churn.

**Comment by mtnbikenc** [comment]
@ewolinetz I didn't catch that those include_role tasks were looping and therefore can't use static: true.  I've been having a hard time getting logging to work, with or without the recursion problems, so if you could help me get that working I can better test all these iterations/fixes instead of relying on CI to figure this out.

**Comment by mtnbikenc** [comment]
@ewolinetz In testing this with Ansible 2.3.2, I've found four other instances of `include_tasks` in the release-3.7 branch.

```
$  grep -r 'include_tasks' roles/                                                                                  [±release-3.7 ✓]
roles/openshift_logging_elasticsearch/tasks/determine_version.yaml:- include_tasks: get_es_version.yml
roles/openshift_logging_elasticsearch/tasks/restart_cluster.yml:  include_tasks: restart_es_node.yml
roles/openshift_logging_elasticsearch/tasks/restart_cluster.yml:  include_tasks: restart_es_node.yml
roles/openshift_logging_elasticsearch/handlers/main.yml:  include_tasks: restart_cluster.yml
```

**Comment by mtnbikenc** [comment]
@ewolinetz After locally fixing those `include_tasks` directives I hit another error:
`'logging_elasticsearch_rollout_override' is undefined`

```
RUNNING HANDLER [openshift_logging_elasticsearch : oc_service] *******************************************************************************
Friday 19 January 2018  09:15:13 -0500 (0:00:00.203)       0:03:27.405 ******** 
fatal: [ec2-52-55-116-150.compute-1.amazonaws.com]: FAILED! => {"failed": true, "msg": "The conditional check 'not logging_elasticsearch_rollout_override | bool' failed. The error was: error while evaluating conditional (not logging_elasticsearch_rollout_override | bool): 'logging_elasticsearch_rollout_override' is undefined\n\nThe error appears to have been in '/home/rteague/git/clusters/aws-c1/openshift-ansible/roles/openshift_logging_elasticsearch/tasks/restart_cluster.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# Disable external communication for {{ _cluster_component }}\n- name: Disable external communication for logging-{{ _cluster_component }}\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
```

Probably need to add `| default(false)`

```yaml
  when: not logging_elasticsearch_rollout_override | default(false) | bool
```

**Comment by mtnbikenc** [comment]
@ewolinetz @sdodson The logging install completed (using Ansible 2.3.2) but then there was a failure in the logging tests.  At least we didn't hit the recursion error so I think we are getting somewhere.

**Pull request merged**
