### PR TITLE
Update Cluster Monitoring Operator role docs

### PR DESCRIPTION
**Pull request by ironcladlou**
Some updates to the Cluster Monitoring Operator docs.

### CODE REVIEW

**Comment by ironcladlou** [comment]
I assume my README updates aren't responsible for the upgrade failure 😉

**Comment by sdodson** [comment]
bot, retest this please

**Comment by sichvoge** [comment]
General feedback, I would not know how to install it into OpenShift just with that doc :) Maybe thats because I lack knowledge, but it would be good to add missing pieces for people that have no previous knowledge with, I guess, Ansible. Would that be possible?

**Comment by ironcladlou** [comment]
@sichvoge 
>General feedback, I would not know how to install it into OpenShift just with that doc :) Maybe thats because I lack knowledge, but it would be good to add missing pieces for people that have no previous knowledge with, I guess, Ansible. Would that be possible?
>For example: To install the monitoring operator, set this variable:. Where do I have to set this?

I'm not sure every role in this repo is supposed to restate the product/installer docs... there's always some set of implied knowledge at each layer. In terms of the READMEs throughout the roles and playbooks in this repo, I see little consistency. For this role specifically, the target audience of the README is engineering/ops/anybody familiar with working with the Ansible installer.

I feel like what you're looking for is our actual product documentation:

https://docs.openshift.org/latest/install_config/index.html

(which our component is not yet a part of)

**Pull request merged**
