### PR TITLE
Added additional Calico Network Plugin Checks

### PR DESCRIPTION
**Pull request by VincentS**
Added additional checks for network plugins when Calico is used in OpenShift.

### CODE REVIEW

**Comment by djosborne** [comment]
@VincentS while you're touching this area, can you reword the part on working with flannel? "currently" was supposed to insinuate that there's no reason Calico _couldn't_ integrate with Flannel in OpenShift. We just haven't done the work to integrate the two ansible playbooks (yet). 

I'm open to other suggestions, but how about something like:

"The Calico playbook does not yet integrate with the Flannel playbook in Openshift. Set either openshift_use_calico or openshift_use_flannel, but not both."

**Comment by VincentS** [comment]
I have changed the text accordingly.

**Comment by ingvagabund** [comment]
aos-ci-test

**Comment by ingvagabund** [comment]
aos-ci-test

**Comment by ingvagabund** [comment]
aos-ci-test

**Comment by ingvagabund** [comment]
[merge]

**Pull request merged**
