### PR TITLE
Add templates for CFME Beta pod images

### PR DESCRIPTION
**Pull request by simaishi**
/cc @fbladilo @bazulay

### CODE REVIEW

**Comment by bazulay** [comment]
@simaishi if you intend to push another PR for towards cfme ga than this patch is o.k. with me.
Otherwise you need to change the names (not to include Beta).

**Comment by simaishi** [comment]
@bazulay this is to be used only with Beta images.  One the GA images become available, I'll open another PR.

**Comment by bazulay** [comment]
LGTM

**Comment by sdodson** [comment]
Going ahead and mering this.

**Pull request merged**
