### PR TITLE
PAPR: don't install TSB on Atomic

### PR DESCRIPTION
**Pull request by sdodson**
PVC cannot be bound

Picked from https://github.com/openshift/openshift-ansible/pull/7614

### CODE REVIEW

**Comment by sdodson** [comment]
bot, retest this please

**Comment by smarterclayton** [comment]
Why is the TSB depending on a PVC????

**Comment by vrutkovs** [comment]
>Why is the TSB depending on a PVC????

`asb-etcd` wants a volume

**Pull request merged**
