### PR TITLE
Add options to configure docker registries

### PR DESCRIPTION
**Pull request by lhuard1A**
Add options to add:
* insecure registries
* default registries
* blocked registries
to the docker daemon.

### CODE REVIEW

**Comment by detiber** [comment]
@lhuard1A looks good, but we should probably add a handler for restarting the docker daemon, and have updates to /etc/sysconfig/docker notify the new handler.

**Comment by lhuard1A** [comment]
@detiber: Good point! I’ve just added the handler.

**Comment by detiber** [comment]
:+1: @wshearn

**Comment by sdodson** [comment]
I'll try to test this tonight but we've had someone report that they're getting the following, ADD_REGISTRY being the problematic line of the two.

```
OPTIONS='--insecure-registry=172.30.0.0/16 --selinux-enabled'
ADD_REGISTRY='--add-registry registry.access.redhat.com --add-registry '
```
 (adds the '=' sign which isn't an issue)
 (adds the trailing --add-registry without a value)

We probably need to make sure we're not adding an empty string to the list of registries and insecure registries.

**Comment by detiber** [comment]
I created https://github.com/openshift/openshift-ansible/pull/516 to address the extra --add-registry param.

**Pull request merged**
