### PR TITLE
crio-firewall: include role lib_os_firewall

### PR DESCRIPTION
**Pull request by giuseppe**
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1529233

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by sdodson** [comment]
/assign michaelgugino
Can you take a look at this? I'm not sure lib_os_firewall will install iptables-services which I believe is the root cause of the bug referenced? I think we need tomake sure that os_firewall role is included instead.

**Comment by michaelgugino** [comment]
os_firewall (which is what ensures iptables is installed) isn't run until the node/master/etcd plays in 3.7.

What is the point in having this port open?  I don't see why the contain runtime needs to provide access to a remote service.

If the port is required for operation of the cluster, then the firewall code needs to be moved to the node/master/etcd or whatever role requires that port to be open.

**Comment by mrunalp** [comment]
@giuseppe The port is used for streaming exec/attach service. It needs to be open so kubectl can connect to the container stdio.

**Comment by michaelgugino** [comment]
@mrunalp Could you go into more detail?  What container are you referring to?  Other container runtimes don't seem to need us to punch this port in the fw, so I would like to get an idea of why it's necessary so we can get it documented properly here and we don't regress on it.

**Comment by giuseppe** [comment]
@michaelgugino does the new version look fine?

**Comment by michaelgugino** [comment]
bot, retest this please

**Comment by michaelgugino** [comment]
/test tox

Flake: Failed to get D-Bus connection: Operation not permitted

**Comment by michaelgugino** [comment]
This isn't a flake, this a problem with tox tests.  We'll have to address that test failure.

**Comment by giuseppe** [comment]
I've rebased the PR

**Comment by sdodson** [comment]
bot, retest this please

**Comment by sdodson** [comment]
bot, retest this please

**Comment by sdodson** [comment]
Removed tox from integration tests in #6790 but failed to merge that before triggering tox this time around, will retry once that job finishes.

**Pull request merged**
