### PR TITLE
oc_atomic_container: support Skopeo output

### PR DESCRIPTION
**Pull request by giuseppe**
we are working on using Skopeo to copy images to the OSTree storage.
The output from atomic will be slightly different.  Support also the new
version.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
aos-ci-test

**Comment by giuseppe** [comment]
aos-ci-test

**Comment by giuseppe** [comment]
[test]

**Comment by giuseppe** [comment]
This is required once https://github.com/projectatomic/atomic/pull/1082 is merged.

The Ansible module for atomic containers already has this change, so it is safe to merge it here as well.

**Comment by ashcrow** [comment]
aos-ci-test

**Comment by giuseppe** [comment]
this is now required by atomic, since the related change got merged: https://github.com/projectatomic/atomic/pull/1082

**Comment by ashcrow** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Pull request merged**
