### PR TITLE
Adding Prometheus 0.23.2

### PR DESCRIPTION
**Pull request by madorn**
Updating rh-operators ConfigMap with Prometheus 0.23.2. See https://github.com/operator-framework/operator-lifecycle-manager/pull/1239

Signed-off-by: Matt Dorn <mdorn@redhat.com>

### CODE REVIEW

**Comment by madorn** [comment]
@sichvoge

**Comment by sichvoge** [comment]
I added some comments but looking further through the PR, I am a bit confused about `PrometheusSpec`, `AlertmanagerSpec` and all the others. Is that generated by something or did you copy and paste the content.

I also asked @s-urbaniak to review just to be sure.

**Comment by madorn** [comment]
@sichvoge just a note that this is the same content of the original PR.

The CRD information is taken directly from upstream Prometheus Operator repo from 0.23.2 branch: https://github.com/coreos/prometheus-operator/tree/v0.23.2/example/prometheus-operator-crd

**Comment by s-urbaniak** [comment]
`PrometheusSpec` is the nested struct of the `Prometheus` CRD and part of the generated documentation, hence this is fine.

**Comment by s-urbaniak** [comment]
ping @madorn i believe i have no permission to approve things here

**Comment by sichvoge** [comment]
If all this ok, the forget about my comments :)

**Comment by s-urbaniak** [comment]
ping @madorn lgtm from my side, do you know whom we can ping to approve?

**Comment by madorn** [comment]
@s-urbaniak not sure

@ecordell @jpeeler - can you help?

**Pull request merged**
