### PR TITLE
Add OpenStack master and node scaleup

### PR DESCRIPTION
**Pull request by tomassedovic**
This adds the `master-scaleup.yml` which can be used to increase the number of master nodes.

We had to change the dynamic inventory in a backwards-incompatible way to achieve this. Previously, the inventory set the `masters` groups directly for every appropriate node in the cluster.

During scaling however, the newly-added nodes must appear in the `new_masters` group but they *must be absent* from `masters`. Since you can't remove nodes from Ansible's inventory at run time, we've renamed the groups the dynamic inventory sets and we translate them to the openshift-ansible groups with the new `evaluate_groups.yml` playbook.

This is a breaking change if you rely on the groups the dynamic inventory used to set: e.g. `masters` or `nodes`, `glusterfs` or `infra_hosts` in your own playbooks. If you do, you should either include `playbooks/openstack/evaluate_groups.yml` or use the new group names: e.g. `openstack_master_nodes`, `openstack_nodes`, `openstack_cns_nodes` or `openstack_infra_nodes`.

Note that `evaluate_groups.yml` creates the openshift-ansible groups (e.g. `masters`, `new_nodes`, `glusterfs`, but not groups that do not exist there (e.g. a group containing the infra nodes only) -- you need to get those from the dynamic inventory.

This also updates the DNS record handling code so only the new records are created on scaleup. This is not a huge deal in the master scaleup but we will be able to use the same mechanism in the node scaleup and there it can actually make a difference.

//cc @mbruzek @jmencak this is the inventory breakage I've mentioned to Matt. This will likely affect your playbooks, but the fixes should be relatively minor. Happy to help and discuss alternatives.

### CODE REVIEW

**Comment by tomassedovic** [comment]
Here's how you would test it:
1. Deploy a cluster with e.g. 1 master node:
    * Set `openshift_openstack_num_masters: 1` in the inventory
    * Run `ansible-playbook ... openshift-ansible/playbooks/openstack/openshift-cluster/provision_install.yml`
2. Wait for the playbook to finish and the cluster to become ready
3. Increase the number of master nodes and run the master-scaleup playbook:
    * `ansible-playbook ... openshift-ansible/playbooks/openstack/openshift-cluster/master-scaleup.yml -e openshift_openstack_num_masters=3`
4. Wait for the playbook to finish, verify:
    * `openstack server list` should show 3 master nodes
    * `oc get nodes --show-labels` should show 3 master nodes in the `Ready` state with matching labels
    * `oc status --suggest` and `oc get pods --all-namespaces` should show no errors or massive pod restarts
5. Delete the cluster
    * `ansible-playbook ... openshift-ansible/playbooks/openstack/openshift-cluster/uninstall.yml`

**Comment by tomassedovic** [comment]
Regarding the inventory breakage, I can see two alternatives:

1. Set a "new node" metadata tag on the OpenStack servers themselves when we create them and use those in the dynamic inventory to populate the `masters` vs. `new_masters` etc. groups.

A downside is that we'll have to clear the `new node` metadata post scaleup and if something get's messed up (e.g. the playbook fails), we could get in a dangerous state.

These days, I'm not keen on this idea (despite having suggested it to @Tlacenka when she did here initial scaleup work, sorry!).

2. Change the master/etcd scaleup logic so the "existing" vs. "new" groups don't have to be exclusive. E.g. that `masters` will have all master nodes (old and new) and `new_masters` only the new ones. This works for the compute and infra nodes (you can have the new nodes both in `nodes` and `new_nodes` during node scaleup). In my testing, the error was somewhere in etcd (so it's possible the only issue is with `etcd` and `new_etcd` having to be exclusive right now -- I hadn't investigated that yet).

If we can fix that, the dynamic inventory could keep setting the `master`, `node` and `etcd` groups as before and the scaleup playbook would just set the `new_*` groups.

I'm not sure how feasible this is, but I do like it and I'd prefer it to the change in this patch.

Since it includes changing the openshift-ansible internals outside of the OpenStack scope, the changes here are isolated and shouldn't affect any other workflows people may be using.

@sdodson would appreciate if you (or someone else you think has a good overview) could comment on the second approach. I.e. making master scaleup works such that the new nodes can be both in `masters` and `new_masters` (and same for etcd).

**Comment by tomassedovic** [comment]
bot, retest this please

**Comment by tzumainn** [comment]
@tomassedovic Still wrapping my head around what's going on, but some quick initial notes about the documentation:

* I think the scaling master section should be combined with the scaling infra/app node sections into one big happy section, since the beginning steps are essentially the same; and as I understand it, the sections about creating a 'new-nodes' file is no longer necessary.

* Is running openshift-ansible/playbooks/openshift-node/scaleup.yml still necessary when scaling infra/app nodes? I kinda assume that the user would run node-scaleup.yml instead, but that's not specified in the documentation.

* If we have the expectation that people may create custom playbooks, it's probably worth documenting that they will want to call evaluate_groups.yml if they want access to the typical openshift host groups.

**Comment by mbruzek** [comment]
This kind of change seems necessary for master scale up. Our automation does not scale the masters after the initial install of 3 but I can see how that would be a good thing.

This change will impact our automation. The code runs a role [after the install is complete](https://github.com/redhat-performance/scale-ci-ansible/blob/master/playbook.yml#L63) that gets the master[0] IP address so we can configure the OpenShift cluster for our tests.

We use the "groups.master" group in [our code](https://github.com/redhat-performance/scale-ci-ansible/blob/master/roles/jenkins_pipeline/tasks/main.yml#L4) to find the first master node for example. The `inventory.py` has been run to install the cluster, but that was in a separate process. Initially I am considering changing the code to use the matching `openstack_master_nodes` group. If anyone knows of a better way to get the master IP address please let me know.

**Comment by tzumainn** [comment]
@mbruzek No problem at all, and apologies if you thought I was rushing you! Thanks for taking the time to take a look at this!

**Comment by tzumainn** [comment]
I think these changes make sense; they're big, but they enable the openstack host groups to match what's apparently expected in the broader openshift-ansible playbooks. All manual testing seems to work - some docs need to be updated a small bit, but that can be done in a followup.

**Comment by sdodson** [comment]
> Change the master/etcd scaleup logic so the "existing" vs. "new" groups don't have to be exclusive. E.g. that masters will have all master nodes (old and new) and new_masters only the new ones. This works for the compute and infra nodes (you can have the new nodes both in nodes and new_nodes during node scaleup). In my testing, the error was somewhere in etcd (so it's possible the only issue is with etcd and new_etcd having to be exclusive right now -- I hadn't investigated that yet).

Discussed this w/ @abutcher who is more familiar with scaleup than I am, we're ok with this approach and we'd be willing to help move towards this approach.
After discussing with @tzumainn we've said we'll go ahead and merge this then we can explore option 2 as potential followup if so desired.

**Comment by sdodson** [comment]
Fedora jobs are broken and are now disabled. Merging.

**Pull request merged**
