### PR TITLE
Update the naming of openshift on rhv to ovirt

### PR DESCRIPTION
**Pull request by sradco**
Updated all references of rhv to use ovirt insread,
since this is an upstream repo.

Accidentally, closed   #9724 PR.
Signed-off-by: Shirly Radco sradco@redhat.com

Please review: @yanivlavi @cwilkers
/assign @vrutkovs
/cc @cwilkers

### CODE REVIEW

**Comment by vrutkovs** [comment]
/ok-to-test

Should `playbooks/rhv` and the rest be removed too?

**Comment by sradco** [comment]
Yes. I'll need to update the patch.Sorry. 
Not sure how I managed to mess up the PR.

**Comment by sradco** [comment]
@cwilkers

**Pull request merged**
