### PR TITLE
Ensure that host pki tree is mounted in containerized components

### PR DESCRIPTION
**Pull request by sdodson**
Ensures that pki trust store from the host is propagated into master and node images

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1460626

### CODE REVIEW

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge][severity: bug]

**Comment by giuseppe** [comment]
@sdodson I've done the related system containers change here: https://github.com/openshift/origin/pull/14741

**Comment by sdodson** [comment]
[merge][severity: bug]

**Comment by sdodson** [comment]
flake on https://github.com/openshift/origin/issues/12773 in https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_openshift_ansible/592/

**Comment by sdodson** [comment]
[merge][severity:blocker]

**Comment by sdodson** [comment]
[merge][severity:blocker]

**Pull request merged**
