### PR TITLE
Bug 1798168: Update RHPAM and RHDM templates and imagestreams on …

### PR DESCRIPTION
**Pull request by spolti**
…OpenShift Service Catalog for release 7.6.0

Signed-off-by: spolti <fspolti@redhat.com>

### CODE REVIEW

**Comment by spolti** [comment]
Hi, can it be merged or is something missing?

**Comment by vrutkovs** [comment]
You'd need a bug filed to pass bugzilla bot

**Comment by spolti** [comment]
It was not necessary on the previous PR, have anything changed?

**Comment by spolti** [comment]
Hi, any updates?

**Comment by spolti** [comment]
Hi @vrutkovs , just created the BZ: https://github.com/openshift/openshift-ansible/pull/12082

is anything else needed?

**Comment by vrutkovs** [comment]
Rename the PR title: `Bug xxxx: Update RHPAM and RHDM templates and imagestreams on`

**Comment by spolti** [comment]
@vrutkovs  can you please advise the correct state the bugzilla should be? it is on the VERIFIED status now but the bot still complaining, should I move it to VERIFIED?

**Comment by vrutkovs** [comment]
The common workflow is making a bug for latest release (4.4.0) and cloning it to a bug which targets 3.11. This workflow is not applicable in 3.11 though

@sdodson could you put `bugzilla/valid-bug` on this PR?

**Comment by sdodson** [comment]
Not relevant to any 4.x implementation, overriding `buzilla/valid-bug`

**Comment by spolti** [comment]
Thanks all.

**Pull request merged**
