### PR TITLE
1505537 Remove pause from master service startup

### PR DESCRIPTION
**Pull request by mtnbikenc**
Pauses may no longer be necessary
Fixes 1505537
https://bugzilla.redhat.com/show_bug.cgi?id=1505537

### CODE REVIEW

**Comment by mtnbikenc** [comment]
@sdodson Is it still worthwhile to proceed with this given that the bug reporter confirmed the issue happened while using a background process? https://bugzilla.redhat.com/show_bug.cgi?id=1505537#c8

**Comment by abutcher** [comment]
I think we can still remove these pauses and if we wanted to get crazy we could probably start the master services in parallel.

**Comment by sdodson** [comment]
> @sdodson Is it still worthwhile to proceed with this given that the bug reporter confirmed the issue happened while using a background process? https://bugzilla.redhat.com/show_bug.cgi?id=1505537#c8

The controllers pause I'm pretty certain we can remove. The API server pause I'm less certain of because I know it can definitely take some time to bootstrap and we should wait for that to happen before starting the rest.

Lets also put together a pause module test case that illustrates the problem and open an upstream issue.

**Comment by mtnbikenc** [comment]
Opened an upstream issue for use of `pause` in a background playbook process.  https://github.com/ansible/ansible/issues/32142

**Comment by mtnbikenc** [comment]
Updated PR to only remove the `pause` for the controller start and combined the startup into a single task.

**Pull request merged**
