### PR TITLE
Fix logging metrics templates

### PR DESCRIPTION
**Pull request by sdodson**
- Remove v1.5 and v1.6 templates, they're no longer used
 - Update enterprise 3.4 templates to use 'v3.4' tag which is a floating tag that moves forward with new builds (to be cherry-picked back to release-1.4 branch)

Ultimately I wonder if this should move to using something like image streams?

### CODE REVIEW

**Comment by sdodson** [comment]
Supersedes #3743 #3742 #3744 #3741 (I think) @ebalsumgo PTAL

**Comment by ebalsumgo** [comment]
so all the PRs are for different version of the file. 1.4 and enterprise, as far as I could tell all of them were completely separate files rather than a link from a central one or anything. so all the PRs are doing the exact same patch into each version. so i suppose cherry pick into whichever one you want it in (latest?) and then backport into the others? up to you guys

**Comment by sdodson** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
[test]

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
[merge]

**Comment by ewolinetz** [comment]
merge flaked on https://github.com/openshift/origin/issues/13814
[merge]

**Comment by ewolinetz** [comment]
[merge]

**Comment by ewolinetz** [comment]
https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_openshift_ansible/275/console

**Pull request merged**
