### PR TITLE
a-o-i-: Allow empty proxy

### PR DESCRIPTION
**Pull request by smunilla**

### CODE REVIEW

**Comment by brenton** [comment]
LGTM. @detiber

**Comment by sdodson** [comment]
This will set the variables to empty strings rather than undefined? that should be fine, testing real quicklike

**Comment by brenton** [comment]
@sdodson, thx!

**Comment by sdodson** [comment]
Seems fine in a quick test.

**Comment by detiber** [comment]
@smunilla looks like pylint is not happy.

**Comment by smunilla** [comment]
@detiber Trailing whitespace fixed

**Pull request merged**
