### PR TITLE
images, syscontainer: change default value for ANSIBLE_CONFIG

### PR DESCRIPTION
**Pull request by giuseppe**
Change it to /usr/share/atomic-openshift-utils/ansible.cfg

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1461281

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by sdodson** [comment]
Do we know why that path changed?

**Comment by giuseppe** [comment]
@sdodson not really sure why/how it changed, but this is the file coming from atomic-openshift-utils:

```bash
rpm -qf /usr/share/atomic-openshift-utils/ansible.cfg
atomic-openshift-utils-3.6.121-1.git.0.ed0b72c.el7.noarch
```

**Comment by ashcrow** [comment]
CI won't test this. @sdodson merge at will.

**Comment by sdodson** [comment]
Looks like it's been that way for quite some time.

c2f3f81d92 (Devan Goodwin        2015-11-10 08:20:24 -0400  277) %{_datadir}/atomic-openshift-utils/ansible.cfg

**Pull request merged**
