### PR TITLE
Add target mount for gluster block

### PR DESCRIPTION
**Pull request by mjudeikis**
Adding target folder mount for gluster block to persist configuration. 
Resolves: #7198
BZ: 1540080

### CODE REVIEW

**Comment by mjudeikis** [comment]
@jarrpa @datarace

**Comment by datarace** [comment]
LGTM

**Comment by SaravanaStorageNetwork** [comment]
minor comment:

/s/glusterfs-target/glusterfs-block/

**Comment by mjudeikis** [comment]
This is my question too... 

Should be following host path naming convention (as it is now) or should we do purpose based (as per suggestion). 

I prefer host path naming convention for HostPath and Purpose for config/secrets/volumes as it makes debugging much easier when tracking volume names.

**Comment by jarrpa** [comment]
This is backporting an existing feature in the templates of cns-deploy, where we named it `gluster-block`. Regardless, this is good enough for now. It introduces some undesirable divergence between the two template locations, but that's just more incentive to consolidate them into one faster. :)

/lgtm

**Comment by jarrpa** [comment]
@mjudeikis Can you reference "Resolves: #7198" and any relevant BZs in the initial comment / description?

**Comment by mjudeikis** [comment]
@jarrpa done. +1 for consolidation plan ;)

**Pull request merged**
