### PR TITLE
Testing hooks.

### PR DESCRIPTION
**Pull request by kwoodson**

### CODE REVIEW

**Comment by kwoodson** [comment]
ok to test

**Comment by kwoodson** [comment]
ok to test

**Comment by kwoodson** [comment]
ok to test

**Comment by kwoodson** [comment]
ok to test

**Comment by kwoodson** [comment]
ok to test

**Comment by kwoodson** [comment]
ok to test

**Comment by kwoodson** [comment]
ok to test

**Comment by kwoodson** [comment]
ok to test

**Comment by twiest** [comment]
:+1:

**Pull request merged**
