### PR TITLE
Temporarilly only migrate jobs as we were before

### PR DESCRIPTION
**Pull request by sdodson**

### CODE REVIEW

**Comment by sdodson** [comment]
@deads2k let us know when we can revert this

**Comment by deads2k** [comment]
> @deads2k let us know when we can revert this

Can't say I'm a fan of intentionally breaking the queue and then trying to fix it up instead of reverting the queue breaker :(.

Here's an issue: https://github.com/openshift/origin/issues/14743

**Comment by sdodson** [comment]
@deads2k This PR reverted the change that widened the storage migration from just jobs to all items. Are you saying that there's an origin change that should've been reverted instead?

**Comment by deads2k** [comment]
> @deads2k This PR reverted the change that widened the storage migration from just jobs to all items. Are you saying that there's an origin change that should've been reverted instead?

The offender looked different (more lines), but if this does the same thing I'm ok with it.  Doesn't ansible have to pass upgrade tests to merge too?

**Comment by sdodson** [comment]
> The offender looked different (more lines), but if this does the same thing I'm ok with it. Doesn't ansible have to pass upgrade tests to merge too?

Yes, but I manually merged the offending PR in haste.

**Pull request merged**
