### PR TITLE
Fix access_modes initialization

### PR DESCRIPTION
**Pull request by luisfdez**
This PR fixes how the `access_modes` are initialized from the parameters.

### CODE REVIEW

**Comment by sdodson** [comment]
Hmm, i would've expected it to be fine how it was. @abutcher thoughts?

**Comment by sdodson** [comment]
bot, test pull request

**Comment by abutcher** [comment]
LGTM but we'll also need to nest the `access_modes` in the default facts dict in the `openshift_facts` module https://github.com/openshift/openshift-ansible/blob/14debfe6456ee6185e77c160da0b8b18641b4694/roles/openshift_facts/library/openshift_facts.py#L1981-L2036. Thanks @luisfdez

**Comment by luisfdez** [comment]
Thanks @abutcher for the comments (sorry for the delay but I missed the notifications).

I just updated the code with your suggestions and rebased the code against master.

Please let me know if now is fined or further modifications are needed.

Cheers,
Luis

**Comment by abutcher** [comment]
aos-ci-test

**Comment by abutcher** [comment]
ok to test

**Comment by rhcarvalho** [comment]
> Hmm, i would've expected it to be fine how it was.

I also failed to understand what was fixed here.

[`PersistentVolumeSpec.AccessModes`](https://github.com/kubernetes/kubernetes/blob/16f7cd189c1a1ec9fc2ef2fd2e4e29b2b333deb9/pkg/api/v1/types.go#L452) is a list of strings, as per the Kubernetes API, there isn't a concept of "access" with a "mode" inside.

This is different than e.g. `params['volume']` that has a `'name'` and `'size'`. The code strangely never uses `params['access']` alone, but instead always access two levels `params['access']['modes']`.

For the sake of learning something new, is there something more to access modes that require this change?

**Comment by abutcher** [comment]
Hey @rhcarvalho, the problem was that parameters passed in like `openshift_hosted_registry_storage_access_modes=['ReadWriteOnce']` get automatically split by `openshift_facts` into a dictionary like `{"openshift": "hosted": {"registry": {"storage": "access": {"modes": ["ReadWriteOnce"]}}}}` and overriding access modes wasn't possible since we were attempting to access the key `"access_modes"`. Variable splitting like this is only done for a subset of parameters and will likely be phased out piece by piece because it's kind of magical and hard to deal with.

**Comment by rhcarvalho** [comment]
> the problem was that parameters passed in like openshift_hosted_registry_storage_access_modes=['ReadWriteOnce'] get automatically split by openshift_facts into a dictionary like {"openshift": "hosted": {"registry": {"storage": "access": {"modes": ["ReadWriteOnce"]}}}}

@abutcher aha, got it. Yeah, I've seen this type of magic in Rails... is this some feature of Ansible or custom code we have. Where can one find more about it? Thanks!

**Pull request merged**
