### PR TITLE
Standardize openshift_provisioners entry point

### PR DESCRIPTION
**Pull request by mtnbikenc**
Adding a `byo` entry point to standardize the playbook flow for openshift_provisioners.

### CODE REVIEW

**Comment by mtnbikenc** [comment]
@wongma7 Good catch on the dash/underscore.  I'll at least attempt to have some consistency with the majority of the files.

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Comment by mtnbikenc** [comment]
Flake https://github.com/openshift/origin/issues/13827

**Comment by mtnbikenc** [comment]
[merge]

**Pull request merged**
