### PR TITLE
Removing resourceVersion when replacing objects.

### PR DESCRIPTION
**Pull request by kwoodson**

### CODE REVIEW

**Comment by kwoodson** [comment]
@ashcrow @sdodson,

I wrote a test to patch a resource 3 times in a tight loop and then run oc_edit in a loop externally.
- Before the change we were seeing the error > 50-60% of the time where the ` the object has been modified`.  
- After the change I was able to see this occur 0-2% of the time in the same test.

I think this is the best solution to reduce the race condition.

**Comment by ashcrow** [comment]
[test]

**Comment by kwoodson** [comment]
aos-ci-test

**Comment by kwoodson** [comment]
[test]

**Comment by kwoodson** [comment]
aos-ci-test

**Comment by kwoodson** [comment]
[test]

**Comment by kwoodson** [comment]
[merge]

**Pull request merged**
