### PR TITLE
added copr-openshift-ansible releaser, removed old rel-eng stuff.

### PR DESCRIPTION
**Pull request by twiest**

### CODE REVIEW

**Comment by mwoodson** [comment]
:+1:

**Comment by detiber** [comment]
@sdodson @dgoodwin Will this affect us?

**Comment by dgoodwin** [comment]
@detiber nope should be fine, new releaser won't affect us, the config file removed is a dead one replaced by the still in use .tito/tito.props.

**Comment by sdodson** [comment]
Looks fine to me.

**Comment by twiest** [comment]
@detiber @dgoodwin @sdodson sorry, I should've at mentioned you guys. I tested this and made sure that it worked properly, so I was pretty confident it wouldn't break anyone, but yeah, I should have still at mentioned you guys so you could weigh in.

I'll do that next time. Sorry.

**Pull request merged**
