### PR TITLE
[WIP] Add etcd nodes management in OpenStack

### LINKED ISSUE #472: etcd node is not created with OpenStack
I run

    ./bin/cluster -v create -t origin -m 1 -n 1 -i 1 -e 1 -o dns=10.0.0.53 \
     -o master_flavor=t1.small \
     -o node_flavor=t1.small -o infra_flavor=t1.small -o image_name=centos-7-amd64 \
     openstack openshift

to deploy OpenShift on OpenStack. This command is expected to create four nodes:

* master node
* compute node
* infra node
* etcd node

But there are only three nodes are created. It seems there are not `etcd` nodes.

### PR DESCRIPTION
**Pull request by lhuard1A**
Fixes #472

### CODE REVIEW

**Comment by lhuard1A** [comment]
@xionglingfeng : As you reported #472 , could you please validate that this PR fixes that issue for you?

**Comment by detiber** [comment]
@twiest @wshearn please review/merge

**Comment by wshearn** [comment]
Says openstack but it is the libvirt playbook that was updated, am I missing something here?

**Comment by lhuard1A** [comment]
@wshearn . Sorry, it seems that I pushed the wrong commit… Let me fix that…

**Comment by xionglingfeng** [comment]
@lhuard1A , I tested this PR and found there are no etcd nodes created in OpenStack. Also, it looks like this PR add etcd nodes in `libvirt` instead of `OpenStack`?

**Comment by jaryn** [comment]
Can one of the admins verify this patch?

**Comment by jaryn** [comment]
Can one of the admins verify this patch?

**Comment by arilivigni** [comment]
Testing job has been triggered.

**Comment by arilivigni** [comment]
Internal Jenkins error during triggering.
 No test results found.

**Comment by lhuard1A** [comment]
Replaced by #996.

**Pull request closed without merging**
