### PR TITLE
Clean up test dir: delete 3.X CI & move libvirt to hack

### PR DESCRIPTION
**Pull request by patrickdillon**
[BYOH 224 Clean up Test] (https://jira.coreos.com/browse/BYOH-224)

The CI subdir is only needed in 3.X. 

In my opinion, test dir should only be for CI, unit, and other testing.  Libvirt for local devel would be more appropriate in hack dir (I think).

### CODE REVIEW

**Comment by patrickdillon** [comment]
/hold 
make sure @sdodson ok with moving libvirt to hack

**Comment by sdodson** [comment]
/hold cancel
Yeah that's fine.

**Pull request merged**
