### PR TITLE
Fix auditConfig for non-HA environments

### PR DESCRIPTION
**Pull request by mtnbikenc**
Bug 1447019

### CODE REVIEW

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
GH_STATE=error
GH_DESC="Internal Jenkins error during provisioning an 3.5 cluster"
GH_CONTEXT=aos-ci-jenkins/OS_3.5_NOT_containerized

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
[merge][severity: blocker]

**Pull request merged**
