### PR TITLE
Make masters schedulable by default

### LINKED ISSUE #6930: origin-web-console nodeSelector makes it unschedulable by default
https://github.com/openshift/openshift-ansible/pull/6882 set the web-console nodeSelector to `node-role.kubernetes.io/master: true`.  The master is cordoned by default.  Thus the web-console fails to schedule unless the default `openshift_web_console_nodeselector` is overridden or the master is manually uncordoned.

https://github.com/openshift/openshift-ansible/pull/6882#commitcomment-27173327
https://github.com/openshift/openshift-ansible/issues/6912#issuecomment-361026002

Is there a reason this pod must run on the master?

@sdodson @spadgett @smarterclayton

### PR DESCRIPTION
**Pull request by vrutkovs**
Fixes #6930

### CODE REVIEW

**Comment by sdodson** [comment]
/test install

Implementation looks fine, can you take a look at all occurences of '_schedulable' in inventory/ and remove things that mark masters are unschedulable and this section https://github.com/openshift/openshift-ansible/blob/master/inventory/hosts.example#L1116-L1118

**Comment by vrutkovs** [comment]
>Implementation looks fine, can you take a look at all occurences of '_schedulable' in inventory/ and remove things that mark masters are unschedulable and this section https://github.com/openshift/openshift-ansible/blob/master/inventory/hosts.example#L1116-L1118

Done, added a note mentioning why masters should be schedulable

**Comment by vrutkovs** [comment]
flakes

/retest

**Comment by sjenning** [comment]
So.. if I set `openshift_schedulable=false` on my master, it will break webconsole deployment per https://github.com/openshift/openshift-ansible/issues/6930 ?

I just deployed today and builds and pods are running on my master :-/

**Comment by michaelgugino** [comment]
@sjenning You won't be able to deploy a webconsole.

You can label your masters (see inventory/hosts.example for an example).  In upcoming releases, master services will be running as static pods; labels will be critical to get right.

**Comment by derekwaynecarr** [comment]
Are masters tainted and is the webconsole applying a toleration?

**Comment by sjenning** [comment]
@derekwaynecarr right now, we are using labels with a node selector in the web-console deployment. https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_web_console/defaults/main.yml#L2

There is a WIP PR to move to taints https://github.com/openshift/openshift-ansible/pull/6932.

**Pull request merged**
