### PR TITLE
[3.5 Backport] Resolve deprecation warnings in Contiv roles

### PR DESCRIPTION
**Pull request by mtnbikenc**
Backports #4479

### CODE REVIEW

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by tbielawa** [comment]
Looks like CI fail was unrelated to this PR

```
[EnvInject] - Variables injected successfully.
[openshift-ansible-slave] $ python /tmp/hudson3005405940977483119.py
Updating status for f39ab34c7ea57efd2ceff9c7b4ccfee2ed6a426c
Failed to update commit status [HTTP 405]
{'date': 'Mon, 31 Jul 2017 16:59:40 GMT', 'x-github-request-id': 'FF2D:3089:21B9946:530C578:597F61FC', 'content-length': '166', 'content-type': 'text/html', 'server': 'GitHub.com'}
Traceback (most recent call last):
  File "/tmp/hudson3005405940977483119.py", line 39, in <module>
    print r.json()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib64/python2.7/site-packages/simplejson/__init__.py", line 501, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 393, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Build step 'Execute Python script' marked build as failure
```

**Comment by mtnbikenc** [comment]
aos-ci-test

**Pull request merged**
