### PR TITLE
WIP - Remove all provider fact magic when cloud provider is configured

### PR DESCRIPTION
**Pull request by sdodson**
This doesn't fulfil the requirements for autoscaling nodes. Need to figure out a way to re-introduce that.

Related #9647

### CODE REVIEW

**Comment by sdodson** [comment]
@thoraxe Give this a shot, `git clone https://github.com/sdodson/openshift-ansible --branch master-nodename`

**Comment by sdodson** [comment]
@mazzystr @kwoodson 
I'm told that we need to use the raw hostname for autoscaled nodes. When this was first implemented it assumed all bootstrapped nodes were autoscaled nodes. Is there a better way to infer when we're dealing with an autoscaled node?

**Comment by sdodson** [comment]
@thoraxe I've stubbed out all the provider fact discovery, this will probably work, can you confirm?

**Comment by thoraxe** [comment]
@sdodson I did manage to have a successful install with the following status/commit:

```
commit b9aa4805dad7dec6309285d7e1e03ed12c3ac8aa
Author: Scott Dodson <sdodson@redhat.com>
Date:   Tue Aug 21 17:44:15 2018 -0400

    Just stub out all the provider facts
```

There are other issues in the environment but the install itself ran successfully.

If you want the logs I have complete logs of prereq and deploy (the latter with vvv)

**Comment by vrutkovs** [comment]
Master branch is closed! A major refactor is ongoing in devel-40. Changes for 3.x should be made directly to the latest release branch they're relevant to and backported from there.

**Pull request closed without merging**
