### PR TITLE
Add a playbook that runs prerequisites before the provision_install

### PR DESCRIPTION
**Pull request by zgalor**
This will allow running these 2 playbooks one after another in a single job

@mwoodson Please review

### CODE REVIEW

**Comment by zgalor** [comment]
@sdodson PTAL

**Comment by zgalor** [comment]
@michaelgugino that could be said for every ansible playbook.
Question is, why shouldn't we provide a way to run this in a single playbook?
In there a use case of running `provision_install.yml` without running `prerequisites.yml` before?
And if there is, which use case is more common?

**Comment by vrutkovs** [comment]
In GCP there's one playbook to run the whole cluster - `launch.yml` - and a bunch of entrypoint playbooks to run a custom install.

IMHO AWS playbooks should follow that pattern, there is no benefit in a playbook which only does part of the job and calls two other playbooks

**Comment by michaelgugino** [comment]
@zgalor 
 > In there a use case of running provision_install.yml without running prerequisites.yml before?

In the context of aws installs, yes.  aws/prerequisites.yml sets up things like ssh keys, security groups, vpcs, etc.  This might not be desirable in all cases.  I don't think people should create this kind of stuff on their account without reading the documentation and understanding *why* they are running that particular playbook.  Inevitably, people will just run the all-in-one playbook without considering the implications.

@vrutkovs scope of the gcp plays is much smaller in terms of provisioning things on the cloud.  Things like vpcs and security groups have to already be in place.

**Comment by brenton** [comment]
FWIW, I'd probably side with Ops on this one.  It's trivial and they are the reason we maintains this code.

**Comment by sdodson** [comment]
/lgtm
It's not supported for customer use so no objection.

**Comment by DanyC97** [comment]
@zgalor my 2 cents here:

* before this PR get's merged the [docs](https://github.com/openshift/openshift-ansible/blob/master/playbooks/aws/README.md) needs updating
* i personally don't agree with adding another _wrapper_ around the 2 playbooks `prerequisites` & `provision_install` for few reasons:
  * if we say that an _operator_ will always run the above playbooks _all_in_one_ then we should better cut deeper and reduce the number of individual playbooks we currently have
  * saying that - as @michaelgugino said, there was a good reason for having group of tasks bundled in playbooks for each stage of the deployment and as such if you or someone else feel that _is too easy_ then you can easily wire the playbooks in _all-in-one_ outside of this repo

so to cut it short, if i would have to vote i'll be -1 on this PR and +1 on @michaelgugino 's comment.

**Comment by zgalor** [comment]
closing.
Will provide an external script

**Pull request closed without merging**
