### PR TITLE
Run console pods on the master

### PR DESCRIPTION
**Pull request by spadgett**
Update the node selector for the console so that it runs on the masters.

/assign @sdodson

### CODE REVIEW

**Comment by sdodson** [comment]
ACK, I'll test this in the context of an upgrade, thanks.

**Comment by spadgett** [comment]
```
failure: repodata/repomd.xml from google-cloud-sdk: [Errno 256] No more mirrors to try.
https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 502 - Bad Gateway
```

/test gcp

**Comment by spadgett** [comment]
It looks like the console pods didn't start in GCP.

cc @smarterclayton 

```
FAILED - RETRYING: Verify that the web console is running (1 retries left).
fatal: [ci-prtest-fa08ce7-98-ig-m-m47p]: FAILED! => {"attempts": 120, "changed": false, "cmd": ["curl", "-k", "https://webconsole.openshift-web-console.svc/healthz"], "delta": "0:00:01.040267", "end": "2018-01-25 22:15:29.837632", "msg": "non-zero return code", "rc": 7, "start": "2018-01-25 22:15:28.797365", "stderr": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (7) Failed connect to webconsole.openshift-web-console.svc:443; Connection refused", "stderr_lines": ["  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current", "                                 Dload  Upload   Total   Spent    Left  Speed", "", "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0", "  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (7) Failed connect to webconsole.openshift-web-console.svc:443; Connection refused"], "stdout": "", "stdout_lines": []}
```

**Comment by smarterclayton** [comment]
You need https://github.com/openshift/release/pull/566 because we don't let ansible set the labels.

**Comment by smarterclayton** [comment]
Should be set now

/retest

**Comment by spadgett** [comment]
@smarterclayton thanks!

**Comment by smarterclayton** [comment]
Well, except for epel sucking

/test gcp

**Comment by spadgett** [comment]
Opened https://github.com/openshift/origin/issues/18301

/test gcp

**Comment by sdodson** [comment]
I've verified that masters are labeled appropriately during upgrade and the console lands on the masters if they were already schedulable. I'm going to do another test to verify that if masters were previously unschedulable (default behavior for masters prior to 3.9) they're marked schedulable during the upgrade unless explicitly marked unschedulable in the inventory. We'll want to make sure we put in a release note that hi-lights this change so that anyone who may have been marking them unschedulable in their inventory removes that prior to upgrading.

**Comment by smarterclayton** [comment]
@sdodson so the note here is that when the masters are also a scale group with bootstrapping (which is where we are going) the node config for that group has to have the label.  So the traditional install path and the cloud path are going to set labels two different ways.

**Comment by sdodson** [comment]
Everything thing checks out on the upgrade path.
/lgtm

**Pull request merged**
