### PR TITLE
Fix issues when using as non-root user which home is mounted from a r…

### PR DESCRIPTION
**Pull request by crmarques**
Fix issue when using a non-root user whose homedir is mounted from a remote file system.

Previous this commit, the modified playbooks/roles run as root when creating dirs and files to configure ~$user/.kube for the non-root user. When this non-root user's homedir is mounted from a remote dir, root has no permission to execute this modification and the playbook fails.

The default behavior for NFS mount is "root_squash", which means that root from the NFS client machine is mapped to nobody user and group ID when accessing the remote file system, so it have no permission to edit the user's homedir.

This setup (one server for users' homedirs that are mounted in all hosts) might be a common one.

This pull request implements the following steps:

- create the .kube dir using the flag become_user set to the user;
- copy the admin.kubeconfig to a temporary file with permissions for user to read;
- using the flag become_user set to the non-root user, copy the file to its own homedir;
- remove the tempory file;
- correct permissions

I recreate this PR from #9433 to the master branch.

### CODE REVIEW

**Comment by crmarques** [comment]
@michaelgugino, I probably was not clear.

My inventory is configured with the following lines:

ansible_user=userA
ansible_become=true

As the ansible.cfg is configure with "remote_user = root", ansible runs commands as root on remote hosts (let's call them ocp-serverX).

The problem is that this root user from ocp-serverX has no permission to write in userA's homedir because it is a directory mounted (with the default flag "root_squash") from remote NFS server on the ocp-serverX.

**Comment by michaelgugino** [comment]
@crmarques 
> The problem is that this root user from ocp-serverX has no permission to write in userA's homedir because it is a directory mounted (with the default flag "root_squash") from remote NFS server on the ocp-serverX.

We don't have ansible write to any user's home directory, other than possibly root.

Please create a bug report with actual failure messages from an actual playbook run, you might be having some other problem.

**Comment by crmarques** [comment]
@michaelgugino, I can open an issue. But if you look at changed files (https://github.com/openshift/openshift-ansible/pull/9474/files#diff-f2c54fda82b66a7764fc60ac952eea8a) you can see that some ansible playbooks try to create the .kube dir inside the ansible_user's homedir and copy admin.kubeconfig into it.

```
  - set_fact:
      client_users: "{{ [ansible_ssh_user, 'root'] | unique }}"
  - name: Create the client config dir(s)
    file:
      path: "~{{ item }}/.kube"
      state: directory
      mode: 0700
      owner: "{{ item }}"
      group: "{{ 'root' if item == 'root' else _ansible_ssh_user_gid.stdout  }}"
    with_items: "{{ client_users }}"
  - name: Copy the admin client config(s)
    copy:
      src: "{{ openshift.common.config_base }}/master/admin.kubeconfig"
      dest: "~{{ item }}/.kube/config"
      remote_src: yes
    with_items: "{{ client_users }}"
  - name: Update the permissions on the admin client config(s)
    file:
      path: "~{{ item }}/.kube/config"
      state: file
      mode: 0700
      owner: "{{ item }}"
      group: "{{ 'root' if item == 'root' else _ansible_ssh_user_gid.stdout  }}"
    with_items: "{{ client_users }}"
```

For instance, disregarding Ansible, root has no permission on this directory "/rhome/my-user", because it is mounted from a remote NFS server with "root_squash" enabled (for security reasons).

```
[root@ocp-master01 ~]# touch /rhome/my-user/bla
touch: cannot touch ‘/rhome/my-user/bla’: Permission denied
```

**Comment by michaelgugino** [comment]
@crmarques 

Okay, I didn't realize the modules were taking '~{{ item }}/x' as home directory for said user.

I think if this is the case, then it's possible the user with nfs home directory is provisioning more than one cluster, and copying this file there doesn't make sense.

Perhaps we should just set failed_when to false, I'm not a fan of manipulating tasks with become statements, @sdodson what do you think?

**Comment by vrutkovs** [comment]
Master branch is closed! A major refactor is ongoing in devel-40. Changes for 3.x should be made directly to the latest release branch they're relevant to and backported from there.

**Pull request closed without merging**
