### PR TITLE
Bug 1322335 - The package name is wrong for rpm upgrade

### PR DESCRIPTION
**Pull request by brenton**

### CODE REVIEW

**Comment by brenton** [comment]
aos-ci-test

**Comment by brenton** [comment]
aos-ci-test

**Comment by brenton** [comment]
We haven't had time to debug the 3.1 containerized install yet so I suspect it will fail.

**Comment by brenton** [comment]
@detiber, this is the PR I mentioned during scrum.

**Comment by detiber** [comment]
@brenton ah, lgtm

**Comment by brenton** [comment]
The containerized failure is unrelated to this change.  I believe it's due to https://bugzilla.redhat.com/show_bug.cgi?id=1322728

**Pull request merged**
