### PR TITLE
adhoc/tutorial_reset: Cleanup the cleanup

### PR DESCRIPTION
**Pull request by cgwalters**
I'd like this playbook to always work.

### CODE REVIEW

**Comment by detiber** [comment]
:+1: @brenton @sdodson

**Comment by wshearn** [comment]
ok to test

**Comment by brenton** [comment]
@wshearn, What testing are you referring to?  Something formal?  In cases of playbooks that aren't yet widely used I prefer to let peer review gate the merge.  If it's reviewed and the only team it could really break is the team that created the playbook and authored the PR then I don't think we have to do additional testing.

**Comment by detiber** [comment]
@brenton The testing is the jenkins test that basically just runs pylint on the repo.

**Comment by brenton** [comment]
@detiber, ok.  I guess I'm just confused.  @wshearn, does "ok to test" mean, "the automated tests passed therefore +1 from me", or "I approve of the change now someone go test this"?

**Comment by wshearn** [comment]
@brenton the ok to test kicks off the tests and they passed.

**Comment by wshearn** [comment]
and it just kicked it off again :D

**Comment by sdodson** [comment]
Should probably change it to look for [test] just to be uniform with all
the other openshift jobs.

**Comment by brenton** [comment]
I'm curious what happens if I say, "this is not ok to test". :)

**Pull request merged**
