### PR TITLE
Configure logrotate on atomic.

### PR DESCRIPTION
**Pull request by abutcher**
@sdodson PTAL - logrotate comes standard with atomic so we can just skip the package install afaik

### CODE REVIEW

**Comment by detiber** [comment]
lgtm, assuming it works on an atomic host :smile:

**Comment by abutcher** [comment]
@detiber We only set `logrotate_scripts` on ec2, yeah?

**Comment by abutcher** [comment]
^ meaning this would basically be a noop on atomic but the configuration would occur if we had any

**Comment by detiber** [comment]
@abutcher nope, the common playbooks are used by the byo playbook as well

**Comment by sdodson** [comment]
LGTM, as far as I can tell this will only enable logrotate which seems fine. The aws playbook is the only playbook that actually defines some logrotate scripts, we may want to consider moving that definition into the common playbooks?

**Comment by abutcher** [comment]
aos-ci-test

**Comment by detiber** [comment]
@sdodson I'm not sure we want to manage a user's logrotate config (unless they want us to at least).

Maybe we can offer some examples in the docs and let them "opt in"

**Comment by abutcher** [comment]
@sdodson @detiber Added an example to byo inventories

**Comment by detiber** [comment]
:+1:

**Comment by abutcher** [comment]
@brenton

**Pull request merged**
