### PR TITLE
Update catalog role patching to use new names

### PR DESCRIPTION
**Pull request by jpeeler**
This is a new capability to use aggregated roles rather than modifying
the roles directly.

### CODE REVIEW

**Comment by jpeeler** [comment]
I haven't personally tested this yet. Will update once I do, though I'm hoping CI will beat me.

**Comment by jpeeler** [comment]
I've tested this now and it works as expected. The last crio job failure was a skopeo package install failure.
/test crio

**Comment by jpeeler** [comment]
This is a fix for https://bugzilla.redhat.com/show_bug.cgi?id=1537050

**Comment by sdodson** [comment]
/priority p0
This is a test blocker.

**Pull request merged**
