### PR TITLE
Add Prometheus scrape config for openshift-logging

### LINKED ISSUE #8602: Add Prometheus scrape config for openshift-logging
To make it possible for Prometheus to scrape Elasticsearch nodes running in Openshift logging project working correctly we need to provide barer token in Prometheus job configuration.

This work started in https://github.com/openshift/origin/pull/19789 and for the needs of OCP 3.9 backport we are going to update the prometheus configuration by declaring a new job for logging only. 

In later OCP releases there should be cluster operators that may deal with this subject differently.

### PR DESCRIPTION
**Pull request by lukas-vlcek**
Closes #8602

### CODE REVIEW

**Comment by vrutkovs** [comment]
bot, retest this please

**Comment by vrutkovs** [comment]
Holding until 3.10 is branched

/hold

**Comment by jcantrill** [comment]
@vrutkovs Can you approve this so it goes into master and we can cherry-pick it back to 3.10 and possibly 3.9

**Comment by vrutkovs** [comment]
@jcantrill sure

/approve
/lgtm
/cherrypick release-3.10

**Comment by lukas-vlcek** [comment]
@jcantrill @vrutkovs 
Shouldn't we retest first? It PR has been sitting here for some time now...

**Pull request merged**
