### PR TITLE
[3.6] dist.iteritems() no longer exists in Python 3.

### PR DESCRIPTION
**Pull request by adelton**
(cherry picked from commit 37636c325aed612c06f86cbb042fc14bcbde218c)
(cherry picked from commit f776a316f90effe6d2ac69c54dcd59d3c8e00c0d)

### CODE REVIEW

**Comment by adelton** [comment]
Likely should go in only after the cherry pick to 3.7 https://github.com/openshift/openshift-ansible/pull/6308 gets merged.

**Comment by mtnbikenc** [comment]
Kicking tests.

**Comment by sdodson** [comment]
bot, test this please

**Pull request merged**
