### PR TITLE
[release-3.10] Calico: Add support for environment variable IP_AUTODETECTION_METHOD

### PR DESCRIPTION
**Pull request by steveteuber**
This is an cherry-pick of #11357

### CODE REVIEW

**Comment by steveteuber** [comment]
@mtnbikenc I'm in contact with Travis-CI to figure out why my PRs trigger their abuse detection.

**Comment by steveteuber** [comment]
Travis-CI has automatically flagged my account for possible abuse.
The problem has been solved, thanks to Dominic from Travis-CI.

@mtnbikenc Could you please say `/retest`

**Comment by mtnbikenc** [comment]
Triggering retest including Travis.
/close

**Pull request merged**
