### PR TITLE
Always deduplicate detected certificate names

### LINKED ISSUE #2430: Named certificates with SANs cause duplicate name entries when cacert is specified
When deploying custom named certificates, if you don't specify the names, [they will be detected from the certificate's CN and SANs][detect]. Now, the first entry in a certificate's SAN list is always the CN. As such, the resulting list needs to be deduplicated. And, as it turns out, [this is done][dedupe].

Unfortunately, for some reason, this is only done if the `cacert` field on the Ansible certificate object [is unspecified][bug]. I'm not quite sure the purpose of the preceding line but I think the aim is to not use self-signed certificates for internal communications.

In any event, the deduplication of the name list should be performed regardless of whether or not a value for `cacert` is provided. As it stands, if you specify `cacert` but not `names` for a certificate with SANs, you'll get an entry in `master-config.yaml`'s `named_certificates` field that looks like this:
```yaml
- certFile: /etc/origin/master/named_certificates/console.crt
  keyFile: /etc/origin/master/named_certificates/console.key
  names:
  - "subdomain.example.com"
  - "subdomain.example.com"
  - "example.com"
```
Which will then cause the `origin-master` service to fail with the following error:
> servingInfo.namedCertificates[0].names[1]: Invalid value: "subdomain.example.com": this name is already used in another named certificate

[detect]: https://github.com/openshift/openshift-ansible/blob/openshift-ansible-3.4.1-1/filter_plugins/oo_filters.py#L509-L537
[dedupe]: https://github.com/openshift/openshift-ansible/blob/openshift-ansible-3.4.1-1/filter_plugins/oo_filters.py#L533
[bug]: https://github.com/openshift/openshift-ansible/blob/openshift-ansible-3.4.1-1/filter_plugins/oo_filters.py#L531-L533

### PR DESCRIPTION
**Pull request by elyscape**
Fixes #2430

### CODE REVIEW

**Comment by elyscape** [comment]
Also, should I backport this patch to any other branches? This issue affects them all.

**Comment by johnr-spindance** [comment]
👍

**Comment by abutcher** [comment]
ok to test

**Comment by abutcher** [comment]
aos-ci-test

**Comment by abutcher** [comment]
LGTM, defer to @sdodson regarding backports

**Comment by detiber** [comment]
lgtm

**Comment by abutcher** [comment]
aos-ci-test

**Pull request merged**
