### PR TITLE
Refactor openshift_projects

### PR DESCRIPTION
**Pull request by mtnbikenc**
The openshift_projects role has been refactored down to one task.  That one task has been moved into the openshift_hosted role since that was the only role calling the projects role.  However, It may be better to move this task somewhere else, given that openshift_hosted will be eventually split into _registry and _router roles.

### CODE REVIEW

**Comment by detiber** [comment]
@mtnbikenc There is potential that other components could make use of a common method of creating and managing projects. @ewolinetz would it make sense to share project management tasks for logging and metrics?

There are also the efforts to deploy integrated projects/projects such as ManageIQ/CloudForms, GlusterFS, etc which would have similar requirements.

**Comment by mtnbikenc** [comment]
@detiber In those instances where projects need to be created, would it not make sense to just call the `oc_project` module to create them as needed, instead of calling a role that has one task?  Additionally, that one task would need to essentially default all the options of the `oc_project` module, an interface to an interface.  The logic in the original role was limited to idempotently creating a project, which is handled within the module.

**Comment by mtnbikenc** [comment]
aos-ci-test
[test]

**Comment by mtnbikenc** [comment]
This PR depends on https://github.com/openshift/openshift-ansible/pull/3654 being merged.

**Comment by mtnbikenc** [comment]
aos-ci-test
[test]

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
[merge]

**Pull request merged**
