### PR TITLE
Bug 1549220 - configmap still exist after running uninstall playbook for logging

### PR DESCRIPTION
**Pull request by nhosoi**
Adding logging-elasticsearch-ops to delete configmaps item.

### CODE REVIEW

**Comment by nhosoi** [comment]
@richm , @jcantrill , @ewolinetz 
Could you please review this PR (finally...)?  Thanks!

**Comment by nhosoi** [comment]
> ci/openshift-jenkins/logging — Jenkins job failed. 

Depending on this PR: https://github.com/openshift/origin-aggregated-logging/pull/993

**Comment by richm** [comment]
@jcantrill @ewolinetz can one of you manually merge this?

**Comment by richm** [comment]
@sdodson can you please just merge this PR manually?

**Comment by richm** [comment]
Can someone please just manually merge this?

**Pull request merged**
