### PR TITLE
Get rid of openshift_facts dep in rhel_subscribe

### PR DESCRIPTION
**Pull request by sdodson**
Because you can't install PyYAML before you subscribe

### CODE REVIEW

**Comment by sdodson** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Comment by ewolinetz** [comment]
flake? [merge]

**Comment by ewolinetz** [comment]
flaked on https://github.com/openshift/origin/issues/14043
[merge]

**Pull request merged**
