### PR TITLE
Fluentd: one output tag, one output plugin (origin-aggregated-logging)

### PR DESCRIPTION
**Pull request by nhosoi**
Adding <label @OUTPUT> to fluent.conf.

### CODE REVIEW

**Comment by ewolinetz** [comment]
Doesn't this need to be one single label since the fluentd's input config routes to the INGRESS label? Wouldn't we need to route to the output label somehow?

**Comment by nhosoi** [comment]
@ewolinetz, 
Not sure this answers your question..., this pr#5503 corresponds to the pr#577 [1] which is already merged.  

In the pr#577, it retags all the tags to one (or two depending upon the existence of the extra ops cluster) using the fluentd "match" directive.  Then we need a specific label (in this case `@OUTPUT`) to go forward to the output plugin.

[1] https://github.com/openshift/origin-aggregated-logging/pull/577

**Comment by nhosoi** [comment]
> ci/openshift-jenkins/containerized — Jenkins job failed. 
Not sure how this pr could cause this failure...
```
RUNNING HANDLER [openshift_master : restart master controllers] ****************
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "generated_timestamp": "2017-09-22 14:21:42.665799", 
    "msg": "Unable to restart service origin-master-controllers: Job for origin-master-controllers.service failed because the control process exited with error code. See \"systemctl status origin-master-controllers.service\" and \"journalctl -xe\" for details.\n"
}
META: ran handlers
 [WARNING]: Could not create retry file '/usr/share/ansible/openshift-
ansible/playbooks/byo/config.retry'.         [Errno 13] Permission denied:
u'/usr/share/ansible/openshift-ansible/playbooks/byo/config.retry'

PLAY RECAP *********************************************************************
localhost                  : ok=307  changed=99   unreachable=0    failed=1   
```

**Comment by nhosoi** [comment]
> ci/openshift-jenkins/logging — Jenkins job failed. 

It looks it hit an error caused by the fluentd installed twice?  I've rebased this pr with the master that contains pr#5511 merged.
```
        "ERROR:Serial number 04 has already been issued,", 
        "      check the database/serial_file for corruption", 

PLAY RECAP *********************************************************************
 [WARNING]: Could not create retry file '/usr/share/ansible/openshift-
ansible/playbooks/byo/openshift-cluster/openshift-logging.retry'.
[Errno 13] Permission denied: u'/usr/share/ansible/openshift-
ansible/playbooks/byo/openshift-cluster/openshift-logging.retry'
localhost                  : ok=115  changed=8    unreachable=0    failed=1   
```

**Comment by nhosoi** [comment]
[(8) Fluentd: one output tag, one output plugin[logging][epic-ois-agl-perf]](https://trello.com/c/aJMg6C6R/570-8-fluentd-one-output-tag-one-output-pluginloggingepic-ois-agl-perf)

**Pull request merged**
