### PR TITLE
Update BYO docs

### PR DESCRIPTION
**Pull request by johnjelinek**
Update command to configure router/registry.

### CODE REVIEW

**Comment by johnjelinek** [comment]
Fixes #301

**Comment by johnjelinek** [comment]
As an aside: both of these docs mention a known problem with ansible 1.9.0, but I was able to deploy with ansible 1.9.1 without problems. I think the docs should just recommend using 1.9.1+.

**Comment by johnjelinek** [comment]
Duplicate of #295

**Comment by sdodson** [comment]
If 'oadmin' is available in all situations, and I believe it is, I'd prefer #292 

What do you think?

**Comment by johnjelinek** [comment]
I prefer `oadm` too. You can close this if you want.

**Pull request closed without merging**
