### PR TITLE
adding parameters to allow for load balancer creation

### PR DESCRIPTION
**Pull request by cooktheryan**
For resolution of BZ 1613546

Running through lint and manually testing now....

### CODE REVIEW

**Comment by cooktheryan** [comment]
Inventory
openshift_cloudprovider_azure_availability_set=ocp-app-instances
openshift_cloudprovider_azure_security_group_name=node-nsg
openshift_cloudprovider_azure_cloud=AzurePublicCloud
openshift_cloudprovider_azure_vnet_name=openshiftvnet

cat /etc/origin/cloudprovider/azure.conf 
tenantId: tenant
subscriptionId: sub
aadClientId: id
aadClientSecret: secret
aadTenantId: tenant
resourceGroup: refarch-azr
location: eastus
primaryAvailabilitySetName: ocp-app-instances
securityGroupName: node-nsg
cloud: AzurePublicCloud
vnetName: openshiftvnet

**Comment by cooktheryan** [comment]
This should probably get scheduled to be part of the next 3.10 release. Do
you know how I could help make that happen?

Ryan

**Comment by michaelgugino** [comment]
@cooktheryan 

/cherry-pick release-3.10

The bot will attempt to pick.  If it fails, you'll need to pick manually and create a PR against 3.10

**Pull request merged**
