### PR TITLE
Fix default ansible service broker image prefix

### PR DESCRIPTION
**Pull request by sngchlko**
ansibleplaybookbundle/ansible-service-broker:latest does not exist.
Use 'ansibleplaybookbundle/origin-' instead of 'ansibleplaybookbundle/'

### CODE REVIEW

**Comment by vrutkovs** [comment]
That would break OSE installation (it uses `ose-` prefix). The image name looks correct to me, as default prefix `__ansible_service_broker_image_prefix` is set to `ansibleplaybookbundle/origin-`

**Comment by sngchlko** [comment]
You are right!
I fixed it.

**Comment by sngchlko** [comment]
@vrutkovs, @sdodson PTAL.

**Comment by vrutkovs** [comment]
Its weird that Github doesn't notify on PR, but this already fixed in https://github.com/openshift/openshift-ansible/pull/6511.

**Pull request closed without merging**
