### PR TITLE
Adding pv encryption and registry backed encryption for s3.

### PR DESCRIPTION
**Pull request by kwoodson**

### CODE REVIEW

**Comment by sdodson** [comment]
Is this a blocker?

**Comment by BigN** [comment]
Not a blocker but the number of dedicated enterprise customers asking for
this feature is quickly increasing. Would be great if we can have this in
3.6 (and not wait until 3.7) so when we upgrade we can enable encryption.

On Jun 26, 2017, at 8:41 PM, Scott Dodson <notifications@github.com> wrote:

Is this a blocker?

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/openshift-ansible/pull/4594#issuecomment-311220256>,
or mute the thread

**Comment by joelddiaz** [comment]
Just in case it isn't clear: doing an in-place upgrade will not enable encryption for the root/boot volumes.

**Comment by sdodson** [comment]
Since this is still WIP we'll hold this until after we fork 3.6 at code freeze.

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
The 3.6 images and repos are all fouled up.

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Pull request merged**
