### PR TITLE
Backport to release-1.5: oc modules.

### PR DESCRIPTION
**Pull request by kwoodson**

### CODE REVIEW

**Comment by kwoodson** [comment]
@sdodson, the last edit that went in was the multiple edits.  It also did a regenerate which by that time had the other modules in it.  I went and added pvc, image, user, group, volume, and configmap.

**Comment by sdodson** [comment]
Didn't realize that travis also did code coverage tests and it's failing.

**Comment by sdodson** [comment]
Also, I'm checking with Justin to see if he's ok with just using a build from master rather than rushing this backport.

**Comment by sdodson** [comment]
Closing this for now.

**Pull request closed without merging**
