### PR TITLE
Updating defaults for PVC names and surrounding with quotations in te…

### PR DESCRIPTION
**Pull request by ewolinetz**
…mplates

This is to address https://bugzilla.redhat.com/show_bug.cgi?id=1430627 and https://bugzilla.redhat.com/show_bug.cgi?id=1430626

### CODE REVIEW

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
@sdodson any qualms with these changes? I'll need to cherry pick this into master too

**Comment by sdodson** [comment]
@ewolinetz looks fine to me

**Comment by sdodson** [comment]
[merge]

**Comment by sdodson** [comment]
forgot the bot only listens on master right now

**Pull request merged**
