### PR TITLE
Compatibility updates to openshift_logging role for ansible 2.2.2.0+

### PR DESCRIPTION
**Pull request by etsauer**
Addresses #3810 

@sdodson @ewolinetz @oybed

### CODE REVIEW

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
Problems pulling corresponding v3.4.1.13 images from an internal registry, something is horked with the 3.4 build. Will reach out to release team to figure out what's up.

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
CI runs Ansible 2.2.1.0 so this seems backwards compat. @ewolinetz PTAL

**Comment by sdodson** [comment]
Actually, we need to test this manually because CI doesn't run logging installs :-(

**Comment by ewolinetz** [comment]
@sdodson oh right, good catch... i'll do a quick manual run locally

**Comment by ewolinetz** [comment]
Ansible 2.2.1.0 test completed for me with installing logging using this branch

@etsauer can you address the yamllint errors from Travis?

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Pull request merged**
