### PR TITLE
Ensured to always use a certificate for the router

### PR DESCRIPTION
**Pull request by aerialls**
This PR is for fixing #5160 to ensured a certificate is always used for the hosted router.

### CODE REVIEW

**Comment by abutcher** [comment]
aos-ci-test

**Comment by abutcher** [comment]
aos-ci-test

**Comment by abutcher** [comment]
The second CI failure is legitimate. I think this task will need to be moved before the previous since it sets a value for `openshift_hosted_router_certificate`.

**Comment by aerialls** [comment]
Indeed! I've reversed the two tasks.

**Comment by abutcher** [comment]
aos-ci-test

**Comment by aerialls** [comment]
Tests don't seem to be triggered 🤔

**Comment by aerialls** [comment]
The first failure does not seem to be related to my change.

**Comment by aerialls** [comment]
Any updates on this one?

Thanks!

**Comment by sdodson** [comment]
aos-ci-test

**Comment by abutcher** [comment]
aos-ci-test

**Comment by abutcher** [comment]
[merge]

**Comment by sdodson** [comment]
[merge]

**Pull request merged**
