### PR TITLE
use config_base instead of hardcoded /etc/openshift

### PR DESCRIPTION
**Pull request by ibotty**

### CODE REVIEW

**Comment by detiber** [comment]
Overall, I agree with this change, but there is no metadata provided by the openshift_cluster_metrics role that provides the dependency on the openshift_common role.  It may work currently because of the order the roles are currently specified and run within the playbooks, but it is not guaranteed to do so.

https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/meta/main.yml can be used as an example for the metadata needed.

**Comment by ibotty** [comment]
I added a commit adding a meta file. I took the name of the author from git. I assume they are ok with the same license as the rest of these playbooks.

**Comment by detiber** [comment]
@spinolacastro can you verify that you are good with the Apache v2 license for the openshift_cluster_metrics role metadata?

**Comment by arilivigni** [comment]
Can one of the admins verify this patch?
I understand the following comments:
- `bot, add author to whitelist`
- `bot, test pull request`
- `bot, test pull request once`

**Comment by spinolacastro** [comment]
@detiber Yes, i am!

**Comment by detiber** [comment]
@spinolacastro that would be outstanding.

@ibotty Do you want to hold off getting this merged in favor of @spinolacastro refactoring for the containerized metrics?

**Comment by ibotty** [comment]
I don't really care, honestly. I was trying to split my mega-diff into manageable chunks to get all differences I have merged.

Regarding the refactoring to use origin-metrics. AFAICT it uses cassandra, hawkular, etc. I have an unfinished patch to use riemann and influxdb. I think the metrics stack should be pluggable. If @spinolacastro refactors this role to be extensible, I am all for it.

**Comment by detiber** [comment]
@sdodson I think this is probably not needed now with the work you are doing for metrics currently. Please close if that is the case.

**Comment by tbielawa** [comment]
This PR has been inactive for quite some time. Please update, fix any conflicts, and reopen this PR if this is still a priority you would like to see action on.

**Pull request closed without merging**
