### PR TITLE
nfs: replace yum with dnf

### PR DESCRIPTION
**Pull request by enoodle**
this is similar to https://github.com/openshift/openshift-ansible/pull/1280

### CODE REVIEW

**Comment by enoodle** [comment]
@abutcher I saw you commented on a similar patch, could you take a look? thanks.

**Comment by abutcher** [comment]
ok to test

**Comment by abutcher** [comment]
aos-ci-test

**Comment by abutcher** [comment]
@brenton

**Comment by abutcher** [comment]
@enoodle Thanks 8)

**Pull request merged**
