### PR TITLE
Add missing quotes for variables

### PR DESCRIPTION
**Pull request by IshentRas**
It causing failure when running playbooks due to missing quotes for variable interpolation

### CODE REVIEW

**Comment by IshentRas** [comment]
@sdodson @mtnbikenc I have found another issue with this play. Shall I send an update to the PR or would you prefer another PR?

**Comment by sdodson** [comment]
Go ahead and update this PR, thanks!

**Comment by IshentRas** [comment]
I have XXXed... somehow. Will reopen another one shortly.. Need to check my upstream...

**Pull request closed without merging**
