### PR TITLE
Remove jinja template delimeters and quotes from when conditions

### PR DESCRIPTION
**Pull request by sdodson**
In ansible 2.3 "[WARNING]: when statements should not include jinja2
templating delimiters such as {{ }} or {% %}. Found: {{
g_glusterfs_hosts is not defined }}"

### CODE REVIEW

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
When starting conditionals with single quotes, the double quotes are still required.  See errors in Travis.

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[test]

**Comment by sdodson** [comment]
[merge]

**Comment by sdodson** [comment]
Rebased.

**Comment by sdodson** [comment]
aos-ci-test

**Comment by abutcher** [comment]
flake https://github.com/openshift/origin/issues/13980

**Comment by abutcher** [comment]
[merge]

**Pull request merged**
