### PR TITLE
Remove hidden tag for latest Fuse builders #11292

### PR DESCRIPTION
**Pull request by apupier**
it will allow to use them with odo

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

NOTICE
======

Master branch is closed! A major refactor is ongoing in devel-40.
Changes for 3.x should be made directly to the latest release branch they're
relevant to and backported from there.

### CODE REVIEW

**Comment by apupier** [comment]
@patrickdillon is it possible for you to review this PR too, please? it is the same than the one you reviewed on 3.10 branch.

**Comment by patrickdillon** [comment]
@apupier Sure!

If you do this sort of change often, you can create your PR against the latest branch (in this case release-3.11) and then `/cherrypick release-3.10` and so on for earlier branches.

**Comment by apupier** [comment]
> If you do this sort of change often, you can create your PR against the latest branch (in this case release-3.11) and then `/cherrypick release-3.10` and so on for earlier branches.

thanks for the info!

**Pull request merged**
