### PR TITLE
Adding file rollover size and max count policies

### PR DESCRIPTION
**Pull request by ewolinetz**
To address https://bugzilla.redhat.com/show_bug.cgi?id=1616169

### CODE REVIEW

**Comment by ewolinetz** [comment]
I want to verify that log4j2 allows us to set both size and time policies, my cluster had trouble installing locally. Will verify with CI
/hold

**Comment by ewolinetz** [comment]
I don't see any errors in the ES logs stating that this was a bad log4j configuration

@jcantrill PTAL

/hold cancel

**Comment by jcantrill** [comment]
/lgtm

Manually updated my config:

```
    appender.rolling.policies.size.type=SizeBasedTriggeringPolicy
    appender.rolling.policies.size.size=2MB
    appender.rolling.strategy.type=DefaultRolloverStrategy
    appender.rolling.strategy.max=5

```
produced:
```
sh-4.2$ ls -l
total 120
-rw-r--r-- 1 1000130000 root   111 Aug 17 23:59 logging-es-2018-08-14.log
-rw-r--r-- 1 1000130000 root 18632 Aug 17 23:59 logging-es-2018-08-17.log
-rw-r--r-- 1 1000130000 root  3147 Aug 18 00:04 logging-es.log
-rw-r--r-- 1 1000130000 root 91823 Aug 18 00:00 logging-es_deprecation.log
-rw-r--r-- 1 1000130000 root     0 Aug 14 18:43 logging-es_index_indexing_slowlog.log
-rw-r--r-- 1 1000130000 root     0 Aug 14 18:43 logging-es_index_search_slowlog.log
```
Note the date diffs are related to my clock skew

**Pull request merged**
