### PR TITLE
specify all logging index mappings for kibana

### PR DESCRIPTION
**Pull request by jcantrill**

### CODE REVIEW

**Comment by ewolinetz** [comment]
[test]

**Comment by jcantrill** [comment]
[aos-ci-test]

**Comment by jcantrill** [comment]
[test]

**Comment by jcantrill** [comment]
[aos-ci-tests]

**Comment by jcantrill** [comment]
@stevekuznetsov  @sdodson I was looking at another PR and it seems it failed for a similar reason.  Missing 'aos-ci-tests' ?

**Comment by sdodson** [comment]
Yes, aos-ci-test needs to be run and green before [ test ] or [ merge ] complete.

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Pull request merged**
