### PR TITLE
Deploy azure clusters using az group deployment create

### PR DESCRIPTION
**Pull request by kargakis**
/assign kwoodson 
/sig azure

### CODE REVIEW

**Comment by kargakis** [comment]
@kwoodson fwiw even upstream e2e tests don't use `acs-engine deploy`. See [here](https://github.com/Azure/acs-engine/blob/659a9d8f8661fdd30eda19ebc0f7ba7115caf3de/test/e2e/runner/cli_provisioner.go#L159) and [here](https://github.com/Azure/acs-engine/blob/659a9d8f8661fdd30eda19ebc0f7ba7115caf3de/test/e2e/azure/cli.go#L208).

**Comment by kargakis** [comment]
@kwoodson we still need acs-engine to generate the arm template that is deployed by az.

**Comment by jim-minter** [comment]
@kargakis would you be happy with https://github.com/openshift/openshift-ansible/pull/8669 instead?

One possible advantage of sticking with `acs-engine deploy` is it will also test things around creation of the application object.

**Comment by kargakis** [comment]
works for me

/close

**Pull request closed without merging**
