### PR TITLE
Remove provisioner restrictions on oc_storageclass

### LINKED ISSUE #5835: Unable to create custom default storageclass
##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM or
`atomic-openshift-utils`

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

Place the output between the code block below:

```
$ ansible --version
ansible 2.4.0.0

$ git describe
openshift-ansible-3.6.173.0.58-1
```

##### Steps To Reproduce
1. Set openshift_storageclass_provisioner to efs
2. Run the playbook

##### Expected Results
Describe what you expected to happen.

```
Created EFS Storage Class
```

##### Observed Results
Describe what is actually happening.

```
TASK [openshift_default_storage_class : Ensure storageclass object] ****************************************************************************************************************************************
Sunday 22 October 2017  00:58:20 +0200 (0:00:00.118)       0:45:38.475 ********
fatal: [openshift-master1]: FAILED! => {
    "changed": false,
    "failed": true
}

MSG:

value of provisioner must be one of: aws-ebs,gce-pd,glusterfs,cinder, got: penshift.org/aws-efs
.......

Failure summary:


  1. Hosts:    openshift-master1
     Play:     Create Hosted Resources
     Task:     Ensure storageclass object
     Message:  value of provisioner must be one of: aws-ebs,gce-pd,glusterfs,cinder, got: penshift.org/aws-efs
```
Related Code:

https://github.com/openshift/openshift-ansible/blob/a148a0f2768e37f212a12c21e6dda4c02b80143c/roles/lib_openshift/library/oc_storageclass.py#L1667

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
CentOS7.4


openshift_storageclass_name="efs"
openshift_storageclass_provisioner="aws-efs"
```

### PR DESCRIPTION
**Pull request by jkroepke**
Fixes #5835

Make possible to use EFS as default provisioner on AWS instead EBS like

```
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: slow
provisioner: example.com/aws-efs
parameters:
  gidMin: "40000"
  gidMax: "50000"
  gidAllocate: "true"
```

### CODE REVIEW

**Comment by kwoodson** [comment]
@jkroepke,

Thanks for submitting this PR.  The modules for lib_openshift are generated.  After making the change that you provided under `src/` please run the following script https://github.com/openshift/openshift-ansible/blob/master/roles/lib_openshift/src/generate.py so that it can generate what comes in the https://github.com/openshift/openshift-ansible/tree/master/roles/lib_openshift/library directory.  Then please add the latest library/oc_storageclass.py to your PR.

Please let me know if you have any questions.

Thanks.

**Comment by jkroepke** [comment]
@kwoodson Sure.

**Comment by kwoodson** [comment]
@jkroepke, with these latest changes does this fix your issue? https://github.com/openshift/openshift-ansible/issues/5835

**Comment by kwoodson** [comment]
bot, test pull request

**Comment by kwoodson** [comment]
@jkroepke, did this end up resolving your issue?

**Comment by pearj** [comment]
Can we get this cherry-picked onto the release-3.6 branch?

**Comment by kwoodson** [comment]
Backport PR here: https://github.com/openshift/openshift-ansible/pull/7232

**Pull request merged**
