### PR TITLE
Update s2i-dotnetcore content

### PR DESCRIPTION
**Pull request by sdodson**

### CODE REVIEW

**Comment by sdodson** [comment]
@jerboaa PTAL this updates your content in master, i'll cherry-pick into release-1.5 once this merges, also do you want this in release-1.4 too?

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Comment by jerboaa** [comment]
@sdodson I'm waiting for confirmation on 3.4 test results.

**Pull request merged**
