### PR TITLE
[RHPAM-1568]/[RHDM-748]

### PR DESCRIPTION
**Pull request by spolti**
Update RHDM/RHPAM application-templates on OCP and OSO for release 7.1

Signed-off-by: Filippe Spolti <fspolti@redhat.com>

### CODE REVIEW

**Comment by spolti** [comment]
Are the issues related with the PR?

**Comment by spolti** [comment]
Hi all, can it be merged?

**Comment by spolti** [comment]
Hi @vrutkovs , apparently the error is not related with the PR, can it be merged?

**Comment by vrutkovs** [comment]
That didn't work :(

Could you open a new PR with this commit targeting `release-3.11` instead?

Closing this as CI won't let it pass currently

**Comment by spolti** [comment]
No worries, I was preparing a new PR for the updated templates anyway :)

@vrutkovs Just to confirm, for openshift 4.0 should I also update openshift-ansible or just update the openshift/library and tag the templates with ocp is enough?

**Comment by vrutkovs** [comment]
@spolti in 4.0 you'd need to update samples operator AFAIK, no changes would be required in openshift-ansible

**Comment by spolti** [comment]
@vrutkovs right, looks like the samples operator fetches the library repository, basically I only needs to update the templates there, right?

**Comment by vrutkovs** [comment]
I think so, but I'm not familiar with the new process, sorry

**Comment by spolti** [comment]
No problem, thanks.

**Pull request closed without merging**
