### PR TITLE
docker: copy Docker metadata to the alternative storage path

### PR DESCRIPTION
**Pull request by giuseppe**
Copy the Docker metadata to the alternative storage path.

Addresses:

https://github.com/openshift/openshift-ansible/pull/6007#issuecomment-345661409

### CODE REVIEW

**Comment by runcom** [comment]
we should have a `/test crio` in openshift-ansible @stevekuznetsov @mrunalp

**Comment by ashcrow** [comment]
Errors are unrelated to this change:

```
[Feature:Prometheus][Conformance] Prometheus when installed to the cluster should start and expose a secured proxy and unsecured metrics [Suite:openshift/conformance/parallel]
```

```
"msg": "Some required package(s) are available at a version\nthat is higher than requested\n  origin-3.8.0\n  origin-node-3.8.0\n  origin-master-3.8.0\nThis will prevent installing the version you requested.\nPlease check your enabled repositories or adjust openshift_release."
```

**Comment by giuseppe** [comment]
@michaelgugino are you fine with the patch as it is or you still need some changes to be done?  The issue is that we currently throw away `/var/lib/docker` and create the storage somewhere else, but this is not enough with devicemapper as it only destroys the metadata but the LVM devices are still there (we'd need something like `atomic storage reset` in this case).  But since what we do is to migrate to another path, I think it is better to move what we already have locally instead of nuking everything.

**Comment by michaelgugino** [comment]
@giuseppe I forgot that switching the review to 'comment' does not clear the 'changes requested' on GitHub.  These look fine.

**Comment by ashcrow** [comment]
/retest

Both failures were unrelated to the change.

**Comment by runcom** [comment]
can someone help to get this merged? :angel: the CRI-O CI is broken since a week and we need this in :innocent:

**Comment by ashcrow** [comment]
Failures are not related to this change.

1. logging failure
2. It's finding a different version of the tag from the registry than it expects.

/cc @sdodson

**Pull request merged**
