### PR TITLE
Fixing typo in openshift_metrics_cassandra_pvc_storage_class_name variable

### PR DESCRIPTION
**Pull request by faust64**
mis-named variable

### CODE REVIEW

**Comment by DanyC97** [comment]
can you please amend the PR title and the commit message to be more meaningful ?

**Comment by michaelgugino** [comment]
/ok-to-test

@ewolinetz

**Comment by ewolinetz** [comment]
cc @jsanda 
/lgtm

**Comment by ewolinetz** [comment]
thanks @faust64

**Pull request merged**
