### PR TITLE
Fix flake8 errors in utils/test

### PR DESCRIPTION
**Pull request by vrutkovs**

### CODE REVIEW

**Comment by michaelgugino** [comment]
@vrutkovs Thank you for the pull request.

@sdodson Is this part of the code we wish to remove?

**Comment by sdodson** [comment]
Yeah but it'll stick around until at least 3.9.

**Comment by vrutkovs** [comment]
Seems to be https://github.com/openshift/origin/issues/14393

/retest

**Comment by vrutkovs** [comment]
Test flakes - https://github.com/openshift/origin/issues/12629, https://github.com/openshift/origin/issues/16672
/retest

**Pull request merged**
