### PR TITLE
Changed template to add miq-log config map

### PR DESCRIPTION
**Pull request by rh-dluong**
Addresses RFE: https://bugzilla.redhat.com/show_bug.cgi?id=1612814

### CODE REVIEW

**Comment by michaelgugino** [comment]
@sdodson ptal

**Comment by sdodson** [comment]
@rh-dluong There's also a role openshift_management that's got these templates too. Can you check that role for required changes, that's the role that's used for automated installs of the management stack.

**Comment by simaishi** [comment]
@rh-dluong The process we've been using is to make changes on ManageIQ templates first, cherry-pick to CFME templates, which gets tested by QE, then update templates in this repo after CFME is released. So making changes here directly will make ManageIQ/CFME templates out of sync with what CFME team maintains and QE uses for their testing.

Are you able to make PR against manageiq-pods instead?

cc @carbonin

**Comment by carbonin** [comment]
+1 for @simaishi 's comment

@rh-dluong can you make this PR on the [manageiq-pods](https://github.com/ManageIQ/manageiq-pods) repo first, then we'll make a PR here when we cut a release?

Thanks

**Comment by rh-dluong** [comment]
@carbonin , will do.  Just 1 follow up question, looks like there's a fairly large re-arch in the master template.  Should I just open a PR for the hammer and g branches?

**Comment by carbonin** [comment]
Yeah, since this isn't something that applies to the master branch just hammer is good. Then we'll decide if it should go back to G and @simaishi will handle backporting in that repo.

**Comment by carbonin** [comment]
This one can be closed, thanks @rh-dluong

**Pull request closed without merging**
