### PR TITLE
Clean up lib_utils role (Part 2)

### PR DESCRIPTION
**Pull request by mtnbikenc**
Removes docker_creds module
  Removes tasks files in container_runtime, common/post.yml and registry_auth.yml

Removes all remaining filters in oo_filters
  Removes filter usage in openshift_facts/defaults/main.yml
  Removes filter usage in openshift_node40/tasks/install.yml

Removes unused lib_utils/test/test_data files

### CODE REVIEW

**Comment by mtnbikenc** [comment]
350
```
Failing tests:

[Area:Networking] multicast when using one of the plugins 'redhat/openshift-ovs-multitenant, redhat/openshift-ovs-networkpolicy' should block multicast traffic in namespaces where it is disabled [Suite:openshift/conformance/parallel]
[Conformance][templates] templateinstance cross-namespace test should create and delete objects across namespaces [Suite:openshift/conformance/parallel/minimal]
[Feature:DeploymentConfig] deploymentconfigs rolled back [Conformance] should rollback to an older deployment [Suite:openshift/conformance/parallel/minimal]
[Feature:DeploymentConfig] deploymentconfigs viewing rollout history [Conformance] should print the rollout history [Suite:openshift/conformance/parallel/minimal]
[Feature:DeploymentConfig] deploymentconfigs won't deploy RC with unresolved images [Conformance] when patched with empty image [Suite:openshift/conformance/parallel/minimal]
[Feature:Prometheus][Conformance] Prometheus when installed on the cluster should report telemetry if a cloud.openshift.com token is present [Suite:openshift/conformance/parallel/minimal]
[k8s.io] EquivalenceCache [Serial] validates pod affinity works properly when new replica pod is scheduled [Suite:openshift/conformance/serial] [Suite:k8s]
[k8s.io] EquivalenceCache [Serial] validates pod anti-affinity works properly when new replica pod is scheduled [Suite:openshift/conformance/serial] [Suite:k8s]
[sig-api-machinery] CustomResourceDefinition Watch CustomResourceDefinition Watch watch on custom resource definition objects [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-api-machinery] Namespaces [Serial] should ensure that all pods are removed when a namespace is deleted [Conformance] [Suite:openshift/conformance/serial/minimal] [Suite:k8s]
[sig-apps] ReplicaSet should serve a basic image on each replica with a public image  [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s]
[sig-network] Networking should check kube-proxy urls [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-scheduling] PodPriorityResolution [Serial] validates critical system priorities are created and resolved [Suite:openshift/conformance/serial] [Suite:k8s]
[sig-scheduling] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run  [Conformance] [Suite:openshift/conformance/serial/minimal] [Suite:k8s]
[sig-scheduling] SchedulerPredicates [Serial] validates that NodeAffinity is respected if not matching [Suite:openshift/conformance/serial] [Suite:k8s]
[sig-scheduling] SchedulerPredicates [Serial] validates that NodeSelector is respected if matching  [Conformance] [Suite:openshift/conformance/serial/minimal] [Suite:k8s]
[sig-scheduling] SchedulerPredicates [Serial] validates that NodeSelector is respected if not matching  [Conformance] [Suite:openshift/conformance/serial/minimal] [Suite:k8s]
[sig-scheduling] SchedulerPredicates [Serial] validates that required NodeAffinity setting is respected if matching [Suite:openshift/conformance/serial] [Suite:k8s]
[sig-scheduling] SchedulerPredicates [Serial] validates that taints-tolerations is respected if matching [Suite:openshift/conformance/serial] [Suite:k8s]
[sig-scheduling] SchedulerPredicates [Serial] validates that taints-tolerations is respected if not matching [Suite:openshift/conformance/serial] [Suite:k8s]
[sig-scheduling] SchedulerPreemption [Serial] validates basic preemption works [Suite:openshift/conformance/serial] [Suite:k8s]
[sig-scheduling] SchedulerPreemption [Serial] validates lower priority pod preemption by critical pod [Suite:openshift/conformance/serial] [Suite:k8s]
[sig-scheduling] SchedulerPreemption [Serial] validates pod anti-affinity works in preemption [Suite:openshift/conformance/serial] [Suite:k8s]
[sig-storage] Dynamic Provisioning Invalid AWS KMS key should report an error and create no PV [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-storage] In-tree Volumes [Driver: cinder] [Testpattern: Pre-provisioned PV (default fs)] volumes should be mountable [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-storage] PVC Protection Verify that scheduling of a pod that uses PVC that is being deleted fails and the pod becomes Unschedulable [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-storage] Secrets should be consumable from pods in volume with mappings [NodeConformance] [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s]
```

**Comment by mtnbikenc** [comment]
Needs #11261 to resolve package install ssh issues through bastion.

**Comment by vrutkovs** [comment]
/hold

devel-40 CI is broken

**Comment by mtnbikenc** [comment]
Needs ssh retry fixes in https://github.com/openshift/openshift-ansible/pull/11261. Hold until that PR merges.
/hold

**Comment by mtnbikenc** [comment]
#11261 is merged
/hold cancel

**Comment by mtnbikenc** [comment]
Rebased for merge conflicts.

**Comment by mtnbikenc** [comment]
Job 517:
```
Failing tests:

[Area:Networking] NetworkPolicy when using a plugin that implements NetworkPolicy should support allow-all policy [Feature:OSNetworkPolicy] [Suite:openshift/conformance/parallel]
[k8s.io] Docker Containers should use the image defaults if command and args are blank [NodeConformance] [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s]
[sig-storage] EmptyDir volumes when FSGroup is specified [NodeFeature:FSGroup] volume on default medium should have the correct mode using FSGroup [Suite:openshift/conformance/parallel] [Suite:k8s]
```

**Comment by mtnbikenc** [comment]
Job 515:
```
Failed waiting for ssh bastion to roll out
E0305 07:00:37.186246     435 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=5, ErrCode=NO_ERROR, debug=""
    error: watch closed before Until timeout
```

Job 514:
```
Failed installing packages on scaled nodes
    Error downloading packages:
      origin-clients-4.0.0-0.alpha.0.1469.761b685.x86_64: [Errno 256] No more mirrors to try.
      origin-node-4.0.0-0.alpha.0.1469.761b685.x86_64: [Errno 256] No more mirrors to try.
      origin-hyperkube-4.0.0-0.alpha.0.1469.761b685.x86_64: [Errno 256] No more mirrors to try.
```

Job 513:
```
Failing tests:

[sig-api-machinery] Namespaces [Serial] should ensure that all pods are removed when a namespace is deleted [Conformance] [Suite:openshift/conformance/serial/minimal] [Suite:k8s]
[sig-network] Services should be able to switch session affinity for service with type clusterIP [Suite:openshift/conformance/parallel] [Suite:k8s]
```

**Pull request merged**
