### PR TITLE
Dump verbose curl output and API logs when API doesn't become available.

### PR DESCRIPTION
**Pull request by abutcher**
Doing this for CI but would also be helpful as we receive a lot of issues on this task.

Ex: https://gist.github.com/abutcher/8f6edcd159741ca06188cd99cf8468d0

Also starting the API in parallel while I'm here.

### CODE REVIEW

**Comment by sdodson** [comment]
Can't wait to see this fail!

**Comment by stevekuznetsov** [comment]
changes here are
/lgtm

**Pull request merged**
