### PR TITLE
[3.3 backport] set default openshift_release and docker_version if not set

### PR DESCRIPTION
**Pull request by ingvagabund**
Fixes: #4523

### CODE REVIEW

**Comment by ingvagabund** [comment]
aos-ci-test

**Comment by ingvagabund** [comment]
@stevekuznetsov not completely sure where the [1] playbook comes from but it is installing docker-1.12 even before the OpenShift Ansible deployment for 3.3 is run. It should install docker-1.10 if anything. Is there any way to fix it? I.e. force docker version to 1.10.*?

[1] /home/jenkins/workspace/openshift-ansible-test-matrix/CONTAINERIZED/_NOT_containerized/OSE_VER/3.3/PYTHON/System-CPython-2.7/TOPOLOGY/openshift-cluster/TargetBranch/release-1.3/nodes/openshift-ansible-slave/atomic-ci-jobs/project/playbooks/openshift/setup.yml

**Comment by stevekuznetsov** [comment]
Not without some custom work. We don't currently support testing for 3.3 on that CI job. @sdodson has been giving out green button pushes I think.

**Comment by ingvagabund** [comment]
If this PR gets pushed without modifying the CI, every PR will be failing. Anyway, it is not right to test 3.3 with docker-1.12*.

**Comment by stevekuznetsov** [comment]
> If this PR gets pushed without modifying the CI, every PR will be failing.

I don't understand -- is HEAD broken after this PR?

> Anyway, it is not right to test 3.3 with docker-1.12*.

Yes, known issue. It is hard to work on things like this as frequency of backports is very small and the work is large -- if you want to work on this to get CI working, we _do_ have a way to install custom Docker version (and we are doing something similar for `ose`) but you'll need to set all that up for these branches of `openshift-ansible.`

**Comment by sdodson** [comment]
We're revisit this after we make it through 3.6 codefreeze. This can wait.

**Comment by sdodson** [comment]
1.3 is no longer being maintained.

**Pull request closed without merging**
