### PR TITLE
Add missing v3.9 gluster templates

### PR DESCRIPTION
**Pull request by sdodson**
Fixes Bug 1532961

### CODE REVIEW

**Comment by jarrpa** [comment]
This seems to only cover files in the `files` subdirectory, what about `templates`?

**Comment by sdodson** [comment]
> This seems to only cover files in the files subdirectory, what about templates?

those seem to already be there, we likely only half fixed a bug in the past :-(

**Comment by sdodson** [comment]
If these files are stable across releases we should get rid of the version specificity and just use the same template for all versions.

**Pull request merged**
