### PR TITLE
Fix issue when there are no infra nodes

### PR DESCRIPTION
**Pull request by lhuard1A**
This issue was already addressed by #1355 fc2f776 but it has been accidentally reverted by 6d3e176.

### CODE REVIEW

**Comment by abutcher** [comment]
aos-ci-test

**Comment by lhuard1A** [comment]
It looks like the tests failed because `subscription-manager` times-out:

OS_3.0:
```
TASK: [common | Disable all repositories] ************************************* 
changed: [10.8.168.230]
changed: [10.8.168.231]
failed: [10.8.168.233] => {"changed": true, "cmd": "subscription-manager repos --disable=\"*\"", "delta": "0:01:05.533857", "end": "2016-03-08 11:07:46.206957", "rc": 70, "start": "2016-03-08 11:06:40.673100", "warnings": []}
stderr: Unable to verify server's identity: timed out
```

OS_3.1:
```
TASK: [common | Register with subscription Manager on stage] ****************** 
changed: [10.8.168.229]
changed: [10.8.168.232]
failed: [10.8.168.234] => {"attempts": 3, "changed": true, "cmd": ["subscription-manager", "register", "--auto-attach", "--force", "--serverurl=subscription.rhn.stage.redhat.com:443/subscription", "--baseurl=cdn.redhat.com", "--username=qa@redhat.com", "--password=redhatqa"], "delta": "0:01:06.580025", "end": "2016-03-08 11:12:02.274664", "failed": true, "rc": 1, "start": "2016-03-08 11:10:55.694639", "warnings": []}
stdout: The system with UUID 82582ce0-d1e3-4a82-9682-a49824bbaa89 has been unregistered
The system has been registered with ID: cfedf598-9b92-4638-8774-0a749aa4f2ce 
```

**Comment by abutcher** [comment]
@lhuard1A Seems we have an intermittent issue on one of the CI boxes @arilivigni and I are taking a look at this now.

**Comment by abutcher** [comment]
@lhuard1A sorry about that

@brenton good to go

**Pull request merged**
