### PR TITLE
vsphere storage default add - redo on PR squashing commits

### PR DESCRIPTION
**Pull request by dav1x**
vsphere storage default add - redo on PR squashing commits

### CODE REVIEW

**Comment by dav1x** [comment]
@sdodson PTAL!

**Comment by sdodson** [comment]
bot, test pull request
/ok-to-test

**Comment by cooktheryan** [comment]
@sdodson it looks like it hit a few flakes in the testing. For example the gcp check failed with

pkg_resources.DistributionNotFound: pycrypto>=2.6


Anything we could do to help remediate this as the storageclass for vmw would be nice to have for 3.9 and for the service broker install

**Comment by sdodson** [comment]
install should be the only one blocking this. gcp is not blocking

**Comment by cooktheryan** [comment]
@dav1x can you keep an eye on this

**Pull request merged**
