### PR TITLE
Add README_origin.md, update README.md to link to origin and OSE readmes

### PR DESCRIPTION
**Pull request by detiber**

### CODE REVIEW

**Comment by detiber** [comment]
@twiest @wshearn: Trying to cleanup docs a bit, added origin readme for using the byo playbooks, added references to the main README to README_origin and README_OSE

**Comment by twiest** [comment]
:+1:

**Comment by detiber** [comment]
@twiest could you merge this when you get a chance?

**Comment by detiber** [comment]
@twiest minor update for fixes to configuring the registry and the router for origin as well as associated fixes for configuring the registry and router for enterprise as well.

**Comment by twiest** [comment]
:+1:

**Pull request merged**
