### PR TITLE
Upgraded Calico to 2.2.1 Release

### PR DESCRIPTION
**Pull request by VincentS**
Upgraded Calico Role to 2.2.1 release from 2.1.x. 

CC: @ozdanborne

### CODE REVIEW

**Comment by sdodson** [comment]
@VincentS you'd mentioned on IRC that you only intended for this change to apply to the latest release if I recall. For my own curiosity, which versions of kube/openshift is Calico 2.2.1 compatible with?

**Comment by sdodson** [comment]
bot, test pull request

**Comment by sdodson** [comment]
aos-ci-test

**Comment by VincentS** [comment]
I talked to @ozdanborne and the PR needs some additional testing before it can be merged.

**Comment by VincentS** [comment]
@sdodson This should be compatible with OpenShift 3.4 and 3.5. We talked at IRC about how Calico gets installed. There are two approaches hosted install and custom install  see http://docs.projectcalico.org/v2.3/getting-started/kubernetes/installation/. This PR is still the Calico custom install approach.

**Comment by VincentS** [comment]
We have tested this PR internally and it worked.

**Comment by sdodson** [comment]
Needs a rebase unfortunately.

**Comment by VincentS** [comment]
#https://github.com/openshift/openshift-ansible/pull/4295 Needs to be merged first for this PR

I rebased it as requested. @sdodson @ingvagabund Can I get a review for this?

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Comment by sdodson** [comment]
resolved conflicts, back into the test queue

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Pull request merged**
