### PR TITLE
Use heketi Service URL in StorageClass templates #9740

### PR DESCRIPTION
**Pull request by jarrpa**
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1599554

### CODE REVIEW

**Comment by DanyC97** [comment]
bravo @jarrpa , thanks for looking into this ! ;)

**Comment by sdodson** [comment]
gcp job should now be fixed, no idea about the logging job

**Comment by michaelgugino** [comment]
gcp job failed to execute.

/test gcp

**Pull request merged**
