### PR TITLE
Check consumed pools prior to attaching.

### LINKED ISSUE #1670: Unable to run rhel_subscribe playbook multiple times
It fails because once you run it the first time, the pool becomes part of the consumed pools for the system, so subsequent runs of `Retrieve the OpenShift Pool ID` fail because the pool doesn't show up in `subscription-manager list --available --matches="{{ rhel_subscription_pool }}" --pool-only`

### PR DESCRIPTION
**Pull request by abutcher**
Also fail when we don't get a match in either available or consumed.

Resolves #1670

### CODE REVIEW

**Comment by ncdc** [comment]
Appears to work, although I think it ended up reattaching me to the pool instead of skipping over it

**Comment by abutcher** [comment]
If more than 1 pool matches `rhel_subscription_pool` the role will keep tacking them on.

**Comment by sdodson** [comment]
The error this is fixing matches this?
```
TASK: [rhel_subscribe | Attach to OpenShift Pool] *****************************                  
fatal: [ose3-master.example.com] => One or more undefined variables: list object has no element 0
fatal: [ose3-node2.example.com] => One or more undefined variables: list object has no element 0 
fatal: [ose3-node1.example.com] => One or more undefined variables: list object has no element 0 
```

**Comment by abutcher** [comment]
@sdodson Yeah, this should fix that.

**Comment by detiber** [comment]
@abutcher any issues with this merging?

**Comment by abutcher** [comment]
@detiber Nope. The role needs more work wrt attaching the right pool when multiple match but this is okay.

**Pull request merged**
