### PR TITLE
[release-3.6] Backport #6215

### PR DESCRIPTION
**Pull request by vrutkovs**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1545907

### CODE REVIEW

**Comment by sdodson** [comment]
/assign fabianvf 
I think there are other commits we need to backport

**Comment by sdodson** [comment]
https://github.com/openshift/openshift-ansible/pull/7137 is the backport to 3.7, lets check that we get everything from that that's relevant

**Comment by vrutkovs** [comment]
flakes

/retest

**Pull request merged**
