### PR TITLE
ci/papr: Update to FAH26

### PR DESCRIPTION
**Pull request by cgwalters**
See https://lists.projectatomic.io/projectatomic-archives/atomic-devel/2017-July/msg00018.html

Two other changes besides just `s/25/26/`:

- While I was here I did `s/dnf/yum/` since the version in F26 is less
  irritating about that, and it reduces friction in projects like this that need
  to span RHEL and Fedora.
- Also we now use `registry.fedoraproject.org/fedora` instead of relying on the Docker Hub.

### CODE REVIEW

**Comment by jlebon** [comment]
Hmm, can you try bumping `OPENSHIFT_IMAGE_TAG` to `v3.6.0-rc.0` as well? IIUC, this might have been fixed in a later version. (https://github.com/elazarl/goproxy/issues/188, https://github.com/elazarl/goproxy/commit/c4fc26588b6ef8af07a191fcb6476387bdd46711, https://github.com/openshift/origin/pull/14754).

**Comment by jlebon** [comment]
> Error from server (NotFound): templates.template.openshift.io "cakephp-example" not found

@sdodson Have you seen this before?

**Comment by sdodson** [comment]
I think those errors aren't fatal. I think this is the one that's creating problems and I've seen it before but I don't understand why it's happening.

```

TASK [openshift_master : check whether our docker-registry setting exists in the env file] ***
task path: /var/tmp/checkout/roles/openshift_master/tasks/main.yml:134
Using module file /usr/lib/python2.7/site-packages/ansible/modules/commands/command.py
<ocp-master> ESTABLISH SSH CONNECTION FOR USER: root
<ocp-master> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/%h-%r ocp-master '/bin/sh -c '"'"'/usr/bin/python3 && sleep 0'"'"''
<ocp-master> (0, '\n{"cmd": ["awk", "/^OPENSHIFT_DEFAULT_REGISTRY=docker-registry.default.svc:5000/", "/etc/sysconfig/origin-master"], "stdout": "", "stderr": "awk: fatal: cannot open file `/etc/sysconfig/origin-master\' for reading (No such file or directory)", "rc": 2, "start": "2017-07-25 14:36:23.973227", "end": "2017-07-25 14:36:23.975861", "delta": "0:00:00.002634", "changed": true, "warnings": [], "invocation": {"module_args": {"_raw_params": "awk \'/^OPENSHIFT_DEFAULT_REGISTRY=docker-registry.default.svc:5000/\' /etc/sysconfig/origin-master", "_uses_shell": false, "warn": true, "chdir": null, "executable": null, "creates": null, "removes": null}}}\n', '')
fatal: [ocp-master]: FAILED! => {
    "changed": false, 
    "cmd": [
        "awk", 
        "/^OPENSHIFT_DEFAULT_REGISTRY=docker-registry.default.svc:5000/", 
        "/etc/sysconfig/origin-master"
    ], 
    "delta": "0:00:00.002634", 
    "end": "2017-07-25 14:36:23.975861", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "_raw_params": "awk '/^OPENSHIFT_DEFAULT_REGISTRY=docker-registry.default.svc:5000/' /etc/sysconfig/origin-master", 
            "_uses_shell": false, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "warn": true
        }
    }, 
    "rc": 2, 
    "start": "2017-07-25 14:36:23.973227"
}``

**Comment by sdodson** [comment]
https://github.com/openshift/openshift-ansible/pull/4918 may fix this

**Comment by jlebon** [comment]
bot, retest this please

**Comment by sdodson** [comment]
bot, retest this please

**Comment by sdodson** [comment]
@jlebon `[Errno 12] Cannot allocate memory` ?

**Comment by jlebon** [comment]
@sdodson Hmm, the default RAM amount is 2G but I see now that the docs quote 8G as the minimum requirement, though I don't think the OpenStack instance could take many parallel loads then. Would 4G be acceptable? How many GBs do the other `aos-ci-jenkins` tests run with?

@cgwalters Also, might as well re-bump this to `v3.6.0` since it's out now.

**Comment by sdodson** [comment]
@jlebon 4G should be plenty

**Comment by jlebon** [comment]
Hmm, k. @cgwalters let's try adding a chunk like this, maybe?

```yaml
specs:
  ram: 4096
```

**Comment by cgwalters** [comment]
Rebased :surfing_man: and updated to use 4096 MB.

**Comment by sdodson** [comment]
bot, retest this please

**Comment by sdodson** [comment]
@cgwalters @jlebon So I added a task to dump logs indicating why the node failed to start, but it starts correctly now but doesn't register. Is there anyway we can debug this interactively?

**Comment by jlebon** [comment]
Replaced by https://github.com/openshift/openshift-ansible/pull/5461.

**Pull request closed without merging**
