### PR TITLE
Bug 1324729 - Import xPaas image streams failed during 3.2 installation

### PR DESCRIPTION
**Pull request by brenton**

### CODE REVIEW

**Comment by brenton** [comment]
I decided to just rip this out of the other PR I'm still working on.

**Comment by brenton** [comment]
@sdodson, PTAL

**Comment by sdodson** [comment]
LGTM, if you feel like it go ahead and fix v1.1 too? It's not as strict but I'd prefer minimizing the diff between the versions of content.

**Comment by brenton** [comment]
@sdodson updated!

**Comment by sdodson** [comment]
LGTM!

**Pull request merged**
