### PR TITLE
GCE cloud provider updates

### PR DESCRIPTION
**Pull request by detiber**
- fix overrides for gce machine type and gce machine image
- Update default image for origin
- Update default ssh user for origin and enterprise
- Remove wip and join_node playbooks
- Added add_nodes playbook which will now allow for using bin/cluster to add
  additional nodes
- Allow env override of ssh_user
- improve list playbook

### CODE REVIEW

**Comment by detiber** [comment]
depends on https://github.com/openshift/openshift-ansible/pull/1235
https://github.com/openshift/openshift-ansible/pull/1236

**Comment by detiber** [comment]
@lhuard1A @menren Mind taking a look at these proposed changes?

**Comment by detiber** [comment]
@twiest This fixes some outstanding issues with the gce provider playbooks.

**Comment by twiest** [comment]
@detiber looks good to me, I'll merge when I see what @menren says.

**Comment by menren** [comment]
This looks good to me.

We may just update the README on GCE with newly added environment variables such as gce_ssh_user or etcd machine types variables

**Comment by twiest** [comment]
@detiber would you like to add the env vars to the GCE README in this PR or another one?

**Comment by detiber** [comment]
@twiest I'll update this PR.

**Comment by detiber** [comment]
@twiest README updated and fixed the consistency of using the gce_ssh_user environment variable.

**Comment by twiest** [comment]
:+1:

**Pull request merged**
