### PR TITLE
Add openshift_docker_hosted_registry_insecure option

### LINKED ISSUE #1832: secure registry considerations
There seems to be a default no possible way to not have the --insecure-registry line added. It appears to be hardcoded.

Also, what are thoughts on adding the ca.crt into the the root bundle: eg.
cp /etc/origin/node/ca.crt /etc/pki/ca-trust/source/anchors; update-ca-trust 

This could avoid having to worry about having to make changes to all nodes should the docker-registry be re-deployed etc. (ie. not worrying about /etc/docker/certs.d/docker-registry-ip:5000 )

The above is all assuming that people are using the default ca.crt for securing their registry..

### PR DESCRIPTION
**Pull request by andrewklau**
lets me override the hardcoded the insecure registry 

Resolves #1832

### CODE REVIEW

**Comment by sdodson** [comment]
aos-ci-test

**Comment by detiber** [comment]
ok to test

**Comment by detiber** [comment]
@abutcher ptal

**Comment by abutcher** [comment]
@detiber :shipit: 

@mwoodson FYI

**Pull request merged**
