### PR TITLE
Add a wait for aggregated APIs when restarting control plane

### PR DESCRIPTION
**Pull request by sdodson**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1623571

### CODE REVIEW

**Comment by vrutkovs** [comment]
Breaks GCP tests - it seems ASB and metrics need to be installed for these API to show up, so these checks should be conditional

**Comment by sdodson** [comment]
Ugh, it's only two right now so we could do discovery to see if they're even installed rather than relying on any openshift-ansible defined state.

**Comment by deads2k** [comment]
> Ugh, it's only two right now so we could do discovery to see if they're even installed rather than relying on any openshift-ansible defined state.

or `oc get apiservices/<therightname` right?  does a 404 give a nonzero return?  It only has to hold one release.

**Comment by michaelgugino** [comment]
> Ugh, it's only two right now so we could do discovery to see if they're even installed rather than relying on any openshift-ansible defined state.

@sdodson we could build in the api check before we start rolling things and use that information to determine whether or not to wait for it.

**Comment by sdodson** [comment]
Refactored to check for registration then wait only when they're registered.
@deads2k does this implementation make sense?

**Comment by sdodson** [comment]
flake
/retest

**Comment by sdodson** [comment]
Squashed intermediate commits into one.

**Pull request merged**
