### PR TITLE
Upgrades: pass openshift_manage_node_is_master to master nodes during upgrade

### PR DESCRIPTION
**Pull request by vrutkovs**
This ensures required labels for master would be set.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1534917
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1535673

### CODE REVIEW

**Comment by vrutkovs** [comment]
Flakes

/retest

**Comment by sdodson** [comment]
Previous round of tests all passed, now CI is flaking on everything, merging.

**Pull request merged**
