### PR TITLE
Fix for node labeling where internal node name != inventory_hostname

### PR DESCRIPTION
**Pull request by detiber**

### CODE REVIEW

**Comment by sdodson** [comment]
LGTM, change makes sense and labels applied in my tests.
:+1:

**Comment by spinolacastro** [comment]
:+1: LGTM, fixed here as well .

**Comment by detiber** [comment]
@spinolacastro @sdodson thanks for taking a look.

@twiest @wshearn squashed and rebased after verification... please merge ASAP.

**Comment by sdodson** [comment]
@brenton ready for merge when you get a chance

**Pull request merged**
