### PR TITLE
Send limited in-addr.arpa zones to node resolver

### PR DESCRIPTION
**Pull request by sureshgaikwad**
Resolve reverse lookup issue

Proposed fix for https://bugzilla.redhat.com/show_bug.cgi?id=1588078

### CODE REVIEW

**Comment by sdodson** [comment]
Yeah, this is a complicated problem. The SVC cidr range is configurable so we'd at least need to accommodate that. That's easy enough for /24 /16 and /8 CIDRS but for classless ranges you have to compute a lengthy list of zones. We'd also need to make sure that this works for not only the kube svc cidr range but also the cluster network cidr (sdn). Our long term solution was to make the node responsible for sending a list of zones it wants to own to dnsmasq via dbus.

/CC @openshift/sig-networking

**Comment by DanyC97** [comment]
that is an interesting issue, ouch ;)

**Comment by danwinship** [comment]
> The SVC cidr range is configurable so we'd at least need to accommodate that. That's easy enough for /24 /16 and /8 CIDRS but for classless ranges you have to compute a lengthy list of zones.

I'd guess 90% of users are using 172.30.0.0/16 for their service cidr, and probably 90% of the rest are using some other /16 or /24. You could just skip the optimization for the classless case and say it will all get fixed in the CoreDNS future.

**Comment by sdodson** [comment]
Lets just check that `osm_cluster_network_cidr =='10.128.0.0/14'` and `openshift_portal_net == '172.30.0.0/16'` then configure the limited reverse zones. Everyone else gets current behavior.

**Comment by DanyC97** [comment]
@danwinship should i guess/ assume that coreDNS will be pulled into openshift too once it makes it into 1.11 K8 ?

**Comment by danwinship** [comment]
@DanyC97 I'm not sure we have a specific schedule, but I think the expectation is that we'll migrate to it eventually.

**Comment by sdodson** [comment]
> Lets just check that osm_cluster_network_cidr =='10.128.0.0/14' and openshift_portal_net == '172.30.0.0/16' then configure the limited reverse zones. Everyone else gets current behavior. Keep it simple and cover the 90%

@sureshgaikwad can you look at updating the PR for this?

**Comment by vrutkovs** [comment]
Master branch is closed! A major refactor is ongoing in devel-40. Changes for 3.x should be made directly to the latest release branch they're relevant to and backported from there.

**Pull request closed without merging**
