### PR TITLE
KIECLOUD-584-Update RHPAM and RHDM templates and imagestreams on Open…

### PR DESCRIPTION
**Pull request by msmagnanijr**
…Shift Service Catalog for 7.12.0 release

Signed-off-by: Mauricio Magnani <msmagnanijr@gmail.com>

### CODE REVIEW

**Review by desmax74 — APPROVED** [review]

**Comment by msmagnanijr** [comment]
@jstuever @patrickdillon  could you please take a look? thanks

**Comment by spolti** [comment]
@vrutkovs can you please take a look on this one?

**Comment by mtnbikenc** [comment]
No longer on this team. @patrickdillon or @jstuever can review.
/uncc

**Comment by msmagnanijr** [comment]
> /ok-to-test
> 
> This would need a BZ to merge.
> 
> Furthermore, we're not making any changes openshift-ansible except for bugs blocking upgrades or impacting customers. Is this a critical fix? If so can you give some background?

@patrickdillon This is about https://issues.redhat.com/browse/KIECLOUD-584 We released a new version so we need to update the templates. We do this for every version that is released. 

The same for OCP 4 https://github.com/openshift/library/pull/299

Thanks

**Comment by spolti** [comment]
Hi @patrickdillon we keep updating templates on ocp 3.11 for the customers that can't migrate to ocp 4.
In the past, someone had made the same question about BZ, and at the end it was not needed.

**Pull request merged**
