### PR TITLE
Libvirt provider fixes

### PR DESCRIPTION
**Pull request by detiber**

### CODE REVIEW

**Comment by detiber** [comment]
This will probably also impact other bin/cluster uses, but I haven't verified, yet.

**Comment by detiber** [comment]
@abutcher This seems to fix libvirt for me, I have a suspicion that the other providers will need a similar fix.

**Comment by bachp** [comment]
I can confirm that the change also fixes aws. However I'm not sure this is really the correct solution.

**Comment by moortimis** [comment]
This fixed my AWS deployment. Thanks

**Comment by detiber** [comment]
@bachp I agree on this not necessarily being the correct solution, however since it resolves the issue and the affected playbooks are community-supported only, I'm going to merge.

I'm happy to review any PRs that might have a more comprehensive fix, though.

**Pull request merged**
