### PR TITLE
Fix flexvolume installation in containarized installs

### PR DESCRIPTION
**Pull request by gnufied**
The PR fixes flexvolume setup for containarized installations. 

I have verified it to be working.

### CODE REVIEW

**Comment by gnufied** [comment]
cc @jsafrane @rootfs @childsb for input.

**Comment by jsafrane** [comment]
I am not sure this PR helps much, user installed flex volume and all the utilities to the host, not into the container with kubelet. The driver may need to execute these utilities.

IMO, the right way would be to run the flex driver on the host, i.e. add `nsenter` to each exec in flex.

**Comment by gnufied** [comment]
actually this PR may be needed regardless of whether each flex call is prefixed with `nsenter` or not, so that flexvolume plugin can be registered to the kubelet and controller-manager. Without it - openshift will reject any volumes that use the plugin as unknown.

**Comment by jsafrane** [comment]
That's very good point. Kubelet needs to see the drivers and this PR is needed. Still, IMO the drivers should not be executed in kubelet's container.

**Comment by gnufied** [comment]
@jsafrane yeah fixing intree flex driver is another thing I am working on, will try and open a PR shortly.

**Comment by sdodson** [comment]
@gnufied Do you have simliar fixes for master and release-3.10? I want to make sure we don't lose those.

**Comment by gnufied** [comment]
@sdodson I think we will need different variant of this for 3.10 because afaik we no longer run stuff as docker container but either as static pods or system containers.

**Comment by sdodson** [comment]
/lgtm
Though, maybe we should consider just making this uniform for both containerized and non containerized?

**Comment by gnufied** [comment]
@sdodson the 3.9 docs for flexvolume is already out with different path for non-containarized installs - https://docs.openshift.com/container-platform/3.9/install_config/persistent_storage/persistent_storage_flex_volume.html

I am not sure if it will be a good idea to change it because users who are using it in non-containarized installs already have a working flex environment. For users in containarized installs, it is already broken and hence we can still update it.

**Comment by jsafrane** [comment]
lgtm from sig-storage POV

**Comment by gnufied** [comment]
@sdodson who should we get approval from this to get merged? My plan is to fix openshift-ansible and then update openshift docs to reflect correct thing.

**Comment by vrutkovs** [comment]
Lets create a PR for master and cherrypick it back to 3.10 and 3.9

**Comment by gnufied** [comment]
There is already a PR open for 3.10 - https://github.com/openshift/openshift-ansible/pull/8964 . The PR for 3.10 is different because of move to static pods for control-plane components and kubelet no longer runs as docker container.

**Pull request merged**
