### PR TITLE
Add the OpenStack provider

### PR DESCRIPTION
**Pull request by tomassedovic**
This replaces the #5797. It has the same content, but preserves the git history from the openshift-ansible-contrib repo.

It uses the openstack roles and playbooks from openshift-ansible-contrib and adapts them to have the same structure as the AWS provider.

This provides a basic deployment with more advanced stuff coming in follow-up patches.

### CODE REVIEW

**Comment by tomassedovic** [comment]
@michaelgugino @oybed @bogdando @sdodson @mbruzek FYI this is the new version of the OpenStack provider PR.

**Comment by bogdando** [comment]
:+1: 
let's do this!

**Comment by sdodson** [comment]
/hold
holding this until 3.7 branch is forked tomorrow when we clear codefreeze

**Comment by tomassedovic** [comment]
@sdodson I see the 3.7 release branch has been created. What's the next step here?

**Comment by bogdando** [comment]
sorry for spamming, I better off remove the reference from the commit msg

**Comment by tomassedovic** [comment]
@michaelgugino I'm not sure what to make of the two failing tests. They don't seem to be related to this change. The vast majority of the files here are new and shouldn't affect the outcome of the CI.

Is there anything I should do here? Assuming this is a flakey CI, is there anything I need to do here? This pull request is no longer in the queue dashboard.

**Comment by tomassedovic** [comment]
And of course if it's not a CI problem, I'm not sure where to look -- the failures doesn't seem to be related to anything here. Any ideas?

**Comment by sdodson** [comment]
They both look like flakes.

**Pull request merged**
