### PR TITLE
Install web console on upgrade

### PR DESCRIPTION
**Pull request by spadgett**
Pared down PR that just installs the web console in post_control_plane upgrade. Leaving #6676 open for now to work on migrating asset config from master-config.yaml.

/assign @sdodson 
@jwforres

### CODE REVIEW

**Comment by spadgett** [comment]
/hold

because I have not been able to fully test. @sdodson I might need help validating.

**Comment by sdodson** [comment]
Looks fine to me, i'll give it a go tonight too.

**Comment by spadgett** [comment]
@sdodson Will this break 3.7 -> 3.8 upgrade? There is no web console image tagged 3.8.

**Comment by sdodson** [comment]
Tested this upgrading OCP 3.7 to 3.8, console was deployed as expected using the v3.9 images.

**Comment by sdodson** [comment]
Actually, the pod is crashlooping against 3.8 API, not sure if this is a problem specific to 3.8 API or not. It may simply just be that the image is quite outdated at this point.

```
# oc logs webconsole-86c5dccd87-xp9sl
Error: no kind "WebConsoleConfiguration" is registered for version "webconsole.config.openshift.io/v1"
```

**Comment by spadgett** [comment]
@sdodson You need these changes in the web console image you're using:

https://github.com/openshift/origin-web-console-server/pull/16

I'm a little worried though that the install completed if the pod is crash looping.

**Comment by sdodson** [comment]
flake

**Pull request merged**
