### PR TITLE
Gluster block release 3.7 cherry-pick

### PR DESCRIPTION
**Pull request by mjudeikis**
Gluster Block cherry pick #7190 #7028 #6996 #6922, bz1550271 and few other issues to fix multiple gluster block automation issues.
Fixes BZ 1540080 for 3.7 branch.

### CODE REVIEW

**Comment by jarrpa** [comment]
@mjudeikis Is there a 3.6 version in the works as well?

**Comment by mjudeikis** [comment]
@jarrpa not yet. One at the time now as it was already challenge to collect all of them :D

**Comment by jarrpa** [comment]
It is holding on the changes being verified in 3.9.

/hold

**Comment by DanyC97** [comment]
@jarrpa sorry if i'm being too pushy, is anything i can do to help to improve the time for this QA to happen ? 

Asking because internally i'm holding a release on origin waiting for the whole glusterFS lot and i'd prefer to avoid any internal fork. If you have an ETA when all this will be completed, would help me a lot to make a decision or come up with a sensible plan b

I understand that you guys can't commit to anything related to origin (i'm not even asking for that) but will be good to know  if / when will be

**Comment by jarrpa** [comment]
As I've asked elsewhere, email me and we'll talk. :)

**Comment by DanyC97** [comment]
@mjudeikis fyi the PR #7028 , in particular [this](https://github.com/openshift/openshift-ansible/pull/7213/files#diff-64bdb07749172e43830e411762cf4039R5)  needs rebase to incorporate https://github.com/openshift/openshift-ansible/pull/7237

thought i should let you know ... ;)

**Comment by jarrpa** [comment]
This is why we want to wait for QE to finish before backporting anything...

**Comment by DanyC97** [comment]
@jarrpa i get it ;) in meantime i'm doing the monkey work internally until upstream catch up, not ideal but i can't wait due to tight deliverables

**Comment by mjudeikis** [comment]
will rebase this when this gets in https://github.com/openshift/openshift-ansible/pull/7322

**Comment by mjudeikis** [comment]
@jarrpa looks like we are done :D waiting for the Green light.

**Comment by mjudeikis** [comment]
Testing this PR in my lab. Running prometheus with gluster-block storage class and 6 nodes of gluster (gluster and registry)
```
[root@ip-172-18-15-94 ~]# oc project openshift-metrics                                                   
Now using project "openshift-metrics" on server "https://ec2-34-201-216-70.compute-1.amazonaws.com:8443".                                                                                                          
[root@ip-172-18-15-94 ~]# oc get pods               
NAME           READY     STATUS    RESTARTS   AGE   
prometheus-0   6/6       Running   0          13m   
[root@ip-172-18-15-94 ~]# oc get pvc                
NAME           STATUS    VOLUME                                     CAPACITY   ACCESSMODES   STORAGECLASS              AGE                                                                                         
alertbuffer    Bound     pvc-2f6709d7-2125-11e8-92dd-0e6c5d2887f8   10G        RWO           glusterfs-storage-block   13m                                                                                         
alertmanager   Bound     pvc-2eb56869-2125-11e8-92dd-0e6c5d2887f8   10Gi       RWO           glusterfs-storage-block   13m                                                                                         
prometheus     Bound     pvc-2e01c8cc-2125-11e8-92dd-0e6c5d2887f8   10Gi       RWO           glusterfs-storage-block   13m                                                                                         
[root@ip-172-18-15-94 ~]# oc get pods               
NAME           READY     STATUS    RESTARTS   AGE   
prometheus-0   6/6       Running   0          14m   
[root@ip-172-18-15-94 ~]# oc get pods --all-namespaces                                                   
NAMESPACE           NAME                                           READY     STATUS    RESTARTS   AGE    
default             docker-registry-1-deploy                       0/1       Error     0          45m    
default             docker-registry-2-nd57s                        1/1       Running   0          30m    
default             registry-console-1-frxbr                       1/1       Running   0          29m    
default             router-2-rmwhx                                 1/1       Running   0          30m    
glusterfs           glusterblock-registry-provisioner-dc-1-dvdtt   1/1       Running   0          48m    
glusterfs           glusterblock-storage-provisioner-dc-1-q7nw6    1/1       Running   0          52m    
glusterfs           glusterfs-registry-d9x5m                       1/1       Running   0          51m    
glusterfs           glusterfs-registry-kjvsp                       1/1       Running   0          51m    
glusterfs           glusterfs-registry-m79pt                       1/1       Running   0          51m    
glusterfs           glusterfs-storage-9xs7b                        1/1       Running   0          56m    
glusterfs           glusterfs-storage-jpc49                        1/1       Running   0          56m    
glusterfs           glusterfs-storage-znlx4                        1/1       Running   0          56m    
glusterfs           heketi-registry-1-679wn                        1/1       Running   0          48m    
glusterfs           heketi-storage-1-6p2gh                         1/1       Running   0          53m    
openshift-metrics   prometheus-0                                   6/6       Running   0          14m
```

**Comment by DanyC97** [comment]
@mjudeikis @jarrpa so just to get it right in my head, how you guys wanna proceed?

* merge this PR first
* then merge https://github.com/openshift/openshift-ansible/pull/7470
* then unblock my PRs ? like https://github.com/openshift/openshift-ansible/pull/7219

**Comment by mjudeikis** [comment]
I think Idea is to collect everything to #7470 (I plan to be done with draft on Monday and start review and test)

**Comment by DanyC97** [comment]
@mjudeikis thank you for letting me know about the plan.

If you don't mind, can you please pull in #7219 (is low risk).

**Comment by mjudeikis** [comment]
closing in favor of https://github.com/openshift/openshift-ansible/pull/7470

**Pull request closed without merging**
