### PR TITLE
Change default set for networkConfig.externalIPNetworkCIDRs to reject all CIDRs

### PR DESCRIPTION
**Pull request by rjhowe**
Changing master-config.yaml networkConfig.externalIPNetworkCIDRs to reject all IPs by default. Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1560712

### CODE REVIEW

**Comment by michaelgugino** [comment]
@rjhowe Let's rebase and get this in.  openshift_master role is gone, make the change in openshift_control_plane.

**Comment by michaelgugino** [comment]
@rjhowe @sdodson Let's rebase and get this in.

**Comment by vrutkovs** [comment]
Master branch is closed! A major refactor is ongoing in devel-40. Changes for 3.x should be made directly to the latest release branch they're relevant to and backported from there.

**Pull request closed without merging**
