### PR TITLE
WIP Implement OpenStack provisioning in Ansible

### PR DESCRIPTION
**Pull request by tomassedovic**
This is the first step towards not requiring OpenStack Heat to do the provisioning.

For now, the Heat and Ansible playbooks live side by side it is possible to select the desired branch by setting `openshift_openstack_provisioner` as either `heat` (default) or `ansible`.

I have managed to get a successful 1 master, 1 infra and 1 compute cluster deployed with:

    ansible-playbook -i openshift-ansible/playbooks/openstack/inventory.py -i inventory openshift-ansible/playbooks/openstack/openshift-cluster/provision_install.yml -e openshift_openstack_provisioner=ansible

and it seems to work just fine (the router and registry pods are up, image builds work, routes are accessible from the outside), except that some of the records are not created in the DNS yet.

To do:
- [ ] Fix setting the `openshift_openstack_public_api_ip` and `openshift_openstack_public_router_ip` variables
- [ ] Node group policies (e.g. affinity, anti-affinity)
- [ ] CNS
- [ ] Cinder Volumes
- [ ] Octavia load balancers
- [ ] VM-based (legacy) load balancers
- [ ] Provider networks
- [ ] Security groups (right now we just open it all up)
- [ ] Kuryr
- [ ] Trunk ports

And probably a host of other things I've missed yet.

### CODE REVIEW

**Comment by tomassedovic** [comment]
Timing-wise, I have not discovered significant differences between this and Heat. But I haven't tried any larger deployments (where I would expect Heat's parallelism to kick in).

**Comment by tomassedovic** [comment]
FYI @luis5tb @tzumainn @jmencak @mbruzek

**Comment by mbruzek** [comment]
Thanks for the ping @tomassedovic this looks like a big change.

For various reasons our automation has to call the playbooks individually to install a cluster. 

```{{ ansible_playbook }} -vvv --user openshift -i inventory -i {{ inventory_py }} {{ openshift_openstack_dir }}/openshift-cluster/prerequisites.yml```

```{{ ansible_playbook }} -vvv --user openshift -i inventory -i {{ inventory_py }} {{ openshift_openstack_dir }}/openshift-cluster/provision.yml```

```{{ ansible_playbook }} -vvv --user openshift -i inventory -i {{ inventory_py }} {{ openshift_openstack_dir }}/openshift-cluster/install.yml```

I would hope that the individual playbooks can still be called individually. Please advise if any of this changes.

Our scale up automation calls the following playbook:

```{{ ansible_playbook }} -vv --user openshift -i inventory/ -i {{ inventory_py }}  -i {{ new_nodes_inventory }} openshift-ansible/playbooks/openshift-node/scaleup.yml```

Does this `scaleup.yml` involve the heat stack as well?

**Comment by tomassedovic** [comment]
Hey @mbruzek. Ideally, nothing should change from the deployer's point of view. All the playbooks in `playbooks/openstack/openshift-cluster` should work just as they used to with the same interface and everything.

The only difference is that we'll be creating the OpenStack resources (VMs, networks etc.) via Ansible directly, rather than invoking Heat.

As for scaleup, the `openshift-ansible/playbooks/openshift-node/scaleup.yml` should not be affected by this change at all either. Presumably, the way you do things now is:

1. Increase the node count in the inventory
2. Run `playbooks/openstack/openshift-cluster/provision.yml` (or `provision-resources.yml`)
3. Set the `new_nodes` Ansible group
4. Run `openshift-ansible/playbooks/openshift-node/scaleup.yml`

That process should keep working as is. I'd like to add a playbook that automates this somewhat (initial work in #9008 though that's mostly just docs describing the above for now), but nothing we do here should break the process above.

**Comment by vrutkovs** [comment]
Master branch is closed! A major refactor is ongoing in devel-40. Changes for 3.x should be made directly to the latest release branch they're relevant to and backported from there.

**Pull request closed without merging**
