### PR TITLE
Update default log driver to journald

### PR DESCRIPTION
**Pull request by smunilla**
Change the default log driver from josn-file to journald to
improve logging functionality.

Fixes Bug 1393178

### CODE REVIEW

**Comment by smunilla** [comment]
@sdodson Is there any reason not to do this I'm not thinking of?

**Comment by sdodson** [comment]
I can't think of anything.
@richm Are there any other tasks that need to be done when changing this on an existing cluster?

**Comment by richm** [comment]
If you change this on an existing cluster, you will need to restart fluentd so that it knows to use journald as the input source.  That is, on the node, when you restart docker to use journald, you should restart fluentd on that node too.
When upgrading to 3.4, will all of the logging components be restarted/redeployed?

**Comment by smunilla** [comment]
Looks like @abutcher had this covered in #2767

**Pull request closed without merging**
