### PR TITLE
Add EAP 7.2.beta to v3.9

### PR DESCRIPTION
**Pull request by luck3y**
Signed-off-by: Ken Wills <kwills@redhat.com>

### CODE REVIEW

**Comment by vrutkovs** [comment]
Looks fine to me, lets squash the commits

**Comment by luck3y** [comment]
@vrutkovs Do you want me to squash them and repush, or do you just want to squash when you merge? Either is fine with me.

**Comment by vrutkovs** [comment]
@luck3y yeah, you should squash those - ideally the bot would merge the PR once the tests are passing, but it can't squash commits

**Comment by luck3y** [comment]
@vrutkovs Squashed, thanks!

**Comment by luck3y** [comment]
rebased this to see if the gpc test is fixed.

**Pull request closed without merging**
