### PR TITLE
GlusterFS: Fix uninstall regression

### PR DESCRIPTION
**Pull request by jarrpa**
This reimpliments #6402 which was missed by #6918.

Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>

### CODE REVIEW

**Comment by DanyC97** [comment]
any idea why is it taking so long for this tests to complete ?

**Comment by jarrpa** [comment]
I shouldn't give myself LGTM. @michaelgugino @mtnbikenc Can either of you take a look?

**Pull request merged**
