### PR TITLE
Clean up versions.sh

### PR DESCRIPTION
**Pull request by sdodson**

### CODE REVIEW

**Comment by sdodson** [comment]
Another possible fix for #1072

**Comment by abutcher** [comment]
Not sure if this difference will matter yet...

```
New:
[root@master4 ~]# sh versions.sh atomic-openshift openshift
---
curr_version: 3.1.0.4-1.git.15.5e061c3.el7aos 
avail_version: 3.0.2.0-0.git.38.7576bc5.el7ose 

Old:
[root@master4 ~]# sh ~/openshift-ansible/playbooks/common/openshift-cluster/upgrades/files/versions.sh atomic-openshift openshift
---
curr_version: 3.1.0.4-1.git.15.5e061c3.el7aos 
avail_version:
```

**Comment by sdodson** [comment]
Added the `grep -v el7ose` back in.

**Comment by abutcher** [comment]
lgtm

**Comment by sdodson** [comment]
@twiest i think this is ready to merge

**Comment by detiber** [comment]
:+1:

**Pull request merged**
