### PR TITLE
Removed unused, unwanted, incorrectly committed code.

### PR DESCRIPTION
**Pull request by kwoodson**

### CODE REVIEW

**Comment by kwoodson** [comment]
[merge]

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
@kwoodson merge job is dependent on the `aos-ci-test` jobs passing.

**Comment by ashcrow** [comment]
Hrm. Can't see why the merge failed. I'm getting a ``503`` trying to review logs. /cc @stevekuznetsov

**Comment by stevekuznetsov** [comment]
As @detiber noted above, the job needs AOS CI jobs to have passed. That merge failed with:

```
Stage CHECK OTHER JOB STATUSES failed.
```

As seen [here](https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_openshift_ansible/16/consoleFull#-138478989358b6e51eb7608a5981914356):
```
01:10:21.444 + /usr/bin/check-pull-request-status.py 3622 /var/lib/jenkins/.config/hub
01:10:22.907 INFO: Found status 'continuous-integration/travis-ci/pr' with state 'success'.
01:10:22.907 [ERROR] Status 'aos-ci-jenkins/OS_3.4_NOT_containerized' is required but was not found on this pull request.
01:10:22.907 [ERROR] Status 'aos-ci-jenkins/OS_3.4_NOT_containerized_e2e_tests' is required but was not found on this pull request.
01:10:22.908 [ERROR] Status 'aos-ci-jenkins/OS_3.4_containerized' is required but was not found on this pull request.
01:10:22.908 [ERROR] Status 'aos-ci-jenkins/OS_3.4_containerized_e2e_tests' is required but was not found on this pull request.
01:10:22.908 [ERROR] Status 'aos-ci-jenkins/OS_3.5_NOT_containerized' is required but was not found on this pull request.
01:10:22.908 [ERROR] Status 'aos-ci-jenkins/OS_3.5_NOT_containerized_e2e_tests' is required but was not found on this pull request.
01:10:22.908 [ERROR] Status 'aos-ci-jenkins/OS_3.5_containerized' is required but was not found on this pull request.
01:10:22.908 [ERROR] Status 'aos-ci-jenkins/OS_3.5_containerized_e2e_tests' is required but was not found on this pull request.
01:10:22.909 [ERROR] Status 'aos-ci-jenkins/OS_unit_tests' is required but was not found on this pull request.
```

I'll tag for re[merge]

**Comment by stevekuznetsov** [comment]
@openshift-bot, the [last build](https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_openshift_ansible/26/) failed from the following flakes:
 - [install](https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_openshift_ansible/26/consoleFull#181270559558b6e51eb7608a5981914356) failed on: https://github.com/openshift/origin/issues/13318

re[merge]

**Comment by ashcrow** [comment]
:crossed_fingers:

**Pull request merged**
