### PR TITLE
[upgrade] Create/configure service signer cert when missing.

### LINKED ISSUE #2444: service-signer.crt/key not created on upgrade from 1.2 to 1.3
TASK [openshift_master_certificates : file] ************************************
...
skipping: [master.app.abac.io] => (item=service-signer.crt) 
skipping: [master.app.abac.io] => (item=service-signer.key) 

....
this will cause the origin-master to fail on startup.

### PR DESCRIPTION
**Pull request by abutcher**
Fixes #2444

@dgoodwin @sdodson PTAL

### CODE REVIEW

**Comment by dgoodwin** [comment]
LGTM

**Comment by sdodson** [comment]
LGTM

**Comment by sdodson** [comment]
I don't think this will work but lets see.

aos-ci-test-extended

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by abutcher** [comment]
ok to test

**Pull request merged**
