### PR TITLE
RH-SSO 7.1 xpaas templates and imageStreams

### PR DESCRIPTION
**Pull request by ruromero**
I have added the following resources:
- All the xpaas templates from v1.2 to v3.6 for rh-sso the same way as they are for 7.0
- ImageStreams for registry.access.redhat.com/redhat-sso-7/sso71-openshift starting from v1.4 until v3.6

### CODE REVIEW

**Comment by sdodson** [comment]
Have you tested sso71 in v1.2 through v3.6? We only generally update the current dev and current GA release unless someone has verified that they've been tested on older releases.

**Comment by ruromero** [comment]
I have only tested v1.4

**Comment by sdodson** [comment]
Ok, lets remove the update for v1.2 and v1.3 then.

**Comment by ruromero** [comment]
done @sdodson

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
this change was picked up via the xpaas v1.4.0 merge

**Pull request closed without merging**
