### PR TITLE
Fix variable interpolation

### PR DESCRIPTION
**Pull request by IshentRas**

### CODE REVIEW

**Comment by ingvagabund** [comment]
@IshentRas think you could build your PR on top of https://github.com/openshift/openshift-ansible/pull/5510 ?

**Comment by sdodson** [comment]
Rebased it on top of master.

**Comment by IshentRas** [comment]
Done

**Comment by abutcher** [comment]
Is this fixing a problem with these checks? I think this would work either way due to the way `oo_collect` works. Here's a [check_results dictionary ](https://gist.github.com/abutcher/d945ed2e2480abc9121a7f5a33b114f2) which has keys: `check_results.check_results.(.+)`. We're able to `oo_collect` `check_results.check_results.etcd` as well as `check_results.etcd` since both key structures exist within the dictionary.

**Comment by IshentRas** [comment]
@abutcher Will try again... Happy to be wrong here. But all my previous attempts were NOK...

**Pull request closed without merging**
