### PR TITLE
Fail if a node_upgrade.yml playbook is run over a master host

### PR DESCRIPTION
**Pull request by ingvagabund**
Node part of a master node is upgraded as part of the control plane upgrade.

Bugs: bz#1455857

### CODE REVIEW

**Comment by ingvagabund** [comment]
aos-ci-test

**Comment by ashcrow** [comment]
@ingvagabund one thing to note, I **think** we still prefer ``assert`` over ``fail``.

**Comment by ingvagabund** [comment]
> @ingvagabund one thing to note, I think we still prefer assert over fail.

True. Still getting used to it.

**Comment by ingvagabund** [comment]
[merge]

**Comment by ingvagabund** [comment]
Closed in favor of https://github.com/openshift/openshift-ansible/pull/4399

**Pull request closed without merging**
