### PR TITLE
Added missing R in cassandra

### PR DESCRIPTION
**Pull request by smossber**
for openshift_metrics_cassanda_pvc_storage_class_name

### CODE REVIEW

**Comment by vrutkovs** [comment]
@rh-atomic-bot bot, test pull request

/ok-to-test

**Comment by sdodson** [comment]
bot, test pull request

**Comment by vrutkovs** [comment]
Master branch is closed! A major refactor is ongoing in devel-40. Changes for 3.x should be made directly to the latest release branch they're relevant to and backported from there.

**Pull request closed without merging**
