### PR TITLE
[3.6] Passing memory and cpu limit for ops ES install

### PR DESCRIPTION
**Pull request by ewolinetz**
Backport of https://github.com/openshift/openshift-ansible/pull/5158
Addresses https://github.com/openshift/origin-aggregated-logging/issues/605

CPU and Memory limit requests variables were not being passed to ES role for ops values

### CODE REVIEW

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
[merge]

**Comment by sdodson** [comment]
Seems unrelated to this PR.

```
TASK [openshift_logging_elasticsearch : Set ES dc] *****************************
task path: /usr/share/ansible/openshift-ansible/roles/openshift_logging_elasticsearch/tasks/main.yaml:281
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "generated_timestamp": "2017-08-24 05:44:08.885642", 
    "msg": {
        "cmd": "/bin/oc create -f /tmp/openshift-logging-ansible-33t4CA/templates/logging-es-dc.yml -n logging", 
        "results": {}, 
        "returncode": 1, 
        "stderr": "Error from server (BadRequest): error when creating \"/tmp/openshift-logging-ansible-33t4CA/templates/logging-es-dc.yml\": DeploymentConfig in version \"v1\" cannot be handled as a DeploymentConfig: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'\n", 
        "stdout": ""
    }
}
```

**Pull request merged**
