### PR TITLE
configure debug_level for master and node from cli

### PR DESCRIPTION
**Pull request by jkhelil**

### CODE REVIEW

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
Seems like a decent compromise to add compatibility with cli.

**Comment by detiber** [comment]
ok to test

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
aos-ci-test

**Comment by jkhelil** [comment]
aos-ci-jenkins/OS_3.0 are failing but does not seem to be related to this commit. how can I run again tests on aos-ci-jenkins/OS_3.0

**Comment by abutcher** [comment]
aos-ci-test

**Comment by detiber** [comment]
:+1: @brenton

**Pull request merged**
