### PR TITLE
fix curator host, port params; remove curator es volumes

### PR DESCRIPTION
**Pull request by richm**
fix curator host, port params; remove curator es volumes
@ewolinetz @stevekuznetsov
[test_logging]

### CODE REVIEW

**Comment by ewolinetz** [comment]
thanks @richm

**Comment by ewolinetz** [comment]
[test]

**Comment by ewolinetz** [comment]
does this make the work in https://github.com/openshift/origin-aggregated-logging/pull/445 unnecessary?

**Comment by stevekuznetsov** [comment]
Cool, this fixes the curator test. Let's this bad boy merged.

**Comment by stevekuznetsov** [comment]
Missing only aos-ci-tests

**Pull request merged**
