### PR TITLE
Fix 1.2 version check

### PR DESCRIPTION
**Pull request by detiber**

### CODE REVIEW

**Comment by sdodson** [comment]
LGTM, I'd also be fine with calling 1.1.3 as 1.2. It's closer to 1.2 than it is 1.1.

**Comment by detiber** [comment]
@sdodson I'm hesitant in calling it 1.2 just because we wouldn't be able to handle any changes between 1.1.3 and 1.2 (and the obvious naming disconnect)

**Comment by sdodson** [comment]
:+1:

**Comment by detiber** [comment]
@brenton

**Pull request merged**
