### PR TITLE
CRIO minor fixes for 3.10

### PR DESCRIPTION
**Pull request by vrutkovs**
* Remove openshift_crio_use_rpm as RPM is the only way to use CRIO now
* Update hosts.example with crio vars
* Ignore errors in docker storage when openshift_use_crio_only is on

### CODE REVIEW

**Comment by ashcrow** [comment]
I'm not against the removal of ``openshift_crio_use_rpm`` as long as it's documented and known anyone using ``cri-o`` before 3.10 will not be able to upgrade.

**Comment by ashcrow** [comment]
I'll let @michaelgugino make the go/no go for the PR but it looks fine to me.

**Comment by vrutkovs** [comment]
>I'm not against the removal of openshift_crio_use_rpm as long as it's documented and known anyone using cri-o before 3.10 will not be able to upgrade.

Its now would be impossible to upgrade if CRIO system container is used - that would be a doc change. In other cases RPM would be assumed

**Pull request merged**
