### PR TITLE
Update origin docs

### PR DESCRIPTION
**Pull request by johnjelinek**
Add service-account reference to post-ansible steps

### CODE REVIEW

**Comment by jtslear** [comment]
So this should also be updated for the AWS documentation as well.  But oddly, for the registry portion, I did not need to specify the service account.

**Comment by sdodson** [comment]
The registry needs a service account when it's deployed using the --mount-host option as it needs to be a privileged container.

**Comment by sdodson** [comment]
This was obviated by linking to the official docs for next steps.

**Comment by jaryn** [comment]
Can one of the admins verify this patch?

**Comment by abutcher** [comment]
@brenton Please close this PR.

**Pull request closed without merging**
