### PR TITLE
Fix typo in variable names for glusterfs firewall configuration

### PR DESCRIPTION
**Pull request by bacek**

### CODE REVIEW

**Comment by kwoodson** [comment]
@bacek, I didn't realize you created a PR to fix.  I'm fine closing mine and taking this one.

https://github.com/openshift/openshift-ansible/pull/5171

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[test]

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Comment by kwoodson** [comment]
@bacek, Did you mean to combine these later commits?  Looks like there was extra code added to this PR that was outside of the scope of the glusterfs variable renaming.

**Comment by bacek** [comment]
Oops. My bad. Let me fix it.

**Comment by bacek** [comment]
@kwoodson fixed.

**Comment by kwoodson** [comment]
aos-ci-test

**Comment by kwoodson** [comment]
[merge]

**Comment by kwoodson** [comment]
[merge]

**Comment by kwoodson** [comment]
```
FAILURE after 60.302s: test/fluentd-forward.sh:113: executing 'oc get pods -l component=fluentd' expecting any result and text '^logging-fluentd-.* Running '; re-trying every 0.2s until completion or 60.000s: the command timed out
```

Unrelated.  Manually merge.

**Pull request merged**
