### PR TITLE
Plugin consolidate

### PR DESCRIPTION
**Pull request by michaelgugino**
This commit relocates filter_plugings to lib_utils,
changes the namespacing to prevent unintended use of
older versions that may be present in filter_plugins/
directory on existing installs.

Add lib_utils to meta depends for roles

Also consolidate some plugins into lib_utils from
various other areas.

Update rpm spec, obsolete plugin rpms.

### CODE REVIEW

**Comment by mtnbikenc** [comment]
All the symlinks for filter_plugins, lookup_plugins and library should be removed.  You could also consolidate the callback from the installer_checkpoint role.  The README.md would just need to be moved/renamed and the references to that role updated.

I don't know how much value adding `lib_utils` to the beginning of every filter give us.

Moving the openshift_quick_installer callback probably broke the quick installer.

**Comment by michaelgugino** [comment]
> I don't know how much value adding lib_utils to the beginning of every filter give us.

It gives us and other users an approximate idea of where this filter lives.

**Comment by michaelgugino** [comment]
>  You could also consolidate the callback from the installer_checkpoint role. The README.md would just need to be moved/renamed and the references to that role updated.

I plan on more consolidation in a follow up.

**Comment by sdodson** [comment]
Specfile changes look good, I've verified the upgrade path works as expected from old to new packages.
/lgtm

**Comment by sdodson** [comment]
Install phase of those tests all completed. Looking to assess how soon the e2e tests will be fixed and may go ahead and merge without any e2e tests.

**Pull request merged**
