### PR TITLE
set KillMode to process in node service file

### PR DESCRIPTION
**Pull request by ingvagabund**
Bug: 1423640

### CODE REVIEW

**Comment by ingvagabund** [comment]
aos-ci-test

**Comment by sdodson** [comment]
CI jobs are still broken on image builds, merging.

**Comment by ingvagabund** [comment]
@sdodson backport to 3.5 and/or 3.4?

**Comment by sdodson** [comment]
yeah, sorry i should've added those labels when reviewing.

**Comment by sjenning** [comment]
This has exposed https://bugzilla.redhat.com/show_bug.cgi?id=1473531

**Comment by derekwaynecarr** [comment]
I do not think this is a safe change given the other problems it exposes.

I would like this reverted.

@ingvagabund @sdodson

**Comment by sdodson** [comment]
@jsafrane can you comment on this?

**Comment by derekwaynecarr** [comment]
i am trying to balance the number of workloads this helps versus the number it hurts.  right now, it appears to me from my reading of the linked issues its harm is greater than its good.  we need to fix the issues it exposed before taking this fix.

**Comment by sjenning** [comment]
@sdodson I agree with @derekwaynecarr.  I'll try to get a fix in for cadvisor, but that fix should really exist _before_ this fix.  And long term, we do not want the fuse processes in the same systemd service with the node process.  Setting `KillMode=process` effectively makes these processes unmanageable by systemd, which is no good.

**Comment by sjenning** [comment]
Also, I was talking to @jsafrane before he signed off and he agrees that the whole thing is hacky.  We talked about using systemd-run + `--experimental-mounter-path` to start the fuse processes in their own service.  That would cause service sprawl but would make each one a child of systemd.  Not sure what that would mean for selinux policy.  Having two different fixes for RPM vs containerized isn't ideal either.

**Comment by sdodson** [comment]
Ok, lets revert.

**Comment by sjenning** [comment]
discussion upstream on this topic for future reference
https://github.com/kubernetes/kubernetes/issues/34965

**Comment by jsafrane** [comment]
I'm fixing mounter in Kubernetes to use systemd-run even when running on directly on the host. PR will follow shortly.

**Comment by jsafrane** [comment]
Kubernetes PR: https://github.com/kubernetes/kubernetes/pull/49640

**Pull request merged**
