### PR TITLE
Add rate limit configurability

### PR DESCRIPTION
**Pull request by sdodson**
# Configure master API rate limits for external clients
#openshift_master_external_ratelimit_qps=200
#openshift_master_external_ratelimit_burst=400
# Configure master API rate limits for loopback clients
#openshift_master_loopback_ratelimit_qps=300
#openshift_master_loopback_ratelimit_burst=600

### CODE REVIEW

**Comment by sdodson** [comment]
@smarterclayton Can you verify these are still sane defaults?

**Comment by smarterclayton** [comment]
@liggitt

**Comment by liggitt** [comment]
lgtm

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Comment by sdodson** [comment]
[merge]

**Pull request merged**
