### PR TITLE
Update dependencies to ensure repos are available before openshift_master_* and etcd_* roles are run

### PR DESCRIPTION
**Pull request by detiber**
addresses https://github.com/openshift/openshift-ansible/issues/364

### CODE REVIEW

**Comment by detiber** [comment]
@twiest @wshearn Fixes an error with origin deployments where the openshift_master_ca role tries to install the openshift binary without having the repos configured yet (using the Vagrantfile), Also adding the dependency on openshift_repos for the etcd roles as well as a precautionary measure for the same reason.

**Comment by twiest** [comment]
:+1:

**Comment by kvjeevan** [comment]
I have downloaded installer from https://install.openshift.com/portable/oo-install-ose.tgz and after running the installer, i get the below error after sometime.  I am trying to install on CentOS 7. Please help me to get around this problem.
-------------------------
TASK: [openshift_master_ca | Install the base package for admin tooling] ******
failed: [10.x.x.x] => {"changed": false, "failed": true, "rc": 0, "results": []}
msg: No Package matching 'openshift' found available, installed or updated

FATAL: all hosts have already failed -- aborting

**Comment by detiber** [comment]
@sdodson ^ related to the package naming changes possibly?

**Comment by sdodson** [comment]
@kvjeevan That installer only works for OSE which requires access to the Red Hat OSE channels which of course wouldn't be available in Centos. I believe at this time we do not plan for the quick installer (what you've downloaded) to work for Origin. 

Here's the docs for the advanced installer that should work on Centos 7 using Origin.
https://docs.openshift.org/latest/install_config/install/advanced_install.html

**Comment by kvjeevan** [comment]
Thanks sdodson. If i look at the issue #364 (https://github.com/openshift/openshift-ansible/issues/364), it seems that it is being deployed on CentOS (looking at /etc/yum.repo.d output in the link) and the fix was suggested for it. If i am not wrong.

**Comment by kvjeevan** [comment]
let me try on RHEL 7.1

**Comment by sdodson** [comment]
@kvjeevan Ok, even with rhel7.1 It will only work if you have the system subscribed to the OSE channels.

**Comment by detiber** [comment]
@kvjeevan @sdodson We will want to support origin through the quick installer at some point (the sooner the better imho). I don't think it's something that we'll get to before the 3.1 release though.

**Comment by kvjeevan** [comment]
@sdodson, I have installed RHEL 7.1 and registered to Redhat subscription network and still seeing the same error :- 
TASK: [openshift_master_ca | Install the base package for admin tooling] ******
failed: [master.ose3.com] => {"changed": false, "failed": true, "rc": 0, "results": []}
msg: No Package matching 'openshift' found available, installed or updated

FATAL: all hosts have already failed -- aborting

**Comment by kvjeevan** [comment]
ran "subscription-manager register" to register my system

**Comment by kvjeevan** [comment]
Is there any workaround to overcome this error?

**Comment by sdodson** [comment]
You need the channels enabled per the documentation here
https://docs.openshift.com/enterprise/3.0/install_config/install/prerequisites.html#software-prerequisites

**Comment by kvjeevan** [comment]
I believe I have the access to it, since when I run the list, OSE in the 30 days evaluation list. Is this not enough. Please suggest.

[root@master ~]# subscription-manager list --available
+-------------------------------------------+
    Available Subscriptions
+-------------------------------------------+
Subscription Name:   30 Day Self-Supported OpenShift Enterprise, 2 Cores
                     Evaluation
Provides:            Red Hat OpenShift Enterprise Application Node
                     Red Hat Software Collections (for RHEL Server)
                     Red Hat JBoss A-MQ Clients
                     Red Hat Beta
                     Red Hat OpenShift Enterprise JBoss EAP add-on
                     Red Hat OpenShift Enterprise
                     JBoss Enterprise Application Platform
                     Red Hat OpenShift Enterprise JBoss A-MQ add-on
                     Red Hat OpenShift Enterprise JBoss FUSE add-on
                     JBoss Enterprise Web Server
                     Oracle Java (for RHEL Server)
                     Red Hat OpenShift Enterprise Client Tools
                     Red Hat Enterprise Linux Server
                     Red Hat Software Collections Beta (for RHEL Server)
                     Red Hat Enterprise Linux Atomic Host
                     Red Hat OpenShift Enterprise Infrastructure
SKU:                 SER0419
Contract:            10820031
Pool ID:             8a85f98150f52c210150f7364bb2607a
Provides Management: Yes
Available:           3
Suggested:           1
Service Level:       Self-Support
Service Type:        L1-L3
Subscription Type:   Standard
Ends:                12/10/2015
System Type:         Physical

**Comment by sdodson** [comment]
That looks right, have you enabled the repos in step #4 here?
https://docs.openshift.com/enterprise/3.0/install_config/install/prerequisites.html#software-prerequisites

```

subscription-manager repos --disable="*"
subscription-manager repos \
  --enable="rhel-7-server-rpms" \
  --enable="rhel-7-server-extras-rpms" \
  --enable="rhel-7-server-ose-3.0-rpms"

```

**Comment by kvjeevan** [comment]
Yes followed those steps:- 
subscription-manager repos --disable="*"
subscription-manager repos \
--enable="rhel-7-server-rpms" \
--enable="rhel-7-server-extras-rpms" \
--enable="rhel-7-server-optional-rpms" \
--enable="rhel-7-server-ose-3.0-rpms"

yum update -y

**Comment by kvjeevan** [comment]
Also, I am following this link - https://blog.openshift.com/setting-openshift-3-openstack/ while installing it.

**Comment by sdodson** [comment]
Ok, so just to re-group what error do you get now?

**Comment by kvjeevan** [comment]
TASK: [openshift_master_ca | Install the base package for admin tooling] ******
failed: [master.ose3.com] => {"changed": false, "failed": true, "rc": 0, "results": []}
msg: No Package matching 'openshift' found available, installed or updated

FATAL: all hosts have already failed -- aborting

**Comment by detiber** [comment]
What does `yum list available *openshift*` show?

And `yum repolist`?

**Comment by kvjeevan** [comment]
Here is the output of both commands:-

[root@master ~]# yum repolist
Loaded plugins: langpacks, product-id, subscription-manager
rhel-7-server-extras-rpms                                | 2.9 kB     00:00
rhel-7-server-optional-rpms                              | 2.9 kB     00:00
rhel-7-server-ose-3.0-rpms                               | 4.0 kB     00:00
rhel-7-server-rpms                                       | 3.7 kB     00:00
(1/3): rhel-7-server-ose-3.0-rpms/7Server/x86_64/group     |  104 B   00:00
(2/3): rhel-7-server-ose-3.0-rpms/7Server/x86_64/updateinf |  11 kB   00:00
(3/3): rhel-7-server-ose-3.0-rpms/7Server/x86_64/primary_d |  29 kB   00:00
repo id                                    repo name                      status
rhel-7-server-extras-rpms/x86_64           Red Hat Enterprise Linux 7 Ser   125
rhel-7-server-optional-rpms/7Server/x86_64 Red Hat Enterprise Linux 7 Ser 6,154
rhel-7-server-ose-3.0-rpms/7Server/x86_64  Red Hat OpenShift Enterprise 3    67
rhel-7-server-rpms/7Server/x86_64          Red Hat Enterprise Linux 7 Ser 7,728
repolist: 14,074

[root@master ~]# yum list available "openshift"
Loaded plugins: langpacks, product-id, subscription-manager
Available Packages
openshift.x86_64   3.0.2.0-0.git.33.f6b0f24.el7ose    rhel-7-server-ose-3.0-rpms
[root@master ~]#

**Comment by detiber** [comment]
@kvjeevan What happens if you manually try to install the package?

What does the generated config file for the installer (~/.config/openshift/installer.cfg.yml)  look like?

**Comment by tompa62** [comment]
Hi.
Any news on this? I have pretty much the same issue with 3.1 on RHEL 7.3. Tried the oo-install-ose script and atomic-openshift-installer. Below you'll see available openshift packages and yum repos. No "plain" openshift rpm available. And I'm registered to RedHat, have a subscription for Red Hat OpenShift Enterprise. 
# yum list available *openshift*
Loaded plugins: product-id, search-disabled-repos, subscription-manager
rhel-7-server-extras-rpms                                                                  | 3.4 kB  00:00:00     
rhel-7-server-ose-3.1-rpms                                                                 | 4.0 kB  00:00:00     
rhel-7-server-rpms                                                                         | 3.5 kB  00:00:00     
(1/9): rhel-7-server-extras-rpms/x86_64/updateinfo                                         | 142 kB  00:00:00     
(2/9): rhel-7-server-extras-rpms/x86_64/group                                              |  104 B  00:00:00     
(3/9): rhel-7-server-extras-rpms/x86_64/primary_db                                         | 199 kB  00:00:00     
(4/9): rhel-7-server-ose-3.1-rpms/x86_64/group                                             |  104 B  00:00:00     
(5/9): rhel-7-server-ose-3.1-rpms/x86_64/updateinfo                                        |  85 kB  00:00:00     
(6/9): rhel-7-server-rpms/7Server/x86_64/group                                             | 701 kB  00:00:00     
(7/9): rhel-7-server-rpms/7Server/x86_64/updateinfo                                        | 1.8 MB  00:00:00     
(8/9): rhel-7-server-ose-3.1-rpms/x86_64/primary_db                                        | 322 kB  00:00:00     
(9/9): rhel-7-server-rpms/7Server/x86_64/primary_db                                        |  34 MB  00:00:00     
Available Packages
jenkins-plugin-openshift.x86_64               0.6.41-1.el7aos            rhel-7-server-ose-3.1-rpms
jenkins-plugin-openshift-pipeline.x86_64 1.0.22-1.el7                  rhel-7-server-ose-3.1-rpms
jenkins-plugin-openshift-sync.x86_64      0.0.12-1.el7                   rhel-7-server-ose-3.1-rpms
nodejs-openshift-auth-proxy.noarch         0.0.20-1.el7aos             rhel-7-server-ose-3.1-rpms
openshift-elasticsearch-plugin.noarch      0.17.0.redhat_1-1.el7   rhel-7-server-ose-3.1-rpms

# yum repolist
Loaded plugins: product-id, search-disabled-repos, subscription-manager
repo id                                      
rhel-7-server-extras-rpms/x86_64             
rhel-7-server-ose-3.1-rpms/x86_64          
rhel-7-server-rpms/7Server/x86_64          

Regards, Tomas

**Pull request merged**
