### PR TITLE
Fixes for BZ#1450307

### PR DESCRIPTION
**Pull request by ashcrow**
- Always set proxy items in ``/etc/atomic.conf``
- Use ``/etc/systemd/system/container-engine.service.d`` for custom file.

https://bugzilla.redhat.com/show_bug.cgi?id=1450307

### CODE REVIEW

**Comment by ashcrow** [comment]
aos-ci-test

**Comment by ashcrow** [comment]
TIL about 🏄

**Comment by ashcrow** [comment]
[merge]

**Comment by sdodson** [comment]
aos-ci-test

**Comment by ashcrow** [comment]
flake https://github.com/openshift/origin/issues/13271

**Comment by ashcrow** [comment]
[merge]

**Comment by ashcrow** [comment]
Unrelated to my change.

```
fatal: [10.8.170.43]: FAILED! => {"changed": false, "failed": true, "msg": "OCP rpm version 3.5.5.15 is different from OCP image version 3.5.5.14"}
```

**Comment by ashcrow** [comment]
aos-ci-test

**Comment by ashcrow** [comment]
[merge]

**Comment by sdodson** [comment]
flake on https://github.com/openshift/origin/issues/14129

**Pull request merged**
