### PR TITLE
Configure persistence volumes for hawkular-metrics and Cassandra logs.

### PR DESCRIPTION
**Pull request by rubenvp8510**

### CODE REVIEW

**Comment by mwringe** [comment]
This needs to be a configurable option.

Do we even want to persist our logs like this? Or should that be up to the OpenShift Logging integration?

**Comment by mwringe** [comment]
It's not as simple as just adding in a PV here, we would need to also use a statefulset for this, which means reconfiguring how our components are deployed.

I also don't see anything in here with regards to what happens if the PV gets full. Does Wildfly automatically take care of this? or are we going to run into problems where the logs get full and we start to lose information?

The other problem is that our PVC is set to recycle, which means if someone deletes the pod, the logs are lost.

**Comment by rubenvp8510** [comment]
@mwringe I'm aware of the statefulset thing, we discussed this on IRC,  regards of the PV gets full, I configured wildly for log rotation.

About the recycle of the PVC , good point, I'll update this PR with new changes.

**Comment by rubenvp8510** [comment]
Just one question, the statefulset are official supported in OpenShift?

**Comment by mwringe** [comment]
We can use statefulsets in OpenShift now

**Pull request closed without merging**
