### PR TITLE
add rpm_q module to query rpm database

### PR DESCRIPTION
**Pull request by ibotty**
As discussed in the containerized-install pull req, that's a simple module to query whether a package is installed.

I will either wait until @sdodson's docker patch lands before I hook it up or if that gets merged first, he can use it himself.

### CODE REVIEW

**Comment by ibotty** [comment]
closed in favor of #808.

**Comment by ibotty** [comment]
argh. wrong tab.

**Comment by detiber** [comment]
@ibotty just getting back around to the PR/issue backlog. I'm not against pulling this in, but I think I would rather see something in place upstream and backport that rather than carry something unique here if possible.

**Comment by ibotty** [comment]
I don't know. I thought, the module could be fleshed out here until it is submitted to ansible modules.

For now, it's very basic, but solves the ugly in many is-it-available-on-atomic use cases.

**Comment by detiber** [comment]
@sdodson @abutcher ptal

**Comment by sdodson** [comment]
ok to test

**Comment by sdodson** [comment]
Two pylint errors we should correct, though the second one is silly we should fix the first.
```
C:  1, 0: Missing module docstring (missing-docstring)
C: 51, 4: Invalid variable name "rc" (invalid-name)
```

**Pull request merged**
