### PR TITLE
add ability to specify storage class for elasticsearch dynamic PVCs

### PR DESCRIPTION
**Pull request by mmckinst**
ref https://github.com/openshift/openshift-ansible/pull/8013

I suppose this should be added for 3.9 as well?

### CODE REVIEW

**Comment by mmckinst** [comment]
ref ref https://bugzilla.redhat.com/show_bug.cgi?id=1521218

**Comment by vrutkovs** [comment]
bot, test pull request

/ok-to-test

**Comment by jcantrill** [comment]
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1521218#c22

@ewolinetz Shouldn't we be deprecating 'dynamic storage'?  I though by defining storage classes and having the appropriate provisioner for the cluster you get 'dynamic storage' which is not the same as the feature implemented here?

**Comment by ewolinetz** [comment]
@jcantrill I'm not sure if we should deprecate dynamic storage yet. However, per my comment on the BZ this PR is not the correct approach. If we are able to specify a storage class for the 'dynamic' task, then it will not be a dynamic PVC. Dynamic PVCs leverage cloud providers to create and manage your PV, which I _think_ is different than using a storage class, though I'm not 100% certain of this.

I believe our operations team still uses dynamic PVCs, so we should not phase them out just yet.

/hold

**Comment by vrutkovs** [comment]
Master branch is closed! A major refactor is ongoing in devel-40. Changes for 3.x should be made directly to the latest release branch they're relevant to and backported from there.

**Pull request closed without merging**
