### PR TITLE
Bug 1419843 - Installation with ansible-2.2.1.0-2 may fail when set_fact for openshift_master

### PR DESCRIPTION
**Pull request by abutcher**
Reference class instead of `self.__class__` within super constructor to avoid calling self forever.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1419843

```
TASK [openshift_master : set_fact] *********************************************
task path: /root/openshift-ansible/roles/openshift_master/tasks/main.yml:146
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 126, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 443, in _execute
    self._task.post_validate(templar=templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/task.py", line 248, in post_validate
    super(Task, self).post_validate(templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/base.py", line 373, in post_validate
    value = templar.template(getattr(self, name))
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 427, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 383, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 583, in do_template
    res = j2_concat(rf)
  File "<template>", line 9, in root
  File "/root/openshift-ansible/filter_plugins/openshift_master.py", line 484, in translate_idps
    idp_inst = idp_class(api_version, idp) if idp_class is not None else IdentityProviderBase(api_version, idp)
  File "/root/openshift-ansible/filter_plugins/openshift_master.py", line 464, in __init__
    IdentityProviderOauthBase.__init__(self, api_version, idp)
  File "/root/openshift-ansible/filter_plugins/openshift_master.py", line 337, in __init__
    super(self.__class__, self).__init__(api_version, idp)
...
RuntimeError: maximum recursion depth exceeded while calling a Python object

fatal: [master1.abutcher.com]: FAILED! => {
    "failed": true
}

MSG:

Unexpected failure during module execution.
```

### CODE REVIEW

**Comment by abutcher** [comment]
aos-ci-test

**Comment by ashcrow** [comment]
Come on bot, you can do it!

**Comment by sdodson** [comment]
I see actual openshift-ansible code being executed so that's good, however it's slooooooooooooooow.
https://atomic-e2e-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/openshift-ansible-3-test-matrix/CONTAINERIZED=_NOT_containerized,OSE_VER=3.4,PYTHON=System-CPython-2.7,TOPOLOGY=openshift-cluster,TargetBranch=master,nodes=openshift-ansible-slave/847/console

**Comment by sdodson** [comment]
I'm confused as to why those tests were marked as failures, lets try this again.

**Comment by sdodson** [comment]
aos-ci-test

**Pull request merged**
