### PR TITLE
[RHPAM-859] - Include RHPAM templates in OpenShift release

### PR DESCRIPTION
**Pull request by spolti**

### CODE REVIEW

**Comment by spolti** [comment]
Please, do not merge it yet.

**Comment by vrutkovs** [comment]
bot, test pull request

**Comment by spolti** [comment]
Hi, feel free to merge it.

**Comment by vrutkovs** [comment]
/hold

waiting for 3.10 branch

**Comment by spolti** [comment]
Hi, can this get merged or there is something else that I missed?

**Comment by vrutkovs** [comment]
3.10 branch is not created yet, this would go into 3.11.0 and then be backported to 3.10.z

**Pull request merged**
