### PR TITLE
bring the docker udev workaround into openshift-ansible.git

### PR DESCRIPTION
**Pull request by joelddiaz**

### CODE REVIEW

**Comment by detiber** [comment]
Any reason we wouldn't make this a part of the docker role as opposed to a separate role?

**Comment by joelddiaz** [comment]
@detiber @twiest not sure we want it to be enabled as a default setting

**Comment by detiber** [comment]
@joelddiaz understood, I was thinking of having it be triggered based on a variable that is set through the inventory or group_vars/host_vars.

roles/workaround_docker_udev_timeout/handlers/main.yml could be added to roles/docker/handlers/main.yml
roles/workaround_docker_udev_timeout/vars/main.yml could be added to roles/docker/vars/main.yml
roles/workaround_docker_udev_timeout/tasks/main.yml could become roles/docker/tasks/udev_workaround.yml

Then you could add something like this to roles/docker/tasks/main.yml:
```
- include: udev_workaround.yml
  when: docker_udev_workaround | default(false)
```

**Comment by joelddiaz** [comment]
@detiber incorporated the udev workaround into the docker role with an off-by-default setting

**Comment by detiber** [comment]
@joelddiaz thanks, I think that is much cleaner. :+1: from me.

**Comment by twiest** [comment]
:+1:

**Pull request merged**
