### PR TITLE
Don't set empty HTTP_PROXY, HTTPS_PROXY, NO_PROXY values

### PR DESCRIPTION
**Pull request by sdodson**

### CODE REVIEW

**Comment by sdodson** [comment]
@andrewklau @brenton PTAL

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by brenton** [comment]
@detiber This worked in my environment.  :+1:  from me.

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
@sdodson please rebase

**Comment by brenton** [comment]
I remember someone mentioning a problem with CI.  Do we have any idea why the test status isn't being reported correctly?

**Comment by sdodson** [comment]
aos-ci-test

**Comment by brenton** [comment]
Looks like CI is happy now.

**Comment by sdodson** [comment]
Lets merge!

**Pull request merged**
