### PR TITLE
Add python2-crypto package to images

### PR DESCRIPTION
**Pull request by smarterclayton**
Caused GCP break for jobs

@sdodson

### CODE REVIEW

**Comment by sdodson** [comment]
Can you pull in https://github.com/openshift/openshift-ansible/pull/6983/commits/c9f441986dd8c39f40bf1d0519d9f38a31060a59 so we also fix this for rpm based installs outside of the container?

**Comment by smarterclayton** [comment]
@sdodson looks like we have another break https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/6982/test_pull_request_openshift_ansible_extended_conformance_gce/288/

**Comment by smarterclayton** [comment]
GCP broke while we were broken

**Comment by sdodson** [comment]
https://github.com/openshift/openshift-ansible/pull/6989 to address the vsphere problems

**Comment by smarterclayton** [comment]
You can fold this into yours.

**Comment by sdodson** [comment]
provisioning of the cluster was successful, merging.

**Pull request merged**
