### PR TITLE
Bug 1767238: make kibana inherit all no proxy parameters

### PR DESCRIPTION
**Pull request by Nebzer0**
Fix BZ 1767238

### CODE REVIEW

**Comment by sdodson** [comment]
/retitle  Bug 1767238: make kibana inherit all no proxy parameters

**Comment by sdodson** [comment]
You've tested that this fixes the problem?

Does the client library used by Kibana actually respect CIDRs in no_proxy? It's generally not widely supported, for instance we had to add support for it to the API server years before that support was in Golang.

**Comment by sdodson** [comment]
I'm sure they're just lacking this relatively recent fix https://github.com/openshift/openshift-ansible/pull/11971

**Comment by ewolinetz** [comment]
+1 to @sdodson 's comment. That sounds like the same issue that #11971 was created to resolve.

That pr's bz was https://bugzilla.redhat.com/show_bug.cgi?id=1757501 and is still in `MODIFIED` meaning we haven't built/released it yet. @bostrt can you verify whether #11971 is all that was needed?

**Comment by bostrt** [comment]
Yes, you are correct. Looks like we were reviewing a slightly out-of-date codebase while trying to come up with a patch.

**Comment by sdodson** [comment]
/close 
Dupe of #11971

**Pull request closed without merging**
