### PR TITLE
pull in recent jenkins template updates

### PR DESCRIPTION
**Pull request by gabemontero**
@sdodson @bparees ptal / fyi

per our recent discussions ... here is the 3.9 version

### CODE REVIEW

**Comment by sdodson** [comment]
I'll merge this as soon as @bparees approves
/cherrypick release-3.9

**Comment by bparees** [comment]
lgtm

@sdodson i don't think you need the cherrypick, this PR is against release-3.9 already.

**Comment by gabemontero** [comment]
Correct it is against the release-3.9 branch, where our origin/release-3.9 PR merged last night

I'll craft a separate PR for master when the origin/master PR merges

**Comment by bparees** [comment]
> I'll craft a separate PR for master when the origin/master PR merges

you shouldn't need to, I believe @sdodson already syncs that on a regular basis during a release.

**Comment by gabemontero** [comment]
hey @sdodson - is there merge button capability if all these test failures due to be various setup / environmental flakes persist?

**Comment by sdodson** [comment]
Yeah no worries, those are all CI snafu.

**Comment by gabemontero** [comment]
thanks man

**Pull request merged**
