### PR TITLE
Revert "Add dnf support"

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Reverts openshift/openshift-ansible#5101

/cc @sdodson @rhcarvalho @jhadvig

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
[test]

**Comment by stevekuznetsov** [comment]
aos-ci-test

**Comment by stevekuznetsov** [comment]
This doesn't fix it either.

**Comment by maxamillion** [comment]
Why was this reverted?

**Comment by stevekuznetsov** [comment]
Revert never merged.

**Comment by maxamillion** [comment]
oh sure enough, nevermind me

**Pull request closed without merging**
