### PR TITLE
Bump documented openshift_release for 1.4/3.4.

### PR DESCRIPTION
**Pull request by dgoodwin**
Fixes Bug 1389137

### CODE REVIEW

**Comment by sdodson** [comment]
> LGTM based off of the Bugzilla. +1 if the tests pass

bugzilla?

**Comment by tbielawa** [comment]
> bugzilla?

https://bugzilla.redhat.com/show_bug.cgi?id=1386333

**Comment by sdodson** [comment]
Editted description so that bot should post a comment when this merges. Lets see.

**Comment by sdodson** [comment]
Hmm, maybe it's got ot be in the commit message itself, oh well.

**Comment by dgoodwin** [comment]
That'll be cool if it works.

**Pull request merged**
