### PR TITLE
Add pyOpenSSL openshift-ansible dep

### PR DESCRIPTION
**Pull request by sdodson**
This regressed in 801779eeb6f6308f81ae7c48409de7686c04a0aa
Related #4617

### CODE REVIEW

**Comment by sdodson** [comment]
@jmainguy PTAL

**Comment by DanyC97** [comment]
@sdodson i suspect we then need to make sure in CentOS PaaS repo this rpm is present, correct ?

**Comment by sdodson** [comment]
> @sdodson i suspect we then need to make sure in CentOS PaaS repo this rpm is present, correct ?

It's part of the base RHEL/Centos package set it shouldn't be a problem.

**Pull request merged**
