### PR TITLE
Fixing 'unscheduleable' typo

### PR DESCRIPTION
**Pull request by brenton**

### CODE REVIEW

**Comment by brenton** [comment]
@detiber, we have a bit of a mess here.  It looks like at some point in time I introduced a typo that has made it's way in to a lot of places.  That's only going to mess things up for people.  What would be a decent way to be backwards compatible and accept both `openshift_unscheduleable` and the correctly spelled `openshift_unschedulable`?

**Comment by brenton** [comment]
@detiber, also, related to this is seems at some point in time our default behavior changed.  It seems like with https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_facts/library/openshift_facts.py#L344 all Masters that have Nodes on them will default to being unschedulable.  I know originally with OSE we didn't want to surprise admins with this new setting so we decided to only set a node unschedulable only if `openshift_schedulable=False` is explicitly set in the inventory.

It seems people aren't complaining loudly about this change so I'd really like to know what you think is best going forward.  We could revert the change or simply add the logic to `atomic-openshift-installer` to correctly set it to `True` when it is explicitly needed.  That logic is a big of a mess in the installer but I'm sure we could find a way to clean it up.

cc @dak1n1

**Comment by detiber** [comment]
@brenton I believe we already handle both spellings...  

also, I would prefer to keep the current default, since it is the desired behavior for an HA installation with the installer explicitly setting schedulable to true for all-in-one deployments...

**Comment by detiber** [comment]
@brenton only references I see to the misspelled scheduleable outside of the utils directory is as a secondary default to openshift_schedulable.

**Comment by dgoodwin** [comment]
@detiber @brenton I will update the logic in the installer to explicitly set openshift_schedulable=True on each master, if those masters are the only nodes in play.

**Comment by brenton** [comment]
@detiber  Ahh, I've removed my changes from the playbooks and have limited the fix to only the example hosts file and atomic-openshift-utils.

@dgoodwin, will this PR cause a conflict for https://github.com/openshift/openshift-ansible/pull/999 ? If so, you could just cherry-pick my commit in to your PR and we'd just merge it together.

**Comment by dgoodwin** [comment]
IIRC I went with the new spelling in a few places where I hit it, so go ahead and merge, I can deal with any conflicts that come up.

**Comment by brenton** [comment]
Ok, I'll merge this now then and you can just rebase.

**Pull request merged**
