### PR TITLE
fix ca cert deploy for 3.10 addresses bz 1585978

### PR DESCRIPTION
**Pull request by newgoliath**
https://bugzilla.redhat.com/show_bug.cgi?id=1585978

```
TASK [Update node client kubeconfig CA data] ********************************************************************************************************************************
fatal: [ec2-34-207-246-134.compute-1.amazonaws.com]: FAILED! => {"changed": false, "failed": true, "msg": "[Errno 2] No such file or directory: '/etc/origin/node/system:node:ip-172-18-0-157.ec2.internal.kubeconfig'"}
fatal: [ec2-52-90-247-129.compute-1.amazonaws.com]: FAILED! => {"changed": false, "failed": true, "msg": "[Errno 2] No such file or directory: '/etc/origin/node/system:node:ip-172-18-11-10.ec2.internal.kubeconfig'"}
```

### CODE REVIEW

**Comment by sdodson** [comment]
/lgtm
thanks

**Comment by sdodson** [comment]
/ok-to-test

Was this sufficient to resolve all problems with the CA redeploy playbook or where there other problems encountered after resolving this?

**Comment by DanyC97** [comment]
@sdodson does this needs to be cherry picked into 3.10 too ?  thx

**Pull request merged**
