### PR TITLE
Provide backup_ext functionality keeping backwards compatibility.

### PR DESCRIPTION
**Pull request by kwoodson**
Updating the backup file extension to be configurable.  This allows the user to specify whatever they want for the value.

### CODE REVIEW

**Comment by sdodson** [comment]
What's the motivation to not have timestamped backups by default? Accumulation of config files?

**Comment by kwoodson** [comment]
@sdodson, yes.  The configuration management loop runs multiple times per day and these files would accumulate.  Also, this provides functionality to allow the user to specify their backup file.

**Comment by sdodson** [comment]
A timestamped backup per seems more in line with the behavior or lineinfile or template. The files are getting updated each time due to PyYAML parsing deficiencies?

```
$ ansible-console -i ~/ansible-ose ose3-master.example.com
root@ose3-master.example.com (1)[f:20]$ lineinfile path="/etc/etcd/etcd.conf" line="test" backup="yes"
ose3-master.example.com | SUCCESS => {
    "backup": "/etc/etcd/etcd.conf.35091.2018-04-15@14:22:56~", 
    "changed": true, 
    "failed": false, 
    "msg": "line added"
}
root@ose3-master.example.com (1)[f:20]$ lineinfile path="/etc/etcd/etcd.conf" line="test2" backup="yes"
ose3-master.example.com | SUCCESS => {
    "backup": "/etc/etcd/etcd.conf.35446.2018-04-15@14:22:59~", 
    "changed": true, 
    "failed": false, 
    "msg": "line added"
}
```

**Comment by kwoodson** [comment]
@sdodson 
> A timestamped backup per moduel call seems more in line with the behavior or lineinfile or template. The files are getting updated each time due to PyYAML parsing deficiencies?

I'm not sure what that script does.  It looks like `lineinfile` is changing each time?  If this calls yedit and yedit is changing each time then that's a bug. If using pyyaml and it is performing an update the output will be updated.  If there are 0 change then 0 changes get written.  Formatting is not an exception.

According to the documentation for `lineinfile`, https://docs.ansible.com/ansible/2.4/lineinfile_module.html the `backup` option  is `false` by default.  If the backup is desired then it creates a timestamped version.

Yedit has the `backup` turned on by default.  Since we wanted to ensure that we didn't break anything.  At this point I'd be fine with turning the `default` to `false`.  If this is done, then I'm fine keeping the module doing the date string as the default and then allow it to be overridden.

**Comment by sdodson** [comment]
@fabianvf @mtnbikenc Opinion on this? I'm fine with making yedit default to not backing up and leaving the timestamped backups when it's enabled. I think backing up to a static suffix is problematic as you only maintain a diff of the very last change to be applied and we often apply several changes over the course of playbook execution.

**Comment by kwoodson** [comment]
@sdodson, I have updated it to _not_ backup by default.  Then takes datetime string as default suffix.

**Comment by fabianvf** [comment]
That approach makes the most sense to me

**Comment by sdodson** [comment]
lgtm, tox errors outstanding though

**Comment by sdodson** [comment]
@kwoodson Yeah, travis is flakey as of late for some reason it's unable to install ansible via pip on ocassion.

from ci/openshift-jenkins/tox
```
./roles/lib_utils/library/yedit.py:228:1: M511 - mutable default arg of type Call

roles/lib_utils/src/test/integration/yedit.yml:
  14:1      warning  comment not indented like content  (comments-indentation)

Found errors while generating module code.
ERROR: InvocationError for command '/data/src/github.com/openshift/openshift-ansible/.tox/py27-generate_validation/bin/python setup.py generate_validation' (exited with code 1)
```

**Comment by kwoodson** [comment]
The generation validation fails since lib_openshift uses the yedit python library.  Regenerating the lib_openshift so that it can use the latest.

**Comment by michaelgugino** [comment]
@kwoodson My comments were in response to this statement:

> The configuration management loop runs multiple times per day and these files would accumulate. Also, this provides functionality to allow the user to specify their backup file as well as maintaining backwards compatibility.

If that is the case, it sounds like yedit was not idempotent.  I have not checked if it is or not.  Are you saying that config loop is changing values multiple times per day, every day?  In any case, I was under the impression that this was being caused by yedit not being idempotent on each run, if that's not the case, then we're good; I don't know off hand how idempotent all of our custom bits are.

**Pull request merged**
