### PR TITLE
[WIP] Bug 1488367: Create registry certificates fails when openshift_hosted_routers have a ca called ca.crt 

### PR DESCRIPTION
**Pull request by abutcher**
https://bugzilla.redhat.com/show_bug.cgi?id=1488367

### CODE REVIEW

**Comment by abutcher** [comment]
This will need a few more changes. Router creation relies on the certs being in `/etc/origin/master` atm.

**Comment by vrutkovs** [comment]
Master branch is closed! A major refactor is ongoing in devel-40. Changes for 3.x should be made directly to the latest release branch they're relevant to and backported from there.

**Pull request closed without merging**
