### PR TITLE
Consolidate etcd common role

### PR DESCRIPTION
**Pull request by ingvagabund**
The last PR toward a single etcd role

### CODE REVIEW

**Comment by ingvagabund** [comment]
The `playbooks/byo/openshift-cluster/redeploy-certificates.yml` fails to finish with the following error:
```sh
PLAY [Restart nodes] *************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************************************
ok: [10.8.173.86]

TASK [Restart docker] ************************************************************************************************************************************************************************************************************************
changed: [10.8.173.86]

TASK [Update docker facts] *******************************************************************************************************************************************************************************************************************
ok: [10.8.173.86]

TASK [Restart containerized services] ********************************************************************************************************************************************************************************************************
skipping: [10.8.173.86] => (item=etcd_container) 
skipping: [10.8.173.86] => (item=openvswitch) 
skipping: [10.8.173.86] => (item=atomic-openshift-master-api) 
skipping: [10.8.173.86] => (item=atomic-openshift-master-controllers) 
skipping: [10.8.173.86] => (item=atomic-openshift-node) 

TASK [Wait for master API to come back online] ***********************************************************************************************************************************************************************************************
skipping: [10.8.173.86]

TASK [restart node] **************************************************************************************************************************************************************************************************************************
fatal: [10.8.173.86]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service atomic-openshift-node: Job for atomic-openshift-node.service failed because the control process exited with error code. See \"systemctl status atomic-openshift-node.service\" and \"journalctl -xe\" for details.\n"}
```

I have deployed 3.6 and 3.7 cluster from the master and run the `redeploy-certificates.yml` playbook from the master and from the commit before I touched the etcd roles and started refactoring. The certificates re-deployment failed all cases with the same error. Meaning, the playbook is broken for some time.

Besides the etcd certificates re-deployment (which is touched by this PR and the one consolidating certificates roles) tasks passed without any isssue.

@sdodson So this PR can be merged as it is.

**Comment by sdodson** [comment]
I'd like @abutcher to check these changes as it's closely related to work he's done in the past and is working on right now.

**Pull request merged**
