### PR TITLE
Provide cacert when performing health checks

### PR DESCRIPTION
**Pull request by abutcher**
@sdodson p t a l

### CODE REVIEW

**Comment by abutcher** [comment]
aos-ci-test

**Comment by sdodson** [comment]
Turns out I had a bad policy which is what spawned this PR, regardless I think this is a fine PR and I can't see any reason not to go ahead with it.

**Comment by abutcher** [comment]
@brenton

**Comment by detiber** [comment]
:+1: from me

**Comment by sdodson** [comment]
aos-ci-test

**Pull request merged**
