### PR TITLE
Add s3 and block uninstall sections as well

### PR DESCRIPTION
**Pull request by SaravanaStorageNetwork**
Signed-off-by: Saravanakumar Arumugam <sarumuga@redhat.com>

### CODE REVIEW

**Comment by SaravanaStorageNetwork** [comment]
@jarrpa  Please check

**Comment by SaravanaStorageNetwork** [comment]
bot, test pull request

**Comment by jarrpa** [comment]
/ok-to-test
/lgtm
bot, test pull request

**Comment by jarrpa** [comment]
@sdodson Can we get a pass on the CI tests since this isn't touched by anything besides tox?

**Comment by sdodson** [comment]
Looks like installation was successful and the job failed on an e2e flake. Merging.

**Pull request merged**
