### PR TITLE
OCPBUGS-41786: Manully cherry-pick the changes for updating Dockerfile to centos9 stream

### PR DESCRIPTION
**Pull request by barbacbd**
Manully cherry-pick the changes for updating Dockerfile to centos9 stream in 4.13

### CODE REVIEW

**Comment by barbacbd** [comment]
For the backport of https://github.com/openshift/openshift-ansible/pull/12512 to 4.13

**Comment by barbacbd** [comment]
/hold 

Waiting on https://github.com/openshift/release/pull/56566

**Comment by gpei** [comment]
@barbacbd Thanks for the PR, all tests passed with this.

**Pull request merged**
