### PR TITLE
Skip "At least one master is schedulable" when no masters are set in oo_masters_to_config

### LINKED ISSUE #8353: azure image builds broken after `install: verify that at least one master is schedulable`
```
TASK [openshift_sanitize_inventory : At least one master is schedulable] *******
Friday 11 May 2018  19:35:09 +0000 (0:00:00.030)       0:07:22.819 ************ 
fatal: [40.76.65.11]: FAILED! => {"msg": "The conditional check 'l_master_schedulable | length > 0' failed. The error was: error while evaluating conditional (l_master_schedulable | length > 0): 'dict object' has no attribute u'oo_nodes_to_bootstrap'\n\nThe error appears to have been in '/usr/share/ansible/openshift-ansible/roles/openshift_sanitize_inventory/tasks/main.yml': line 101, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: At least one master is schedulable\n  ^ here\n"}
```

relevant PRs are:
https://github.com/openshift/openshift-ansible/pull/7911
https://github.com/openshift/openshift-ansible/pull/8341

### PR DESCRIPTION
**Pull request by vrutkovs**
Fixes #8353 

This would fix failing GCP test and Azure image building

### CODE REVIEW

**Comment by sdodson** [comment]
Merge this as soon as the GCP test goes green.

**Comment by vrutkovs** [comment]
GCP flake

/test gcp

**Comment by sdodson** [comment]
post install flake, where as prior to this change install was failing before making it to e2e, merging to unblock the queue

**Pull request merged**
