### PR TITLE
[KIECLOUD-585] Update RHPAM and RHDM templates and imagestreams on Op…

### PR DESCRIPTION
**Pull request by davidesalerno**
…enShift Service Catalog for 7.12.1 release

Signed-off-by: Davide Salerno <dsalerno@redhat.com>

See: https://issues.redhat.com/browse/KIECLOUD-585

### CODE REVIEW

**Comment by spolti** [comment]
hi @patrickdillon, can you please take a look on this?
About the Bugzilla reference, I think we don't need it, for previous time we have update the app templates, we didn't have to create it.

**Comment by spolti** [comment]
@jstuever Hi, can you please take a look?

**Comment by davidesalerno** [comment]
@jstuever @patrickdillon It seems that there are 2 steps in the CI that are broken, is there someone that could help us?
-

**Comment by patrickdillon** [comment]
/hold

to prevent test from spinning while the image is broken

**Pull request merged**
