### PR TITLE
cleanup roles after roles move to openshift-tools

### PR DESCRIPTION
**Pull request by joelddiaz**
things left behind unchanged even though they were copied:

playbooks/adhoc/*
roles/dns
roles/kube_nfs_volumes
roles/os_update_latest

### CODE REVIEW

**Comment by joelddiaz** [comment]
@detiber please give this the first review to see if there's anything on this list that should stay in openshift-ansible

**Comment by detiber** [comment]
@joelddiaz lgtm

**Comment by joelddiaz** [comment]
@sdodson @abutcher this PR is the move of roles out of openshift-ansible into openshift-tools. please review.
I'm told amadeaus should also review this: @menren @lhuard1A

**Comment by sdodson** [comment]
aos-ci-test

**Comment by abutcher** [comment]
lgtm

**Comment by sdodson** [comment]
LGTM

**Comment by joelddiaz** [comment]
@detiber @sdodson @abutcher : added the removal of inventory/multi_inventory.* to this PR

@menren @lhuard1A : bump

**Comment by sdodson** [comment]
aos-ci-test

**Comment by menren** [comment]
:+1:

**Comment by abutcher** [comment]
:+1:

**Comment by lhuard1A** [comment]
Hi there,

Thanks for the notification. (And thanks for having kept `roles/dns` because I remember having difficulties starting OpenShift on our OpenStack without it.)

**Comment by joelddiaz** [comment]
@sdodson @detiber just want to get your +1s (with the last addition of the "remove multi-inventory" piece) before merging this

**Comment by sdodson** [comment]
:+1:

**Comment by detiber** [comment]
@joelddiaz lgtm :shipit:

**Pull request merged**
