### PR TITLE
[RHPAM-1241] - Include RHPAM templates in OpenShift release

### PR DESCRIPTION
**Pull request by spolti**
Signed-off-by: Filippe Spolti <fspolti@redhat.com>

### CODE REVIEW

**Comment by michaelgugino** [comment]
@sdodson

**Comment by spolti** [comment]
Hi, is this PR ready to get merged or do I need to do something else?

**Comment by sdodson** [comment]
> Hi, is this PR ready to get merged or do I need to do something else?

it's fine, sorry for the delay

**Pull request merged**
