### PR TITLE
[3.6] Force reconciliation of role for 3.6

### PR DESCRIPTION
**Pull request by sdodson**
This is needed because in 3.6 we cannot reconcile non-cluster roles in the
bootstrap reconciliation code.  In 3.7 this is taken care of in code.

Adds version_gte_3_7 facts and Backports https://github.com/openshift/openshift-ansible/pull/5617

### CODE REVIEW

**Comment by simo5** [comment]
/hold
please check th changes on the PR in master

**Comment by sdodson** [comment]
@simo5 ok, I've been able to confirm that this works for both positive and negative cases.

**Comment by sdodson** [comment]
That last test looks like it failed conformance tests while still running 1.5. I was hoping to at least see the ansible tasks execute if not a green test run.

**Comment by simo5** [comment]
@sdodson I saw a bunch of router errors, and did not investigate

**Comment by sdodson** [comment]
@simo5 Added warning notification.

**Pull request merged**
