### PR TITLE
[KIECLOUD-460] - Update RHPAM and RHDM templates and imagestreams on …

### PR DESCRIPTION
**Pull request by spolti**
…OpenShift Service Catalog for 7.9.1 release

Signed-off-by: spolti <fspolti@redhat.com>

### CODE REVIEW

**Comment by mtnbikenc** [comment]
/hold
images is broken because of pip dependencies.  azure-cli-core requires PyJWT.  Newly released PyJWT 2.0 dropped Python 2 support.  https://github.com/jpadilla/pyjwt/releases/tag/2.0.0

We need to investigate further.

**Comment by spolti** [comment]
Hi, any updates on this?

**Comment by mtnbikenc** [comment]
Images job fixed by https://github.com/openshift/openshift-ansible/pull/12289

**Comment by mtnbikenc** [comment]
Images job should be fixed.
/hold cancel

**Pull request merged**
