### PR TITLE
[wip]add openshift.master.pod total count

### PR DESCRIPTION
**Pull request by BlueShells**
add the total count of pod

### CODE REVIEW

**Comment by BlueShells** [comment]
@twiest ,could you review this for me I just added another item

**Comment by twiest** [comment]
:+1:

**Comment by jaryn** [comment]
Can one of the admins verify this patch?

**Comment by jaryn** [comment]
Can one of the admins verify this patch?

**Comment by arilivigni** [comment]
Testing job has been triggered.

**Comment by arilivigni** [comment]
Internal Jenkins error during triggering.
 No test results found.

**Comment by tbielawa** [comment]
This PR has been inactive for quite some time. Please update, fix any conflicts, and reopen this PR if this is still a priority you would like to see action on.

**Pull request closed without merging**
