### PR TITLE
Fixes #5174: Remove unnecessary passlib check

### LINKED ISSUE #5174: Metrics fail to install when the control host runs on Mac OS X
#### Description

When installing the metrics component as explained [here](https://docs.openshift.com/container-platform/3.6/install_config/cluster_metrics.html), if the control host runs on Mac OS X and Ansible has been installed using brew, **the installation fails**. 

##### Version

```
$ ansible --version
ansible 2.3.0.0
  config file = /Users/nmasse/git/OpenShift-Lab/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]

$ git describe
openshift-ansible-3.6.173.0.10-1
```

##### Steps To Reproduce
```
$ ansible-playbook openshift-ansible/byo/openshift-cluster/openshift-metrics.yml \
   -e openshift_metrics_install_metrics=True \
   -e openshift_metrics_hawkular_hostname=hawkular-metrics.openshift.test
```

##### Expected Results

Playbook completes successfully

##### Observed Results

The playbook fails when checking for the passlib library that is a requirement of the `htpasswd` module : 
```
TASK [openshift_metrics : Check that python-passlib is available on the control host] ******************************************************************************************************************
fatal: [openshift36.openshift.test]: FAILED! => {
    "assertion": "'not installed' not in passlib_result.stdout", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true, 
    "msg": "python-passlib rpm must be installed on control host"
}
	to retry, use: --limit @/Users/nmasse/git/OpenShift-Lab/allinone.retry
```

##### Additional Information

passlib **is** installed, but not globally : 
```
$ python -c 'import passlib' 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named passlib

$ PYTHONPATH=/usr/local/Cellar/ansible/2.3.0.0_2/libexec/lib/python2.7/site-packages/ python -c 'import passlib' 

```

The current pre-requisites check assumes that passlib is installed globally, but in some cases it is installed in an alternate site-package. Especially, this is the case when using ansible on Mac OS X, when installed through brew : Ansible is installed, along with passlib.

### PR DESCRIPTION
**Pull request by jkroepke**
Follow up: https://github.com/openshift/openshift-ansible/pull/5175

As https://github.com/openshift/openshift-ansible/pull/5175#discussion_r202629249 this check can be removed.

### CODE REVIEW

**Comment by vrutkovs** [comment]
bot, test pull request

**Comment by jkroepke** [comment]
@michaelgugino  any status here?

**Comment by csheremeta** [comment]
Can we get this backported to 3.9?

**Pull request merged**
