### PR TITLE
[3.2] 1480129 Remove Jinja delimiters and double quotes from when conditions

### PR DESCRIPTION
**Pull request by mtnbikenc**
Bug 1480129

### CODE REVIEW

**Comment by sdodson** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
Fixed typo.

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
@sdodson As best I can tell logs are showing the install is completing successfully, however, post jobs are failing.  Should I run aos-ci-test again?  I looked back over past merges to this branch and found only one successful test.

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
Containerized installs seem to keep failing tests.  Testing locally.

**Comment by mtnbikenc** [comment]
@sdodson The containerized failure appears to be unrelated to the changes in this PR.  I did some searching on this and it looks like an old bug.  Should I work to get CI fixed on the release-1.2 branch?

```
Aug 29 10:52:54 ip-172-18-15-156.ec2.internal systemd[1]: Starting atomic-openshift-node.service...
Aug 29 10:52:54 ip-172-18-15-156.ec2.internal atomic-openshift-node[3307]: Error response from daemon: Driver devicemapper failed to remove root filesystem a0cbfbfdf6de98528499632f6d9f1c262e0130e281e8211b52f83d9b35d2c410: failed to remove device 96f10c7174c6b5bd1b0ed47d29d451f20a73c4df9c10f30c82e0c9d084026f4a:devicemapper: Error running DeleteDevice dm_task_run failed
Aug 29 10:52:54 ip-172-18-15-156.ec2.internal atomic-openshift-node[3317]: /usr/bin/docker-current: Error response from daemon: Conflict. The name "/atomic-openshift-node" is already in use by container a0cbfbfdf6de98528499632f6d9f1c262e0130e281e8211b52f83d9b35d2c410. You have to remove (or rename) that container to be able to reuse that name..
Aug 29 10:52:54 ip-172-18-15-156.ec2.internal atomic-openshift-node[3317]: See '/usr/bin/docker-current run --help'.
Aug 29 10:52:54 ip-172-18-15-156.ec2.internal systemd[1]: atomic-openshift-node.service: main process exited, code=exited, status=125/n/a
```

**Comment by sdodson** [comment]
There's an origin github issue on this I'm sure but the search service seems down.

**Pull request merged**
