### PR TITLE
Fix reg console bp 3.10

### PR DESCRIPTION
**Pull request by michaelgugino**
Backports https://github.com/openshift/openshift-ansible/pull/9644

Backports https://github.com/openshift/openshift-ansible/pull/9447

### CODE REVIEW

**Comment by sdodson** [comment]
`     Message:  The task includes an option with an undefined variable. The error was: 'openshift_cluster_monitoring_operator_node_selector' is undefined` from the gcp test logs

**Comment by vrutkovs** [comment]
@sdodson yes, https://github.com/openshift/openshift-ansible/pull/9691 should fix that, PTAL

**Pull request merged**
