### PR TITLE
bug: Fix boolean conversion in idp

### LINKED ISSUE #2454: Invalid boolean conversion for extraAuthorizeParameters include_granted_scopes
When trying to define an OpenIDConnect ID provider in Ansible hosts by setting include_granted_scopes. If the value is “true” with the double quotes then the definition is invalid. 

For instance extraAuthorizeParameters': {'include_granted_scopes': ‘\”true\"'} results in include_granted_scopes: false in the configuration.

The issue seems to be that the value of include_granted_scopes is evaluated as ansible_bool.

https://github.com/openshift/openshift-ansible/blob/b8e72ea2143834317043f19cbc3dddf8ad9047a5/filter_plugins/openshift_master.py#L388

### PR DESCRIPTION
**Pull request by ashcrow**
Forward port of https://github.com/openshift/openshift-ansible/pull/2896

Work originally done by @smunilla

Closes #2454

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1488505

### CODE REVIEW

**Comment by sdodson** [comment]
aos-ci-test

**Comment by enj** [comment]
Both this and #5350 seem fine to me.  I will let @smunilla / @sdodson decide if they have a preference.

**Comment by enj** [comment]
Though I do see how this may work correctly in situations such as https://github.com/openshift/openshift-ansible/pull/5350#issuecomment-328654412 whereas #5350 may not.

**Comment by enj** [comment]
Some tests would be nice 😄

**Comment by mtnbikenc** [comment]
My preference is #5350 over this PR.

**Comment by sdodson** [comment]
Closed in favor of #5350

**Pull request closed without merging**
