### PR TITLE
openshift_sanitize_inventory: disallow conflicting deployment types

### PR DESCRIPTION
**Pull request by sosiouxme**
https://github.com/openshift/openshift-ansible/issues/3843#issuecomment-292572070 for background.

### CODE REVIEW

**Comment by sosiouxme** [comment]
aos-ci-test

**Comment by sosiouxme** [comment]
@stevekuznetsov @sdodson any idea why aos-ci-jenkins/OS_unit_tests hasn't completed here? Can you kick it off again or something?

**Comment by stevekuznetsov** [comment]
We migrated the `tox` tests into the [`test_pull_request_openshift_ansible_tox`](https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible_tox/) Jenkins job but for what it's worth it's also in the Travis output

**Comment by sosiouxme** [comment]
aos-ci-test

**Comment by sosiouxme** [comment]
@stevekuznetsov I'm not concerned where the unit tests run, but rather that the aos-ci-jenkins/OS_unit_tests test is required to merge and doesn't seem to be finishing.

**Comment by stevekuznetsov** [comment]
It isn't required for merge in that the status won't be checked. It's required for merge in that it will run in Jenkins and if it fails there you will not merge.

**Comment by sosiouxme** [comment]
Heh, OK. Well let's try a [merge] already then.

**Comment by sosiouxme** [comment]
Looks like flake https://github.com/openshift/origin/issues/12544
[merge] again

**Pull request merged**
