### PR TITLE
added a empty file to the contiv empty dir. This allows contiv to be vendored in git

### PR DESCRIPTION
**Pull request by mwoodson**

### CODE REVIEW

**Comment by mwoodson** [comment]
@sdodson @kwoodson 

This will allow ops to vendor the contiv dir appropriately.

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Comment by sdodson** [comment]
[merge]

**Comment by kwoodson** [comment]
[merge]

**Comment by kwoodson** [comment]
[test]

**Comment by kwoodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
flake on https://github.com/openshift/origin/issues/13739
[merge]

**Comment by kwoodson** [comment]
flake https://github.com/openshift/origin/issues/13271

**Comment by kwoodson** [comment]
[merge]

**Comment by sdodson** [comment]
I've been told the CI issue is fixed.

[merge]

**Comment by kwoodson** [comment]
flake https://github.com/openshift/origin/issues/13271

**Comment by kwoodson** [comment]
[merge]

**Pull request merged**
