### PR TITLE
Configure Kuryr CNI daemon

### PR DESCRIPTION
**Pull request by dulek**
Kuryr CNI daemon is scalability improvement that moves watching K8s API
and VIF plugging into a separate entity called kuryr-daemon.
Kuryr-daemon will run in a container and serve requests from
kuryr-driver.

### CODE REVIEW

**Comment by dulek** [comment]
This is WiP, need to wait for upstream Kuryr patches to be merged.

**Comment by dulek** [comment]
I've rebased the patch and tested it with latest Kuryr upstream merges. Seems to work fine.

@celebdor why were you disabling "plugins" in https://github.com/openshift/openshift-ansible/blob/eb6b20fc9183cc2aae424c72efd1191b99110a93/roles/kuryr/tasks/node.yaml#L43 ? Looks like current origin-node service will never be started when plugins is disabled. I needed to remove it, otherwise systemd kept restarting it.

**Comment by dulek** [comment]
Following @celebdor advice I've removed plugins and dns from disabled services on origin-node. I've tested it and stuff works fine.

**Comment by dulek** [comment]
@sdodson: Can you trigger CI on this? My manual testing was successful.
@celebdor: Could you take a look if this is okay from your perspective?

**Comment by sdodson** [comment]
bot, add author to whitelist
bot, test pull request
/ok-to-test

**Comment by dulek** [comment]
@sdodson: Can you confirm if CI error is related? "rm: cannot remove ‘/tmp/etcd/member’: Permission denied" sounds like a more generic error.

**Pull request merged**
