### PR TITLE
openshift_node: Remove master from aws node building

### PR DESCRIPTION
**Pull request by ashcrow**
Since it is expected to be re-added at some point in the future the lines
have been commented out rather than deleted.

### CODE REVIEW

**Comment by ashcrow** [comment]
Looks like I need to remove the items to pass yamllint. Will do.

**Comment by ashcrow** [comment]
logging failure is a flake:
```
[openshift/origin-logging-fluentd] ERROR:  Error installing fluent-plugin-systemd:
[openshift/origin-logging-fluentd] 	ERROR: Failed to build gem native extension.
[openshift/origin-logging-fluentd]     /usr/bin/ruby extconf.rb
```

**Comment by ashcrow** [comment]
bot, retest this please

**Comment by ashcrow** [comment]
flake https://github.com/openshift/origin/issues/17880

**Comment by ashcrow** [comment]
I don't quite know what's failing:

```
########## FINISHED STAGE: FAILURE: FORWARD PARAMETERS TO THE REMOTE HOST [00h 00m 00s] ##########
Build step 'Execute a set of scripts' marked build as failure
```

**Comment by ashcrow** [comment]
Unrelated failure in logging:

```
[openshift/origin-logging-fluentd] make: *** ["/opt/app-root/src/gems/ffi-1.9.21/ext/ffi_c/libffi-x86_64-linux"/.libs/libffi_convenience.a] Error 1
[openshift/origin-logging-fluentd] Gem files will remain installed in /opt/app-root/src/gems/ffi-1.9.21 for inspection.
[openshift/origin-logging-fluentd] Results logged to /opt/app-root/src/gems/ffi-1.9.21/ext/ffi_c/gem_make.out
```

**Comment by kwoodson** [comment]
@ashcrow, these are unrelated and this change is very low impact for the task at hand.  Merging

**Pull request merged**
