### PR TITLE
Bug 1511044- Slurp the etcd certs instead of using the lookup

### PR DESCRIPTION
**Pull request by fabianvf**
https://bugzilla.redhat.com/show_bug.cgi?id=1511044

Tested in my local environment, everything came up green.

### CODE REVIEW

**Comment by sdodson** [comment]
lint error 
```
roles/ansible_service_broker/tasks/generate_certs.yml:
  37:5      error    wrong indentation: expected 2 but found 4  (indentation)
yamllint issues found
ERROR: InvocationError: '/home/travis/build/openshift/openshift-ansible/.tox/py27-yamllint/bin/python setup.py yamllint'
```

**Comment by fabianvf** [comment]
Fixed lint error.

**Pull request merged**
