### PR TITLE
[KIECLOUD-268] - Update RHPAM and RHMD templates and imagestreams on …

### PR DESCRIPTION
**Pull request by spolti**
…OpenShift Service Catalog for release 7.4.0

Signed-off-by: Filippe Spolti <fspolti@redhat.com>

### CODE REVIEW

**Comment by errantepiphany** [comment]
@patrickdillon @jstuever : It looks like this PR is stuck at "Needs approved, lgtm labels." Do you know who can do that, please?

**Comment by vrutkovs** [comment]
/hold

requires https://github.com/openshift/release/pull/4533

**Comment by errantepiphany** [comment]
@spolti Failed test?

**Comment by vrutkovs** [comment]
@spolti needs rebase

**Pull request merged**
