### PR TITLE
add support for imagePolicyConfig in master

### PR DESCRIPTION
**Pull request by detiber**

### CODE REVIEW

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
@abutcher ptal

**Comment by abutcher** [comment]
aos-ci-test

**Comment by detiber** [comment]
oh, nice...  3.1 containerized is trying to install the atomic-openshift package to check version.

**Comment by abutcher** [comment]
Oyyy

**Comment by abutcher** [comment]
Changes LGTM

**Comment by abutcher** [comment]
aos-ci-test

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
closing in favor of: https://github.com/openshift/openshift-ansible/pull/1738

**Pull request closed without merging**
