### PR TITLE
Check for mandatory node-group configmaps during upgrades

### PR DESCRIPTION
**Pull request by michaelgugino**
This commit enforces presence of mandatory node-group
configmaps during upgrade.

### CODE REVIEW

**Comment by sdodson** [comment]
Need to ensure that we're not nuking configmaps on 3.10 to 3.10.1 upgrades.
Need to ensure that every single host that's in the nodes group has `openshift_node_group_name` specified.

**Comment by sdodson** [comment]
@smarterclayton FYI, we're going to block upgrades until configmaps for master, infra, and compute exist. We'll provide a playbook to build them for automation but we expect customers to create them on their own before upgrading.

**Comment by michaelgugino** [comment]
/hold

I don't want to enforce pointless config maps; we're kind of locked into a pattern.  I'm going to write a module to mine what groups we need.

**Pull request merged**
