### PR TITLE
Use local address for loopback kubeconfig

### PR DESCRIPTION
**Pull request by detiber**
@abutcher ptal

### CODE REVIEW

**Comment by abutcher** [comment]
LGTM aside from pylint

**Comment by detiber** [comment]
Good old pylint, mostly wanted some feedback on the proposed changes before I bothered spending any more time on it :)

**Comment by abutcher** [comment]
@detiber Yeah it looks good, I ran through an install as well.

**Comment by detiber** [comment]
closing in favor of: https://github.com/openshift/openshift-ansible/pull/1175

**Pull request closed without merging**
