### PR TITLE
Fix rhgs-s3 image name

### PR DESCRIPTION
**Pull request by SaravanaStorageNetwork**
rhgs3/rhgs-gluster-s3-server-rhel7 should be  rhgs3/rhgs-s3-server-rhel7

Signed-off-by: Saravanakumar Arumugam <sarumuga@redhat.com>

### CODE REVIEW

**Comment by SaravanaStorageNetwork** [comment]
@jarrpa  Please check

**Comment by SaravanaStorageNetwork** [comment]
bot, test pull request

**Comment by jarrpa** [comment]
Good catch! Sorry. :)

/ok-to-test
/lgtm
bot, test pull request

**Comment by SaravanaStorageNetwork** [comment]
@sdodson @michaelgugino @jarrpa This is failing for no reason - Please help to get this merged

**Pull request merged**
