### PR TITLE
Bug 1258243: Use lower() filter for node hostname

### PR DESCRIPTION
**Pull request by abutcher**
Moving this from #540.

@sdodson ptal

### CODE REVIEW

**Comment by sdodson** [comment]
LGTM

**Comment by abutcher** [comment]
@brenton pls2merge

**Comment by brenton** [comment]
Until we ship https://trello.com/c/PIcsdyXN/72-ci-deploy-resources-to-run-ansible-playbook-against-for-master-and-prs or QE signs off (many of them are on a national holiday) I'd say you simply could add this PR to the BZ and move the bug to ON_QA.

Alternatively, you could follow up with the reporter and have the customer test the PR if it was urgent to them.  If the customer verified it solved their problem I'd consider merging it in before QE returns.  I know it seems silly for something as trivial as this I just know we've broken things in the past for simpler changes.

**Comment by abutcher** [comment]
@brenton Sure thing 8)

**Comment by abutcher** [comment]
@brenton This has been verified by QE after an update.

**Pull request merged**
