### PR TITLE
move etcd backup to etcd_common role

### PR DESCRIPTION
**Pull request by ingvagabund**
SSIA

### CODE REVIEW

**Comment by ingvagabund** [comment]
aso-ci-test

**Comment by ingvagabund** [comment]
aos-ci-test

**Comment by sdodson** [comment]
I think it'd be good to follow up to push the backup call from the playbook down into etcd_upgrade role so that whenever you perform an etcd_upgrade you get a backup. However I can see how that goes against our rules about "loosely" coupling roles.

I'm forever struggling with whether the onus is on the playbook author or the role author to Do The Right Thing(tm).

**Comment by sdodson** [comment]
Haven't had a chance to test this locally will try to get to that ASAP. but if this is a blocker for etcd v3 migration lets go ahead and get it in.

**Comment by ingvagabund** [comment]
I have tested that locally with both installation and upgrade

**Comment by sdodson** [comment]
[merge]

**Comment by ingvagabund** [comment]
```
rm: cannot remove ‘/tmp/etcd/member’: Permission denied
```

CI related issue

**Comment by sdodson** [comment]
@stevekuznetsov ideas on that failure?

**Comment by stevekuznetsov** [comment]
The failure was in the [`Extended.[k8s.io] Daemon set [Serial] Should adopt or recreate existing pods when creating a RollingUpdate DaemonSet with matching or mismatching templateGeneration` extended test](https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check/584/testReport/junit/(root)/Extended/_k8s_io__Daemon_set__Serial__Should_adopt_or_recreate_existing_pods_when_creating_a_RollingUpdate_DaemonSet_with_matching_or_mismatching_templateGeneration/). 

@ingvagabund I would appreciate it if you would find the root cause of the issue before hitting the merge button. The action taken here is reckless.

**Comment by stevekuznetsov** [comment]
Cleanup of `etcd` data is best-effort. Not sure why the permissions were wrong there.

**Comment by sdodson** [comment]
flake on https://github.com/openshift/origin/issues/14129

**Comment by ingvagabund** [comment]
@stevekuznetsov if the CI failure was related to the PR, it would fail before the e2e tests. I agree it is important to find the root cause. I can re-run the entire merge job once again to see if the flake disappears. Saying that, I can't wait forever for the PR to get merged.

**Pull request merged**
