### PR TITLE
Ensure linux linefeeds in case people use windows per default

### PR DESCRIPTION
**Pull request by xrow**
Well if you deploy linux repo files with windows linefeeds yum will not work. What do you expect. Therefore I would try to set linux linefeeds per default

### CODE REVIEW

**Comment by sdodson** [comment]
/cc @jim-minter 
PTAL

**Comment by jim-minter** [comment]
@sdodson not sure why you sent this my way.  I don't think this would cause problems for azure; as regards the rest of openshift-ansible I don't think it's my say.

**Comment by xrow** [comment]
The risk is that any specific text file needs \r\n for whatever reason. But I can`t imagine what file that could be on a linux host.

**Comment by michaelgugino** [comment]
I'm not sure we need this, typically users can set their preferred line ending in a linux-aware text editors on Windows or other platforms.

Generally speaking, I don't think we support running openshift-ansible from a Windows machine.

**Comment by xrow** [comment]
The problem happens at git clone and not with the text editor. What is the problem with this merge then?

**Comment by michaelgugino** [comment]
> The problem happens at git clone and not with the text editor. What is the problem with this merge then? Why is wide support not a desire?

I'm not clear on what the problem is.  Where are these line feeds coming from?

If I clone a repo, and hash some text file, I'm assuming the resulting has would be the same on any operating system.

**Comment by xrow** [comment]
@michaelgugino No it is not. For example on windows the default for git core.autocrlf is true. That means, if  now clone a repo with not reforced lineendings they all turn to \r\n. If I would now mount the 
 windows ansible project folder in linux in vagrant I would get \r\n in ansible templates on a linux system. If I now run ansible on that linux system, ansible will create \r\n files on a linux system. :-/ That`s black magic!!! PLZ assist :-)

**Comment by michaelgugino** [comment]
> @michaelgugino No it is not. For example on windows the default for git core.autocrlf is true. That means, if now clone a repo with not reforced lineendings they all turn to \r\n. If I would now mount the
windows ansible project folder in linux in vagrant I would get \r\n in ansible templates on a linux system. If I now run ansible on that linux system, ansible will create \r\n files on a linux system. :-/ That`s black magic!!! PLZ assist :-)

I have looked into this.  git only makes these changes by setting it up to do so.  Please setup your environment to not automatically transform eol characters and use a text editor that supports unix-style line feeds.

**Comment by xrow** [comment]
ok will accept that proposal

**Pull request closed without merging**
