### PR TITLE
Fix extension script for catalog

### PR DESCRIPTION
**Pull request by michaelgugino**
Currently, playbook wire_aggregator places an empty
plugin script for openshift master called
openshift-ansible-catalog-console.js

This file should not be empty if using template_service_broker.

I have updated this file to include a boolean and the proper
string.

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1506502

### CODE REVIEW

**Comment by michaelgugino** [comment]
@ewolinetz We really need to get a readme together for the TSB role that points to some documentation.  Also, can you look over this wire aggregator stuff and add some comments to that file that describes what it's doing?  I think we should probably move that logic into the master role.

**Comment by sdodson** [comment]
/kind bug
/priority p0
@spadgett I assume we need to get this into release-3.7 as a blocker fix?

**Comment by spadgett** [comment]
Changes LGTM. This seems cleaner.

>  I assume we need to get this into release-3.7 as a blocker fix?

Yes, I agree this is a blocker that should be fixed for 3.7.

**Pull request merged**
