### PR TITLE
pin azure cli to version 2.0.47

### PR DESCRIPTION
**Pull request by charlesakalugwu**
closes https://github.com/openshift/openshift-azure/issues/591

/cc @jim-minter @kwoodson

### CODE REVIEW

**Comment by kwoodson** [comment]
Flakes
```
error: could not resolve inputs: could not determine inputs for step [input:root]: could not resolve base image: Get https://api.ci.openshift.org/apis/image.openshift.io/v1/namespaces/openshift/imagestreamtags/release:golang-1.10: EOF
```

**Comment by kwoodson** [comment]
It looks like the test did not have a valid yum repo:
```
TASK [openshift_excluder : Install docker excluder - yum] **********************
task path: /usr/share/ansible/openshift-ansible/roles/openshift_excluder/tasks/install.yml:9
Thursday 11 October 2018  17:43:32 +0000 (0:00:00.064)       0:02:03.394 ****** 
FAILED - RETRYING: Install docker excluder - yum (3 retries left).
FAILED - RETRYING: Install docker excluder - yum (2 retries left).
FAILED - RETRYING: Install docker excluder - yum (1 retries left).
fatal: [35.237.74.215]: FAILED! => {"attempts": 3, "changed": false, "msg": "No package matching 'origin-docker-excluder-4.0**' found available, installed or updated", "rc": 126, "results": ["No package matching 'origin-docker-excluder-4.0**' found available, installed or updated"]}
```

**Comment by kargakis** [comment]
/lgtm

needs an approval and most probably a manual merge @kwoodson @jim-minter @pweil-

**Comment by kwoodson** [comment]
@kargakis, since we are modifying the Dockerfile we need @sdodson's approval.  Would prefer we inform him of the change before stomping the merge button.

**Comment by kwoodson** [comment]
This is still a flake on the yum repository being invalid:
```
  results:
  - No package matching 'origin-docker-excluder-4.0**' found available, installed or updated
```

**Comment by charlesakalugwu** [comment]
@vrutkovs failed again. Feels like this will never happen :(

**Comment by vrutkovs** [comment]
@charlesakalugwu sorry, issues on CI. This would merge eventually

**Comment by vrutkovs** [comment]
CI issues were resolved
/retest

**Comment by vrutkovs** [comment]
/hold

CI won't pass until https://github.com/openshift/openshift-ansible/pull/10377 is merged

**Pull request merged**
