### PR TITLE
Backport changes for glusterfs and heketi template

### PR DESCRIPTION
**Pull request by SaravanaStorageNetwork**
Backport changes for glusterfs and heketi template

To avoid unknown parameter errors like GB_GLFS_LRU_COUNT and
HEKETI_FSTAB

Signed-off-by: Saravanakumar Arumugam <sarumuga@redhat.com>

### CODE REVIEW

**Comment by SaravanaStorageNetwork** [comment]
@jarrpa  With latest images, using old 3.6 template files fails with unknown parameter errors.  
Please check.

**Comment by jarrpa** [comment]
@SaravanaStorageNetwork This should all have been taken care of by https://github.com/openshift/openshift-ansible/pull/6493 no?

**Comment by SaravanaStorageNetwork** [comment]
@jarrpa  you are right - it is available in release3.6 . But, it is not available in master branch's openshift_storage_glusterfs/files/v3.6/ templates

**Comment by jarrpa** [comment]
OH! Right! Augh, this is so confusing... I'm going to nuke those version directories. :)

Since you're doing this: There are a few other files (like for s3 and the block provisioner) that should be included. Could you just take the `files/v3.6` and `templates/v3.6` directories from the 3.6 branch and copy them to master?

**Comment by SaravanaStorageNetwork** [comment]
> Since you're doing this: There are a few other files (like for s3 and the block provisioner) that should be included. Could you just take the files/v3.6 and templates/v3.6 directories from the 3.6 branch and copy them to master?
Sure, will update in this patch itself.

**Comment by SaravanaStorageNetwork** [comment]
> Since you're doing this: There are a few other files (like for s3 and the block provisioner) that should be included. Could you just take the files/v3.6 and templates/v3.6 directories from the 3.6 branch and copy them to master?

@jarrpa  This is done..please check

**Pull request merged**
