### PR TITLE
Sync 3.5 cfme templates over to 3.6

### LINKED ISSUE #4446: cloudforms docker image project has been retagged, and now the cfme templates are broken
#### Description

Sample image from https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/files/examples/v1.5/cfme-templates/cfme-template.yaml :

registry.access.redhat.com/**cloudforms**/cfme-openshift-app

But

$ docker search registry.access.redhat.com/cloudforms
INDEX        NAME                                                                              DESCRIPTION                                     STARS     OFFICIAL   AUTOMATED
redhat.com   registry.access.redhat.com/**cloudforms42**/cfme                                      Red Hat® CloudForms manages private cloud...    0                    
redhat.com   registry.access.redhat.com/**cloudforms42**/cfme-openshift-app                        Red Hat® CloudForms Appliance image to be...    0                    
redhat.com   registry.access.redhat.com/**cloudforms42**/cfme-openshift-memcached                  Memcached image that provides distributed ...   0                    
redhat.com   registry.access.redhat.com/**cloudforms42**/cfme-openshift-postgresql                 Postgresql image that provides database se...   0                    
redhat.com   registry.access.redhat.com/**cloudforms45**/cfme-openshift-app                        Red Hat® CloudForms Appliance image to be...    0                    
redhat.com   registry.access.redhat.com/**cloudforms45**/cfme-openshift-memcached                  Memcached image that provides distributed ...   0                    
redhat.com   registry.access.redhat.com/**cloudforms45**/cfme-openshift-postgresql                 Postgresql image that provides database se...   0                    

##### Version

OCP 3.5

@jorgemoralespou

### PR DESCRIPTION
**Pull request by sdodson**
Fixes #4446

### CODE REVIEW

**Comment by sdodson** [comment]
@simaishi please take a look

**Comment by simaishi** [comment]
Need confirmation from @Loicavenel about adding the templates to v1.6 directory, as [the last discussion](https://github.com/openshift/openshift-ansible/pull/4334#issuecomment-305810215) (earlier this month) was to add them later and I'm not sure about the timing.

cfme-* files look good if there are no specific changes needed for v1.6.  (can't comment on jboss-*)

**Comment by sdodson** [comment]
I need to get them into 3.6 branch ASAP or they'll miss the 3.6 code freeze. I assume it's better to keep them in line with what's in 3.5 than it is to have what's currently in there?

**Comment by simaishi** [comment]
Probably true, but that just isn't my call...

**Pull request merged**
