### PR TITLE
[release-3.9] [Bug 1558689] Add hostname package to RHEL image

### PR DESCRIPTION
**Pull request by mtnbikenc**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1558689

### CODE REVIEW

**Comment by sdodson** [comment]
This is needed in master and release-3.10 as well? probably won't cherrypick cleanly as i think there's some diff across branches.
/lgtm

**Comment by mtnbikenc** [comment]
gcp test is failing because the test is pulling the 3.9 image from docker hub, which is currently broken.  Changes to the test definition have caused the image to be pulled remotely instead of using the image that was built locally.

**Pull request merged**
