### PR TITLE
Improve cleanup of networks and disks in GCP

### PR DESCRIPTION
**Pull request by smarterclayton**
Firewall rules are sometimes leaked by the cluster, preventing us
from tearing down. Make that more resilient

### CODE REVIEW

**Comment by sdodson** [comment]
Does this need to be picked back into all branches that current provision GCP infra?

**Comment by smarterclayton** [comment]
It doesn't seem to fix the entire problem (some firewall rules are still
not getting torn down).  I'm currently trying to identify which resource is
holding on to the rules.

**Pull request merged**
