### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by rhcarvalho**
Fixed some typos while getting familiar with the code base.

### CODE REVIEW

**Comment by rhcarvalho** [comment]
Doubts (not included in the patch):
- I found tens of occurrences of "useage" ("usage") in templates in `roles/openshift_examples/files/examples/**/xpaas-templates/**`, but I'm assuming those are just copy-pasted from elsewhere, maybe not worth changing.
- I found also a few typos in the release notes in `openshift-ansible.spec`, but also considered that not to be something that welcomes updates.

**Comment by abutcher** [comment]
aos-ci-test

**Comment by abutcher** [comment]
WRT doubts: the templates are sync'd from elsewhere. @sdodson where can we fix the "useage" in the upstream templates?

**Comment by sdodson** [comment]
PR opened against upstream repo.

**Comment by rhcarvalho** [comment]
@abutcher thank you.

**Comment by abutcher** [comment]
@rhcarvalho Thanks!

**Pull request merged**
