### PR TITLE
apiVersion moved to stable and to apps/v1

### PR DESCRIPTION
**Pull request by sreber84**
The core workloads API, which is composed of the DaemonSet, Deployment, ReplicaSet, and StatefulSet kinds, has been promoted to GA stability in the apps/v1 group version in OpenShift Container Platform 3.9.

### CODE REVIEW

**Comment by jcantrill** [comment]
@richm thoughts here?  @sreber84 isn't this something that should be left as is regardless of the api promotion?  3.11 went out the door with the given version and this could, however unlikely, have a ripple affect to other logging related tools.  I would expect it to be bumped in later versions instead of a point release

cc @ewolinetz did we bump in 4.x?

**Comment by richm** [comment]
NACK from me.

A quick `git grep -A 2 extensions/v1beta1` in openshift-ansible branch release-3.11 shows several places where daemonset is being used.  I think a change like this should be a global openshift-ansible change of *all* of the `extensions/v1beta1` daemonsets to be `apps/v1`.

**Comment by sreber84** [comment]
@jcantrill yeah once submitted I also found that most deployments in OpenShift 3.11 have the same API extension. I mainly created the request as we identified some issues with customers when using `extensions/v1beta1` for `DaemonSet` in OpenShift 3.11 and thus figured it would be good to fix it. As we always should act as example I was eager to fix it. But I agree introducing this in point release does not make sense and is too risky. Hopefully we have this fixed in 4.x

**Pull request closed without merging**
