### PR TITLE
Cleanup unused openstack provider code

### PR DESCRIPTION
**Pull request by bogdando**
Remove references for bastion, ssh UI tunnek and static inventory.
Update docs.

@tomassedovic PTAL

### CODE REVIEW

**Comment by bogdando** [comment]
@tomassedovic @michaelgugino PTAL
e2e worked for me with https://github.com/openshift/openshift-ansible/pull/6345 in place

**Comment by michaelgugino** [comment]
/ok-to-test

This looks okay to me.

**Comment by tomassedovic** [comment]
Thanks @bogdando! Looks good to me too. I'm testing it now.

**Comment by bogdando** [comment]
@sdodson perchance, do you know why this one doesn't get merged automagically?

**Comment by michaelgugino** [comment]
bot, retest this please

**Pull request merged**
