### PR TITLE
Native ha port fixes

### PR DESCRIPTION
**Pull request by abutcher**
* Remove extra port from the master url.
* Add an `haproxy_frontend_port` var so we can use it for `os_firewall`.

@detiber PTAL

### CODE REVIEW

**Comment by abutcher** [comment]
aos-ci-test

**Comment by detiber** [comment]
@abutcher :+1:

**Comment by abutcher** [comment]
aos-ci-test

**Comment by abutcher** [comment]
aos-ci-test

**Comment by arilivigni** [comment]
aos-ci-test

**Comment by abutcher** [comment]
@brenton :point_up:

**Comment by arilivigni** [comment]
aos-ci-test

**Pull request merged**
