### PR TITLE
[RHDM-662] - Update RHDM templates on OCP and OSO

### PR DESCRIPTION
**Pull request by spolti**

### CODE REVIEW

**Comment by vrutkovs** [comment]
bot, test pull request

**Comment by spolti** [comment]
@vrutkovs the fails seems to be unrelated, is there something that I need to do or it just need to be retest?

**Comment by vrutkovs** [comment]
Yep, failures are unrelated

/retest

**Comment by spolti** [comment]
Hi, are this PR ready to get merged? Thanks.

**Pull request merged**
