### PR TITLE
[3.7] service catalog: Update API healthz check to use uri module and add noproxy

### PR DESCRIPTION
**Pull request by vrutkovs**
Backport of  #7222 and #7262

### CODE REVIEW

**Comment by sdodson** [comment]
@abutcher I know we discussed this change on Friday, what's your take on whether we move forward with this? If we do I think we also need to go back and change all curl invocations to align with this if possible.

**Comment by abutcher** [comment]
@sdodson I was worried we were losing testing TLS here but I see ‘-k’ on the original. URI module seems fine but why are we not validating certs?

**Comment by vrutkovs** [comment]
>why are we not validating certs

Certs might be self-signed, IIUC its required to skip certs on containerized systems at least

**Pull request merged**
