### PR TITLE
added port 4789 to master security group for access to SDN network

### PR DESCRIPTION
**Pull request by jdnieto**

### CODE REVIEW

**Comment by abutcher** [comment]
@jdnieto This adds ingress 4789 to the etcd security group. Should be master security group?

**Comment by jdnieto** [comment]
@abutcher repaired, sorry for the mistake :(

**Comment by sdodson** [comment]
A master needs to be a node in order to be on the SDN, is your master not also a node?

**Comment by jdnieto** [comment]
Yes, my master is also a node. oc get nodes shows my master. But in
openshift-ansible it is created without that port in OpenStack, and their
security group is master without 4789 SDN port.

El mar., 16 feb. 2016 19:36, Scott Dodson <notifications@github.com>
escribió:

> A master needs to be a node in order to be on the SDN, is your master not
> also a node?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/openshift-ansible/pull/1414#issuecomment-184818410>
> .
>
-- 

Un saludo.
-------------------------------------------
José David Martín Nieto
RHCE, RHCJA, RHCJD, RHCoE-PaaS, RHCoE-Hibernate, RHCI, RHCX
#110-442-589

Public Key 2048R/24C474E5 C8B9 5589 9C19 1453 1184  EEAE A642 701E 24C4
74E5 @pool.sks-keyservers.net

**Comment by sdodson** [comment]
@abutcher explained the situation to me, LGTM

**Comment by abutcher** [comment]
If masters and nodes are in their own security groups then we should probably also add 10250 to master ingress. I'm not very familiar with the openstack bits in openshift-ansible so I'll have to defer to @lhuard1A and @menren

**Comment by jdnieto** [comment]
@abutcher the port 10250 is only needed for connection between master and nodes, and it's already enabled in the node-secgrp. So it's not needed. But I modified also the infra-secgrp for the same reason. I'm thinking to create a new pull request configuring a new group called "common-group" for the common ports and to allocate it together with the corresponding groups in instances.
What do you think?

**Comment by jdnieto** [comment]
I close this pull request. Opened a new one with better description. [#1423](https://github.com/openshift/openshift-ansible/pull/1423)

**Pull request closed without merging**
