### PR TITLE
Remove podpreset, runtime-config

### PR DESCRIPTION
**Pull request by liggitt**
Remove unnecessary runtime-config and podpreset enablement

### CODE REVIEW

**Comment by liggitt** [comment]
service catalog doesn't use pod presets, and the runtime-config format being used doesn't match what kube supports (`apis/` prefix is incorrect and silently ignored by kube < 1.10)

**Comment by smarterclayton** [comment]
You need to add an upgrade test to remove this then.

**Comment by smarterclayton** [comment]
I'm just going to fold this and #7751 into #7649

**Comment by smarterclayton** [comment]
folded in

**Pull request closed without merging**
