### PR TITLE
Update main.yml

### PR DESCRIPTION
**Pull request by niqhil**
Do not enforce nfs storage plugin. Let it be handled at the configuration storage_plugin_deps. 
This gives error for byo offline install. ( yum repo )

### CODE REVIEW

**Comment by abutcher** [comment]
Looks good but I think `'nfs'` should be in the default `storage_plugin_deps` defined in `openshift_facts` but this would allow it to be overridden in inventory.

Are you installing on centos? Want to know where nfs-utils isn't available and maybe we can resolve that or document it better.

**Comment by abutcher** [comment]
Oh, offline install...

**Comment by detiber** [comment]
@niqhil +1 to this change, can you squash the commits?

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
@niqhil apologies about letting this PR drag on, if you can resolve the conflict, we can re-test and get this merged.

**Comment by mtnbikenc** [comment]
Closing this PR as it is stale and needs to be rebased.   Please reopen the PR if you feel this patch is still applicable.  Thanks!

**Pull request closed without merging**
