### PR TITLE
allow node config sync controller to handle multiple node labels

### PR DESCRIPTION
**Pull request by jim-minter**

### CODE REVIEW

**Comment by jim-minter** [comment]
@smarterclayton afaics the node config sync controller doesn't handle applying multiple labels to a node object - this patch should resolve.  ptal.

**Comment by smarterclayton** [comment]
Holding nose...

**Comment by jim-minter** [comment]
:cry: 

This change breaks GCP.  Currently in GCP the node-labels in the node-config looks like:
```
  node-labels:
  - node-role.kubernetes.io/compute=true,role=app
```

Whereas Azure's look like:
```
  node-labels:
  - node-role.kubernetes.io/compute=true
  - region=primary
```

I think the way the GCP config is being populated is invalid, but I don't know whether it's changeable?  

@smarterclayton before I dive in, what's your opinion on how to deal with this?

**Comment by smarterclayton** [comment]
Both forms are valid.

**Comment by mjudeikis** [comment]
@jim-minter : 
```
labels=$(tr ' ' '\n' <<<$args | sed -ne '/^--node-labels=/ { s/^[^=]*=//; p; }' | tr '[\n,]' ' ')
```
test:
```
[root@ocp-master-15100269-0 0]# cat /tmp/label.sh
 conf="$1"
 if args="$(openshift start node --write-flags --config ${conf})"; then
                  labels=$(tr ' ' '\n' <<<$args | sed -ne '/^--node-labels=/ { s/^[^=]*=//; p; }' | tr '[\n,]' ' ')                                                                                      
                if [[ -n "${labels}" ]]; then
                  echo ${labels}
                fi
fi                                                                                                                                                
[root@ocp-master-15100269-0 0]# /tmp/label.sh /etc/origin/node/bootstrap-node-config-mix.yaml 
node-role.kubernetes.io/compute=true role=app test=label
[root@ocp-master-15100269-0 0]# /tmp/label.sh /etc/origin/node/bootstrap-node-config-gcp.yaml 
node-role.kubernetes.io/compute=true role=app
[root@ocp-master-15100269-0 0]# /tmp/label.sh /etc/origin/node/bootstrap-node-config-azure.yaml
node-role.kubernetes.io/compute=true role=app
```

**Comment by jim-minter** [comment]
@mtnbikenc or @vrutkovs please can you approve?  clayton doesn't love it but he's letting it past.

**Pull request merged**
