### PR TITLE
Fix proxy settings. For real. For actual this time.

### PR DESCRIPTION
**Pull request by tbielawa**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1467776
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1466783
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1472244
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1468424
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1470165

Some of there were 'fixed' before but that commit was merged too soon. This actually fixes the needful.

Actual fix was just adding `or 'no_proxy' in common:`

We have a [trello card](https://trello.com/c/b7uCBkfB/474-tech-debt-proxy-settings-are-organically-messy) to fix this up correctly.

# If you review this

Please make sure [you read the logs below](https://github.com/openshift/openshift-ansible/pull/4794#issuecomment-316460698). They demonstrate proxy settings being set, or not, and the parameters that went into that business.

### CODE REVIEW

**Comment by tbielawa** [comment]
Review of different proxy setting permutations and their results

# LOG-01


Using inventory params:
```ini
    [OSEv3:vars]

    openshift_no_proxy=m01.example.com,n01.example.com,n02.example.com,foobar.example.com
    openshift_master_cluster_method=native
    openshift_master_cluster_hostname=m01.example.com
    openshift_master_cluster_public_hostname=m01.example.com
    openshift_master_default_subdomain=m01.example.com
```

* Note that 'foobar.example.com' is not an actual cluster member. This
  demonstrates that the openshift_no_proxy value was being used, these
  results are not from auto-generated hostnames

* Note that I forgot to set `openshift_schedulable=True` on
  `m01.example.com` in the `[nodes]` section of the inventory


```[ansible-console]$ grep -ri _proxy /etc/origin/ /etc/sysconfig/
n02.example.com | SUCCESS | rc=0 >>
/etc/origin/master/master-config.yaml:        - name: NO_PROXY
/etc/origin/master/master-config.yaml:        - name: no_proxy
/etc/sysconfig/docker:NO_PROXY='.cluster.local,.svc,foobar.example.com,m01.example.com,n01.example.com,n02.example.com'
/etc/sysconfig/atomic-openshift-master:NO_PROXY=.cluster.local,.svc,foobar.example.com,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
/etc/sysconfig/atomic-openshift-master-api:NO_PROXY=.cluster.local,.svc,foobar.example.com,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
/etc/sysconfig/atomic-openshift-master-controllers:NO_PROXY=.cluster.local,.svc,foobar.example.com,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
/etc/sysconfig/atomic-openshift-node:# Origin uses standard HTTP_PROXY environment variables. Be sure to set
/etc/sysconfig/atomic-openshift-node:# NO_PROXY for your master
/etc/sysconfig/atomic-openshift-node:#NO_PROXY=master.example.com
/etc/sysconfig/atomic-openshift-node:#HTTP_PROXY=http://USER:PASSWORD@IPADDR:PORT
/etc/sysconfig/atomic-openshift-node:#HTTPS_PROXY=https://USER:PASSWORD@IPADDR:PORT

n01.example.com | SUCCESS | rc=0 >>
/etc/origin/master/master-config.yaml:        - name: NO_PROXY
/etc/origin/master/master-config.yaml:        - name: no_proxy
/etc/sysconfig/docker:NO_PROXY='.cluster.local,.svc,foobar.example.com,m01.example.com,n01.example.com,n02.example.com'
/etc/sysconfig/atomic-openshift-master:NO_PROXY=.cluster.local,.svc,foobar.example.com,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
/etc/sysconfig/atomic-openshift-master-api:NO_PROXY=.cluster.local,.svc,foobar.example.com,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
/etc/sysconfig/atomic-openshift-master-controllers:NO_PROXY=.cluster.local,.svc,foobar.example.com,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
/etc/sysconfig/atomic-openshift-node:# Origin uses standard HTTP_PROXY environment variables. Be sure to set
/etc/sysconfig/atomic-openshift-node:# NO_PROXY for your master
/etc/sysconfig/atomic-openshift-node:#NO_PROXY=master.example.com
/etc/sysconfig/atomic-openshift-node:#HTTP_PROXY=http://USER:PASSWORD@IPADDR:PORT
/etc/sysconfig/atomic-openshift-node:#HTTPS_PROXY=https://USER:PASSWORD@IPADDR:PORT

m01.example.com | SUCCESS | rc=0 >>
/etc/origin/master/master-config.yaml:        - name: NO_PROXY
/etc/origin/master/master-config.yaml:        - name: no_proxy
/etc/sysconfig/docker:NO_PROXY='.cluster.local,.svc,foobar.example.com,m01.example.com,n01.example.com,n02.example.com'
/etc/sysconfig/atomic-openshift-master:NO_PROXY=.cluster.local,.svc,foobar.example.com,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
/etc/sysconfig/atomic-openshift-master-api:NO_PROXY=.cluster.local,.svc,foobar.example.com,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
/etc/sysconfig/atomic-openshift-master-controllers:NO_PROXY=.cluster.local,.svc,foobar.example.com,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
/etc/sysconfig/atomic-openshift-node:# Origin uses standard HTTP_PROXY environment variables. Be sure to set
/etc/sysconfig/atomic-openshift-node:# NO_PROXY for your master
/etc/sysconfig/atomic-openshift-node:#NO_PROXY=master.example.com
/etc/sysconfig/atomic-openshift-node:#HTTP_PROXY=http://USER:PASSWORD@IPADDR:PORT
/etc/sysconfig/atomic-openshift-node:#HTTPS_PROXY=https://USER:PASSWORD@IPADDR:PORT
```

# LOG-02

Using inventory params:

```ini
    [OSEv3:vars]

    openshift_https_proxy=http://file.rdu.redhat.com:3128
    openshift_http_proxy=http://file.rdu.redhat.com:3128

    openshift_master_cluster_method=native
    openshift_master_cluster_hostname=m01.example.com
    openshift_master_cluster_public_hostname=m01.example.com
    openshift_master_default_subdomain=m01.example.com
```

* Note that in LOG-01 I had forgot to set `openshift_schedulable=True`
  on `m01.example.com` in the `[nodes]` section of the inventory. That
  has been fixed in this test.

```
[ansible-console]$ grep -ri _proxy /etc/origin/ /etc/sysconfig/
m01.example.com | SUCCESS | rc=0 >>
/etc/origin/master/master-config.yaml:        - name: HTTP_PROXY
/etc/origin/master/master-config.yaml:        - name: HTTPS_PROXY
/etc/origin/master/master-config.yaml:        - name: NO_PROXY
/etc/origin/master/master-config.yaml:        - name: http_proxy
/etc/origin/master/master-config.yaml:        - name: https_proxy
/etc/origin/master/master-config.yaml:        - name: no_proxy
/etc/sysconfig/docker:HTTP_PROXY='http://file.rdu.redhat.com:3128'
/etc/sysconfig/docker:HTTPS_PROXY='http://file.rdu.redhat.com:3128'
/etc/sysconfig/docker:NO_PROXY='.cluster.local,.svc,m01.example.com'
/etc/sysconfig/atomic-openshift-master:HTTP_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master:HTTPS_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master:NO_PROXY=.cluster.local,.svc,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
/etc/sysconfig/atomic-openshift-master-api:HTTP_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master-api:HTTPS_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master-api:NO_PROXY=.cluster.local,.svc,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
/etc/sysconfig/atomic-openshift-master-controllers:HTTP_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master-controllers:HTTPS_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master-controllers:NO_PROXY=.cluster.local,.svc,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
/etc/sysconfig/atomic-openshift-node:# Origin uses standard HTTP_PROXY environment variables. Be sure to set
/etc/sysconfig/atomic-openshift-node:# NO_PROXY for your master
/etc/sysconfig/atomic-openshift-node:#NO_PROXY=master.example.com
/etc/sysconfig/atomic-openshift-node:#HTTP_PROXY=http://USER:PASSWORD@IPADDR:PORT
/etc/sysconfig/atomic-openshift-node:#HTTPS_PROXY=https://USER:PASSWORD@IPADDR:PORT
/etc/sysconfig/atomic-openshift-node:HTTP_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-node:HTTPS_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-node:NO_PROXY=.cluster.local,.svc,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14

n02.example.com | SUCCESS | rc=0 >>
/etc/origin/master/master-config.yaml:        - name: HTTP_PROXY
/etc/origin/master/master-config.yaml:        - name: HTTPS_PROXY
/etc/origin/master/master-config.yaml:        - name: NO_PROXY
/etc/origin/master/master-config.yaml:        - name: http_proxy
/etc/origin/master/master-config.yaml:        - name: https_proxy
/etc/origin/master/master-config.yaml:        - name: no_proxy
/etc/sysconfig/docker:HTTP_PROXY='http://file.rdu.redhat.com:3128'
/etc/sysconfig/docker:HTTPS_PROXY='http://file.rdu.redhat.com:3128'
/etc/sysconfig/docker:NO_PROXY='.cluster.local,.svc,m01.example.com,n01.example.com,n02.example.com'
/etc/sysconfig/atomic-openshift-master:HTTP_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master:HTTPS_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master:NO_PROXY=.cluster.local,.svc,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
/etc/sysconfig/atomic-openshift-master-api:HTTP_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master-api:HTTPS_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master-api:NO_PROXY=.cluster.local,.svc,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
/etc/sysconfig/atomic-openshift-master-controllers:HTTP_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master-controllers:HTTPS_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master-controllers:NO_PROXY=.cluster.local,.svc,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
/etc/sysconfig/atomic-openshift-node:# Origin uses standard HTTP_PROXY environment variables. Be sure to set
/etc/sysconfig/atomic-openshift-node:# NO_PROXY for your master
/etc/sysconfig/atomic-openshift-node:#NO_PROXY=master.example.com
/etc/sysconfig/atomic-openshift-node:#HTTP_PROXY=http://USER:PASSWORD@IPADDR:PORT
/etc/sysconfig/atomic-openshift-node:#HTTPS_PROXY=https://USER:PASSWORD@IPADDR:PORT
/etc/sysconfig/atomic-openshift-node:HTTP_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-node:HTTPS_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-node:NO_PROXY=.cluster.local,.svc,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14

n01.example.com | SUCCESS | rc=0 >>
/etc/origin/master/master-config.yaml:        - name: HTTP_PROXY
/etc/origin/master/master-config.yaml:        - name: HTTPS_PROXY
/etc/origin/master/master-config.yaml:        - name: NO_PROXY
/etc/origin/master/master-config.yaml:        - name: http_proxy
/etc/origin/master/master-config.yaml:        - name: https_proxy
/etc/origin/master/master-config.yaml:        - name: no_proxy
/etc/sysconfig/docker:HTTP_PROXY='http://file.rdu.redhat.com:3128'
/etc/sysconfig/docker:HTTPS_PROXY='http://file.rdu.redhat.com:3128'
/etc/sysconfig/docker:NO_PROXY='.cluster.local,.svc,m01.example.com,n01.example.com,n02.example.com'
/etc/sysconfig/atomic-openshift-master:HTTP_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master:HTTPS_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master:NO_PROXY=.cluster.local,.svc,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
/etc/sysconfig/atomic-openshift-master-api:HTTP_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master-api:HTTPS_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master-api:NO_PROXY=.cluster.local,.svc,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
/etc/sysconfig/atomic-openshift-master-controllers:HTTP_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master-controllers:HTTPS_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master-controllers:NO_PROXY=.cluster.local,.svc,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
/etc/sysconfig/atomic-openshift-node:# Origin uses standard HTTP_PROXY environment variables. Be sure to set
/etc/sysconfig/atomic-openshift-node:# NO_PROXY for your master
/etc/sysconfig/atomic-openshift-node:#NO_PROXY=master.example.com
/etc/sysconfig/atomic-openshift-node:#HTTP_PROXY=http://USER:PASSWORD@IPADDR:PORT
/etc/sysconfig/atomic-openshift-node:#HTTPS_PROXY=https://USER:PASSWORD@IPADDR:PORT
/etc/sysconfig/atomic-openshift-node:HTTP_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-node:HTTPS_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-node:NO_PROXY=.cluster.local,.svc,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
```

# LOG-03

Using inventory params:

```ini
    [OSEv3:vars]

    openshift_no_proxy=m01.example.com,n01.example.com,n02.example.com,foobar.example.com
    openshift_https_proxy=http://file.rdu.redhat.com:3128
    openshift_http_proxy=http://file.rdu.redhat.com:3128

    openshift_master_cluster_method=native
    openshift_master_cluster_hostname=m01.example.com
    openshift_master_cluster_public_hostname=m01.example.com
    openshift_master_default_subdomain=m01.example.com
```


```
[ansible-console]$ grep -ri _proxy /etc/origin/ /etc/sysconfig/
n02.example.com | SUCCESS | rc=0 >>
/etc/origin/master/master-config.yaml:        - name: HTTP_PROXY
/etc/origin/master/master-config.yaml:        - name: HTTPS_PROXY
/etc/origin/master/master-config.yaml:        - name: NO_PROXY
/etc/origin/master/master-config.yaml:        - name: http_proxy
/etc/origin/master/master-config.yaml:        - name: https_proxy
/etc/origin/master/master-config.yaml:        - name: no_proxy
/etc/sysconfig/docker:HTTP_PROXY='http://file.rdu.redhat.com:3128'
/etc/sysconfig/docker:HTTPS_PROXY='http://file.rdu.redhat.com:3128'
/etc/sysconfig/docker:NO_PROXY='.cluster.local,.svc,foobar.example.com,m01.example.com,n01.example.com,n02.example.com'
/etc/sysconfig/atomic-openshift-master:HTTP_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master:HTTPS_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master:NO_PROXY=.cluster.local,.svc,foobar.example.com,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
/etc/sysconfig/atomic-openshift-master-api:HTTP_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master-api:HTTPS_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master-api:NO_PROXY=.cluster.local,.svc,foobar.example.com,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
/etc/sysconfig/atomic-openshift-master-controllers:HTTP_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master-controllers:HTTPS_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master-controllers:NO_PROXY=.cluster.local,.svc,foobar.example.com,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
/etc/sysconfig/atomic-openshift-node:# Origin uses standard HTTP_PROXY environment variables. Be sure to set
/etc/sysconfig/atomic-openshift-node:# NO_PROXY for your master
/etc/sysconfig/atomic-openshift-node:#NO_PROXY=master.example.com
/etc/sysconfig/atomic-openshift-node:#HTTP_PROXY=http://USER:PASSWORD@IPADDR:PORT
/etc/sysconfig/atomic-openshift-node:#HTTPS_PROXY=https://USER:PASSWORD@IPADDR:PORT
/etc/sysconfig/atomic-openshift-node:HTTP_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-node:HTTPS_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-node:NO_PROXY=.cluster.local,.svc,foobar.example.com,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14

n01.example.com | SUCCESS | rc=0 >>
/etc/origin/master/master-config.yaml:        - name: HTTP_PROXY
/etc/origin/master/master-config.yaml:        - name: HTTPS_PROXY
/etc/origin/master/master-config.yaml:        - name: NO_PROXY
/etc/origin/master/master-config.yaml:        - name: http_proxy
/etc/origin/master/master-config.yaml:        - name: https_proxy
/etc/origin/master/master-config.yaml:        - name: no_proxy
/etc/sysconfig/docker:HTTP_PROXY='http://file.rdu.redhat.com:3128'
/etc/sysconfig/docker:HTTPS_PROXY='http://file.rdu.redhat.com:3128'
/etc/sysconfig/docker:NO_PROXY='.cluster.local,.svc,foobar.example.com,m01.example.com,n01.example.com,n02.example.com'
/etc/sysconfig/atomic-openshift-master:HTTP_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master:HTTPS_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master:NO_PROXY=.cluster.local,.svc,foobar.example.com,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
/etc/sysconfig/atomic-openshift-master-api:HTTP_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master-api:HTTPS_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master-api:NO_PROXY=.cluster.local,.svc,foobar.example.com,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
/etc/sysconfig/atomic-openshift-master-controllers:HTTP_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master-controllers:HTTPS_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master-controllers:NO_PROXY=.cluster.local,.svc,foobar.example.com,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
/etc/sysconfig/atomic-openshift-node:# Origin uses standard HTTP_PROXY environment variables. Be sure to set
/etc/sysconfig/atomic-openshift-node:# NO_PROXY for your master
/etc/sysconfig/atomic-openshift-node:#NO_PROXY=master.example.com
/etc/sysconfig/atomic-openshift-node:#HTTP_PROXY=http://USER:PASSWORD@IPADDR:PORT
/etc/sysconfig/atomic-openshift-node:#HTTPS_PROXY=https://USER:PASSWORD@IPADDR:PORT
/etc/sysconfig/atomic-openshift-node:HTTP_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-node:HTTPS_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-node:NO_PROXY=.cluster.local,.svc,foobar.example.com,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14

m01.example.com | SUCCESS | rc=0 >>
/etc/origin/master/master-config.yaml:        - name: HTTP_PROXY
/etc/origin/master/master-config.yaml:        - name: HTTPS_PROXY
/etc/origin/master/master-config.yaml:        - name: NO_PROXY
/etc/origin/master/master-config.yaml:        - name: http_proxy
/etc/origin/master/master-config.yaml:        - name: https_proxy
/etc/origin/master/master-config.yaml:        - name: no_proxy
/etc/sysconfig/docker:HTTP_PROXY='http://file.rdu.redhat.com:3128'
/etc/sysconfig/docker:HTTPS_PROXY='http://file.rdu.redhat.com:3128'
/etc/sysconfig/docker:NO_PROXY='.cluster.local,.svc,foobar.example.com,m01.example.com,n01.example.com,n02.example.com'
/etc/sysconfig/atomic-openshift-master:HTTP_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master:HTTPS_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master:NO_PROXY=.cluster.local,.svc,foobar.example.com,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
/etc/sysconfig/atomic-openshift-master-api:HTTP_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master-api:HTTPS_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master-api:NO_PROXY=.cluster.local,.svc,foobar.example.com,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
/etc/sysconfig/atomic-openshift-master-controllers:HTTP_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master-controllers:HTTPS_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-master-controllers:NO_PROXY=.cluster.local,.svc,foobar.example.com,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
/etc/sysconfig/atomic-openshift-node:# Origin uses standard HTTP_PROXY environment variables. Be sure to set
/etc/sysconfig/atomic-openshift-node:# NO_PROXY for your master
/etc/sysconfig/atomic-openshift-node:#NO_PROXY=master.example.com
/etc/sysconfig/atomic-openshift-node:#HTTP_PROXY=http://USER:PASSWORD@IPADDR:PORT
/etc/sysconfig/atomic-openshift-node:#HTTPS_PROXY=https://USER:PASSWORD@IPADDR:PORT
/etc/sysconfig/atomic-openshift-node:HTTP_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-node:HTTPS_PROXY=http://file.rdu.redhat.com:3128
/etc/sysconfig/atomic-openshift-node:NO_PROXY=.cluster.local,.svc,foobar.example.com,m01.example.com,n01.example.com,n02.example.com,172.30.0.0/16,10.128.0.0/14
```

# LOG-04

Using inventory params:

```ini
    [OSEv3:vars]
    openshift_master_cluster_method=native
    openshift_master_cluster_hostname=m01.example.com
    openshift_master_cluster_public_hostname=m01.example.com
    openshift_master_default_subdomain=m01.example.com
```

```
[ansible-console]$ grep -ri _proxy /etc/origin/ /etc/sysconfig/
n02.example.com | SUCCESS | rc=0 >>
/etc/sysconfig/atomic-openshift-master:# Origin uses standard HTTP_PROXY environment variables. Be sure to set
/etc/sysconfig/atomic-openshift-master:# NO_PROXY for your master
/etc/sysconfig/atomic-openshift-master:#NO_PROXY=master.example.com
/etc/sysconfig/atomic-openshift-master:#HTTP_PROXY=http://USER:PASSWORD@IPADDR:PORT
/etc/sysconfig/atomic-openshift-master:#HTTPS_PROXY=https://USER:PASSWORD@IPADDR:PORT
/etc/sysconfig/atomic-openshift-node:# Origin uses standard HTTP_PROXY environment variables. Be sure to set
/etc/sysconfig/atomic-openshift-node:# NO_PROXY for your master
/etc/sysconfig/atomic-openshift-node:#NO_PROXY=master.example.com
/etc/sysconfig/atomic-openshift-node:#HTTP_PROXY=http://USER:PASSWORD@IPADDR:PORT
/etc/sysconfig/atomic-openshift-node:#HTTPS_PROXY=https://USER:PASSWORD@IPADDR:PORT

m01.example.com | SUCCESS | rc=0 >>
/etc/sysconfig/atomic-openshift-master:# Origin uses standard HTTP_PROXY environment variables. Be sure to set
/etc/sysconfig/atomic-openshift-master:# NO_PROXY for your master
/etc/sysconfig/atomic-openshift-master:#NO_PROXY=master.example.com
/etc/sysconfig/atomic-openshift-master:#HTTP_PROXY=http://USER:PASSWORD@IPADDR:PORT
/etc/sysconfig/atomic-openshift-master:#HTTPS_PROXY=https://USER:PASSWORD@IPADDR:PORT
/etc/sysconfig/atomic-openshift-node:# Origin uses standard HTTP_PROXY environment variables. Be sure to set
/etc/sysconfig/atomic-openshift-node:# NO_PROXY for your master
/etc/sysconfig/atomic-openshift-node:#NO_PROXY=master.example.com
/etc/sysconfig/atomic-openshift-node:#HTTP_PROXY=http://USER:PASSWORD@IPADDR:PORT
/etc/sysconfig/atomic-openshift-node:#HTTPS_PROXY=https://USER:PASSWORD@IPADDR:PORT

n01.example.com | SUCCESS | rc=0 >>
/etc/sysconfig/atomic-openshift-master:# Origin uses standard HTTP_PROXY environment variables. Be sure to set
/etc/sysconfig/atomic-openshift-master:# NO_PROXY for your master
/etc/sysconfig/atomic-openshift-master:#NO_PROXY=master.example.com
/etc/sysconfig/atomic-openshift-master:#HTTP_PROXY=http://USER:PASSWORD@IPADDR:PORT
/etc/sysconfig/atomic-openshift-master:#HTTPS_PROXY=https://USER:PASSWORD@IPADDR:PORT
/etc/sysconfig/atomic-openshift-node:# Origin uses standard HTTP_PROXY environment variables. Be sure to set
/etc/sysconfig/atomic-openshift-node:# NO_PROXY for your master
/etc/sysconfig/atomic-openshift-node:#NO_PROXY=master.example.com
/etc/sysconfig/atomic-openshift-node:#HTTP_PROXY=http://USER:PASSWORD@IPADDR:PORT
/etc/sysconfig/atomic-openshift-node:#HTTPS_PROXY=https://USER:PASSWORD@IPADDR:PORT
```

**Comment by tbielawa** [comment]
aos-ci-test

**Comment by tbielawa** [comment]
[test]

**Comment by tbielawa** [comment]
Flake https://github.com/openshift/origin/issues/15356

**Comment by tbielawa** [comment]
re[test]

**Comment by tbielawa** [comment]
[merge][severity:blocker]

**Comment by sdodson** [comment]
If QE tests this and we're good to go we should backport the net change between master and release-1.5/1.4 back there. No need to backport the intermediate steps. But lets wait for QE to sign off on the change before wasting time on that.

**Pull request merged**
