### PR TITLE
Update console config for API changes

### PR DESCRIPTION
**Pull request by spadgett**
Adopt API changes from https://github.com/openshift/api/pull/31

For now, both the new and old config need to be written to avoid breaking install until origin-web-console-server is updated.

/assign @sdodson 
@deads2k @jwforres FYI

### CODE REVIEW

**Comment by deads2k** [comment]
Right idea. Let me know when it is ready for review.

**Comment by spadgett** [comment]
Corresponding origin changes: https://github.com/openshift/origin/pull/18114

**Comment by spadgett** [comment]
I was able to test with the changes from https://github.com/openshift/origin-web-console-server/pull/20

@sdodson @deads2k this should be ready for a review

**Comment by deads2k** [comment]
The config file lgtm.

**Comment by spadgett** [comment]
Rebased

**Comment by spadgett** [comment]
@sdodson updated

**Comment by sdodson** [comment]
It's waiting on travis but travis is backlogged according to their status page. Haven't seen a travis job post in ~5hrs.

**Pull request merged**
