### PR TITLE
Deprecate installer_checkpoint

### PR DESCRIPTION
**Pull request by mtnbikenc**
This role is no longer necessary.

### CODE REVIEW

**Comment by mtnbikenc** [comment]
```
level=fatal msg="failed to initialize the cluster: timed out waiting for the condition"
```
/retest

**Comment by mtnbikenc** [comment]
The test passed, then flaked when it reran after lgtm.  Ugh.
```
level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply using Terraform"
```
/retest

**Comment by mtnbikenc** [comment]
```
fatal: [localhost]: FAILED! => 
  msg: 'The conditional check ''svc.results.results[0].status.loadBalancer.ingress | length > 0'' failed. The error was: error while evaluating conditional
```
/retest

**Comment by mtnbikenc** [comment]
```
Failing tests:

[Conformance][Area:Networking][Feature:Router] The default ClusterIngress should support default wildcard reencrypt routes through external DNS [Suite:openshift/conformance/parallel/minimal]
[Feature:Builds] build have source revision metadata  started build should contain source revision information [Suite:openshift/conformance/parallel]
[Feature:Builds] result image should have proper labels set  S2I build from a template should create a image from "test-s2i-build.json" template with proper Docker labels [Suite:openshift/conformance/parallel]
[sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should perform rolling updates and roll backs of template modifications with PVCs [Suite:openshift/conformance/parallel] [Suite:k8s]
```
/retest

**Comment by vrutkovs** [comment]
```
Failing tests:

[Feature:Platform] Managed cluster should have no crashlooping pods in core namespaces over two minutes [Suite:openshift/conformance/parallel]
```
/retest

**Comment by mtnbikenc** [comment]
Crashlooping pods is due to https://github.com/openshift/machine-config-operator/pull/495

**Comment by mtnbikenc** [comment]
Two consecutive failures on the same test with a known fix in the works.  Merging.

**Pull request merged**
