### PR TITLE
Do not attempt to override openstack nodename

### PR DESCRIPTION
**Pull request by detiber**

### CODE REVIEW

**Comment by detiber** [comment]
@cooktheryan @jianlinliu I don't currently have an environment to test against to validate these changes.

**Comment by detiber** [comment]
aos-ci-test

**Comment by cooktheryan** [comment]
@markllama @tomassedovic wanted to get your guys input on this

**Comment by detiber** [comment]
@sdodson I'm hoping that it reverts enough. I mainly do not want to invalidate testing that has already happened with other platforms using nodename :)

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
@sdodson this should be good to go now. I only created this against release-1.5, since I wasn't sure if we wanted to try to solve this better for 1.6/3.6.

**Comment by sdodson** [comment]
Yeah, I think it's best if we could come up with a better solution for 1.6.

**Pull request merged**
