### PR TITLE
Allowing non-root users to sync the examples directory

### PR DESCRIPTION
**Pull request by brenton**

### CODE REVIEW

**Comment by brenton** [comment]
@twiest, @jwhonce, @sdodson, PTAL

Using copy is pretty slow for this many files.  Originally I looked in to only using copy to push out the handful of files we needed but the more I looked at the contents the more I thought people would want them all.  I then looked at complicated ways of rsync'ing to a tmp dir and moving things where they were needed but that turned out way to complex for something this simple.  Ideally, I just want something that we can rip out if when we are able to package these things properly.

**Comment by sdodson** [comment]
If we switch back to synchronize let's merge in #300

**Comment by jwhonce** [comment]
@sdodson @brenton This fix fails for me when I do

````
$ bin/cluster create gce jhonce

TASK: [openshift_examples | Copy openshift examples] ************************** 
failed: [jhonce-master-b61b9 -> 127.0.0.1] => {"cmd": "rsync --delay-updates -F --compress --recursive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' \"/home/jhonce/Projects/openshift-ansible/playbooks/common/openshift-master/roles/openshift_examples/files/examples\" \"jhonce@104.197.45.207:/usr/share/openshift\"", "failed": true, "rc": 255}
msg: Warning: Permanently added '104.197.45.207' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.1]


FATAL: all hosts have already failed -- aborting
```

I can ssh into the master without giving a password, So I'm unsure why rsync fails.  This was the same behavior I and others saw that lead to removing synchronize in #303

**Comment by brenton** [comment]
Crazy. I guess copy it is then.

**Comment by detiber** [comment]
@brenton The issue I saw with synchronize is that it failed to work with a sudo user set.  

The workaround I did was to create a tarball of the files and use the unarchive module to extract that tarball on the host. It's not the cleanest solution by any means, but in the end it appears to remain idempotent over runs.

**Pull request closed without merging**
