### PR TITLE
pyOpenSSL is now python2-pyOpenSSL in RHEL

### PR DESCRIPTION
**Pull request by vrutkovs**
This should unblock the CI

### CODE REVIEW

**Comment by sdodson** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/9159/pull-ci-openshift-openshift-ansible-e2e-gcp/1377/  is the problem this intends to fix.

**Comment by vrutkovs** [comment]
It certainly fixes `ci/prow/unit` - https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/9607/pull-ci-openshift-openshift-ansible-unit/1240/

**Comment by sdodson** [comment]
/retest
Looks like metadata has been updated though rpms still exist on the mirrors.

**Comment by vrutkovs** [comment]
No longer needed - it seems a wrong RPM has been tagged in CentOS repos

**Pull request closed without merging**
