### PR TITLE
Wrap docker stop in retries

### PR DESCRIPTION
**Pull request by sdodson**

### CODE REVIEW

**Comment by sdodson** [comment]
@ashcrow PTAL

This should cover all places where we're stopping an individual service. There's a few places where we loop through services and we'll want to investigate how to deal with those in the future but I think this will be good enough for now.

**Comment by ashcrow** [comment]
@sdodson LGTM. Merge away.

**Comment by ashcrow** [comment]
@sdodson I do see a few more places that stop docker ...

**Comment by sdodson** [comment]
@ashcrow I ignored anything in playbooks/adhoc as those shouldn't be used.

**Pull request merged**
