### PR TITLE
Bug 1808068: Add /usr/share/pki to sync pod

### PR DESCRIPTION
**Pull request by mtnbikenc**

### CODE REVIEW

**Comment by mtnbikenc** [comment]
Bug tags are not applicable to the release-3.11 branch.

**Comment by petr-muller** [comment]
/hold

There's no point in retesting this after ~400 attempts

**Comment by mtnbikenc** [comment]
CI issues should be resolved.
/hold cancel

**Comment by petr-muller** [comment]
/bugzilla refresh
/hold

Holding to stop the apparently endless retests.

**Comment by mtnbikenc** [comment]
No changes, just force-pushed to get a new SHA.

**Comment by mtnbikenc** [comment]
/test e2e-aws
```
Summarizing 4 Failures:

[Fail] [Feature:Builds][Conformance] jenkins autoprovision Pipeline build config [It] should autoprovision jenkins [Suite:openshift/conformance/parallel/minimal] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/builds/jenkins_autoprovision.go:46

[Fail] [Feature:DeploymentConfig] deploymentconfigs paused [Conformance] [It] should disable actions on deployments [Suite:openshift/conformance/parallel/minimal] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:793

[Fail] [sig-cli] Kubectl client [k8s.io] Update Demo [It] should scale a replication controller  [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/util.go:2230

[Fail] [Feature:DeploymentConfig] deploymentconfigs with test deployments [Conformance] [It] should run a deployment to completion and then scale to zero [Suite:openshift/conformance/parallel/minimal] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:374
```

**Comment by mtnbikenc** [comment]
/test e2e-aws

```
Summarizing 3 Failures:
[Fail] [Feature:DeploymentConfig] deploymentconfigs adoption [Conformance] [It] will orphan all RCs and adopt them back when recreated [Suite:openshift/conformance/parallel/minimal] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:1657
[Fail] [Feature:DeploymentConfig] deploymentconfigs with test deployments [Conformance] [It] should run a deployment to completion and then scale to zero [Suite:openshift/conformance/parallel/minimal] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:374
[Fail] [Feature:DeploymentConfig] deploymentconfigs with revision history limits [Conformance] [It] should never persist more old deployments than acceptable after being observed by the controller [Suite:openshift/conformance/parallel/minimal] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:969
```

**Comment by mtnbikenc** [comment]
```
Summarizing 3 Failures:

[Fail] [Feature:DeploymentConfig] deploymentconfigs with test deployments [Conformance] [It] should run a deployment to completion and then scale to zero [Suite:openshift/conformance/parallel/minimal] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:348

[Fail] [sig-cli] Kubectl client [k8s.io] Update Demo [It] should scale a replication controller  [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/util.go:2230

[Fail] [sig-cli] Kubectl client [k8s.io] Update Demo [It] should do a rolling update of a replication controller  [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/util.go:2230
```

**Comment by mtnbikenc** [comment]
Bug tags are not applicable to the release-3.11 branch.

**Comment by mtnbikenc** [comment]
Retest after #12156 merges.

**Pull request merged**
