### PR TITLE
Cluster Metrics

### PR DESCRIPTION
**Pull request by spinolacastro**

### CODE REVIEW

**Comment by detiber** [comment]
@spinolacastro only issues I have are that this is using the kube read only port and it will conflict with https://github.com/openshift/openshift-ansible/pull/460 (which allows for setting the kubeletArguments on the node.

I know there were discussion upstream about supporting this over the secured kube port, but I'm not sure the outcome of those.  If we can't get around using the read only port at this time, I would prefer that we document that this is potentially a security risk.

**Comment by spinolacastro** [comment]
@detiber i can fix the conflict.
I'm don't like those open ports  but i couldn't  figure out a way to make the cluster running without them.
Perhaps we could tweak the firewall rules to be a little more restrictive, ( internal network )?

**Comment by detiber** [comment]
@spinolacastro I think as long as we document the potential security implications (in the README for the openshift_cluster_metrics_role) I think we are good enough.  I expect that most installations will have some type of hardware firewall or security groups configuration that could be leveraged to limit exposure.

**Comment by spinolacastro** [comment]
@detiber Done.

**Comment by detiber** [comment]
:+1: looks good to me.

@wshearn I see this as more of an "origin" and/or undocumented feature (outside of the role documentation) until we can support heapster without needing the kubelet read only port opened.

@brenton ^ just a heads up that initial support is hear for cluster metrics, but I don't see it as something we want to advertise or support for enterprise until we've eliminated the need for the read only kubelet port. https://github.com/openshift/origin/issues/3020 is the issue for tracking the feature on the openshift side.

**Comment by spinolacastro** [comment]
@detiber Do you need anything else to merge?

**Comment by detiber** [comment]
@wshearn @twiest please review/merge

**Comment by wshearn** [comment]
Looks good to me, default only touches origin so :+1:

**Pull request merged**
