### PR TITLE
Guard check for container install based on openshift dictionary key

### PR DESCRIPTION
**Pull request by admiyo**

### CODE REVIEW

**Comment by sdodson** [comment]
bot, test pull request

**Comment by sdodson** [comment]
@abutcher I guess this is necessary because it's run across host group and we may hit another node that hasn't had facts collected?

**Comment by admiyo** [comment]
Yes, I was seeing this when running on a two node cluster.  Without this change, the expresssion was erroring out with an error indicating that the openshift dictionary had not been created.

**Comment by sdodson** [comment]
aos-ci-test

**Comment by abutcher** [comment]
bot, retest this please

**Comment by abutcher** [comment]
@sdodson Right, I can see this being a problem if one of the hosts were unavailable or had received a previous error. We collect facts for all `oo_nodes_to_config` in the play prior to the changes so I would expect facts to be set.

**Comment by abutcher** [comment]
[merge]

**Pull request merged**
