### PR TITLE
Add EAP CD templates to v3.10

### PR DESCRIPTION
**Pull request by luck3y**
This is a followup to https://github.com/openshift/openshift-ansible/pull/8091 to add the EAP CD templates. Sorry, I thought I'd included these in the previous PR.

### CODE REVIEW

**Comment by luck3y** [comment]
@bstansberry FYI

**Comment by vrutkovs** [comment]
v3.9 templates should go into a separate PR against `release-3.9`, as master (3.10) branch cannot be used to setup 3.9

**Comment by vrutkovs** [comment]
bot, add author to whitelist

**Comment by vrutkovs** [comment]
bot, retest this please

**Comment by luck3y** [comment]
rebased on master and updated to drop the v3.9 parts.

**Comment by luck3y** [comment]
bot, /test install

**Comment by luck3y** [comment]
@vrutkovs Is there an issue with the /install and /system-container tests, do you know? Looking at the results I don't see why they're failing, and looling at the PR queue, I see them failing a lot.

**Comment by luck3y** [comment]
@vrutkovs Thanks, that seems better now! :)

**Comment by vrutkovs** [comment]
This looks good to me, can we get someone to verify the contents are correct?

**Pull request merged**
