### PR TITLE
pylint: disable travis error

### PR DESCRIPTION
**Pull request by vrutkovs**
pylint error was introduced in #9315

### CODE REVIEW

**Comment by sdodson** [comment]
@vrutkovs Can you push this commit to the cherrypick branches for #9315, create new PRs with both commits, or just green button them at the same time? I just want to reduce the time that downstream branches are broken however you'd like to do that.

**Comment by vrutkovs** [comment]
@sdodson yeah, I amended a fix for those in cherrypick branches already

**Pull request merged**
