### PR TITLE
Update glusterfs-template

### PR DESCRIPTION
**Pull request by SaravanaStorageNetwork**
- Add GB_LOGDIR
 - failureThreshold as 50 secs

Signed-off-by: Saravanakumar Arumugam <sarumuga@redhat.com>

### CODE REVIEW

**Comment by SaravanaStorageNetwork** [comment]
@jarrpa  Please check

**Comment by jarrpa** [comment]
This is a relatively minor patch. As long as it passes tox, we should be good to go.

/ok-to-test
/lgtm

**Comment by jarrpa** [comment]
@sdodson @michaelgugino What's this papr-bot thing?

**Comment by michaelgugino** [comment]
@jarrpa That's for running fedora-atomic tests.

**Comment by michaelgugino** [comment]
bot, test pull request

**Comment by DanyC97** [comment]
@SaravanaStorageNetwork wouldn't have been nice to carry on making the changes on `files/v3.{7,6}` too? :)

**Comment by jarrpa** [comment]
@DanyC97 We will do that once 3.9 finishes QA.

**Comment by SaravanaStorageNetwork** [comment]
@sdodson @michaelgugino  @jarrpa  Could you check - this is keep failing

**Pull request merged**
