### PR TITLE
Add iptables rules for flannel

### PR DESCRIPTION
**Pull request by imcsk8**
[WIP] When using flannel there are iptables rules that need
to be added as stated here:

https://access.redhat.com/documentation/en-us/reference_architectures/2017/html-single/deploying_red_hat_openshift_container_platform_3.4_on_red_hat_openstack_platform_10/#run_ansible_installer

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1493955

### CODE REVIEW

**Comment by pravisankar** [comment]
@imcsk8 
Tests are failing with this error:
```
yaml.scanner.ScannerError: mapping values are not allowed here
  in "/data/src/github.com/openshift/openshift-ansible/roles/flannel/tasks/main.yml", line 45, column 11

The error appears to have been in '/usr/share/ansible/openshift-ansible/roles/flannel/tasks/main.yml': line 45, column 11, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  command: /sbin/iptables --wait -I FORWARD -d {{ hostvars[groups.oo_first_master.0].openshift.master.sdn_cluster_network_cidr }} -i {{ flannel_interface }} -j ACCEPT -m comment --comment "Pod to Pod communication"
    notify:
          ^ here
```

**Comment by pravisankar** [comment]
Failed with  "Tag v3.7.0-rc.0 not found in repository docker.io/openshift/origin"
/retest

**Comment by knobunc** [comment]
@sdodson Can you help with this please?

**Comment by sdodson** [comment]
@imcsk8 The handlers aren't global so you'll need to replicate the handler from here into roles/flannel/handlers/main.yml
https://github.com/openshift/openshift-ansible/blob/master/roles/nuage_node/handlers/main.yaml#L6-L8

Also, try putting single quotes around the entire command.

**Comment by knobunc** [comment]
@imcsk8 any updates?

**Comment by knobunc** [comment]
@sdodson Thanks!

**Pull request merged**
