### PR TITLE
Ensure that openshift_node_facts has been called for dns_ip

### PR DESCRIPTION
**Pull request by sdodson**

### CODE REVIEW

**Comment by sdodson** [comment]
@csrwng this may fix the issue you're seeing

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
@csrwng did this help? locally it works for me with and without the change

**Comment by csrwng** [comment]
So tried patching the change into the 3.6 branch and of course didn't work. Is it ok to use master to install a 3.6 cluster?

**Comment by csrwng** [comment]
Output:

```
ERROR! the role 'openshift_node_facts' was not found in /home/azureuser/openshift-ansible/playbooks/byo/openshift-cluster/../../common/openshift-cluster/../openshift-node/roles:/etc/ansible/roles:/home/azureuser/openshift-ansible/roles:/home/azureuser/openshift-ansible/playbooks/byo/openshift-cluster/../../common/openshift-cluster/../openshift-node

The error appears to have been in '/home/azureuser/openshift-ansible/roles/openshift_node_dnsmasq/meta/main.yml': line 16, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- role: openshift_common
- role: openshift_node_facts
  ^ here
```

**Comment by sdodson** [comment]
Yeah, master branch should work for 3.6 installs.

**Comment by csrwng** [comment]
Trying that now

**Comment by csrwng** [comment]
@sdodson so this looks good. I got past the error in my deployment. Now I get another one about not having an etcd host, will try to sort it out.

**Comment by sdodson** [comment]
[merge]

**Comment by sdodson** [comment]
Merge would be blocked by the fact that this needs to be fixed on both master and release-3.6 branches. #5147 to fix on release-3.6 branch

**Comment by jhadvig** [comment]
The issue is still reproducable... Our install_upgrade job is failing due to it 
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/4460/consoleFull#39147885258b6e51eb7608a5981914356

**Comment by sdodson** [comment]
@jhadvig that job used openshift-ansible-3.6.173.0.7-1.git.0.f6f19ed.el7 which is from before this merged even though the job ran after it. Any idea why?

**Comment by jhadvig** [comment]
@sdodson that version we are using for installation of origin. and then we are upgrading to the latest version.
The idea of that job is to install the latest available version of previous minor release (in this case 3.6.x) and upgrade to the last minor version release (in this case 3.7.x)

**Pull request merged**
