### PR TITLE
[WIP] Use provided node iam role name rather than using hard coded value.

### PR DESCRIPTION
**Pull request by abutcher**

### CODE REVIEW

**Comment by abutcher** [comment]
@csrwng Good point, I don't understand why we're moving away from cluster specific role names / roles but that would need to be changed as well.

**Comment by csrwng** [comment]
@abutcher the reason is that the deprovisioning of those roles introduced a few problems. @joelddiaz may have more context

**Comment by joelddiaz** [comment]
@abutcher @csrwng IIRC there was a fear about AWS letting you remove iam roles that are actively in use. Running instances that could run ec2:DescribeInstances suddenly would lose the ability, and scale groups would fail to scale up because the iam role went missing.

**Comment by vrutkovs** [comment]
Master branch is closed! A major refactor is ongoing in devel-40. Changes for 3.x should be made directly to the latest release branch they're relevant to and backported from there.

**Pull request closed without merging**
