### PR TITLE
use openshift_image_tag default for prometheus_node_exporter image

### PR DESCRIPTION
**Pull request by aweiteka**
Signed-off-by: Aaron Weitekamp <aweiteka@redhat.com>

/cc @pgier

### CODE REVIEW

**Comment by pgier** [comment]
LGTM, but it looks like the node_exporter container isn't set up yet for automatic build/tag with the rest of the openshift containers.  I'll follow up with RCM to get this set up.

**Comment by aweiteka** [comment]
@pgier sounds good. Let's merge this once the 3.9 tag is confirmed. We need to get this in by the 3.9 release.

**Comment by aweiteka** [comment]
Images have landed. /retest

Output (truncated/redacted):
```
$ curl -X GET -k <REGISTRY_URL>/v1/repositories/openshift3/prometheus-node-exporter/tags | python -m json.tool
{
    "0.15.2": "2590ebd50e53e243ae57ecaca44a9f4410ba7d468622eec649bebbd953949acf",
    "0.15.2-1": "2590ebd50e53e243ae57ecaca44a9f4410ba7d468622eec649bebbd953949acf",
    "latest": "54799bb6d52c7852b69d20c9982b78b004c3e7cfe2f37b462dcae645b94b30c6",
    "v0.15.2": "894aa1c2714770dfcb40fc7e8f3866a7e3f998db9dd8b21eebebbd95d9968d5c",
    "v0.15.2-1": "894aa1c2714770dfcb40fc7e8f3866a7e3f998db9dd8b21eebebbd95d9968d5c",
    "v3.9": "54799bb6d52c7852b69d20c9982b78b004c3e7cfe2f37b462dcae645b94b30c6",
    "v3.9.10": "d923e17649b8ba65515193b64f8e0fe15b23b5a7b1ea0acede1397509ac0a094",
    "v3.9.10-1": "d923e17649b8ba65515193b64f8e0fe15b23b5a7b1ea0acede1397509ac0a094",
    "v3.9.10.20180315.142724": "d923e17649b8ba65515193b64f8e0fe15b23b5a7b1ea0acede1397509ac0a094",
    "v3.9.11": "54799bb6d52c7852b69d20c9982b78b004c3e7cfe2f37b462dcae645b94b30c6",
    "v3.9.11-1": "54799bb6d52c7852b69d20c9982b78b004c3e7cfe2f37b462dcae645b94b30c6",
    "v3.9.11.20180315.181300": "54799bb6d52c7852b69d20c9982b78b004c3e7cfe2f37b462dcae645b94b30c6",
    "v3.9.8": "7ddf429234a77e029845dc5a6407df33e7980efd3ebb8512d59a73b2fa9358e4",
    "v3.9.8-1": "7ddf429234a77e029845dc5a6407df33e7980efd3ebb8512d59a73b2fa9358e4",
    "v3.9.8.20180313.172024": "7ddf429234a77e029845dc5a6407df33e7980efd3ebb8512d59a73b2fa9358e4",
    "v3.9.9": "ca3c74c435f1b05251ccc6654e7cda0d7cc1acc53d39d18fdc62f6bd22c0108c",
    "v3.9.9-1": "ca3c74c435f1b05251ccc6654e7cda0d7cc1acc53d39d18fdc62f6bd22c0108c",
    "v3.9.9.20180314.185428": "ca3c74c435f1b05251ccc6654e7cda0d7cc1acc53d39d18fdc62f6bd22c0108c"
}
```

**Comment by aweiteka** [comment]
[retest]

**Comment by aweiteka** [comment]
@pgier is this approved?

**Comment by pgier** [comment]
The node_exporter image is now tagged for openshift 3.9, so this should be ok to merge
/lgtm

**Comment by pgier** [comment]
lgtm

**Pull request merged**
