### PR TITLE
Remove openshift_clock role

### PR DESCRIPTION
**Pull request by michaelgugino**
This commit removes the openshift_clock role, which
may be called various times throughout the deployment
as it is needed by various components.

This commit moves the clock bits to init/base_packages.yml
which is called by prerequisites.

### CODE REVIEW

**Comment by vrutkovs** [comment]
bot, retest this please

**Comment by vrutkovs** [comment]
It seems to skip this step on Atomic

**Comment by vrutkovs** [comment]
```

TASK [Start and enable ntpd/chronyd] *******************************************
Tuesday 24 April 2018  14:57:40 +0000 (0:00:00.048)       0:00:08.084 ********* 
skipping: [ocp-master] => {"changed": false, "skip_reason": "Conditional result was False"}
skipping: [ocp-node1] => {"changed": false, "skip_reason": "Conditional result was False"}
skipping: [ocp-node2] => {"changed": false, "skip_reason": "Conditional result was False"}
```

I wonder why is being skipped -  `openshift_clock_enabled` must be explicitely set to False to skip this. 

The problem is that it may cause certs to be invalid and thus cause us more flakes in the future

**Comment by michaelgugino** [comment]
@vrutkovs It appears atomic CI is no longer calling prerequisites.yml

**Comment by vrutkovs** [comment]
@michaelgugino right, that would explain it. Lets fix `papr.sh` in this PR then

**Comment by michaelgugino** [comment]
bot, retest this please

**Comment by vrutkovs** [comment]
bot, retest this please

**Pull request merged**
