### PR TITLE
[3.6] Remove unsupported parameters from example inventory files.

### PR DESCRIPTION
**Pull request by jarrpa**
Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>

### CODE REVIEW

**Comment by sdodson** [comment]
When you create a backport can you link to the master branch pr too so they reference each other?
https://github.com/openshift/openshift-ansible/pull/4858

**Comment by sdodson** [comment]
and link to the bz too :-)

**Comment by jarrpa** [comment]
Do you want that in the commit message, too?

**Comment by sdodson** [comment]
Yeah, either the commit or the PR description. If "Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1474692" is in the commit or description of the PR when it merges then it will post a comment to the BZ when things are merged.

**Comment by jarrpa** [comment]
Ah, okay. Is "Fixed" a keyword?

**Pull request merged**
