### PR TITLE
Update inventory file for ansible playbook for OSE deployment.

### PR DESCRIPTION
**Pull request by ingvagabund**
Update inventory file for ansible playbook for OSE deployment:

- enterprise value for deployment_type is depricated. Use openshift-enterprise instead.
- key=value pairs must be on the same line

### CODE REVIEW

**Comment by ingvagabund** [comment]
@ncdc

**Comment by ingvagabund** [comment]
@sdodson, @detiber, @brenton

**Comment by abutcher** [comment]
@brenton lgtm

**Comment by detiber** [comment]
@brenton @abutcher Should we just point them to the official docs here instead?

**Comment by abutcher** [comment]
@detiber If we're going that route I'd prefer to delete this README and link from the root README

**Comment by detiber** [comment]
@abutcher sounds good to me

**Comment by ingvagabund** [comment]
@abutcher got the link? I will update the README so it is covered in this PR. What about README for origin? The same or keep the way it is?

**Comment by abutcher** [comment]
@ingvagabund OSE: https://docs.openshift.com/enterprise/latest/install_config/install/index.html Origin: https://docs.openshift.org/latest/install_config/install/index.html

**Comment by abutcher** [comment]
@ingvagabund Blow em both away :smile:

**Comment by ingvagabund** [comment]
Find those two better:

* https://docs.openshift.org/latest/install_config/install/advanced_install.html
* https://docs.openshift.com/enterprise/latest/install_config/install/advanced_install.html

This repo is about ansible so let's reference ansible way of making the world

**Comment by abutcher** [comment]
@brenton PTAL

**Pull request merged**
