### PR TITLE
[1.3] Fix origin repo deployment

### PR DESCRIPTION
**Pull request by michaelgugino**
Currently, origin deployments place a repo on nodes and
masters named centos-openshift-origin. At some point,
the maintainers of centos-openshift-origin migrated
previous releases of openshift to their own respective
repositories.

This commit provides the correct repositories for
centos-openshift-origin based on the variable openshift_release,
defaulting to the latest release reposititory (unversioned).

Fixes: https://github.com/openshift/openshift-ansible/issues/5404
(cherry picked from commit b2d72ae1c08525c322113713571b9c0d096e36c5)

Back-ports: #5538

### CODE REVIEW

**Comment by ashcrow** [comment]
I'm going to guess that ``tox`` was not in use this far back.

```
ERROR: toxini file 'tox.ini' not found
```

@sdodson I recommend manual merge if other tests come back green.

**Comment by ashcrow** [comment]
```
Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"OS_ONLY_BUILD_PLATFORMS=linux/amd64\\\": stat OS_ONLY_BUILD_PLATFORMS=linux/amd64: no such file or directory\"\n"
Error: failed to start containers: 87d326c7beac0640e9c9c19fa9a49859a19fd98247f95663e5f60133f09a5cb4
```

**Comment by ashcrow** [comment]
Based on the significant differences in code between 1.5+ and 1.3 in CI I sort of want to recommend not backporting especially if 1.3 is past it's prime.

@sdodson WDYT?

**Comment by sdodson** [comment]
Without this change users cannot install Origin 1.3, the packages no longer exist in the repos currently referenced.

I believe we should merge this without CI. Worst case they're still just as broken as they are today.

**Comment by sdodson** [comment]
That said, no one should have an expectation that we continue to fix 1.3 bugs. So, maybe not fixing this is the best indicator of that.

**Pull request closed without merging**
