### PR TITLE
GCP node tags can be provided instead hardcoded

### PR DESCRIPTION
**Pull request by e-minguez**
Fixes https://github.com/openshift/openshift-ansible/issues/7979

### CODE REVIEW

**Comment by cooktheryan** [comment]
:+1:

**Comment by e-minguez** [comment]
Unrelated CI issues it seems... triggering a new test with /retest

**Comment by e-minguez** [comment]
CI complains about:
`RetryError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/ed/84/09e8dd117081db2077cf08dbd670a3454ab0265b05e8e7f75482492b46f0/ansible-2.4.3.0.tar.gz (Caused by ResponseError('too many 503 error responses',))`

**Comment by michaelgugino** [comment]
I'm not sure we want to make this configurable.  @smarterclayton

**Comment by sdodson** [comment]
bot, retest this please

**Comment by smarterclayton** [comment]
We don’t want this because the dynamic provisioning node groups (what is used to set up the gcp scale groups) already allow this to be set as additional tags.

**Comment by smarterclayton** [comment]
Specifically https://github.com/openshift/release/blob/master/cluster/test-deploy/gcp/vars.yaml in openshift_gcp_node_group_config

**Comment by e-minguez** [comment]
I'm ok on closing it but then we should document that if users want to create loadbalancer services types in gcp they should tag their instances with that particular tag, otherwise the firewall rules won't apply to nodes.
I'm thinking in byo instances scenario as the gcp instances creation code is not GA yet, am I right?

**Comment by jkupferer** [comment]
I was just reviewing this code and I think the wrong call was made here. We cannot assume that we can dictate the firewall tagging policy of an enterprise. We can recommend that they go with the default, but we should allow this node tag to be configurable.

Working as an architect with my current client running 20+ OCP clusters, the PaaS group which manages the clustes does not have access to set policy for firewall tags or change firewall rules. They definitely cannot use tags that include a cluster specific prefix.

**Pull request closed without merging**
