### PR TITLE
Conditionally add in a Calico v3 manifest and upgrade path to facilitate upgrades.

### PR DESCRIPTION
**Pull request by mgleung**
To upgrade Calico from v2.6.5+ to v3+, a data migration is needed from etcdv2 to etcdv3. These changes attempt to add in another manifest to be used for any version of v3+ as well as an init container to handle the data migration should it be necessary to facilitate any upgrade from Calico v2.6.5+ to v3. The init container will not trigger any data migration unless it is needed (there is no Calico data in etcdv3 and there is Calico etcdv2 data). For any OpenShift user, the process of upgrading/installing Calico will not change, only when specific Calico versions are used, will the proper manifests be created and applied.

### CODE REVIEW

**Comment by sdodson** [comment]
@mgleung Are there any plans to move to using CRDs rather than direct etcd access?

**Comment by mgleung** [comment]
@sdodson Currently we are focused on cleaning up the experience for our users on etcd. We will want to additionally support using CRDs, but as of now, there is no concrete plan or timetable.

**Comment by vrutkovs** [comment]
bot, test pull request

**Pull request merged**
