### PR TITLE
Add service catalog to be upgraded

### PR DESCRIPTION
**Pull request by jpeeler**
Currently service catalog was left running at the previous version.

https://bugzilla.redhat.com/show_bug.cgi?id=1541247

### CODE REVIEW

**Comment by jpeeler** [comment]
flakes:
openshift/origin#17641 for crio test failure
https://github.com/openshift/origin/issues/17882 for install test failure

**Comment by sdodson** [comment]
/lgtm
I think we need to check TSB and ASB to ensure that they're similarly idempotent and make sure to add them to the upgrade. I'm pretty sure the TSB is not idempotent as it relies on `oc create`.

**Pull request merged**
