### PR TITLE
Require ansible 2.6, allow ansible 2.7

### PR DESCRIPTION
**Pull request by vrutkovs**
Update ansible version to changes in https://cbs.centos.org/repos/configmanagement7-ansible-27-testing/x86_64/os/Packages/

### CODE REVIEW

**Comment by DanyC97** [comment]
my suggestion will be to use https://github.com/openshift/openshift-ansible/pull/11254#issuecomment-468613786 repo rather than cbs which is (according to the CentOS Infra guys used for dev and not for user consumption)

**Comment by vrutkovs** [comment]
>my suggestion will be to use [#11254 (comment)](https://github.com/openshift/openshift-ansible/pull/11254#issuecomment-468613786) repo rather than cbs which is (according to the CentOS Infra guys used for dev and not for user consumption)

Oh, okay, we could move to the new repo later on. Lets merge this PR to unblock others, that'd give us time to reorganize the repos

**Comment by DanyC97** [comment]
sounds good to me

**Pull request merged**
