### PR TITLE
fix bz 1550271: restore mpath defaults config

### PR DESCRIPTION
**Pull request by rootfs**
Per conversation with Benjamin Marzinski, need to restore default config to fix the BZ

### CODE REVIEW

**Comment by rootfs** [comment]
cc @eparis @childsb @tsmetana

**Comment by rootfs** [comment]
cc @ckyriakidou

**Comment by bmarzins** [comment]
ACK

-Ben

**Comment by rootfs** [comment]
cc @mjudeikis

**Comment by sdodson** [comment]
#7368 backported to release-3.9

**Comment by mjudeikis** [comment]
@rootfs , @sdodson . I have cherry ready for 3.7 with few other ones for glusterfs. WIll add this change to it. 
https://github.com/openshift/openshift-ansible/pull/7213 
cc: @jarrpa

**Comment by jarrpa** [comment]
@mjudeikis Also make one for 3.6.

**Comment by mjudeikis** [comment]
3.7 is part of this monster: https://github.com/openshift/openshift-ansible/pull/7213 
3.6 : https://github.com/openshift/openshift-ansible/pull/7372

**Comment by rootfs** [comment]
3.7 fix is proposed at https://github.com/openshift/openshift-ansible/pull/8152

**Pull request merged**
