### PR TITLE
[release-3.9] [Bug 1553213] Upgrade cri-o during 3.9 upgrade

### PR DESCRIPTION
**Pull request by mtnbikenc**
This is a selective backport of #8628, #8661 and #9615

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1553213

### CODE REVIEW

**Comment by ashcrow** [comment]
```
TASK [openshift_master_certificates : Generate the loopback master client config] ***
Friday 17 August 2018  13:40:38 +0000 (0:00:00.107)       0:14:34.513 ********* 
ERROR! |failed expects hostvars is a dict
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
```

**Comment by mtnbikenc** [comment]
@ashcrow That error happens all the time because the 3.9 image on docker is broken and has been for some time. :(

**Comment by ashcrow** [comment]
@mtnbikenc good to know. Thanks!

**Comment by ashcrow** [comment]
Same known error:
```
TASK [openshift_master_certificates : Generate the loopback master client config] ***
Friday 17 August 2018  13:40:38 +0000 (0:00:00.107)       0:14:34.513 ********* 
ERROR! |failed expects hostvars is a dict
++ export status=FAILURE
```

Everything else looks good.

**Comment by ashcrow** [comment]
NM it merged :-D

**Comment by mtnbikenc** [comment]
@ceagan Thanks, opened https://github.com/openshift/openshift-ansible/pull/9679

**Pull request merged**
