### PR TITLE
Fix auditFilePath when running in a container

### PR DESCRIPTION
**Pull request by giuseppe**
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1437456

### CODE REVIEW

**Comment by giuseppe** [comment]
I've verified that the file is accessible from the host when in `master-config.yaml` I use this:

```yaml
auditConfig:
  enabled: true
  auditFilePath: /var/log/origin-master.log
```

**Comment by giuseppe** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Pull request merged**
