### PR TITLE
Playbook to deploy keepalived on master nodes for native HA

### PR DESCRIPTION
**Pull request by bacek**
Just simple playbook to deploy keepalived on master node for HA clustering without external LoadBlanacer with round-robin DNS only.

Uses ansible-keepalived role from evrardjp/ansible-keepalived to deploy keepalived and couple of iptables rules to enable VRRP traffic.

### CODE REVIEW

**Comment by DanyC97** [comment]
@bacek are you still interested in working on this code? 

Currently we already have the [LB](https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_loadbalancer)  role however that doesn't have the keepalived hence no HA.

saying that i personally like this approach of ditching LB group and just use the Master nodes are LB group because then will reduce the deployment footprint
But to get it integrated i think we need to move away from a standalone playbook ..

@michaelgugino @vrutkovs @sdodson  what you guys think, do you like this idea?

**Comment by bacek** [comment]
I'm in. If it will align with OpenShift strategy.

**Comment by vrutkovs** [comment]
>saying that i personally like this approach of ditching LB group and just use the Master nodes as LB group because it will reduce the deployment footprint

I don't mind adding new role and option for keepalived masters, although the code needs to be reworked to align with other roles - names, drop Ubuntu install etc.

**Comment by sdodson** [comment]
@openshift/sig-networking @smarterclayton Does deploying IP failover/keepalived for API load balancing align with our future of Origin/OCP?

**Comment by DanyC97** [comment]
@sdodson if below is true

> deploying IP failover/keepalived for API load balancing align with our future of Origin/OCP

then i believe we will need also:

* ipfailover lib module (like we do with the router today)
* add a new role or s'thing along this lines ..

**Comment by sdodson** [comment]
Sorry, we appreciate the PR but we do not wish to support this given that it's limited to environments where one can easily assign a VIP and the fact that we feel in most environments a pre-existing load balancing solution would be preferred. If we could deliver one solution that works for all deployment scenarios we'd accept that.

**Pull request closed without merging**
