### PR TITLE
Retry image prepulls

### PR DESCRIPTION
**Pull request by vrutkovs**
Random minor errors may occur during image prepulls

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1639201#c8

### CODE REVIEW

**Comment by sdodson** [comment]
/lgtm
Discussed the error w/ @runcom and we can't figure out the cause but he suggests retries should be fine.

**Comment by sdodson** [comment]
Example error from the bug.
```
TASK [openshift_node : Check status of node image pre-pull] ********************
Monday 29 October 2018  15:39:31 +0800 (0:00:00.117)       0:06:22.707 ******** 
changed: [host-8-251-110.redhat.com] => {"ansible_job_id": "274419478459.15172", "attempts": 1, "changed": true, "cmd": ["crictl", "pull", "registry.access.redhat.com/openshift3/ose-node:v3.11"], "delta": "0:01:45.258525", "end": "2018-10-29 03:35:49.786125", "failed_when_result": false, "finished": 1, "msg": "non-zero return code", "rc": 1, "start": "2018-10-29 03:34:04.527600", "stderr": "W1029 03:34:04.559334   15179 util_unix.go:75] Using \"/var/run/crio/crio.sock\" as endpoint is deprecated, please consider using full url format \"unix:///var/run/crio/crio.sock\".\ntime=\"2018-10-29T03:35:49-04:00\" level=fatal msg=\"pulling image failed: rpc error: code = Unavailable desc = transport is closing\"", "stderr_lines": ["W1029 03:34:04.559334   15179 util_unix.go:75] Using \"/var/run/crio/crio.sock\" as endpoint is deprecated, please consider using full url format \"unix:///var/run/crio/crio.sock\".", "time=\"2018-10-29T03:35:49-04:00\" level=fatal msg=\"pulling image failed: rpc error: code = Unavailable desc = transport is closing\""], "stdout": "", "stdout_lines": []}
```

**Comment by runcom** [comment]
we (CRI-O) would greatly benefit from logs (cri-o journald, system journal etc etc). If you guys happen to reproduce or have logs handy, please send them out my way,thanks!

**Comment by vrutkovs** [comment]
Not gonna work - there is no way to know if return code is returned as this task is async

**Pull request closed without merging**
