### PR TITLE
Support custom diagnostic pod prefixes for healthchecks

### LINKED ISSUE #8306: Cannot use custom images with diagnostics health check
#### Description

The `oc adm diagnostics` commands provide options to allow using a custom image for the diagnostics that deploy pods as part of the process. There are no such equivalent inventory options when using the openshift health check playbook.

##### Version
```
ansible 2.4.4.0
  config file = /opt/rhel-ansible/ansible.cfg
  configured module search path = [u'/home/.../.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### Steps To Reproduce
1. Run the health check playbook on a cluster without access to docker hub

##### Expected Results
Playbook offers config variables to change the images used to run diagnostics pods

##### Observed Results
No such options are available, hence the health check playbook is doomed to fail

##### Additional Information
It should be fairly simple to change `roles/openshift_health_checker/openshift_checks/diagnostics.py` to support adding  `--pod-image`  and friends to the `adm diagnostics` commands.

### PR DESCRIPTION
**Pull request by jlsalmon**
Fixes #8306

### CODE REVIEW

**Comment by sdodson** [comment]
bot, test pull request

**Comment by jlsalmon** [comment]
I've looked at the failed test logs and can't see anything related to this PR specifically.

/retest
/assign @sosiouxme

**Comment by vrutkovs** [comment]
Master branch is closed! A major refactor is ongoing in devel-40. Changes for 3.x should be made directly to the latest release branch they're relevant to and backported from there.

**Pull request closed without merging**
