### PR TITLE
GlusterFS suppot for OpenShift v1.5 

### PR DESCRIPTION
**Pull request by chinacoolhacker**
Added files and templates for OpenShift v1.5

### CODE REVIEW

**Comment by michaelgugino** [comment]
/ok-to-test

@chinacoolhacker Were you able to test this locally?

Also, there seems to be a merge commit included in this PR.  Can you make sure it's just the one commit?

**Comment by chinacoolhacker** [comment]
@michaelgugino i only test this templates then i test backport, https://github.com/openshift/openshift-ansible/pull/5786 you can check log https://github.com/openshift/openshift-ansible/files/1397885/glusterfs.ansible.log  
Also, i fix up blank commit from PR

**Comment by chinacoolhacker** [comment]
bot, test pull request

**Pull request merged**
