### PR TITLE
Allow user to specify local openstack.conf

### PR DESCRIPTION
**Pull request by tzumainn**

### CODE REVIEW

**Comment by tzumainn** [comment]
@celebdor, does this look like what you were looking for?

**Comment by tomassedovic** [comment]
Thanks! This looks good to me. I've tested it out and the file is created and set up correctly.

@vrutkovs (or anyone else on from the owners) could you have a look please? We'd like to have a way to just specify the full openstack.conf file for the cloud provider for options that openshift-ansible doesn't provide.

**Pull request merged**
