### PR TITLE
Update cfme templates to auto-generate postgresql password

### PR DESCRIPTION
**Pull request by simaishi**
https://bugzilla.redhat.com/show_bug.cgi?id=1461973
(upstream fix: https://github.com/ManageIQ/manageiq-pods/pull/118)

@fbladilo please review

### CODE REVIEW

**Comment by fbladilo** [comment]
@simaishi LGTM 👍

**Comment by sdodson** [comment]
bot, test pull request

**Comment by sdodson** [comment]
aos-ci-test

**Comment by simaishi** [comment]
@sdodson not sure if anything is needed from me... this template goes with already released CFME 5.8.1 errata.

**Pull request merged**
