### PR TITLE
Fix the gluster-s3 pod label used in gluster-s3 service.

### PR DESCRIPTION
**Pull request by SaravanaStorageNetwork**
Signed-off-by: Saravanakumar Arumugam <sarumuga@redhat.com>

### CODE REVIEW

**Comment by SaravanaStorageNetwork** [comment]
bot, test pull request

**Comment by SaravanaStorageNetwork** [comment]
@jarrpa  Please check - There are three commits in total related to s3

**Comment by jarrpa** [comment]
Legit!

/ok-to-test
/lgtm
bot, add author to whitelist

**Comment by SaravanaStorageNetwork** [comment]
@sdodson @michaelgugino @jarrpa  Failing again -  Please help to get this merged

**Comment by SaravanaStorageNetwork** [comment]
PR #7454  sent  for release-3.9 @jarrpa

**Pull request merged**
