### PR TITLE
Test: Fail on entry point playbooks in common

### PR DESCRIPTION
**Pull request by mtnbikenc**
- Added a tox check to fail if an entry point was found in `playbooks/common`
- Moved task include files into `tasks/' directory to separate task file from playbook files.  This allows proper parsing of yaml files as playbooks.  It also enhances the description of the file being a task list instead of a playbook.
- Deleted legacy files used by {aws/gce/libvirt/openstack}

Depends on:
#5179 merged
#5182 merged
#5201 merged

### CODE REVIEW

**Comment by mtnbikenc** [comment]
@kwoodson You mentioned something about breaking out the checks when I added the entry point discovery logic.  Maybe I can handle that in this PR to better separate the individual tests that are run on playbooks.

**Comment by kwoodson** [comment]
@mtnbikenc, We have checks scattered throughout most of our repository.  I'd really like to group those together in the prevalidation of our health checker or somewhere similar.  It seems illogical to run for minutes during an install and fail inside of a role/playbook when a version of python is not as expected.  We should have caught something like this early on.

**Comment by mtnbikenc** [comment]
@kwoodson I think my terminology may have thrown you off.  I was referring to the checks we are performing in CI using setup.py to validate code meets our standards.  I previously added the discovery and syntax checking of all entry point playbooks.  In this PR I'm adding a check to make sure entry point playbooks are not added to `common`.

**Comment by kwoodson** [comment]
@mtnbikenc, makes sense now for entry point checking. Thanks for the explanation.

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
[merge]

**Comment by dobbymoodge** [comment]
rekick [merge] b/c restart

**Comment by mtnbikenc** [comment]
Flake https://github.com/openshift/origin/issues/16005

**Comment by mtnbikenc** [comment]
[merge]

**Comment by mtnbikenc** [comment]
Flake pulling from docker.io
`Trying to pull repository docker.io/openshift/origin-release`

**Pull request merged**
