### PR TITLE
Wait for API availability before migrating storage, add retries

### PR DESCRIPTION
**Pull request by sdodson**
Wait for all core apis to become available and add more retries to the
storage migration to work around a problem where storage migration fails
due to certain api endpoints not being available in time

Potential fix for https://bugzilla.redhat.com/show_bug.cgi?id=1591053

### CODE REVIEW

**Comment by mtnbikenc** [comment]
@sdodson This doesn't call into the task that checks all core APIs.  That task is at the end of main.yml and will require some refactoring to be able to call it directly.  There are a lot of checks here which could be useful to run at different stages but I don't know that we need to completely rework it at this point.  Increasing retries looks fine.

**Comment by sdodson** [comment]
Ugh, can't believe I missed that. I've moved the core api checks into the included task file, i think it's a good generic check for api availability now.

**Comment by sdodson** [comment]
Fixed an undefined variable error i encountered in testing.

**Comment by mtnbikenc** [comment]
I hit the same error in my test.
/lgtm

**Pull request merged**
