### PR TITLE
Fix version checker, Require 2.7.8

### PR DESCRIPTION
**Pull request by mtnbikenc**
* Fix version requirement plugin to allow Ansible development versions (2.8.0.dev0)
* Standardize all version refs to 2.7.8

### CODE REVIEW

**Comment by sdodson** [comment]
/lgtm

> Fix version requirement plugin to allow Ansible development versions (2.8.0.dev0)

Thanks for that.

**Comment by mtnbikenc** [comment]
> Thanks for that.

This was the only error I hit when running scaleup.yml with Ansible 2.8.0.dev0, which is what the devel branch reported.

**Comment by mtnbikenc** [comment]
Some other Ansible issue in CI tests.
/hold

**Comment by mtnbikenc** [comment]
Passing openshift-ansible scaleup.

Job 533:
```
Failing tests:

[k8s.io] [sig-node] PreStop should call prestop when killing a pod  [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s]
[sig-api-machinery] Namespaces [Serial] should ensure that all pods are removed when a namespace is deleted [Conformance] [Suite:openshift/conformance/serial/minimal] [Suite:k8s]
```
/hold cancel

**Comment by mtnbikenc** [comment]
Job 541:
```
Failing tests:

[Feature:Builds][Conformance] s2i build with a quota  Building from a template should create an s2i build with a quota and run it [Suite:openshift/conformance/parallel/minimal]
```

**Comment by mtnbikenc** [comment]
Two consecutive jobs flaked on different tests.  This is a candidate for merge.

**Comment by mtnbikenc** [comment]
Consecutive jobs with different test flakes.
/override ci/prow/e2e-aws-scaleup

**Comment by sdodson** [comment]
All tests have passed, though there's an errant blocking status. Merging.

**Pull request merged**
