### PR TITLE
[1.5] Changed annotation for dynamic provisioning on metrics and logging

### PR DESCRIPTION
**Pull request by zonArt**
provisioning with storageclass is not working when using the alpha version

### CODE REVIEW

**Comment by zonArt** [comment]
aos-ci-jenkins

**Comment by zonArt** [comment]
bot, test pull request

**Comment by sdodson** [comment]
@gnufied @kwoodson PTAL

**Comment by gnufied** [comment]
@zonArt there is an actual storageClass called `dynamic` created before being used here right? I seem to remember - we do have that class but just wanted to double check..

**Comment by sdodson** [comment]
aos-ci-test

**Comment by zonArt** [comment]
@gnufied Actually this is my second concern on the playbook, I'm not sure the storageclass is created. What I personally did was run the config.yml playbook without metrics and logging deployment, once cluster is up, create the storageclass and run the playbook again with metrics/logging deployment.
But I also may have missed something and in this case I would love to know how to set the storageclass (especially the provider part), I'm using ceph

**Comment by gnufied** [comment]
@sdodson  please don't merge this yet, I take back my earlier "approval".  I am looking bit closely.

**Comment by gnufied** [comment]
@zonArt just to confirm by ceph you mean `ceph-rbd` right?

**Comment by zonArt** [comment]
@gnufied yes `ceph-rbd`

**Comment by gnufied** [comment]
I do not think we create any ceph-rbd based storageclasses as part of openshift-ansible steps. We should leave the PVC definition as it is and not change it.

**Comment by zonArt** [comment]
@gnufied I think you're right this storageclass is not created, however as it is moving to beta, I think it's a good idea to correct the annotations in the pvc to reflect the change. This is intended for the 1.5 version of origin no sense to have that on master. But I think you already noticed that.

**Comment by gnufied** [comment]
@zonArt yeah the name of storageclasses has already been changed on master in preparation for 3.6 release. We are also creating default storageclasses in master branch but only for GCE & AWS envs.  @kwoodson is working on another refactor to make default storageclasses more configurable.

Lets close this PR for now.

**Comment by kwoodson** [comment]
@gnufied, @zonArt,  Is there any harm switching from alpha to beta?  If the current behavior doesn't work with the `dynamic` storageclass then it is `no harm no foul`, right?

I'm fine with bumping the version up from `alpha` to `beta` if it is better off in the long run.

If the current `alpha` is working and switching to `beta` breaks something then I would agree, let's not do it.  Please help me understand what I'm missing.

**Comment by gnufied** [comment]
switching from alpha to beta could actually break existing scripts, because alpha annotation is special and it works even if there is no actual storage class present. So,  if a PVC has an alpha annotation for storageclass but the actual storageclass doesn't exist - provisioner tries to make best guess and provisions a volume using cloudprovider information. 

If we switch to beta - it means that, the specified storageclass must exist, otherwise it won't work.

**Comment by kwoodson** [comment]
@gnufied, thanks for clarifying.  Let's hold off on this then.

**Comment by michaelgugino** [comment]
Closing due to inactivity.

**Pull request closed without merging**
