### PR TITLE
Cherry picking from 1.5 for openshift_logging

### PR DESCRIPTION
**Pull request by ewolinetz**

### CODE REVIEW

**Comment by ewolinetz** [comment]
I may want to revert the latest commit, I'll need to verify whether or not k8s allows the rollingUpdate parameter on the ds when we patch it during an upgrade

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
@sdodson any qualms with this PR?

**Comment by sdodson** [comment]
[merge]

**Pull request merged**
