### PR TITLE
Begin to add native support for multi-master HA against next branch

### PR DESCRIPTION
**Pull request by detiber**
This builds upon https://github.com/openshift/openshift-ansible/pull/494 since the packaging/binary changes made there are required.

### CODE REVIEW

**Comment by detiber** [comment]
@abutcher This is the start of native HA support for multi-master.  It's still a bit rough. Will tag you on the trello card as well.

**Comment by jaryn** [comment]
Can one of the admins verify this patch?

**Comment by jaryn** [comment]
Can one of the admins verify this patch?

**Comment by detiber** [comment]
closing in favor of https://github.com/openshift/openshift-ansible/pull/608

**Pull request closed without merging**
