### PR TITLE
Label master nodes with openshift-infra=apiserver for service catalog

### PR DESCRIPTION
**Pull request by jpeeler**
This enables catalog to run on all the masters instead of just the first
one.

### CODE REVIEW

**Comment by jpeeler** [comment]
Cherry pick of https://github.com/openshift/openshift-ansible/pull/7526, but I'd like to see the CI now while WIP.

**Comment by jpeeler** [comment]
Ref https://bugzilla.redhat.com/show_bug.cgi?id=1554623

**Comment by sdodson** [comment]
/retest
bot, retest this please
/lgtm

**Comment by jpeeler** [comment]
I think there's a very similar label called region:infra or something. I thought that the openshift-infra label was in use only by service-catalog. (If that's not the case, can we just cherry-pick https://github.com/openshift/openshift-ansible/pull/7644/?)

**Comment by michaelgugino** [comment]
@jpeeler 3.9 (new installs or upgrades from 3.7) forces all masters to have the master label.

You can just set your node selector like this: https://github.com/openshift/openshift-ansible/blob/release-3.9/roles/openshift_web_console/defaults/main.yml#L2

**Comment by michaelgugino** [comment]
@jpeeler looks like we're hard-setting
'node_selector: {'node-role.kubernetes.io/master': 'true'}'
in master.  Probably can do that here.

**Pull request merged**
