### PR TITLE
Mount device manager socket dir path

### PR DESCRIPTION
**Pull request by vikaschoudhary16**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1552511

/cc @sjenning @sdodson

### CODE REVIEW

**Comment by sdodson** [comment]
What assurances do we have that /var/lib/kubelet will exist on the host prior to running this and if it doesn't exist and is created when mounting this, will that cause problems?

**Comment by vikaschoudhary16** [comment]
@sdodson There will be no problem if this path does not exist and is created when mounting this. 

Device manager(Kubelet) will create a unix socket file at this path at the kubelet initialization. This socket will be then used by plugins(daemonsets) to communicate with kubelet. So if this path is not there and then created before mounting has no problems.

**Comment by sdodson** [comment]
Ok, thanks, if this is relevant to master then let's make the change there too.

**Comment by sjenning** [comment]
@vikaschoudhary16 can you forward port this to master?

**Comment by sjenning** [comment]
@vikaschoudhary16 disregard previous comment.  afaict, in 3.10, this should not be an issue as containerized kubelet is no longer supported and we have currently abandon the path to use kubelet in a system container.  Thus the kubelet will run in the host mount namespace and there is no issue.

Can you verify that this is the case?

**Pull request merged**
