### PR TITLE
Remove v3_3 upgrade playbooks

### PR DESCRIPTION
**Pull request by mtnbikenc**

### CODE REVIEW

**Comment by sdodson** [comment]
Lets wait on this to see what shakes out of the multi-version upgrade stuff. I'm sure we can reconstruct this from other branches and history but I'd prefer leaving it for now.

**Comment by mtnbikenc** [comment]
@sdodson Are we going to continue to keep the old upgrade playbooks around?

**Comment by detiber** [comment]
@sdodson @mtnbikenc I would suggest leaving the old, but potentially compatible playbooks in place. That way all bugfixes, etc can be done in master and changes can be backported back to the affected branch. Granted with current work, that would mean backporting the module work. But as long as nothing that is 3.5+ specific is done that should be possible.

**Comment by mtnbikenc** [comment]
Closing this PR.  The work can be completed when deemed necessary in the future.

**Pull request closed without merging**
