### PR TITLE
[osa] remove crio vars & add packages

### PR DESCRIPTION
**Pull request by mjudeikis**
remove variable so we can pass it from playbook execution level 
Add packages so dual builds would work

### CODE REVIEW

**Comment by kargakis** [comment]
Do you need the changes in release with the latest changes in this PR?

**Comment by mjudeikis** [comment]
@kargakis no, they already in.

**Comment by kargakis** [comment]
> @kargakis no, they already in.

I am asking whether we need to revert them

**Comment by mjudeikis** [comment]
> I am asking whether we need to revert them
No. Just in the interim we will install CRIO and Skopeo on the nodes but we will not use them, or configure in any way.

**Pull request merged**
