### PR TITLE
Bug 1523294- ASB remove tasks are now idempotent

### PR DESCRIPTION
**Pull request by fabianvf**
https://bugzilla.redhat.com/show_bug.cgi?id=1523294

### CODE REVIEW

**Comment by bysnupy** [comment]
You need to add `register: result` attribute before using `result` variable in `failed_when`.

This yaml was occured a following error message.
```
"msg": "The conditional check 'result.msg is defined and result.msg.returncode is defined' failed. The error was: error while evaluating conditional (result.msg is defined and result.msg.returncode is defined): 'result' is undefined"
```

**Comment by fabianvf** [comment]
Wow, great catch. Not sure how that register slipped out between my testing and my commit. Thanks for the review.

**Comment by fabianvf** [comment]
@kwoodson Thinking about this issue more, it seems that if the namespace doesn't exist when we're trying to remove a resource it shouldn't throw the error. Would you be in favor of changing that behavior in lib_openshift rather than working around it here?

**Pull request closed without merging**
