### PR TITLE
Backport excluders to 1.3

### PR DESCRIPTION
**Pull request by ingvagabund**
Based on 1.4 backport https://github.com/openshift/openshift-ansible/pull/4368. Just removing 3.4 part.

This will require a lot of testing:
* [x] - test 3.3 deployment
* [x] - test 3.3 -> 3.3 upgrade
* [x] - test 3.3 -> 3.3 upgrade (node only)
* [x] - test 3.3 -> 3.3 upgrade (control plane only)
* [x] - test 3.3 node scale up
* [x] - test 3.3 master scale up

### Testing inventories
**Deployment**
```yaml
[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
ansible_ssh_user = root
deployment_type = openshift-enterprise
osm_use_cockpit = false
openshift_master_cluster_method = native
docker_version = "1.10*"
openshift_release = v3.3

[masters]
10.8.175.202 ansible_ssh_host=10.8.175.202
10.8.175.205 ansible_ssh_host=10.8.175.205

[nodes]
10.8.175.209 ansible_ssh_host=10.8.175.209

[etcd]
10.8.175.202 ansible_ssh_host=10.8.175.202
10.8.175.205 ansible_ssh_host=10.8.175.205
```

**Node scaleup**
```yaml
[OSEv3:children]
masters
nodes
etcd
new_nodes

[OSEv3:vars]
ansible_ssh_user = root
deployment_type = openshift-enterprise
osm_use_cockpit = false
openshift_master_cluster_method = native
docker_version = "1.10*"
openshift_release = v3.3

[masters]
10.8.175.202 ansible_ssh_host=10.8.175.202
10.8.175.205 ansible_ssh_host=10.8.175.205

[nodes]
10.8.175.209 ansible_ssh_host=10.8.175.209

[etcd]
10.8.175.202 ansible_ssh_host=10.8.175.202
10.8.175.205 ansible_ssh_host=10.8.175.205

[new_nodes]
10.8.172.117 ansible_ssh_host=10.8.172.117
```

**Master scaleup**
```yaml
[OSEv3:children]
masters
nodes
etcd
new_masters

[OSEv3:vars]
ansible_ssh_user = root
deployment_type = openshift-enterprise
osm_use_cockpit = false
openshift_master_cluster_method = native
docker_version = "1.10*"
openshift_release = v3.3

[masters]
10.8.175.202 ansible_ssh_host=10.8.175.202
10.8.175.205 ansible_ssh_host=10.8.175.205

[nodes]
10.8.175.209 ansible_ssh_host=10.8.175.209
10.8.172.117 ansible_ssh_host=10.8.172.117

[etcd]
10.8.175.202 ansible_ssh_host=10.8.175.202
10.8.175.205 ansible_ssh_host=10.8.175.205

[new_masters]
10.8.175.46 ansible_ssh_host=10.8.175.46
```

**Upgrades**
```yaml
[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
ansible_ssh_user = root
deployment_type = openshift-enterprise
osm_use_cockpit = false
openshift_master_cluster_method = native
docker_version = "1.10*"
openshift_release = v3.3

[masters]
10.8.175.202 ansible_ssh_host=10.8.175.202
10.8.175.205 ansible_ssh_host=10.8.175.205
10.8.175.46 ansible_ssh_host=10.8.175.46

[nodes]
10.8.175.209 ansible_ssh_host=10.8.175.209
10.8.172.117 ansible_ssh_host=10.8.172.117

[etcd]
10.8.175.202 ansible_ssh_host=10.8.175.202
10.8.175.205 ansible_ssh_host=10.8.175.205
```

### CODE REVIEW

**Comment by ingvagabund** [comment]
aos-ci-test

**Comment by ingvagabund** [comment]
aos-ci-test

**Comment by ashcrow** [comment]
On containerized ```Summarizing 19 Failures```

**Comment by ingvagabund** [comment]
aos-ci-test

**Comment by ingvagabund** [comment]
Another PR to backport before merge: https://github.com/openshift/openshift-ansible/pull/4399

**Comment by sdodson** [comment]
jenkins timed out

**Comment by sdodson** [comment]
aos-ci-test

**Comment by ingvagabund** [comment]
[test]

**Comment by ingvagabund** [comment]
aos-ci-test

**Pull request merged**
