### PR TITLE
Updating probe timeout and exposing variable to adjust timeout in image

### PR DESCRIPTION
**Pull request by ewolinetz**
Ansible counter-part of https://github.com/openshift/origin-aggregated-logging/pull/457

### CODE REVIEW

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
[test]

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
[merge]

**Comment by ewolinetz** [comment]
part of solution for https://bugzilla.redhat.com/show_bug.cgi?id=1456139

**Pull request merged**
