### PR TITLE
Fixing indentation for topology keyfor antiaffinity rules

### PR DESCRIPTION
**Pull request by ewolinetz**
Fixes bad indentation in https://github.com/openshift/openshift-ansible/pull/7864

### CODE REVIEW

**Comment by ewolinetz** [comment]
I confirmed it locally, this fixes it... My indentation on the prior one got all jacked up with removing the jinja logic

**Comment by richm** [comment]
bot, please merge

**Comment by richm** [comment]
bot, please merge

**Comment by richm** [comment]
bot, pretty please?  with sugar on top?

**Comment by richm** [comment]
bot, you'd do it for Randolph Scott . . .

**Pull request merged**
