### PR TITLE
Adding error checking to create.

### PR DESCRIPTION
**Pull request by kwoodson**

### CODE REVIEW

**Comment by kwoodson** [comment]
aos-ci-test

**Comment by kwoodson** [comment]
[merge]

**Comment by kwoodson** [comment]
```TASK [openshift_master : Install or Update HA controller master system container] ***
task path: /usr/share/ansible/openshift-ansible/roles/openshift_master/tasks/system_container.yml:22
fatal: [localhost]: FAILED! => {
    "failed": true, 
    "generated_timestamp": "2017-08-11 05:08:28.770622", 
    "msg": "template error while templating string: expected token ':', got '}'. String: {{{ 'docker:' if openshift.common.system_images_registry == 'docker' else openshift.common.system_images_registry + '/' }}{ openshift.master.master_system_image }}:{{ openshift_image_tag }}"
}```

@sdodson, any ideas here?  This is unrelated to my PR.

**Comment by abutcher** [comment]
@kwoodson that one was fixed in https://github.com/openshift/openshift-ansible/pull/5060

**Comment by sdodson** [comment]
[merge]

**Pull request merged**
