### PR TITLE
Disconnected install fails at service catalog imagePullPolicy: Always

### PR DESCRIPTION
**Pull request by jkaurredhat**
Fix for bugzilla : https://bugzilla.redhat.com/show_bug.cgi?id=1524805

### CODE REVIEW

**Comment by mtnbikenc** [comment]
Changes from #6819 and #7079 were not backported to 3.7.
/lgtm

**Comment by vrutkovs** [comment]
/hold
devel-40 CI is broken

**Comment by vrutkovs** [comment]
/hold cancel

wrong PR, sorry

**Pull request merged**
