### PR TITLE
Add support for secret encryption

### PR DESCRIPTION
**Pull request by irozzo-1A**
@vrutkovs This is the new PR replacing #10470

### CODE REVIEW

**Comment by sdodson** [comment]
/lgtm
Thanks!

**Comment by irozzo-1A** [comment]
@sdodson Thx for merging this, I would like to have this for versions 3.9 and 3.10 as well. Is it possible? I made the PRs already.

**Comment by sdodson** [comment]
@irozzo-1A got them, thanks!

**Pull request merged**
