### PR TITLE
Don't get file checksum, attributes and mime type in stat module calls

### PR DESCRIPTION
**Pull request by vrutkovs**
In most cases this module is used to find out if the file exits, so no need 
to waste CPU on checksum and attributes

### CODE REVIEW

**Comment by sdodson** [comment]
Does this produce a measurable speedup?

**Comment by vrutkovs** [comment]
Yep, a few seconds can be shaved off:

master branch on atomic:
```
TASK [container_runtime : stat] ************************************************
task path: /var/tmp/checkout/roles/container_runtime/tasks/package_docker.yml:49
Monday 16 July 2018  09:22:47 +0000 (0:00:03.783)       0:01:21.578 *********** 
```
This PR:
```
task path: /var/tmp/checkout/roles/container_runtime/tasks/package_docker.yml:49
Monday 16 July 2018  15:21:49 +0000 (0:00:02.267)       0:01:11.271 *********** 
```

Larger folder would be checked faster

**Comment by michaelgugino** [comment]
Seems sensible to me.

**Comment by vrutkovs** [comment]
bot, retest this please

**Comment by vrutkovs** [comment]
bot, retest this please

**Comment by vrutkovs** [comment]
bot, retest this please

**Comment by vrutkovs** [comment]
bot, retest this please

**Comment by vrutkovs** [comment]
bot, retest this please

**Pull request merged**
