### PR TITLE
add template service broker configurable

### PR DESCRIPTION
**Pull request by jim-minter**
@sdodson
@bparees

### CODE REVIEW

**Comment by jim-minter** [comment]
Needs to be merged /after/ https://github.com/openshift/origin/pull/13872

**Comment by bparees** [comment]
will need to revisit this after the api is agreed on.

**Comment by sdodson** [comment]
WIP/DO NOT MERGE then?

**Comment by jim-minter** [comment]
openshift/origin#13872 has now merged, please review and merge this PR.

**Comment by bparees** [comment]
lgtm.  @sdodson ?

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Pull request merged**
