### PR TITLE
Allow ansible >= 1.9.4

### PR DESCRIPTION
**Pull request by abutcher**
Working towards #686.

### CODE REVIEW

**Comment by detiber** [comment]
If you add a check on the upgrade to fail for 2.0+, then we can go ahead and get this merged.

**Comment by abutcher** [comment]
aos-ci-test

**Comment by sdodson** [comment]
LGTM

**Comment by abutcher** [comment]
@detiber To show a clean "v2 is not supported for upgrades" message we would have to separate the `vars_files` changes from #1862, otherwise we'd end up seeing the `vars_files` error first thing. I'm leaning towards doing both at once if we can swing it.

**Pull request merged**
