### PR TITLE
Node group management update.

### PR DESCRIPTION
**Pull request by kwoodson**

### CODE REVIEW

**Comment by kwoodson** [comment]
@mwoodson @sdodson @derekwaynecarr,

This has been updated for ansible 2.4 and I believe it is ready to go.

**Comment by kwoodson** [comment]
Rebased onto master to pick up 2.4 ec2_group fixes.

**Comment by kwoodson** [comment]
Removed a couple of lines of commented code.

**Comment by sdodson** [comment]
bot, retest this please

**Comment by sdodson** [comment]
thanks a flake

**Pull request merged**
