### PR TITLE
openshift_node: always check for missing TCMU iSCSI device entry

### PR DESCRIPTION
**Pull request by jarrpa**
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1694960

Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>

### CODE REVIEW

**Comment by vrutkovs** [comment]
Shouldn't `"Add devices section"` task be updated too?

**Comment by jarrpa** [comment]
@vrutkovs By my understanding, no. The reason being is that the contents of `devices {}` should be allowed to be modified after it's initially inserted (e.g. other device types may be added). The difference is that the LIO-ORG TCMU device entry should remain unmodified, so it's okay to overwrite it if necessary.

**Comment by vrutkovs** [comment]
okay, sounds good to me

/lgtm

**Pull request merged**
