### PR TITLE
Fix g_glusterfs_hosts variable never set

### PR DESCRIPTION
**Pull request by juanwolf**
Hi,
I was trying to install glusterfs using the playbook located at `playbooks/byo/openshift-glusterfs/config.yml` but the common playbook (`playbooks/common/openshift-glusterfs/config.yml`) was not setting the `g_glusterfs_hosts` variable, so the whole glusterfs installation was skipped everytime.

Changing this variable to groups.oo_glusterfs_to_config fixed the issue.

I also added the support of glusterfs_hostname host variable when labelling the nodes as I use different nodenames than the hostnames in my configuration.

### CODE REVIEW

**Comment by jarrpa** [comment]
@juanwolf Not quite right. #4245 addresses this more completely [here](https://github.com/openshift/openshift-ansible/pull/4245/commits/724336edf86604e0fdbaca0b419de1c373e1b14d). I'd ask to wait for that PR to go through. :)

**Comment by juanwolf** [comment]
Nice! I will close this PR then, I was just wondering if you were supporting the case where the domain name and the nodename are different in the heketi topology, I did not see it in your PR.

**Comment by jarrpa** [comment]
I believe I do... but in a commit I haven't pushed into the PR yet. ;) I've been hitting some bugs in finalizing the work. I was hoping to push them yesterday. Will be trying again today.

**Comment by juanwolf** [comment]
Ok, awesome! Looking forward for this PR to be merged!

**Pull request closed without merging**
