### PR TITLE
Backport the fix for flannel iptable rules

### PR DESCRIPTION
**Pull request by sureshgaikwad**
The pod communication fails due to missing iptable rules. Add these rules during installation. This is failing in OCP 3.5 and is fixed in OCP 3.9 as per BZ #1473858. Filing a backport request. This is the original PR
https://github.com/openshift/openshift-ansible/pull/5853/files

### CODE REVIEW

**Comment by sdodson** [comment]
@imcsk8 this was backported for this cloned bug https://bugzilla.redhat.com/show_bug.cgi?id=1594310 though your original bug was https://bugzilla.redhat.com/show_bug.cgi?id=1493955 which may be slightly different. Do you mind taking a look at this and the bug to see if you believe this would resolve the issue?

**Comment by sdodson** [comment]
If so we need to also get this into 3.7 and 3.6 before getting it into 3.5.

**Comment by sureshgaikwad** [comment]
We also need to add the iptables rules for DNS specifically for 3.5.

# iptables -A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 53 -j ACCEPT
# iptables -A OS_FIREWALL_ALLOW -p udp -m state --state NEW -m udp --dport 53 -j ACCEPT

or simply:

# iptables -I INPUT -p udp --dport 53 -j ACCEPT
# iptables -I INPUT -p tcp --dport 53 -j ACCEPT


Something like this:

- name: Allow name resolution from pod
  command: /sbin/iptables -A OS_FIREWALL_ALLOW -p tcp -m state --state NEW --dport 53 -j ACCEPT -m comment --comment "DNS tcp communication"
  notify:
    - save iptable rules

- name: Allow name resolution from pod
  command: /sbin/iptables -A OS_FIREWALL_ALLOW -p udp -m state --state NEW --dport 53 -j ACCEPT -m comment --comment "DNS udp communication"
  notify:
    - save iptable rules

**Comment by imcsk8** [comment]
it looks ok, it might be ok to stash the commits.
also, i'm not sure if @sureshgaikwad suggestion should be on this PR or in a new one since this one is a backport

**Comment by sureshgaikwad** [comment]
@imcsk8 I can create new PR for this if required. Is it possible add those rules along with these in the same version.
This is added in [OCP3.9](https://github.com/openshift/openshift-ansible/blob/release-3.9/roles/flannel/tasks/main.yml#L55-L61)

**Comment by sureshgaikwad** [comment]
@imcsk8 any updates on this? I will create a new PR for the DNS rules. For flannel backport, can we merge this for 3.5?

**Comment by mtnbikenc** [comment]
Closing due to no recent activity. Please open a new PR if this change is still needed.
/close

**Pull request closed without merging**
