### PR TITLE
_idp['name'] not availabe

### PR DESCRIPTION
**Pull request by st0ne-dot-at**
The key 'name' is popped from the _idp dictionary in line 54.

    self.name = self._idp.pop('name')

Therefore it is not accessible in line 161.

### CODE REVIEW

**Comment by DanyC97** [comment]
@st0ne-dot-at fyi this was fixed or that is my understanding https://github.com/openshift/openshift-ansible/pull/9858 ...

@vrutkovs fyi

**Comment by vrutkovs** [comment]
Oh, right

/ok-to-test

**Pull request merged**
