### PR TITLE
Fix variants for v3.6

### PR DESCRIPTION
**Pull request by mtnbikenc**
Fixes bug 1447204

### CODE REVIEW

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
@sdodson Still seeing failures related to excluders.  https://github.com/openshift/openshift-ansible/pull/4068#issuecomment-298675268

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
this is maddening, I see success on other jobs now so the only thing I can come up with is they were doing a build and had not pushed the repo yet

**Pull request merged**
