### PR TITLE
Patch to enable import_jks_certs.sh to work on OSX

### PR DESCRIPTION
**Pull request by mazzystr**
@ewolinetz - Here's that patch to import_jks_certs.sh

### CODE REVIEW

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by sdodson** [comment]
master PR too?

**Comment by ewolinetz** [comment]
@sdodson this file doesn't exist in master, the cert approach for metrics was changed to no longer need it

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
[merge]

**Comment by sdodson** [comment]
@stobias123 It was merged into master but not release-1.5 branch.

@mazzystr and @ewolinetz can we reconcile these two patches and make sure that release-1.5 and master are in sync?

**Comment by ewolinetz** [comment]
I can open a PR to backport that `base64 -d` update to release-1.5 today

**Comment by ewolinetz** [comment]
https://github.com/openshift/openshift-ansible/pull/4171

**Pull request merged**
