### PR TITLE
Fix Prometheus byo entry point

### PR DESCRIPTION
**Pull request by mtnbikenc**
Adds the std_include.yml playbook to the byo entrypoint and moves the conditional install to the openshift_hosted.yml portion of an install.

### CODE REVIEW

**Comment by mtnbikenc** [comment]
Alternative to https://github.com/openshift/openshift-ansible/pull/5613

**Comment by mtnbikenc** [comment]
@zgalor The metrics and logging installs were moved out of openshift hosted and given their own 'phase' of a complete deployment.  The same install logic for those is present here: https://github.com/openshift/openshift-ansible/blob/master/playbooks/common/openshift-cluster/config.yml#L41

Let me know if this does not answer your question.

**Comment by zgalor** [comment]
Yes. it does.
I need someone to explain this "hosted" thing because I'm pretty sure prometheus shouldn't be on it either.

**Comment by sdodson** [comment]
@zgalor It's just a general concept we use to refer to components that get installed after we have a working cluster. Logging, metrics, router, registry, etc. Phases are just what we're referring to as independent steps that can be executed if you choose to run the installation as a series of steps rather than one huge playbook, they're also how we'd instruct someone to resume an installation if for instance it failed at the 'hosted' step.

**Pull request merged**
