### PR TITLE
Contiv multi-master and other fixes

### PR DESCRIPTION
**Pull request by nbartos**
Contiv's etcd was not being deployed correctly when using more than
one master.  To make it easier to manage, it has been moved into a
k8s container.

The api proxy was hardcoded to an old version (1.1.1), and in some
environments would run into a docker error.  This has been moved into
a k8s container for easier management.

The firewall was too permissive on several ports.  Many were open to
the world when they should have only been accessible inside the
cluster.

Many of the contiv role variables were not prefixed with 'contiv',
which may end up clobbering variables from another role.  Now all the
contiv specific role variables start with 'contiv_'.

The api proxy's default self-signed certificate was bundled with the
role.  This means someone with read-only MITM access and this key
could decrypt traffic.  Granted a user defined certificate from a
trusted CA should be used in a production environment, it is still
better to generate one in each environment when one is not provided.

### CODE REVIEW

**Comment by nbartos** [comment]
@jcpowermac @sdodson and @srampal can you PTAL?  Thanks!

**Comment by sdodson** [comment]
bot, test pull request

**Comment by sdodson** [comment]
Neither the crio or logging tests are currently blocking FWIW.

**Pull request merged**
