### PR TITLE
Updating registry-console version to be v3.6 instead of 3.6

### PR DESCRIPTION
**Pull request by ewolinetz**
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1452214

### CODE REVIEW

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by abutcher** [comment]
[merge]

**Comment by ewolinetz** [comment]
flaked on https://github.com/openshift/origin/issues/14334

**Comment by ewolinetz** [comment]
[merge]

**Comment by ewolinetz** [comment]
[merge][severity: bug]

**Comment by sdodson** [comment]
[merge][severity: bug]

**Comment by stevekuznetsov** [comment]
[merge][severity: bug]

**Comment by ewolinetz** [comment]
flaked on https://github.com/openshift/origin/issues/14129

**Comment by ewolinetz** [comment]
[merge][severity: bug]

**Comment by stevekuznetsov** [comment]
Looks like AWS flaked out when we were gathering facts?

```
TASK [Gathering Facts] *********************************************************
fatal: [172.18.8.17]: UNREACHABLE! => {
    "changed": false, 
    "generated_timestamp": "2017-05-26 12:41:37.141566", 
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 172.18.8.17 port 22: Connection refused\r\n", 
    "unreachable": true
}
```

**Comment by stevekuznetsov** [comment]
@openshift-bot, the [last build](https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_openshift_ansible/470/) failed from the following flakes:
 - [conformance](https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_openshift_ansible/470/testReport/junit/(root)/Extended/deploymentconfigs_with_test_deployments__Conformance__should_run_a_deployment_to_completion_and_then_scale_to_zero/) failed on: https://github.com/openshift/origin/issues/13980

re[merge]

**Comment by sdodson** [comment]
https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_openshift_ansible/471/ failed on https://github.com/openshift/origin/issues/13980

**Pull request merged**
