### PR TITLE
Revert "namespace the byo inventory so the group names aren't so gene…

### PR DESCRIPTION
**Pull request by sdodson**
Reverts openshift/openshift-ansible#423

### CODE REVIEW

**Comment by sdodson** [comment]
@brenton or @wshearn please merge soon, we have SMEs already running into the issues associated with this change.

**Comment by detiber** [comment]
@sdodson @brenton What is the issue that SMEs where running into? I agree that we shouldn't break existing users, but overall the namespacing is probably a good idea for those running an existing ansible infrastructure.

We could probably update playbooks/byo/openshift-cluster/config.yml to use the old group naming if the new namespaced group naming is not available.  That should accomplish not breaking existing users while also providing namespacing for more advanced users.

**Comment by sdodson** [comment]
@detiber Just that they were getting NOOP runs because their inventories used the old group names so nothing matched the playbooks.

I can't think of any way of making this change without breaking someone, so I guess the best we can hope for is to make sure we have corresponding docs changes ready to go.

**Comment by brenton** [comment]
@detiber, the problem was the the group names changed in the inventory.  People that previously had `[nodes]` and `[masters]` in their inventory were immediately broken.

**Comment by detiber** [comment]
@sdodson @brenton 

Right, I think the following would accomplish what we are looking for and move over to the new namespaced groups.

in  playbooks/byo/openshift-cluster/config.yml:
```
 @@ -2,8 +2,8 @@
 - include: ../../common/openshift-cluster/config.yml
   vars:
     g_etcd_group: "{{ 'openshift_etcd' if (groups['openshift_etcd'] is defined and groups['openshift_etcd'] | count > 0) else 'etcd' }}"
     g_masters_group: "{{  'openshift_masters' if (groups['openshift_masters'] is defined and groups['openshift_masters'] | count > 0) else 'masters' }}"
     g_nodes_group: "{{ 'openshift_nodes' if (groups['openshift_nodes'] is defined and groups['openshift_nodes'] | count > 0) else 'nodes' }}"
```

The etcd part being a bit iffy, since it could be an empty group, but hope that gets my idea across.

**Comment by brenton** [comment]
I'm definitely supportive of these sorts of refactorings as long as they're backwards compatible and the installer / docs are updated. :)

**Pull request merged**
