### PR TITLE
Repo rework

### PR DESCRIPTION
**Pull request by detiber**
With fedora no longer needing special repo configuration, it only leaves the config needed for the CentOS PaaS SIG, so simplifying for the particular use case needed.

Also removing cleanup of repos on changing deployment_type, since it was mainly used in dev and introduced a lot of complexity.

### CODE REVIEW

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
@sdodson @abutcher ptal

**Comment by sdodson** [comment]
LGTM

**Comment by detiber** [comment]
@maxamillion

**Pull request merged**
