### PR TITLE
Fix for bug 1298

### LINKED ISSUE #1298: Ansible changes for nuage seem to be broken
Ran the upstream openshift installer as follows

ansible-playbook -vvvv -i nodes playbooks/byo/config.yml

<pre>
# nodes file
# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
masters
nodes

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root

# If ansible_ssh_user is not root, ansible_sudo must be set to true
#ansible_sudo=true

deployment_type=openshift-enterprise

openshift_use_openshift_sdn=False

openshift_use_nuage=True
os_sdn_network_plugin_name='nuage/vsp-k8s'

vsd_api_url=https://192.168.100.200:8443
vsp_version=v3_2
enterprise=nuage
domain=openshift-vishal

vsc_active_ip=192.168.100.201
#vsc_standby_ip=192.168.100.202
uplink_interface=eth0

nuage_kubemon_rpm=http://172.22.61.12/openshift/RPMS/x86_64/nuagekubemon-0.0-1.el7.x86_64.rpm
vrs_rpm=http://172.22.61.12/openshift/RPMS/x86_64/nuage-openvswitch-3.2.6-225.el7.x86_64.rpm
plugin_rpm=http://172.22.61.12/openshift/RPMS/x86_64/nuage-k8s-plugin-0.0-1.el7.x86_64.rpm

nuagekubemon_log_dir=/var/log/nuagekubemon

# host group for masters
[masters]
master.nuageopenshift.com openshift_node_labels="{'region': 'infra', 'zone': 'default'}"

# host group for nodes, includes region info
[nodes]
node1.nuageopenshift.com openshift_node_labels="{'region': 'primary', 'zone': 'east'}"
node2.nuageopenshift.com openshift_node_labels="{'region': 'primary', 'zone': 'west'}"
</pre>

I hit the following error

<pre>
2016-01-28 12:06:12,006 p=12563 u=ovs-7 |  TASK: [nuage_node | Set the vsp-k8s.yaml] *************************************
2016-01-28 12:06:12,071 p=12563 u=ovs-7 |  <node1.nuageopenshift.com> ESTABLISH CONNECTION FOR USER: root
2016-01-28 12:06:12,072 p=12563 u=ovs-7 |  <node1.nuageopenshift.com> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/ovs-7/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 node1.nuageopenshift.com /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1454011572.07-202707713624084 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1454011572.07-202707713624084 && echo $HOME/.ansible/tmp/ansible-tmp-1454011572.07-202707713624084'
2016-01-28 12:06:12,075 p=12563 u=ovs-7 |  <node2.nuageopenshift.com> ESTABLISH CONNECTION FOR USER: root
2016-01-28 12:06:12,076 p=12563 u=ovs-7 |  <node2.nuageopenshift.com> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/ovs-7/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 node2.nuageopenshift.com /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1454011572.08-98479345617300 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1454011572.08-98479345617300 && echo $HOME/.ansible/tmp/ansible-tmp-1454011572.08-98479345617300'
2016-01-28 12:06:12,132 p=12563 u=ovs-7 |  fatal: [node2.nuageopenshift.com] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'openshift_node_master_api_url' is undefined", 'failed': True}
2016-01-28 12:06:12,132 p=12563 u=ovs-7 |  fatal: [node2.nuageopenshift.com] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'openshift_node_master_api_url' is undefined", 'failed': True}
2016-01-28 12:06:12,150 p=12563 u=ovs-7 |  fatal: [node1.nuageopenshift.com] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'openshift_node_master_api_url' is undefined", 'failed': True}
2016-01-28 12:06:12,151 p=12563 u=ovs-7 |  fatal: [node1.nuageopenshift.com] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'openshift_node_master_api_url' is undefined", 'failed': True}
</pre>

### PR DESCRIPTION
**Pull request by vishpat**
resolves #1298

### CODE REVIEW

**Comment by detiber** [comment]
ok to test

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
@vishpat can you update the description of the PR to say:
resolves https://github.com/openshift/openshift-ansible/issues/1298

**Comment by abutcher** [comment]
@brenton Good to go

**Pull request merged**
