### PR TITLE
Bug 1427080: The router wasn't upgraded to current ose-haproxy-router image version

### PR DESCRIPTION
**Pull request by abutcher**
Corrects a typo and moves namespace arg to end of `oc_obj` command to avoid the error seen below with `--all-namespaces`.

```
/bin/oc --all-namespaces get pods --selector=router -o json
Error: unknown command "pods" for "oc"

Did you mean this?
        logs

Run 'oc --help' for usage.
```

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1427080

### CODE REVIEW

**Comment by abutcher** [comment]
aos-ci-test

**Comment by kwoodson** [comment]
@abutcher, seems like a good change.

**Comment by detiber** [comment]
@abutcher travis failures

**Comment by sdodson** [comment]
Looks like tests need to be updated?

**Comment by abutcher** [comment]
Yep! Updates incoming.

**Comment by abutcher** [comment]
aos-ci-test

**Pull request merged**
