### PR TITLE
BZ1427040: Create hosted registry service

### PR DESCRIPTION
**Pull request by mtnbikenc**
Fixes 1427040

### CODE REVIEW

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by sdodson** [comment]
I think this will solve the immediate problem, but Clayton pointed out we also need to sign the cert with 'docker-registry.default.svc' as we may need to use the short name in the future. I'll try to find out more.

**Comment by kwoodson** [comment]
@sdodson, are you referring to this piece of the code for signing?

Do we need to add something to that?

https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_hosted/tasks/registry/secure.yml#L21-L32

**Comment by sdodson** [comment]
Yeah, we should add "docker-registry.default.svc" to the list. I'll get it tomorrow unless you guys get it first, this isn't critical today though.

**Comment by smarterclayton** [comment]
I'm not actually seeing the registry created:

https://ci.openshift.redhat.com/jenkins/job/zz_origin_gce_image/139/consoleFull#394909855849c75fe4b0052e114d805c

and more detail here:

```
TASK [openshift_hosted : Create OpenShift registry] ****************************
task path: /usr/share/ansible/openshift-ansible/roles/openshift_hosted/tasks/registry/registry.yml:91
Wednesday 01 March 2017  02:39:42 +0000 (0:00:00.039)       0:16:49.599 *******
Using module file /usr/share/ansible/openshift-ansible/roles/lib_openshift/library/oc_adm_registry.py
<35.184.102.120> ESTABLISH SSH CONNECTION FOR USER: cloud-user
<35.184.102.120> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=900s -o GSSAPIAuthentication=no -o StrictHostKeyChecking=no -o 'IdentityFile="/home/cloud-user/.ssh/google_compute_engine"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=cloud-user -o ConnectTimeout=10 -o ControlPath=/var/tmp/%h-%r 35.184.102.120 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-zndtbcwbxyrrdsiagqpowxuoncgojmyf; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
changed: [ci-claytontest-ig-m-qpct] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "daemonset": false,
            "debug": false,
            "edits": [
                {
                    "action": "put",
                    "key": "spec.strategy.rollingParams",
                    "value": {
                        "intervalSeconds": 1,
                        "maxSurge": "25%",
                        "maxUnavailable": "25%",
                        "timeoutSeconds": 600,
                        "updatePeriodSeconds": 1
                    }
                },
                {
                    "action": "put",
                    "key": "spec.template.spec.containers[0].livenessProbe.httpGet.scheme",
                    "value": "HTTPS"
                },
                {
                    "action": "put",
                    "key": "spec.template.spec.containers[0].readinessProbe.httpGet.scheme",
                    "value": "HTTPS"
                }
            ],
            "enforce_quota": false,
            "env_vars": {
                "REGISTRY_HTTP_TLS_CERTIFICATE": "/etc/secrets/registry.crt",
                "REGISTRY_HTTP_TLS_KEY": "/etc/secrets/registry.key"
            },
            "force": true,
            "images": "openshift/origin-${component}:${version}",
            "kubeconfig": "/etc/origin/master/admin.kubeconfig",
            "labels": null,
            "latest_images": false,
            "mount_host": null,
            "name": "docker-registry",
            "namespace": "default",
            "ports": [
                "5000"
            ],
            "replicas": 1,
            "selector": "role=infra",
            "service_account": "registry",
            "state": "present",
            "tls_certificate": null,
            "tls_key": null,
            "volume_mounts": [
                {
                    "name": "registry-certificates",
                    "path": "/etc/secrets",
                    "secret_name": "registry-certificates",
                    "type": "secret"
                }
            ]
        },
        "module_name": "oc_adm_registry"
    },
    "results": {
        "results": [],
        "returncode": 0
    },
    "state": "present"
}
```

It *looks* (at first glance) that creating the service up front then triggers the "this registry already exists" because the service does in fact exist.  But the actual deployment doesn't.  So I don't think this fix works.

**Comment by smarterclayton** [comment]
Since `oc adm registry` will not create anything if the service already exists.

**Comment by detiber** [comment]
@smarterclayton I believe that issue is being addressed here: https://github.com/openshift/openshift-ansible/pull/3493

**Comment by smarterclayton** [comment]
Timeframe on that?

**Comment by detiber** [comment]
@sdodson ^

**Pull request merged**
