### PR TITLE
Bug 1491636 - honor openshift_logging_es_ops_nodeselector

### PR DESCRIPTION
**Pull request by wozniakjan**
https://bugzilla.redhat.com/show_bug.cgi?id=1491636

### CODE REVIEW

**Comment by ewolinetz** [comment]
Please be sure to also open a cherry-pick on release-3.6

**Comment by wozniakjan** [comment]
There appears to be a fix for this in 3.6 https://github.com/openshift/openshift-ansible/pull/5124
I will sync with @jcantrill if maybe he would prefer this to be a "forward-port" of his PR

**Comment by jcantrill** [comment]
aos-ci-test

**Comment by wozniakjan** [comment]
I don't think those failures are related to the PR. Both happen before logging roles are included. 

One is unable to run GetNodes in taskrunner
`2017-09-15 11:03:54,729 - taskrunner - ERROR - Caught exception while running 'GetNodes'`

Second is missing a package yum wants to install
`<10.8.244.174> (0, '\r\n{"changed": false, "results": ["No package matching \'atomic-openshift-docker-excluder-3.6.173.0.33*\' found available, installed or updated"]`

**Comment by wozniakjan** [comment]
aos-ci-test

**Comment by stevekuznetsov** [comment]
@wozniakjan the `aos-ci-test` is deprecated -- no need to use it.

**Comment by wozniakjan** [comment]
@stevekuznetsov thanks, what command should I use to rerun the tests? There was a short message at some point suggesting `/retest` but is no longer here and didn't seem to do much. The failures don't seem to be relevant to my change

**Comment by stevekuznetsov** [comment]
@wozniakjan yeah so things are a little messy for PRs that have statuses from the past but you should be looking at the following status for things you need to do:

```
 Submit Queue — PR does not have lgtm label. 
```

So right now you have all of the green tests you need to merge, you just need to find someone to review the content and sign off on it.

**Pull request merged**
