### PR TITLE
Updated Selinux Requirement Check Logic to distinguish mode.

### PR DESCRIPTION
**Pull request by Jooho**
Selinux 'Enforcing' mode is a requirement for installing OpenShift but the 'when' condition check only if Selinux is enabled or not. So OpenShift can be installed with Selinux 'Permissive' mode which is not what official document[1] describes:

```
Security-Enhanced Linux (SELinux) must be enabled on all of the servers before installing OpenShift Container Platform or the installer will fail. Also, configure SELINUX=enforcing and SELINUXTYPE=targeted in the /etc/selinux/config file:
```

With this PR, I added following conditions:
- ansible_selinux.mode != 'enforcing'   
- ansible_selinux.config_mode != 'enforcing'  (for permanent config)

Therefore, the task will fail if 'selinux mode' is not 'enforcing'.

Thanks,
Jooho Lee.

[1]https://docs.openshift.com/container-platform/3.10/install/prerequisites.html

### CODE REVIEW

**Comment by vrutkovs** [comment]
I don't think we require `enforcing`, it should also work with `permissive`

**Comment by Jooho** [comment]
@vrutkovs 
If so, it is doc bug. right?

**Comment by vrutkovs** [comment]
@sdodson @michaelgugino WDYT?

**Comment by Jooho** [comment]
@vrutkovs I found this logic to check "Enforcing" and "Permissive" from here.

https://github.com/openshift/openshift-ansible/blob/75e91451169aa16b41b535983460c3f28b22b28b/roles/openshift_openstack/tasks/node-configuration.yml#L9-L12

Moreover, I believe we always say OpenShift is much secure because of seliux but using permissive mode does not sound real safe.

**Comment by Jooho** [comment]
Created Issues #9823   (sorry for the opposite workflow).

Ok if OpenShift does not need Selinux "Enforcing" mode, please let me know. Then, I will close this PR.

**Comment by vrutkovs** [comment]
Master branch is closed! A major refactor is ongoing in devel-40. Changes for 3.x should be made directly to the latest release branch they're relevant to and backported from there.

**Pull request closed without merging**
