### PR TITLE
Apply app label to console replica sets and pods

### PR DESCRIPTION
**Pull request by spadgett**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1584725

/cc @sdodson @mfojtik @tnozicka

### CODE REVIEW

**Comment by spadgett** [comment]
@sdodson I've verified that this fixes the problem

**Comment by spadgett** [comment]
> Stage PROVISION CLOUD RESOURCES [00h 10m 33s] failed.

/retest

**Comment by sdodson** [comment]
@spadgett The fedora failures seem legit, can you take a look at them? I wonder why they're only happening there. here's the inventory used by these jobs https://github.com/openshift/openshift-ansible/blob/master/.papr.all-in-one.inventory

```
STDERR:

'app' already has a value (openshift-web-console), and --overwrite is false
'app' already has a value (openshift-web-console), and --overwrite is false
```

**Comment by spadgett** [comment]
/hold cancel

thanks for catching that @sdodson, updated

**Pull request merged**
