### PR TITLE
Playbook Consolidation - openshift-logging

### PR DESCRIPTION
**Pull request by mtnbikenc**
- Create playbooks/openshift-logging directory
- Consolidate openshift-logging playbooks to above
- Fix all include path references throughout playbooks/

Trello: https://trello.com/c/UWYQzfs9/571-2-playbook-consolidation-openshift-logging

### CODE REVIEW

**Comment by mtnbikenc** [comment]
The CI logging test will need to be updated with the new location for the logging install playbook.

**Comment by sdodson** [comment]
@ewolinetz can someone from logging and @mtnbikenc stage a change for the logging tests in such a way that on master it uses these new playbooks but on older branches it uses the old playbooks?

**Comment by ewolinetz** [comment]
@sdodson we may need to get hacky to figure out how to run a specific playbook against a certain version. I don't believe there is a simple way to differentiate the branches like we do for openshift-ansible

**Comment by michaelgugino** [comment]
@sdodson @ewolinetz This is an instance of something that can be abstracted into openshift-ansible.

CI calls openshift-ansible/tests/install-logging.sh

We can put whatever version in that file we wish.

**Comment by mtnbikenc** [comment]
> CI calls openshift-ansible/tests/install-logging.sh
And we could have something different based on the requirements of what branch we are on.  Seems tests in CI don't play well as the product moves forward over time with different branches.

**Comment by mtnbikenc** [comment]
Updated PR to temporarily preserve CI compatibility, but still allow refactoring to proceed.

**Comment by mtnbikenc** [comment]
bot, retest

**Comment by mtnbikenc** [comment]
bot, retest this please

**Comment by mtnbikenc** [comment]
@jlebon Could you provide some guidance on how to fix the fedora/27/atomic test error?

**Comment by jlebon** [comment]
Yeah, infra is being flaky right now. Let me restart it once more.

**Comment by mtnbikenc** [comment]
Kick
/hold

**Pull request merged**
