### PR TITLE
Rename osc to oc

### PR DESCRIPTION
**Pull request by smarterclayton**
Will be merged after openshift/origin#2900

### CODE REVIEW

**Comment by smarterclayton** [comment]
Once this is merged older deployments will fail.  We either need to add fallback code or force people to use the latest packages.

**Comment by smarterclayton** [comment]
@detiber

**Comment by detiber** [comment]
@smarterclayton I've updated https://github.com/openshift/openshift-ansible/pull/248 to handle both possible binary names.

**Comment by smarterclayton** [comment]
If it's fixed in #248 i'm going to close here

**Pull request closed without merging**
