### PR TITLE
Don't use from ansible.module_utils.six as its no longer available in Ansible 2.4

### PR DESCRIPTION
**Pull request by vrutkovs**

### CODE REVIEW

**Comment by vrutkovs** [comment]
Test flake: https://github.com/openshift/origin/issues/17882

**Comment by vrutkovs** [comment]
Test flakes

/retest

**Comment by vrutkovs** [comment]
Flaaaakes

/retest

**Comment by sdodson** [comment]
repeated post install flakes, if this broke it'd break the install

**Pull request merged**
