### PR TITLE
Properly quote "true" and "false" strings for include_granted_scopes.

### LINKED ISSUE #2454: Invalid boolean conversion for extraAuthorizeParameters include_granted_scopes
When trying to define an OpenIDConnect ID provider in Ansible hosts by setting include_granted_scopes. If the value is “true” with the double quotes then the definition is invalid. 

For instance extraAuthorizeParameters': {'include_granted_scopes': ‘\”true\"'} results in include_granted_scopes: false in the configuration.

The issue seems to be that the value of include_granted_scopes is evaluated as ansible_bool.

https://github.com/openshift/openshift-ansible/blob/b8e72ea2143834317043f19cbc3dddf8ad9047a5/filter_plugins/openshift_master.py#L388

### PR DESCRIPTION
**Pull request by adelton**
Fixes #2454.

### CODE REVIEW

**Comment by enj** [comment]
I do not understand why ansible needs to do anything special here at all.  The value is a string, so why are we parsing it and then simply turning it back into a string?  Why not simply pass it through?

xref #2896 https://bugzilla.redhat.com/show_bug.cgi?id=1488505

@sdodson @mtnbikenc @smunilla

**Comment by sdodson** [comment]
I think this would properly handle the situation where the user had provided the value as a boolean and we convert it into a string. We should be forgiving of user input if we can.

**Comment by sdodson** [comment]
@adelton you've tested both quoted  and unquoted values?

**Comment by ashcrow** [comment]
@enj I think because ansible tries to be a bit too helpful. For instance:

```yaml
---
- name: Show ansible being too helpful
  hosts: 127.0.0.1
  gather_facts: no
  tasks:

  - set_fact:
      test: "true"

  - debug:
      var: test

  - debug:
      msg: "{{ test }}"
```

Results

```
...
TASK [set_fact] *****************************************************************************************************************************************************************************************************
Monday 11 September 2017  16:48:10 -0400 (0:00:00.038)       0:00:00.038 ******                           
ok: [127.0.0.1]                                      

TASK [debug] ********************************************************************************************************************************************************************************************************
Monday 11 September 2017  16:48:10 -0400 (0:00:00.010)       0:00:00.049 ******                           
ok: [127.0.0.1] => {                                 
    "test": true                                     
}                                                    

TASK [debug] ********************************************************************************************************************************************************************************************************
Monday 11 September 2017  16:48:10 -0400 (0:00:00.014)       0:00:00.063 ******                           
ok: [127.0.0.1] => {}                                

MSG:                                                 

True                                                 


PLAY RECAP **********************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=3    changed=0    unreachable=0    failed=0       
...
```

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by enj** [comment]
Can we make sure Ansible will not try to be extra helpful and auto cast the string into a bool?

**Comment by sdodson** [comment]
Reading through it I believe that should be fine.
[merge]

**Comment by adelton** [comment]
Note that this pull request was not really correct: https://github.com/openshift/openshift-ansible/issues/2454#issuecomment-329101226

**Comment by adelton** [comment]
@sdodson, could we have this issue reopened?

**Pull request merged**
