### PR TITLE
[WIP] Deprecate the legacy manageiq role

### PR DESCRIPTION
**Pull request by tbielawa**
# DON'T MERGE THIS

My understanding is that the openshift_manageiq role should be no more. This removes all traces of the legacy role from this repository.

* **See also:** https://github.com/openshift/openshift-ansible/issues/4883

### CODE REVIEW

**Comment by tbielawa** [comment]
@brenton @sdodson 

We talked about deprecating this role on Wednesday. This PR will remove *nearly* all traces of it, save for a README.md file pointing people to `openshift_cfme`. Is this what you're looking for?

**Comment by brenton** [comment]
Pretty much.  If you haven't already, I'd talk with a few of the original authors (and check our docs) to see if anyone still relies on this code.

**Comment by tbielawa** [comment]
emailed some folks listed in the early commits for this role

**Comment by tbielawa** [comment]
Just to be clear

> (and check our docs)

There are no references to this role online.

**Comment by enoodle** [comment]
This role is not parallel to openshit_cfme. This one is needed to allow managing the openshift cluster from manageiq and the other one for deploying cfme ( manageiq ) on openshift. I don't understand at all why it was decided that this role is deprecated but I don't think so at all, In fact I have been trying to merge updates to it in the last several days. Cc @simon3z

**Comment by tbielawa** [comment]
@enoodle said

> This role is not parallel to openshit_cfme. This one is needed to allow managing the openshift cluster from manageiq
> and the other one for deploying cfme ( manageiq ) on openshift. I don't understand at all why it was decided that this
> role is deprecated but I don't think so at all, In fact I have been trying to merge updates to it in the last several days.
> Cc @simon3z

What with the complete lack of documentation around this role, i.e., **no README at all** we were confused as to why it even existed. Thank you for the clarification @enoodle

**Comment by tbielawa** [comment]
TODO: Make a README for this role because it has actual relevance.

**Comment by tbielawa** [comment]
@enoodle if you wouldn't mind submitting a PR for merging that included a README with it we would be most grateful :heart:

**Comment by enoodle** [comment]
https://github.com/openshift/openshift-ansible/pull/5009

**Pull request closed without merging**
