### PR TITLE
Standardize all Origin versioning on 3.6

### PR DESCRIPTION
**Pull request by mtnbikenc**

### CODE REVIEW

**Comment by jarrpa** [comment]
@mtnbikenc The GlusterFS role related changes LGTM. I'll just have to make sure to rebase and merge-resolve an existing PR if this one goes in first.. :)

**Comment by sdodson** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
aos ci tests had to be rerun but did not complete before merge job checked task completion.
re[merge]

**Comment by sdodson** [comment]
[merge]

**Comment by mtnbikenc** [comment]
Rebased to resolve merge conflicts, again.

**Comment by mtnbikenc** [comment]
aos-ci-test

**Pull request merged**
