### PR TITLE
Edits to fix to typos, grammar, and product branding in cli_installer

### PR DESCRIPTION
**Pull request by tpoitras**
When doing an install today, I found some typos so decided I'd submit a PR to fix them instead of making a BZ.

While I was in there, I found some minor grammar fixes, and simple branding things like:
s/ansible/Ansible
s/openshift/OpenShift or s/Openhift/OpenShift

### CODE REVIEW

**Comment by tpoitras** [comment]
Ping @sdodson for sanity check, hope I'm not over-stepping boundaries here. :smile:

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
@tpoitras ok, we're down to a real test failure here. Can you update utils/test/cli_installer_tests.py", line 725 to match the new strings?

```
+ nosetests --with-xunit --xunit-file=/home/jenkins/workspace/openshift-ansible-2-unit-tests/nosetests.xml utils/
.......................F...........
======================================================================
FAIL: test_quick_ha_only_2_masters (test.cli_installer_tests.UnattendedCliTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "/home/jenkins/workspace/openshift-ansible-2-unit-tests/openshift-ansible/utils/test/cli_installer_tests.py", line 725, in test_quick_ha_only_2_masters
    self.assertTrue("A minimum of 3 Masters are required" in result.output)
AssertionError: False is not true
```

**Comment by tpoitras** [comment]
Thanks @sdodson - I did a change on that  line:

s/Masters/masters

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
@smunilla just string updates from docs team to bring things in line with standards.

**Comment by smunilla** [comment]
:+1:

**Pull request merged**
