### PR TITLE
Removing openshift_repo dependencies.  Moving to beginning of openshift_cluster.

### PR DESCRIPTION
**Pull request by kwoodson**

### CODE REVIEW

**Comment by kwoodson** [comment]
@mtnbikenc, please take a look at this one.  I am not as sure as to where to include `openshift_repo` but I chose the config.yml.  Please let me know if you think this isn't a good place for this.  I did complete a successful cluster install using this commit.

With these changes I was able to shave 1:28 off of an install.  (37:51 down to 36:23).  This is only about a 4.8% improvement with my 8 node cluster.

**Comment by mtnbikenc** [comment]
This change reduces the calls to openshift_repos during byo/config.yml from 41 to 1.  With the other PR moving openshift_sanitize_inventory up, it would be a candidate to remove it from the openshift_repos dependencies.  I will evaluate the other roles where openshift_repos has been removed and see if it affects any other execution paths for other entry point playbooks.

**Comment by kwoodson** [comment]
@mtnbikenc, 
> With the other PR moving openshift_sanitize_inventory up, it would be a candidate to remove it from the openshift_repos dependencies.

Agreed.  Its going to get more difficult the longer we wait on merging other PRs into master

>  I will evaluate the other roles where openshift_repos has been removed and see if it affects any other execution paths for other entry point playbooks.

Thanks for doing this.  I thought that the `std_include.yml` might be a good place for this if `config.yml` isn't the right place.  Thoughts?

I was going to take a bit deeper dive today at this but figured your graphing tools would probably be much faster.  Maybe I need a refresher on the graphing tools and I can attempt to assist with additions to that code.  Let me know if you want to sync up via video conference or IRC.

**Comment by kwoodson** [comment]
@mtnbikenc, I'm moving the `openshift_repos` into the `std_include.yml`.  This moves this role to the front initial setup of repositories since `openshift_version` requires repositories to be laid down.

I know we don't want `std_include.yml` expanded but the `openshift_verion` role depended on `openshift_repos` before so this shouldn't be any worse than before for `std_include.yml`.  Now that the repositories have been initialized in the beginning we can remove their dependencies which is what the majority of this PR incorporates.

**Comment by kwoodson** [comment]
[test]

**Comment by sdodson** [comment]
travis errors and needs aos ci test once those are cleared

**Comment by kwoodson** [comment]
aos-ci-test

**Comment by kwoodson** [comment]
Rebased with master.

**Comment by kwoodson** [comment]
aos-ci-test

**Comment by kwoodson** [comment]
@mtnbikenc, good catch.  I rebased and added the init repos file.

**Comment by kwoodson** [comment]
aos-ci-test

**Comment by kwoodson** [comment]
flake
https://github.com/openshift/origin/issues/8571
https://github.com/openshift/origin/issues/10162

**Comment by kwoodson** [comment]
Looks like we need to rebase and run the gauntlet.

**Comment by sdodson** [comment]
Rebase and once aos-ci-test is done i'll merge this. I want to try to get all of this landed today.

**Comment by kwoodson** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
Flake https://github.com/openshift/origin/issues/14898 yum repo

**Comment by mtnbikenc** [comment]
[merge]

**Comment by kwoodson** [comment]
flake
https://github.com/openshift/origin/issues/8571

**Comment by kwoodson** [comment]
[merge]

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
@kwoodson Somehow `initialize_openshift_repos.yml` was dropped from the commits during the last rebase.

**Comment by kwoodson** [comment]
@mtnbikenc, thanks for watching this one.  I'm not sure what happened but I added the file again.

**Comment by kwoodson** [comment]
aos-ci-test

**Comment by kwoodson** [comment]
@sosiouxme @rhcarvalho,

Any idea what happened here? 
```
		     Message:  Failed to get D-Bus connection: Operation not permitted
```

**Comment by sosiouxme** [comment]
@kwoodson no, but it's happening quite a lot :(
https://github.com/openshift/origin/issues/15769

**Comment by ingvagabund** [comment]
Aweeeeeesooome, thanks @kwoodson

**Pull request merged**
