### PR TITLE
Cleanup following move to openshift-tools

### LINKED ISSUE #1935: rsync error: some files could not be transferred (code 23)
Machine : Macox X
Virtualbox : Version 5.0.16 r105871
Vagrant : Version 5.0.16 r105871

Command executed under openshift-ansible project 

````
OPENSHIFT_NUM_NODES=0 vagrant up
Bringing machine 'master' up with 'virtualbox' provider...
==> master: Checking if box 'centos/7' is up to date...
==> master: Clearing any previously set forwarded ports...
==> master: Clearing any previously set network interfaces...
==> master: Preparing network interfaces based on configuration...
    master: Adapter 1: nat
    master: Adapter 2: hostonly
==> master: Forwarding ports...
    master: 8443 => 8443 (adapter 1)
    master: 22 => 2222 (adapter 1)
==> master: Running 'pre-boot' VM customizations...
==> master: Booting VM...
==> master: Waiting for machine to boot. This may take a few minutes...
    master: SSH address: 127.0.0.1:2222
    master: SSH username: vagrant
    master: SSH auth method: private key
    master: Warning: Connection timeout. Retrying...
    master: Warning: Remote connection disconnect. Retrying...
==> master: Machine booted and ready!
==> master: Checking for guest additions in VM...
    master: No guest additions were detected on the base box for this VM! Guest
    master: additions are required for forwarded ports, shared folders, host only
    master: networking, and more. If SSH fails on this machine, please install
    master: the guest additions and repackage the box to continue.
    master: 
    master: This is not an error message; everything may continue to work properly,
    master: in which case you may ignore this message.
==> master: Setting hostname...
==> master: Configuring and enabling network interfaces...
==> master: Rsyncing folder: /Users/chmoulli/Temp/ansible-openshift/openshift-ansible/ => /home/vagrant/sync
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /Users/chmoulli/Temp/ansible-openshift/openshift-ansible/
Guest path: /home/vagrant/sync
Command: rsync --verbose --archive --delete -z --copy-links --no-owner --no-group --rsync-path sudo rsync -e ssh -p 2222 -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i '/Users/chmoulli/.vagrant.d/insecure_private_key' --exclude .vagrant/ /Users/chmoulli/Temp/ansible-openshift/openshift-ansible/ vagrant@127.0.0.1:/home/vagrant/sync
Error: Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.
symlink has no referent: "/Users/chmoulli/Temp/ansible-openshift/openshift-ansible/bin/openshift_ansible/multi_inventory.py"
rsync error: some files could not be transferred (code 23) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-47/rsync/main.c(992) [sender=2.6.9]
````

### PR DESCRIPTION
**Pull request by abutcher**
@joelddiaz PTAL, removing files from

```
bin/
roles/openshift_ansible_inventory
test/
```

Fixes #1935

### CODE REVIEW

**Comment by abutcher** [comment]
ok to test

**Comment by abutcher** [comment]
aos-ci-test

**Comment by abutcher** [comment]
aos-ci-test

**Comment by arilivigni** [comment]
aos-ci-test

**Comment by arilivigni** [comment]
@abutcher I am looking into this it seems envs are not getting passed in from job to job

**Comment by arilivigni** [comment]
@abutcher this is a result of a security fix.  I will update our jobs and verify that works.  
More info:
https://issues.jenkins-ci.org/browse/JENKINS-29031

**Comment by arilivigni** [comment]
aos-ci-test

**Comment by arilivigni** [comment]
aos-ci-test

**Comment by arilivigni** [comment]
aos-ci-test

**Comment by arilivigni** [comment]
aos-ci-test

**Comment by arilivigni** [comment]
aos-ci-test

**Comment by arilivigni** [comment]
aos-ci-test

**Comment by arilivigni** [comment]
@abutcher I think I finally have this fixed matrix jobs will make this easier in the long term

**Comment by abutcher** [comment]
Thanks @arilivigni udabes!

**Comment by arilivigni** [comment]
@abutcher np I am sorry that this had such a huge ripple effect from just upgrading Jenkins.

**Pull request merged**
