### PR TITLE
Use the proper pod subnet instead the services one

### LINKED ISSUE #4809: flanneld with OCP 3.5: Incorrect pod IP & no pod connectivity
#### Description

Experiencing strange behavior when deploying OCP 3.5 (on RHOSP8) using flanneld SDN (host-gw backend). Although the Ansible deployment is successful and pods can be launched, pod IP's are on the service network, not the clusterNetwork. If this is expected behavior, iptables are blocking traffic to/from pods.

Has anyone had experience (or success) deploying with flanneld using host-gw backend on Openstack?

##### Version

```
 ansible 2.3.1.0
  config file = /home/e307033/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

openshift-ansible-3.6.89.0-1

oc v3.5.5.31
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://***.com:8443
openshift v3.5.5.31
kubernetes v1.5.2+43a9be4
```

##### Steps To Reproduce
1. Deploy OCP 3.5 via RPM using flanneld with host-gw backend
2. Attempt a pod deployment (e.g. Jenkins)
3. Pod receives an IP address on the service subnet (172.30.0.0/16), not the clusterNetwork (10.128.0.0/14)

##### Expected Results
- Pods receive an IP on the clusterNetwork
- Traffic flows as expected to/from pods

##### Observed Results
- Pods fail to obtain an IP on the clusterNetwork using flanneld with host-gw backend. 
- iptables fail to permit traffic to/from pods.
- Halting iptables permits traffic to/from pods on the service network

##### Additional Information

- This OCP 3.5 deployment is atop RHOSP8
- oadm diagnostics fails because pods cannot communicate with internal/sky DNS
- Neutron port security was disabled for all instance ports (required when using flanneld with OCP on Openstack)
- An identical installation using the default SDN works fine, but I'm really attempting to avoid double-encapsulation of traffic

```
Red Hat Enterprise Linux Server release 7.3 (Maipo)
```

### PR DESCRIPTION
**Pull request by e-minguez**
Fixes #4809 ?
Related to https://bugzilla.redhat.com/show_bug.cgi?id=1473858

### CODE REVIEW

**Comment by e-minguez** [comment]
I've amend the commit as I've tested it and it didn't worked.

Now it works as:

* Flannel network uses the ```osm_cluster_network_cidr``` value
* Flannel SubnetLen needs to be specified in CIDR notation, and as ```osm_host_subnet_length``` is "number of bits to allocate to each host’s subnet"[1], the SubnetLen is calculated by 32 - ```osm_host_subnet_length```.
* SubnetMin is not required

Tested in an OSP environment with the provided changes:

```
[cloud-user@bastion ~]$ oc new-project myproject001
Now using project "myproject001" on server "https://ocp.edu.example.com:8443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-ex.git

to build a new example application in Ruby.

[cloud-user@bastion ~]$ oc new-app openshift/hello-openshift
--> Found Docker image c7d26ad (About an hour old) from Docker Hub for "openshift/hello-openshift"

    * An image stream will be created as "hello-openshift:latest" that will track this image
    * This image will be deployed in deployment config "hello-openshift"
    * Ports 8080/tcp, 8888/tcp will be load balanced by service "hello-openshift"
      * Other containers can access this service through the hostname "hello-openshift"
    * WARNING: Image "openshift/hello-openshift" runs as the 'root' user which may not be permitted by your cluster administrator

--> Creating resources ...
    imagestream "hello-openshift" created
    deploymentconfig "hello-openshift" created
    service "hello-openshift" created
--> Success
    Run 'oc status' to view your app.

[cloud-user@bastion ~]$ oc get pod hello-openshift-1-7kgl7 -o jsonpath={.status.podIP}
172.29.31.2

[cloud-user@bastion ~]$ oc get svc
NAME              CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
hello-openshift   172.30.181.36   <none>        8080/TCP,8888/TCP   4m
```

[1] https://github.com/openshift/openshift-ansible/blob/master/inventory/byo/hosts.origin.example#L671-L672

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[test]

**Comment by sdodson** [comment]
[test]

**Comment by e-minguez** [comment]
Is there anything I can do for pushing this @sdodson ? Thanks!

**Comment by sdodson** [comment]
[merge]

**Comment by miheer** [comment]
After setting ->
osm_cluster_network_cidr=10.128.0.0/14
osm_host_subnet_length=9

I get the following error ->
AnsibleError: {{ 32 - openshift.master.sdn_host_subnet_length }}: Unexpected templating type error occurred on ({{ 32 - openshift.master.sdn_host_subnet_length }}): unsupported operand type(s) for -: 'int' and 'AnsibleUnsafeText'

What needs to be done ?

**Comment by miheer** [comment]
The following helped to set the CIDR ->

openshift.master.sdn_cluster_network_cidr=10.128.0.0/14
openshift.master.sdn_host_subnet_length=9

**Pull request merged**
