### PR TITLE
rename openshift_metrics to openshift_hosted_metrics

### PR DESCRIPTION
**Pull request by jcantrill**
cc @sdodson @detiber  per our discussion.  Are there affiliated openshift-docs as well that need to be updated?

### CODE REVIEW

**Comment by detiber** [comment]
@jcantrill looks like there is a merge conflict

**Comment by jcantrill** [comment]
@detiber rebased

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
@sdodson lgtm, do we need to update any documentation as well?

**Comment by sdodson** [comment]
> @sdodson lgtm, do we need to update any documentation as well?

no, we never documented the role name, so should be a noop as far as end users are aware.

**Comment by sdodson** [comment]
I'd like to hold this for a bit until @dgoodwin says he's done looking at another metrics issue.

**Comment by detiber** [comment]
@jcantrill looks like this needs a rebase.

@sdodson @dgoodwin any blockers on this besides the rebase?

**Comment by sdodson** [comment]
No, lets go ahead.

**Comment by sdodson** [comment]
Once it's rebased we're good to go.

**Comment by jcantrill** [comment]
@sdodson rebased...

**Comment by abutcher** [comment]
aos-ci-test

**Pull request merged**
