### PR TITLE
tox integration: don't actually run tests

### PR DESCRIPTION
**Pull request by sosiouxme**
The runtime environment for these test playbooks keeps breaking expectations that things will run on real hosts with users and such. The actual value they're providing would be better provided by just adding tests of the check playbooks against test clusters with real hosts (which I'll add to my tech debt list).

### CODE REVIEW

**Comment by sosiouxme** [comment]
@stevekuznetsov can't remember if anything was explicitly calling the integration tests now... is it a Jenkins job mod to get this out of the tests?

/cc @mazzystr

**Comment by mazzystr** [comment]
LGTM.  Do we need someone with more exp to review as well?  @sdodson

**Comment by stevekuznetsov** [comment]
AFAIR the `tox` job runs these today

**Comment by stevekuznetsov** [comment]
See:

https://github.com/openshift/aos-cd-jobs/blob/14be97d62ee0d1e03a64fe93d6a8152344961829/sjb/config/test_cases/test_pull_request_openshift_ansible_tox.yml#L20-L33

**Comment by sosiouxme** [comment]
Yeah, I was confused thinking they ran during main tox. So I'll disable execution of those files too. Thanks.

**Comment by sosiouxme** [comment]
These don't affect anything but tox and travis tests. Since those are passing, going to just merge this.

**Pull request merged**
