### PR TITLE
Bug 1818961: [release-4.4] Use oc_csr_approve Ansible module for CSR approval

### PR DESCRIPTION
**Pull request by mtnbikenc**
Cherry picks #12129

Also includes these for Python unit tests:
Use Python3 for tests #12102
Refine Python version for tox in travis #12116

### CODE REVIEW

**Comment by mtnbikenc** [comment]
/hold
Many many e2e tests are failing each time.

**Comment by derekwaynecarr** [comment]
note on 4/9: will revisit once team removes the hold.

**Comment by mtnbikenc** [comment]
CI should be fixed with an updated runc package.
/hold cancel
/retest

**Pull request merged**
