### PR TITLE
Don't make config files world readable

### PR DESCRIPTION
**Pull request by sdodson**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1302513

### CODE REVIEW

**Comment by sdodson** [comment]
@abutcher PTAL

**Comment by sdodson** [comment]
aos-ci-test

**Comment by abutcher** [comment]
LGTM

**Comment by abutcher** [comment]
CI failing on this consistently
```
TASK: [openshift_common | Install the base package for versioning] ************ 
failed: [10.8.52.50] => {"changed": false, "failed": true, "rc": 0, "results": []}
msg: No Package matching 'atomic-openshift' found available, installed or updated
```

**Comment by brenton** [comment]
@arilivigni, it looks like the 3.0 jenkins run isn't setting `deployment-type: enterprise`.  That's how openshift-ansible knows to look for the package named `openshift` instead of `atomic-openshift` in 3.1 and later.

**Comment by arilivigni** [comment]
@brenton I had no idea additional changes are needed you told me the version of the product was all that mattered.  This complicates the setup I will have to look at a work around

**Comment by arilivigni** [comment]
@brenton FYI it is set to this -                 "deployment_type": "openshift-enterprise",

**Comment by brenton** [comment]
`deployment_type: openshift-enterprise` == 3.1, `deployment_type: enterprise` == 3.0

**Comment by arilivigni** [comment]
I am going to make a separate topology for 3.0 clusters and just have to update the yaml accordingly.
I also need to fix to make sure aos-ci-jenkins completes.  I think I am going to change that to unit-tests

**Comment by arilivigni** [comment]
aos-ci-test

**Comment by arilivigni** [comment]
aos-ci-test

**Comment by abutcher** [comment]
@brenton ^
@arilivigni thanks!

**Comment by arilivigni** [comment]
@brenton This seems to be working as expected I did some testing.  There is one minor issue that I put put for review with getting the logs on the unit tests

**Comment by arilivigni** [comment]
@abutcher ^^^ np :)

**Comment by sdodson** [comment]
Very nice, thanks.

**Comment by brenton** [comment]
:100:

**Pull request merged**
