### PR TITLE
Default to OSE 3.1 in interactive installer instead of 3.0.

### PR DESCRIPTION
**Pull request by dgoodwin**
Also includes commit to fix unit tests on developer systems where the openshift-ansible rpms are installed.

### CODE REVIEW

**Comment by detiber** [comment]
@dgoodwin while unrelated to this PR, mind fixing the pylint error that is getting flagged?
```
C:435, 0: Line too long (145/120) (line-too-long)
```

**Comment by dgoodwin** [comment]
Sure, all set now.

**Comment by detiber** [comment]
@dgoodwin thanks, nothing like a long comment to make pylint mad...

:+1: from me

**Comment by dgoodwin** [comment]
@brenton could we get a merge on this, Sam hit the test problem this fixes. Thanks!

**Pull request merged**
