### PR TITLE
Install boto3 from pip

### PR DESCRIPTION
**Pull request by sdodson**
Due to https://bugs.centos.org/view.php?id=15516 we can't use 
python2-boto3

### CODE REVIEW

**Comment by wking** [comment]
I had an additional commit cherry-picked in #10874.  Do we need that commit as well?  I'm waiting to see how the image builds go...

**Comment by vrutkovs** [comment]
We do need python-docker-py commit too. Most importantly we should disable e2e-gcp test - or maybe just force-merge

**Comment by wking** [comment]
> ... maybe just force-merge

I'm fine with force-merges to unstick CI, but I think we should wait to make sure we've actually fixed `prow/image` before merging :p

**Comment by sdodson** [comment]
I think merging is requisite for building a new image, no?

**Comment by sdodson** [comment]
Merging via the bot is what i meant.

**Pull request merged**
