### PR TITLE
[3.7] Registry remove legacy vars

### PR DESCRIPTION
**Pull request by legionus**
This is backport of https://github.com/openshift/openshift-ansible/pull/8020
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1570845

### CODE REVIEW

**Comment by bparees** [comment]
@sdodson is CI broken for 3.7?

**Comment by sdodson** [comment]
@bparees Yes unfortunately. If this looks good to you we'll merge it manually.

**Comment by legionus** [comment]
> did you have any specific concerns?

@bparees I'm worried that in this version I had to change the code because installer is too old and it is not tested. I could not test it locally.

**Comment by bparees** [comment]
> I could not test it locally.

what issue did you run into testing it locally?

**Comment by legionus** [comment]
> what issue did you run into testing it locally?

I can't find rpm packages for v3.7.

**Comment by bparees** [comment]
> I can't find rpm packages for v3.7.

@sdodson can someone from your team help @legionus get through a 3.7 install?

**Comment by wshearn** [comment]
Testing this out on a 3.7 cluster with this pr patched into the release-3.7 branch

`Monday 30 April 2018  13:06:38 -0400 (0:00:15.394)       0:01:43.738 **********
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IndexError: list assignment index out of range
fatal: [ded-int-aws-master-8f7f7]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_Ix1l1r/ansible_module_oc_env.py\", line 1945, in <module>\n    main()\n  File \"/tmp/ansible_Ix1l1r/ansible_module_oc_env.py\", line 1936, in main\n    results = OCEnv.run_ansible(module.params, module.check_mode)\n  File \"/tmp/ansible_Ix1l1r/ansible_module_oc_env.py\", line 1874, in run_ansible\n    api_rval = ocenv.delete()\n  File \"/tmp/ansible_Ix1l1r/ansible_module_oc_env.py\", line 1829, in delete\n    if self.resource.delete_env_var(self.env_vars.keys()):\n  File \"/tmp/ansible_Ix1l1r/ansible_module_oc_env.py\", line 1556, in delete_env_var\n    del env_vars_array[idx]\nIndexError: list assignment index out of range\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}`

**Comment by legionus** [comment]
@wshearn this is a bug in the `oc_env.py`

```
del env_vars_array[idx]
IndexError: list assignment index out of range
```

We are trying to delete an item by index only if we found it in an array, but `idx` is out of loops and so if we have several `keys`, then the next value will not be taken as the next iteration.

```python
    def delete_env_var(self, keys):
        '''delete a list of keys '''
        if not isinstance(keys, list):
            keys = [keys]

        env_vars_array = self.get_env_vars()
        modified = False
        idx = None
        for key in keys:
            for env_idx, env_var in enumerate(env_vars_array):
                if env_var['name'] == key:
                    idx = env_idx
                    break

            if idx:
                modified = True
                del env_vars_array[idx]

        if modified:
            return True

        return False
```

The correct code should look like this:

```diff
diff --git a/roles/lib_openshift/library/oc_env.py b/roles/lib_openshift/library/oc_env.py
index f334ddaa4..24b31e585 100644
--- a/roles/lib_openshift/library/oc_env.py
+++ b/roles/lib_openshift/library/oc_env.py
@@ -1543,8 +1543,8 @@ spec:
 
         env_vars_array = self.get_env_vars()
         modified = False
-        idx = None
         for key in keys:
+            idx = None
             for env_idx, env_var in enumerate(env_vars_array):
                 if env_var['name'] == key:
                     idx = env_idx
```

@bparees @sdodson @vrutkovs @wshearn Should I add such fix in my PR or I should open new one ?

**Comment by vrutkovs** [comment]
@legionus this PR is fine

**Comment by legionus** [comment]
@wshearn can you check it once again ?

**Comment by bparees** [comment]
@sdodson @wshearn can you take another look?

**Comment by vrutkovs** [comment]
3.7 build should now be fixed

/retest

**Comment by legionus** [comment]
```
FAILURE after 600.199s: test/cluster/functionality.sh:80: executing 'curl_es 'logging-es-data-master-1qu7xl8l-1-kf6mm' '/_cat/indices?h=index'' expecting any result and text '^(project|\.operations)\.'; re-trying every 0.2s until completion or 600.000s: the command timed out
```
I want to believe that this is a flake ))
/retest

**Comment by sdodson** [comment]
Ran through this on my test environment.
```
  1. Hosts:    ose3-master.example.com
     Play:     Clean up registry environment variables and check service account permissions
     Task:     create registry serviceaccount
     Message:  The task includes an option with an undefined variable. The error was: 'openshift_hosted_registry_namespace' is undefined
               
               The error appears to have been in '/home/rdu/sdodson/git/openshift-ansible/roles/openshift_hosted/tasks/registry_service_account.yml': line 2, column 3, but may
               be elsewhere in the file depending on the exact syntax problem.
               
               The offending line appears to be:
               
               ---
               - name: create registry serviceaccount
                 ^ here
               
               exception type: <class 'ansible.errors.AnsibleUndefinedVariable'>
               exception: 'openshift_hosted_registry_namespace' is undefined
```
I think we need to move openshift_hosted_registry_namespace. This variable is set in the main tasks so when we skip those we're not getting them. I think that we should move all these variables into roles/openshift_hosted/defaults.main.yml https://github.com/legionus/openshift-ansible/blob/0ccfbda01e070454016c559c25a4999de65c2781/roles/openshift_hosted/tasks/registry.yml#L45-L51

**Comment by sdodson** [comment]
I'm testing that suggestion locally, I'll confirm once I know if it fixes things.

**Comment by bparees** [comment]
@sdodson needs a /approve?

**Comment by sdodson** [comment]
Failures are known problems with this branch or flames, merging.

**Pull request merged**
