### PR TITLE
added the tito and copr_cli roles

### PR DESCRIPTION
**Pull request by twiest**

### CODE REVIEW

**Comment by joelddiaz** [comment]
:+1:

**Comment by detiber** [comment]
These roles almost seem a bit overkill here...  Is the plan to extend them beyond just installing a single package each?  Or would it make more sense to have a single role that comprised the development tools needed, including tito and copr_cli?

**Comment by twiest** [comment]
From an operations perspective, we need to precisely control what is installed on our hosts. To that end, we try to create very modular / cohesive roles.

Our general philosophy is:
* Create roles specific to a single technology
* Name roles based on the rpm(s) they manage (if possible / practical)
* Have roles be as cohesive as practical ("do one thing and do it well", or in this case, "manage one technology, and manage it well").
* Have a single role manage that technology (don't have 2 or 3 roles that manage the same technology / rpm). That gets very confusing if you're trying to add something to the role that manages tito, but you now have N roles that manage it. Do you add it to all of them, or just some of them? What if you mess up and miss one?

This sometimes leads to very small roles like the two here, but it gives us the advantages of:
* A host can have just tito installed, or just copr-cli installed, or both. If we combine them into a single role, every host has to have both or none.
* It's very easy to see which role manages tito.
* It's very easy to see the boundaries of that role (tito, and only tito, anything else goes in a different role). This makes it easy for people to know where to put stuff, and discourages them from growing a role beyond what it should be.
* These two roles can grow independently, as makes sense.


If I were to combine these two roles into a "development_tools" role, as suggested, what's to stop someone from coming along and adding make, gcc, etc to it?

Then we'd have many RPMs installed on our hosts that we really don't want installed. This is a management and security problem.

So, yes, sometimes we have small roles like these, but that is a very small downside IMO compared to the alternatives.

**Comment by detiber** [comment]
@twiest I definitely see where you are coming from.

Concerns I see:
1. increasing the number of roles we add to openshift-ansible that do not actually support deploying and running openshift.
  - Is this something that would make more sense in an ops specific public/private repo?
  - I just don't see a lot of use for this for origin/enterprise users of openshift-ansible
2. installation without configuration of a package just seems overkill for a role to me.
  - Maybe we could limit these to included tasks files until there is something beyond just package installation that would necessitate a role?

**Comment by twiest** [comment]
@detiber you seem to have a different impression of the purpose of this repo than I do. Maybe we should get together and talk about this in person. Ping me the next time you're in the tower.

**Pull request merged**
