### PR TITLE
BUG 1753890: Fixing NSX role templates to refer correct variable for clusterip

### PR DESCRIPTION
**Pull request by ravitri**
Changing role/nsx template variables to point to correct variable to resolve clusterip.

### CODE REVIEW

**Comment by ravitri** [comment]
Wrongly raised PR.. Will raise new PR

**Comment by ravitri** [comment]
@jstuever @jcpowermac - Can you please review and approve the change?

**Comment by jstuever** [comment]
Looks like you need to rebase before we can land this.

**Comment by ravitri** [comment]
@jstuever - Just to confirm. Actually initially I missed changing the base branch to openshift:release-3.11 so the PR was raised against master branch. This added the "needs-rebase" label to PR. I changed the base branch to "release-3.11" and other labels got changed except for "needs-rebase". Am not sure why. Is this the reason you requested for rebase (label)? 

Let me know if rebase is required as such. 

Besides, I deleted my local branch thinking that 'needs-rebase' label might have been a glitch. Maybe I shouldn't have done that. If I create new local branch, the github branch would get modified and the PR would close I think. Am I correct? Any other way I can rebase if required?

**Pull request merged**
