### PR TITLE
Add support for static pods to etcd helpers

### PR DESCRIPTION
**Pull request by sdodson**
Backports #9385

### CODE REVIEW

**Comment by michaelgugino** [comment]
No cherry-pick -x?

**Comment by sdodson** [comment]
It didn't pick cleanly.

**Comment by sdodson** [comment]
@kalexand-rh I've lost track of where we'd discussed the missing helper scripts in 3.10 but this resolves it and should be in the next errata.

**Comment by kalexand-rh** [comment]
@ahardin-rh, @tmorriso-rh, will you please add this fix to the next batch of errata?

**Comment by sdodson** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1610166 was the bug that I was thinking of.

**Pull request merged**
