### PR TITLE
Fix RPM Package Version in case of Missing declaration

### PR DESCRIPTION
**Pull request by gianpieropavesi1A**
I need this fix otherwise is impossible to create a cluster. Do you have any idea to make it in another way?

2017-03-28 15:09:19,884 p=20697 u=gpavesi |  TASK [openshift_common : Install the base package for versioning] **************
2017-03-28 15:09:19,884 p=20697 u=gpavesi |  task path: /home/gpavesi/src/openshift-ansible/roles/openshift_common/tasks/main.yml:44
2017-03-28 15:09:19,923 p=20697 u=gpavesi |  Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/packaging/os/yum.py
2017-03-28 15:09:20,371 p=20697 u=gpavesi |  fatal: [gianp5-master-0]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "conf_file": null, 
            "disable_gpg_check": false, 
            "disablerepo": null, 
            "enablerepo": null, 
            "exclude": null, 
            "install_repoquery": true, 
            "list": null, 
            "name": [
                "atomic-openshift-"
            ], 
            "state": "present", 
            "update_cache": false, 
            "validate_certs": true
        }
    }, 
    "rc": 126, 
    "results": [
        "No package matching 'atomic-openshift-' found available, installed or updated"
    ]
}

MSG:

No package matching 'atomic-openshift-' found available, installed or updated

### CODE REVIEW

**Comment by sdodson** [comment]
bot, test pull request once

**Comment by sdodson** [comment]
aos-ci-test

**Comment by gianpieropavesi1A** [comment]
Please can someone take a look of it? Very thanks in advance!

**Comment by gianpieropavesi1A** [comment]
@sdodson @gnufied @ncdc @brenton  Please, can someone take a look, thanks!!!!!

**Comment by sdodson** [comment]
@gianpieropavesi1A can you share your inventory? I'm curious which openshift_image_tag openshift_pkg_version openshift_release, etc variables are set.

**Comment by gianpieropavesi1A** [comment]
@sdodson we don't set those variables. Why are there mandatory? The purpose of the fix is to update the packages at the latest update even if those variables are not set.

**Comment by sdodson** [comment]
@gianpieropavesi1A they're not, i'm trying to understand the scenario where you'd need this change though so having your inventory variables would help.

**Comment by gianpieropavesi1A** [comment]
@sdodson As you can see we don't set any vars related to version, we are used to install the latest version present in the channels configured inside the server based on a rhel7.3. Actually, without my fix we are  not able to do that, seems we need to fix version but we don't want to fix version, we want the installer grab the latest one from configured repo, this is how we do openshift upgrades, thanks!

[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=ansible

# If ansible_ssh_user is not root, ansible_sudo must be set to true
ansible_sudo=true

# To deploy origin, change deployment_type to origin
deployment_type=openshift-enterprise

# Additionally included repositories on the nodes
openshift_additional_repos=[]

# additionally set properties
ansible_become="true"
cli_docker_additional_registries="xxxx"
cli_docker_log_driver="json-file"
cli_docker_log_options="max-size=50m,max-file=9"
cli_openshift_hosted_metrics_deploy="False"
cli_openshift_master_default_subdomain=""
debug_level="5"
openshfit_hosted_metrics_additional_heapster_sinks=""
openshift_hosted_metrics_deployer_prefix="openshift3/"
openshift_hosted_metrics_public_url="https://hawkular-metrics./hawkular/metrics"
openshift_hosted_registry_selector="type=infra"
openshift_hosted_router_selector="type=infra"
openshift_master_cluster_method="native"
openshift_no_proxy=.cluster.local,.node.xxx,openshift-master-xxx
openshift_generate_no_proxy_hosts="False"
openshift_master_cluster_method=native
openshift_master_cluster_hostname=openshift-master-xxx

**Comment by sdodson** [comment]
[merge]

**Comment by gianpieropavesi1A** [comment]
very thanks @sdodson but I see the FAILURE because of [98fc572](https://github.com/openshift/openshift-ansible/commit/98fc57273d4c7c8bf1aeb7c81da983aa8f316dd9)

**Comment by gianpieropavesi1A** [comment]
I decline it

**Pull request closed without merging**
