### PR TITLE
Replace deprecated sudo with become.

### PR DESCRIPTION
**Pull request by abutcher**
@detiber PTAL

### CODE REVIEW

**Comment by abutcher** [comment]
aos-ci-test

**Comment by detiber** [comment]
@abutcher I'm a little torn on using true/false in the playbooks here. Ansible docs generally use yes/no. 

That said, I think using true/false in the inventory makes more sense to more users.

**Comment by abutcher** [comment]
aos-ci-test

**Comment by abutcher** [comment]
@detiber Updated for `yes`/`no`

**Pull request merged**
