### PR TITLE
docker_image_availability: encode error message

### PR DESCRIPTION
**Pull request by vrutkovs**
Encode error message when checking for docker image availability
to ensure this works with ansible-playbook and ansible-playbook-3

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1544648

Signed-off-by: Vadim Rutkovsky <vrutkovs@redhat.com>

### CODE REVIEW

**Comment by vrutkovs** [comment]
Flakes

/retest

**Comment by vrutkovs** [comment]
Flake

/test gcp

**Comment by vrutkovs** [comment]
>This code looks correct to me, though it's not the cause of the original bug.

>Looks like someone copy and pasted the left-pointing single quote '’' (0x2019), which didn't properly >terminate the first single quote in their variable.

I think ansible was smart enough to wrap it in double quotes - and then passed it with the single quote to skopeo and tried to print the error message - and failed to do so in py2. Running this with `ansible-playbook-3` showed correct error message.

This change would show the error message in both py2 and py3 versions of ansible-playbook. It also doesn't seem to be dependent on `ansible_python_interpreter`

**Comment by michaelgugino** [comment]
> I think ansible was smart enough to wrap it in double quotes - and then passed it with the single quote to skopeo and tried to print the error message

The underlying cause of the failure was a malformed string which included an un-closed single quote.  This single quote (ascii single quote) looks like it was terminated by a unicode left-pointing single quote (or upside-down single quote, not sure of what you would call this character), 0x2019.

In essence:
```yaml
var1: (single_quote)Some string(0x2019)
```
This resulted in an un-terminated single-quote, so ansible/python assumed that the first single quote character was just part of the string.  This happens frequently when trying to copy/paste from word document software or email clients.  Those applications try to prettify the quotes, and it breaks other applications when things are copied to and from.

The user probably meant to put:
```yaml
var1: (single_quote)Some string(single_quote)
```

**Pull request merged**
