### PR TITLE
Fix compatibility with ansible-core 2.13

### PR DESCRIPTION
**Pull request by yselkowitz**
Based on C8S, RHEL 8.7 will get a version bump of ansible-core.

/cc @barbacbd

### CODE REVIEW

**Review by barbacbd — COMMENTED** [review]
This looks good to me but I want to wait to see the results of https://github.com/openshift/release/pull/32849. this could help solve some of the issues (I hope).

**Comment by yselkowitz** [comment]
The workers-rhel8 periodic job is currently failing with the same error, so it seems this doesn't perform any miracles in that regard, and it's not clear to me what is the root cause.  However, this does fix the following messages from the logs:
```
[DEPRECATION WARNING]: [defaults]callback_whitelist option, normalizing names 
to new standard, use callbacks_enabled instead. This feature will be removed 
from ansible-core in version 2.15. Deprecation warnings can be disabled by 
setting deprecation_warnings=False in ansible.cfg.
```
```
redirecting (type: callback) ansible.builtin.profile_tasks to ansible.posix.profile_tasks
[WARNING]: Skipping callback plugin 'profile_tasks', unable to load
```
There had also been an error wrt `/usr/bin/env python` vs `/usr/bin/python`, but I don't see that anymore, perhaps it was fixed in one of the 2.13.z point releases that have since landed in C8S.

**Comment by barbacbd** [comment]
/retitle OCPBUGS-3338: Fix compatibility with ansible-core 2.13

**Pull request merged**
