### PR TITLE
Updating to latest gce.py inventory module from ansible

### PR DESCRIPTION
**Pull request by kwoodson**

### CODE REVIEW

**Comment by kwoodson** [comment]
@menren,

I'd like to update the gce.py inventory library to the latest.  Would you mind testing this and verifying it works for you?

**Comment by menren** [comment]
I did a first test and I have the following error.
```
  bin/cluster create gce -i 0 -n 2  github
Traceback (most recent call last):
  File "/bin/ansible-playbook", line 324, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/bin/ansible-playbook", line 157, in main
    inventory = ansible.inventory.Inventory(options.inventory, vault_password=vault_pass)
  File "/usr/lib/python2.7/site-packages/ansible/inventory/__init__.py", line 100, in __init__
    self.parser = InventoryDirectory(filename=host_list)
  File "/usr/lib/python2.7/site-packages/ansible/inventory/dir.py", line 58, in __init__
    parser = InventoryParser(filename=fullpath)
  File "/usr/lib/python2.7/site-packages/ansible/inventory/ini.py", line 43, in __init__
    self._parse()
  File "/usr/lib/python2.7/site-packages/ansible/inventory/ini.py", line 47, in _parse
    self._parse_base_groups()
  File "/usr/lib/python2.7/site-packages/ansible/inventory/ini.py", line 108, in _parse_base_groups
    tokens = shlex.split(line)
  File "/usr/lib64/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/usr/lib64/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib64/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib64/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation
ACTION [create] failed: Command 'ansible-playbook  -i inventory/gce/hosts -e 'num_masters=1 num_nodes=2 cluster_id=github num_etcd=0 num_infra=0 deployment_type=origin' playbooks/gce/openshift-cluster/launch.yml' returned non-zero exit status 1
```

I am using ansible 1.9.2.

Could you investigate ?

**Comment by kwoodson** [comment]
@menren,

The gce.py needed to be executable.  I have added that.  Please re-test.

**Comment by menren** [comment]
The deployment seems to be OK for me.

However now there is a default pod deployed : 
`router-1-deploy                          0/1       Pending            0          52m`
This is not related to this PR.
Anyways I will do some more functional tests

**Comment by kwoodson** [comment]
@menren,

:+1:  when you are ready and I'll merge.

**Comment by kwoodson** [comment]
@menren,

Any update on this?

**Comment by menren** [comment]
My tests and investigation took some times, the cluster deployed with this branch is not fully working, I suspect it's because of new version of kubernetes ...

:+1: for this PR

**Pull request merged**
