### PR TITLE
Condensing multiple task `when` into a single one

### PR DESCRIPTION
**Pull request by ewolinetz**
Addresses https://github.com/openshift/openshift-ansible/pull/4154#issuecomment-301164654

### CODE REVIEW

**Comment by abutcher** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
[merge]

**Comment by stevekuznetsov** [comment]
@ewolinetz you'll need to label this PR as a blocker-bug to merge into that branch:

```
+ approve.sh openshift-ansible release-1.4 none
[ERROR] Only blocker bugs are allowed to merge during stage-cut.
```

**Comment by sdodson** [comment]
@stevekuznetsov could the error instruct people as to the remedy?

**Comment by sdodson** [comment]
[merge][severity: blocker]

**Comment by stevekuznetsov** [comment]
> @stevekuznetsov could the error instruct people as to the remedy?

Not really sure that is appropriate -- you should label this as a blocker because it _is_, not because you want it to merge.

**Comment by sdodson** [comment]
@stevekuznetsov fair enough

**Pull request merged**
