### PR TITLE
sync examples

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@sdodson sorry, this should not be changing 3.9, it should be for v3.10. I guess the sync script needs to be updated?

**Comment by sdodson** [comment]
> @sdodson sorry, this should not be changing 3.9, it should be for v3.10. I guess the sync script needs to be updated?

Yeah, we need to update the sync script.

**Comment by bparees** [comment]
@sdodson i reran the sync w/ the v3.10 arg, ptal.

I also deleted your cherry pick command.

**Comment by vrutkovs** [comment]
flakes

/retest

**Comment by vrutkovs** [comment]
Flakes

/retest

**Comment by vrutkovs** [comment]
Flakes

/retest

**Comment by bparees** [comment]
@sdodson yeah looks like they were, or rather they exposed a weakness in one of our tests.  Fixing the test here: https://github.com/openshift/origin/pull/19507

**Comment by bparees** [comment]
@vrutkovs @sdodson ok it looks like this should be good to go now

**Pull request merged**
