### PR TITLE
[release-3.6] openshift_checks/docker_storage: overlay/2 support

### PR DESCRIPTION
**Pull request by sosiouxme**
fix https://bugzilla.redhat.com/show_bug.cgi?id=1469197

When Docker is configured with the `overlay` or `overlay2` storage driver, check that it is supported and usage is below threshold.

Also, document and fix `openshift_docker_selinux_enabled` option so that running the check need not result in the docker role reconfiguring and restarting docker with `--selinux-enabled` (which will prevent docker from running with these drivers at all).

### CODE REVIEW

**Comment by sosiouxme** [comment]
aos-ci-test

**Comment by sosiouxme** [comment]
[merge]

**Comment by sosiouxme** [comment]
should have been severity blocker anyway, but:
`[ERROR] No approval criteria are configured for 'release-3.6' branch of 'openshift-ansible' repo.`
Guessing we need that fixed to use the bot for this... @stevekuznetsov ? @sdodson?

**Comment by sdodson** [comment]
https://github.com/openshift/aos-cd-jobs/pull/443 to update the bot

**Comment by sdodson** [comment]
[merge][severity:blocker]

**Comment by sdodson** [comment]
if that fails we'll just merge manually

**Comment by sosiouxme** [comment]
@sdodson Still `No approval criteria are configured for 'release-3.6' branch`

**Comment by sdodson** [comment]
checking with CD team on whether or not something needs to be done to update the jobs

**Pull request merged**
