### PR TITLE
Add any_errors_fatal to openstack playbooks

### PR DESCRIPTION
**Pull request by tzumainn**

### CODE REVIEW

**Comment by tomassedovic** [comment]
Awesome, thanks! This is not necessary for the `localhost` jobs, only for the multihost plays, but there's no harm in leaving it there.

Anyway, it works great! Needs a rebase but we can merge it afterwards. Note that some of the plays have now moved under install and they still require any_errors_fatal, too.

**Comment by tomassedovic** [comment]
So sadly, when I tested this, it didn't seem to work. But there's apparently a few ansible bugs about that, so I'm okay to merge this.

For the record, here's how I'm testing this. I've added the following to the provision playbook, right after the `Populate DNS entries` task:

```yaml
  - os_server:
      name: app-node-0.openshift.example.com
      state: absent
```

It will delete an app server (the name is hardcoded so if your env is different, change this). The play should abort during the `TASK [Detecting Operating System from ostree_booted]`. In my testing, it continued way after that just skipping tasks related to the app node.

Apparently though, it's possible to enable this option globally in `ansible.cfg` as well:

`any_errors_fatal = True`

And that seem so be working fine. Would you mind adding that to the readme? Something along the lines of "It is recommended that you put `any_errors_fatal = True` which will abort the Ansible execution as soon as any error is encountered."

**Comment by tzumainn** [comment]
I actually was going to just document the ansible.cfg change and leave it at that, but when I was testing - I did so by removing a nova server after the heat stack was created - the ansible.cfg change did nothing, while my changes worked.

any_errors_fatal only seems to work on the specific tasks I threw it on, so perhaps the reason your test didn't work is because you were expecting it to fail in the playbooks/init/basic_facts.yml playbook?

**Comment by tomassedovic** [comment]
Interesting. Maybe our Ansible versions are different. The changes in this PR did nothing at all to me -- as if they weren't there. While the ansible.cfg version worked perfectly.

So let's do both.

**Comment by tzumainn** [comment]
Fair enough! Out of curiosity, what's your ansible version?

**Comment by tomassedovic** [comment]
@tzumainn: `ansible 2.4.1.0`

**Comment by tzumainn** [comment]
@tomassedovic I'm using 2.4.2.0. Now I'm really confused...

**Comment by tomassedovic** [comment]
Hm, so I updated to 2.4.2.0 but I keep seeing the same thing: ansible.cfg stops the play right after the failure, whereas without it, this patch keeps going for ages afterwards.

**Comment by tzumainn** [comment]
@tomassedovic Okay, I've added a note to the README. I guess one of the billion options here will work, although it might be a different one for each person.

**Pull request merged**
