### PR TITLE
Updating Kibana-proxy secret key name, fixing deleting secrets, fixed…

### PR DESCRIPTION
**Pull request by ewolinetz**
… extra ES dc creation

### CODE REVIEW

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
[test_logging]

**Comment by ewolinetz** [comment]
[test]

**Comment by ewolinetz** [comment]
[merge][severity: bug]

**Comment by ewolinetz** [comment]
[merge][severity: blocker]

**Comment by ewolinetz** [comment]
@sdodson can you work your magic on this?

**Comment by ewolinetz** [comment]
[merge][severity: blocker]

**Comment by sdodson** [comment]
[merge]

**Comment by ewolinetz** [comment]
@stevekuznetsov any idea why the merge job is failing on this? its non-obvious to me...

**Comment by sdodson** [comment]
This is a bug in the bot, fixing (by deleting previous merge comments).

**Comment by sdodson** [comment]
[merge]

**Comment by stevekuznetsov** [comment]
[test_logging]

**Pull request merged**
