### PR TITLE
Bug 1247461 - Fixing github triggers for the xpaas templates

### PR DESCRIPTION
**Pull request by brenton**

### CODE REVIEW

**Comment by brenton** [comment]
@sdodson, @bparees, mind taking a look?

**Comment by bparees** [comment]
GitHub is the preferred format now. sorry :(

**Comment by bparees** [comment]
(I should have been clearer in my bugzilla update)

**Comment by brenton** [comment]
No prob.  I'll update it!

**Comment by sdodson** [comment]
@brenton What's that second commit 'Merging in latest fixes from OSE' ?

**Comment by brenton** [comment]
@bparees, mind checking now?

**Comment by bparees** [comment]
lgtm

**Comment by brenton** [comment]
@sdodson, well, since I had assumed these had been tested I pushed them live yesterday with updates that QE had verified.  I want to push this out now and not pull in the latest from master from Ops that QE hasn't verified for OSE.  So I tagged my commit v3.0.0-8 that has v3.0.0-7 as it's parent and then merged in the latest from master.

**Pull request merged**
