### PR TITLE
Revert "Revert ansible-2.4 work on release-3.6 branch"

### PR DESCRIPTION
**Pull request by sdodson**
Reverts openshift/openshift-ansible#4987

We're merge this once we're clear of 3.6 GA

### CODE REVIEW

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Comment by mtnbikenc** [comment]
:cry: 
```
No package atomic-openshift-utils-3.6.173.0.6-1.git.0.e9c8501.el7 available.
Error: Nothing to do
```

**Comment by sdodson** [comment]
[merge]

**Comment by sdodson** [comment]
That's my fault. I messed up some specfile changes on Friday, should be fixed now.

**Pull request merged**
