### PR TITLE
Add CentOS ansible 2.6-versioned repo to the Dockerfile

### PR DESCRIPTION
**Pull request by vrutkovs**
Use ansible versioned repo

### CODE REVIEW

**Comment by vrutkovs** [comment]
Seems azure test is failing the merge - https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/10406/test_pull_request_openshift_ansible_extended_conformance_azure/2718/
/retest

**Comment by jim-minter** [comment]
discussed with @vrutkovs via IRC - don't believe that azure tests are blocking here

**Pull request merged**
