### PR TITLE
a-o-i: More flexible upgrade mappings

### PR DESCRIPTION
**Pull request by smunilla**
Change the upgrade logic to allow for more than two types of upgrades.

### CODE REVIEW

**Comment by smunilla** [comment]
@brenton I was thinking something like this?

**Comment by brenton** [comment]
Is that all that is needed to call the correct playbook?  The new playbook will be `playbooks/byo/openshift-cluster/upgrades/v3_1_to_v3_2/upgrade.yml`.

**Comment by smunilla** [comment]
@brenton Yes. In a rare bit of foresight, I wrote the original code with exactly this in mind :)

**Comment by smunilla** [comment]
Superseded by PR1536

**Pull request closed without merging**
