### PR TITLE
Default storage for glusterfs installation

### PR DESCRIPTION
**Pull request by jkaurredhat**
Fixes Bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1529048

Signed-off-by: jkaurredhat <jkaur@redhat.com>

### CODE REVIEW

**Comment by jkaurredhat** [comment]
Cc @jarrpa

**Comment by jarrpa** [comment]
@jkaurredhat This is not acceptable. If this is to be considered, it should be configurable and default to false.

**Comment by sdodson** [comment]
Lets get this updated per @jarrpa comment. We should also look to ensure that OCP documentation clarifies supported configuration based on subscriptions utilized.

**Comment by davidaah** [comment]
@sdodson @jarrpa until a product decision is made would you be comfortable at least pushing through a patch to get this in as an "optional" flag with default disabled?

i've found my 3.7 deploy is broken in the same manner until i apply the default condition and then kill the pods that were stuck in creating or crashloopbackoff

**Comment by davidaah** [comment]
note: this also is breaking prometheus deployment as well

**Comment by jarrpa** [comment]
@davidaah Yes, that is what we're asking for. :)

**Comment by davidaah** [comment]
awesome thanks @jarrpa , manually recreating PVCs and destroying pods has not been fun :)... i will keep an eye out for an updated PR but would be happy to submit one as well if needed to get something in to master

**Comment by vrutkovs** [comment]
Closing due to no recent activity. Please open a new PR if this change is still needed.
/close

**Pull request closed without merging**
