### PR TITLE
Remove NoVolumeNodeConflict from 3.9+

### PR DESCRIPTION
**Pull request by sdodson**

### CODE REVIEW

**Comment by aveshagarwal** [comment]
@sdodson lgtm except as we discussed or IRC that `CheckVolumeBinding` is missing.

**Comment by sdodson** [comment]
@michaelgugino should we get rid of roles/openshift_master_facts/lookup_plugins/openshift_master_facts_default_predicates.py at this point? Seems wholely duplicated from roles/lib_utils/lookup_plugins/openshift_master_facts_default_predicates.py ?

**Comment by michaelgugino** [comment]
@sdodson that sounds fine to me.  I might have missed that one when I was doing the refactoring.

I left the addon (logging, metrics) roles' plugins somewhat intact to try to keep those somewhat portable.  If it's part of core openshift, it should most likely be in lib_utils.

**Comment by sdodson** [comment]
@aveshagarwal added CheckVolumeBinding
/retest

**Comment by aveshagarwal** [comment]
@sdodson thanks. lgtm for predicates. Not sure I can provide lgtm here as I have not reviewed other changes.

**Comment by michaelgugino** [comment]
bot, retest this please

**Pull request merged**
