### PR TITLE
Update aoi manpage with correct operation count

### PR DESCRIPTION
**Pull request by tbielawa**
Update aoi manpage with correct operation count

### CODE REVIEW

**Comment by tbielawa** [comment]
aos-ci-test

**Comment by tbielawa** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by tbielawa** [comment]
aos-ci-test

**Comment by tbielawa** [comment]
aos-ci-test

**Comment by tbielawa** [comment]
aos-ci-test

**Comment by tbielawa** [comment]
aos-ci-test

**Pull request merged**
