### PR TITLE
[release-3.11] Refactor openshift_examples to support multi-arch deployments

### PR DESCRIPTION
**Pull request by jeffdyoung**
@sdodson In addition to fixing bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1660955
ppc64le will now install the proper imagestreams and templates by default. 

To do this, I had to refactor things a bit (hope thats ok?):

- broke out logic from roles/openshift_examples/tasks/main.yml to import these playbooks (depending on arch): create_example_tar.yml, ppc64le_examples.yml, x86_64_examples.yml and stream_secrets.yml. More refactoring could be done, but this seemed like a good first pass. I also did this so that other archs would not install examples by default.

- moved x86_64 imagestreams/templates from roles/openshift_examples/files/latest to roles/openshift_examples/x86_64 so the create_example_tar.yml can automatically build openshift_example.tar based on arch. (no additional arch check)

- Separated dotnet imagestream from centos/rhel_image_stream variables and gave them their own variables (since these will only be x86) for centos and rhel:
```
centos_image_streams:
  - "{{ image_streams_base }}/image-streams-centos7.json"
  - "{{ image_streams_base }}/dotnet_imagestreams_centos.json"
rhel_image_streams:
  - "{{ image_streams_base }}/image-streams-rhel7.json"
  - "{{ image_streams_base }}/dotnet_imagestreams.json"
```

To:
```
centos_image_streams: "{{ image_streams_base }}/image-streams-centos7.json"
centos_dotnet_streams: "{{ image_streams_base }}/dotnet_imagestreams_centos.json"
rhel_image_streams: "{{ image_streams_base }}/image-streams-rhel7.json"
rhel_dotnet_streams: "{{ image_streams_base }}/dotnet_imagestreams.json"
```

I've tested okd (x86), ocp (x86/power) installs on baremetal, and 3.10->3.11 power upgrade and it seems to behave as expected.

PTAL and let me know if you think more changes are needed. 
Thanks

### CODE REVIEW

**Comment by jeffdyoung** [comment]
@vrutkovs retest?
@sdodson you ok with this?

**Comment by jeffdyoung** [comment]
@vrutkovs can you approve with @sdodson out? We were hoping to get this into the next z-stream.

**Comment by sdodson** [comment]
/lgtm

Nice cleanup!

**Pull request merged**
