### PR TITLE
[WIP] Remove critical pod annotations and move to priority classes.

### PR DESCRIPTION
**Pull request by aveshagarwal**
Please feel free to provide feedback, but **do not merge** yet as I am going to do some testing to make sure it works as expected.

@sjenning @derekwaynecarr @ravisantoshgudimetla

### CODE REVIEW

**Comment by aveshagarwal** [comment]
@sdodson @michaelgugino any idea why travis-ci is failing for python 2.7 but passing for python 3+?

**Comment by michaelgugino** [comment]
@aveshagarwal I'm not sure wh travis didn't complete.  /retest only works for the prow jobs, travis is not trigger the same way.

**Comment by aveshagarwal** [comment]
> @aveshagarwal I'm not sure wh travis didn't complete. /retest only works for the prow jobs, travis is not trigger the same way.

thanks @michaelgugino

**Comment by aveshagarwal** [comment]
putting WIP again so that it does not get merged in 3.11 as this PR is for future.

**Comment by vrutkovs** [comment]
Master branch is closed! A major refactor is ongoing in devel-40. Changes for 3.x should be made directly to the latest release branch they're relevant to and backported from there.

**Pull request closed without merging**
