### PR TITLE
Updating tsb image names

### PR DESCRIPTION
**Pull request by ewolinetz**
Corresponding openshift-ansible update for ~~https://github.com/openshift/origin/pull/16800~~  https://github.com/openshift/origin/pull/17338

### CODE REVIEW

**Comment by ewolinetz** [comment]
/hold
until the new images are ready

**Comment by ewolinetz** [comment]
I don't think that image is available yet to be pulled down, hence tests failing

**Comment by ewolinetz** [comment]
origin image is there now
/retest

**Comment by ewolinetz** [comment]
Currently seeing 
```
msg="Handler for GET /v1.24/images/ansibleplaybookbundle/ansible-service-broker:latest/json returned error: No such image: ansibleplaybookbundle/ansible-service-broker:latest"
```

**Comment by wzheng1** [comment]
Is this pr ready to be merged?

**Comment by sdodson** [comment]
@ewolinetz don't you also need to switch to the new entry point importing the new apiserver-template.yaml ?

**Comment by ewolinetz** [comment]
@sdodson I shoudn't need to, should I? I'd imagine that'd be covered by another PR...

**Comment by ewolinetz** [comment]
@sdodson added missing logic and tests are passing now...

**Comment by ewolinetz** [comment]
logging failure is independent of this PR
/test extended_conformance_install_crio

**Comment by sdodson** [comment]
e2e flakes for everyone!

**Pull request merged**
