### PR TITLE
[3.7] GlusterFS - Invoke oc binary with the admin.kubeconfig token rather than default token from /Users/$HOME/.kube/config

### PR DESCRIPTION
**Pull request by DanyC97**

### CODE REVIEW

**Comment by DanyC97** [comment]
@jarrpa @michaelgugino fyi

**Comment by jarrpa** [comment]
Looks good, putting it on hold until QA for 3.9 is done.

/hold

**Comment by mjudeikis** [comment]
@DanyC97 was this one merged to master already? (sorry, I might missed it when collecting all PRs to backport to 3.7)

**Comment by DanyC97** [comment]
@mjudeikis i was a good citizen and created https://github.com/openshift/openshift-ansible/pull/7205 too but it has not merged yet. Maybe you can merge it ?

**Comment by DanyC97** [comment]
@jarrpa fyi in case you missed this one (know you been very busy ;) )

**Comment by jarrpa** [comment]
Missed, no. Lose track of, maybe. ;) Still, I would like to see the version going into master to be backported as part of #7470. Maybe see if you can work with @mjudeikis to get it in. Note that I would prefer you do this using `git cherry-pick -x` from the master commit onto his backport branch.

**Comment by DanyC97** [comment]
ah great then we can close this PR? wasn't aware which method you prefer: cherry-pick or both. Now i know ;)  

@mjudeikis you need help with back porting from master into you big PR ? let me know.

**Comment by jarrpa** [comment]
Yeah, I'll close this one.

**Pull request closed without merging**
