### PR TITLE
crio: use systemd manager

### PR DESCRIPTION
**Pull request by giuseppe**
fix a regression introduced last week.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
we have no tests for CRI-O here so it makes no sense to wait for the CI.

@sdodson could we quickly merge this so that we can kick another test on the CI for CRI-O?

**Comment by runcom** [comment]
> we have no tests for CRI-O here so it makes no sense to wait for the CI.

we would love to have CRI-O specific tests also /cc @mrunalp

**Comment by mrunalp** [comment]
Yeah, we should have some tests for cri-o here otherwise we will always have this issue of having to merge changes without  knowing the impact.

**Pull request merged**
