### PR TITLE
Ae ansible merge service configs

### PR DESCRIPTION
**Pull request by sdodson**
Supersedes #420

### CODE REVIEW

**Comment by brenton** [comment]
@sdodson, @ashcrow, could either of you record the current understanding of how `deployment_type`,  `product_type` and `service_type` should be used (or derived)?  I couldn't find the info in the previous PR and I want to make sure I'm understanding it so we can figure out if we'll support the current OSE 3.0 release.

CC @detiber

**Comment by ashcrow** [comment]
@brenton 

- ```service_type```: Internal only variable. It is based off the ```deployment_type```. If the ```deployment_type``` is set by the installer to ```origin``` then ```origin-{master,node}``` is used for services. Otherwise ```atomic-openshift-{master,node}``` is used for services

```deployment_type```: Set by user with default. Same as before (@aveshagarwal correct me here if I'm wrong please).

```product_type```: Set by user with default. This almost seems like it could go away in favor of the generated ```service_type```. Looking through it seems that ```product_type``` was trying to be ```service_type``` but at a higher level.

**Comment by aveshagarwal** [comment]
Both deployment_type and product_type are set by user. service_type is being set internally. 

deployment_types : online, origin, enterprise
product_types : origin, openshift, atomic-enterprise
service types: origin-{master, node},  atomic-openshift-{master, node}

**Comment by sdodson** [comment]
Current master only has deployment types
```
known_openshift_deployment_types: ['origin', 'online', 'enterprise']
```

I agree with @ashcrow that that `product_type` should be removed from the proposed changes and we compute `service_type` based on deployment_type and would suggest we use 
```
known_openshift_deployment_types: ['origin', 'online', 'enterprise','atomic-enterprise','openshift-enterprise']
service_type: "{{ 'origin' if deployment_type == 'origin' elseif 'openshift' if deployment_type == 'enterprise' else 'atomic-openshift' }}"
```

`deployment_type` of `enterprise` should only be used in OSE < 3.1. And `atomic-enterprise` vs `openshift-enterprise` could be used to differentiate feature sets.

`service_type` is slightly overloaded as it also refers to the package names, perhaps `content_set`? BTW the suggested service_type is pseudo-code, i'd have to verify the ansible syntax.

**Comment by aveshagarwal** [comment]
@sdodson product_type was implemented before recent naming changes when product name, its package name and services name were also same and so product_type worked.

**Comment by aveshagarwal** [comment]
@sdodson but I still think that deployment_type and service_type does not still clearly distinguish between product_types , because for same deployment type = enterprise and service_types/content_set/package names: atomic-openshit-{master, node}, there are 2 products:  openshift and atomic-enterprise.

**Comment by brenton** [comment]
@aveshagarwal, I think what @sdodson is saying is that for 3.1 the only deployment types we AEP and OSE care about are 'atomic-enterprise' and 'openshift-enterprise'.  The others are for origin, online or legacy ones for backwards compatibility.

I think we're going to attempt to sanely continue supporting the OSE 3.0 installs in this PR but if it turns out to be too messy we may even rethink that and consider branching.

**Comment by sdodson** [comment]
See #494

**Pull request closed without merging**
