### PR TITLE
change heketi logic

### PR DESCRIPTION
**Pull request by mjudeikis**
Fixes role idempotency with CRS

### CODE REVIEW

**Comment by mjudeikis** [comment]
If im configuring some steps after the cluster is already deployed and rerunning the playbook this secret gets regenerated and not read from secret. This causes plays to fails.

it would be good that somebody would review my logic as I tested this only with CRS and not CNS.

cc: @jarrpa  @SaravanaStorageNetwork

**Comment by jarrpa** [comment]
Hmm.... offhand, it looks like it should be fine. But I definitely want this tested in a CNS deployment. It'll be a while before I can get to it, so if someone else can verify first that would speed things up.

**Comment by jarrpa** [comment]
Oh. That's not something we currently support anyway, so it doesn't matter if it works or not yet. ;)

/lgtm

**Pull request merged**
