### PR TITLE
add run_once for create secret task in calico_master role

### PR DESCRIPTION
**Pull request by jeffrey4l**

### CODE REVIEW

**Comment by sdodson** [comment]
/lgtm
/ok-to-test
bot, test pull request

**Comment by diogo-reis** [comment]
I'm using the branch "release-3.9" and I'm having this problem. It is possible to apply this PR to branch release-3.9?

**Comment by jeffrey4l** [comment]
@vrutkovs  could you cherry pick this into release-3.9 branch? thanks.

**Comment by vrutkovs** [comment]
Sure thing

/cherrypick release-3.9

**Comment by diogo-reis** [comment]
Thanks, @jeffrey4l, @vrutkovs.

**Pull request merged**
