### PR TITLE
Fixes 1507119: Add retries to fixup shared-resource-viewer role

### PR DESCRIPTION
**Pull request by cuppett**
Attempting to add retries to resolve a common 3.6.z upgrade bug according to recommendation from the BZ.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1507119

### CODE REVIEW

**Comment by vrutkovs** [comment]
Are we replacing an existing role? What's causing this role to change?

**Comment by cuppett** [comment]
From @enj comments in the BZ there appears a change to the roles for 3.5->3.6. 

https://bugzilla.redhat.com/show_bug.cgi?id=1507119#c4

**Comment by sdodson** [comment]
/lgtm
This is already done on newer branches.

**Comment by sdodson** [comment]
e2e flakes, merging

**Pull request merged**
