### PR TITLE
use the correct name for the ruamel-yaml python module

### PR DESCRIPTION
**Pull request by ingvagabund**
SSIA

### CODE REVIEW

**Comment by ingvagabund** [comment]
aos-ci-test

**Comment by sdodson** [comment]
Merging this to unblock other things.

**Comment by sdodson** [comment]
well, nevermind, i can wait 30 minutes for the ci jobs to finish

**Comment by detiber** [comment]
I think there is a package out there that provides ruamel.yaml but does not provide python-ruamel-yaml.

I ran into this when trying to use the python-ruamel-yaml package from here: https://copr.fedorainfracloud.org/coprs/g/OpenShiftOnlineOps/openshift-tools/build/507334/

**Comment by sdodson** [comment]
I think that's a packaging error, I discussed that with Troy and we've since fixed that and the fedora packages don't provide that either.

**Comment by sdodson** [comment]
The Fedora packages in testing provide this
```
python-ruamel.yaml = 0.12.14-3.fc24
python-ruamel.yaml(x86-64) = 0.12.14-3.fc24
python2-ruamel-yaml = 0.12.14-3.fc24
python2-ruamel-yaml(x86-64) = 0.12.14-3.fc24
```

**Comment by sdodson** [comment]
oh wait, hmm

**Comment by detiber** [comment]
It could be a bug with the package/dnf/yum modules as well.

**Comment by ingvagabund** [comment]
The ``python-ruamel-yaml.spec`` does not declare any ``Provides: ruamel.yaml``. I am no python packaging guru to say what is the right way. Though, it seems the package should provide the virtual provides as it is the first name python developers will search for.

**Pull request merged**
