### PR TITLE
Return role dependencies to roles for openshift_{hosted,master,node}

### PR DESCRIPTION
**Pull request by abutcher**
Undoes #2240 in which role dependencies were moved to playbooks to improve run speed w/ ansible 2.1.

### CODE REVIEW

**Comment by abutcher** [comment]
aos-ci-test

**Comment by ashcrow** [comment]
I did some smoke testing on this as well. Worked fine :+1:.

**Comment by detiber** [comment]
@abutcher what is the performance diff with this vs the current approach?

**Comment by abutcher** [comment]
@detiber about the same

```
Dependencies in playbook: 11:06.71
Dependencies in role meta: 10:54.38
```

**Pull request merged**
