### PR TITLE
Fix broken oc_secret update function

### PR DESCRIPTION
**Pull request by barlik**

### CODE REVIEW

**Comment by barlik** [comment]
Please backport to release-3.6 as well.

**Comment by abutcher** [comment]
I kept starting to type comments but you got it :smile: :+1:

**Comment by barlik** [comment]
I should probably pay more attention to big ascii banners saying "generated do not edit" :)

**Comment by abutcher** [comment]
We're working through some flaky tests so some will need to be re-ran for now.
/test logging

**Comment by barlik** [comment]
sorry, I've accidentally pushed another patch to this branch. I've reverted it back, could you lgtm and retest it again?

**Pull request merged**
