### PR TITLE
Disable Swap: Add bool for proper conditional handling

### PR DESCRIPTION
**Pull request by mtnbikenc**
Bug 144668

### CODE REVIEW

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
[merge]

**Comment by mtnbikenc** [comment]
When did we start blocking on 3.6?
```
[ERROR] Status 'aos-ci-jenkins/OS_3.6_containerized' is in the 'error' state. This status must succeed for a merge.
```

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
[merge]

**Comment by sdodson** [comment]
re[merge] last merge failed due to statuses

**Pull request merged**
