### PR TITLE
metrics_server: add nodes resource to aggregated-metrics-reader

### PR DESCRIPTION
**Pull request by s-urbaniak**
related with https://github.com/coreos/kube-prometheus/pull/384 and https://github.com/kubernetes-sigs/metrics-server/pull/297
/cc @openshift/openshift-team-monitoring

### CODE REVIEW

**Comment by simonpasquier** [comment]
@s-urbaniak you need to edit the PR description to remove "Bug ....:" :smirk:

**Comment by LiliC** [comment]
/retitle metrics_server: add nodes resource to aggregated-metrics-reader

**Comment by brancz** [comment]
I think linking the bugzilla is correct, but the 3.11 bug does should not be linked to the 4.x bug I think.

**Comment by brancz** [comment]
I guess that was good enough after all :man_shrugging: :smile:

**Comment by sdodson** [comment]
> I guess that was good enough after all man_shrugging smile tada

but now you have to manually go set the bug MODIFIED

**Comment by brancz** [comment]
Makes sense. Thanks for the reminder!

**Pull request merged**
