### PR TITLE
a-o-i: Support for unattended upgrades

### PR DESCRIPTION
**Pull request by smunilla**
Adds the ability to perform upgrades without any user input through:

atomic-openshift-installer --unattended upgrade --next-major
or
atomic-openshift-installer --unattended upgrade --latest-minor

### CODE REVIEW

**Comment by smunilla** [comment]
@brenton

**Comment by brenton** [comment]
Could you rebase this on top of https://github.com/openshift/openshift-ansible/pull/1523 ?

**Comment by detiber** [comment]
Now if only we could just pass in a master fqdn and have it discover the
hosts in the cluster from the master.

**Comment by smunilla** [comment]
@brenton and…done

**Comment by brenton** [comment]
It doesn't seem like this can handle upgrading to 3.1.1.90x versions.  Could you take a look at that?  It will be really helpful if you can install the GA version and then run the upgrade command to install that version.

**Comment by smunilla** [comment]
I'll take a look to see why that would be. As is, it's just calling the v3_1_minor playbook.

**Pull request merged**
