### PR TITLE
Fixing missing _es_version variable

### PR DESCRIPTION
**Pull request by ewolinetz**
Found when doing a local upgrade from ES 2 -> ES 5

### CODE REVIEW

**Comment by richm** [comment]
What is the condition when a full cluster restart is required? e.g. I am deploying es version `x.y.z`, and the current version is `a.b.c`, is the condition when `x > a`? Is there some way we can discover both of those versions, and parameterize them, rather than having a hardcoded `5` in there?

**Comment by ewolinetz** [comment]
@richm yes, so currently we discover a.b.c by querying the cluster, however x.y.z will need to be specified in the role since we would know what version we are installing.

I had hard coded it since when we move to the operator model, we won't require this logic at all but I could move this into a `vars/main.yml` entry.

**Comment by richm** [comment]
Ah, then if operator solves this problem, we can leave it as is

**Comment by ewolinetz** [comment]
fluentd flake
/retest

**Comment by ewolinetz** [comment]
go bot, go!

**Pull request merged**
