### PR TITLE
changed oc to {{ openshift_client_binary }}

### PR DESCRIPTION
**Pull request by datarace**
Having oc command in my environment caused 'file not found' errors, probably due to PATH inconsistencies. Changing code to use the var {{ openshift_client_binary }} as per all other code.

### CODE REVIEW

**Comment by mjudeikis** [comment]
ping @ewolinetz

**Comment by mjudeikis** [comment]
@jcantrill release-3.7 has diff code base... we have pr for this outstanding... one sec

**Comment by datarace** [comment]
Cherry pick for release 3.7
https://github.com/openshift/openshift-ansible/pull/7070

**Comment by jcantrill** [comment]
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1543478

**Comment by leventyalcin** [comment]
How can I be notified when this has been released in the RPM package?

**Comment by datarace** [comment]
@leventyalcin  
Check out https://docs.openshift.com/container-platform/3.7/release_notes/ocp_3_7_release_notes.html to see when release increments above 3.7.23, then check the release details for this PR

**Pull request merged**
