### PR TITLE
Do not escalate privileges in jks generation tasks

### LINKED ISSUE #4203: openshift_logging: don't create local tmpdir with `become`
Local tmp dir is created without `local_action` and `become: no`. This causes permissions errors when the control host is in the cluster and the tmpdir is created as root but the user running the playbook isn't root.

### PR DESCRIPTION
**Pull request by irozzo-1A**
fixes #4203

### CODE REVIEW

**Comment by irozzo-1A** [comment]
@sdodson @stevekuznetsov This is not just a backport of #4203, I added  `become: no` to other `local_action`s. This should allow to have all local actions of openshift-logging playbook executed by an unprivileged user.

**Comment by sdodson** [comment]
> @sdodson @stevekuznetsov This is not just a backport of #4203, I added become: no to other local_actions. This should allow to have all local actions of openshift-logging playbook executed by an unprivileged user.

Lets make sure that master branch has all of these changes as well. We shouldn't allow these to get out of sync.

**Comment by irozzo-1A** [comment]
> Lets make sure that master branch has all of these changes as well. We shouldn't allow these to get out of sync.

@sdodson #6205

**Comment by sdodson** [comment]
The system-containers job is a flake, the logging job is a failure to build logging so it's hard to tell if the install would work or not. However I suspect everything with this PR is fine after looking it over once again. Merging.

**Pull request merged**
