### PR TITLE
Update IMAGE_PREFIX and IMAGE_VERSION values in hawkular template

### PR DESCRIPTION
**Pull request by nak3**

### CODE REVIEW

**Comment by detiber** [comment]
@sdodson this looks good to me at an initial glance.

**Comment by sdodson** [comment]
#976 handled the enterprise bits, I wonder why github is showing the diffs still?

@mwringe can you verify the origin changes are appropriate?

**Comment by mwringe** [comment]
@sdodson if you are referring to the github origin-metrics account, its because I have not yet had the chance to update the values listed there. It is on my todo list and hopefully I will soon have those updated.

The origin changes look good to me, but I have not actually gone in and verified it.

**Comment by sdodson** [comment]
:+1: LGTM

**Comment by sdodson** [comment]
@brenton good to merge, really only affects origin as we already fixed enterprise

**Pull request merged**
