### PR TITLE
Add missing symlink to roles

### PR DESCRIPTION
**Pull request by rhcarvalho**
It turned out that the playbook `playbooks/byo/openshift-preflight/check.yml` would only work under a certain `ansible.cfg` in which `roles/` was added to `roles_path`.

It was the case with the example config prior to b804e70cdd0bc8601bfc87fcf3e34043223828ee.

(wish we had something to catch this type of problem on CI)

### CODE REVIEW

**Comment by rhcarvalho** [comment]
aos-ci-test

**Comment by rhcarvalho** [comment]
Some CI tests are failing with:

```
BadRequest: Unable to associate floating ip 10.8.180.226 to fixed ip 172.16.132.91 for instance 46b0a9ef-ab26-457f-9860-d580f0df2aed. Error: External network 03670b37-8304-4518-9cfa-9ff17d197e12 is not reachable from subnet 3c47f4f1-f011-488f-a730-56bf2088a8b6.  Therefore, cannot associate Port bba65c3b-2efe-4319-a768-3dc25f26d52e with a Floating IP. (HTTP 400) (Request-ID: req-47406884-0bee-4ab5-a279-4737bb439c38)
```

Is it a known issue with the CI env? /cc @sdodson

**Comment by rhcarvalho** [comment]
One more try, aos-ci-test

**Comment by sdodson** [comment]
test infra flake, merging this

**Pull request merged**
