### PR TITLE
Switch logging and metrics OCP image tag from 3.6.0 to v3.6

### PR DESCRIPTION
**Pull request by sdodson**
This likely isn't the right tag for master but 'v3.7' tags don't exist yet.

Related https://bugzilla.redhat.com/show_bug.cgi?id=1445568
Related https://bugzilla.redhat.com/show_bug.cgi?id=1476712

### CODE REVIEW

**Comment by ewolinetz** [comment]
@sdodson does this also need a backport to the 3.6 release branch?

**Comment by sdodson** [comment]
yeah, and i think it's a blocker, yay

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Pull request merged**
