### PR TITLE
[3.7] PAPR: try to rebase on the latest code

### PR DESCRIPTION
**Pull request by vrutkovs**
Cherry-pick of #8233 on 3.7 branch

### CODE REVIEW

**Comment by jlebon** [comment]
Quoting from the other PR:

```
# Rebase existing branch on the latest code locally, as PAPR running doesn't do merges
```

I don't follow this. PAPR already does try to use the merge. If it can't, it's that there are conflicts that need to be resolved:

https://github.com/projectatomic/papr/blob/b43654acd5709bd0b3de659ae7be702f546203cc/papr/main#L91

**Comment by vrutkovs** [comment]
>I don't follow this. PAPR already does try to use the merge. If it can't, it's that there are conflicts that need to be resolved:

That's weird, we've seen PAPR sticking to the same commit, while target branch was updated - hence this change.

**Comment by jlebon** [comment]
Right, PRs are not automatically retested if the target branch is updated since the last test. The way we do this in other PAPR projects is to combine it with the [Homu](https://github.com/servo/homu) merge bot (our instance lives [here](https://homu-projectatomic-ci.apps.ci.centos.org/)). Tests are then rerun at merge time to make sure what we test is what we merge. I'm guessing Prow does something similar as well, right? Does it push the test merge to a temporary branch?

**Comment by vrutkovs** [comment]
> I'm guessing Prow does something similar as well, right? Does it push the test merge to a temporary branch?

Prow does rebase the PR whenever the branch changes, but I'm not sure if it pushes the result somewhere. I'll check with Steve if it does.

Leaving this open so that we'd check how it works in master and apply this other branches later on

**Pull request merged**
