### PR TITLE
Install latest gcloud

### PR DESCRIPTION
**Pull request by kargakis**
The pinned gcloud version seems to be no more

https://ci.openshift.redhat.com/jenkins/job/test_branch_openshift_ansible_extended_conformance_gce/682/consoleFull#-35116557558b6e51eb7608a5981914356

/assign smarterclayton 
/cherrypick release-3.9

### CODE REVIEW

**Comment by sdodson** [comment]
/lgtm
will merge as soon as gcp tests pass to unblock the queue

**Comment by michaelgugino** [comment]
@sdodson do we even want to specify a version here?  We could probably just remove the version from the package name altogether.

**Comment by kargakis** [comment]
I had removed the version initially but it seems that gcloud moves quite fast so it's probably preferrable to stick to one.

**Comment by kargakis** [comment]
```
TASK [openshift_gcp : Add masters to requisite groups] *************************
Monday 07 May 2018  14:18:17 +0000 (0:00:00.062)       0:09:29.281 ************ 
fatal: [localhost]: FAILED! => {"msg": "'dict object' has no attribute 'tag_ocp-master'"}
```
Unclear what has failed earlier in the process to result into this. Maybe it's easier to add the old version back to the mirrors cc @kwoodson

**Comment by sdodson** [comment]
I think https://github.com/openshift/openshift-ansible/pull/8241 may be the cause of the current failure

**Comment by sdodson** [comment]
Fixed by finding another source for google-cloud-sdk-183 but we need to find a better solution.

**Pull request closed without merging**
