### PR TITLE
GlusterFS: Implement container image version check

### PR DESCRIPTION
**Pull request by jarrpa**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1643465

Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>

### CODE REVIEW

**Comment by miminar** [comment]
Please document this openshift-docs, I've just hit this. It occurs pretty late in the installation run forcing us to update the inventory and restart.

**Comment by jarrpa** [comment]
@miminar https://bugzilla.redhat.com/show_bug.cgi?id=1677336

**Comment by leifmadsen** [comment]
I just ran into this using a known working inventory, and the defaults make my existing inventory not work. It took me a day to find this issue and understand that I am now required to add extra information to an inventory. The Ansible that was added to do all the version checks should note that if `latest` is found, that the inventory likely needs updating, and to refer to documentation that explains what needs to be set.

**Pull request merged**
