### PR TITLE
Fix HAProxy logging

### PR DESCRIPTION
**Pull request by sdodson**
- Fix haproxy logging -- probably more do to here to get useful logs but at least this will show us when frontends/backends are initialized

### CODE REVIEW

**Comment by sdodson** [comment]
@abutcher you removed the serial stuff, will re-introducing this break your work?

**Comment by sdodson** [comment]
@jeremyeder pretty sure this will fix your deployments

**Comment by sdodson** [comment]
aos-ci-test

**Comment by abutcher** [comment]
@sdodson Re-adding serial is fine but may be slower.

**Comment by liggitt** [comment]
https://github.com/openshift/origin/pull/10099 will make the policy setup more robust, but letting the masters start one at a time would still be ideal (bootstrap stuff will still compete unnecessarily in etcd if all the masters start at once)

**Pull request merged**
