### PR TITLE
Check for openshift attribute before using it during CNS install.

### PR DESCRIPTION
**Pull request by jmencak**
Fixes: BZ1523681

### CODE REVIEW

**Comment by jarrpa** [comment]
Howdy! A few questions:

* Why are you setting openshift_storage_glusterfs_wipe when the openshift hostvars are not available?
* Which playbook are you running?
* Did you previously run an installation of GlusterFS? And did it fail?

**Comment by jmencak** [comment]
Hi:
1) I'm setting openshift_storage_glusterfs_wipe to remove LVM metadata from devices previously used by glusterfs pods; if this is not done, installation will fail with these devices taken by the OS
2) playbooks/byo/openshift-glusterfs/config.yml and playbooks/byo/config.yml In both cases the install fails.
3) Installation works fine withouth openshift_storage_glusterfs_wipe and the LVM information wiped from the devices, so no, it didn't fail.  Subsequent installations fail, of course, both with openshift_storage_glusterfs_wipe set or unset.

I need this for CI environment, so a full wipe is necessary.  That's why I'm running with openshift_storage_glusterfs_wipe=true;  This PR fixes the issues I'm seeing.

**Comment by jmencak** [comment]
Can I ask for the ci/openshift-jenkins/extended_conformance_install_crio test to be removed?  It clearly doesn't fail due to this trivial PR.

**Comment by jarrpa** [comment]
This is not the correct fix. All GlusterFS nodes need to have openshift facts set. The right fix is to make sure that the `playbooks/openshift-glusterfs/config.yaml` playbook properly includes the required roles to set these variables. This was already done in 3.7, but for 3.8 they forced a refactor of how the playbooks are laid out and some of the dependencies may have been broken. The openshift hostvars should ALWAYS be present.

**Comment by jmencak** [comment]
The problem is this fails on a loadbalancer node and 3.7.x, please check the Red Hat BZ.

**Comment by jarrpa** [comment]
Oh, I see. ...apologies, I'm not much of an expert on Openshift. Why wouldn't the openshift variables be set on the node, then? I would imagine that the node would need to be a schedulable openshift node and thus always have the openshift hostvars.

**Comment by jmencak** [comment]
A loadbalancer node is not part of the cluster in a multi-master setup, for example.  "oc get nodes" will not show you a loadbalancer for example.  I believe in "defensive programming" and this PR is a step towards having a bit more defensiveness in the installer.

**Comment by jarrpa** [comment]
And you're saying you can still run the GlusterFS pods on the loadbalancer node? How does it receive labels and how would we be able to remove them? We don't want to skip this step of we're actually doing a wipe.

**Comment by jmencak** [comment]
Of course I cannot, loadbalancer is not part of the cluster to run pods on.  But the "groups.all" returns it in glusterfs_deploy.yml when ansible is run.

**Comment by jarrpa** [comment]
....oh! Would it be better then to change the group list to `groups.nodes` or something?

**Comment by jmencak** [comment]
That was my initial idea too, but honestly, I'm not sure if we can use groups.nodes.  Does this always return just openshift nodes?  What if somebody wanted to do something crazy like run CNS on the masters?  Do we want to stop them?  Probably not.  Saying that, while master don't need to be nodes in theory, they actually have to, as plenty of things wouldn't work (I'm told).  Long story short, I thought that groups.all was a cleaner solutions as long as you check for the attribute.

**Comment by jarrpa** [comment]
Okay. Well, thank you for your patience! I'm convinced. :)

/lgtm

**Comment by jmencak** [comment]
Thanks for the review, I didn't expect it to be easy. ;-)

**Comment by jmencak** [comment]
So, the conformance test fails with:

rm: cannot remove ‘/tmp/etcd/member’: Permission denied
[ERROR] test/extended/conformance.sh exited with code 1 after 00h 31m 06s

Can this be fixed or skipped somehow?

**Comment by sdodson** [comment]
flake

**Pull request merged**
