### PR TITLE
[WIP] Add Azure playbook

### PR DESCRIPTION
**Pull request by jim-minter**

### CODE REVIEW

**Comment by kwoodson** [comment]
@sdodson, we have squashed down the commits and simplified the code path for azure.  This is an opinionated install at this point.  We are not intending for customers to use these entry points.

We also have a few small follow up PRs that are needed but this encompasses the majority of the work.

**Comment by jim-minter** [comment]
@sdodson @kwoodson I believe this is ready for merge, ptal.

I have added a second commit which removes all dependencies on ansible 2.5.  I'd like to leave the commits separate so that if/when we move to ansible 2.5, we can revert the second commit.

AFAICS the system-containers test failure is not related to this PR.

**Comment by sdodson** [comment]
Can you put a README.md in playbooks/azure that explains this is not supported for OCP use?

**Comment by jim-minter** [comment]
@sdodson done: "The playbooks and tasks under this directory are not supported for end-customer use."

**Comment by jim-minter** [comment]
@sdodson please can this be merged?

**Comment by sdodson** [comment]
Those failures are both problems in CI configuration. The installation playbooks completed successfully without error, merging.

**Pull request merged**
