### PR TITLE
fixes 1419839.  Install only heapster for openshift_metrics when heap…

### PR DESCRIPTION
**Pull request by jcantrill**
…ster standalone flag is set.

### CODE REVIEW

**Comment by jcantrill** [comment]
@mwringe Can you comment on the prevalence of installing only heapster?  Does this need to land 3.5 or can it wait for  a point release?

**Comment by ewolinetz** [comment]
LGTM

**Comment by mwringe** [comment]
> @mwringe Can you comment on the prevalence of installing only heapster? Does this need to land 3.5 or can it wait for a point release?

I don't think we even have this in OCP, only in Origin. Its used by users who only want the HPA and do not want the other metrics components. But some people are using this since they only want the HPA

**Comment by jcantrill** [comment]
@sdodson based on https://github.com/openshift/openshift-ansible/pull/3284#issuecomment-278363223 we can wait.  My only reservation might be there are some org change that might make it more challanging to rebase but I suspect that is your reasons to prefer to defer.

**Comment by sdodson** [comment]
:shipit:

**Comment by smarterclayton** [comment]
Heck yeah!

**Pull request merged**
