### PR TITLE
Kuryr: Copy CNI plugins as DaemonSet initContainer

### PR DESCRIPTION
**Pull request by dulek**
Starting from 3.10 there's no way for SDN plugins to do Ansible
operations on the node. Kuryr was using that mechanism to install CNI
plugins binaries and disable kube-proxy. The latter seems to be
unnecessary now.

As for CNI plugins this commit moves copying them to Kuryr CNI DaemonSet
initContainer. The init container is running openshfit-node image which
includes binaries in /opt/cni/bin. The entrypoint will copy the binaries
to the correct directory on the node.

I'm also removing orphaned node.yaml from Kuryr role.

### CODE REVIEW

**Comment by dulek** [comment]
Okay, this just got verified by @luis5tb and Jon. Should be fine from Kuryr perspective.

**Comment by tomassedovic** [comment]
Note, this fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1571588

**Comment by vrutkovs** [comment]
bot, retest this please

**Comment by celebdor** [comment]
[Make Kuryr CNI DaemonSet download CNI plugins](https://trello.com/c/D6LzH8Se/394-make-kuryr-cni-daemonset-download-cni-plugins)

**Pull request merged**
