### PR TITLE
CF 4.6 Beta templates for OpenShift v3.7 and v3.9

### PR DESCRIPTION
**Pull request by simaishi**
cc @sdodson @Loicavenel

### CODE REVIEW

**Comment by sdodson** [comment]
bot, test pull request

**Comment by simaishi** [comment]
@sdodson @Loicavenel Updated templates in `openshift_management` directory as well.

**Comment by sdodson** [comment]
/lgtm
thanks

**Comment by bazulay** [comment]
@simaishi  @sdodson  were these templates tested with the openshift_management role ?
In case it is not than the role must be updated.

**Comment by bazulay** [comment]
@simaishi  @sdodson @gtanzill  was the openshift_management role tested with these templates

**Comment by sdodson** [comment]
OpenShift QE teams should pick up the change in the next build and go through them however they're not included in CI and Cluster Lifecycle team doesn't have capacity to test the content.

**Pull request merged**
