### PR TITLE
[3.7] GlusterFS: enable modprobe in pods that manage bricks

### PR DESCRIPTION
**Pull request by DanyC97**
Backports #7831
@jarrpa pls help review

### CODE REVIEW

**Comment by jarrpa** [comment]
/lgtm
/ok-to-test
bot, test pull request

**Comment by DanyC97** [comment]
@jarrpa is anything i need to look at ?

**Comment by DanyC97** [comment]
@sdodson master branch PR reference is https://github.com/openshift/openshift-ansible/pull/7831

**Comment by DanyC97** [comment]
@sdodson  PR description updated as suggested

**Comment by DanyC97** [comment]
@jarrpa @sdodson any idea holds this PR ?

**Comment by DanyC97** [comment]
thanks @jarrpa !

**Comment by michaelgugino** [comment]
@jarrpa I wouldn't say flake is the right word, these tests are just broken ATM unfortunately.

**Pull request merged**
