### PR TITLE
CNS installer mislabeling Heketi route

### PR DESCRIPTION
**Pull request by jkaurredhat**
#5906 
Signed-off-by: jkaurredhat <jkaur@redhat.com>

### CODE REVIEW

**Comment by jkaurredhat** [comment]
Cc @jarrpa

**Comment by jarrpa** [comment]
This PR is invalid. It's changes should be merged into #5906 and let those changes propagate to the 3.8 branch normally.

**Comment by DanyC97** [comment]
@jkaurredhat are you happy to close this PR and focus on #5906

**Comment by jarrpa** [comment]
I just realized this change is invalid. `ROUTE_NAME` is not the FQDN that will be reachable as the route address, `it is used in the generation of the FQDN. `ROUTE_NAME` must also be kept separate since the user is allwoed to specify a custom `glusterfs_heketi_url` to override `ROUTE_NAME`.

Closing this PR.

**Pull request closed without merging**
