### PR TITLE
Updating python-passlib assert

### PR DESCRIPTION
**Pull request by ewolinetz**
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1455310
Fixes https://github.com/openshift/openshift-ansible/issues/4111
Fixes https://github.com/openshift/openshift-ansible/issues/4287

### CODE REVIEW

**Comment by metal3d** [comment]
I guess my suggestion at #4285 is probably better. I'm not using rpm but a python command. Because passlib can be installed with "pip" for example, so RPM will not find the package. Am I wrong ?

**Comment by sdodson** [comment]
Yeah, while control host being other platforms is not something we explicitly support I'd prefer that anything that happens on the control host be as portable as possible. So I think attempting a python import is probably a better solution than relying on rpm.

**Comment by ewolinetz** [comment]
@sdodson updated to use approach used by @metal3d

**Comment by metal3d** [comment]
So I will close my PR and vote for yours

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Comment by sdodson** [comment]
[merge][severity: bug]

**Comment by sdodson** [comment]
flake https://github.com/openshift/origin/issues/13980
[merge][severity:bug]

**Comment by isaldarriaga** [comment]
@sdodson still happenning.

Client's output:
```
$ git describe
openshift-ansible-3.10.29-1-22-gdec10a6d6
```

```
$ cat /etc/*-release
Fedora release 28 (Twenty Eight)
...
```

```
$ ansible-playbook -i "/path/to/inventory.yaml" "playbooks/openshift-metrics/config.yml"
...
TASK [openshift_metrics : Check that python-passlib is available on the control host] ********************************************
task path: /home/ivan/convergence.cloud/dev-ops/kube-prod/origin/openshift-ansible-v3.10/roles/openshift_metrics/tasks/main.yaml:6
fatal: [prod-master-01.convergence.cloud]: FAILED! => {
    "assertion": "'not installed' not in passlib_result.stdout", 
    "changed": false, 
    "evaluated_to": false, 
    "msg": "python-passlib rpm must be installed on control host"
}
...
prod-master-01.example.com : ok=55   changed=2    unreachable=0    failed=1
...
```

Server's output:
```
[root@prod-master-01 ~]# cat /etc/*-release
CentOS Linux release 7.5.1804 (Core)
...

[root@prod-master-01 ~]# rpm -qa | grep passlib
python-passlib-1.6.5-2.el7.noarch

[root@prod-master-01 ~]# rpm -q python2-passlib
package python2-passlib is not installed

[root@prod-master-01 ~]# yum info python-passlib
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.scalabledns.com
 * extras: mirror.hmc.edu
 * updates: centos.sonn.com
Installed Packages
Name        : python-passlib
Arch        : noarch
Version     : 1.6.5
Release     : 2.el7
Size        : 2.7 M
Repo        : installed
From repo   : extras
Summary     : Comprehensive password hashing framework supporting over 20
            : schemes
URL         : https://bitbucket.org/ecollins/passlib
License     : BSD and Beerware and Copyright only
Description : Passlib is a password hashing library for Python 2 & 3, which
            : provides cross-platform implementations of over 20 password
            : hashing algorithms, as well as a framework for managing existing
            : password hashes. It's designed to be useful for a wide range of
            : tasks, from verifying a hash found in /etc/shadow, to providing
            : full-strength password hashing for multi-user application.

```

this problem is [fixed](https://github.com/ansible/ansible/pull/20202#issuecomment-309432286) in ansible 2.40 and 2.3.2

```
$ ansible --version

ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ivan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
```

**Pull request merged**
