### PR TITLE
Add a pause after node startup to prevent restart handler from interfering with sdn configuration

### PR DESCRIPTION
**Pull request by detiber**

### CODE REVIEW

**Comment by detiber** [comment]
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1246628

**Comment by brenton** [comment]
Mind rebasing this?  It helps me when it comes time to tag things if it includes other stuff we'd like QE to test.

**Comment by detiber** [comment]
@brenton done!

**Comment by brenton** [comment]
QE passed so I'm merging this in.

**Pull request merged**
