### PR TITLE
Use htpasswd hawkular metrics utility to generate SHA256 FIPS complia…

### PR DESCRIPTION
**Pull request by rubenvp8510**
…nt hashes

BZs associated with this PR: 
 - https://bugzilla.redhat.com/show_bug.cgi?id=1564681
- https://bugzilla.redhat.com/show_bug.cgi?id=1691678

### CODE REVIEW

**Comment by rubenvp8510** [comment]
@ewolinetz Question, I'm assuming that at this point can execute the docker command, is that a valid assumption?

I need to execute a command inside a container.

Thanks

**Comment by ewolinetz** [comment]
@rubenvp8510 i didn't notice that you were using `docker`... i'm not sure that's a valid assumption to make.

**Comment by rubenvp8510** [comment]
@ewolinetz Do you know what are the options in this case?

**Comment by ewolinetz** [comment]
I would suggest this is something run within the hawkular pod upon start-up, that is the approach we have taken for logging.

**Comment by rubenvp8510** [comment]
The thing is that I need the output of the command to create a secret and continue with the installation.

**Pull request merged**
