### PR TITLE
[WIP] Libvirt inventory: include non-RUNNING hosts

### PR DESCRIPTION
**Pull request by cben**
Currently libvirt hosts in non-RUNING states are silently omitted.
[possible states list: https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainState]
This is confusing, it's more useful to show the user "you also had these hosts but we couldn't act on them".

This PR makes the dynamic inventory simply include all hosts, and set a hostvar with the state.  The playbooks still don't look at this hostvar, but already fail in a IMHO more useful way:
```
...
GATHERING FACTS *************************************************************** 
fatal: [metrics4-node-compute-266fe] => SSH Error: ssh: Could not resolve hostname metrics4-node-compute-266fe: No address associated with hostname
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.
fatal: [metrics4-node-compute-0e7b2] => SSH Error: ssh: Could not resolve hostname metrics4-node-compute-0e7b2: No address associated with hostname
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.
fatal: [metrics4-node-infra-48f49] => SSH Error: ssh: Could not resolve hostname metrics4-node-infra-48f49: No address associated with hostname
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.
ok: [metrics4-master-d780a]
...
PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/bpaskinc/list.retry

localhost                  : ok=3    changed=0    unreachable=0    failed=0   
metrics4-master-d780a      : ok=1    changed=0    unreachable=0    failed=0   
metrics4-node-compute-0e7b2 : ok=0    changed=0    unreachable=1    failed=0   
metrics4-node-compute-266fe : ok=0    changed=0    unreachable=1    failed=0   
metrics4-node-infra-48f49  : ok=0    changed=0    unreachable=1    failed=0   
```
(in this example the other 3 hosts were PAUSED.)

- Libvirt's python wrapping exposes enums in an ugly way making it very hard to get a string.  The python module in the second commit is major overkill, I wrote it out of stubbornness — the _least_ messy way I found — but I suspect we don't want it in openshift-ansible.
  I should really fix this in libvirt; we don't want to depend on recent libvirt versions, but we don't really need the reason, only the state and that takes just a few lines, which extracted into the first commit.

- The next step would be to add early playbook tasks that fail with a nice message showing the VM state.  Or try starting the VMs!   Is this worth it?  Where should I put them?  Everything except terminate.yml?

### CODE REVIEW

**Comment by cben** [comment]
Oh, wait.  libvirt is LGPL, openshift-ansible is Apache license.   My module copy-pastes parts from libvirt.py (it's the most-maintainable of the alternatives I tried), which would be problematic.
So I'm dropping the second commit from this PR.
[permalink: https://github.com/cben/openshift-ansible/blob/559535629c6abce15d040080afadb51c4753a8cc/inventory/libvirt/helpers/libvirt_state_symbolic.py]

**Comment by detiber** [comment]
ok to test

**Comment by detiber** [comment]
@cben thanks for catching the license incompatibility. 

As an aside, I started to contribute this module upstream to ansible via: https://github.com/ansible/ansible/pull/10686

I just have never gotten around to addressing their request for documentation. If you are interested, I would suggest submitting a followup PR there for inclusion in the upstream ansible repo.

**Comment by detiber** [comment]
@lhuard1A could you test that this change does not break your environments?

**Comment by lhuard1A** [comment]
Hi,

I made a try of this PR with the following configuration:

```
$ LANG=C virsh list --all
 Id    Name                           State
----------------------------------------------------
 73    lenaic-master-45598            running
 76    lenaic-node-infra-3a693        running
 -     lenaic-node-compute-4bf35      shut off
 -     lenaic-node-compute-d1e55      shut off
```

and I got the following error:

```
TASK: [openshift_facts | Verify Ansible version is greater than or equal to 1.9.4 and less than 2.0] *** 
fatal: [lenaic-master-45598] => Traceback (most recent call last):
  File "/home/lenaic/doc/prog/RedHat/openshift-ansible/py-venv-libvirt/lib/python2.7/site-packages/ansible/runner/__init__.py", line 586, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/home/lenaic/doc/prog/RedHat/openshift-ansible/py-venv-libvirt/lib/python2.7/site-packages/ansible/runner/__init__.py", line 789, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/home/lenaic/doc/prog/RedHat/openshift-ansible/py-venv-libvirt/lib/python2.7/site-packages/ansible/runner/__init__.py", line 869, in _executor_internal_inner
    if not utils.check_conditional(cond, self.basedir, inject, fail_on_undefined=self.error_on_undefined_vars):
  File "/home/lenaic/doc/prog/RedHat/openshift-ansible/py-venv-libvirt/lib/python2.7/site-packages/ansible/utils/__init__.py", line 269, in check_conditional
    conditional = template.template(basedir, presented, inject)
  File "/home/lenaic/doc/prog/RedHat/openshift-ansible/py-venv-libvirt/lib/python2.7/site-packages/ansible/utils/template.py", line 124, in template
    varname = template_from_string(basedir, varname, templatevars, fail_on_undefined)
  File "/home/lenaic/doc/prog/RedHat/openshift-ansible/py-venv-libvirt/lib/python2.7/site-packages/ansible/utils/template.py", line 382, in template_from_string
    res = jinja2.utils.concat(rf)
  File "<template>", line 6, in root
  File "/usr/lib/python2.7/site-packages/jinja2/runtime.py", line 156, in resolve
    return self.parent[key]
  File "/home/lenaic/doc/prog/RedHat/openshift-ansible/py-venv-libvirt/lib/python2.7/site-packages/ansible/utils/template.py", line 205, in __getitem__
    return template(self.basedir, var, self.vars, fail_on_undefined=self.fail_on_undefined)
  File "/home/lenaic/doc/prog/RedHat/openshift-ansible/py-venv-libvirt/lib/python2.7/site-packages/ansible/utils/template.py", line 124, in template
    varname = template_from_string(basedir, varname, templatevars, fail_on_undefined)
  File "/home/lenaic/doc/prog/RedHat/openshift-ansible/py-venv-libvirt/lib/python2.7/site-packages/ansible/utils/template.py", line 382, in template_from_string
    res = jinja2.utils.concat(rf)
  File "<template>", line 10, in root
  File "/home/lenaic/doc/prog/RedHat/openshift-ansible/filter_plugins/oo_filters.py", line 592, in oo_persistent_volumes
    kind = hostvars['openshift']['hosted'][component]['storage']['kind']
KeyError: 'storage'


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
lenaic-master-45598        : ok=183  changed=9    unreachable=1    failed=0   
lenaic-node-compute-4bf35  : ok=0    changed=0    unreachable=1    failed=0   
lenaic-node-compute-d1e55  : ok=0    changed=0    unreachable=1    failed=0   
lenaic-node-infra-3a693    : ok=19   changed=2    unreachable=0    failed=0   
localhost                  : ok=18   changed=0    unreachable=0    failed=0   
```

It looks like, if some nodes are not running, the `hostvars` variable contains incomplete information about those nodes and some parts of the `oo_persistent_volumes()` method of `oo_filters.py` don’t cope property with the miss of the `storage` key.

**Comment by detiber** [comment]
@cben I think the failure is no longer so obvious.

**Comment by cben** [comment]
Yeah, looks worse.

**Pull request closed without merging**
