### PR TITLE
Fixing the spec for PR 1734

### PR DESCRIPTION
**Pull request by brenton**
@joelddiaz, @sdodson, PTAL.  We don't ship the inventory subpackage in OSE but this was required in order to get things to build.

### CODE REVIEW

**Comment by brenton** [comment]
If Ops is no longer using this subpackage it would be great to remove it.

**Comment by joelddiaz** [comment]
@brenton fine by me to remove the subpackage. we have our own in openshift-tools and have migrated our pre-existing RPMs to depend on the version from openshift-tools now.

**Comment by sdodson** [comment]
LGTM

**Comment by brenton** [comment]
@joelddiaz  Are any of the following in use?
```
openshift-ansible-inventory-3.0.81-1.git.10.472fa25.el7.noarch
openshift-ansible-inventory-gce-3.0.81-1.git.10.472fa25.el7.noarch
openshift-ansible-inventory-aws-3.0.81-1.git.10.472fa25.el7.noarch
```

**Comment by joelddiaz** [comment]
@brenton not by us any more

**Comment by brenton** [comment]
@joelddiaz are there any other subpackages you are no longer using?

**Comment by joelddiaz** [comment]
@brenton i grepped around our repos, and i don't see anywhere that we are using or depending on RPMs from openshift-ansible any more

**Comment by brenton** [comment]
@joelddiaz, thx. I'll pull out the other ones we don't ship.

**Comment by brenton** [comment]
@tdawson, fyi, we'll need to have this merged before you do tomorrow's build.

**Comment by brenton** [comment]
@joelddiaz, Does Ops use any of these files under /bin?  Are they available from another repository now?

cc @detiber, I suspect we can't remove these files yet since some community members are still using them.  Do you know if that's the case?  I might just limit the changes to the specfile for now.

**Comment by brenton** [comment]
I put the bin file removal in a separate commit.  I'm happy to remove it if now's not the time to worry about this.

**Comment by brenton** [comment]
I'm just going to make the specfile change.  We need to get this moving.

**Comment by joelddiaz** [comment]
@brenton we aren't using anything under openshift-ansible/bin. we've copied/split it up between openshift-tools/scripts/inventory-clients and openshift-tools/openshift_tools/inventory_clients

**Pull request merged**
