### PR TITLE
use hostnamectl to set the hostname

### PR DESCRIPTION
**Pull request by sdodson**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1280171

### CODE REVIEW

**Comment by sdodson** [comment]
@detiber you and I had discussed this but I think I misunderstood the problem when I mentioned it. re-reading the bug it looks like QE understands that you can't set the hostname to a name that doesn't resolve, but they have hosts where they'd like to set the hostname to a name that does resolve. This swaps out ansible hostname module for hostnamectl on atomic.

**Comment by detiber** [comment]
@sdodson why not just change both to use hostnamectl?  All supported host targets we support would have it.

**Comment by sdodson** [comment]
> @sdodson why not just change both to use hostnamectl? All supported host targets we support would have it.

Makes sense, done.

**Comment by detiber** [comment]
:+1: @brenton

**Pull request merged**
