### PR TITLE
Enable openshift-aws-autoscaler

### PR DESCRIPTION
**Pull request by mazzystr**
Enable openshift-aws-autoscaler

Minimum req'd keys...
```
openshift_cluster_autoscaler_install: true
openshift_cluster_autoscaler_node_groups:
- name: "ccallegar2 compute group 1"
  min: "6"
  max: "10"
```

### CODE REVIEW

**Comment by mazzystr** [comment]
### INSTALL
```
PLAY [Setup master instances] ***********************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************
ok: [localhost]

TASK [openshift_aws : Alert user to variables needed - clusterid] ***********************************************************************
ok: [localhost] => {
    "msg": "openshift_aws_clusterid=ccallegar2"
}

TASK [openshift_aws : Alert user to variables needed - region] **************************************************************************
ok: [localhost] => {
    "msg": "openshift_aws_region=us-east-1"
}

TASK [openshift_aws : fetch master instances] *******************************************************************************************
ok: [localhost]

TASK [openshift_aws : debug] ************************************************************************************************************
ok: [localhost] => {
    "instancesout": {
        "attempts": 1,
        "changed": false,
        "failed": false,
        "instances": [
        jsonjsonjson......
        ]
    }
}

TASK [openshift_aws : add new master to masters group] **********************************************************************************
changed: [localhost] => (item={junkjunkjunk... })

TASK [add a master to oo_first_master group] ********************************************************************************************
changed: [localhost]

PLAY [Cluster Auto Scaler Install Checkpoint Start] *************************************************************************************

TASK [Set Cluster Auto Scaler install 'In Progress'] ************************************************************************************
ok: [ec2-54-209-39-204.compute-1.amazonaws.com]

PLAY [OpenShift Cluster Auto Scaler] ****************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************
ok: [ec2-54-209-39-204.compute-1.amazonaws.com]

TASK [openshift_cluster_autoscaler : Set cluster autoscaler namespace] ******************************************************************
changed: [ec2-54-209-39-204.compute-1.amazonaws.com]

TASK [openshift_cluster_autoscaler : create the cluster-autoscaler serviceaccount] ******************************************************
changed: [ec2-54-209-39-204.compute-1.amazonaws.com]

TASK [openshift_cluster_autoscaler : copy the cluster-autoscaler files] *****************************************************************
ok: [ec2-54-209-39-204.compute-1.amazonaws.com] => (item=clusterrole.yml)
changed: [ec2-54-209-39-204.compute-1.amazonaws.com] => (item=role.yml)

TASK [openshift_cluster_autoscaler : Ensure the cluster-autoscaler roles are present] ***************************************************
changed: [ec2-54-209-39-204.compute-1.amazonaws.com] => (item={u'type': u'clusterrole', u'name': u'cluster-autoscaler', u'fname': u'clusterrole.yml'})
changed: [ec2-54-209-39-204.compute-1.amazonaws.com] => (item={u'type': u'role', u'name': u'cluster-autoscaler', u'fname': u'role.yml'})

TASK [openshift_cluster_autoscaler : include_tasks] *************************************************************************************
included: /home/ccallega/git/openshift-ansible/roles/openshift_cluster_autoscaler/tasks/aws.yml for ec2-54-209-39-204.compute-1.amazonaws.com

TASK [openshift_cluster_autoscaler : Check that openshift_cluster_autoscaler_aws_key is set] ********************************************
skipping: [ec2-54-209-39-204.compute-1.amazonaws.com]

TASK [openshift_cluster_autoscaler : Check that openshift_cluster_autoscaler_aws_secret_key is set] *************************************
skipping: [ec2-54-209-39-204.compute-1.amazonaws.com]

TASK [openshift_cluster_autoscaler : laydown the aws-credentials] ***********************************************************************
ok: [ec2-54-209-39-204.compute-1.amazonaws.com]

TASK [openshift_cluster_autoscaler : create the aws creds secret] ***********************************************************************
changed: [ec2-54-209-39-204.compute-1.amazonaws.com]

TASK [openshift_cluster_autoscaler : create the policies] *******************************************************************************
ok: [ec2-54-209-39-204.compute-1.amazonaws.com] => (item={u'name': u'cluster-role'})
changed: [ec2-54-209-39-204.compute-1.amazonaws.com] => (item={u'name': u'role', u'role_namespace': u'openshift-autoscaler'})

TASK [openshift_cluster_autoscaler : grant cluster-reader to cluster-autoscaler] ********************************************************
ok: [ec2-54-209-39-204.compute-1.amazonaws.com]

TASK [openshift_cluster_autoscaler : laydown the deployment file for cluster-autoscaler] ************************************************
changed: [ec2-54-209-39-204.compute-1.amazonaws.com]

TASK [openshift_cluster_autoscaler : Ensure the cluster-autoscaler is present] **********************************************************
changed: [ec2-54-209-39-204.compute-1.amazonaws.com]

PLAY [Cluster Auto Scaler Install Checkpoint End] ***************************************************************************************

TASK [Set Cluster Auto Scaler install 'Complete'] ***************************************************************************************
ok: [ec2-54-209-39-204.compute-1.amazonaws.com]

PLAY RECAP ******************************************************************************************************************************
ec2-54-209-39-204.compute-1.amazonaws.com : ok=14   changed=8    unreachable=0    failed=0
localhost                  : ok=9    changed=2    unreachable=0    failed=0


INSTALLER STATUS ************************************************************************************************************************
Cluster Auto Scaler Install  : Complete (0:00:29)
```

### OPENSHIFT
```
[root@ip-172-31-43-79 ~]# oc project openshift-autoscaler
Now using project "openshift-autoscaler" on server "https://internal.api.ccallegar2.sysdeseng.com:443".
[root@ip-172-31-43-79 ~]# oc get all
NAME                                      READY     STATUS    RESTARTS   AGE
pod/cluster-autoscaler-5799fb9974-87ghb   1/1       Running   0          6m

NAME                                 DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/cluster-autoscaler   1         1         1            1           6m

NAME                                            DESIRED   CURRENT   READY     AGE
replicaset.apps/cluster-autoscaler-5799fb9974   1         1         1         6m
[root@ip-172-31-43-79 ~]# oc describe deployment.apps/cluster-autoscaler
Name:                   cluster-autoscaler
Namespace:              openshift-autoscaler
CreationTimestamp:      Fri, 14 Sep 2018 22:27:06 +0000
Labels:                 app=cluster-autoscaler
Annotations:            deployment.kubernetes.io/revision=1
Selector:               app=cluster-autoscaler,role=infra
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=cluster-autoscaler
                    role=infra
  Service Account:  cluster-autoscaler
  Containers:
   autoscaler:
    Image:      registry.reg-aws.openshift.com:443/openshift3/ose-cluster-autoscaler:v3.11
    Port:       <none>
    Host Port:  <none>
    Args:
      /bin/cluster-autoscaler
      --alsologtostderr
      --v=4
      --skip-nodes-with-local-storage=False
      --leader-elect-resource-lock=configmaps
      --namespace=openshift-autoscaler
      --cloud-provider=aws
      --nodes=6:10:ccallegar2 compute group 1
    Environment:
      AWS_REGION:                   us-east-1
      AWS_SHARED_CREDENTIALS_FILE:  /var/run/secrets/aws-creds/creds
    Mounts:
      /var/run/secrets/aws-creds from aws-creds (ro)
  Volumes:
   aws-creds:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  autoscaler-credentials
    Optional:    false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   cluster-autoscaler-5799fb9974 (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  6m    deployment-controller  Scaled up replica set cluster-autoscaler-5799fb9974 to 1
```

**Comment by mazzystr** [comment]
@michaelgugino @sdodson @frobware

**Comment by sdodson** [comment]
Are you saying that without this change there's no host in oo_first_master group? If that's the case I'd expect the group initialization to happen in the public playbook rather than the private playbooks.

I don't quite understand what this change is actually doing or why it's necessary.

**Comment by mazzystr** [comment]
Let's close this with no merge.  I now see how the components play works.

**Pull request closed without merging**
