### PR TITLE
Add CA to Node CA-trust

### PR DESCRIPTION
**Pull request by abutcher**
Builds on #1990

### CODE REVIEW

**Comment by andrewklau** [comment]
I picked the first commit and ran this today, it seemed to work as expected. Is this something that will be merged?

**Comment by abutcher** [comment]
@andrewklau I'd like to push for this to get merged post 3.3 freeze.

**Comment by detiber** [comment]
@abutcher anything this needs other than tests?

**Comment by abutcher** [comment]
@detiber This needs melded with what I had to do for secure registry.

**Comment by abutcher** [comment]
This is now part of #2475.

**Pull request closed without merging**
