### PR TITLE
Backport to 3.6 - logging: fix kibana and kibana-ops defaults

### PR DESCRIPTION
**Pull request by wozniakjan**
backport of https://github.com/openshift/openshift-ansible/pull/5358

### CODE REVIEW

**Comment by ingvagabund** [comment]
Looks like the failed conformance tests are completely unrelated to this PR. @wozniakjan can you remove the last commit? We can merge it manually. @ewolinetz WDYT?

**Comment by wozniakjan** [comment]
@ingvagabund I agree, done

**Pull request merged**
