### PR TITLE
[release-3.9] Get precise openshift version with containerized installation

### PR DESCRIPTION
**Pull request by nak3**
Currently get_container_openshift_version() in openshift_facts.py
library does not get precise openshift version when containerized
installation. Due to that some version check fails like bz#1597528.

This patch changes to call openshift version by running container and
get precise version.

Fixes https://github.com/openshift/openshift-ansible/pull/9054

### CODE REVIEW

**Comment by michaelgugino** [comment]
/approve

This seems sensible.  Hopefully we don't run into an edge case where someone has pulled a later version of the v3.9 tag that will be different than what's actually running.  Not sure if we want to build protection against that.

@sdodson @mtnbikenc @vrutkovs thoughts?

**Comment by sdodson** [comment]
Yeah, I think that's fine.

**Pull request merged**
