### PR TITLE
Rework default TSB prefix and imagename to match other services

### PR DESCRIPTION
**Pull request by vrutkovs**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1518917

### CODE REVIEW

**Comment by sdodson** [comment]
/lgtm
We should add a release note to mention this change as it will affect anyone who has previously overridden this value. https://github.com/openshift/openshift-docs/issues/6458
something like 

We have updated the image prefix name definition for the template service broker to include the 'origin-' or 'ose-' prefix similar to all other components. If you had previously configured `template_service_broker_prefix=registry.example.com/` it must be updated to be `template_service_broker_prefix=registry.example.com/ose-`

**Comment by vrutkovs** [comment]
>We should add a release note to mention this change as it will affect anyone who has previously overridden this value

Done

**Comment by mtnbikenc** [comment]
FWIW, it doesn't look like adding 'ose-' to the prefix is the predominate method.  We still have inconsistency in *_prefix: usage.

```
$  grep -r -E '_prefix:.*registry' roles/                                                                               [±master ✓]
roles/openshift_logging_kibana/vars/openshift-enterprise.yml:__openshift_logging_kibana_image_prefix: "{{ openshift_logging_image_prefix | default('registry.access.redhat.com/openshift3/') }}"
roles/openshift_logging_kibana/vars/openshift-enterprise.yml:__openshift_logging_kibana_proxy_image_prefix: "{{ openshift_logging_image_prefix | default('registry.access.redhat.com/openshift3/') }}"
roles/openshift_prometheus/vars/openshift-enterprise.yml:l_openshift_prometheus_image_prefix: "{{ openshift_prometheus_image_prefix | default('registry.access.redhat.com/openshift3/') }}"
roles/openshift_logging_curator/vars/openshift-enterprise.yml:__openshift_logging_curator_image_prefix: "{{ openshift_logging_image_prefix | default('registry.access.redhat.com/openshift3/') }}"
roles/template_service_broker/vars/openshift-enterprise.yml:__template_service_broker_prefix: "registry.access.redhat.com/openshift3/ose-"
roles/openshift_logging_mux/vars/openshift-enterprise.yml:__openshift_logging_mux_image_prefix: "{{ openshift_logging_image_prefix | default('registry.access.redhat.com/openshift3/') }}"
roles/openshift_logging_fluentd/vars/openshift-enterprise.yml:__openshift_logging_fluentd_image_prefix: "{{ openshift_logging_image_prefix | default('registry.access.redhat.com/openshift3/') }}"
roles/openshift_service_catalog/vars/openshift-enterprise.yml:__openshift_service_catalog_image_prefix: "registry.access.redhat.com/openshift3/ose-"
roles/openshift_logging_eventrouter/vars/openshift-enterprise.yml:__openshift_logging_eventrouter_image_prefix: "{{ openshift_logging_image_prefix | default('registry.access.redhat.com/openshift3/') }}"
roles/openshift_metrics/vars/openshift-enterprise.yml:__openshift_metrics_image_prefix: "registry.access.redhat.com/openshift3/"
roles/ansible_service_broker/vars/openshift-enterprise.yml:__ansible_service_broker_image_prefix: registry.access.redhat.com/openshift3/ose-
roles/ansible_service_broker/vars/openshift-enterprise.yml:__ansible_service_broker_etcd_image_prefix: registry.access.redhat.com/rhel7/
roles/openshift_web_console/vars/openshift-enterprise.yml:__openshift_web_console_prefix: "registry.access.redhat.com/openshift3/"
roles/openshift_logging_elasticsearch/vars/openshift-enterprise.yml:__openshift_logging_elasticsearch_image_prefix: "{{ openshift_logging_image_prefix | default('registry.access.redhat.com/openshift3/') }}"
roles/openshift_logging_elasticsearch/vars/openshift-enterprise.yml:__openshift_logging_elasticsearch_proxy_image_prefix: "{{ openshift_logging_image_prefix | default('registry.access.redhat.com/openshift3/') }}"
```

**Comment by mtnbikenc** [comment]
OTOH, having 'origin-' seems to be more consistent for those related _prefix vars.  But there is still inconsistency in the use there.  We probably need to open a card to address all of these across the board.

```
$  grep -r -E '_prefix:.*openshift/' roles/                                                                             [±master ✓]
roles/openshift_logging_kibana/vars/default_images.yml:__openshift_logging_kibana_image_prefix: "{{ openshift_logging_image_prefix | default('docker.io/openshift/origin-') }}"
roles/openshift_logging_kibana/vars/default_images.yml:__openshift_logging_kibana_proxy_image_prefix: "{{ openshift_logging_image_prefix | default('docker.io/openshift/origin-') }}"
roles/openshift_provisioners/defaults/main.yaml:openshift_provisioners_image_prefix: docker.io/openshift/origin-
roles/openshift_prometheus/vars/default_images.yml:l_openshift_prometheus_image_prefix: "{{ openshift_prometheus_image_prefix | default('openshift/') }}"
roles/openshift_logging_curator/vars/default_images.yml:__openshift_logging_curator_image_prefix: "{{ openshift_logging_image_prefix | default('docker.io/openshift/origin-') }}"
roles/template_service_broker/vars/default_images.yml:__template_service_broker_prefix: "docker.io/openshift/origin-"
roles/openshift_logging_mux/vars/default_images.yml:__openshift_logging_mux_image_prefix: "{{ openshift_logging_image_prefix | default('docker.io/openshift/origin-') }}"
roles/openshift_logging_fluentd/vars/default_images.yml:__openshift_logging_fluentd_image_prefix: "{{ openshift_logging_image_prefix | default('docker.io/openshift/origin-') }}"
roles/openshift_service_catalog/vars/default_images.yml:__openshift_service_catalog_image_prefix: "docker.io/openshift/origin-"
roles/openshift_logging_eventrouter/vars/default_images.yml:__openshift_logging_eventrouter_image_prefix: "{{ openshift_logging_image_prefix | default('docker.io/openshift/origin-') }}"
roles/openshift_metrics/vars/default_images.yml:__openshift_metrics_image_prefix: "docker.io/openshift/origin-"
roles/openshift_web_console/vars/default_images.yml:__openshift_web_console_prefix: "docker.io/openshift/"
roles/openshift_logging_elasticsearch/vars/default_images.yml:__openshift_logging_elasticsearch_image_prefix: "{{ openshift_logging_image_prefix | default('docker.io/openshift/origin-') }}"
roles/openshift_logging_elasticsearch/vars/default_images.yml:__openshift_logging_elasticsearch_proxy_image_prefix: "{{ openshift_logging_image_prefix | default('docker.io/openshift/') }}"
```

**Pull request merged**
