### PR TITLE
Flush ansible handlers before running restart service tasks in contiv

### PR DESCRIPTION
**Pull request by jeffrey4l**
Need flush the handler to reload systemd before running restart service
tasks.

### CODE REVIEW

**Comment by vrutkovs** [comment]
bot, test pull request

**Comment by vrutkovs** [comment]
/lgtm

GCP tests are flaking

**Comment by jeffrey4l** [comment]
thanks @vrutkovs . How could we backport this patch to stable branch?

**Comment by vrutkovs** [comment]
@jeffrey4l Sure, backporting to 3.9

/cherrypick release-3.9

**Pull request merged**
