### PR TITLE
[wip] Add restart back to openshift-node join

### PR DESCRIPTION
**Pull request by jcpowermac**
See pull requests:

PR #12003
PR #12011
PR #11968

### CODE REVIEW

**Comment by jcpowermac** [comment]
Needs PR #12011 to merge first.

**Comment by mtnbikenc** [comment]
@jcpowermac Touch a file in the openshift_logging role to trigger the logging tests.  Let's see if it passes.

**Comment by mtnbikenc** [comment]
This change looks good except it will need https://github.com/openshift/openshift-ansible/pull/12239 first to ensure restarts don't fail for GlusterFS environments when GlusterFS has not yet been deployed during initial install.

**Comment by mtnbikenc** [comment]
Related https://bugzilla.redhat.com/show_bug.cgi?id=1768876
/test install
/test logging

**Comment by mtnbikenc** [comment]
#12239 has merged
/test install
/test logging

**Comment by mtnbikenc** [comment]
Adding this restart caused issues with docker and cni plugins in CI.  The change in #12261 was rolled back and we will not be pursing this at this time.

/close

**Pull request closed without merging**
