### PR TITLE
Revert "Add metrics-server to openshift-metrics playbook"

### PR DESCRIPTION
**Pull request by frobware**
This reverts commit 3f78dcf35d2f14beb35855e9d8b079dfbc0beeff.

We don't yet have OCP images for metrics-server so reverting until we
do have images.

### CODE REVIEW

**Comment by frobware** [comment]
@sjenning @DirectXMan12 as discussed in standup.

**Comment by sjenning** [comment]
fyi @derekwaynecarr

**Comment by sjenning** [comment]
/hold
Let wait on this for the moment.  We can still revert after feature freeze.  I really would like to talk with @derekwaynecarr about this first.

**Comment by sjenning** [comment]
Exception was denied.  Need to revert until 3.11.

/hold cancel

**Comment by sdodson** [comment]
bot, retest this please

**Pull request merged**
