### PR TITLE
Convert calico install from systemd-based to self-hosted

### PR DESCRIPTION
**Pull request by ozdanborne**
This PR updates the method by which Calico is installed from a systemd-based installation to a self-hosted install. An upgrade playbook is added which can be used to upgrade a live system from systemd-based to self-hosted.

cc: @rajatchopra

### CODE REVIEW

**Comment by rajatchopra** [comment]
This is still a 'work in progress' until declared otherwise in a later comment.

**Comment by ozdanborne** [comment]
Thanks @rajatchopra . I had a bad rebase that was causing issues. I've fixed it and it should all be resolved now.

Note that I'm having issues running this against the master branch due to bug #7134 . 
Here is a working branch which has the same commit cherry-picked onto the release-3.8 branch: https://github.com/ozdanborne/openshift-ansible/tree/calico-hosted-3.8

**Comment by rajatchopra** [comment]
This install has been tested and the cluster comes up fine. There was an inadvertent error in the testing related to wrong override of public_hostname of one of the nodes - but the rest of the cluster functioned properly.

/lgtm
/approve

This comment unholds WIP tag mentioned in https://github.com/openshift/openshift-ansible/pull/7115#issuecomment-365349608


@sdodson What do you think is wrong with Travis here? Anything legit?

**Comment by ozdanborne** [comment]
@rajatchopra Looks like travis was failing due to some whitespace / newline linting, as well as some issues with me using `include` instead of `include_tasks` / `include_role`. I added a second commit which fixed the latter. I'd like to quickly run it through the paces to make sure I didn't break anything.

Can I get another /lgtm in the meantime?

**Comment by ozdanborne** [comment]
/retest

I just completed a runthrough with the latest changes and everything is still working as expected. 

@rajatchopra @sdodson can I get an lgtm for testing?

**Comment by ozdanborne** [comment]
@sdodson can you take a look? I can't see anything that would be the fault of my changes. Should I rebase?

**Comment by ozdanborne** [comment]
@sdodson @rajatchopra any advice?

**Comment by ozdanborne** [comment]
ping @sdodson @rajatchopra

**Comment by ozdanborne** [comment]
Hey guys, I rebased and squashed. Anything else I can do to get this going? @rajatchopra @sdodson

**Comment by ozdanborne** [comment]
@sdodson sorry to pester but hoping to get this in soon...

**Comment by ozdanborne** [comment]
@sdodson what's the deal here? The code I've changed isn't even executed by the CI tests. How is it possible that it's causing the tests to fail?

**Comment by sdodson** [comment]
These are all related to broken CI. The last problem should be fixed now. 
/test install

**Comment by dhananjaysathe** [comment]
Is there a reason we can't switch to the new calico 3.0.x (given the nice calicoctl and global policy work)  on a fresh ocp 3.9 release. I wouldn't mind giving it a try and reporting but wanted to know if this as already been considered and rejected before I spend the time. @ozdanborne @sdodson

**Pull request merged**
