### PR TITLE
Remove openshift_excluders status tasks

### PR DESCRIPTION
**Pull request by sdodson**
Since we no longer care about the current status and instead just install/enable/disable based on enable_excluders variables we can remove calls to status which were attempting to upgrade packages that were not installed and call the status function on non existent binaries.

Previously with enable_excluders=false we were installing them via the status.yml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1432345

### CODE REVIEW

**Comment by sdodson** [comment]
@jhadvig please try this

**Comment by ingvagabund** [comment]
In that case, we can remove all `enable_docker_excluder_override` and `disable_openshift_excluder_override` occurrences as well.

**Comment by sdodson** [comment]
Ok, do you think this makes sense in general though?

**Comment by ingvagabund** [comment]
I was wondering a while ago if we really need the status at this point and I don't think we do.

**Comment by ingvagabund** [comment]
The remaining variables can be removed later,. They are set in the status only anyway. If not set, they are set to some default value.

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Pull request merged**
