### PR TITLE
Fix templating of static service files

### PR DESCRIPTION
**Pull request by mtnbikenc**
Static files should use `copy:` to retrieve from the `files\` directory.  Maybe?

https://github.com/ansible/ansible/issues/18489
https://github.com/openshift/openshift-ansible/pull/4131

### CODE REVIEW

**Comment by mtnbikenc** [comment]
Appears there is a bug in Ansible.  Looks in `<role_name>/tasks/files` instead of `<role_name>/files`.

Debug:
```
 27140 1494616290.06971: search_path:
	/home/rteague/dev/clusters/aws-c1/openshift-ansible/roles/openshift_master/tasks/files/atomic-openshift-master.service
	/home/rteague/dev/clusters/aws-c1/openshift-ansible/roles/openshift_master/tasks/atomic-openshift-master.service
	/home/rteague/dev/clusters/aws-c1/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_6/../../../../common/openshift-cluster/upgrades/v3_6/../files/atomic-openshift-master.service
	/home/rteague/dev/clusters/aws-c1/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_6/../../../../common/openshift-cluster/upgrades/v3_6/../atomic-openshift-master.service
```

```
> $ ansible --versionansible 2.3.0.0
  config file = /home/rteague/dev/clusters/aws-c1/ansible.cfg
  configured module search path = [u'/usr/lib/python2.7/site-packages/ara/plugins/modules']
  python version = 2.7.13 (default, Jan 12 2017, 17:59:37) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

**Comment by mtnbikenc** [comment]
Added a temporary static link for `tasks/files -> ../files` until i can figure out if and where this is fixed in Ansible.  Confirmed the problem also exists in Ansible 2.2.2.0.

**Comment by sdodson** [comment]
@mtnbikenc Unfortunately some of these aren't static. All of the services that depend on docker have jinja templates to evaluate.

**Comment by sdodson** [comment]
The node services.

**Comment by mtnbikenc** [comment]
@sdodson Yeah, thanks for pointing that out.  I'll fix the node service files.  I'm still running into this problem and there has been a lot of churn on search path resolution, even recently.

https://github.com/ansible/ansible/commit/ec05cd63367e052e64bd3a2a3d4b2f616ee05fd0

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by ashcrow** [comment]
This looks unrelated to me. Looking for a flake.

```
2017-05-15 16:26:30,316 - taskrunner - ERROR - Caught exception while running 'GetNodes'
Traceback (most recent call last):
  File "/home/jenkins/shiningpanda/jobs/26eaa329/virtualenvs/d41d8cd9/lib/python2.7/site-packages/taskrunner/main.py", line 144, in _run_tasks
    task.run(context)
  File "/home/jenkins/workspace/openshift-ansible-test-matrix/CONTAINERIZED/_NOT_containerized/OSE_VER/3.6/PYTHON/System-CPython-2.7/TOPOLOGY/openshift-cluster/TargetBranch/master/nodes/openshift-ansible-slave/ci-factory/tasks/get_nodes_task.py", line 280, in run
    desc = self.create_nodes(names)
  File "/home/jenkins/workspace/openshift-ansible-test-matrix/CONTAINERIZED/_NOT_containerized/OSE_VER/3.6/PYTHON/System-CPython-2.7/TOPOLOGY/openshift-cluster/TargetBranch/master/nodes/openshift-ansible-slave/ci-factory/tasks/get_nodes_task.py", line 337, in create_nodes
    vms = self._boot_nodes(names)
  File "/home/jenkins/workspace/openshift-ansible-test-matrix/CONTAINERIZED/_NOT_containerized/OSE_VER/3.6/PYTHON/System-CPython-2.7/TOPOLOGY/openshift-cluster/TargetBranch/master/nodes/openshift-ansible-slave/ci-factory/tasks/get_nodes_task.py", line 415, in _boot_nodes
    user_data=user_data)
  File "/home/jenkins/workspace/openshift-ansible-test-matrix/CONTAINERIZED/_NOT_containerized/OSE_VER/3.6/PYTHON/System-CPython-2.7/TOPOLOGY/openshift-cluster/TargetBranch/master/nodes/openshift-ansible-slave/ci-factory/tasks/nodefactory.py", line 104, in boot_node
    raise Exception('An unexpected exception has '
Exception: An unexpected exception has been encountered
```

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
[merge]

**Pull request merged**
