### PR TITLE
Bug 1816959: [release-4.3] Use oc_csr_approve Ansible module for CSR approval

### PR DESCRIPTION
**Pull request by jcpowermac**
Cherry pick: https://github.com/openshift/openshift-ansible/pull/12136

### CODE REVIEW

**Comment by mtnbikenc** [comment]
The scaleup step in CI passed and I've tested this on a 4.3 dev cluster build.
/lgtm

Need to hold until CI issues are resolved.
/hold

**Comment by mtnbikenc** [comment]
CI should be fixed with a new runc package.
/hold cancel
/retest

**Comment by russellb** [comment]
Hi, there!  (reviewing some backports as patch manager here ...)

I had a bit of feedback on the structure of this PR to take into account for the future.

I would appreciate some more detail in the commit message for the main change here.  At first it looked like a new feature to me.  By looking to the bug, I see that these changes are to fix a failure, but it's not obvious.  When deciding if this looks appropriate for a backport, I'd hope to find details about the problem and why these changes fix that problem in the commit message.

It would also be better to split unrelated changes into separate PRs,  It was a little surprising to see the travis-ci changes, for example.

**Pull request merged**
