### PR TITLE
[3.6] etcd upgrade: move validate_etcd_conf.yml to etcd_upgrade role

### PR DESCRIPTION
**Pull request by vrutkovs**
Follow-up for #7781, moves config yaml to the etcd_upgrade role.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1567857

No cherrypick required for 3.7+ branches, as these use `etcd` role for upgrade

### CODE REVIEW

**Comment by sdodson** [comment]
@michaelgugino In release-3.7 there is no etcd_upgrade role where as in release-3.6 there is and that's where the majority of the changes in #7781 were made but the file referenced here is in the wrong role. It wasn't backported proplery.

@vrutkovs I think maybe you forgot to add roles/etcd_upgrade/tasks/validate_etcd_conf.yml to your commit? this only has deletion of the bad file rather than moving to the proper path.

**Comment by vrutkovs** [comment]
Ugh, indeed, my fault

**Comment by michaelgugino** [comment]
@vrutkovs Is there something calling this task_file that is currently failing?  How is this supposed to be executed?

**Comment by sdodson** [comment]
@michaelgugino it's called here https://github.com/openshift/openshift-ansible/pull/7781/files#diff-93f3128ff64af28c7c6ebb47e792aaacR23

**Pull request merged**
