### PR TITLE
Enforce connection: local and become: no on all localhost plays

### PR DESCRIPTION
**Pull request by detiber**

### CODE REVIEW

**Comment by detiber** [comment]
@twiest created this to avoid unpredictable behavior we've seen around using host: localhost without specifying connection: local and become: no for plays against localhost.

**Comment by detiber** [comment]
@wshearn ptal

**Comment by detiber** [comment]
@brenton ptal

**Comment by brenton** [comment]
Seems reasonable to me.

**Comment by detiber** [comment]
@twiest @wshearn any objections to this?

**Comment by twiest** [comment]
@detiber We have seen weird behavior in the past with this, so although I hate having to specify that for each playbook, it's probably the right thing to do.

begrudging   :+1:     :)

**Pull request merged**
