### PR TITLE
Refactor of openshift_version.

### PR DESCRIPTION
**Pull request by kwoodson**

### CODE REVIEW

**Comment by kwoodson** [comment]
The main idea behind this PR is removing the openshift_version dependencies.  The openshift_version role is run inside of the `openshift-ansible/playbooks/common/openshift_cluster/std_include.yml` as the initialize_openshift_version.yml.

Once this role is run all of the variables that this role sets are defined and there is no longer a need to run it again.  I have also removed docker and docker_facts as dependencies to this role.  The only place that does run a docker command is in the containerized version.  I believe it is safe to assume that we have docker installed if you are running a containerized install.  If this is a poor assumption then we need to rethink we how std_include.yml and our required software is laid down.  The very next task after std_include.yml is the openshift_health_checker which then validates a lot of options, installed software, and other fail worth items.  I'd vote the validation move to that area if needed.

**Comment by kwoodson** [comment]
Investigating the atomic failure.  Appears that we need to call openshift_docker_facts.  I'll revert the files that are required in meta/main.yml for openshift_version and test.

**Comment by kwoodson** [comment]
aos-ci-test

**Comment by tbielawa** [comment]
I can +1 this worked for my simple use case. 1 single-host all-in-one install.

Before (latest master):
* OK: 694 
* Skipped: 3089

After (this branch):
* OK: 643
* Skipped: 2083

**Comment by kwoodson** [comment]
@sdodson, here is another refactor I think is valuable.

**Comment by kwoodson** [comment]
[merge]

**Comment by kwoodson** [comment]
[test]

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
needs aos-ci-test before merge would pass

**Comment by kwoodson** [comment]
@sdodson, this passed all other tests except this one test_pull_request_openshift_ansible_extended_conformance_install_with_status_check and that failed with this error message.
```
Failure summary:

  1. Host:     10.8.171.25
     Play:     Verify Requirements
     Task:     openshift_health_check
     Message:  One or more checks failed
     Details:  check "docker_image_availability":
               One or more required Docker images are not available:
                   registry.ops.openshift.com/openshift3/ose-haproxy-router:v3.6
               Configured registries: XXXXXXXXXXXXXXXXXXXXXXXXXXX, registry.ops.openshift.com

  2. Host:     10.8.171.244
     Play:     Verify Requirements
     Task:     openshift_health_check
     Message:  One or more checks failed
     Details:  check "docker_image_availability":
               One or more required Docker images are not available:
                   registry.ops.openshift.com/openshift3/ose-haproxy-router:v3.6
               Configured registries: XXXXXXXXXXXXXXXXXXXXXXXXXXX, registry.ops.openshift.com

  3. Host:     10.8.171.247
     Play:     Configure nodes
     Task:     openshift_node_certificates : fail
     Message:  CA certificate /etc/origin/master/ca.crt doesn't exist on CA host 10.8.171.25. Apply 'openshift_ca' role to 10.8.171.25.
```

This seems unrelated.

**Comment by sdodson** [comment]
aos-ci-test

**Comment by kwoodson** [comment]
@sdodson, thanks for watching this one.  This is looking much better.  The one that is marked failure is from the previous failures.  Does that update on its own?

**Comment by sdodson** [comment]
Should be fine to add the merge tag if you're ready.

**Comment by kwoodson** [comment]
[merge]

**Pull request merged**
