### PR TITLE
 Keep .yaml file convention 

### PR DESCRIPTION
**Pull request by xandradx**
NOTICE
======

Master branch is closed! A major refactor is ongoing in devel-40.
Changes for 3.x should be made directly to the latest release branch they're
relevant to and backported from there.

### CODE REVIEW

**Comment by vrutkovs** [comment]
Interesting, other roles are using `yml`, so it probably would be best to convert other tasks in `openshift_ovirt` role instead

**Comment by vrutkovs** [comment]
@rgolangh WDYT?

**Comment by rgolangh** [comment]
My only concern is people who import the task in manually, which I don't know how many like that there are. I too want to keep the yaml convension and not yml. 

BTW I didn't know this 3.11 branch still accepts prs. I have some more I need you to approve.

**Comment by xandradx** [comment]
> My only concern is people who import the task in manually, which I don't know how many like that there are. I too want to keep the yaml convension and not yml.
> 
> BTW I didn't know this 3.11 branch still accepts prs. I have some more I need you to approve.

Actually the original PR was made to the master branch, check  [main.yaml](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_ovirt/tasks/main.yaml.

In this file you include the .yaml file but the file is .yml so the role it's broken if you just tried to use it from that branch.

**Comment by mtnbikenc** [comment]
The file extension was fixed for the include_task in https://github.com/openshift/openshift-ansible/pull/10805/files#diff-04c084ec5112c027a829f9c9744b4997 for 3.11.

There are twice as many uses of ".yml" as "*.yaml" in roles files for this project.  Either works however consistency is preferred within a role.  Given the other files in this role are .yaml (except for defaults/main.yml) I'm fine with changing to .yaml.

I've had to write plenty of test logic around handling both .yml and .yaml.

**Comment by DanyC97** [comment]
@mtnbikenc regarding

> I've had to write plenty of test logic around handling both .yml and .yaml.

are you able to point me to any tests which do check around the `yaml` vs `yml` ? just curious, nothing else

**Comment by mtnbikenc** [comment]
@DanyC97 
> are you able to point me to any tests which do check around the `yaml` vs `yml` ? just curious, nothing else

In this repo, `setup.py` has several Ansible checks which needed to be yaml/yml agnostic, using `ya?ml$`.  I have another tool which would generate diagrams of playbooks, and the yaml/yml issue was much more problematic for that use case.  There are cases where include_role or include_tasks was used and the filename provided didn't include any extension.  Ansible would automatically look for yaml/yml extensions if the target file was not found.  I had to write that checking into the diagraming tool.

**Comment by mtnbikenc** [comment]
Please reopen after addressing the comments and rebasing.
/close

**Pull request closed without merging**
