### PR TITLE
tag fix without ose-

### PR DESCRIPTION
**Pull request by cooktheryan**
incorrect tag when trying to deploy efs

### CODE REVIEW

**Comment by vrutkovs** [comment]
Flakes

/retest

**Comment by cooktheryan** [comment]
@vrutkovs one of these times i feel like testing will work in our favor

**Comment by vrutkovs** [comment]
Fffffffflakes!

/retest

**Comment by cooktheryan** [comment]
@vrutkovs I'm going to make a sacrifice of snacks from the snack room to please the ci system

**Comment by vrutkovs** [comment]
CI apparently overate @cooktheryan's snacks yesterday

/retest

**Comment by cooktheryan** [comment]
@vrutkovs looks like we are getting closer

**Pull request merged**
