### PR TITLE
logging: write ES heap dump to persistent storage

### PR DESCRIPTION
**Pull request by wozniakjan**
Sets elastic search heap dump to persistent storage

### CODE REVIEW

**Comment by ewolinetz** [comment]
@wozniakjan is there a required update in origin-aggregated-logging that goes with this change?

**Comment by wozniakjan** [comment]
@ewolinetz yes, this PR https://github.com/openshift/origin-aggregated-logging/pull/486

**Comment by ewolinetz** [comment]
This is part of the fix for https://bugzilla.redhat.com/show_bug.cgi?id=1369914

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
[merge]

**Comment by ewolinetz** [comment]
flaked on https://github.com/openshift/origin/issues/14043
[merge]

**Comment by ewolinetz** [comment]
flaked on https://github.com/openshift/origin/issues/14523
[merge]

**Comment by sdodson** [comment]
[test]

**Pull request merged**
