### PR TITLE
Backport GlusterFS storage for v1.5

### PR DESCRIPTION
**Pull request by chinacoolhacker**
Backport GlusterFS storage for v1.5

### CODE REVIEW

**Comment by chinacoolhacker** [comment]
It was tested at my 3-masters cluster and it works fine, so, please, check.

**Comment by chinacoolhacker** [comment]
bot, test pull request

**Comment by michaelgugino** [comment]
@chinacoolhacker We don't typically backport such large features into release branches.  The master branch and 3.6 release branch can both deploy version 1.5.  I think that would be a better fit for utilizing glusterfs with 1.5.

**Comment by chinacoolhacker** [comment]
@michaelgugino Sorry, but i cant find templates for 1.5 here
https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_storage_glusterfs/files and https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_storage_glusterfs/templates here, so i'm not sure, but looks like ansible will fail to find them according to 'openshift.common.examples_content_version' option in task.

**Comment by michaelgugino** [comment]
@chinacoolhacker 

That does appear to be the case.  Would you be willing to try to add the necessary files for 1.5 to work in the master branch?  I think that PR would be much smaller, and we can probably merge that.

**Comment by chinacoolhacker** [comment]
@michaelgugino Ok, this is a new PR https://github.com/openshift/openshift-ansible/pull/5867

**Comment by michaelgugino** [comment]
Closed in favor of PR #5867

**Pull request closed without merging**
