### PR TITLE
Enable pullthrough by default in registry config for object storage.

### PR DESCRIPTION
**Pull request by abutcher**

### CODE REVIEW

**Comment by detiber** [comment]
This option should probably be toggle-able.

**Comment by abutcher** [comment]
@detiber Sounds good. I'll make this disabled by default with a toggle on var.

**Comment by detiber** [comment]
@abutcher I think having the default being enabled is fine, we just should have a way for someone to disable it.

**Comment by abutcher** [comment]
aos-ci-test

**Comment by abutcher** [comment]
@sdodson ptal

**Comment by sdodson** [comment]
LGTM

**Pull request merged**
