### PR TITLE
Restart masters post reconcile

### PR DESCRIPTION
**Pull request by detiber**
addresses https://github.com/openshift/openshift-ansible/issues/813

@sdodson @dgoodwin

### CODE REVIEW

**Comment by sdodson** [comment]
LGTM, thanks.

**Comment by detiber** [comment]
@sdodson @dgoodwin One thing I just thought of...  We aren't doing any special handling in the case of 3.0.z HA installs...  we shouldn't be using the service module to manipulate the service in that scenario, we should be using the pcs tool on the first master instead.

**Comment by dgoodwin** [comment]
Thanks! Checking this off the upgrade card.

**Comment by detiber** [comment]
@dgoodwin added some of the re-ordering and cleanup I discussed on the previous commit.  Working on generating those missing certs now.

**Comment by dgoodwin** [comment]
This looks good to me. I am working on the embedded vs non etcd grouping issue in a separate PR which has merged this work in already.

**Pull request closed without merging**
