### PR TITLE
Remove all references to pacemaker (pcs, pcsd) and openshift.master.cluster_method.

### PR DESCRIPTION
**Pull request by abutcher**
With pacemaker removed there is no longer a need for
`openshift.master.cluster_method`. We only have one option.

https://trello.com/c/xHdqzFee/524-2-remove-openshiftmastercluster-role-pacemaker

### CODE REVIEW

**Comment by mtnbikenc** [comment]
Rebased again
/lgtm

**Comment by sdodson** [comment]
last install failure was a flake

**Pull request merged**
