### PR TITLE
[3.10] Refactor image health checks

### PR DESCRIPTION
**Pull request by michaelgugino**
This commit refactors image health checks to be more in line
with how images are actually pulled in 3.10+.

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1613100
(cherry picked from commit f4ad0aad0ba06e4f265c24b7ab278725b413b531)

Backports: https://github.com/openshift/openshift-ansible/pull/9827

### CODE REVIEW

**Comment by michaelgugino** [comment]
I don't see a reason for install job to keep failing.  Probably the image is missing CA certs, so it's refusing to connect, but how we currently do this checks we don't get any good output. as to what the actual problem is.

**Comment by sdodson** [comment]
/hold
until QE has validated 3.11 bug

**Comment by michaelgugino** [comment]
/hold cancel

3.11 bug verified by qe.

**Pull request merged**
