### PR TITLE
Grafana: oauth-proxy for OCP deployments should default to openshift_image_tag

### PR DESCRIPTION
**Pull request by vrutkovs**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1579415

### CODE REVIEW

**Comment by michaelgugino** [comment]
This is all being changed in my patch set.  After it merges, we can adjust grafana version in appropriate new variable.

**Comment by vrutkovs** [comment]
Not needed after https://github.com/openshift/openshift-ansible/pull/8489 was merged

**Pull request closed without merging**
