### PR TITLE
Bug 1939605: crio: set manage_network_ns_lifecycle to true

### PR DESCRIPTION
**Pull request by haircommander**
should fix https://bugzilla.redhat.com/show_bug.cgi?id=1939605

Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Comment by haircommander** [comment]
/hold

we'll want some validation against this to make sure we don't regress.

**Comment by nee1esh** [comment]
@haircommander are we ready to remove hold on this?

**Comment by mtnbikenc** [comment]
FYI, builds are failing because of python package dependency issues.  Feel free to update [Dockerfile](https://github.com/openshift/openshift-ansible/blob/release-3.11/images/installer/Dockerfile).  I'm guessing upgrading `pip` will help some (and remove the need for some of the recent version pinning) and some python packages may need to be move to `pip install` because the versions in the CentOS repo are so old.

**Comment by haircommander** [comment]
I would like to verify it's actually needed. ideally, someone would just add this line if they need it, and I don't know if it'll be worth making the change for everyone

**Comment by haircommander** [comment]
going forward with https://github.com/openshift/openshift-ansible/pull/12316/ instead

**Pull request closed without merging**
