### PR TITLE
[release-3.10] Update tox test environment vars

### PR DESCRIPTION
**Pull request by mtnbikenc**
Adds Ansible environment vars required to change Ansible to use /tmp
instead of user home.

Backports #11631

### CODE REVIEW

**Comment by mtnbikenc** [comment]
```
[Fail] [Conformance][Area:Networking][Feature:Router] The HAProxy router [It] should expose prometheus metrics for a route [Suite:openshift/conformance/parallel] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/router/metrics.go:202
```

**Comment by mtnbikenc** [comment]
web console deployment failed
`failed pulling image \"openshift/origin-pod:v3.9.0\`
Why is it pulling 3.9.0?

**Comment by vrutkovs** [comment]
>Why is it pulling 3.9.0?

Upgrade scenario sets up 3.9 and upgrades it to 3.10. But due to Cloudflare outage Dockerhub is not accessible :/

**Pull request merged**
