### PR TITLE
enable service-serving-cert-signer by default

### LINKED ISSUE #2345: enable service-serving-cert-signer by default
Commands like `oadm router` want to take advantage of the service-serving-cert-signing controller.  This requires that 
```yaml
controllerConfig:
  serviceServingCert:
    signer:
      certFile: service-signer.crt
      keyFile: service-signer.key
```

in the master-config.yaml be configured with a signer.  This signs for internal DNS names and can be created using a command like:

```bash
oadm ca create-signer-cert --cert=service-signer.crt --key=service-signer.key --serial=service-signer-serial.txt
```

https://github.com/openshift/openshift-docs/pull/2324 has docs about using it.

### PR DESCRIPTION
**Pull request by abutcher**
Fixes #2345
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1366975

### CODE REVIEW

**Comment by abutcher** [comment]
@sdodson PTAL

**Comment by sdodson** [comment]
LGTM

**Comment by sdodson** [comment]
aos-ci-test

**Comment by abutcher** [comment]
aos-ci-test

**Pull request merged**
