### PR TITLE
Add cloudprovider config dir to docker options.

### PR DESCRIPTION
**Pull request by abutcher**
Adds `/etc/origin/cloudprovider` volume mount when cloudprovider options have been set.

### CODE REVIEW

**Comment by abutcher** [comment]
@detiber ptal

**Comment by detiber** [comment]
lgtm

**Comment by abutcher** [comment]
@brenton

**Comment by abutcher** [comment]
@brenton Should be good to merge

**Comment by brenton** [comment]
aos-ci-test

**Comment by detiber** [comment]
:shipit:

**Pull request merged**
