### PR TITLE
Pause for console rollout

### PR DESCRIPTION
**Pull request by spadgett**
/assign @sdodson

### CODE REVIEW

**Comment by spadgett** [comment]
@sdodson Opinion on this change? This should at least mitigate the risk of verifying the console is running before the new rollout starts.

I'm not in love with an arbitrary wait, but I'm not what else we can check. If there are no changes to the deployment, a new revision isn't created.

**Comment by sdodson** [comment]
I can't come up with a better solution, is 10s usually long enough for the existing pod to stop responding to requests?

**Comment by spadgett** [comment]
@sdodson I could make it something more conservative.

It's a recreate deployment, so it will delete the old pods before creating any new ones. If we ever switch to rolling, we might need to revisit this.

**Comment by spadgett** [comment]
Updated to 30s

**Comment by spadgett** [comment]
yum error

/test gcp

**Pull request merged**
