### PR TITLE
Remove policy in favor of role bindings.

### PR DESCRIPTION
**Pull request by kwoodson**

### CODE REVIEW

**Comment by kwoodson** [comment]
aos-ci-test

**Comment by kwoodson** [comment]
aos-ci-test

**Comment by enj** [comment]
Fixes #4880

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
After making some serious hacks to openshift-ansible to avoid attempting to install any rpms I've 
 - Starting with an operational 3.6 install
 - Dump etcd data
 - Deploy custom build
 - Run playbooks, confirmed the same failures reported
 - Merged this PR
 - Run playbooks, confirmed success

I need to test a clean install w/ this but aos-ci-test should do that too.

**Comment by sdodson** [comment]
[merge]

**Comment by sdodson** [comment]
[merge]

**Pull request merged**
