### PR TITLE
XPAAS v1.3 content

### PR DESCRIPTION
**Pull request by sdodson**

### CODE REVIEW

**Comment by sdodson** [comment]
@rcernich can you take a look at this. The processerver62 stuff was removed correct? GIT is detecting that removal as a rename, I guess because the files are similar enough that it considers them to have just been renamed? Do we need to do anything to remove those templates from old installs during an upgrade?

```
 rename roles/openshift_examples/files/examples/v1.2/xpaas-templates/{processserver62-mysql-s2i.json => sso70-mysql-persistent.json} (72%)
 rename roles/openshift_examples/files/examples/v1.2/xpaas-templates/{processserver62-mysql-persistent-s2i.json => sso70-mysql.json} (66%)
 rename roles/openshift_examples/files/examples/v1.2/xpaas-templates/{processserver62-postgresql-persistent-s2i.json => sso70-postgresql-persistent.json} (71%)
 rename roles/openshift_examples/files/examples/v1.2/xpaas-templates/{processserver62-postgresql-s2i.json => sso70-postgresql.json} (69%)
```

**Comment by rcernich** [comment]
@sdodson we've never released the process server templates, but they were in our master branch, as they were being worked on in parallel, but won't be released until the next xpaas release, 1.3.1, so I removed them before tagging.  That said, it looks like the sso templates were created from the process server templates maybe?  I'm not sure why the diff is showing up like that.

**Comment by sdodson** [comment]
@rcernich Ok, thanks. Are you fine with us merging this?

**Comment by rcernich** [comment]
yep!

**Comment by sdodson** [comment]
@brenton ready

**Comment by brenton** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Pull request merged**
