### PR TITLE
Use openshift-clients package name

### PR DESCRIPTION
**Pull request by mtnbikenc**

### CODE REVIEW

**Comment by sdodson** [comment]
/lgtm cancel
We need to update other package names too to account for this and I think we can get rid of `{{{ openshift_service_type }}}`

https://github.com/openshift/openshift-ansible/blob/devel-40/roles/openshift_node40/tasks/install.yml#L21-L23

**Comment by mtnbikenc** [comment]
@sdodson I'll get this updated.
/lgtm cancel

**Comment by mtnbikenc** [comment]
Cluster setup failed.
/retest

**Pull request merged**
