### PR TITLE
Correct openshift_release regular expression

### PR DESCRIPTION
**Pull request by mtnbikenc**
Match only versions like:
3.7
3.7.0
3.7.0.0

Avoids matches like:
3.7.0.0.0.0

### CODE REVIEW

**Comment by mtnbikenc** [comment]
Flake https://github.com/openshift/origin/issues/16005
/test logging

**Comment by mtnbikenc** [comment]
Docker registry flake
/test containerized

**Comment by tbielawa** [comment]
```
$ grep openshift_release hosts-local-openshift_release                                                 
openshift_release=v3.7.a.b
```

And running this branch:

```
$ ansible-playbook -vv -i hosts-local-openshift_release playbooks/byo/config.yml
...
TASK [openshift_sanitize_inventory : Abort when openshift_release is invalid] ***************************************************************************************************************************************
task path: /home/tbielawa/rhat/os/openshift-ansible/roles/openshift_sanitize_inventory/tasks/main.yml:47
Friday 27 October 2017  10:28:46 -0400 (0:00:00.096)       0:00:07.718 ********
fatal: [m01.example.com]: FAILED! => {"changed": false, "failed": true, "msg": "openshift_release is \"3.7.a.b\" which is not a valid version string.\nPlease set it to a version string like \"3.4\"."}
... [ for each other host as well ]
```

Push it to the edge of almost acceptable with `openshift_release=v3.7.0.0.0` (that's one extra dot-zero)

```
openshift_release is \"3.7.0.0.0\" which is not a valid version string.\nPlease set it to a version string like \"3.4\"
```

really weird "openshift_release=v3.7.`" (dot-backtick). Also fails

four dotted-digits (`3.7.0.1`) works

```
TASK [openshift_sanitize_inventory : Abort when openshift_release is invalid] ***************************************************************************************************************************************
task path: /home/tbielawa/rhat/os/openshift-ansible/roles/openshift_sanitize_inventory/tasks/main.yml:47
Friday 27 October 2017  10:32:27 -0400 (0:00:00.092)       0:00:11.956 ********
skipping: [m01.example.com] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}
skipping: [n01.example.com] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}
skipping: [n02.example.com] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}
```

/lgtm

**Comment by tbielawa** [comment]
heh. Even caught `b3.7.0.1` :+1: 

```
TASK [openshift_sanitize_inventory : Normalize openshift_release] ***************************************************************************************************************************************************
task path: /home/tbielawa/rhat/os/openshift-ansible/roles/openshift_sanitize_inventory/tasks/main.yml:37
Friday 27 October 2017  10:34:47 -0400 (0:00:00.087)       0:00:04.302 ******** 
ok: [m01.example.com] => {"ansible_facts": {"openshift_release": "b3.7.0.1"}, "changed": false, "failed": false}
ok: [n01.example.com] => {"ansible_facts": {"openshift_release": "b3.7.0.1"}, "changed": false, "failed": false}
ok: [n02.example.com] => {"ansible_facts": {"openshift_release": "b3.7.0.1"}, "changed": false, "failed": false}

TASK [openshift_sanitize_inventory : Abort when openshift_release is invalid] ***************************************************************************************************************************************
task path: /home/tbielawa/rhat/os/openshift-ansible/roles/openshift_sanitize_inventory/tasks/main.yml:47
Friday 27 October 2017  10:34:47 -0400 (0:00:00.090)       0:00:04.392 ******** 
fatal: [m01.example.com]: FAILED! => {"changed": false, "failed": true, "msg": "openshift_release is \"b3.7.0.1\" which is not a valid version string.\nPlease set it to a version string like \"3.4\"."}
fatal: [n01.example.com]: FAILED! => {"changed": false, "failed": true, "msg": "openshift_release is \"b3.7.0.1\" which is not a valid version string.\nPlease set it to a version string like \"3.4\"."}
fatal: [n02.example.com]: FAILED! => {"changed": false, "failed": true, "msg": "openshift_release is \"b3.7.0.1\" which is not a valid version string.\nPlease set it to a version string like \"3.4\"."}
```

**Comment by mtnbikenc** [comment]
All tests passed except containerized.

**Pull request merged**
