### PR TITLE
[RHDM-354] - Add RHDM 7.0 GA templates and image streams to Openshift…

### PR DESCRIPTION
**Pull request by spolti**
… service catalog

Signed-off-by: Filippe Spolti <fspolti@redhat.com>

### CODE REVIEW

**Comment by spolti** [comment]
Hi, @bparees, by executing the script with the default config the templates were copied to v3.9 directory, to add the templates for ocp 3.7 and 3.8, do I need to execute the example_sync script tagging this versions or it will be automatically imported?

**Comment by bparees** [comment]
we're not going to add them to 3.7 and 3.8.
we're not even going to add them to 3.9 (we're well past featurecut on 3.9).

I need @rettori and @sspeiche to sign off on this PR to confirm we intend to ship these out of the box with OCP, but I would not expect us to do so until 3.10 at this point.

**Comment by sspeiche** [comment]
+1 from me, I leave it to @rettori to confirm

**Comment by rettori** [comment]
Let's target 3.10 and instruct product team to provide instructions on how to enable it on earlier releases.

D.

**Comment by bparees** [comment]
@spolti can you redo this PR to target the v3.10 folder?

**Comment by spolti** [comment]
@bparees Sure.

**Comment by bparees** [comment]
@spolti did you intentionally remove your changes to the sync script?

**Comment by spolti** [comment]
@bparees I forgot to add the script in the commit, just updated the pr, thanks.

**Comment by bparees** [comment]
lgtm. @sdodson ?

**Comment by sdodson** [comment]
Yup, looks fine, thanks.

bot, test pull request
/ok-to-test
/lgtm

**Pull request merged**
