### PR TITLE
[release-3.11] Add readiness + liveness probes for Service Catalog

### PR DESCRIPTION
**Pull request by jboyd01**
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1630324

### CODE REVIEW

**Comment by sdodson** [comment]
/lgtm
Is there suspicion that this would alleviate some of the problems during restarts/upgrades?

**Comment by jboyd01** [comment]
> Is there suspicion that this would alleviate some of the problems during restarts/upgrades?
I wish.  These should have been in here from the beginning, I'm unable to find a reason why they were not.  In the associated PR the customer realized they were missing after hitting an issue where Catalog would become unresponsive.  I'm just doing some final verification testing with these right now. 

re: restart/upgrade - that is next on my list, will be starting on that this afternoon.

**Comment by sdodson** [comment]
Nevermind, was already picked here https://github.com/openshift/openshift-ansible/pull/10629

**Pull request merged**
