### PR TITLE
Clarified scaling docs, combining master/infra/app sections

### PR DESCRIPTION
**Pull request by tzumainn**
After the recent update to master scaling, the process of scaling infra/app nodes changed. This change updates the documentation to reflect that.

### CODE REVIEW

**Comment by tzumainn** [comment]
@tomassedovic Could you take a look? I tested by scaling infra nodes using the procedure described in this update.

**Comment by tomassedovic** [comment]
Awesome! Thanks @tzumainn and sorry I forgot to do that on my own PR.

**Pull request merged**
