### PR TITLE
crio: ensure we are logged in to the registry

### PR DESCRIPTION
**Pull request by giuseppe**
Closes: https://github.com/openshift/openshift-ansible/issues/7177

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by sjenning** [comment]
/lgtm
/assign sdodson 
fyi @runcom

**Comment by runcom** [comment]
Awesome!!LGTM

**Comment by sjenning** [comment]
/hold
I was in the middle of a redeployment attempt with the following in my inventory
```
openshift_use_crio: true
openshift_crio_systemcontainer_image_override: registry.reg-aws.openshift.com/openshift3/cri-o:v3.9
```
I was expecting it would fail without this patch like it failed last night, but the prereq playbook completed successfully.  So... I don't know what is going on.

**Comment by sjenning** [comment]
Not sure what happened the first time I ran this, but the original issue isn't happening anymore.  I don't think this fix is required.  Sorry for the noise :-/

**Pull request closed without merging**
