### PR TITLE
Update imageConfig.format on upgrades to match oreg_url

### PR DESCRIPTION
**Pull request by sdodson**
If someone (like @jhadvig) had updated oreg_url value when upgrading we should update that.

### CODE REVIEW

**Comment by jhadvig** [comment]
Tested the change with the upgrade playbook and the format is updated correctly now.
Thanks @sdodson :+1:

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Comment by sdodson** [comment]
flake https://github.com/openshift/origin/issues/9999
[merge]

**Pull request merged**
