### PR TITLE
[release-3.9]: Update doc link on the etcd embedded group validation message

### PR DESCRIPTION
**Pull request by DanyC97**
Fixes https://github.com/openshift/openshift-ansible/issues/9838

### CODE REVIEW

**Comment by DanyC97** [comment]
@vrutkovs pls help review, thanks

**Comment by vrutkovs** [comment]
y u no start with master?

**Comment by DanyC97** [comment]
@vrutkovs the reason i haven't started with the normal process: master -> 3.10 -> 3.9 is because in 3.10 + we no longer have the same task in ` playbooks/init/evaluate_groups.yml` (i wasn't trying to be a bad boy and shortcut ;) )

as such i think is fair to say this PR will/ is required only for 3.9 branch, you agree ?

**Comment by vrutkovs** [comment]
Oh, okay. We'll need master PR (cherrypicked to 3.10 then)

**Comment by DanyC97** [comment]
@vrutkovs so as discussed please cancel the cherry pick and i'll fire 2new PRs.

**Pull request merged**
