### PR TITLE
Dockerfile.rhel7: simplify pkg install

### PR DESCRIPTION
**Pull request by vrutkovs**
PTAL @sosiouxme

### CODE REVIEW

**Comment by sdodson** [comment]
/lgtm
/hold
Lets wait until we merge into master though.

**Comment by mtnbikenc** [comment]
/retest
```
level=debug msg="Still waiting for the cluster to initialize: Working towards 0.0.1-2019-03-22-165410: 66% complete"
level=fatal msg="failed to initialize the cluster: timed out waiting for the condition"
```

**Pull request merged**
