### PR TITLE
Remove dns role

### PR DESCRIPTION
**Pull request by michaelgugino**
This commit removes openshift_facts dependency from dns role.

### CODE REVIEW

**Comment by ashcrow** [comment]
aos-ci-test

**Comment by ashcrow** [comment]
[merge]

**Comment by michaelgugino** [comment]
Yeah, looks like this role is now unused after the bin/cluster parts have been removed.

I think we should just remove this role and it's dependencies.  Thoughts?

**Comment by mtnbikenc** [comment]
As pointed out by @sdodson, the `dns` role is no longer in use and could be completely removed from the repo.  I searched through the branches and the last I found it was used is in release-1.2 by the openstack playbooks.

**Comment by kwoodson** [comment]
@michaelgugino, feel free to remove the role.

**Comment by michaelgugino** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
Flake openshift/origin#16005 'wait_for_fluentd_to_catch_up'
[merge]

**Comment by kwoodson** [comment]
Flake openshift/origin#16005

**Comment by kwoodson** [comment]
[merge] in separate comments.

**Comment by ashcrow** [comment]
[merge]

**Comment by ashcrow** [comment]
If this flakes again @kwoodson or I will manually merge this PR.

**Pull request merged**
