### PR TITLE
Move repo and subscribe to prerequisites

### PR DESCRIPTION
**Pull request by michaelgugino**
This commit refactors some steps in rhel subscribe and
moves repos.yml from init/main to prerequisites.

### CODE REVIEW

**Comment by kwoodson** [comment]
I think we should consolidate on one variable for each as @michaelgugino is doing here.  I'd prefer not to have 2 or more variables for the same data.

**Comment by sdodson** [comment]
> I think we should consolidate on one variable for each as @michaelgugino is doing here. I'd prefer not to have 2 or more variables for the same data.

Yup, consolidate, but prefer the old variables that were defined prior to #6404

**Comment by sdodson** [comment]
install completed, merging to unblock the queue

**Pull request merged**
