### PR TITLE
add firewall rules for node exporter

### PR DESCRIPTION
**Pull request by mjudeikis**
Add router and node exporter ports for OSA builds

cc: @openshift/sig-azure

### CODE REVIEW

**Comment by jim-minter** [comment]
@mjudeikis '{"service":"Router stats port", "port":"1936/tcp"}' goes away with https://github.com/jim-minter/azure-helm/pull/78 ?

**Comment by mjudeikis** [comment]
@jim-minter  yes. I didn't believed in #78 yesterday :D

**Comment by mjudeikis** [comment]
@jim-minter updated

**Pull request merged**
