### PR TITLE
Remove unused origin repo

### PR DESCRIPTION
**Pull request by yselkowitz**
Not only does this get us a current openshift-clients, it will be needed for the collections dependencies going forward.

### CODE REVIEW

**Review by barbacbd — COMMENTED** [review]
Do we want to put a hold on this until there is time to discuss or ensure that we are all on the same page going forward? @yselkowitz @jstuever

**Comment by yselkowitz** [comment]
Reworked based on top of https://github.com/openshift/release/pull/30618

**Review by barbacbd — COMMENTED** [review]
/lgtm

**Pull request merged**
