### PR TITLE
Add option to generate a static inventory for Openstack

### PR DESCRIPTION
**Pull request by tzumainn**
This updates OpenStack's inventory.py to allow for the generation of a static inventory in ini format, and updates the documentation explaining how to use it.

### CODE REVIEW

**Comment by tzumainn** [comment]
@luis5tb Whoops, sorry, I only applied my code after the provision step. The error you saw should be fixed now, could you try again?

**Comment by luis5tb** [comment]
@tzumainn: I tested it again, and now it works! Thanks!

**Comment by luis5tb** [comment]
bot, retest this please
/retest

**Comment by tzumainn** [comment]
@luis5tb Apologies again - I fixed some lint errors; could you take another look?

**Comment by tzumainn** [comment]
@luis5tb Sorry, one last time - I had to add a fix for python3, where ConfigParser is configparser instead. But I've verified that the previously failing test now passes!

**Pull request merged**
