### PR TITLE
[WIP] Merge recent changes into enterprise-3.2

### PR DESCRIPTION
**Pull request by sdodson**
Since we've not yet introduced any code that *requires* ansible 2.0/2.1 we'll go ahead and pull everything into enterprise-3.2

### CODE REVIEW

**Comment by sdodson** [comment]
@abutcher as soon as we merge something into master that requires 2.x lets bring this up to date and merge it.

**Comment by sdodson** [comment]
@dgoodwin this will remove the docker-1.10 requirement for 3.2 since it was removed in master. Before we merge this we should decide what the right thing to do for 3.2 is.

**Comment by dgoodwin** [comment]
Hard one, I like the state of master personally, but we can't ignore that Docker 1.10 really should be in place going forward. It's probably correct to keep the 1.10 requirement for 3.2 if we know it will be available by then.

**Comment by sdodson** [comment]
meh, i over-wrote my branch, closing this

**Pull request closed without merging**
