### PR TITLE
Remove papr test files

### PR DESCRIPTION
**Pull request by mtnbikenc**
papr is not used on the master branch

### CODE REVIEW

**Comment by vrutkovs** [comment]
I don't think its being used in any branch anyway

/cherrypick release-3.11

**Comment by mtnbikenc** [comment]
/retest
```
Failing tests:

[sig-storage] In-tree Volumes [Driver: nfs] [Testpattern: Dynamic PV (default fs)] volumes should be mountable [Suite:openshift/conformance/parallel] [Suite:k8s]
```

**Comment by mtnbikenc** [comment]
```
Error creating VPC: VpcLimitExceeded: The maximum number of VPCs has been reached.
```

**Pull request merged**
