### PR TITLE
atomic-openshift-installer: Fix broken nosetest

### PR DESCRIPTION
**Pull request by smunilla**
This is a fix for the failing test_fresh_install_with_config.

### CODE REVIEW

**Comment by abutcher** [comment]
aos-ci-test

**Comment by abutcher** [comment]
Fix for http://paste.fedoraproject.org/302212/

:+1: @sdodson @twiest

**Comment by sdodson** [comment]
:+1: @twiest should be good to merge

**Comment by abutcher** [comment]
@brenton

**Pull request merged**
