### PR TITLE
Upgrade Prometheus AlertManager to v0.14.0

### PR DESCRIPTION
**Pull request by simonpasquier**

### CODE REVIEW

**Comment by simonpasquier** [comment]
@aweiteka @ironcladlou please take a look.

**Comment by simonpasquier** [comment]
@pgier can you have a look too?

**Comment by smarterclayton** [comment]
bot, retest this please

**Comment by sdodson** [comment]
bot, retest this please

**Comment by sdodson** [comment]
Yes, not sure why it's not being marked skipped.

**Comment by simonpasquier** [comment]
@sdodson thanks a lot!

**Pull request merged**
