### PR TITLE
unexclude excluder if it is to be upgraded and already installed

### PR DESCRIPTION
**Pull request by ingvagabund**
Fixes: #3858

### CODE REVIEW

**Comment by ingvagabund** [comment]
aos-ci-test

**Comment by jhadvig** [comment]
@ingvagabund tested your change with the upgrade playbook for 3_6 and it passed with out any errors

**Comment by ingvagabund** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Pull request merged**
