### PR TITLE
[KIECLOUD-292] - Update RHPAM and RHMD templates and imagestreams on …

### PR DESCRIPTION
**Pull request by spolti**
…OpenShift Service Catalog for release 7.4.1

Signed-off-by: Filippe Spolti <fspolti@redhat.com>

### CODE REVIEW

**Comment by spolti** [comment]
@vrutkovs Hi, can you please take a look?

**Comment by spolti** [comment]
Hi @patrickdillon @vrutkovs can this be merged?

**Comment by vrutkovs** [comment]
This should have been fixed by https://github.com/openshift/release/pull/4859

/retest

**Pull request merged**
