### PR TITLE
OCPBUGS-29527: Install ose-aws-ecr-image-credential-provider

### PR DESCRIPTION
**Pull request by sdodson**
This is a new package required since 4.14.11

### CODE REVIEW

**Comment by JoelSpeed** [comment]
/lgtm

Need to see tests pass but I approve of the addition

**Comment by patrickdillon** [comment]
> Looks like those failures are unique to master branch, looking to open 4.15 PR verify it passes there then override here.

4.15 is also permafailing: https://issues.redhat.com/browse/CORS-3271

perhaps we can get pre-merge testing?

**Comment by patrickdillon** [comment]
> > Looks like those failures are unique to master branch, looking to open 4.15 PR verify it passes there then override here.
> 
> 4.15 is also permafailing: https://issues.redhat.com/browse/CORS-3271
> 
> perhaps we can get pre-merge testing?

Actually, it looks possible our permafailing may be due to the bug being fixed here.

>     "start": "2024-02-15 04:48:37.109313",
    "stderr": "Warning: The unit file, source configuration file or drop-ins of kubelet.service changed on disk. Run 'systemctl daemon-reload' to reload units.",
    "stderr_lines": [
        "Warning: The unit file, source configuration file or drop-ins of kubelet.service changed on disk. Run 'systemctl daemon-reload' to reload units."
    ],
    "stdout": "● kubelet.service - Kubernetes Kubelet\n   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)\n  Drop-In: /etc/systemd/system/kubelet.service.d\n           └─01-kubens.conf, 10-mco-default-madv.conf, 20-logging.conf, 20-node-env.conf\n   Active: activating (auto-restart) (Result: exit-code) since Thu 2024-02-15 04:48:35 UTC; 1s ago\n  Process: 6828 ExecStart=/usr/local/bin/kubenswrapper /usr/bin/kubelet --config=/etc/kubernetes/kubelet.conf --bootstrap-kubeconfig=/etc/kubernetes/kubeconfig --kubeconfig=/var/lib/kubelet/kubeconfig --container-runtime-endpoint=/var/run/crio/crio.sock --runtime-cgroups=/system.slice/crio.service --node-labels=node-role.kubernetes.io/worker,node.openshift.io/os_id=${ID} --node-ip=${KUBELET_NODE_IP} --minimum-container-ttl-duration=6m0s --volume-plugin-dir=/etc/kubernetes/kubelet-plugins/volume/exec --cloud-provider=external **--image-credential-provider-bin-dir=/usr/libexec/kubelet-image-credential-provider-plugins --image-credential-provider-config=/etc/kubernetes/credential-providers/ecr-credential-provider.yaml** --hostname-override=${KUBELET_NODE_NAME} --provider-id=${KUBELET_PROVIDERID} --pod-infra-container-image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:6068d844068ad78d7dc11129962fbd562eff5a2b2df82f1342dae2dae1817542 --system-reserved=cpu=${SYSTEM_RESERVED_CPU},memory=${SYSTEM_RESERVED_MEMORY},ephemeral-storage=${SYSTEM_RESERVED_ES} --v=${KUBELET_LOG_LEVEL} (code=exited, status=1/FAILURE)\n  Process: 6827 ExecStartPre=/bin/rm -f /var/lib/kubelet/memory_manager_state (code=exited, status=0/SUCCESS)\n  Process: 6825 ExecStartPre=/bin/rm -f /var/lib/kubelet/cpu_manager_state (code=exited, status=0/SUCCESS)\n  Process: 6823 ExecStartPre=/bin/mkdir --parents /etc/kubernetes/manifests (code=exited, status=0/SUCCESS)\n Main PID: 6828 (code=exited, status=1/FAILURE)\n      CPU: 85ms\n\nFeb 15 04:48:35 ip-10-0-93-44.us-west-1.compute.internal systemd[1]: kubelet.service: Consumed 85ms CPU time",

**Comment by patrickdillon** [comment]
testing 4.15 in #12488

**Comment by sdodson** [comment]
Still lacking crio 1.29 in repos for this job

**Pull request merged**
