### PR TITLE
[devel-40] clean up unused playbooks and roles.

### PR DESCRIPTION
**Pull request by jstuever**
The purpose of this PR is to clean up the playbooks and roles brought over from 3.x that are no longer used by the 4.x code base.

### CODE REVIEW

**Comment by DanyC97** [comment]
@jstuever nice one ! Spring cleaning is coming ;)))

**Comment by vrutkovs** [comment]
Scaleup passes, approving
/lgtm

**Comment by sdodson** [comment]
Appears to be flakes rather than a defect based on the varied tests that are failing.

**Comment by DanyC97** [comment]
💯 🆒    @jstuever

**Pull request merged**
