### PR TITLE
[release-3.7]: Add the ability to specify a timeout for node drain operations

### PR DESCRIPTION
**Pull request by DanyC97**
Cherry-pick https://github.com/openshift/openshift-ansible/pull/5080

@sdodson @michaelgugino @vrutkovs pls help review

### CODE REVIEW

**Comment by DanyC97** [comment]
same situation here @vrutkovs regarding comments made in https://github.com/openshift/openshift-ansible/pull/8429

**Comment by vrutkovs** [comment]
bot, test pull request

**Comment by DanyC97** [comment]
can someone try to re-kick the test pls ?

**Comment by sdodson** [comment]
Yeah, there's even some internal uses for 3.7 still.

**Comment by vrutkovs** [comment]
/approve
/lgtm

Flakes

**Pull request merged**
