### PR TITLE
Update Fuse templates with 7.1 release (3.9)

### PR DESCRIPTION
**Pull request by astefanutti**

### CODE REVIEW

**Comment by astefanutti** [comment]
@sdodson is it still possible to update catalog entries on 3.9 branch?

**Comment by sdodson** [comment]
@astefanutti As long as you can tell me they've been tested in 3.9

**Comment by astefanutti** [comment]
@sdodson I confirm Fuse 7.1 on OpenShift support OS 3.9 (See https://access.redhat.com/articles/310603).

**Comment by sdodson** [comment]
@astefanutti thanks!

**Pull request merged**
