### PR TITLE
aws ami: make it so the tags from the orinal AMI are used with the newly created AMI

### PR DESCRIPTION
**Pull request by mwoodson**

### CODE REVIEW

**Comment by mwoodson** [comment]
@kwoodson @sdodson @jupierce 

This PR attempts to merge the AMI tags from the original AMI into the newly created AMI.

**Comment by sdodson** [comment]
yet another flake
/test gcp

**Comment by sdodson** [comment]
Need https://github.com/openshift/openshift-ansible/pull/7056

**Pull request merged**
