### PR TITLE
[3.6] Backport Add dnf support

### PR DESCRIPTION
**Pull request by ashcrow**
Backport of https://github.com/openshift/openshift-ansible/pull/5101

### CODE REVIEW

**Comment by ashcrow** [comment]
cc @maxamillion

**Comment by ashcrow** [comment]
Forgoing testing due to bot downtime.

**Comment by ashcrow** [comment]
aos-ci-test

**Comment by maxamillion** [comment]
@ashcrow :+1: Thanks!

**Comment by ashcrow** [comment]
Searched for flakes but didn't find them but still unrelated.

```
      "", 
        "\u001b[91m\u001b[1m[Fail] \u001b[0m\u001b[90m[k8s.io] EmptyDir volumes \u001b[0m\u001b[0mwhen FSGroup is specified [Feature:FSGroup] \u001b[0m\u001b[91m\u001b[1m[It] volume on default medium should have the correct mode using FSGroup [Volume] \u001b[0m", 
        "\u001b[37m/builddir/build/BUILD/atomic-openshift-git-0.5d51a23/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/util.go:2183\u001b[0m", 
        "", 
        "\u001b[91m\u001b[1m[Fail] \u001b[0m\u001b[90m[k8s.io] EmptyDir volumes \u001b[0m\u001b[0mwhen FSGroup is specified [Feature:FSGroup] \u001b[0m\u001b[91m\u001b[1m[It] files with FSGroup ownership should support (root,0644,tmpfs) [Volume] \u001b[0m", 
        "\u001b[37m/builddir/build/BUILD/atomic-openshift-git-0.5d51a23/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/util.go:2183\u001b[0m", 
        "", 
        "\u001b[91m\u001b[1m[Fail] \u001b[0m\u001b[90m[k8s.io] EmptyDir volumes \u001b[0m\u001b[91m\u001b[1m[It] should support (root,0666,tmpfs) [Conformance] [Volume] \u001b[0m", 
        "\u001b[37m/builddir/build/BUILD/atomic-openshift-git-0.5d51a23/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/util.go:2183\u001b[0m", 
        "", 
        "\u001b[91m\u001b[1m[Fail] \u001b[0m\u001b[90m[k8s.io] EmptyDir volumes \u001b[0m\u001b[91m\u001b[1m[It] volume on default medium should have the correct mode [Conformance] [Volume] \u001b[0m", 
        "\u001b[37m/builddir/build/BUILD/atomic-openshift-git-0.5d51a23/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/util.go:2183\u001b[0m", 
        "", 
        "\u001b[91m\u001b[1m[Fail] \u001b[0m\u001b[90m[k8s.io] EmptyDir volumes \u001b[0m\u001b[91m\u001b[1m[It] should support (non-root,0777,tmpfs) [Conformance] [Volume] \u001b[0m", 
        "\u001b[37m/builddir/build/BUILD/atomic-openshift-git-0.5d51a23/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/util.go:2183\u001b[0m", 
        "", 
        "\u001b[91m\u001b[1m[Fail] \u001b[0m\u001b[90m[k8s.io] EmptyDir volumes \u001b[0m\u001b[91m\u001b[1m[It] should support (root,0666,default) [Conformance] [Volume] \u001b[0m", 
        "\u001b[37m/builddir/build/BUILD/atomic-openshift-git-0.5d51a23/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/util.go:2183\u001b[0m", 
        "", 
        "\u001b[91m\u001b[1m[Fail] \u001b[0m\u001b[90m[k8s.io] EmptyDir volumes \u001b[0m\u001b[91m\u001b[1m[It] should support (root,0777,tmpfs) [Conformance] [Volume] \u001b[0m", 
        "\u001b[37m/builddir/build/BUILD/atomic-openshift-git-0.5d51a23/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/util.go:2183\u001b[0m", 
        "", 
        "\u001b[91m\u001b[1m[Fail] \u001b[0m\u001b[90m[k8s.io] EmptyDir volumes \u001b[0m\u001b[91m\u001b[1m[It] volume on tmpfs should have the correct mode [Conformance] [Volume] \u001b[0m", 
        "\u001b[37m/builddir/build/BUILD/atomic-openshift-git-0.5d51a23/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/util.go:2183\u001b[0m", 
        "", 
        "\u001b[91m\u001b[1m[Fail] \u001b[0m\u001b[90m[k8s.io] EmptyDir volumes \u001b[0m\u001b[91m\u001b[1m[It] should support (root,0644,tmpfs) [Conformance] [Volume] \u001b[0m", 
        "\u001b[37m/builddir/build/BUILD/atomic-openshift-git-0.5d51a23/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/util.go:2183\u001b[0m", 
        "", 
        "\u001b[91m\u001b[1m[Fail] \u001b[0m\u001b[90m[k8s.io] EmptyDir volumes \u001b[0m\u001b[0mwhen FSGroup is specified [Feature:FSGroup] \u001b[0m\u001b[91m\u001b[1m[It] new files should be created with FSGroup ownership when container is root [Volume] \u001b[0m", 
        "\u001b[37m/builddir/build/BUILD/atomic-openshift-git-0.5d51a23/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/util.go:2183\u001b[0m", 
        "", 
        "\u001b[91m\u001b[1m[Fail] \u001b[0m\u001b[90m[k8s.io] EmptyDir volumes \u001b[0m\u001b[91m\u001b[1m[It] should support (non-root,0644,tmpfs) [Conformance] [Volume] \u001b[0m", 
        "\u001b[37m/builddir/build/BUILD/atomic-openshift-git-0.5d51a23/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/util.go:2183\u001b[0m", 
        "", 
        "\u001b[91m\u001b[1m[Fail] \u001b[0m\u001b[90m[k8s.io] EmptyDir wrapper volumes \u001b[0m\u001b[91m\u001b[1m[It] should not cause race condition when used for git_repo [Serial] [Slow] [Volume] \u001b[0m", 
        "\u001b[37m/builddir/build/BUILD/atomic-openshift-git-0.5d51a23/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/pods.go:83\u001b[0m", 
        "", 
        "\u001b[91m\u001b[1m[Fail] \u001b[0m\u001b[90m[k8s.io] EmptyDir volumes \u001b[0m\u001b[91m\u001b[1m[It] should support (non-root,0666,tmpfs) [Conformance] [Volume] \u001b[0m", 
        "\u001b[37m/builddir/build/BUILD/atomic-openshift-git-0.5d51a23/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/util.go:2183\u001b[0m", 
        "", 
        "\u001b[91m\u001b[1m[Fail] \u001b[0m\u001b[90m[k8s.io] EmptyDir volumes \u001b[0m\u001b[91m\u001b[1m[It] should support (root,0777,default) [Conformance] [Volume] \u001b[0m", 
        "\u001b[37m/builddir/build/BUILD/atomic-openshift-git-0.5d51a23/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/util.go:2183\u001b[0m", 
        "", 
        "\u001b[91m\u001b[1m[Fail] \u001b[0m\u001b[90m[k8s.io] EmptyDir volumes \u001b[0m\u001b[0mwhen FSGroup is specified [Feature:FSGroup] \u001b[0m\u001b[91m\u001b[1m[It] volume on tmpfs should have the correct mode using FSGroup [Volume] \u001b[0m", 
        "\u001b[37m/builddir/build/BUILD/atomic-openshift-git-0.5d51a23/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/util.go:2183\u001b[0m", 
        "", 
        "\u001b[91m\u001b[1m[Fail] \u001b[0m\u001b[90m[k8s.io] EmptyDir volumes \u001b[0m\u001b[91m\u001b[1m[It] should support (root,0644,default) [Conformance] [Volume] \u001b[0m", 
        "\u001b[37m/builddir/build/BUILD/atomic-openshift-git-0.5d51a23/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/util.go:2183\u001b[0m", 
        "", 
        "\u001b[91m\u001b[1m[Fail] \u001b[0m\u001b[90m[k8s.io] EmptyDir volumes \u001b[0m\u001b[91m\u001b[1m[It] should support (non-root,0777,default) [Conformance] [Volume] \u001b[0m", 
        "\u001b[37m/builddir/build/BUILD/atomic-openshift-git-0.5d51a23/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/util.go:2183\u001b[0m", 
        "", 
        "\u001b[91m\u001b[1m[Fail] \u001b[0m\u001b[90m[k8s.io] EmptyDir volumes \u001b[0m\u001b[0mwhen FSGroup is specified [Feature:FSGroup] \u001b[0m\u001b[91m\u001b[1m[It] new files should be created with FSGroup ownership when container is non-root [Volume] \u001b[0m", 
        "\u001b[37m/builddir/build/BUILD/atomic-openshift-git-0.5d51a23/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/util.go:2183\u001b[0m", 
        "", 
        "\u001b[91m\u001b[1m[Fail] \u001b[0m\u001b[90m[k8s.io] EmptyDir wrapper volumes \u001b[0m\u001b[91m\u001b[1m[It] should not cause race condition when used for configmaps [Serial] [Slow] [Volume] \u001b[0m", 
        "\u001b[37m/builddir/build/BUILD/atomic-openshift-git-0.5d51a23/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/empty_dir_wrapper.go:389\u001b[0m", 
        "", 
        "\u001b[91m\u001b[1m[Fail] \u001b[0m\u001b[90m[k8s.io] EmptyDir wrapper volumes \u001b[0m\u001b[91m\u001b[1m[It] should not conflict [Volume] \u001b[0m", 
        "\u001b[37m/builddir/build/BUILD/atomic-openshift-git-0.5d51a23/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/pods.go:83\u001b[0m", 
        "", 
        "\u001b[91m\u001b[1m[Fail] \u001b[0m\u001b[90m[k8s.io] EmptyDir volumes \u001b[0m\u001b[91m\u001b[1m[It] should support (non-root,0666,default) [Conformance] [Volume] \u001b[0m", 
        "\u001b[37m/builddir/build/BUILD/atomic-openshift-git-0.5d51a23/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/util.go:2183\u001b[0m", 
        "", 
        "\u001b[91m\u001b[1m[Fail] \u001b[0m\u001b[90m[k8s.io] EmptyDir volumes \u001b[0m\u001b[91m\u001b[1m[It] should support (non-root,0644,default) [Conformance] [Volume] \u001b[0m", 
        "\u001b[37m/builddir/build/BUILD/atomic-openshift-git-0.5d51a23/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/util.go:2183\u001b[0m", 
        "", 
        "\u001b[1m\u001b[91mRan 22 of 866 Specs in 7005.432 seconds\u001b[0m", 
        "\u001b[1m\u001b[91mFAIL!\u001b[0m -- \u001b[32m\u001b[1m0 Passed\u001b[0m | \u001b[91m\u001b[1m22 Failed\u001b[0m | \u001b[33m\u001b[1m0 Pending\u001b[0m | \u001b[36m\u001b[1m844 Skipped\u001b[0m --- FAIL: TestExtended (7005.49s)", 
        "FAIL"
```

**Comment by ashcrow** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Comment by ashcrow** [comment]
Infra flake

```
golang-1.7: Pulling from docker.io/openshift/origin-release
343b09361036: Already exists
b06b2c9b346b: Already exists
dd0895ba6fa0: Pulling fs layer
fc0c0e6d24b7: Pulling fs layer
e4d51ba9b586: Pulling fs layer
dd0895ba6fa0: Verifying Checksum
dd0895ba6fa0: Download complete
e4d51ba9b586: Verifying Checksum
e4d51ba9b586: Download complete
dd0895ba6fa0: Pull complete
fc0c0e6d24b7: Verifying Checksum
fc0c0e6d24b7: Download complete
fc0c0e6d24b7: Pull complete
e4d51ba9b586: Pull complete
Digest: sha256:4667335ed1c6bbd6cfdedb4e612724e5fa53d1ba36f05e3de33f3976a02ab1af
Write failed: Broken pipe
```

**Comment by ashcrow** [comment]
[merge]

**Pull request merged**
