### PR TITLE
Update image stream to openshift/origin:2c55ade

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/cc @abutcher @sdodson we need to automate this
/cc @bparees @csrwng

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
aos-ci-test

**Comment by stevekuznetsov** [comment]
[test]

**Comment by bparees** [comment]
lgtm

**Comment by sdodson** [comment]
[merge]

**Comment by sdodson** [comment]
github you done lost yo mind

**Pull request closed without merging**
