### PR TITLE
WIP Move etcd_data_dir fact into common facts

### PR DESCRIPTION
**Pull request by abutcher**
@dgoodwin PTAL

### CODE REVIEW

**Comment by abutcher** [comment]
Hopefully fixes #853 - still testing...

**Comment by dgoodwin** [comment]
Looks ok with master with embedded etcd. Thanks.

**Comment by detiber** [comment]
@abutcher there should be an etcd role, we should probably use that instead of master or common, and just make sure that a single master with embedded_etcd=True sets the fact as well (we can do this using a module call to openshift_facts from within the master role conditionally based on the value of openshift.master.embedded_etcd.

I'd prefer to keep common facts ones that are shared between multiple host types and not just as a catch all.

**Comment by abutcher** [comment]
@detiber Agreed. Working on it

**Comment by detiber** [comment]
for ^ if there isn't already an etcd role, we should add one...  we should also be calling openshift_facts and setting openshift variables for all etcd hosts (preferrably outside of the etcd role, since it is supposed to be a general role), so either a pre-call or a post-call to openshift-facts in the playbooks/common/openshift-etcd playbook.

We could also wrap the etcd role in an openshift-etcd role that could call openshift-facts and then set the generic variables for the etcd role accordingly through a dependency in the role metadata.

**Comment by abutcher** [comment]
@detiber Yep, there isn't an etcd role in facts and rather than go down that road I just flopped it into common. I'm digging into what needs to happen in the module.

**Comment by abutcher** [comment]
Closing this and letting @detiber drive since we're in a hot LZ.

**Pull request closed without merging**
