### PR TITLE
upgrade_control_plane.yml: systemd_units.yaml needs the master facts

### PR DESCRIPTION
**Pull request by tremble**

### CODE REVIEW

**Comment by abutcher** [comment]
@dgoodwin PTAL

**Comment by detiber** [comment]
@dgoodwin I believe this is related to the following bug: https://bugzilla.redhat.com/show_bug.cgi?id=1400819

**Comment by tremble** [comment]
Yeah sorry for the lack of detail.  That bugzilla is the same error I was seeing.  Do the unit tests run the upgrade jobs?

"AnsibleUndefinedVariable: 'openshift_master_config_file' is undefined"

**Comment by tremble** [comment]
Hitting it was as simple as running the upgrade playbook (I was actually running the v3_3 upgrade playbook)

ansible -i inventory/openplatform-a3/ openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_3/upgrade.yaml

(I was trying master because I hit #2907 on the 1.3 branch)


Mark

**Pull request merged**
