### PR TITLE
Pass first master's openshift_image_tag to openshift_loadbalancer for containerized haproxy installation.

### PR DESCRIPTION
**Pull request by abutcher**
https://bugzilla.redhat.com/show_bug.cgi?id=1467252

### CODE REVIEW

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Comment by abutcher** [comment]
aos-ci-test

**Comment by abutcher** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Comment by abutcher** [comment]
flake https://github.com/openshift/origin/issues/15356

**Comment by abutcher** [comment]
[merge]

**Pull request merged**
