### PR TITLE
Fix metrics deployment in 3.4

### PR DESCRIPTION
**Pull request by tbielawa**
Initial commit fixes PART of the issue with deploying the metrics component of OCP in 3.4. Specifically the first commit fixes an error caused by deprecation of providing multiple parameters as a comma-separated list to the 'oc process' command.

https://bugzilla.redhat.com/show_bug.cgi?id=1390849

### CODE REVIEW

**Comment by sdodson** [comment]
Rebased on master to pick up recent deployer template fixes.

**Comment by sdodson** [comment]
@tbielawa PTAL i think this is good to go

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by tbielawa** [comment]
Testing now

**Pull request merged**
