### PR TITLE
Add a license parameter to gcloud command

### PR DESCRIPTION
**Pull request by jcpowermac**
Adding `openshift_gcp_licenses` parameter will allow the enablement of nested virtualization in a gcp instance.  This will allow openshift / kubevirt users to test virtual machines on gcp.

```
openshift_gcp_licenses: https://www.googleapis.com/compute/v1/projects/vm-options/global/licenses/enable-vmx
```

### CODE REVIEW

**Comment by jcpowermac** [comment]
I tested this PR using: https://github.com/openshift/release/tree/master/cluster/test-deploy
with `openshift_gcp_licenses` defined and undefined.

**Comment by mtnbikenc** [comment]
@jcpowermac Please add the content of the PR description to `inventory/hosts.example` with the other openshift_gcp variables as a note and an example of how to use this option.

**Comment by jcpowermac** [comment]
@mtnbikenc added updates to `inventory/hosts.example`

**Pull request merged**
