### PR TITLE
[3.5] Switching commands for modules during upgrade of router and registry.

### PR DESCRIPTION
**Pull request by mtnbikenc**
Backports https://github.com/openshift/openshift-ansible/pull/3897
Bug https://bugzilla.redhat.com/show_bug.cgi?id=1462721

### CODE REVIEW

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
[merge][severity: bug]

**Comment by mtnbikenc** [comment]
It's a flake.  Looking...

**Comment by kwoodson** [comment]
@mtnbikenc, I love the simplicity of this and using the edits.

**Comment by sdodson** [comment]
Reviewed the test failures, this seems unrelated.

**Pull request merged**
