### PR TITLE
set the etcd backend quota to 4GB by default

### PR DESCRIPTION
**Pull request by ingvagabund**
Bug: 1492891

### CODE REVIEW

**Comment by sdodson** [comment]
We should add this to the upgrade playbook so that it gets set when upgrading to 3.6 or 3.7 too.

**Comment by ingvagabund** [comment]
> We should add this to the upgrade playbook so that it gets set when upgrading to 3.6 or 3.7 too.

Given the master branch currently supports 3.5->3.6 and 3.6->3.7 upgrades the `ETCD_QUOTA_BACKEND_BYTES` is set always.

If backported to release-3.6 branch, we can do basically the same as the --quota-backend-bytes has been here long enough.

**Pull request merged**
