### PR TITLE
Fix for gluster-s3 pvc check count.

### PR DESCRIPTION
**Pull request by SaravanaStorageNetwork**
Signed-off-by: Saravanakumar Arumugam <sarumuga@redhat.com>

### CODE REVIEW

**Comment by SaravanaStorageNetwork** [comment]
@jarrpa  Please check

**Comment by SaravanaStorageNetwork** [comment]
bot, test pull request

**Comment by jarrpa** [comment]
Nice solution, thanks!

/ok-to-test
/lgtm
/bot, test pull request

**Comment by SaravanaStorageNetwork** [comment]
@sdodson @michaelgugino @jarrpa   failing again - Please help to get this merged

**Pull request merged**
