### PR TITLE
Add system-only annotation to hawkular-metrics-admin

### PR DESCRIPTION
**Pull request by enj**
https://bugzilla.redhat.com/show_bug.cgi?id=1436620

cc @jwforres @benjaminapetersen

### CODE REVIEW

**Comment by enj** [comment]
aos-ci-test

**Comment by enj** [comment]
@sdodson from reading https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_manageiq/tasks/main.yaml I can see that this change will not be honored if the role already exists.

In origin we handle this through reconciliation - something similar needs to happen here.

**Comment by enj** [comment]
cc @tbielawa @simon3z

**Comment by sdodson** [comment]
> In origin we handle this through reconciliation - something similar needs to happen here.

Do the policy reconcilers handle this today? We call those during upgrade, everytime.

**Comment by enj** [comment]
> Do the policy reconcilers handle this today? We call those during upgrade, everytime.

No, only the bootstrap cluster roles and bindings (embedded in `oc`) are reconciled.

**Comment by simon3z** [comment]
cc @cben @enoodle

**Comment by simon3z** [comment]
cc @moolitayer

**Pull request closed without merging**
