### PR TITLE
Adding Docker Log Options capabilities

### PR DESCRIPTION
**Pull request by ejemba**
In regard of issue
https://github.com/openshift/openshift-ansible/issues/696

added option to : bin/cluster 
   -o log_driver=json-file -o log_options="max-size=5m,max-files=5"

will be added to OPTIONS in /etc/sysconfig/docker in all nodes of the cluster.

### CODE REVIEW

**Comment by detiber** [comment]
@ejemba Can you rename log_driver and log_options to docker_log_driver and docker_log_options?

otherwise, :+1:

**Comment by ejemba** [comment]
@detiber Yes,will do that tomorrow morning .

**Comment by abutcher** [comment]
@detiber @brenton Parameter names have been updated here so I'd say we're good to merge

**Comment by detiber** [comment]
@brenton :+1: from me

**Comment by nak3** [comment]
This options is available for anisble installation now, right? Please add it to the documentation https://docs.openshift.com/enterprise/latest/install_config/install/advanced_install.html

**Pull request merged**
