### PR TITLE
azure: ensure cloud provider config is laid down in bootstrap node config

### PR DESCRIPTION
**Pull request by jim-minter**

### CODE REVIEW

**Comment by jim-minter** [comment]
@kwoodson @mjudeikis @kargakis @pweil- fyi
this should solve https://github.com/Azure/acs-engine/issues/3070, but we also require https://github.com/openshift/openshift-ansible/pull/8656 to go in and get into the openshift/origin-ansible:v3.10 docker hub image

**Comment by kwoodson** [comment]
@jim-minter, 

This would also require the following:
- pass in the inventory variables so that the `openshift_sanitize_inventory` succeeds.  https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_sanitize_inventory/tasks/main.yml#L80-L96
- remove /etc/origin/cloudprovider/azure.conf  as we do not want to bake the credentials into the image.   Probably here as a separate task:  https://github.com/openshift/openshift-ansible/blob/master/playbooks/azure/openshift-cluster/build_node_image.yml#L59

**Comment by jim-minter** [comment]
@kwoodson I didn't need to do either of those things to successfully build an image.  Is it because I'm not setting `openshift_cloudprovider_kind` ?

**Comment by kwoodson** [comment]
@jim-minter, yes.

It looks like the node-config.yaml gets configured here: https://github.com/openshift/openshift-ansible/blob/master/playbooks/openshift-node/private/image_prep.yml#L16.  This is missing the `azure` settings in the config file. This is _not_ the config file that is used.

Shortly after, https://github.com/openshift/openshift-ansible/blob/master/playbooks/openshift-node/private/image_prep.yml#L28 is called which lays down the `bootstrap-node-config.yaml` which is the one you are referring to.  This seems like it would bypass those other requirements I mentioned earlier as they aren't being referenced.

/lgtm

**Pull request merged**
