### PR TITLE
Adding std_include to metrics

### LINKED ISSUE #5105: Origin Metrics playbook outdated -- `the field 'args' has an invalid value`
When setting up a Origin Metrics using the BYO playbooks on an existing cluster (`oc cluster up --version=latest`), the process fails with the following message:

```
TASK [openshift_metrics : Copy the admin client config(s)] ********************************************************************************************************************************************************
task path: /mnt/storage/jpkroehling/Projects/src/github.com/openshift/openshift-ansible/roles/openshift_metrics/tasks/main.yaml:39
fatal: [masters]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'openshift' is undefined\n\nThe error appears to have been in '/mnt/storage/jpkroehling/Projects/src/github.com/openshift/openshift-ansible/roles/openshift_metrics/tasks/main.yaml': line 39, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Copy the admin client config(s)\n  ^ here\n"}
fatal: [nodes]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'openshift' is undefined\n\nThe error appears to have been in '/mnt/storage/jpkroehling/Projects/src/github.com/openshift/openshift-ansible/roles/openshift_metrics/tasks/main.yaml': line 39, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Copy the admin client config(s)\n  ^ here\n"}
fatal: [etcd]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'openshift' is undefined\n\nThe error appears to have been in '/mnt/storage/jpkroehling/Projects/src/github.com/openshift/openshift-ansible/roles/openshift_metrics/tasks/main.yaml': line 39, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Copy the admin client config(s)\n  ^ here\n"}
fatal: [lb]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'openshift' is undefined\n\nThe error appears to have been in '/mnt/storage/jpkroehling/Projects/src/github.com/openshift/openshift-ansible/roles/openshift_metrics/tasks/main.yaml': line 39, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Copy the admin client config(s)\n  ^ here\n"}
fatal: [nfs]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'openshift' is undefined\n\nThe error appears to have been in '/mnt/storage/jpkroehling/Projects/src/github.com/openshift/openshift-ansible/roles/openshift_metrics/tasks/main.yaml': line 39, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Copy the admin client config(s)\n  ^ here\n"}
```
(script used for this: https://paste.fedoraproject.org/paste/oE669j5mlIZYrodc5Bklew/ )

Using a `oc` built from a recent revision (e2c9b75f1e61b5c8fae7ebc50eb905150bbd7303, Tue Aug 15 21:42:03 2017 -0700) to setup a cluster with metrics (`oc cluster up --version=latest --metrics=true`) yields similar results. There are several `openshift-ansible-metrics-job-xxx` pods in `Error` state under the `openshift-infra` namespace, and the following can be seen on the logs:

```
TASK [openshift_metrics : Copy the admin client config(s)] *********************
Wednesday 16 August 2017  14:14:19 +0000 (0:00:00.099)       0:00:02.004 ****** 
fatal: [127.0.0.1]: FAILED! => {
    "failed": true
}

MSG:

the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'openshift' is undefined

The error appears to have been in '/usr/share/ansible/openshift-ansible/roles/openshift_metrics/tasks/main.yaml': line 39, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Copy the admin client config(s)
  ^ here
```
(full logs: https://paste.fedoraproject.org/paste/ibmZla2DUr6J7hZKxNJhFA)

Expected results:
- The BYO Cluster playbook for installing Origin Metrics should work with a minimal inventory file (see the script https://paste.fedoraproject.org/paste/oE669j5mlIZYrodc5Bklew/ )
- `oc cluster up --version=latest --metrics=true` should also bring a working Origin Metrics installation

### PR DESCRIPTION
**Pull request by kwoodson**
Fixes #5105

### CODE REVIEW

**Comment by kwoodson** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by kwoodson** [comment]
[merge]

**Comment by kwoodson** [comment]
```
[ERROR] Status 'aos-ci-jenkins/OS_3.6_NOT_containerized' is required but was not found on this pull request.
[ERROR] Status 'aos-ci-jenkins/OS_3.6_NOT_containerized_e2e_tests' is required but was not found on this pull request.
[ERROR] Status 'aos-ci-jenkins/OS_3.6_containerized' is required but was not found on this pull request.
[ERROR] Status 'aos-ci-jenkins/OS_3.6_containerized_e2e_tests' is required but was not found on this pull request.
```

@sdodson, @mtnbikenc, what is needed here to push this along?

**Pull request merged**
