### PR TITLE
Add ability to disable os_firewall

### PR DESCRIPTION
**Pull request by detiber**
@abutcher ptal

### CODE REVIEW

**Comment by abutcher** [comment]
aos-ci-test

**Comment by abutcher** [comment]
@detiber Should we call this out in the example inventory files?

**Comment by detiber** [comment]
@abutcher possibly, I'm thinking about going back in and making it the default for cloud based installs as well...

**Comment by detiber** [comment]
@brenton @sdodson @abutcher @twiest: Looking for some feedback on the though of disabling the firewall by default when deploying to cloud instances, since the hosts are already managed by security_groups.

The user would also have the choice to override the defaults by setting os_firewall_enabled

**Comment by detiber** [comment]
@brenton @abutcher: still looking for a second opinion about whether it would be 'intuitive' to the users to default the local firewall to 'off' (wide open) for cloud-based deployments?

**Comment by abutcher** [comment]
@detiber Everyone will probably end up doing things differently wrt using host firewalls or fine grained NACLs vs security groups but I think it's fine to steer users towards security groups for cloud environments with the option to enable os firewall...

**Comment by detiber** [comment]
@brenton I think I'd like to go ahead and get this merged as an undocumented change for now, and add a card for addressing the dynamic setting of the firewall config.

**Pull request merged**
