### PR TITLE
Fix renaming error with calico template files

### PR DESCRIPTION
**Pull request by ozdanborne**
#4142 accidentally switched up the renaming of these template files. This PR corrects them.

The calico playbook errors out an ansible run in current master without this commit.

cc: @VincentS

### CODE REVIEW

**Comment by VincentS** [comment]
Sorry for the mixup of filenames. @sdodson @ingvagabund Can you do a review for this PR?

**Comment by sdodson** [comment]
bot, test pull request

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Pull request merged**
