### PR TITLE
Refactor and remove openshift_serviceaccount

### PR DESCRIPTION
**Pull request by mtnbikenc**
With the addition of the oc_* modules, the openshift_service account role can be replaced with idempotent tasks where needed.  This PR removes the openshift_serviceaccount role, which was only being used by the openshift_hosted role.  This will also simplify splitting router/registry into separate roles.

### CODE REVIEW

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
[test]

**Comment by sdodson** [comment]
[merge]

**Comment by mtnbikenc** [comment]
[merge]

**Pull request merged**
