### PR TITLE
fix ovs error

### PR DESCRIPTION
**Pull request by riffraff169**
Remove version requirement from openvswitch package, since listed version got removed from repo.

### CODE REVIEW

**Comment by kahou82** [comment]
LGTM 👍

**Comment by michaelgugino** [comment]
/lgtm-cancel

@riffraff169 Can you submit the patch against master?  We can then backport to this branch and 3.7.

**Comment by riffraff169** [comment]
sure, i'll do it this evening...

**Comment by michaelgugino** [comment]
@riffraff169 You will need to open a new PR against master, this PR will need to be closed.

**Pull request closed without merging**
