### PR TITLE
Enable EPEL repo for openshift origin install on CentOS

### PR DESCRIPTION
**Pull request by mtnbikenc**
The ansible package was removed from CentOS extras.

### CODE REVIEW

**Comment by Boran** [comment]
Hi, 
the EPEL URL is hard coded, so how can one use site-internal caches?
An attempted upgrade of 3.11 has failed due to this change.

**Comment by mtnbikenc** [comment]
I'll look into adding an inventory variable.

**Comment by mtnbikenc** [comment]
@Boran Does this suffice? https://github.com/openshift/openshift-ansible/pull/12160

**Comment by Boran** [comment]
Looks good. Thx.

**Comment by Boran** [comment]
Verified: Also tested in a cluster 3.11 upgrade, works as expected. Thanks.

**Pull request merged**
