### PR TITLE
Raise on dry-run failures.

### PR DESCRIPTION
**Pull request by kwoodson**

### CODE REVIEW

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by kwoodson** [comment]
aos-ci-test

**Comment by kwoodson** [comment]
[merge]

**Comment by kwoodson** [comment]
@stevekuznetsov, @sdodson, 
13:32:51         "No package matching 'origin-docker-excluder' found available, installed or updated"

Can we get this fixed or can we go back to manually merging?

**Comment by stevekuznetsov** [comment]
Was fixed yesterday

**Pull request merged**
