### PR TITLE
openshift_logging: use deployments instead of DCs

### PR DESCRIPTION
**Pull request by wozniakjan**
Change the deploymentconfigs to kubernetes deployments.

NOTE: after the #3509 got merged to master, additions in oc_scale.py proposed here are no longer used by any playbook, should they be removed from this PR?

### CODE REVIEW

**Comment by wozniakjan** [comment]
@jcantrill, @richm could you please take a look at this PR? 

I am afraid I can't add a reviewer properly according to [this page](https://help.github.com/articles/requesting-a-pull-request-review/)

**Comment by stevekuznetsov** [comment]
Is there some background on why we'd prefer `Deployment`s over `DeploymentConfig`s ?

**Comment by wozniakjan** [comment]
I can't provide sufficient answer but there is a trello card for it :)

https://trello.com/c/fJr858nz

**Comment by ewolinetz** [comment]
What is the impact on users that are currently using DCs and then running the playbook with these changes? Will they end up with duplicates e.g. a Kibana DC and a Kibana Deployment?

**Comment by jcantrill** [comment]
We prefer to use deployments mostly to rely on upstream constructs where it makes sense.  Currently, there is nothing about a DC that we utilize.  In regards to  how this will impact current users, we will have to account for an 'upgrade' path.  Also, I wonder  if we have concerns of how this might affect associated tooling.

Should we punt this change to 3.7 where we can add more thought around it?

**Comment by stevekuznetsov** [comment]
I would wait until upstream Origin has a clear upgrade path from DC --> D

**Comment by wozniakjan** [comment]
> Will they end up with duplicates e.g. a Kibana DC and a Kibana Deployment?

yes, I haven't thought that through very well, thanks!

**Pull request closed without merging**
