### PR TITLE
remove outdated openshift_cluster_metrics role

### PR DESCRIPTION
**Pull request by detiber**

### CODE REVIEW

**Comment by detiber** [comment]
@abutcher @wshearn @mwoodson heads up

**Comment by detiber** [comment]
aos-ci-test

**Comment by abutcher** [comment]
lgtm

**Comment by detiber** [comment]
aos-ci-test

**Comment by abutcher** [comment]
Overall will remain :x:'d but tests are good.

**Comment by detiber** [comment]
@abutcher thanks, any idea if/when we can get that cleared up?

**Comment by detiber** [comment]
@wshearn

**Pull request merged**
