### PR TITLE
crio: rename openshift_docker_use_crio to openshift_use_crio

### PR DESCRIPTION
**Pull request by giuseppe**
It is confusing to have _docker_ in the name, since they are two
different backends.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by ashcrow** [comment]
@gshipley I think the templates need updating too:

```
$ grep -rl 'use_crio' roles/ | sort | uniq
roles/docker/tasks/main.yml
roles/openshift_cli/tasks/main.yml
roles/openshift_docker_facts/tasks/main.yml
roles/openshift_node/tasks/main.yml
roles/openshift_node/tasks/openvswitch_system_container.yml
roles/openshift_node/templates/node.service.j2
roles/openshift_node/templates/node.yaml.v1.j2
roles/openshift_node/templates/openshift.docker.node.dep.service
roles/openshift_version/tasks/set_version_containerized.yml
```

**Comment by ashcrow** [comment]
Looking good. Since it's not covered by tests we need to manually verify the change.

**Comment by giuseppe** [comment]
removed the "[WIP]".  Tested locally and it works with the last CRI-O version.

**Comment by ashcrow** [comment]
aos-ci-test

**Comment by ashcrow** [comment]
[merge]

**Comment by ashcrow** [comment]
Infra flake

[merge]

**Pull request merged**
