### PR TITLE
Don't special case origin on centos

### LINKED ISSUE #2127: Missing CentOS-OpenShift-Origin.repo on centos
When running openshift-ansible on centos it fails with:

TASK: [openshift_master | Install Master package] *****************************
<centos-origin-master-0.example.com> ESTABLISH CONNECTION FOR USER: centos
<centos-origin-master-0.example.com> REMOTE_MODULE yum name=origin-master state=present
<centos-origin-master-0.example.com> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=centos -o ConnectTimeout=10 centos-origin-master-0.example.com /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1467902039.03-23892697339742 && echo $HOME/.ansible/tmp/ansible-tmp-1467902039.03-23892697339742'
<centos-origin-master-0.example.com> PUT /tmp/tmpT3kwEL TO /home/centos/.ansible/tmp/ansible-tmp-1467902039.03-23892697339742/yum
<centos-origin-master-0.example.com> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=centos -o ConnectTimeout=10 centos-origin-master-0.example.com /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=skysrqgjrlijtaiojuwnuxtlrcmyeawu] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-skysrqgjrlijtaiojuwnuxtlrcmyeawu; LANG=C LC_CTYPE=C /usr/bin/python -tt /home/centos/.ansible/tmp/ansible-tmp-1467902039.03-23892697339742/yum; rm -rf /home/centos/.ansible/tmp/ansible-tmp-1467902039.03-23892697339742/ >/dev/null 2>&1'"'"''
failed: [centos-origin-master-0.example.com] => {"changed": false, "failed": true, "rc": 0, "results": []}
msg: No Package matching 'origin-master' found available, installed or updated

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/main.retry

centos-origin-master-0.example.com : ok=279  changed=6    unreachable=0    failed=1
centos-origin-node-35innwvf.example.com : ok=44   changed=1    unreachable=0    failed=0
localhost                  : ok=41   changed=2    unreachable=0    failed=0

It seems to be related to https://github.com/openshift/openshift-ansible/commit/79120836a6332ab23ced4cc74112f41b26bd337f (it passes w/o this commit).

It seems that task "[openshift_repos | Remove any yum repo files for other deployment types RHEL/CentOS]" deletes file /etc/yum.repos.d/CentOS-OpenShift-Origin.repo and this file is not copied to nodes in any next step.

### PR DESCRIPTION
**Pull request by sdodson**
Rather than special casing origin on centos just deploy the repo files on our own so that they're managed like all the other repos.

Fixes #2127

### CODE REVIEW

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
@detiber what do you think about removing the special casing of using the centos release rpms?

**Comment by detiber** [comment]
@sdodson, so you are saying just always lay down the cert and the repo file for the CentOS PaaS SIG if the OS is not Fedora and the deployment_type is Origin?

**Comment by sdodson** [comment]
Yes, what i ran into with simply renaming it is that none of the existing logic to remove repo files for other deployment types was triggering, so I started wondering if it'd just be clearer to to handle rhel/centos origin repos the same way we're handling the others.

**Comment by detiber** [comment]
@sdodson :+1:

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
@detiber k, i'm done now.

**Comment by detiber** [comment]
lgtm

**Pull request merged**
