### PR TITLE
Rename container-engine-docker to container-engine

### PR DESCRIPTION
**Pull request by ashcrow**

### CODE REVIEW

**Comment by ashcrow** [comment]
aos-ci-test

**Comment by ashcrow** [comment]
```
No package matching 'atomic-openshift-docker-excluder-3.6.65*
```

**Comment by ashcrow** [comment]
aos-ci-test

**Comment by ashcrow** [comment]
**sigh**
```
No package matching 'atomic-openshift-docker-excluder-3.6.65
```

**Comment by ashcrow** [comment]
aos-ci-test

**Comment by ganhuang** [comment]
Hi, @ashcrow , do you mind taking a look at https://github.com/openshift/openshift-ansible/pull/4103, there're a few issues found in today's testing, this way seems to be more clear and easier rather than writing down each issue. I'll close it if you have better solution for those issues.

**Comment by ashcrow** [comment]
@ganhuang will do, thanks!

**Comment by ashcrow** [comment]
Closing in favor of https://github.com/openshift/openshift-ansible/pull/4103/files.

**Pull request closed without merging**
