### PR TITLE
Allowing openshift_metrics to specify PV selectors and allow way to d…

### PR DESCRIPTION
**Pull request by ewolinetz**
…efine selectors when creating pv

Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1442277

### CODE REVIEW

**Comment by ewolinetz** [comment]
Actually, would need to backport to 1.5 for the bz attached... but should be same approach

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[test]

**Comment by sdodson** [comment]
travis pylint is unhappy

**Comment by ewolinetz** [comment]
@sdodson whoops, on it now

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
[merge]

**Pull request merged**
