### PR TITLE
Remove oo_option facts.

### PR DESCRIPTION
**Pull request by abutcher**
This mainly ensures that `openshift_master_default_subdomain` isn't set to `""` so that router certificates are configured for the default value.

### CODE REVIEW

**Comment by abutcher** [comment]
bot, retest this please

**Comment by abutcher** [comment]
[test]

**Comment by sdodson** [comment]
Needs a specfile change to remove lookup_plugins or an empty file in that directory to preserve it may be easier.

**Comment by mtnbikenc** [comment]
I was wondering why it is trying to symlink:
```
ln -sf ../../../../../ansible_plugins/lookup_plugins/oo_option.py oo_option.py
```

**Pull request closed without merging**
