### PR TITLE
change become syntax logging

### PR DESCRIPTION
**Pull request by mjudeikis**
Change syntax of logging playbook when ansible is running on non-privileged user.

### CODE REVIEW

**Comment by mjudeikis** [comment]
see https://github.com/ansible/ansible/issues/18770#issuecomment-265176863
and https://github.com/ansible/ansible/issues/18770

**Comment by mjudeikis** [comment]
/hold
more bugs coming...

**Comment by ewolinetz** [comment]
logging test flake
/retest

**Comment by ewolinetz** [comment]
thanks for this @mjudeikis I'm trying to confirm with some of the members of the openshift-ansible team on whether or not this pattern should be applied to our other roles too.

**Comment by mjudeikis** [comment]
I think It should anywhere we need to downgrade permissions (I assume most
of the test is done using root so this issue is not comming up). But it
depends in case by case basis depending on task... I did test in 3.9 so we
will need cherry-pick.

**Comment by mjudeikis** [comment]
@ewolinetz  please lgtm this of you can. I have customer depending on this.

**Comment by jcantrill** [comment]
3.10 is still currently only receiving blockers. any changes that need to be in a 3.10.z stream need to wait until after the 3.10 release.  Anything targeted for 3.11 can go into master if that is how @sdodson his operating his master branch.

**Comment by mjudeikis** [comment]
@jcantrill  @sdodson  if this is not on known bugs list we should add this usecase to QA... aka "Stop testing stuff with the root user" :/

**Comment by ewolinetz** [comment]
bot, retest this please

**Comment by sdodson** [comment]
bot, retest this please

**Comment by mjudeikis** [comment]
bot, retest this please

**Pull request merged**
