### PR TITLE
WIP Add confirm to reconcile scc

### PR DESCRIPTION
**Pull request by vrutkovs**
This should fix failing `fedora/27/atomic/upgrade_minor` test

### CODE REVIEW

**Comment by vrutkovs** [comment]
bot, retest this please

**Comment by liggitt** [comment]
I misunderstood what this was doing. This is intentionally doing a dry run to see if reconciliation is required. In this case, it is required.

And yes, this PR adds a new field to the SCC objects which makes them require reconciliation. Why does that fail an upgrade job?

**Comment by michaelgugino** [comment]
@liggitt 

```
commit e5b9d94f14f6770aca9d20e435cb15503a799e7a
Author: Kenjiro Nakayama <nakayamakenjiro@gmail.com>
Date:   Wed May 16 22:58:39 2018 +0900
```

    Stop upgrade when existing sccs will be changed
    
    When running ugrade playbook, ansible upgrade playbook runs `oc adm
    reconcile-sccs --confirm --additive-only=true` by design. It could
    break cluster depends on users' configuration.
    
    Although we are saying that changing default SCCs is bad practice,
    some users notice it after the worst thing happened. To make matters
    worse, once customized SCCs are reconciled, it is difficult to recover
    the cluster from it as nobody took the backup of SCCs.
    
    To prevent such worst case, this PR changes upgrade playbook to stop
    when existing sccs will be changed.

**Comment by liggitt** [comment]
that removes the product's ability to evolve the SCC API. reconciliation will be required in 3.11

**Comment by sdodson** [comment]
This is a problem in oc not the installer.

**Comment by sdodson** [comment]
https://github.com/openshift/origin/pull/20197 was the fix

**Pull request closed without merging**
