### PR TITLE
GlusterFS: Default glusterfs_name in loop items.

### LINKED ISSUE #4745: Error during ansible playbook: 'glusterfs_name' is undefined
#### Description

Trying to install a Calico cluster. Runs of openshift-ansible on byo is failing due to an undefined `glusterfs_name`. 

This commit seems pretty suspect: #4245 

I'm very surprised that I seem to be the only one hitting this. Would have thought it's not calico-specific but it could very well be...

##### Version

```
ansible 2.2.0.0
openshift-ansible-3.6.141-1-20-gb8c5241
```

(Current master)

##### Steps To Reproduce

`ansible-playbook openshift-ansible/playbooks/byo/config.yml`

##### Expected Results

Successful playbook runthrough.

##### Observed Results

```
TASK [openshift_storage_glusterfs : Create temp directory for doing work in] ***
skipping: [master]

TASK [openshift_storage_glusterfs : set_fact] **********************************
skipping: [master]

TASK [openshift_storage_glusterfs : Verify target namespace exists] ************
skipping: [master]

TASK [openshift_storage_glusterfs : Delete pre-existing heketi resources] ******
fatal: [master]: FAILED! => {"failed": true, "msg": "'glusterfs_name' is undefined"}
        to retry, use: --limit @/home/turk/openshift-ansible/playbooks/byo/config.retry

PLAY RECAP *********************************************************************
etcd1                      : ok=128  changed=13   unreachable=0    failed=0   
localhost                  : ok=12   changed=0    unreachable=0    failed=0   
master                     : ok=518  changed=131  unreachable=0    failed=1   
node                       : ok=261  changed=69   unreachable=0    failed=0   


Failure summary:

  1. Host:     master
     Play:     Configure GlusterFS
     Task:     openshift_storage_glusterfs : Delete pre-existing heketi resources
     Message:  'glusterfs_name' is undefined
```

##### Additional Information

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)

CentOS Linux release 7.3.1611 (Core) 

* Your inventory file (especially any non-standard configuration parameters)

```
[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
os_sdn_network_plugin_name=cni
openshift_use_openshift_sdn=false
openshift_use_calico=true
openshift_disable_check=memory_availability,docker_storage


[masters]
master

[nodes]
master openshift_node_labels="{'region': 'infra'}"
node

[etcd]
etcd1
```

### PR DESCRIPTION
**Pull request by jarrpa**
Fixes #4745

Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>

### CODE REVIEW

**Comment by ozdanborne** [comment]
I think you missed one: `Delete pre-existing GlusterFS resources` in `./roles/openshift_storage_glusterfs/tasks/glusterfs_deploy.yml`

**Comment by jarrpa** [comment]
Good catch! Fixed. :)

**Comment by sdodson** [comment]
aos-ci-test

**Comment by ozdanborne** [comment]
ping @sdodson

**Comment by sdodson** [comment]
thanks for the reminder

**Pull request merged**
