### PR TITLE
Removing docker-registry route in cockpit-ui as its handled in openshift_hosted.

### PR DESCRIPTION
**Pull request by kwoodson**

### CODE REVIEW

**Comment by kwoodson** [comment]
@mwoodson @joelddiaz 

Here is the fix for the issue we are seeing with the passthrough route being setup.  Cockpit-ui was overriding it after the re-encrypt route was laid down.  This should fix it.

**Comment by mwoodson** [comment]
I would consider this to be a ops blocker for 3.5 at this point.  To be explicit, this needs to be in 3.5 as well.

Thanks!

**Comment by kwoodson** [comment]
aos-ci-test

**Comment by abutcher** [comment]
aos-ci-test

**Comment by kwoodson** [comment]
[merge]

**Pull request merged**
