### PR TITLE
Making router pods scale with infra nodes

### PR DESCRIPTION
**Pull request by etsauer**
This PR compares the current replica count of the router and ensures that it matches the count of nodes with the matching label. This should enable the router to scale as the infra nodes are scaled up and down.

@sdodson @abutcher

### CODE REVIEW

**Comment by etsauer** [comment]
bump. anyone?

**Comment by detiber** [comment]
@abutcher and @kwoodson are in the process of reworking the router/registry config. 

@sdodson It might be worth it to still accept this and backport to <= 1.4/3.4

**Comment by sdodson** [comment]
I'm curious the scenarios in which you've found this to be necessary, if you look at https://github.com/openshift/openshift-ansible/pull/3340/files#diff-fd7332c663fa2d9479983470772ccaf2R37 we're already figuring out the number of nodes that match your selector and then when we create the router we set the replicas. So this code shouldn't be necessary.

**Comment by detiber** [comment]
@sdodson I believe the use case is scaling up/down an existing router based on the number of infra nodes.

**Comment by etsauer** [comment]
@sdodson,  @detiber is correct. This additional code handles post install scale-up events.

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
I think the right solution to this in the future is to use daemonsets for registry and router but that may be a ways off.

**Comment by detiber** [comment]
@sdodson why do you think that is a ways off? The oc adm {router,registry} commands already have support for deploying using daemonsets.

Of course migration of existing deployments to daemonsets might be a bit tricky

**Comment by etsauer** [comment]
agreed. daemonsets is the better way to go. does that fit in with the overall re-work that @abutcher and @kwoodson are doing?

**Comment by etsauer** [comment]
@detiber as far as migration goes, could we make it a configurable option for a while and give operators a choice to transition?

**Pull request merged**
