### PR TITLE
[bz 1473154] Fix gce storageclass provider.

### PR DESCRIPTION
**Pull request by kwoodson**

### CODE REVIEW

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Comment by kwoodson** [comment]
@sdodson, I ran through an install and attempted to test this. I currently do not have a cluster on gce but I'm more confident this is fixed since I was able to test it a few more times.

Fix for this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1473154

**Comment by sdodson** [comment]
[merge]

**Comment by sdodson** [comment]
If that fails ping me and i'll manually merge it

**Comment by sdodson** [comment]
We need to pick this into release-3.6 too

**Comment by kwoodson** [comment]
@sdodson I'll pick this one once it merges.

**Comment by sdodson** [comment]
flaked on https://github.com/openshift/origin/issues/15356

**Comment by kwoodson** [comment]
@sdodson thanks

**Pull request merged**
