### PR TITLE
Re-enabling new tuned profile hierarchy (PR5089)

### PR DESCRIPTION
**Pull request by jmencak**
This PR is to re-enable the new tuned profile hierarchy as outlined in #5089 and #5054.

### CODE REVIEW

**Comment by jmencak** [comment]
Fixes https://github.com/openshift/openshift-ansible/issues/5351, @kwoodson , PTAL.

**Comment by kwoodson** [comment]
aos-ci-test

**Comment by kwoodson** [comment]
[merge]

**Comment by jeremyeder** [comment]
aos-ci-test

**Comment by jeremyeder** [comment]
@kwoodson @sdodson can you make it so that @jmencak or @jeremyeder can re-kick these tests?

**Comment by sdodson** [comment]
[merge]

**Comment by sdodson** [comment]
> @kwoodson @sdodson can you make it so that @jmencak or @jeremyeder can re-kick these tests?

looks like you can

**Comment by jmencak** [comment]
Do the first two CI tests pass when one performs a commit that doesn't change anything?  I think I've seen similar issues with #5089.

**Pull request merged**
