### PR TITLE
Lock down generated certs dir

### PR DESCRIPTION
**Pull request by sdodson**

### CODE REVIEW

**Comment by sdodson** [comment]
aos-ci-test

**Comment by detiber** [comment]
:+1:

**Comment by sdodson** [comment]
aos-ci-test

**Comment by arilivigni** [comment]
aos-ci-test

**Comment by arilivigni** [comment]
@sdodson I am rerunning this with the changes to the inventory that @detiber recommended so this should pass unless there is some other issue.

**Comment by sdodson** [comment]
@brenton should be good to go

**Pull request merged**
