### PR TITLE
Update CloudForms 4.6 templates for configmap mount and GA image location

### PR DESCRIPTION
**Pull request by simaishi**
- Change templates to mount the configmap into the directory the new image expects.
https://github.com/ManageIQ/manageiq-pods/pull/264

- Changed image location from Beta to GA (images won't become available until CF 4.6 goes GA)

### CODE REVIEW

**Comment by simaishi** [comment]
cc @sdodson

**Comment by vrutkovs** [comment]
bot, add author to whitelist

/ok-to-test

**Comment by sdodson** [comment]
Thanks @simaishi

**Pull request merged**
