### PR TITLE
Add openshift_docker_options to append arbitrary options to

### PR DESCRIPTION
**Pull request by sdodson**
/etc/sysconfig/docker OPTIONS

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1308621

### CODE REVIEW

**Comment by sdodson** [comment]
@abutcher PTAL

**Comment by abutcher** [comment]
LGTM @brenton

**Comment by brenton** [comment]
nice.  Thanks scott!

**Comment by sdodson** [comment]
eh, i should've done this before asking for review, but better late than never :-(

aos-ci-test

**Comment by abutcher** [comment]
I tested this locally with and without options. :)

**Pull request merged**
