### PR TITLE
Remove complex containerized version logic and fix f27 build

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by smarterclayton** [comment]
@michaelgugino backport of this fix to fix system-containers and f27 atomic jobs in 3.9

**Comment by michaelgugino** [comment]
@smarterclayton do you believe we will need this in 3.7 and 3.6 as well?  I noticed the tagging in those versions is similar to what we have in 3.9 now.

@sdodson this is what I was referring to.

**Comment by sdodson** [comment]
@michaelgugino Yeah, I think we should backport.

**Comment by smarterclayton** [comment]
The containerized bit also needs to get sorted out, but that's a larger backport.  Any issue with merging this as is and then fixing that separate?  or just add that commit to this PR?

**Comment by michaelgugino** [comment]
@smarterclayton let's merge and bp as-is.

**Pull request merged**
