### PR TITLE
OCPBUGS-29150: Align IPSEC with RHCOS

### PR DESCRIPTION
**Pull request by patrickdillon**
[ipsec: edit /etc/ipsec.conf to modify nssdir](https://github.com/openshift/openshift-ansible/commit/7045d83cafd2ac8a7b3804770f902c29c87c317b)

[Add and enable ipsec service](https://github.com/openshift/openshift-ansible/commit/4a057a46cea61e29fc91b6dc1978c80e8d96b18b)

#12482 for some reason could not get a clean cherry-pick. So this is a manual cherry-pick which also includes #12481

### CODE REVIEW

**Comment by patrickdillon** [comment]
/hold 
screwed up the rebase

**Review by barbacbd — COMMENTED** [review]
/lgtm

**Pull request merged**
