### PR TITLE
GlusterFS Fixes 4

### PR DESCRIPTION
**Pull request by jarrpa**
Fix communications with external GlusterFS nodes, add more documentation.

### CODE REVIEW

**Comment by sdodson** [comment]
Is this a release blocker?

**Comment by jarrpa** [comment]
Possibly? It fixes bugs found in testing, but I'd have to ask how urgent it is.

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge][severity:blocker]

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge][severity:blocker]

**Pull request merged**
