### PR TITLE
Add integration between Hawkular Alerts and Elasticsearch

### PR DESCRIPTION
**Pull request by mwringe**

### CODE REVIEW

**Comment by mwringe** [comment]
@jpkrohling I submitted this PR for you. Please monitor this.

**Comment by mwringe** [comment]
@ewolinetz Can you please take a look?

**Comment by ewolinetz** [comment]
aos-ci-test

**Comment by ewolinetz** [comment]
@mwringe this seems pretty straight forward to me, is there anything required on the logging images at all or the hawkular images?
Is this a bug or a release blocker at all?

**Comment by jpkrohling** [comment]
> is there anything required on the logging images at all or the hawkular images

No changes are required on the Hawkular side, but there are a couple of things to change on the Logging side, specially regarding the authorization. Some hacks are required to make it work, like this:
https://gist.github.com/jpkrohling/ef5999334dc488a838fb45ae459174e9#file-centos-origin-ansible-logging-metrics-sh-L106-L112

During our tests, we also had to remove the readiness checks from the Logging DCs, but I expect that to be fixed for the final logging images:

https://gist.github.com/jpkrohling/ef5999334dc488a838fb45ae459174e9#file-centos-origin-ansible-logging-metrics-sh-L86-L103

>  Is this a bug or a release blocker at all?

Not that I'm aware of.

cc @richm , @lucasponce

**Comment by jpkrohling** [comment]
By the way: this PR does not *require* changes to Logging. Once this is merged, Hawkular Alerts will start attempting to contact Elasticsearch at the given location, but will soft fail. Besides some noise on the logs, no bad side effects are expected on the Hawkular side. 

@lucasponce : can you confirm this?

**Comment by lucasponce** [comment]
The token is handled in the wrapper script for metrics ?

**Comment by jpkrohling** [comment]
> The token is handled in the wrapper script for metrics ?

Yes. On a next version of Alerts, it could accept the location for the file containing the token, so that it can react to file changes.

**Comment by lucasponce** [comment]
El 16 jun. 2017 3:16, "Juraci Paixão Kröhling" <notifications@github.com>
escribió:

By the way: this PR does not *require* changes to Logging. Once this is
merged, Hawkular Alerts will start attempting to contact Elasticsearch at
the given location, but will soft fail. Besides some noise on the logs, no
bad side effects are expected on the Hawkular side.

@lucasponce <https://github.com/lucasponce> : can you confirm this?

Yes. If hawkular alerts can't connect it will log but it won't fail or
impact on other component besides noise.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/openshift-ansible/pull/4453#issuecomment-308952508>,
or mute the thread

**Comment by ewolinetz** [comment]
Given that this doesnt resolve a bug and isn't a release blocker we'll wait on merging it in until after the current  sprint/release

**Comment by michaelgugino** [comment]
@ewolinetz Does this still need to ship?

**Comment by ewolinetz** [comment]
@mwringe this is still wanting to be merged in, correct?

**Comment by michaelgugino** [comment]
Close/reopen to trigger integration tests.

**Comment by mwringe** [comment]
I think its best to close this issue. I don't believe we want to pursue this option at this point in time.

**Pull request closed without merging**
