### PR TITLE
Bug 1767579: Remove import playbook restart

### PR DESCRIPTION
**Pull request by jcpowermac**
This restart is causing issues in CI specifically GCP.
Will revisit the original issue after CI is running correctly.

BZ 1746143
BZ 1767579

### CODE REVIEW

**Comment by patrickdillon** [comment]
This should fix the CSR errors we're seeing in CI? 
```
Failure summary:


  1. Hosts:    ci-op-mlf6yn70-a2bb0-ig-m-ll9q
     Play:     masters
     Task:     Approve node certificates when bootstrapping
     Message:  Could not find csr for nodes: ci-op-mlf6yn70-a2bb0-ig-n-bw3l, ci-op-mlf6yn70-a2bb0-ig-n-tlk5, ci-op-mlf6yn70-a2bb0-ig-n-rhcx
```

**Comment by jcpowermac** [comment]
> This should fix the CSR errors we're seeing in CI?
> 
> ```
> Failure summary:
> 
> 
>   1. Hosts:    ci-op-mlf6yn70-a2bb0-ig-m-ll9q
>      Play:     masters
>      Task:     Approve node certificates when bootstrapping
>      Message:  Could not find csr for nodes: ci-op-mlf6yn70-a2bb0-ig-n-bw3l, ci-op-mlf6yn70-a2bb0-ig-n-tlk5, ci-op-mlf6yn70-a2bb0-ig-n-rhcx
> ```
@patrickdillon it was reported in the BZ that my PR https://github.com/openshift/openshift-ansible/pull/11968
broke it.  Though now that is still failing has me questioning it.  Let's see if removing the `update-ca-trust` fixes it.

**Comment by abhat** [comment]
Potentially related to: BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1766619

**Comment by jcpowermac** [comment]
retesting adding update-ca-extract back in.

**Pull request merged**
