### PR TITLE
Adjust the logic as to when examples are deployed

### PR DESCRIPTION
**Pull request by sdodson**
* Move all example enablement into the openshift_examples role
* Add openshift-enterprise and atomic-openshift to the mix

### CODE REVIEW

**Comment by sdodson** [comment]
@wshearn You may be interested in this, I know some folks have been asking you about examples that are installed. Feel free to merge as is or let me know how we want to handle 'online' deployment_type.

**Comment by sdodson** [comment]
@abutcher PTAL and tag brenton for merge if it looks good to you

**Comment by abutcher** [comment]
@sdodson In `roles/openshift_examples/tasks/main.yml` I think that this

```
when: openshift_examples_load_rhel
``` 

should be 

```
when: openshift_examples_load_rhel | bool
```

**Comment by sdodson** [comment]
@abutcher Thanks, fixed that and another case of the same problem.

**Comment by abutcher** [comment]
LGTM @brenton

**Comment by jaryn** [comment]
Can one of the admins verify this patch?

**Comment by wshearn** [comment]
@abutcher can you add online to the list of deployments that all the examples gets loaded in?

**Comment by abutcher** [comment]
@sdodson Can you add the online change before @brenton gets to this?

**Comment by sdodson** [comment]
@abutcher @wshearn done

**Comment by abutcher** [comment]
LGTM :+1:

**Comment by brenton** [comment]
I'll let @wshearn merge this when he's OK with the change.

**Comment by jaryn** [comment]
Can one of the admins verify this patch?

**Comment by wshearn** [comment]
:+1:

**Pull request merged**
