### PR TITLE
Increase maxconn settings for haproxy lb

### PR DESCRIPTION
**Pull request by detiber**
Resolves https://github.com/openshift/openshift-ansible/issues/1497

### CODE REVIEW

**Comment by sdodson** [comment]
LGTM

**Comment by sdodson** [comment]
@brenton

**Comment by detiber** [comment]
@brenton lets hold off until we get some more confirmation/recommendations on the tuning params.

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
@brenton I think this is ready to go.

**Comment by jeremyeder** [comment]
@brenton when will https://github.com/openshift/openshift-ansible/pull/1524 show up in an OSE puddle? /cc @timothysc @rflorenc

**Comment by detiber** [comment]
@jeremyeder you'll also probably want this one as well: https://github.com/openshift/openshift-ansible/pull/1540

**Comment by brenton** [comment]
@jeremyeder, both of those are available in the puddle that was built last Friday.

**Comment by detiber** [comment]
@brenton I don't think https://github.com/openshift/openshift-ansible/pull/1540 is in that puddle, since it hasn't been merged yet.

**Comment by brenton** [comment]
@detiber, ahh, you're right.  When I opened it up I saw the purple merged image but that was for the referenced PR.

**Pull request merged**
