### PR TITLE
Refactor certificate playbooks for checkpointing

### PR DESCRIPTION
**Pull request by mtnbikenc**
The recent breakout of the certificate playbooks resulted in the certificate portion of the install to be outside of the component checkpoint.  This PR moves the certificate playbooks inside their respective config.yml playbook.

Removes an unused tasks file from the openshift_named_certificates role.

### CODE REVIEW

**Comment by michaelgugino** [comment]
@kwoodson Is ami_build or provisioning impacted by this?

**Comment by kwoodson** [comment]
I don't think this effects the bootstrapping.  Since the bootstrapping enters through the `byo/config.yml` I think that we should be okay.

**Pull request merged**
