### PR TITLE
ssh bastion: use TCP NLB and require ops-mirror.pem

### PR DESCRIPTION
**Pull request by vrutkovs**
Create TCP-based NLB for ssh-bastion to speed up SSH.

This PR also requires AWS secret to have ops-mirror.pem file, otherwise if its not present yum install would timeout without any valid error message

This cuts scaleup time from 40+ mins to ~15 minutes

### CODE REVIEW

**Comment by sdodson** [comment]
Is the PR description still accurate?

**Comment by vrutkovs** [comment]
I'm gonna try few tricks with ssh-bastion and update PR description if one of them works

**Comment by vrutkovs** [comment]
```
Failing tests:

[sig-storage] PVC Protection Verify "immediate" deletion of a PVC that is not in active use by a pod [Suite:openshift/conformance/parallel] [Suite:k8s]
```
/retest

**Comment by jstuever** [comment]
```

Failing tests:

[sig-cli] Kubectl Port forwarding [k8s.io] With a server listening on localhost [k8s.io] that expects a client request should support a client that connects, sends DATA, and disconnects [Suite:openshift/conformance/parallel] [Suite:k8s]
```
/retest

**Pull request merged**
