### PR TITLE
Fixing a bug by removing default debug output.

### PR DESCRIPTION
**Pull request by kwoodson**

### CODE REVIEW

**Comment by kwoodson** [comment]
I had @dustymabe test this fix on AH and it resolved an issue he was hitting.

**Comment by sdodson** [comment]
aos-ci-test

**Comment by dustymabe** [comment]
any chance we could get this merged today? I know it's saturday but hopefully all someone has to do is "click a button" :)

**Comment by kwoodson** [comment]
@dustymabe, enjoy your Saturday ;)

**Pull request merged**
