### PR TITLE
Fix to glusterfs installation by importing

### PR DESCRIPTION
**Pull request by SaravanaStorageNetwork**
appropriate playbooks basic_facts and evaluate_groups.

Signed-off-by: Saravanakumar Arumugam <sarumuga@redhat.com>

### CODE REVIEW

**Comment by SaravanaStorageNetwork** [comment]
@jarrpa @sdodson  PTAL

**Comment by SaravanaStorageNetwork** [comment]
Following two variables are not evaluated when OCS installation playbook is ran.
groups['oo_glusterfs_to_config'] and openshift_is_atomic

import the playbooks such that the variables are populated.
init/basic_facts.yml
init/evaluate_groups.yml

**Comment by SaravanaStorageNetwork** [comment]
> setup_nodes.yml is not intended to be run as a top-level playbook, hence why it's under private. What are you trying to do?
@jarrpa   Please refer the comment
https://github.com/openshift/openshift-ansible/pull/9885#issuecomment-418159319

Also, the logs:
https://gist.github.com/SaravanaStorageNetwork/0dd10b92dddc875192c2945a32a8aa29

Please feel free the update the PR as this break the installation.

**Comment by michaelgugino** [comment]
@SaravanaStorageNetwork @jarrpa this will be addressed by https://github.com/openshift/openshift-ansible/pull/9847/files#diff-e711314cf7c3adc6ae693e72a7c62ec4R4

**Comment by SaravanaStorageNetwork** [comment]
@michaelgugino  @jarrpa   
Issue is following variables are not defined:
1. openshift_is_atomic is undefined 
2. oo_glusterfs_to_config 

Does the PR you mentioned addresses both ?

**Comment by jarrpa** [comment]
@SaravanaStorageNetwork The comment you linked does nothing to describe what you're trying to do, only the problem you're running into. So, again, what is it you're trying to do that you are running into this problem? My guess is that, yes, the PR I submitted will take care of the problem in a broader and more correct way, but I can't be certain until I know what you're trying to accomplish.

**Comment by SaravanaStorageNetwork** [comment]
@jarrpa :) 

Problem:
Following two variables are not evaluated when OCS installation playbook is ran.
groups['oo_glusterfs_to_config'] and openshift_is_atomic

Solution:
import the playbooks such that the variables are populated.
init/basic_facts.yml
init/evaluate_groups.yml

**Comment by jarrpa** [comment]
@SaravanaStorageNetwork What EXACT commands are you running? And are you just doing a basic brownfield installation?

**Comment by SaravanaStorageNetwork** [comment]
Yes brownfield installation using 

> 
> Defined glusterfs group in inventory file, execute CNS standalone deployment playbook.
>  ansible-playbook -vvv /usr/share/ansible/openshift-ansible/playbooks/openshift-glusterfs/config.yml

as mentioned in https://bugzilla.redhat.com/show_bug.cgi?id=1624819

**Comment by vrutkovs** [comment]
Master branch is closed! A major refactor is ongoing in devel-40. Changes for 3.x should be made directly to the latest release branch they're relevant to and backported from there.

**Pull request closed without merging**
