### PR TITLE
a-o-i: Remove 3.2 options for 3.1 quick installer

### PR DESCRIPTION
**Pull request by smunilla**
Remove any option for installing 3.2 in this version and add some logic to
instruct the user when they need to update the installer before attempting
a major upgrade of their cluster.

### CODE REVIEW

**Comment by sdodson** [comment]
Disable the pylint check for too many lines?

**Comment by smunilla** [comment]
aoi-ci-test

**Comment by sdodson** [comment]
Does this need to be rebased? looks like there's a lot of unassociated changes.

**Comment by smunilla** [comment]
@sdodson That should be much better now. Not sure what was up there.

**Comment by sdodson** [comment]
Should we also remove playbooks/common/openshift-cluster/upgrades/v3_1_to_v3_2/ ?

**Comment by sdodson** [comment]
I think this is sufficient, though I do wonder if we should remove the other v3_1_to_v3_2 playbooks.

**Comment by smunilla** [comment]
Might as well remove those while we're here. I'll update.

**Comment by sdodson** [comment]
QE has reported https://bugzilla.redhat.com/show_bug.cgi?id=1355926 against this PR

**Pull request closed without merging**
