### PR TITLE
Variables to specify failureThreshold for Hawkular probes

### PR DESCRIPTION
**Pull request by jmartisk**
fix for https://bugzilla.redhat.com/show_bug.cgi?id=1678100

### CODE REVIEW

**Comment by jmartisk** [comment]
@vrutkovs could we try to get this moving please? The tests failed but I suppose it's not a problem of the changes. Can we retest this? (not sure if I have a way to trigger that myself, suppose that no)

**Comment by jmartisk** [comment]
@vrutkovs sorry for poking you again, but a customer is asking when this will be in. The failure again looks unrelated to the PR

**Comment by ewolinetz** [comment]
@vrutkovs I'm going to have to defer to @jsanda

**Comment by jmartisk** [comment]
AFAIK John is no longer working on this, at least not in the company. perhaps @rubenvp8510  's review could help

**Comment by rubenvp8510** [comment]
This LGTM. only one small think,I'm wondering if it worth to add periodSeconds parameter too. Other than that, this looks good.

**Comment by jmartisk** [comment]
Thanks. I'd suggest we go with the current commit for now, the customer has been waiting a long time and this should be enough for resolving their problem

**Comment by rubenvp8510** [comment]
Ok, then this is ready to be merged

**Comment by vrutkovs** [comment]
/hold

@sdodson could you override the result here? scaleup task is mistakenly running for 3.11 PR

**Pull request merged**
