### PR TITLE
cherry-pick to 3.6 gluster block

### PR DESCRIPTION
**Pull request by mjudeikis**

### CODE REVIEW

**Comment by mjudeikis** [comment]
@jarrpa this one still kicking... testing now...

**Comment by mjudeikis** [comment]
looks like same dynamic inventory case here:
```
    glusterfs_nodes: "{{ groups.glusterfs_registry | default(groups.glusterfs) }}"
```
to
```
    glusterfs_nodes: "{{ groups.glusterfs_registry if groups.glusterfs_registry | lenght > 0 else groups.glusterfs }}"
```
Because of this endpoints templates gets evaluates wrong... testing the fix before committing... But it might be fixed again for all branches...

**Comment by jarrpa** [comment]
We don't want to hold up these PRs for this dynamic inventory stuff, and in particular I don't want it on QE's radar to test for it. If you can, push through without it and we'll backport the group fixes separately.

**Comment by mjudeikis** [comment]
this one does not hold... But it fails due firewall now...  I move forward overwriting those using debug mode, but now storage failing to provision.

**Comment by jarrpa** [comment]
@mjudeikis Always run tox on your end.

**Comment by mjudeikis** [comment]
@jarrpa for this we were firewall... so Copied it from 3.7+ but because plays are little bit different, added it just before Pods are created. Other option would be included before config... any ideas?

**Comment by jarrpa** [comment]
@mjudeikis Put the firewall include before the node labeling task.

**Comment by mjudeikis** [comment]
@jarrpa did it but would like to know your thinking behind this. I was thinking to do this just before deployment of the pods as its one pre-req needed for nodes. So if anything fails before deployment of pods, we would not leave residual firewalls rules open.

**Comment by jarrpa** [comment]
In 3.7+ all the firewall modifications get done before the main role tasks even run, so there's precedent for this. I just like having it at early as reasonably possible, and I figured just after any wipe operations was good enough.

**Pull request merged**
