### PR TITLE
add support for overriding default registry url

### PR DESCRIPTION
**Pull request by detiber**

### CODE REVIEW

**Comment by detiber** [comment]
@twiest - This one is particularly useful for overriding the registry url on a per-environment basis, and also for making use of the module for development/pre-release versions of enterprise.

**Comment by twiest** [comment]
@detiber won't automatically merge, please resubmit.

**Comment by detiber** [comment]
@twiest - rebased

**Comment by twiest** [comment]
@detiber conflicted with your other PR I just merged. :(

**Comment by detiber** [comment]
heh...  let me rebase again, looks like the other rebased PR conflicted as well

**Comment by detiber** [comment]
@twiest fixed for real this time

**Comment by twiest** [comment]
:+1:

**Pull request merged**
