### PR TITLE
Run some basic etcd checks after migration to ensure leases are good

### PR DESCRIPTION
**Pull request by tbielawa**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1468187

No idea if this will work yet. Just including the existing checks. Is there a way to loop these? Should I add retries in the included file? What's the best approach here?

### CODE REVIEW

**Comment by tbielawa** [comment]
[test]

**Comment by tbielawa** [comment]
aos-ci-test

**Comment by tbielawa** [comment]
@sdodson updated w/ a copy of the existing checks. Sequence as follows:

1. Run check
1. See if it's cool
1. Wait 5 seconds
1. Run check
1. See if it's cool
1. Wait 5 seconds
1. Run check
1. ...

**Comment by sdodson** [comment]
[test]

**Comment by sdodson** [comment]
LGTM, lets change to 30 seconds.

**Comment by tbielawa** [comment]
aos-ci-test

**Comment by tbielawa** [comment]
[test]

**Pull request merged**
