### PR TITLE
Replace node.js proxy with oauth-proxy

### PR DESCRIPTION
**Pull request by josefkarasek**

### CODE REVIEW

**Comment by richm** [comment]
@ewolinetz @jcantrill lgtm - you?

**Comment by jcantrill** [comment]
I'm really supprised that this passed our tests since i expect we need additional support from https://github.com/openshift/origin-aggregated-logging/pull/1242

**Comment by ewolinetz** [comment]
test concern aside, LGTM

**Comment by ewolinetz** [comment]
/test logging
now that https://github.com/openshift/origin-aggregated-logging/pull/1242 merged in

**Comment by ewolinetz** [comment]
fluentd flake
/retest

**Comment by jcantrill** [comment]
Manually merging as the failed test has passed in previous runs and is unrelated to remote-syslog

**Pull request merged**
