### PR TITLE
Stop all services prior to upgrading, start all services after

### PR DESCRIPTION
**Pull request by sdodson**
Forward ports #3881

### CODE REVIEW

**Comment by ingvagabund** [comment]
aos-ci-test

**Comment by ingvagabund** [comment]
> error: "aos-ci-jenkins/OS_3.5_NOT_containerized, aos-ci-jenkins/OS_3.5_NOT_containerized_e2e_tests" for d2fc419 (logs)

I don't see any error here. Besides. the `aos-ci-jenkins/OS_3.5_NOT_containerized_e2e_tests` status says `"e2e tests passed"`. @sdodson missing a command to run a single test instead of the whole set.

**Comment by sdodson** [comment]
Yeah, I see no errors but it posted as a failure. :-(

**Comment by sdodson** [comment]
aos-ci-test

**Comment by ingvagabund** [comment]
aos-ci-test

**Comment by ingvagabund** [comment]
All tests up to the OS_3.6_containerized passed. The OS_3.6_containerized flaked on the unavailable excluders. Still wondering why is that happening. Though, not related to this PR.

**Pull request merged**
