### PR TITLE
Add a var to configure jenkinsPipelineConfig

### LINKED ISSUE #3562: Add option configure jenkinsPipelineConfig
The Jenkins pipeline config should be added to the master-config.yaml configurable so eg. jenkins-persistent could be used instead of jenkins-empheral

https://docs.openshift.org/latest/install_config/configuring_pipeline_execution.html

### PR DESCRIPTION
**Pull request by vrutkovs**
Fixes #3562

### CODE REVIEW

**Comment by sdodson** [comment]
I'd prefer we not add any additional configuration at this point but the cited issue says there's no reason not to. Ansible code lgtm, over to devex to approve.

/cc @bparees

**Comment by bparees** [comment]
has someone lined up QE to test this?

i'm ok w/ the changes, but i share @sdodson's concerns about how late this change is coming in.

**Comment by vrutkovs** [comment]
/hold

Lets hold it off until 3.11 release at least

**Comment by vrutkovs** [comment]
Master branch is closed! A major refactor is ongoing in devel-40. Changes for 3.x should be made directly to the latest release branch they're relevant to and backported from there.

**Pull request closed without merging**
