### PR TITLE
[BZ 1564857] fix image name

### PR DESCRIPTION
**Pull request by jsanda**

### CODE REVIEW

**Comment by jsanda** [comment]
@ewolinetz or @sdodson can you please review this? OCP 3.10 metric testing is currently blocked on this.

**Comment by jsanda** [comment]
I am not sure how/why my commit would cause travis to fail. Is the failure unrelated to my change?

**Comment by ewolinetz** [comment]
i think its unrelated
/ok-to-test

**Comment by ewolinetz** [comment]
not sure how to kick off travis again... but this change LGTM

**Comment by vrutkovs** [comment]
Flake

/retest

**Pull request merged**
