### PR TITLE
a-o-i: Bug1329455, [quick-install] Cannot add new nodes in pre-existing env

### PR DESCRIPTION
**Pull request by ganhuang**
It's enough to identify installed/uninstalled hosts by mastr and node roles instead of all kins of hosts.

### CODE REVIEW

**Comment by detiber** [comment]
> It's enough to identify installed/uninstalled hosts by mastr and node roles instead of all kins of hosts.

@ganhuang I'm not sure that is the case, in the case of containerized installs, the lb and storage hosts cannot be on a master or a node (and they cannot be containerized currently).

@smunilla Would it make more sense here to derive installed/uninstalled as sets based on iterating through the defined roles and the hosts that are assigned to each role?

**Comment by ganhuang** [comment]
>
@ganhuang I'm not sure that is the case, in the case of containerized installs, the lb and storage hosts cannot be on a master or a node (and they cannot be containerized currently).

 @detiber , yeah, i see. In the old code, LB will be added to installed_hosts automatically even if LB wasn't installed successfully, and it doesn't handle separate nfs host either. From openshift_fact.py, we could hardly identify if LB/NFS were actually be installed. 

In the new code, I thought in most of cases, only by master and node roles should we be able to identify if the cluster is installed successfully.

**Comment by detiber** [comment]
@abutcher ptal

**Comment by abutcher** [comment]
Fixed the pylint problem and squashed in #2297.

**Pull request closed without merging**
