### PR TITLE
upgrade: restart ovs-vswitchd and ovsdb-server

### PR DESCRIPTION
**Pull request by giuseppe**
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1420636

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
[test]

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Comment by brenton** [comment]
[merge]

**Comment by sdodson** [comment]
[merge]

**Pull request merged**
