### PR TITLE
Give service-catalog controller-manager permissions to update status of ClusterServiceClasses and ClusterServicePlans

### PR DESCRIPTION
**Pull request by staebler**
Add to ClusterRole service-catalog-controller permissions to perform updates on clusterserviceclasses/status and clusterserviceplans/status.

### CODE REVIEW

**Comment by ewolinetz** [comment]
With all these changes being made for fixing in openshift-ansible, we should investigate using ocp templates for ASB/SC like we do for the TSB role

**Comment by ewolinetz** [comment]
@sdodson i think logging is going to fail every time right now until a fluentd plugin is fixed

**Comment by sdodson** [comment]
> @sdodson i think logging is going to fail every time right now until a fluentd plugin is fixed

:cry: Is there a fix in the works for that?

**Pull request merged**
