### PR TITLE
[KIECLOUD-494] - Update RHPAM and RHDM templates and imagestreams on …

### PR DESCRIPTION
**Pull request by msmagnanijr**
…OpenShift Service Catalog for 7.10.1 release

See: https://issues.redhat.com/browse/KIECLOUD-494

Signed-off-by: Mauricio Magnani <mmagnani@redhat.com>

### CODE REVIEW

**Comment by msmagnanijr** [comment]
@mtnbikenc could you please take a look? thanks!

**Comment by msmagnanijr** [comment]
Hi @mtnbikenc @jcpowermac is it possible to merge it? thanks :)

**Comment by mtnbikenc** [comment]
Image build issue resolved.
/retest

**Comment by mtnbikenc** [comment]
e2e-aws job is still broken due to ruby (https://github.com/openshift/origin/pull/26070)
/hold
/ok-to-test
/retest

**Review by mtnbikenc — APPROVED** [review]
e2e-aws ci should be fixed.
/hold cancel
/retest

**Comment by mtnbikenc** [comment]
/retest
```
[36mINFO[0m[2021-05-24T20:21:08Z] Summarizing 1 Failure:                       
[36mINFO[0m[2021-05-24T20:21:08Z]                                              
[36mINFO[0m[2021-05-24T20:21:08Z] [Fail] [Feature:Builds][Conformance] imagechangetriggers  [It] imagechangetriggers should trigger builds of all types [Suite:openshift/conformance/parallel/minimal]  
[36mINFO[0m[2021-05-24T20:21:08Z] /tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/builds/imagechangetriggers.go:62 
```

**Comment by mtnbikenc** [comment]
/retest
```
[36mINFO[0m[2021-05-24T20:48:18Z] Summarizing 1 Failure:                       
[36mINFO[0m[2021-05-24T20:48:18Z]                                              
[36mINFO[0m[2021-05-24T20:48:18Z] [Fail] [Feature:DeploymentConfig] deploymentconfigs with failing hook [Conformance] [It] should get all logs from retried hooks [Suite:openshift/conformance/parallel/minimal]  
[36mINFO[0m[2021-05-24T20:48:18Z] /tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:838 
```

**Pull request merged**
