### PR TITLE
Running Logging Mux Component as privileged to mount 'filebufferstorage' as hostPath

### PR DESCRIPTION
**Pull request by steveteuber**
Currently it isn't possible to mount the `filebufferstorage` of the OpenShift Aggregated Logging Mux Component as `hostPath`:

Ansible Inventory:

```yaml
openshift_logging_use_mux: true
openshift_logging_mux_file_buffer_storage_type: hostmount
```

### CODE REVIEW

**Comment by steveteuber** [comment]
@nhosoi and @jcantrill: Please have a look.

**Comment by jcantrill** [comment]
@richm whats your thoughts here given mux doesn't have official support

**Comment by steveteuber** [comment]
With SELinux in enforcing mode, fluentd is not able to read/write on the host.
There is an open issue about it: https://github.com/openshift/origin-aggregated-logging/issues/89

```
$ sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      31
```

As well with the `hostmount-anyuid` scc for `system:serviceaccount:logging:aggregated-logging-mux`:

```
$ oc edit scc hostmount-anyuid
...
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:openshift-infra:pv-recycler-controller
- system:serviceaccount:kube-service-catalog:service-catalog-apiserver
- system:serviceaccount:logging:aggregated-logging-mux
```

I know that `privileged` gives the fluentd container a lot more access than is needed...

**Comment by steveteuber** [comment]
Our use cases for using mux:

1. Reducing the number of connections from Fluentd to an **external** Elasticsearch
2. Filtering logs before sending the records to Elasticsearch
3. Allow logging to be used as a central logging service for clients

**Comment by richm** [comment]
> With SELinux in enforcing mode, fluentd is not able to read/write on the host.
There is an open issue about it: openshift/origin-aggregated-logging#89

That issue is 3 years old . . . might be worth trying to follow the elasticsearch instructions for using `hostmount-anyuid` to see if those instructions work.

Also note that MUX is deprecated in 3.x, and not supported at all in 4.x, so just a warning that you will need to deploy your own custom fluentd in order to do what mux is currently doing, in the future.

**Comment by steveteuber** [comment]
Thanks, `hostmount-anyuid` is working with the following SELinux policy:
```
semanage fcontext -a -t container_file_t "/var/lib/fluentd(/.*)?"
```

Then I should add this policy while provisioning our hardware nodes.

Nevertheless, I would like to change the `hostPath` for `filebufferstorage`, `/var/log/fluentd` is the wrong location. I'll create a new Pull-Request for that or I'll create my own mux setup right away...

4.x will be interesting for us when we can installing it on bare metal.

**Pull request closed without merging**
