### PR TITLE
[3.9] WIP Ansible 2.6 fixes

### PR DESCRIPTION
**Pull request by vrutkovs**
3.9-specific fix to support ansible 2.6. Master PR is #9109

Resolves: #7596

### CODE REVIEW

**Comment by sdodson** [comment]
Is this already done on release-3.10 and master too?

**Comment by mtnbikenc** [comment]
Is this getting forward ported?

**Comment by vrutkovs** [comment]
This commit is not required for 3.10 or master - `certificates_to_synchronize` is not being called. The filter however might be used later on, so I'll include the commit in #9109

**Comment by xrow** [comment]
thanks a lot

**Pull request merged**
