### PR TITLE
New `iptablesSyncPeriod` field in node configuration

### PR DESCRIPTION
**Pull request by abutcher**
I alphabetized local facts in `roles/openshift_node/tasks/main.yml` while I was in the area.

For #665.

/cc @sdodson @detiber @kargakis

### CODE REVIEW

**Comment by detiber** [comment]
:+1:

**Comment by kwoodson** [comment]
ok to test

**Comment by kwoodson** [comment]
ok to test

**Comment by abutcher** [comment]
ok to test

**Comment by abutcher** [comment]
@brenton good to merge

**Pull request merged**
