### PR TITLE
[3.9] docker rootdir is different when installing crio

### PR DESCRIPTION
**Pull request by sjenning**
master PR: https://github.com/openshift/openshift-ansible/pull/8027

xref https://bugzilla.redhat.com/show_bug.cgi?id=1552827#c25

/cc @ashcrow @vikaslaad
/assign @sdodson

### CODE REVIEW

**Comment by sjenning** [comment]
system-containers test failing w/
```
TASK [openshift_cli : Pull CLI Image] ******************************************
task path: /usr/share/ansible/openshift-ansible/roles/openshift_cli/tasks/main.yml:26
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "cmd": [
        "atomic", 
        "pull", 
        "--storage", 
        "ostree", 
        "docker:openshift/origin:v3.9.0"
    ], 
    "delta": "0:00:00.463804", 
    "end": "2018-05-02 20:56:22.881314", 
    "generated_timestamp": "2018-05-02 20:56:22.912711", 
    "msg": "non-zero return code", 
    "rc": 1, 
    "start": "2018-05-02 20:56:22.417510", 
    "stderr": [
        "Error response from daemon: reference does not exist"
    ], 
    "stdout": []
}
```

**Comment by vrutkovs** [comment]
Failing system-containers test should be fixed by https://github.com/openshift/aos-cd-jobs/pull/1336

**Pull request merged**
