### PR TITLE
[KIECLOUD-316] - Update RHPAM and RHDM templates and imagestreams on …

### PR DESCRIPTION
**Pull request by spolti**
…OpenShift Service Catalog for release 7.5.0

Signed-off-by: Filippe Spolti <fspolti@redhat.com>

### CODE REVIEW

**Comment by spolti** [comment]
Hi @vrutkovs can this PR be merged?

**Comment by spolti** [comment]
Hi @vrutkovs are these failures related with the changes made by this PR?

**Comment by vrutkovs** [comment]
Seems all of these are temporary issues

/retest

**Comment by vrutkovs** [comment]
/hold

Putting this on hold as it seems there are GCP issues.

Does this need to be merged urgently?

**Comment by spolti** [comment]
@vrutkovs , a little bit since rhpam 7.5 was released last week.

**Pull request merged**
