### PR TITLE
Support log level configuration for Nuage exec plugin via ansible installer

### PR DESCRIPTION
**Pull request by abhat**
@detiber @vishpat please review.

### CODE REVIEW

**Comment by detiber** [comment]
@vishpat @abhat should there be a similar setting for the master component as well?

**Comment by detiber** [comment]
ok to test

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
@vishpat as an aside, are there any plans to provide some documentation around how to configure/use the nuage plugin?

We've had some internal requests asking about it, and outside of pointing to the role and the use_nuage flag there is not much to point them at.

**Comment by abhat** [comment]
@detiber good catch - uploaded the files to configure the log level on the nuage-openshift-monitor.

**Comment by abhat** [comment]
@detiber we will officially support the integration starting the upcoming release VSP 3.2R7. But if you are having specific people asking internally, we can unicast on email and make the user guide available to you.

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
@abhat I'll reach out if it comes up again.

**Comment by detiber** [comment]
:+1: @brenton @mwoodson

**Pull request merged**
