### PR TITLE
Bug 1786297: Remove machine config apply from upgrade

### PR DESCRIPTION
**Pull request by mtnbikenc**
Applying the machine config during upgrade is not necessary as this is
handled by MCO when machine config changes occur because MCD is already
running on the host.

### CODE REVIEW

**Comment by mtnbikenc** [comment]
`Throttling: Rate exceeded`
/retest

**Comment by sdodson** [comment]
So during our upgrade we simply reboot to ensure new binaries are used? MCO may or may not have applied configuration changes already? This seems potentially racey.

**Comment by sdodson** [comment]
/hold
until question answered.

**Comment by sdodson** [comment]
/hold cancel
The purpose of ansible rebooting the host is to ensure that new binaries are in use not to ensure that configuration changes are live which is assumed to be handled via MCO.

**Pull request merged**
