### PR TITLE
Update examples-sync.sh

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: https://github.com/openshift/openshift-ansible/issues/722

### CODE REVIEW

**Comment by mfojtik** [comment]
@sdodson

**Comment by jaryn** [comment]
Can one of the admins verify this patch?

**Comment by mfojtik** [comment]
@jaryn do you run some sort of Jenkins connected to your Github account?

**Comment by sdodson** [comment]
This would actually regress a few things but I review the xpaas streams and examples before committing them anyway.

So :+1: 

@brenton this is good to go, changes the examples maintenance script to point to a tagged release from the middleware teams.

**Pull request merged**
