### PR TITLE
Disable OpenShift features if installing Atomic Enterprise

### PR DESCRIPTION
**Pull request by detiber**

### CODE REVIEW

**Comment by detiber** [comment]
@abutcher @sdodson either of you mind giving this a review?

**Comment by detiber** [comment]
@dgoodwin @smunilla We'll need to build on this to support installing Atomic Enterprise through the installer wrapper. At some point in the future we'll want to support updating an Atomic Enterprise system to an OpenShift system and that would require setting osm_disabled_features to an empty list in addition to changing deployment_type fact.

We'd have to work out exactly how to do that, since we currently have the config clobbering issue to worry about as well and couldn't reliably trust blindly running the config playbooks.

**Comment by dgoodwin** [comment]
@detiber FWIW we might be good to go for new AEP installations once this is merged, you can select AEP in the wrapper now and it sets the atomic-enterprise deployment_type. 

Upgrade sounds a little more fun. :)

**Comment by sdodson** [comment]
LGTM

**Comment by detiber** [comment]
@brenton looks like this is ready to go, according to https://trello.com/c/8Eg36y6b, there was an issue accessing the AEP images, but it was worked around by re-tagging the OSE images.

**Pull request merged**
