### PR TITLE
Removes hardcoded python2

### LINKED ISSUE #383: hardcoded python path
There seems to be a hardcoded python2 path in the inventory/gce/hosts/hosts file:
localhost ansible_connection=local ansible_sudo=no ansible_python_interpreter=__/usr/local/bin/python2__

This sort of breaks things - for example on my Mac this path breaks as my python2 is in /usr/local/bin/python2

It would be good if this wasn't hardcoded OR that the GCE how to documentation told you to put your path in here.

### PR DESCRIPTION
**Pull request by jtslear**
* replaces the hard coded items in favor of pulling a users environment
* resolves #383
* Feedback and/or additional testing is more than welcome

### CODE REVIEW

**Comment by detiber** [comment]
@lhuard1A @twiest We need to come up with a compromise here that will work for both the Arch use case and the Mac use case....

**Comment by twiest** [comment]
ok to test

**Comment by twiest** [comment]
@detiber this PR doesn't do that (I honestly don't know)?

If it doesn't, what do you suggest?

**Comment by detiber** [comment]
@twiest hah, helps if I read the code diff...  yes, I believe it does, would like confirmation from @lhuard1A that it works in their environment though.

**Comment by lhuard1A** [comment]
@detiber : This PR works for me :+1:

**Comment by detiber** [comment]
@twiest make it so, this will also make @burrsutter's life easier as he will no longer have to manually edit the ec2 dynamic inventory to run the demo playbooks :)

**Comment by twiest** [comment]
:+1:

**Pull request merged**
