### PR TITLE
Avoid hardcoded namespace default in lib_openshift/oc_adm_router

### LINKED ISSUE #7009: Hardcoded namespace default in lib_openshift/oc_adm_router
#### Description

Provide a brief description of your issue here. For example:

> On a multi master install, if the first master goes down we can no
> longer scaleup the cluster with new nodes or masters.

##### Version

```
$ ansible --version
ansible 2.4.2.0

$ git describe
openshift-ansible-3.7.27-1-22-g99841ad50
```

##### Steps To Reproduce
1. Configure `openshift_hosted_routers` with namespace != default
2. Run config.yml playbook

##### Expected Results
Router successfully deployed in custom namespace 

##### Observed Results
Router successfully deployed in default namespace 

Maybe, because the Namespace default is hardcoded here:

https://github.com/openshift/openshift-ansible/blob/26caf813c55a090279260436ec315d8331bcc2e4/roles/lib_openshift/library/oc_adm_router.py#L2653

### PR DESCRIPTION
**Pull request by jkroepke**
Fixes #7009

### CODE REVIEW

**Comment by vrutkovs** [comment]
bot, test pull request

**Comment by jkroepke** [comment]
Any chance to get this into 3.9, too?

**Pull request merged**
