### PR TITLE
Playbook Consolidation - openshift-glusterfs

### PR DESCRIPTION
**Pull request by mtnbikenc**
- Create playbooks/openshift-glusterfs directory
- Consolidate openshift-glusterfs playbooks to above
- Fix all include path references throughout playbooks/

Trello: https://trello.com/c/Pg2wwsrW/549-2-playbook-consolidation-openshift-glusterfs

### CODE REVIEW

**Comment by mtnbikenc** [comment]
@jarrpa This is work based on the approved [proposal for playbook consolidation](https://github.com/openshift/openshift-ansible/pull/5322).  The work is now being performed and tracked in [Trello](https://trello.com/c/WlJsREnJ/531-epic-openshift-ansible-playbook-consolidation).

**Comment by jarrpa** [comment]
@mtnbikenc ...ah, all right then. I still say this should hold until the GlusterFS errata for 3.7 is out the door.

**Comment by mtnbikenc** [comment]
@jarrpa Do you have a link to the GlusterFS errata I could reference?

**Comment by jarrpa** [comment]
@mtnbikenc I don't know about errata unfortunately, but it's being tracked by this BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1512978

**Comment by sdodson** [comment]
/hold cancel
the CNS fixes have merged already into master and release-3.7, we're now waiting on QE to test them

**Comment by jarrpa** [comment]
@sdodson This merge is going to make it harder for me to backport any fixes that may need to be made from bugs found by QE... is that standard practice on this project?

**Comment by sdodson** [comment]
> @sdodson This merge is going to make it harder for me to backport any fixes that may need to be made from bugs found by QE... is that standard practice on this project?

This is a long planned major refactoring of playbooks that should be a one time thing. Lets hope most fixes come via updates to the role rather than the playbooks.

**Pull request merged**
