### PR TITLE
Drop inconsistent flannel SDN for openstack

### PR DESCRIPTION
**Pull request by bogdando**
Flannel SDN support by openstack provider is left
behind in the openshift-ansible-contribs.
Restore it back, if supported in the future.

### CODE REVIEW

**Comment by bogdando** [comment]
@tomassedovic

**Comment by tzumainn** [comment]
Tested, looks good to me!

Quick question: is it just shift-on-stack that won't support flannel? There still seems to be lots of flannel code inside of openshift-ansible (although this PR removes it from the openstack sections).

**Comment by bogdando** [comment]
@tzumainn this does not remove flannel support as a feature, we'll have to reimplement it though as the code had been moved from its old repo in inconsistent state. This is to remove that inconsistency, not to drop flannel support for ever :) @tomassedovic

**Comment by tzumainn** [comment]
@bogdando Ah, gotcha! Just out of curiosity, is there a plan for re-implementing that support? I just want to be sure that we're not removing something that we'll end up re-adding later.

**Comment by bogdando** [comment]
The documentaion part is going to be superseded by https://github.com/openshift/openshift-ansible/pull/7398 it seems

**Pull request closed without merging**
