### PR TITLE
[3.6] Adding Contrail SDN support for OpenShift

### PR DESCRIPTION
**Pull request by savithruml**
Added a flag to OpenShift Ansible for provisioning Juniper Contrail SDN controller

### CODE REVIEW

**Comment by ingvagabund** [comment]
@savithruml is there an easy way to test the contrail SDN?

**Comment by ingvagabund** [comment]
I see the PR updates release-3.6. Could you open a PR for the master branch and have it merged there first?

**Comment by savithruml** [comment]
@ingvagabund thanks I will open a PR to the master branch! [Instructions for testing Contrail SDN for OpenShift Enterprise](https://github.com/savithruml/openshift-contrail/wiki/OpenShift-Enterprise-with-Contrail-Networking)

**Comment by savithruml** [comment]
@ingvagabund [PR for master](https://github.com/openshift/openshift-ansible/pull/5623)

**Comment by savithruml** [comment]
Moving everything to [#5628](https://github.com/openshift/openshift-ansible/pull/5628/files/926a99392ecf7139f7e5d55a34104a1fc40bc081#diff-7906aa88255762cbc17ade09eef74d78)

**Pull request closed without merging**
