### PR TITLE
Sync latest imagestreams

### LINKED ISSUE #1302: examples fail to load
The installer fails to load the examples:

failed: [192.1.0.3] => {"changed": false, "cmd": ["oc", "create", "-n", "openshift", "-f", "/usr/share/openshift/examples/image-streams/image-streams-centos7.json"], "delta": "0:00:00.606947", "end": "2016-01-28 16:05:39.297060", "failed": true, "failed_when_result": true, "rc": 1, "start": "2016-01-28 16:05:38.690113", "stdout_lines": [], "warnings": []}
stderr: Error from server: ImageStream "ruby" is invalid: [spec.tags[2.0].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[2.2].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[latest].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[2.0].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[2.2].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[latest].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag']
Error from server: ImageStream "nodejs" is invalid: [spec.tags[0.10].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[latest].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[0.10].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[latest].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag']
Error from server: ImageStream "perl" is invalid: [spec.tags[5.16].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[5.20].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[latest].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[latest].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[5.16].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[5.20].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag']
Error from server: ImageStream "php" is invalid: [spec.tags[5.5].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[5.6].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[latest].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[5.5].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[5.6].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[latest].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag']
Error from server: ImageStream "python" is invalid: [spec.tags[2.7].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[3.3].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[3.4].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[latest].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[2.7].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[3.3].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[3.4].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[latest].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag']
Error from server: ImageStream "wildfly" is invalid: [spec.tags[8.1].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[latest].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[8.1].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[latest].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag']
Error from server: ImageStream "mysql" is invalid: [spec.tags[5.6].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[latest].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[5.5].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[latest].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[5.5].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[5.6].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag']
Error from server: ImageStream "postgresql" is invalid: [spec.tags[9.2].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[9.4].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[latest].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[9.2].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[9.4].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[latest].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag']
Error from server: ImageStream "mongodb" is invalid: [spec.tags[2.4].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[2.6].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[latest].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[2.4].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[2.6].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[latest].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag']
Error from server: ImageStream "jenkins" is invalid: [spec.tags[1].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[latest].from.name: invalid value '', Details: must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[1].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag', spec.tags[latest].from.kind: invalid value '', Details: valid values are 'DockerImage', 'ImageStreamImage', 'ImageStreamTag']

### PR DESCRIPTION
**Pull request by sdodson**
Fixes #1302 probably, testing now

### CODE REVIEW

**Comment by sdodson** [comment]
@liggitt as far as you know this lowercasing is compatible with v1.1/v1.0 ?

**Comment by liggitt** [comment]
Yes, lowercase kind/name was always correct, title-case attribute was always wrong, but the parser silently tolerated it.

**Comment by sdodson** [comment]
@detiber Mind taking a look, this was the only missing bool, correct?

**Comment by detiber** [comment]
@sdodson lgtm, thanks!

**Comment by sdodson** [comment]
@brenton g2g

**Comment by sdodson** [comment]
BTW, I've confirmed that this works with the latest origin codebase and OSE 3.1.x

**Pull request merged**
