### PR TITLE
Remove unused/broken node cert plays

### PR DESCRIPTION
**Pull request by michaelgugino**
This commit removes node certificate plays that are no
longer in use.

### CODE REVIEW

**Comment by vrutkovs** [comment]
IIUC there is no way to rotate node cert - except re-adding it to the cluster via `oc delete node`?

**Comment by michaelgugino** [comment]
@vrutkovs you could delete the existing certs, restart the node, and then approve the csrs.

**Comment by sdodson** [comment]
Yeah, renewing the node certs should be as simple as 1) Drain, 2) delete /etc/origin/node/certificates/* 3) restart 4) approve. The CA isn't handled in any manner but we're discussing what to do with that on the mailing list.

**Comment by DanyC97** [comment]
@sdodson  regarding 

> The CA isn't handled in any manner but we're discussing what to do with that on the mailing list

is that on dev mailing list? if so i haven't seen anything. In case i've missed the thread just let me know roughly the time and i'll search myself for it, thx

**Comment by sdodson** [comment]
> is that on dev mailing list? if so i haven't seen anything. In case i've missed the thread just let me know roughly the time and i'll search myself for it, thx

It wasn't on a public list. The tl;dr is that we'd like for the node sync pod to be responsible for rolling out new CA bundles to nodes rather than ansible.

**Comment by DanyC97** [comment]
@sdodson thank you for the info, interesting approach.

**Pull request merged**
