### PR TITLE
Normalize logging entry point to include std_include.

### PR DESCRIPTION
**Pull request by kwoodson**

### CODE REVIEW

**Comment by kwoodson** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
[test]

**Comment by kwoodson** [comment]
[merge]

**Comment by sdodson** [comment]
[merge]

**Comment by kwoodson** [comment]
Flake 
https://github.com/openshift/origin/issues/10162

**Comment by kwoodson** [comment]
[merge]

**Comment by kwoodson** [comment]
flake https://github.com/openshift/origin/issues/8571

**Comment by kwoodson** [comment]
[merge]

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
@kwoodson if that comes back green ping me to merge this

**Comment by kwoodson** [comment]
@sdodson, I'm not sure why it didn't run here.  I dug through the logs and it didn't run the aos ci tests because 
```
[ERROR] Status 'aos-ci-jenkins/OS_3.6_NOT_containerized' is required but was not found on this pull request.
[ERROR] Status 'aos-ci-jenkins/OS_3.6_NOT_containerized_e2e_tests' is required but was not found on this pull request.
[ERROR] Status 'aos-ci-jenkins/OS_3.6_containerized' is required but was not found on this pull request.
[ERROR] Status 'aos-ci-jenkins/OS_3.6_containerized_e2e_tests' is required but was not found on this pull request.
++ export status=FAILURE
++ status=FAILURE
```

Any way to rekick the tests?  This is painful.

**Comment by kwoodson** [comment]
[merge]

**Comment by sdodson** [comment]
Just an ordering issue, all the last tests passed but aos ci test wasn't done first so merging manually.

**Pull request merged**
