### PR TITLE
GlusterFS: Fix block StorageClass heketi route

### PR DESCRIPTION
**Pull request by jarrpa**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1542861

### CODE REVIEW

**Comment by jarrpa** [comment]
@mjudeikis Does this look about right?

**Comment by mjudeikis** [comment]
@jarrpa running to the train now. Will review in ~2hours on the train :)

**Comment by mjudeikis** [comment]
Brain freeze... Checking what the diff here https://github.com/jarrpa/openshift-ansible/blob/bc712160ddd27d0531a66da4f930d26b5506aa34/roles/openshift_storage_glusterfs/tasks/glusterfs_common.yml#L284 and here https://github.com/jarrpa/openshift-ansible/blob/bc712160ddd27d0531a66da4f930d26b5506aa34/roles/openshift_storage_glusterfs/tasks/glusterfs_common.yml#L334

**Comment by mjudeikis** [comment]
/lgtm
But I think we could save few cycles with mergings those 2 blocks with parameters as they have almost same code...
Dear future me: Fix it, please.

**Comment by jarrpa** [comment]
@mjudeikis Yeah I thought about that too, just moving those two tasks into their own block and adding `openshift_storage_glusterfs_block_storageclass` into the `when` clause for that block. This felt "safer" and is easier to test for now. :)

**Comment by mjudeikis** [comment]
Let's get it through QA and this can be backported later :)

**Pull request merged**
