### PR TITLE
Support for logging and metrics endpoints

### PR DESCRIPTION
**Pull request by detiber**
- Adds support for setting metricsPublicURL and loggingPublicURL
  - Default metricsPublicURL is https://{{ openshift_public_hostname }}:8443/metrics
  - Default loggingPublicURL is https://{{ openshift_public_hostname }}:8443/logging
  - openshift_master_console_use_ssl and openshift_master_console_port will
    override the connection type and port used by the metrics and logging endpoints.
  - openshift_master_{metrics,logging}_path will change the path for the respective endpoints
  - openshift_master_cluster_hostname will override openshift_public_hostname if provided
  - specifying openshift_master_public_{metrics,logging}_url will override any
    of the above settings and/or defaults

### CODE REVIEW

**Comment by detiber** [comment]
@adellape We'll probably want to add this to the docs in some way to match up with both the installation docs as well as the metrics/logging docs changes

**Comment by detiber** [comment]
@spadgett Do you see any issues with this implementation?

**Comment by spadgett** [comment]
@detiber The metrics public URL has to point to Hawkular metrics set up according to these instructions:

https://github.com/mwringe/origin-metrics

We should leave it unset if Hawkular is not configured or there will be errors on the pod page in the Web Console.

Similar for logging public URL, which should point to Kibana.  @sosiouxme can tell you more on logging.

Apologies if I was not clear in my issue.

**Comment by arilivigni** [comment]
Testing job has been triggered.

**Comment by arilivigni** [comment]
Internal Jenkins error during triggering.
 No test results found.

**Pull request closed without merging**
