### PR TITLE
Start requiring Ansible 2.4

### PR DESCRIPTION
**Pull request by mtnbikenc**
We've tested Ansible 2.4 and need to start addressing deprecation warnings.  This change will allow us to start migrating away from the `include:` directive as well as make necessary changes for obsolete AWS modules.

### CODE REVIEW

**Comment by mtnbikenc** [comment]
@kwoodson Yeah, this is for 3.8.  I'm wanting to start migrating away from `include:` while I'm touching all these files for the playbook consolidation, which is also for 3.8.

**Comment by mtnbikenc** [comment]
Jenkins needs to be updated to use Ansible 2.4.

**Comment by mtnbikenc** [comment]
@stevekuznetsov How can we go about updating CI to use Ansible 2.4?

**Comment by stevekuznetsov** [comment]
Where are we going to source the new RPMs? Are they in the latest RHEL Extras compose? Are they in RHUI? Do we need a custom COPR or repo?

**Comment by sdodson** [comment]
They're in RHEL Extras as of 7.4.1

**Comment by stevekuznetsov** [comment]
So we should see them in RHUI? Or do we need to cherry pick them from the RHEL 7 Next to the mirrors?

**Comment by sdodson** [comment]
They should be in RHUI by now, they shipped to RHEL Extras several weeks
ago.

**Pull request merged**
