### PR TITLE
Remove override default.py callback plugin

### PR DESCRIPTION
**Pull request by mtnbikenc**
The functionality of this plugin has been added to Ansible as the [debug.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/callback/debug.py) callback plugin.  The Ansible default plugin has added a significant amount of functionality as well as updates to the CallbackBase class.  When developing new plugins for OpenShift-Ansible this override can result in [unexpected](https://github.com/ansible/ansible/issues/27151) behavior.

This plugin was originally added in #1861.

### CODE REVIEW

**Comment by mtnbikenc** [comment]
Flake https://github.com/openshift/origin/issues/13977 Should update pod when spec was updated and update strategy is RollingUpdate
/retest

**Comment by tbielawa** [comment]
Kill it with :fire:

**Pull request merged**
