### PR TITLE
Update xpaas streams and templates for their v1.1.0 release

### PR DESCRIPTION
**Pull request by sdodson**
This includes renaming all of the templates and imageStreams to include minor
versions in their names. Older templates will be replaced with their newer
versions. Older imageStreams will not be removed from the openshift namespace
but are no longer supported and will not receive and further updates. Users should migrate their applications to use the newer imageStreams.

### CODE REVIEW

**Comment by sdodson** [comment]
@rcernich As we discussed.

**Comment by sdodson** [comment]
Should not be merged until we have approval from xpaas folks and we've verified that the new images are live.

**Comment by sdodson** [comment]
I've split the actual content updates from the ansible automation to migrate them so that github will show the diffs. @abutcher or @detiber any ideas on how to improve a01aa3f5088c2a39293263c6ff3561eaa60afcde ?

**Comment by sdodson** [comment]
@detiber you ok with merging this as is? The xpaas-1.1 images have landed.

**Comment by rcernich** [comment]
fyi, looks like jboss-webserver-3/webserver30-tomcat8-openshift:1.1 is still missing

**Comment by detiber** [comment]
@sdodson @rcernich Will these examples run unmodified on a 3.0 system?  If they require 3.1, we will probably need to have a distinct copy of the old xpaas templates/imagestreams for 3.0.

**Comment by sdodson** [comment]
I believe so but @rcernich can verify my memory is correct.

**Comment by rcernich** [comment]
Yep, they'll work on 3.0.x.

**Comment by detiber** [comment]
:+1: from me then.

@brenton

**Pull request merged**
