### PR TITLE
Stagger HA master service start

### PR DESCRIPTION
**Pull request by abutcher**
@detiber thoughts on an approach like this?

### CODE REVIEW

**Comment by sdodson** [comment]
Have we discussed why this is necessary with origin folks? While we can work around it here, if master services cannot be started in parallel that's something that needs to be fixed in the product for situations where an entire environment is restarted outside of our control (power outage, etc).

CC: @smarterclayton

**Comment by abutcher** [comment]
We haven't but this may not be necessary. All of my testing has been good
so far.

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
Confirmed to have resolved problems with at least one cluster install.

**Comment by sdodson** [comment]
aos-ci-test

**Pull request merged**
