### PR TITLE
Validate storage kinds aren't dynamic without dynamic provisioning enabled

### PR DESCRIPTION
**Pull request by ewolinetz**
Checking if any openshift_*_storage_kind variables are set to dynamic without enabling dynamic provisioning nor setting a cloud provider.

Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1415297

### CODE REVIEW

**Comment by ewolinetz** [comment]
@sdodson  Should we also have a way to ignore this check if we want?

**Comment by sdodson** [comment]
/retest

> @sdodson Should we also have a way to ignore this check if we want?

openshift_master_dynamic_provisioning_enabled does that, right?

**Comment by sdodson** [comment]
bot, retest this please

**Comment by sdodson** [comment]
failure looks legit

**Comment by ewolinetz** [comment]
@sdodson yes, but I was thinking more along the lines of like `openshift_disable_check`. So that if a customer really wants, they can ignore this error and configure this how they please.

**Comment by sdodson** [comment]
That sounds fine with me, how about adding a condition on `'dynamic_volumes_enabled' in openshift_disable_check | default([])` so we're just extending the existing openshift_disable_check functionality?

**Comment by sdodson** [comment]
@sosiouxme any objection to ^^ suggestion of extending openshift_disable_check?

**Comment by sosiouxme** [comment]
No particular objections, and I am sympathetic with the desire not to proliferate variables. Reusing `openshift_disable_check` would not hurt anything technically but it may worth another variable for the different role just to not intermingle their affairs.

**Comment by ewolinetz** [comment]
Per our convo on IRC, we're going with a new variable name since QE can provide a value of "*" to `openshift_disable_check`. Maybe down the road we can move where this check is done where it would be appropriate to use `openshift_disable_check` instead.

**Pull request merged**
