### PR TITLE
Do not check package version on non-master/node

### LINKED ISSUE #3594: [healthchecks] the package_version check always checks for master/node packages regardless of host group
#### Description

When running `playbooks/byo/openshift-preflight/check.yml`, the `package_version` check reports failures on hosts that can't access the `atomic-openshift-{master,node}` packages even when this is expected, e.g. on etcd or lb hosts.

##### Version

```
openshift-ansible-3.5.3-1-521-g3125e72
```

##### Steps To Reproduce
1. Have a cluster with `[etcd]`, `[lb]` and/or additional "auxiliary" host groups
2. Run the `playbooks/byo/openshift-preflight/check.yml` playbook

##### Expected Results
Hosts would not report a failure when they have access to the packages they need.

##### Observed Results
Hosts that don't have access to `atomic-openshift-{master,node}` packages in their configured repos are reported as failed, even when the hosts don't need these packages.
Describe what is actually happening.

```
$ ansible-playbook playbooks/byo/openshift-preflight/check.yml
[...]
Failure summary:

  1. Host:     etcd2.example.com
     Play:     run OpenShift health checks
     Task:     openshift_health_check
     Message:  One or more checks failed
     Details:  {'package_availability': {'_ansible_parsed': True,
                                         u'changed': False,
                                         u'invocation': {u'module_args': {u'packages': []}}},
                'package_update': {'_ansible_parsed': True,
                                   u'changed': False,
                                   u'invocation': {u'module_args': {u'packages': []}}},
                'package_version': {'_ansible_parsed': True,
                                    u'failed': True,
                                    u'invocation': {u'module_args': {u'prefix': u'atomic-openshift',
                                                                     u'version': u'v3.4'}},
                                    u'msg': u'Not all of the required packages are available at requested version 3.4:\n  atomic-openshift\n  atomic-openshift-master\n  atomic-openshift-node\nPlease check your subscriptions and enabled repositories.'}}
```

##### Additional Information

The inventory file used here has:

```
[OSEv3:children]
masters
nodes
etcd
lb
dns

# [...]

[etcd]
etcd2.example.com
# [...]

[lb]
lb.example.com
```

the hosts in *etcd*, *lb* and *dns* groups all fail the check.

### PR DESCRIPTION
**Pull request by rhcarvalho**
Fixes #3594.

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@codificat, I've updated the implementation to use `is_active` to skip the check when appropriate. PTAL.

**Comment by rhcarvalho** [comment]
aos-ci-test

**Comment by rhcarvalho** [comment]
[merge]

**Comment by rhcarvalho** [comment]
aos-ci-test

**Comment by rhcarvalho** [comment]
continuous-integration/openshift-jenkins/test — Failed

```
build/temp.linux-x86_64-2.7/build
    creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
    build/temp.linux-x86_64-2.7/_openssl.c:12:24: fatal error: pyconfig.h: No such file or directory
     #  include <pyconfig.h>
                            ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible_tox/8/console


@stevekuznetsov @sdodson missing dependencies to compile Python modules?

**Comment by stevekuznetsov** [comment]
@rhcarvalho fixed it this morning, those install instructions in the README for `tox` should also say to install the `cryptography` dependencies ;)

**Comment by stevekuznetsov** [comment]
re[merge]

**Comment by rhcarvalho** [comment]
I can't really tell what failed... https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_openshift_ansible/199/

[merge] again

**Comment by sdodson** [comment]
flake https://github.com/openshift/origin/issues/10162
[merge]

**Comment by rhcarvalho** [comment]
The unit test failures were caused by the way we instantiate action plugins in tests, something that manifested itself only in Ansible 2.3 and fixed in #3919.

[test]

**Comment by rhcarvalho** [comment]
[merge]

**Pull request merged**
