### PR TITLE
Revert "Refactor registry-console template and vars"

### PR DESCRIPTION
**Pull request by sdodson**
Had to address some conflicts due to subsequent changes to the sanity checks.

This reverts commit ea7fe4f7caba4b05ecaeca6c43b86dbd3762c4ce.
This reverts https://github.com/openshift/openshift-ansible/pull/9447

### CODE REVIEW

**Comment by sdodson** [comment]
Seriously? Everything failed?
/retest

**Comment by michaelgugino** [comment]
@sdodson any particular reason we're reverting this?

**Comment by vrutkovs** [comment]
Not sure if we want to revert the whole PR though, it seems just the component part doesn't get replaced

**Comment by sdodson** [comment]
Seriously? Everything failed?
/retest

> Not sure if we want to revert the whole PR though, it seems just the component part doesn't get replaced

I'm fine with that if you have the time to implement it.

**Comment by sdodson** [comment]
@michaelgugino https://github.com/openshift/openshift-ansible/pull/9447#issuecomment-413186276 it was passing through literal `${ component}` into the IMAGE_NAME

**Pull request closed without merging**
