### PR TITLE
prelim/partial update to jenkins imagestream to enable tests (while w…

### PR DESCRIPTION
**Pull request by gabemontero**
…e wait for global PR in openshift/origin to merge)

@bparees per discussion on IRC

### CODE REVIEW

**Comment by bparees** [comment]
@gabemontero please change the rhel one too, so at least those two are in sync.

**Comment by gabemontero** [comment]
@bparees I do not believe there are v4.0 images yet for rhel .... changing to that will break things

**Comment by bparees** [comment]
> @bparees I do not believe there are v4.0 images yet for rhel .... changing to that will break things

there are never v4.0 images for rhel until we GA.  QE knows how to modify the imagestream as needed.

**Comment by gabemontero** [comment]
rhel update

**Comment by bparees** [comment]
/lgtm

@sdodson fyi

**Comment by gabemontero** [comment]
the travis failure was a hiccup downloading python

**Pull request merged**
