### PR TITLE
3.9 upgrade: remove openshift.common.service_type

### PR DESCRIPTION
**Pull request by vrutkovs**
See eb6b20fc9183cc2aae424c72efd1191b99110a93

### CODE REVIEW

**Comment by vrutkovs** [comment]
Some logging flake

/retest

**Comment by vrutkovs** [comment]
devicemapper error in install test

/retest

**Comment by vrutkovs** [comment]
Test flakes

/retest

**Comment by vrutkovs** [comment]
Test flakes

/retest

**Comment by sdodson** [comment]
e2e flake

**Pull request merged**
