### PR TITLE
Disable config trigger logging

### PR DESCRIPTION
**Pull request by ewolinetz**
Removes the default config trigger from the ES generated DC and adds a handler to roll out any updated ES node in a controlled, rolling manner

Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1498989

### CODE REVIEW

**Comment by ewolinetz** [comment]
We will need to have corresponding changes to the origin-aggregated-logging repo for tests to continue to pass with the removal of the change trigger

**Comment by portante** [comment]
Waiting for green state may not be successful if the upgrade did not start in a green state.  Do we have a pre-condition or set of pre-conditions that need to be met for we'll start an upgrade?

**Comment by ewolinetz** [comment]
@portante we do not have that documented or fleshed out I believe. Do you have a set of requirements in mind? Also this may be used to scale up or try to fix a broken installation, so we have to keep that in mind too.

Is there a need to check for cluster status at all then? Should we make sure its at least yellow or are there cases where red may be alright for continuing?

**Comment by portante** [comment]
> Also this may be used to scale up or try to fix a broken installation, so we have to keep that in mind too.

Yes, that is a good point.

> Is there a need to check for cluster status at all then? Should we make sure its at least yellow or are there cases where red may be alright for continuing?

Since we are dealing with user's data with logs, we need to be mindful of what changes we make when and in what context.

So perhaps we can consider the following:

 * By default, playbooks look for an ES cluster in the `green` state, waiting for a period of time for the cluster to go `green` before continuing, failing the play if the cluster goes not reach a `green` state within that period of time

   * Also by default, each rollout of a DC would result in a wait for `green` state as well

 * Allow a user to override the behavior of failing the play, letting the play continue in any Elasticsearch state

   * And then each rollout of a DC would NOT result in a wait for `green` state

**Comment by ewolinetz** [comment]
> So perhaps we can consider the following:
> 
>     By default, playbooks look for an ES cluster in the green state, waiting for a period of time for the cluster to go green before continuing, failing the play if the cluster goes not reach a green state within that period of time

I'm a little wary of doing this since we would have a lot of angry users that do a fresh install with logging only to have the play fail because ES is taking too long... Unless this is only for an upgrade/pre-existing cluster scenario?

>         Also by default, each rollout of a DC would result in a wait for green state as well
> 
>     Allow a user to override the behavior of failing the play, letting the play continue in any Elasticsearch state
>         And then each rollout of a DC would NOT result in a wait for green state

This makes sense and is pretty simple to do.

**Comment by ewolinetz** [comment]
I may need to increase the amount of time we wait for the ES pod to come back up... what is committed was enough for my local system, not sure about CI

**Comment by ewolinetz** [comment]
@portante we just have our logging test which will run the playbook that causes the handler to fire

**Pull request merged**
