### PR TITLE
Do not escalate privileges in jks generation tasks

### LINKED ISSUE #4203: openshift_logging: don't create local tmpdir with `become`
Local tmp dir is created without `local_action` and `become: no`. This causes permissions errors when the control host is in the cluster and the tmpdir is created as root but the user running the playbook isn't root.

### PR DESCRIPTION
**Pull request by irozzo-1A**
fixes #4203

### CODE REVIEW

**Comment by sdodson** [comment]
bot, test pull request
/lgtm

**Comment by ewolinetz** [comment]
Logging test that is currently failing is due to a template issue, https://github.com/openshift/openshift-ansible/pull/6204 should resolve it

**Comment by irozzo-1A** [comment]
@ewolinetz @sdodson logging test is now succeeding

**Pull request merged**
