### PR TITLE
Fix etcd cert generation when etcd_interface is defined

### PR DESCRIPTION
**Pull request by detiber**

### CODE REVIEW

**Comment by jaryn** [comment]
Can one of the admins verify this patch?

**Comment by jaryn** [comment]
Can one of the admins verify this patch?

**Comment by detiber** [comment]
Squashed following QE verification of https://bugzilla.redhat.com/show_bug.cgi?id=1272201 and https://bugzilla.redhat.com/show_bug.cgi?id=1267733

@brenton this should be ready to go unless @sdodson or yourself see an issue with the implementation.

**Comment by sdodson** [comment]
Very clever solution. LGTM :+1:

**Pull request merged**
