### PR TITLE
1501599 for 36

### PR DESCRIPTION
**Pull request by jcantrill**
This is a 3.6 backport for #5888

### CODE REVIEW

**Comment by ewolinetz** [comment]
only upgrade is failing for a 3.6 pr. manually merging

**Comment by ewolinetz** [comment]
im not sure how to get the travis-ci test to come back... but that is preventing me from manually merging..
@sdodson or @stevekuznetsov any thoughts?

**Comment by sdodson** [comment]
I think close and re-open is the only way to kick travis. But that apparently triggers all the other tests to re-run. As soon as travis comes back i'll merge.

**Pull request merged**
