### PR TITLE
Add scaleup playbook and docs for OpenStack

### PR DESCRIPTION
**Pull request by tomassedovic**
This documents how to scale up a cluster running on OpenStack and adds a
playbook to make the process more convenient.

### CODE REVIEW

**Comment by tomassedovic** [comment]
Here's how you can test this:

1. Do a normal deployment (using provision_install)
2. Create some pods
3. Scale up as described in the docs
4. Mark the previous app nodes unschedulable by running: `oc adm manage-node app-node-0.tsedovic.openshift.cool --schedulable=false` etc.
5. Delete the previous pods

They should be created on the newly-added nodes and should be working just as they were before.

**Comment by vrutkovs** [comment]
@tomassedovic included playbooks should be in `private/`, but since openshift-node doesn't have a single playbook for scaling it should be:
```
- import_playbook: ../../openshift-node/private/bootstrap.yml
- import_playbook: ../../openshift-node/private/join.yml
```

**Comment by tomassedovic** [comment]
Right, thanks @vrutkovs!

Turns out it's not strictly speaking necessary here, but I'll want to add a fully-automated scaleup playbook later (one that creates the nodes and then configures the cluster) and I'll keep it in mind for then.

**Comment by tzumainn** [comment]
@tomassedovic Quick question - is there any reason why steps 2 and 3 couldn't/shouldn't be combined into one playbook?

**Comment by mbruzek** [comment]
@tomassedovic and @tzumainn this is generally the way we automated the scale up with a few notable exceptions:

1.  The '[new_nodes]' group had to be in the '[OSEv3:children]' group to get the OSEv3 variables.
2.  We split the install and provision steps so we could do a few things, such as putting the new VMs in the DNS server. Can we expect the `configure_new_nodes.yml` playbook to add the new nodes to DNS? (If so we can remove it from our automation, if not, perhaps we should consider adding this feature).
3.  The automation adds `openshift_node_group_name=\"node-config-compute\""` to each line of the Ansible inventory file so each node is property labeled when the OpenShift is installed.

The last thing our automation does is call the `openshift-ansible/playbooks/openshift-nodescaleup.yml` playbook

**Comment by tomassedovic** [comment]
Thanks for the feedback @mbruzek!

Do I understand it correctly that you're *not* using the dynamic inventory for scaleup? With it, points 1. and 3. should be handled automatically. I mean, they were in my testing.

Yeah `configure_new_nodes.yml` has been added in this patch. It configures docker storage to use Overlay 2 (might be a default now but we wanted to be sure) and makes sure the node hostnames match their names in Nova (a few things didn't work properly when that's the case). But it's not a huge deal if you don't do that.

Adding the DNS configuration there sounds like a great idea. I might do that in another PR though. There's a bunch more work to be done around scaling anyway, and I'd prefer to split it up to make it easier on the reviewers (and maybe have other people contribute).

**Comment by tomassedovic** [comment]
@tzumainn: I'll do that later -- possibly in a followup patch. I'd like to get to a fully automated scaleup playbook, but that will require additional changes. And e.g. (as evidenced in the previous tox failure and discussion) you can't just include the `origin-node/scaleup.yml` playbook.

**Comment by tomassedovic** [comment]
bot, retest this please

**Comment by mbruzek** [comment]
@tomassedovic We are indeed using the dynamic inventory but adding the new_nodes inventory in the home directory did not give us the child relation to OSEv3.yml properties file.

**Comment by tomassedovic** [comment]
bot, retest this please

**Comment by tomassedovic** [comment]
Thanks @tzumainn! I've updated the docs based on your suggestions!

And I've added `new_nodes` to the `OSEv3` group just in case @mbruzek.

**Comment by tomassedovic** [comment]
@tzumainn @luis5tb can you add the lgtm back? All I did was resolve the conflict in the docs.

**Comment by sdodson** [comment]
@tomassedovic Can you backport this to release-3.10? @mbruzek has requested it there.

**Comment by tomassedovic** [comment]
@sdodson here it is: https://github.com/openshift/openshift-ansible/pull/9242

**Pull request merged**
