### PR TITLE
Use six rather than try/except import for configparser

### PR DESCRIPTION
**Pull request by mscherer**

### CODE REVIEW

**Comment by mscherer** [comment]
aos-ci-test

**Comment by mscherer** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
@mscherer thanks, LGTM but we're trying to wrap up a release and minimize churn. Without this fix are Fedora or other Python 3 environments broken?

**Comment by mscherer** [comment]
Oh no, that's just a cleanup as I was reading the code, nothing urgent at all.

**Comment by mscherer** [comment]
Seems to no longer be needed since be949e0a

**Pull request closed without merging**
