### PR TITLE
validate data after v2->v3 etcd migration

### PR DESCRIPTION
**Pull request by ingvagabund**
SSIA

### CODE REVIEW

**Comment by ingvagabund** [comment]
aos-ci-test

**Comment by ingvagabund** [comment]
@smarterclayton do you think it makes sense to incorporate the validation as a command into oadm? Or would it be better to poke coreos guys and have it as a part of the `etcdctl` command?

**Comment by smarterclayton** [comment]
What validation is this again?  If it's that the migrate command worked correctly, I'd probably lean on etcdctl to do that.

**Comment by ingvagabund** [comment]
That all v2 keys are in v3 data store and their values in v2 are identical in v3.

**Comment by michaelgugino** [comment]
Closing due to inactivity.

**Pull request closed without merging**
