### PR TITLE
Fix for recent az changes.

### PR DESCRIPTION
**Pull request by kwoodson**
Fixes the failed image copy.  

Fixes https://github.com/openshift/release/issues/1648

Comments here:
https://github.com/openshift/release/issues/1648#issuecomment-424149482

### CODE REVIEW

**Comment by kargakis** [comment]
@kwoodson we also need to cherrypick back to release-3.10 and release-3.11, right?

/cherrypick release-3.10

**Comment by kargakis** [comment]
gcp job seems to fail due to an issue with the CI rpm repo
```
TASK [Ensure openshift-ansible installer package deps are installed] ***********
task path: /usr/share/ansible/openshift-ansible/playbooks/init/base_packages.yml:33
Tuesday 25 September 2018  08:35:48 +0000 (0:00:00.494)       0:00:52.823 ***** 
FAILED - RETRYING: Ensure openshift-ansible installer package deps are installed (3 retries left).
FAILED - RETRYING: Ensure openshift-ansible installer package deps are installed (2 retries left).
FAILED - RETRYING: Ensure openshift-ansible installer package deps are installed (1 retries left).
fatal: [35.231.18.173]: FAILED! => {"attempts": 3, "changed": false, "msg": "Failure talking to yum: failure: repodata/repomd.xml from origin-pr: [Errno 256] No more mirrors to try.\nhttp://rpm-repo-ci-op-70mvkn0z.svc.ci.openshift.org/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found"}
```
Seems to started failing yesterday afternoon UCT
https://deck-ci.svc.ci.openshift.org/?repo=openshift%2Fopenshift-ansible&job=pull-ci-openshift-openshift-ansible-master-e2e-gcp

cc @smarterclayton @stevekuznetsov @bbguimaraes

**Comment by kwoodson** [comment]
The gcp flakes are unrelated to this PR.

**Comment by stevekuznetsov** [comment]
@kargakis can you make an issue in `openshift/release` for https://github.com/openshift/openshift-ansible/pull/10215#issuecomment-424262121 ?

**Pull request merged**
