### PR TITLE
GlusterFS: Replace heketi Route with Service URL

### PR DESCRIPTION
**Pull request by jarrpa**
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1593450

Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>

### CODE REVIEW

**Comment by aramalipoor** [comment]
@jarrpa After this change we're getting this error when creating new PVCs:
```
Failed to provision volume with StorageClass "glusterfs-storage": failed to create volume: failed to create volume: Post http://heketi-storage.glusterfs.svc:8080/volumes: dial tcp: lookup heketi-storage.glusterfs.svc on 192.168.255.1:53: no such host
```
This `192.168.255.1` is our DNS server which is functioning fine as expected.

I'm not sure which component/controller is trying this URL 'cause any pod within `glusterfs` namespace can resolve it correctly.

FYI we're using `os_sdn_network_plugin_name: redhat/openshift-ovs-multitenant`.

**Comment by jarrpa** [comment]
I'm guessing you need to do some additional configuration due to your network plugin. From the [SDN documentation](https://docs.openshift.com/container-platform/3.10/architecture/networking/sdn.html):
> The ovs-multitenant plug-in provides project-level isolation for pods and services. Each project receives a unique Virtual Network ID (VNID) that identifies traffic from pods assigned to the project. Pods from different projects cannot send packets to or receive packets from pods and services of a different project.
> 
> However, **projects that receive VNID 0 are more privileged in that they are allowed to communicate with all other pods, and all other pods can communicate with them**. In OpenShift Container Platform clusters, the default project has VNID 0. This facilitates certain services, such as the load balancer, to communicate with all other pods in the cluster and vice versa.

**Pull request merged**
