### PR TITLE
[release-3.9] Refactor gluster image to use oreg_url

### PR DESCRIPTION
**Pull request by jarrpa**
This commit refactors various gluster component image
variables to utilize oreg_url.  This commit also
refactors filter plugin to make etcd_image filter reusable.

Backport of #8585

### CODE REVIEW

**Comment by jarrpa** [comment]
@michaelgugino This was in response to someone who ran into the bug where downstream images were being pulled from docker.io. Is there something else you'd like to see done?

**Comment by michaelgugino** [comment]
@jarrpa 

We've already released 3.9 so our variables for image names and whatnot should be locked in.  It's probably possible to specify exactly what image you want in 3.9 already with existing variables, so they should do that.

**Comment by jarrpa** [comment]
@michaelgugino It should still be possible for an installation that does not specify any image names to succeed by default. If this PR is not an acceptable answer for that, please let me know what would be.

**Comment by jarrpa** [comment]
I'll note that CNS does not strictly follow OCP's release schedule, as such our desired default image names may need to change post-release.

**Comment by jarrpa** [comment]
@michaelgugino Ping?

**Pull request closed without merging**
