### PR TITLE
For now, we require that your default interface be NM_CONTROLLED=yes

### LINKED ISSUE #2163: nameserver changed
In my private network I have deployed a bind server with IP 192.168.0.88. 

**Before Installing:**

```
# node1.localdomain 192.168.0.101
$ sudo cat /etc/resolv.conf 
search localdomain
nameserver 192.168.0.88
nameserver 8.8.8.8
```

```
# docker options
OPTIONS=' --selinux-enabled --dns 192.168.0.88 --dns 8.8.8.8 --insecure-registry=172.30.0.0/16 --log-driver=json-file'
```

**After Installing:**
_nameserver_ has been changed.

```
# node1.localdomain 192.168.0.101
$ sudo cat /etc/resolv.conf 
search localdomain
nameserver 192.168.0.101
nameserver 8.8.8.8
```

_dns_ options were removed

```
# docker options
OPTIONS=' --selinux-enabled --insecure-registry=172.30.0.0/16 --log-driver=json-file --log-opt max-size=50m'
```

**Installation:**

```
# cat /etc/ansible/hosts 
# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
masters
nodes

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root

# If ansible_ssh_user is not root, ansible_sudo must be set to true
#ansible_sudo=true

deployment_type=origin

# uncomment the following to enable htpasswd authentication; defaults to DenyAllPasswordIdentityProvider
#openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

# host group for masters
[masters]
node1.localdomain

# host group for nodes, includes region info
[nodes]
node1.localdomain openshift_node_labels="{'region': 'infra', 'zone': 'default'}" openshift_schedulable=true
```

```
# ansible-playbook ~/openshift-ansible/playbooks/byo/config.yml
```

**Issue:**

```
I0717 06:30:03.649386       1 builder.go:57] Master version "v1.2.0", Builder version "v1.2.0"
I0717 06:30:03.716060       1 builder.go:145] Running build with cgroup limits: api.CGroupLimits{MemoryLimitBytes:92233720368547, CPUShares:2, CPUPeriod:100000, CPUQuota:-1, MemorySwap:92233720368547}
I0717 06:30:03.890806       1 sti.go:205] The value of ALLOWED_UIDS is [1-]
I0717 06:30:03.890843       1 sti.go:213] The value of DROP_CAPS is [KILL,MKNOD,SETGID,SETUID,SYS_CHROOT]
I0717 06:30:03.902074       1 docker.go:355] Using locally available image "centos/python-34-centos7@sha256:e3ad517f317ad7a5d1939ab38e406825d2b51e9cc676df53825356fc18027c15"
I0717 06:30:03.906015       1 sti.go:232] Creating a new S2I builder with build config: "Builder Name:\t\t\tPython 3.4\nBuilder Image:\t\t\tcentos/python-34-centos7@sha256:e3ad517f317ad7a5d1939ab38e406825d2b51e9cc676df53825356fc18027c15\nBuilder Image Version:\t\te761571bb1bc910bda65674e0d43c4c3509a7823\nBuilder Base Version:\t\te178f1c\nSource:\t\t\t\tfile:///tmp/s2i-build680461441/upload/src\nOutput Image Tag:\t\tdjango-ex/django-example-2:ffd6400a\nEnvironment:\t\t\tOPENSHIFT_BUILD_NAME=django-example-2,OPENSHIFT_BUILD_NAMESPACE=django-ex,OPENSHIFT_BUILD_SOURCE=https://github.com/openshift/django-ex.git,PIP_INDEX_URL=\nIncremental Build:\t\tdisabled\nRemove Old Build:\t\tdisabled\nBuilder Pull Policy:\t\tif-not-present\nPrevious Image Pull Policy:\talways\nQuiet:\t\t\t\tdisabled\nLayered Build:\t\t\tdisabled\nWorkdir:\t\t\t/tmp/s2i-build680461441\nDocker NetworkMode:\t\tcontainer:3f83a7f33dd9a756ef3abc9939c6a51e22d0519bc97937403d75a9591d167843\nDocker Endpoint:\t\tunix:///var/run/docker.sock\n"
I0717 06:30:03.912004       1 docker.go:355] Using locally available image "centos/python-34-centos7@sha256:e3ad517f317ad7a5d1939ab38e406825d2b51e9cc676df53825356fc18027c15"
I0717 06:30:03.923626       1 docker.go:355] Using locally available image "centos/python-34-centos7@sha256:e3ad517f317ad7a5d1939ab38e406825d2b51e9cc676df53825356fc18027c15"
I0717 06:30:03.923688       1 docker.go:475] Image contains io.openshift.s2i.scripts-url set to 'image:///usr/libexec/s2i'
I0717 06:30:03.923751       1 sti.go:140] Preparing to build django-ex/django-example-2:ffd6400a
I0717 06:30:04.081751       1 source.go:197] Downloading "https://github.com/openshift/django-ex.git" ...
I0717 06:30:20.081999       1 cleanup.go:23] Removing temporary directory /tmp/s2i-build680461441
I0717 06:30:20.082028       1 fs.go:156] Removing directory '/tmp/s2i-build680461441'
F0717 06:30:20.082433       1 builder.go:204] Error: build error: timeout while waiting for remote repository "https://github.com/openshift/django-ex.git"
```

**How I solved it:**
I again appended `--dns 192.168.0.88 --dns 8.8.8.8` to docker `OPTIONS` again. And restarted the node(tried restarting the docker alone but it didn't worked).

### PR DESCRIPTION
**Pull request by sdodson**
Need to review how this intersects with 1.3 DNS changes
Fixes #2163

### CODE REVIEW

**Comment by sdodson** [comment]
aos-ci-test

**Comment by abutcher** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Pull request closed without merging**
