### PR TITLE
[master] set default openshift_release and docker_version if not set

### PR DESCRIPTION
**Pull request by ingvagabund**
Fixes: #4523

### CODE REVIEW

**Comment by ingvagabund** [comment]
aos-ci-test

**Comment by ingvagabund** [comment]
```
You requested openshift_release 3.6, which is not matched by
the latest OpenShift RPM we detected as atomic-openshift-3.5.5.28
on host 10.8.168.245.
We will only install the latest RPMs, so please ensure you are getting the release
you expect. You may need to adjust your Ansible inventory, modify the repositories
available on the host, or run the appropriate OpenShift upgrade playbook.
```

**Comment by ingvagabund** [comment]
@jhadvig @stevekuznetsov any plans to test master branch with 3.6?

**Comment by ingvagabund** [comment]
@jhadvig @stevekuznetsov I believe you will have to set `openshift_release` explicitly for the `OS_3.5` flavour if tests.

**Comment by jhadvig** [comment]
@ingvagabund you mean as a additional envvar when launching the installation or upgrade process ?

**Comment by ingvagabund** [comment]
@jhadvig yeap, or maybe just test the master branch with OCP 3.6

**Comment by stevekuznetsov** [comment]
Not clear on what the question is @ingvagabund. There are plans to move the previous version tests and containerized tests from AOS CI onto our Jenkins, yes. There should be a card for it on the Cluster Lifecycle board.

**Comment by ingvagabund** [comment]
> Not clear on what the question is @ingvagabund. There are plans to move the previous version tests and containerized tests from AOS CI onto our Jenkins, yes. There should be a card for it on the Cluster Lifecycle board.

If you check the failed 3.5 test, the fail message says it is trying to install 3.6 OCP instead of 3.5. That is caused by this PR since it sets the `openshift_release` to `v3.6` by default. Given the 3.5 CI test does not set the variable, `openshift_release` is set to `v3.6` instead of `v3.5` (since if it is not set, it gets automatically detected based on version of available OCP rpms). Setting `--extra-vars openshift_releaes=v3.5` will solve the problem.

**Comment by stevekuznetsov** [comment]
OK. Update the job definition in Gerrit to get that variable passed to the test. Seems reasonable to me.

**Comment by ingvagabund** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by ingvagabund** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[test]

**Comment by sdodson** [comment]
aos-ci-test

**Comment by michaelgugino** [comment]
Closing due to inactivity.

**Pull request closed without merging**
