### PR TITLE
[release-3.10]: Update openshift_release version in sample inventory

### PR DESCRIPTION
**Pull request by DanyC97**
Fixes https://github.com/openshift/openshift-ansible/issues/9480

### CODE REVIEW

**Comment by DanyC97** [comment]
@vrutkovs pls help review

**Comment by vrutkovs** [comment]
Looks good, however since 3.10 `openshift_release` is not required, lets make it commented and add a note that it would install whatever version is available in the repos?

cc @michaelgugino

**Comment by michaelgugino** [comment]
This change looks fine.  @vrutkovs I think the official docs are a better place for explaining the subtleties of these variables.

**Comment by DanyC97** [comment]
let me know if you happy with @michaelgugino 's response regarding the comment @vrutkovs . Happy to do add it in the sample file if consensus has been reached ;) 

@vrutkovs regarding

>openshift_release is not required

are you saying is no longer used in 3.10 or it default to whatever finds in the repos ?

**Comment by vrutkovs** [comment]
>I think the official docs are a better place for explaining the subtleties of these variables.

Agree

>are you saying is no longer used in 3.10 or it default to whatever finds in the repos ?

It is used and it would limit the available releases, however when its not set openshift-ansible would work fine (unlike other branches which require it). See #7699

**Pull request merged**
