### PR TITLE
master cherry picks for 3.6.1

### PR DESCRIPTION
**Pull request by sosiouxme**
Most of what the Customer Success team is merging to master is still relevant to the 3.6 lifecycle. Here's a PR to track those changes into 3.6.1 once 3.6.0 is code complete.

Included PRs (update as they merge):

- [add check to detect increased etcd traffic](https://github.com/openshift/openshift-ansible/pull/4316)
- [Fix broken link to Docker image instructions](https://github.com/openshift/openshift-ansible/pull/4807)
- [Remove dependency on playbook2image, rebase directly on OS.](https://github.com/openshift/openshift-ansible/pull/4742)
- [verify sane log times in logging stack](https://github.com/openshift/openshift-ansible/pull/4682)
- [openshift_checks: store args in check properties](https://github.com/openshift/openshift-ansible/pull/4485)
- [add fluentd logging driver config check](https://github.com/openshift/openshift-ansible/pull/4592)
- [Misc cleanup and input normalization](https://github.com/openshift/openshift-ansible/pull/4899)
- [package_version check: tolerate release version 3.7](https://github.com/openshift/openshift-ansible/pull/4969)
- [Origin image build: add oc client](https://github.com/openshift/openshift-ansible/pull/5003)

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@sosiouxme thanks for keeping track of this!

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[test]

**Comment by sosiouxme** [comment]
tests passed except for the fedora/25/atomic test blocking.

@sdodson @rhcarvalho shall we go ahead and get this merged? Needs an approval.

**Comment by sdodson** [comment]
fedora/25/atomic should no longer be blocking but I'm fine with merging it for you for expediency since the tests have all passed minus the ordering dependency between the two

**Comment by sosiouxme** [comment]
@sdodson cool, if you don't want to waste merge queue time on this it's fine with me. Or I can merge it the official way with an approval.

**Comment by sdodson** [comment]
[merge]

**Comment by sosiouxme** [comment]
https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_openshift_ansible/816/
```
+ approve.sh openshift-ansible release-3.6 none
[ERROR] No approval criteria are configured for 'release-3.6' branch of 'openshift-ansible' repo.
```

@sdodson @stevekuznetsov errr... what?

**Comment by stevekuznetsov** [comment]
@jupierce ^^

**Comment by jupierce** [comment]
I've now set an approver for this branch.

**Comment by sosiouxme** [comment]
@smunilla note https://github.com/openshift/openshift-ansible/pull/4814/commits/6ff80cead7a9a0b10f6b681a11b8a12ee58d0560 coming over from master will affect the downstream ose-ansible build. Content has moved around a bit.

**Pull request merged**
