### PR TITLE
Cleanup byo references

### PR DESCRIPTION
**Pull request by mtnbikenc**
* Remove playbooks/byo/config.yml, replaced by playbooks/deploy_cluster.yml
* Update example inventories
* Update doc references to 'byo' paths

### CODE REVIEW

**Comment by mtnbikenc** [comment]
Pending https://github.com/openshift/aos-cd-jobs/pull/931

**Comment by sdodson** [comment]
Need to update the specfile
```
cp: cannot stat 'inventory/byo/*': No such file or directory
```

**Comment by mtnbikenc** [comment]
specfile updated

**Pull request merged**
