### PR TITLE
Cleanup not required dns bits

### PR DESCRIPTION
**Pull request by bogdando**
* Do not manage hostnames for openstack cloud provider,
let cloud-init to do its job.
* Make python-dns / dnspython dependency check conditional.
* Drop not used dns node flavor and image.
* Do not manage dns nodes and sec groups in heat stacks.
* Keep supporting dynamic updates for private DNS records, yet only
limited to an external DNS managed elsewhere (not deployed by
the openshift_openstack provider). So users may still benefit from
this feature, sending nsupdates to private and public servers as
they want it.
* Fix openstack default for external nsupdate keys. It should be
  undefined by default as the dns-populate logic is based on that.
* Fix dns records generation for openstack provider's populate-dns.
* Update docs

Follows up https://github.com/openshift/openshift-ansible/pull/6290

@tomassedovic PTAL

### CODE REVIEW

**Comment by bogdando** [comment]
@tomassedovic @michaelgugino PTAL
e2e worked for me with https://github.com/openshift/openshift-ansible/pull/6345 in place

**Comment by michaelgugino** [comment]
/ok-to-test

This looks okay to me.

**Comment by bogdando** [comment]
@tomassedovic It has escaped the rebasing nightmare. e2e works for me. PTAL

**Comment by tomassedovic** [comment]
Nice one, thanks!

**Comment by bogdando** [comment]
@michaelgugino @sdodson could you please merge this?

**Comment by sdodson** [comment]
bot, test this please

**Comment by sdodson** [comment]
bot, add author to whitelist

**Comment by bogdando** [comment]
bot, test this please

**Comment by sdodson** [comment]
That failure is due to fedora infra outage. Merging this based on everything else being green and the lgtm

**Pull request merged**
