### PR TITLE
cluster_monitoring_operator: Bump to the latest build

### PR DESCRIPTION
**Pull request by elad661**
Based on the newly open-sourced https://github.com/openshift/cluster-monitoring-operator

/cc @ironcladlou

### CODE REVIEW

**Comment by sdodson** [comment]
How often are you going to be bumping this? If it's frequent please just override this locally to the version you wish to use or provide a tag that moves with your work.

**Comment by elad661** [comment]
@sdodson afaik this is not going to be a frequent thing. We'll soon have versioned tags for this (instead of the hash) and it's supposed to be relatively stable.

@ironcladlou, @brancz, @mxinden - what are your thoughts on this?

**Comment by elad661** [comment]
Changed the commit to use the new `v0.0.1` tag

**Comment by elad661** [comment]
bot, retest this please

**Pull request merged**
