### PR TITLE
a-o-i: Redo logic for detecting master_lb

### PR DESCRIPTION
**Pull request by smunilla**
After much research and debugging, it turns out the facts
for nativeha hosts were much less consistent than I hoped.
With this newfound knowledge, I've implemented this method.

In short, you check with the first master to see what it thinks
the master_lb is, then you include that host as "installed".

### CODE REVIEW

**Comment by smunilla** [comment]
@abutcher @brenton PTAL

**Comment by abutcher** [comment]
:+1:

**Comment by smunilla** [comment]
aos-ci-tests

**Comment by smunilla** [comment]
aos-ci-test

**Comment by abutcher** [comment]
@brenton should be good to merge but parent CI job never marked complete

**Pull request merged**
