### PR TITLE
SDN should read bootstrapped config

### LINKED ISSUE #8264: [3.10] flake: SDN won't come up on masters
Tests on Fedora Atomic frequently flake - SDN fails to start up on master

See logs at https://s3.amazonaws.com/aos-ci/ghprb/openshift/openshift-ansible/9a893cfafe6f5403f874cd8cb584a52ab87067d5.0.1525429564778020246/artifacts/index.html

[Master logs](https://gist.github.com/vrutkovs/7172587937a10e4a9c9c3905df728650):

* [API server is up](https://gist.github.com/vrutkovs/7172587937a10e4a9c9c3905df728650#file-fah_log-txt-L1)
* [Web Console template is processed](https://gist.github.com/vrutkovs/7172587937a10e4a9c9c3905df728650#file-fah_log-txt-L86)
* [Waiting for web console to come up](https://gist.github.com/vrutkovs/7172587937a10e4a9c9c3905df728650#file-fah_log-txt-L114)
* [Something kills API](https://gist.github.com/vrutkovs/7172587937a10e4a9c9c3905df728650#file-fah_log-txt-L274) - what's causing it?
* [SDN container is declared dead](https://gist.github.com/vrutkovs/7172587937a10e4a9c9c3905df728650#file-fah_log-txt-L381)
* [SDN container starts again](https://gist.github.com/vrutkovs/7172587937a10e4a9c9c3905df728650#file-fah_log-txt-L446)

After that the timeout for web console to be up hits.

Any ideas what's going on here? /cc @smarterclayton @openshift/networking 

Log with debug_level=4 - https://gist.github.com/vrutkovs/d9128bdccbf3e48cb9b2a675684775b6

The only suspicious thing I see is:
```
May 04 15:29:09 ocp-master docker-containerd-current[802]: time="2018-05-04T15:29:09.041571714Z" level=error msg="containerd: deleting container" error="exit status 1: \"container a199c08d3a9d2b3938f19915a9b7f228a682c92154b0ceae8c14bfae48ec448a does not exist\\none or more of the container deletions failed\\n\""
```
Could it be docker failing to restart SDN container?

### PR DESCRIPTION
**Pull request by vrutkovs**
Node-config.yaml is being removed on masters during control-plane install. Due to a race condition it might not be saved in the configmap and restored later on, as sync service requires SDN to start, which might not be up yet.

Instead of waiting for components to sync it's safe to leave node-config.yaml, as it won't be used by bootstrapped masters. If any changes would be required sync service would rewrite it and restart the node.

SDN script was updated to read atomic-openshift/origin config and extract CONFIG_FILE instead of hardcoded node-config.yaml

This should fix FAH single master install flakes

Fixes #8264 

First run: https://s3.amazonaws.com/aos-ci/ghprb/openshift/openshift-ansible/5c6f01c7018c3068c985bdd8e6b6530dc932d080.0.1525977983960669013/index.html

2nd run: https://s3.amazonaws.com/aos-ci/ghprb/openshift/openshift-ansible/5c6f01c7018c3068c985bdd8e6b6530dc932d080.0.1525982173679960029/index.html

### CODE REVIEW

**Comment by vrutkovs** [comment]
bot, retest this please

**Comment by vrutkovs** [comment]
bot, retest this please

**Comment by vrutkovs** [comment]
bot, retest this please

**Comment by vrutkovs** [comment]
bot, retest this please

**Comment by vrutkovs** [comment]
bot, retest this please

**Comment by vrutkovs** [comment]
@michaelgugino PTAL, added SDN bits to fix this

**Comment by vrutkovs** [comment]
bot, retest this please

**Comment by smarterclayton** [comment]
I think we may need to revert this.

**Pull request merged**
