### PR TITLE
Fix quoting

### PR DESCRIPTION
**Pull request by lukas-vlcek**
Back-porting https://github.com/openshift/openshift-ansible/pull/3763
@ewolinetz @richm PTAL

### CODE REVIEW

**Comment by sdodson** [comment]
This regressed yesterday, right? So we need this to fix a a regression?

**Comment by ewolinetz** [comment]
@sdodson correct

**Comment by ewolinetz** [comment]
http://pastebin.test.redhat.com/468050

**Comment by lukas-vlcek** [comment]
Closing in favour of #3766

**Pull request closed without merging**
