### PR TITLE
Add masterConfig.volumeConfig.dynamicProvisioningEnabled

### LINKED ISSUE #1759: Allow opt-out of Dynamic Provisioning
Dynamic provisioning is on by default in Kube and Origin.  A feature flag was recently added to disable the default provisioning functionality.

The new feature flag is "DynamicProvisioningEnabled" and a missing config value defaults to True.

https://github.com/openshift/origin/pull/8426

### PR DESCRIPTION
**Pull request by sdodson**
Fixes #1759

### CODE REVIEW

**Comment by sdodson** [comment]
@markturansky please take a look, thanks

**Comment by markturansky** [comment]
I don't know ansible at all, but the flag is correct and from the filenames, I think the defaults look correct.

OSO and Dedicated have their own set of ansible scripts where this would be disabled?

**Comment by sdodson** [comment]
> OSO and Dedicated have their own set of ansible scripts where this would be disabled?

It's my understanding that they pull our ansible code. They'd want to set openshift_master_dynamic_provisioning_enabled=False in their inventories. They should know how to do that. As long as the config file templates are correct i'm happy.

**Comment by sdodson** [comment]
aos-ci-test

**Comment by detiber** [comment]
@dak1n1 this will require a new variable be set to disable the dynamic provisioning for Ops:
```
openshift_master_dynamic_provisioning_enabled=False
```

**Comment by markturansky** [comment]
@detiber got an issue in the private repo to track that:  https://github.com/openshift/online/issues/109

**Comment by dak1n1** [comment]
:+1:

**Pull request merged**
