### PR TITLE
Fix unsafe boolean handling on use_dnsmasq

### PR DESCRIPTION
**Pull request by sdodson**
Some installs seem to be getting openshift.master.dns_port = 8053 here https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_master/defaults/main.yml#L12-L15 but in the template openshift.master.dns_port = 53 https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_master/templates/master.yaml.v1.j2#L57

Before this change see that iptables and config mismatch
```
$ iptables -nL | grep 53 && grep -e 53 -e dns /etc/origin/master/master-config.yaml /etc/ansible/facts.d/openshift.fact"
master1
  ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            state NEW tcp dpt:8053
  ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            state NEW udp dpt:8053
  /etc/origin/master/master-config.yaml:dnsConfig:
  /etc/origin/master/master-config.yaml:  bindAddress: 0.0.0.0:53
master2
  ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            state NEW tcp dpt:8053
  ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            state NEW udp dpt:8053
  /etc/origin/master/master-config.yaml:dnsConfig:
  /etc/origin/master/master-config.yaml:  bindAddress: 0.0.0.0:53
master3
  ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            state NEW tcp dpt:53
  ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            state NEW udp dpt:53
  /etc/origin/master/master-config.yaml:dnsConfig:
  /etc/origin/master/master-config.yaml:  bindAddress: 0.0.0.0:53
```

After this change (apply patch, re-run config playbook)
```
master1
    ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            state NEW tcp dpt:8053
    ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            state NEW udp dpt:8053
    ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            state NEW tcp dpt:53
    ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            state NEW udp dpt:53
    /etc/origin/master/master-config.yaml:dnsConfig:
    /etc/origin/master/master-config.yaml:  bindAddress: 0.0.0.0:53
master2
    ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            state NEW tcp dpt:53
    ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            state NEW udp dpt:53
    /etc/origin/master/master-config.yaml:dnsConfig:
    /etc/origin/master/master-config.yaml:  bindAddress: 0.0.0.0:53
master3
    ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            state NEW tcp dpt:8053
    ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            state NEW udp dpt:8053
    ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            state NEW tcp dpt:53
    ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            state NEW udp dpt:53
    /etc/origin/master/master-config.yaml:dnsConfig:
    /etc/origin/master/master-config.yaml:  bindAddress: 0.0.0.0:53
```

### CODE REVIEW

**Comment by abutcher** [comment]
aos-ci-test

**Comment by sdodson** [comment]
Only thing I can think of is that roles/openshift_master/defaults/main.yml is evaluated before the role dependencies are called but the template is evaluated after the dependencies.

**Comment by brenton** [comment]
@detiber

**Comment by sdodson** [comment]
@andrewklau can you check to see if you're hitting this problem?

**Comment by detiber** [comment]
@brenton lgtm, mobile site is not letting me merge though

**Comment by sdodson** [comment]
Lets wait a bit, still testing.

**Comment by sdodson** [comment]
Ok, the problem is happening because the base package isn't installed at before we start looking at version_gte_3_2_or_1_2 which defaults to True in that [case](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_facts/library/openshift_facts.py#L839-L842). So the fact that playbooks were re-run in the test cluster are the real reason that the problem was fixed. This also explains why the first master is fine but other masters aren't because openshift_master_certificates has installed the base package on the first master before it configures the firewall. Testing a fix right now.

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Pull request merged**
