### PR TITLE
test/aws: copy criotested cert if it was mounted by CI

### PR DESCRIPTION
**Pull request by vrutkovs**
Switch to CRI-O from criotested repo.

This does the following:
* Update MCD port
* Wait for scaledup machines to become running
* Avoid templating crio config - change only `pause_image` and `pause_command`
* test/aws: copy `ops-mirror.pem` certificate to target systems to access the repo and install new CRIO

### CODE REVIEW

**Comment by mtnbikenc** [comment]
Looks like no changes in the new push.
/lgtm

**Comment by vrutkovs** [comment]
Right, had to force-push so that the new AWS secret would be picked up - works now

**Comment by vrutkovs** [comment]
Fixed the path to `injected/dynamic`

**Comment by mtnbikenc** [comment]
Hash change.
/lgtm

**Comment by mtnbikenc** [comment]
'addresses' has empty IPs:
```yaml
        status:
          addresses:
          - address: ''
            type: ExternalDNS
          - address: ''
            type: InternalDNS
```

**Comment by mtnbikenc** [comment]
Two failed tests:
```
Failing tests:

[Feature:DeploymentConfig] deploymentconfigs keep the deployer pod invariant valid [Conformance] should deal with config change in case the deployment is still running [Suite:openshift/conformance/parallel/minimal]
[sig-api-machinery] Namespaces [Serial] should ensure that all pods are removed when a namespace is deleted [Conformance] [Suite:openshift/conformance/serial/minimal] [Suite:k8s]
```

**Comment by vrutkovs** [comment]
```
Failing tests:
[Feature:DeploymentConfig] deploymentconfigs keep the deployer pod invariant valid [Conformance] should deal with config change in case the deployment is still running [Suite:openshift/conformance/parallel/minimal]
[sig-api-machinery] Namespaces [Serial] should ensure that all pods are removed when a namespace is deleted [Conformance] [Suite:openshift/conformance/serial/minimal] [Suite:k8s]
```

**Comment by mtnbikenc** [comment]
```
Failing tests:

[Conformance][Area:Networking][Feature:Router] The HAProxy router should enable openshift-monitoring to pull metrics [Suite:openshift/conformance/parallel/minimal]
[Feature:DeploymentConfig] deploymentconfigs when run iteratively [Conformance] should only deploy the last deployment [Suite:openshift/conformance/parallel/minimal]
```

**Comment by vrutkovs** [comment]
```
Failing tests: 
[Conformance][Area:Networking][Feature:Router] The HAProxy router should enable openshift-monitoring to pull metrics [Suite:openshift/conformance/parallel/minimal] [sig-api-machinery] Namespaces [Serial] should ensure that all pods are removed when a namespace is deleted [Conformance] [Suite:openshift/conformance/serial/minimal] [Suite:k8s]
```

Router issue has occurred again, lets have another
/retest
and see if that happens again

**Comment by vrutkovs** [comment]
```
Failing tests:

[Conformance][Area:Networking][Feature:Router] The HAProxy router should enable openshift-monitoring to pull metrics [Suite:openshift/conformance/parallel/minimal]
[Feature:DeploymentConfig] deploymentconfigs when run iteratively [Conformance] should only deploy the last deployment [Suite:openshift/conformance/parallel/minimal]
```

**Comment by vrutkovs** [comment]
Replaced by #11203

**Pull request closed without merging**
