### PR TITLE
Update to CloudForms 4.6.2 templates

### PR DESCRIPTION
**Pull request by simaishi**
The latest CloudForms templates that go with CF 4.6.2 release.

I'm updating https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_examples/files/examples/v3.10 as well, just to keep the files in sync with`roles/openshift_management/files/templates/cloudforms` but I don't know if CF 4.6 works on v3.10 or not...

cc @sdodson

### CODE REVIEW

**Comment by sdodson** [comment]
bot, add author to whitelist

**Comment by sdodson** [comment]
bot, retest this please

**Comment by vrutkovs** [comment]
bot, retest this please

**Pull request merged**
