### PR TITLE
Add prometheus.io/port to avoid unreachable targets

### PR DESCRIPTION
**Pull request by mcanevet**

### CODE REVIEW

**Comment by sdodson** [comment]
bot, test pull request

**Comment by zgalor** [comment]
@mcanevet Could you explain why this is required?

**Comment by mcanevet** [comment]
@zgalor without this PR, a target for each port exported by containers in the prometheus pod is created in Prometheus (8443, 9090, 9443, 9099 and 9093). But only the only target reachable by prometheus is 8443, so this PR removes unreachable targets from the prometheus configuration.

**Comment by mcanevet** [comment]
@zgalor done : https://github.com/openshift/origin/pull/17422

**Comment by michaelgugino** [comment]
is this port hard-coded, or should it be configurable?

**Comment by mcanevet** [comment]
I'm not sure it makes sense to have it configurable as it is the port exposed by the service itself.

**Comment by zgalor** [comment]
oauth-proxy 8443 port is non-configurable so there is no point in making the annotation configurable

**Comment by michaelgugino** [comment]
When https://github.com/openshift/origin/pull/17422 merges, ping me and I'll merge this one.

/lgtm

**Pull request closed without merging**
