### PR TITLE
Remove kube-nfs-volumes role

### PR DESCRIPTION
**Pull request by wongma7**
let's obsolete it. @jsafrane

### CODE REVIEW

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Comment by wongma7** [comment]
merge failed because of https://github.com/openshift/origin/issues/13536

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
flake on https://github.com/openshift/origin/issues/13536
[merge]

**Pull request merged**
