### PR TITLE
Add critical pod annotation so that descheduler does not evict itself or does not get evicted by others.

### PR DESCRIPTION
**Pull request by aveshagarwal**
Testing looks good.

@ravisantoshgudimetla @ingvagabund @sjenning

### CODE REVIEW

**Comment by michaelgugino** [comment]
@aveshagarwal This is deprecated? https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/#rescheduler-guaranteed-scheduling-of-critical-add-ons

**Comment by aveshagarwal** [comment]
> @aveshagarwal This is deprecated? https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/#rescheduler-guaranteed-scheduling-of-critical-add-ons

Yes it is temporary until priority and preemption becomes available in 3.11. See other similar PR already merged: https://github.com/openshift/openshift-ansible/pull/8119

**Comment by michaelgugino** [comment]
@aveshagarwal I'm not familiar with CronJobs, so maybe this doesn't apply, but the docs explicitly state that in order for this to work the Pod needs to be apart of the kube-system namespace, like so: https://github.com/openshift/openshift-ansible/pull/8119/files#diff-5e5cd9365d8905fca9ac98bde4b12d24R5

**Comment by aveshagarwal** [comment]
> @aveshagarwal I'm not familiar with CronJobs, so maybe this doesn't apply, but the docs explicitly state that in order for this to work the Pod needs to be apart of the kube-system namespace, like so: https://github.com/openshift/openshift-ansible/pull/8119/files#diff-5e5cd9365d8905fca9ac98bde4b12d24R5

No, that requirement is now upstream only. See this PR that adds the support for all "openshift-*" name spaces:  https://github.com/openshift/origin/pull/19104

**Comment by vrutkovs** [comment]
bot, retest this please

**Pull request merged**
