### PR TITLE
dockergc: change image name to ose-control-plane

### PR DESCRIPTION
**Pull request by giuseppe**
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1585984

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
@sdodson PTAL

**Comment by runcom** [comment]
thanks @giuseppe !

**Comment by sdodson** [comment]
bot, retest this please

**Comment by sdodson** [comment]
Thanks, if this doesn't merge by the morning ping me and i'll merge it.

**Pull request merged**
