### PR TITLE
Bz1467824 - Prevent node container volumes from leaking

### PR DESCRIPTION
**Pull request by sdodson**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1467824

### CODE REVIEW

**Comment by sdodson** [comment]
@vikram-redhat PTAL

**Comment by sdodson** [comment]
aos-ci-test

**Comment by vikram-redhat** [comment]
@sdodson did you mean to tag Vivek Goyal instead of me? I can't seem to tag him myself here to clarify.

**Comment by sdodson** [comment]
Yes, sorry.

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[test]

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by michaelgugino** [comment]
Link bug closed.  Closing this PR as it's not longer valid.

**Pull request closed without merging**
