### PR TITLE
CFME: Set image change triggers to auto=true for OCP 3.4

### PR DESCRIPTION
**Pull request by simaishi**
(https://github.com/ManageIQ/manageiq-pods/pull/88)

### CODE REVIEW

**Comment by simaishi** [comment]
@bazulay @fbladilo please review

**Comment by fbladilo** [comment]
@simaishi :+1: That will do.

**Comment by bazulay** [comment]
LGTM :+1:

**Comment by sdodson** [comment]
Can you get the content in v1.5 directory as well in a separate commit?

**Comment by simaishi** [comment]
@sdodson Didn't realize there was v1.5 directory... Changed there as well.

**Pull request merged**
