### PR TITLE
Add support for setting identity provider custom values

### PR DESCRIPTION
**Pull request by detiber**
Add support for setting identity provider custom values
- htpasswd users
- ldap ca file
- openid ca file
- request_header ca file

Resolves https://github.com/openshift/openshift-ansible/issues/1661

### CODE REVIEW

**Comment by detiber** [comment]
@simon3z It's not quite ready yet, but wanted to let you know this is here for tracking purposes.

**Comment by simon3z** [comment]
@detiber I assume that by the virtue of being in `openshift_master/templates` it's expanded to all masters, right?

**Comment by detiber** [comment]
That is correct, if the variables are specified they are managed for all masters.

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
@sdodson @abutcher ptal, this should be about ready to go now.

**Comment by abutcher** [comment]
lgtm

**Pull request merged**
