### PR TITLE
Remove unused imagestream of registry-console

### PR DESCRIPTION
**Pull request by nak3**
Currently ImageStream was configured in registry-console template
(registry-console.yaml), however the ImageStream was not used from any
resources. DC in the template refers image on
registry.access.redhat.com or dockerhub.

This patch removes the unused ImageStream to avoid confusion.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1583093

### CODE REVIEW

**Comment by vrutkovs** [comment]
The patch looks good, but wouldn't it be easier to use this imagestream tag instead? This is the way we deploy SDN:
* [Add a trigger to resolve imagestreamtag image and update the deployment](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_sdn/files/sdn.yaml#L10)
* [set `image` to " "](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_sdn/files/sdn.yaml#L39) so it would be updated by Openshift

**Comment by nak3** [comment]
@vrutkovs Thank you. Updated DeploymentConfig to refer to the ImageStream. It will need some change on upgrade playbook to patch these changes, though.

**Comment by vrutkovs** [comment]
>It will need some change on upgrade playbook to patch these changes, though.

I hope it won't be required - a new template would be imported, registry-console would be rebuilt from template and a new deployment would use ImageStreamTag. I haven't tested it yet though

**Comment by vrutkovs** [comment]
Registry-console was not redeployed on update, I'll create a new PR

/lgtm

**Pull request merged**
