### PR TITLE
[release-3.11] Fix OpenShift SDN/OVS pod restart during upgrades

### PR DESCRIPTION
**Pull request by mtnbikenc**
Fix OpenShift SDN/OVS pod restart during upgrades

When the OpenShift SDN/OVS DaemonSets were upgraded during control plane
upgrades with an updateStrategy of RollingUpdate, an upgrade of the pods
in the entire cluster was performed.  This caused unexpected network and
application outages on nodes.

This patch updates the following:
* Changed the updateStrategy for SDN/OVS pods to OnDelete in the template,
  affects new installs.
* Added control plane upgrade task to modify SDN/OVS daemonsets to use
  OnDelete updateStrategy
* Added node upgrade task to delete all SDN/OVS pods while nodes are drained

Network outages for nodes should only occur during the node upgrade when
nodes are drained.

Reverts #10910 
Forward ports #11050

### CODE REVIEW

**Comment by mtnbikenc** [comment]
Waiting for testing feedback on changes to 3.10.
/hold

**Comment by squeed** [comment]
Seems reasonable to me. Definitely check that, after the upgrade is finished, both the `ovs` and `sdn` daemonsets are fully upgraded across the cluster (it's hard for me to tell if the playbooks accomplish that).

**Comment by sdodson** [comment]
/hold cancel
Internal teams have confirmed that applying this change resolved their problems during upgrade.

**Pull request merged**
