### PR TITLE
Upgrade to etcd 3.2

### PR DESCRIPTION
**Pull request by sdodson**
It's got wonderful fixes that we'd enjoy having.

### CODE REVIEW

**Comment by sdodson** [comment]
@smarterclayton Do we also want to upgrade folks to etcd-3.2 during v3.6 upgrades?

**Comment by michaelgugino** [comment]
I'm not familiar with this path, but it looks like a simple change and matches the bits above it.

/lgtm

**Comment by smarterclayton** [comment]
@sdodson re: your question about upgrading, we should, but it can
potentially wait.

**Pull request merged**
