### PR TITLE
Include object validation in 3.6 upgrades

### PR DESCRIPTION
**Pull request by sdodson**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1428934

### CODE REVIEW

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
I was going to move these up to a common upgrade validator but then realized that the 3.5 validator has some 3.5 specific checks. I'm worried that the notion of petsets may have been removed entirely from 3.6 so we wouldn't want to run the 3.5 petset check on 3.6.

**Comment by sdodson** [comment]
aos-ci-test

**Comment by abutcher** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Pull request merged**
