### PR TITLE
adding container.yaml

### PR DESCRIPTION
**Pull request by adammhaile**
@sdodson This is for testing the new ODCS requirements as we discussed.

### CODE REVIEW

**Comment by sdodson** [comment]
This file should probably be exempt from yaml linting, but the fix looks straight forward enough, can we update it to remove the whitespace?

images/installer/container.yaml:
  14:1      error    too many blank lines (1 > 0)  (empty-lines)

**Comment by adammhaile** [comment]
@sdodson how dare the yaml rules be different from python.
Fixed now.

**Comment by adammhaile** [comment]
@sdodson that file should lint fine now

**Pull request merged**
