### PR TITLE
fixes to better deal with gce image defaults

### PR DESCRIPTION
**Pull request by detiber**
- remove exception if INPUT rules are not found, gce centos-7 image is stripped of
  default rules
- ignore_errors for systemctl mask operation, fails with permission denied on
  gce centos-7 image.

### CODE REVIEW

**Comment by detiber** [comment]
@jwhonce This is the issue you were running into.

**Comment by jwhonce** [comment]
@detiber FYI The GCE playbooks/roles used to deploy libra-rhel7 image.  The centos images have never been tested against.

**Comment by detiber** [comment]
@jwhonce yeah, I wanted to avoid using the libra-rhel7 image for origin deployments since it is a private ami

**Comment by detiber** [comment]
@jwhonce I verified these changes after doing the pylint updates.
Passing `--deployment-type=online` when running bin/cluster or setting `DEPLOYMENT_TYPE=online` in the environment retains the previous behavior of installing the libra-rhel7 image and the internal repos. Only when deployment_type is origin (which is now the default) is the centos-7 image used as well as the public copr repo.

**Pull request merged**
