### PR TITLE
Adding support for an SSL certificate signed by the OpenStack cluster

### PR DESCRIPTION
**Pull request by dcritch**
This change will enable specifying a self-signed certificate from the OpenStack cluster to communicate with it via SSL.

The certificate can be supplied as a variable of the form:
openshift_cloudprovider_openstack_ca_file: |
  -----BEGIN CERTIFICATE-----
  <...snip...>
  -----END CERTIFICATE-----

@celebdor

### CODE REVIEW

**Comment by vrutkovs** [comment]
bot, test pull request

**Comment by tzumainn** [comment]
@dcritch This looks great - thanks for submitting the PR!

Could you also update the documentation? https://github.com/openshift/openshift-ansible/blob/master/playbooks/openstack/configuration.md#openstack-with-ssl-configuration

**Comment by dcritch** [comment]
@tzumainn thanks! updated the doc as requested: https://github.com/dcritch/openshift-ansible/blob/openstack-ssl-cert/playbooks/openstack/configuration.md#openstack-with-ssl-configuration

**Pull request merged**
