### PR TITLE
Reserve kubernetes and 'kubernetes-' prefixed namespaces

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by enj** [comment]
LGTM

**Comment by enj** [comment]
aos-ci-test

**Comment by sdodson** [comment]
Checking with CD team as to why the image is 3.6.52 but the RPM repo only has 3.6.50.

**Comment by sdodson** [comment]
aos-ci-test

**Comment by ingvagabund** [comment]
[merge]

**Comment by sdodson** [comment]
flake on https://github.com/openshift/origin/issues/14161
[merge]

**Pull request merged**
