### PR TITLE
fix descheduler pod should be critical pod

### PR DESCRIPTION
**Pull request by wjiangjay**
Fix https://bugzilla.redhat.com/show_bug.cgi?id=1579200

### CODE REVIEW

**Comment by wjiangjay** [comment]
@aveshagarwal @ingvagabund @ravisantoshgudimetla help review this, thx

**Comment by ingvagabund** [comment]
@aveshagarwal @ravisantoshgudimetla lgtm, waiting for you to review it in case there is more to fix.

**Comment by aveshagarwal** [comment]
@wjiangjay thanks.

**Pull request merged**
