### PR TITLE
byo inventory versions 3.5 -> 3.6

### PR DESCRIPTION
**Pull request by ashcrow**
https://bugzilla.redhat.com/show_bug.cgi?id=1448998

### CODE REVIEW

**Comment by ashcrow** [comment]
aos-ci-test

**Comment by sdodson** [comment]
Err, do you mind getting hosts.origin.example too? It should be s/1.5/3.6/ too since versioning has converged.

**Comment by ashcrow** [comment]
@sdodson sure.

**Comment by ashcrow** [comment]
aos-ci-test

**Comment by ashcrow** [comment]
@sdodson ⬆️

**Comment by sdodson** [comment]
docs only, merging.

**Pull request merged**
