### PR TITLE
update xpaas imagestreams to explicitly import tags

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@sdodson ptal

**Comment by sdodson** [comment]
Should we just bump xPaaS to ose-v1.4.7 where they added this https://github.com/jboss-openshift/application-templates/commit/411ffde500d70382a89eb42e6ab40d1f0bd7536c ? I'm fine either way, we've just very deliberately not made any downstream changes to their content in the past.

**Comment by bparees** [comment]
@sdodson i pulled this from what is in the v3.6 dir of the v3.7 branch currently, i figured that was safest.

**Comment by bparees** [comment]
(basically i guess i'd prefer to do the minimal change here)

**Comment by sdodson** [comment]
/approve
/lgtm
CI will fail most likely, i'll merge if so.

**Pull request merged**
