### PR TITLE
Adding proxy env vars for dc/docker-registry

### PR DESCRIPTION
**Pull request by mangirdaz**
Port back registry proxy settings to release-3.6

### CODE REVIEW

**Comment by mangirdaz** [comment]
@kwoodson porting your change into release-3.6. Please review. This is blocking our "golive" now so appreciate fast response :)

**Comment by kwoodson** [comment]
@mangirdaz, have you confirmed that this fixes your issue?  I know we had some back and forth with QE that said there were still some outstanding issues.  If you can confirm we can move this along.

**Comment by mangirdaz** [comment]
@kwoodson validating now with client... "they ran into other issue" so let's hold the horses until tomorrow so we can make sure we didn't left anything hanging.

**Comment by mangirdaz** [comment]
@kwoodson this works and solves the problems.

**Comment by kwoodson** [comment]
@sdodson, Let's get this backported to 3.6 with this PR.  @mangirdaz tested these changes and this looks good.

**Comment by sdodson** [comment]
Please link to the master branch PR.

**Comment by sdodson** [comment]
https://github.com/openshift/openshift-ansible/pull/5148

**Pull request merged**
