### PR TITLE
Make sure to include upgrade_pre when upgrading master nodes

### PR DESCRIPTION
**Pull request by sdodson**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1542399

### CODE REVIEW

**Comment by sdodson** [comment]
@michaelgugino seems like if upgrade_pre.yml is always required we should just make it a step in upgrade.yml ?

**Comment by michaelgugino** [comment]
@sdodson for nodes, upgrade_pre runs in a non-serial play, which will save large environments tons of time.

**Pull request merged**
