### PR TITLE
Update etcd pod to 3.2.22

### PR DESCRIPTION
**Pull request by sdodson**

### CODE REVIEW

**Comment by rphillips** [comment]
@sdodson Does this etcd image need to be qualified with the specified version as well? [etcd.yaml](https://github.com/openshift/openshift-ansible/blob/37e2c16d10c3b56005bb8e84f1af9d41f49cbe7d/roles/etcd/files/etcd.yaml#L16)

It brings in any 3.3 point release.

**Comment by sdodson** [comment]
> @sdodson Does this etcd image need to be qualified with the specified version as well? etcd.yaml

We patch the pod definition with etcd_image defined via roles/etcd/defaults/main.yml

https://github.com/openshift/openshift-ansible/blob/master/roles/etcd/tasks/static.yml#L55-L70

We should make it more clear that what's actually in the file is a dummy value that's always overwritten... also lets verify it's *always* overwritten.

**Comment by sdodson** [comment]
> We need to change the yaml from a static file to a template and use etcd_image to populate the image path in the pod spec.

Yeah, that's better implementation.

**Pull request merged**
