### PR TITLE
add support for vsphere-volume registry and other services

### PR DESCRIPTION
**Pull request by dav1x**
This adds support for volume annotations and by extension support for vsphere-volume.

### CODE REVIEW

**Comment by dav1x** [comment]
Resolves BZ - https://bugzilla.redhat.com/show_bug.cgi?id=1548163

**Comment by sdodson** [comment]
@dav1x can you check the pylint failures in the travis job?

**Comment by dav1x** [comment]
@sdodson ahh. The modified function returns 5 values with the addition of annotations. I'll need to add an unused var to the other functions that reference it for: build_pv_nfs, build_pv_openstack and build_pv_glusterfs.

**Comment by michaelgugino** [comment]
Close/reopen to trigger latest tests.

**Pull request merged**
