### PR TITLE
[release-3.10] Avoid using aliases which are prone to discovery problems

### PR DESCRIPTION
**Pull request by sdodson**
Backports #11342

### CODE REVIEW

**Comment by vrutkovs** [comment]
Seems it needs b40a8c31f657b573152c517088bb3beb78bfe244 here too

**Comment by sdodson** [comment]
@vrutkovs Caught it up with where release-3.11 was. I was thinking of squashing out some of the reverted changes, do you think I should or leave it more 1 to 1 with commits from release-3.11?

**Comment by vrutkovs** [comment]
Lets leave commits as is - it would be easier to track those

/lgtm

**Comment by sdodson** [comment]
I'll merge if it flakes again.

**Pull request merged**
