### PR TITLE
Fix openshift_image_tag=latest.

### LINKED ISSUE #3045: openshift_image_tag=latest broken again
https://github.com/openshift/openshift-ansible/pull/2882 allowed for `openshift_image_tag=latest`.
I think is was broken shortly thereafter with https://github.com/openshift/openshift-ansible/pull/2855 afaict

```
deployment_type=origin
openshift_image_tag=latest
```

```
TASK [openshift_master_facts : set_fact] ***************************************
fatal: [origin-master.local.variantweb.net]: FAILED! => {"failed": true, "msg": "Unknown short_version atest"}
```

Looks like a code path is assuming the first character of the image tag is 'v' and removing it.

### PR DESCRIPTION
**Pull request by abutcher**
Fixes #3045

### CODE REVIEW

**Comment by sjenning** [comment]
```
TASK [openshift_version : Set containerized version to configure if openshift_image_tag specified] ***
fatal: [origin-master.local.variantweb.net]: FAILED! => {"failed": true, "msg": "template error while templating string: expected token 'name', got 'string'. String: {{ openshift_image_tag[1:].split('-')[0] if openshift_image_tag is not 'latest' else openshift_image_tag }}"}
```

**Comment by abutcher** [comment]
aos-ci-test

**Comment by abutcher** [comment]
@sjenning I think the issue was with the comparison. I'm able to complete an install with `openshift_image_tag=latest` with the updates.

**Comment by sjenning** [comment]
WFM thanks!

**Comment by abutcher** [comment]
aos-ci-test

**Pull request merged**
