### PR TITLE
Bug 1287977 - Incorrect check output from atomic-openshift-installer …

### PR DESCRIPTION
**Pull request by brenton**
…when working with preconfigured load balancer

### CODE REVIEW

**Comment by brenton** [comment]
supersedes https://github.com/openshift/openshift-ansible/pull/1017

**Comment by brenton** [comment]
@smunilla, @dgoodwin, PTAL

**Comment by smunilla** [comment]
:+1:

**Comment by dgoodwin** [comment]
LTGM as well.

**Comment by brenton** [comment]
@smunilla, @dgoodwin, I also added a commit to improve our output when gathering facts.  It was being lost before.

**Pull request merged**
