### PR TITLE
announce transition to samples operator for example imagestreams and …

### PR DESCRIPTION
**Pull request by gabemontero**
…templates

@bparees @sdodson @jwforres  PTAL

Also, any opinions on what additional communication channels should be used to alert folks like the xpaas team, cfme team, etc. ?  Minimally names of folks to email perhaps ...

### CODE REVIEW

**Comment by gabemontero** [comment]
fyi I am already in communication with the folks responsible for the ppc64le support

**Comment by sdodson** [comment]
@rcernich and @knrc would be the folks I'd notify about this change.

**Comment by bparees** [comment]
i don't think ansible is even going to exist anymore in v4, so I don't think this is useful

also i don't think anyone needs to be notified.  it's our job (as the samples operator owner) to continue to ship the content that ansible used to ship.

**Comment by gabemontero** [comment]
On Fri, Sep 14, 2018 at 11:54 AM, Ben Parees <notifications@github.com>
wrote:

> i don't think ansible is even going to exist anymore in v4, so I don't
> think this is useful
>
> also i don't think anyone needs to be notified. it's our job (as the
> samples operator owner) to continue to ship the content that ansible used
> to ship.
>
But content will evolve after 4.0 GA's .... sure, these README updates may
not be the final answer, but this is
my attempt to initiate the reset on the expectations on the process of
injecting new content moving forward.

**Comment by sdodson** [comment]
openshift-ansible will continue to exist but should only be responsible for deploying container runtimes and kubelet on RHEL hosts then handing off to new installer for the rest. Once we have a method to bootstrap 4.0 API, Controllers, and CVO this role should definitely be removed entirely.

**Comment by gabemontero** [comment]
The jboss umbrella of prods appears engaged now wrt updating openshift/library and the eventual removal of the openshift_examples role

Per @bparees 's objection nuking this PR

**Pull request closed without merging**
