### PR TITLE
Custom cors configuration 

### PR DESCRIPTION
**Pull request by spinolacastro**

### CODE REVIEW

**Comment by brenton** [comment]
This looks good to me.  I'm going to include this in a batch of PRs to be tested by our QE team.

**Comment by detiber** [comment]
@spinolacastro can you cleanup this PR to remove the 0235e00 and ae40756 commits?

otherwise :+1: from me.

**Comment by spinolacastro** [comment]
@detiber Done

**Comment by detiber** [comment]
@brenton No further blockers from my side.

**Comment by brenton** [comment]
I was hoping to find time to update a branch that QE has tested that included like 10 PRs.  They tested this one already and didn't find any problems so I'm just going to go ahead and merge it.

**Pull request merged**
