### PR TITLE
Standardize use of byo and common for network_manager.yml

### PR DESCRIPTION
**Pull request by mtnbikenc**
The openshift-node/network_manager.yml playbook does not follow the same pattern as other playbooks to have a 'common' part and a 'byo' part.  This PR splits the tasks as appropriate.

Depends on #3895

### CODE REVIEW

**Comment by kwoodson** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
[merge]

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
Flake https://github.com/openshift/origin/issues/12544

**Comment by mtnbikenc** [comment]
[merge]

**Comment by mtnbikenc** [comment]
Flake https://github.com/openshift/origin/issues/13705 Dumping container logs
Flake https://github.com/openshift/origin/issues/13067 oc new-app [It] should succeed with a --name of 58 characters
[merge]

**Pull request merged**
