### PR TITLE
Add some tests for utils to get the coverage up

### PR DESCRIPTION
**Pull request by tbielawa**
Just tests.

### CODE REVIEW

**Comment by tbielawa** [comment]
aos-ci-test

**Comment by tbielawa** [comment]
@smunilla @abutcher PTAL

**Comment by smunilla** [comment]
I'm @smunilla and I approve of this change :+1:

**Comment by tbielawa** [comment]
aos-ci-test

**Comment by tbielawa** [comment]
aos-ci-test

**Comment by tbielawa** [comment]
aos-ci-test

**Comment by tbielawa** [comment]
aos-ci-test

**Comment by sdodson** [comment]
3.4 test is a flake

**Pull request merged**
