### PR TITLE
Properly pass the "external network" option to the HEAT template

### LINKED ISSUE #471: External network is stucked at default value
Current version (2cbba20205318b3c16b7aa8cd2693e2838c547c1) of master branch seems ignored `-o external_net` and `-o floating_ip_pools` parameters and always use `External` as external network name. This make the creation failed when external network is named other than 'external'.

### PR DESCRIPTION
**Pull request by lhuard1A**
and cleanup OpenStack options a little bit…

Fixes #471

### CODE REVIEW

**Comment by lhuard1A** [comment]
@xionglingfeng Could you please check that this PR fixes the issue #471 that you reported?

**Comment by xionglingfeng** [comment]
@lhuard1A Tested and worked. Thank you!

**Comment by lhuard1A** [comment]
@detiber @wshearn : Could you please have a look at this one?

**Comment by wshearn** [comment]
@detiber this looks good to me :+1:

**Comment by detiber** [comment]
@wshearn :+1:  here, please merge.

**Pull request merged**
