### PR TITLE
Add organizations attribute to github identity provider

### PR DESCRIPTION
**Pull request by detiber**
resolves https://github.com/openshift/openshift-ansible/issues/1360

### CODE REVIEW

**Comment by detiber** [comment]
aos-ci-test

**Comment by abutcher** [comment]
```
openshift_master_identity_providers=[{'name': 'github', 'login': 'true', 'challenge': 'false', 'kind': 'GitHubIdentityProvider', 'clientID': '324234234134234', 'clientSecret': '234234234234234', 'organizations': ['myorgname', 'anotherorgname']}]
```

```
  identityProviders:
  - challenge: false
    login: true
    name: github
    provider:
      apiVersion: v1
      clientID: '324234234134234'
      clientSecret: '234234234234234'
      kind: GitHubIdentityProvider
      mappingMethod: claim
      organizations:
      - myorgname
      - anotherorgname
```

@detiber LGTM. On a side note I think `mappingMethod` is in the wrong place. The docs have it at the same level as `challenge` or `name`.

**Comment by detiber** [comment]
@abutcher how the mappingMethod has been broken in that way for so long, I have no idea ;)

**Comment by detiber** [comment]
aos-ci-test

**Comment by detiber** [comment]
@abutcher mind taking another look now?

**Comment by abutcher** [comment]
```
  identityProviders:
  - challenge: false
    login: true
    mappingMethod: claim
    name: github
    provider:
      apiVersion: v1
      clientID: '324234234134234'
      clientSecret: '234234234234234'
      kind: GitHubIdentityProvider
      organizations:
      - myorgname
      - anotherorgname
```

@brenton :+1:

**Comment by brenton** [comment]
@detiber, want to squash the commits?

**Comment by detiber** [comment]
@brenton done.

**Pull request merged**
