### PR TITLE
Update atomic ci origin image to 1.5.1.

### PR DESCRIPTION
**Pull request by abutcher**

### CODE REVIEW

**Comment by abutcher** [comment]
@sdodson Also needed to revert "Add /etc/sysconfig/etcd to etcd_container" for tests to pass.

**Comment by ingvagabund** [comment]
> Also needed to revert "Add /etc/sysconfig/etcd to etcd_container" for tests to pass.

@abutcher why is that needed?

**Comment by abutcher** [comment]
@ingvagabund Let me see if I can find that log. I should have linked it in here but etcd was unable to start due to missing that file.

**Comment by sdodson** [comment]
Fine with reverting that commit for now, we should get https://github.com/openshift/openshift-ansible/pull/3999 merged into master and then pick that into 1.5.

**Comment by abutcher** [comment]
aos-ci-test

**Comment by abutcher** [comment]
[merge]

**Pull request merged**
