### PR TITLE
[BZ1486450] Only run migrate auth for < 3.7

### PR DESCRIPTION
**Pull request by mtnbikenc**
Fixes 1486450

### CODE REVIEW

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[test]

**Comment by sdodson** [comment]
@jupierce which branch do you need this in? stage?

**Comment by jupierce** [comment]
@sdodson Master is fine. Thanks.

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
[merge]

**Comment by mtnbikenc** [comment]
Flake https://github.com/openshift/origin/issues/16005
[merge]

**Comment by mtnbikenc** [comment]
Second flake https://github.com/openshift/origin/issues/16005
Merging.

**Pull request merged**
