### PR TITLE
missing default variables cause curator to fail

### PR DESCRIPTION
**Pull request by josefkarasek**

### CODE REVIEW

**Comment by josefkarasek** [comment]
fixes github.com/openshift/origin-aggregated-logging/pull/1114

**Comment by ewolinetz** [comment]
/hold
we may want to use `| default(omit)` instead so that we can force the default value evaluation into the subrole

**Comment by sdodson** [comment]
/lgtm

CDN flakes

**Comment by ewolinetz** [comment]
merging to unblock origin-aggregated-logging tests

**Comment by josefkarasek** [comment]
Thanks @ewolinetz !

**Pull request merged**
