### PR TITLE
Update systemd units to use proper container service name

### PR DESCRIPTION
**Pull request by ashcrow**
- If using a system container: container-engine
- If using a package install: docker

Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1448800

### CODE REVIEW

**Comment by ashcrow** [comment]
aos-ci-test

**Comment by sdodson** [comment]
This won't affect RPM based installs, is that ok? Those systemd units are distributed in the RPMs. Would we expect RPM based installs to start using docker as a system container?

**Comment by ashcrow** [comment]
After speaking with @sdodson I'm going to add service updates to this PR as well to ensure these units get used no matter what install type is chosen.

**Comment by ashcrow** [comment]
@sdodson ⬆️

**Comment by ashcrow** [comment]
```
The command "pip install tox-travis coveralls" failed and exited with 2 during .
```

**Comment by ashcrow** [comment]
aos-ci-test

**Comment by ashcrow** [comment]
rebased to pull in coveralls fix

**Comment by ashcrow** [comment]
Hello bot?

**Comment by ashcrow** [comment]
Heh, looks like one flake. However, it hasn't caught up to test the latest version yet. 🤞 by tomorrow.

**Comment by ashcrow** [comment]
Error is excluder flake and from over 8 hours ago.

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Comment by ashcrow** [comment]
Come on bot, merge already!

**Comment by ashcrow** [comment]
[merge]

**Comment by ashcrow** [comment]
Merge failure:

```
	common.go:80: got exit code 2, want 0
	common.go:98: 
		$ (cd /data/src/github.com/openshift/openshift-ansible/test/integration/openshift_health_checker/preflight && ansible-playbook -i /dev/null playbooks/package_update_repo_disabled.yml)
```

**Comment by sdodson** [comment]
I'm afraid this may've broken upgrades. I don't think those are critical path yet so i'm not going to revert this just yet, we can investigate tomorrow.

When running playbooks/byo/openshift-cluster/upgrades/v3_6/upgrade.yml I get
```
TASK [Install Master service file] ************************************************************************************
fatal: [ose3-master.example.com]: FAILED! => {
    "changed": false, 
    "failed": true
}

MSG:

Unable to find 'atomic-openshift-master.service' in expected paths.


PLAY RECAP ************************************************************************************************************
localhost                  : ok=18   changed=0    unreachable=0    failed=0   
ose3-master.example.com    : ok=210  changed=17   unreachable=0    failed=1   
ose3-node1.example.com     : ok=178  changed=12   unreachable=0    failed=0   
```

**Comment by mtnbikenc** [comment]
@sdodson I just hit this as well when testing upgrades on my PR.

**Comment by mtnbikenc** [comment]
@sdodson It appears to be related to this case https://github.com/ansible/ansible/issues/18489.  Since the file is not really being templated (static file) I'm thinking they should be moved to `files` and use the `copy` module.  I'll work on fixing this in a PR.

**Pull request merged**
