### PR TITLE
Add role to manageiq to allow creation of projects

### PR DESCRIPTION
**Pull request by zeari**
This should allow manageiq to:
  1. request a new project, become an admin in that project,
  2. instantiate a template in that project,
  3. bind a role in that project

@deads2k Please review.

@enoodle Thanks for the help
cc @simon3z @moolitayer @zakiva

### CODE REVIEW

**Comment by simon3z** [comment]
@zeari @moolitayer @detiber should we handle upgrades?

E.g. `system:image-auditor` was added under `manage_iq_openshift_3_2_tasks`. Should we add this under `manage_iq_openshift_3_3_tasks`?

**Comment by simon3z** [comment]
cc @deads2k

**Comment by zeari** [comment]
As far as I can tell this role allows you to create projects through this process: https://docs.openshift.com/enterprise/3.0/admin_guide/selfprovisioned_projects.html

which isnt quite the same as creating a project as a cluster-admin

**Comment by deads2k** [comment]
That's the correct role and the command looks correct.

**Comment by detiber** [comment]
ok to test

**Comment by detiber** [comment]
aos-ci-test

**Comment by simon3z** [comment]
@abutcher @detiber what about this [comment](https://github.com/openshift/openshift-ansible/pull/2453#issuecomment-247275555). No need for anything related to upgrade?

**Comment by abutcher** [comment]
@simon3z the `openshift_manageiq` role is applied during upgrade in [post.yml](https://github.com/openshift/openshift-ansible/blob/master/playbooks/common/openshift-cluster/upgrades/post.yml#L13) and each task in this list will be ran. Based on CI running clean in 3.2/3.3, the added task should be okay for either version. I could be missing something...

**Pull request merged**
