### PR TITLE
service catalog: updates for upstream v0.1.16

### PR DESCRIPTION
**Pull request by jboyd01**

### CODE REVIEW

**Comment by jboyd01** [comment]
fyi @jpeeler

**Comment by sdodson** [comment]
I'm not knowledgable enough about SC to review this.
/assign jpeeler

**Comment by jpeeler** [comment]
This looks fine, but probably best for this to go in after catalog is rebased. Don't have a PR cut for it yet.

**Comment by sdodson** [comment]
Yeah, install seems to be failing on unknown flags as it is now.

**Comment by jboyd01** [comment]
@jpeeler chicken or the egg? :/

**Comment by jboyd01** [comment]
just added changes to pick up the right version of Catalog (roles/openshift_service_catalog/vars/default_images.yml) and dump out more of the logs on startup failure.

**Comment by jboyd01** [comment]
updated with quoting the v0.1

**Comment by jpeeler** [comment]
I don't think this will pass until https://github.com/openshift/aos-cd-jobs/issues/1345 is resolved.

**Pull request merged**
