### PR TITLE
Bug 1306665 - [metrics] update metrics-deployer template to use lates…

### PR DESCRIPTION
**Pull request by brenton**
…t image versions

### CODE REVIEW

**Comment by sdodson** [comment]
Interesting, for some reason I was under the impression these wouldn't be updated until 3.2 if not 3.3 so I didn't look for any updates.

**Comment by detiber** [comment]
@sdodson @brenton are we going to be releasing updates for each release? If so, then we should probably tie the version number to the binary version....  My other though is if the newer metrics-deployer template will work on older installations...

**Comment by brenton** [comment]
@detiber, hmm.. I like the idea of setting it to the version the rest of the deployment is using.  Would that mean we'd need to templatize this template?

**Comment by brenton** [comment]
Also, I'm guessing it would mean tagging the images differently in the registry.  The questions we have now for the integration services team are is whether or not the new default of 3.1.1 can safely be used in 3.1.0 environments?

**Comment by jcantrill** [comment]
@brenton from an origin perspective, there is a PR https://github.com/openshift/origin/pull/6825 to tag and build with origin releases to keep them in lockstep.  I think it makes sense to do the same with these releases as well.  @ewolinetz can you verify @brenton question using the e2e script?

**Comment by ewolinetz** [comment]
We were able to get the 3.1.1 images for metrics to install and start up on a 3.1.0 base and confirm that metrics for containers are coming in and able to get status from hawkular.

**Pull request merged**
