### PR TITLE
Allow admins to opt out of journald configuration

### PR DESCRIPTION
**Pull request by sdodson**

### CODE REVIEW

**Comment by sdodson** [comment]
CC: @stevekuznetsov

**Comment by sdodson** [comment]
@soltysh One thing I noticed is that we're also only configuring journald on masters. Is that the only place it's necessary/desired?

**Comment by sdodson** [comment]
/hold 
This may not be the source of the problems that folks are encountering as the CI jobs that are failing don't actually use the installer.

**Comment by soltysh** [comment]
> @soltysh One thing I noticed is that we're also only configuring journald on masters. Is that the only place it's necessary/desired?

Hmm... I think this should apply to all nodes, not just masters. It's the computation nodes that are actually running the pods that will suffer the problem.

> This may not be the source of the problems that folks are encountering as the CI jobs that are failing don't actually use the installer.

The installer is used in several places only and those does not seem to be affected. I'll be working on tweaking the journald manually for all tests, similarly how it's done in https://github.com/openshift/origin/pull/17758

I'd wait with this pr, we might go with other options soon, that would entirely solve our journald rate limitting problem. And most importantly would scale better.

**Comment by vrutkovs** [comment]
Master branch is closed! A major refactor is ongoing in devel-40. Changes for 3.x should be made directly to the latest release branch they're relevant to and backported from there.

**Pull request closed without merging**
