### PR TITLE
updating to the latest ec2.py (and re-patching with our changes).

### PR DESCRIPTION
**Pull request by twiest**

### CODE REVIEW

**Comment by twiest** [comment]
@a13m @detiber @brenton @wshearn @kwoodson  Hey guys, I want to update the ec2.py dynamic inventory. Ours is a bit old and crufty. I applied our usual patches to it and I tested it locally.

This is an important piece, so I wanted to make sure you guys were aware of it being updated.

@lenaic I'm not sure if you use AWS in addition to GCE, but just in case you do, I wanted to let you know about this PR so you could weigh in.

Any feedback or objections to merging this?

**Comment by menren** [comment]
We also use AWS but less than GCE. I will ask my colleagues to have a look at it

**Comment by twiest** [comment]
@menren thanks!

**Comment by twiest** [comment]
Just an FYI, there is a behavior change with this new ec2.py.

The upstream ec2.py now defaults to replacing hyphens in group names with under scores.

You can retain the old behavior setting "replace_dash_in_groups" to false in the ec2.ini file like this:
```
replace_dash_in_groups = False
```

My team plans on setting this value to false when we roll out this new inventory. This is just for the short term. In the longer term, we'll change our playbooks to use the new behavior.

The default ec2.ini in this PR has replace_dash_in_groups set to True to mirror the upstream ec2.ini. 

Should we change replace_dash_in_groups to false in our ec2.ini so we don't have a behavior change?

If we change it, we'll have to remember to always change it each time we update ec2.ini with the upstream ec2.ini.

Thoughts?

**Comment by detiber** [comment]
@twiest I think we should definitely change it for the provided ec2.ini as well, at least until the playbooks are updated.

That said, If I'm reading that right, it'll make the group naming more inline with the gce and openstack playbooks, which means we could reduce some of the duplication in all of the cloud based playbooks by at least having common group names. The last oddball outside of byo would then be the libvirt playbook, but that can be updated to use underscores instead of dashes as well.

**Comment by twiest** [comment]
@detiber ok, I changed the provided ec2.ini to default to the old behavior.

The ec2.ini now has this:
```
replace_dash_in_groups = False
```

@detiber with this change, are you a +1 on merging this PR?

I'll wait to hear back from menren and give others a chance to weigh in.

I would, however, like to merge this soon, if there aren't any objections.

**Comment by twiest** [comment]
@sdodson Sorry, I forgot to at mention you as well in the original comment. Would you mind taking a look also?

**Comment by sdodson** [comment]
I can't get to this right now and I'm not familiar with the EC2 bits. I defer to Jason's judgement.

**Comment by detiber** [comment]
@twiest :+1: from me

**Comment by arilivigni** [comment]
Testing job has been triggered.

**Comment by arilivigni** [comment]
Internal Jenkins error during triggering.
 No test results found.

**Comment by twiest** [comment]
Hey Guys, I have a +1 for merging (above), so I'm going to merge this PR on Monday, Nov 16th, unless I hear an objection.

**Comment by menren** [comment]
Hello,

I would like to test it.
Last week I started tests on AWS and I encountered issues with openshift_manage_nodes role which does not find the oo_first_master host. This test is done without this PR code.
`
GATHERING FACTS *************************************************************** 
FATAL: no hosts matched or all hosts have already failed -- aborting


TASK: [openshift_manage_nodes | Wait for Node Registration] **************** 
FATAL: no hosts matched or all hosts have already failed -- aborting

`
Today I am testing the new ec2.py
By default RDS and elasticCache are enabled in ec2.ini.
I wonder if most people are using both of them.
In our case we use none of them.

**Comment by detiber** [comment]
@menren can you provide more context into what your testing consisted of?

When spinning up an environment using the aws playbooks, there should be no issues finding the first master. However, if you attempt to run another playbook immediately, you may run into issues related to using the cached inventory. The ec2 dynamic inventory caches the data, and you may want to run `inventory/aws/hosts/ec2.py --refresh-cache` between runs to ensure that you are operating on current data.

**Comment by detiber** [comment]
@menren as far as RDS and elasticCache being enabled in the ec2.ini, I agree that it is probably not needed for the general case, but I believe that @twiest is attempting to keep the ini file that we ship as close to the upstream version as possible.

That said, it probably wouldn't hurt to fork the ec2.ini file, since we are shipping it with our repo for the use of running it with openshift-ansible.

**Comment by menren** [comment]
I have a weird bug in the `playbooks/common/openshift-node/config.yml` there are 2 ocurrences of `oo_first_master`
It's correctly done at the first call : 
`
 - name: Create node certificates
   hosts: oo_first_master
`

But the second time 
`
 - name: Set schedulability
  hosts: oo_first_master
`
ansible says that `no hosts matched or all hosts have already failed`

This issue happens with old and new ec2.py. 

By moving the 2nd call to oo_first_master earlier, ansible recognizes the host.
I am still working on it, looking for the code between the 2 calls to oo_first_master that make this fail.
On OpenStack or GCE this should seem to be fine.

I would welcome any tips on this bug

**Comment by twiest** [comment]
@menren ok, I'll wait until your testing is finished. Please let me know when that is, as I'd really like to merge this PR soon. Thanks!

**Comment by detiber** [comment]
@twiest I think it's safe to say that @menren's issue is not related to the ec2.py change.

**Comment by detiber** [comment]
@menren mind creating a gist or a pastebin of the ansible output? I suspect that the first master host failed a step at some point, and that is why you are getting the error on the later use of oo_first_master.

**Comment by menren** [comment]
Here is the stdout ansible
[log.txt](https://github.com/openshift/openshift-ansible/files/35697/log.txt)

It's a pretty verbose output.
What is interesting is in the end.

I am also testing a feature to pass openshift_pkg_version by command line. This is working well on GCE and OpenStack and should not impact this test.

There are few failed : docker restarting on master, or yum install. What do you think ?

**Comment by detiber** [comment]
@menren 
```
failed: [c14-master-375d2] => {"failed": true}
msg: Job for docker.service failed. See 'systemctl status docker.service' and 'journalctl -xn' for details.
```
Is the culprit here, once this task failed, the host is then marked as failed and  further actions will not be completed against that host, hence the later failure for oo_first_master (since c14-master-375d2 is the only member of that group).

The issue is that newer versions of docker fail when configured for lvm loop, which is the way we are configuring the master currently: https://github.com/openshift/openshift-ansible/blob/master/playbooks/aws/openshift-cluster/tasks/launch_instances.yml#L82-L108

Without digging into it too much at this point, I suspect that we'll need to add a docker volume to volume_devs.master, and extend the oo_ec2_volume_definition filter to handle that as well.

As for why OpenStack/GCE are working but ec2 is failing... My only guess is that OpenStack and GCE may be using lvm provisioned disks, which would allow docker_storage_setup to steal some of that space away to create the lvm volumes for docker, while ec2 does not configure LVM

**Comment by menren** [comment]
Docker was only installed on openshift nodes.

Here ansible tries to restart docker on openshift master.

Do we install Docker openshift master now ?
If yes for what purpose ?
If no, we can just restart Docker on openshift nodes

**Comment by menren** [comment]
Ok @detiber by looking in the systemd, the start operation of docker times out.
This issue is known here : https://github.com/docker/docker/issues/15498

By running `systemctl start docker` manually, docker is started after a while.
Then stopping/starting docker again are instant.

Only the first start of Docker times out and only on the master.

**Comment by detiber** [comment]
@menren for deployments that use openshift-sdn we require the master to also be a node for the purpose of the sdn configuration.

The master host is the only one using lvm-loop, the other nodes are provisioned with an additional volume that is configured via cloud-init to be used by docker-storage-setup.

**Comment by menren** [comment]
By adding theses lines, a new volume will automatically created for the master ?
```
diff --git a/playbooks/aws/openshift-cluster/tasks/launch_instances.yml b/playbooks/aws/openshift-cluster/tasks/launch_instances.yml
index 48a08ba..8549151 100644
--- a/playbooks/aws/openshift-cluster/tasks/launch_instances.yml
+++ b/playbooks/aws/openshift-cluster/tasks/launch_instances.yml
@@ -97,6 +97,10 @@
           volume_size: "{{ lookup('env', 'os_master_root_vol_size') | default(25, true) }}"
           device_type: "{{ lookup('env', 'os_master_root_vol_type') | default('gp2', true) }}"
           iops: "{{ lookup('env', 'os_master_root_vol_iops') | default(500, true) }}"
+        docker:
+          volume_size: "{{ lookup('env', 'os_docker_vol_size') | default(10, true) }}"
+          device_type: "{{ lookup('env', 'os_docker_vol_type') | default('gp2', true) }}"
+          iops: "{{ lookup('env', 'os_docker_vol_iops') | default(500, true) }}"
       node:
         root:
           volume_size: "{{ lookup('env', 'os_node_root_vol_size') | default(85, true) }}"

```
With this code, ansible still fails at the start of docker on master host.


I continued my investigation and it seems that when I start Docker manually, some configuration changed.

To confirm that hypothesis I added `ignore_errors: yes` in the Docker role : 
```
- name: enable and start the docker service
  service: name=docker enabled=yes state=started
  ignore_errors: yes

```
The `enable and start docker service` fails in the master as expected
But Docker will be started by https://github.com/openshift/openshift-ansible/blob/master/roles/docker/handlers/main.yml
With this workaround the cluster is deployed without error. However I am not sure that is fully functional.

By the way this is not the right place to discuss about this issue. We should open an issue for this

Imo this PR is ok and does not affect this issue.

**Comment by twiest** [comment]
@menren the problems you are experiencing seem to be unrelated to this PR (ec2.py).

Are you ok if I merge this PR?

**Comment by menren** [comment]
I tested this ec2.py by merging your code in one of our fork of AWS and this seem to work properly.

However by cloning master branch's code, I discovered some issues with my configuration of AWS (ec2 security groups etc.)
So I can't tell you that's ok for 100% with master's code.

**Comment by twiest** [comment]
@menren are you having the same problems with the current ec2.py that's in master?

If so, then I think it's unrelated to this PR.

**Comment by menren** [comment]
I think so to. +1 for this PR

**Comment by twiest** [comment]
Thanks guys, merging based on comments.

**Pull request merged**
