### PR TITLE
Add EAP CD imagestream to 3.10

### PR DESCRIPTION
**Pull request by luck3y**
This is the same IS definition as: https://github.com/jboss-container-images/jboss-eap-7-openshift-image/blob/eap-cd/templates/eap-cd-image-stream.json

### CODE REVIEW

**Comment by michaelgugino** [comment]
@sdodson PTAL

**Comment by sdodson** [comment]
@luck3y The image referenced will be live at 3.10 GA?

**Comment by sdodson** [comment]
Nevermind, I see it's live now.

**Comment by luck3y** [comment]
@sdodson Yep, thanks!

**Pull request merged**
