### PR TITLE
Scale up workers in CI runs

### PR DESCRIPTION
**Pull request by vrutkovs**
This would create one worker initially and scale up another one after cluster is setup

~~Requires https://github.com/openshift/release/pull/2637~~

TODO:
* [x] Create `core` user in test playbooks, as origin tests expect ssh bastion to be the same

### CODE REVIEW

**Comment by vrutkovs** [comment]
>"waiting for openshift-console URL: context deadline exceeded"

/retest

**Comment by sdodson** [comment]
/lgtm
/retest

Will merge if this flakes.

**Pull request merged**
