### PR TITLE
[KIECLOUD-56] - Update PAM DM templates on OpenShift for 7.1.1

### PR DESCRIPTION
**Pull request by spolti**
Signed-off-by: Filippe Spolti <fspolti@redhat.com>

NOTICE
======

Master branch is closed! A major refactor is ongoing in devel-40.
Changes for 3.x should be made directly to the latest release branch they're
relevant to and backported from there.

### CODE REVIEW

**Comment by spolti** [comment]
@vrutkovs Hey, here is the new pr.

**Comment by vrutkovs** [comment]
@sdodson  @spolti does this need to be cherrypicked to 3.10?

**Comment by sdodson** [comment]
> @sdodson @spolti does this need to be cherrypicked to 3.10?

Yeah if it's tested with 3.10 and they want it there too.

**Comment by spolti** [comment]
@vrutkovs @sdodson it would be great.

**Pull request merged**
