### PR TITLE
Reduce warning output

### PR DESCRIPTION
**Pull request by abutcher**
Especially from the command module since we are using the command module rather than the alternative for a reason in most (if not all) cases.

There are a few warnings not covered here such as from the standalone registry deployment tasks in `openshift_hosted` that are removed in https://github.com/openshift/openshift-ansible/pull/2475.

### CODE REVIEW

**Comment by sdodson** [comment]
LGTM, aos-ci-test

**Comment by tbielawa** [comment]
aos-ci-test

**Comment by abutcher** [comment]
Please hold merge I'm gonna comb the CI output for some that I missed.

**Comment by abutcher** [comment]
aos-ci-test

**Comment by abutcher** [comment]
@sdodson good to go

**Pull request merged**
