### PR TITLE
Add Fuse Console templates

### PR DESCRIPTION
**Pull request by astefanutti**
Following up #9036 which omitted to add the Fuse console templates.

### CODE REVIEW

**Comment by vrutkovs** [comment]
bot, test pull request

**Comment by sdodson** [comment]
@astefanutti Where does this file come from? when I run the sync scripts I don't see this new content. I'd much rather ensure that the sync scripts are properly sourcing content from upstream repos than accept a PR that modifies things here.

**Comment by sdodson** [comment]
We pull from whatever is in the GA branch of your repo.

**Comment by astefanutti** [comment]
@sdodson I agree. I missed the sync thing. I've just created #9123 that updates the sync script to move the console templates added by this PR.

Let me know if you want me to close this PR. If that script doesn't run automatically, I can run it for 3.9 release as we'd like to have the Fuse content updated for it as well. I'm not sure whether updating the master branch is necessary as well...

**Comment by sdodson** [comment]
This is fine, picked #9123 back into release-3.10 too

**Comment by astefanutti** [comment]
Thanks for the feedback.

**Pull request merged**
