### PR TITLE
GCE node fixes

### PR DESCRIPTION
**Pull request by jimmidyson**
Ref #575

### CODE REVIEW

**Comment by menren** [comment]
This issue should be fixed by the recent PR of @twiest to make the infra node on GCE like AWS

**Comment by twiest** [comment]
@jimmidyson Can you please test the latest master and see if my changes fixed this problem please?

If they did, can I close this PR?

**Comment by jaryn** [comment]
Can one of the admins verify this patch?

**Comment by jimmidyson** [comment]
How can I check what `gce_machine_image` should be?

**Comment by jimmidyson** [comment]
OK trying with `centos-7-v20150929`.

**Comment by jimmidyson** [comment]
Hung on `Wait for user setup` - no SSH key was assigned to the VM it seems.

**Comment by menren** [comment]
Imo you have to set up an image with correct .ssh/authorized_keys before deploying because the ansible-gce module does not seem to manage ssh keys

**Comment by jimmidyson** [comment]
That's not great then as I don't to put my ssh keys in the image, don't want to have to update the image to roll ssh keys or add new keys in. Shame this is a limitation of the ansible-gce module.

**Comment by jimmidyson** [comment]
Looking at https://github.com/ansible/ansible-modules-core/issues/1083 this should be possible to do.

**Comment by menren** [comment]
I agree with you that can be improved.

I looked at https://github.com/ansible/ansible-modules-core/issues/1083
So passing the ssh-key by metadata it should work ? A bit weird but ok if it works ...
The official documentation of ansible-gce should be updated if it's working
And then we should do a PR to add the possibility to add ssh-key

**Comment by jaryn** [comment]
Can one of the admins verify this patch?

**Comment by jimmidyson** [comment]
Closing this PR but would like the ssh key stuff updated if possible.

**Pull request closed without merging**
