### PR TITLE
Contrib: Hook to verify modules match assembled fragments

### PR DESCRIPTION
**Pull request by tbielawa**
Simple hook to verify generated content matches expected assembled content.

### CODE REVIEW

**Comment by tbielawa** [comment]
aos-ci-test

**Comment by tbielawa** [comment]
[test]

**Comment by sdodson** [comment]
I don't like the contrib directory only because we have https://github.com/openshift/openshift-ansible-contrib and this gets confusing.  Maybe put them in their rightful places, leave them un-executable and mention them in README.md?

**Comment by tbielawa** [comment]
@sdodson  said:

> I don't like the contrib directory only because we have https://github.com/openshift/openshift-ansible-contrib and this gets confusing. Maybe put them in their rightful places, leave them un-executable and mention them in README.md?

Where is the rightful place for git hooks? You can't commit files in the `.git` directory :disappointed: 

```
$ git add .git/hooks/pre-commit
error: Invalid path '.git/hooks/pre-commit'
error: unable to add .git/hooks/pre-commit to index
fatal: adding files failed
```

I forgot about openshift-ansible-contrib. That's a good point.

**Comment by sdodson** [comment]
Yeah, nevermind .git doesn't work.  Maybe hack/git/* ?

**Comment by tbielawa** [comment]
> Yeah, nevermind .git doesn't work. Maybe hack/git/* ?

Sounds good to me. Will update eventually

**Comment by tbielawa** [comment]
aos-ci-test

**Comment by tbielawa** [comment]
[test]

**Comment by tbielawa** [comment]
[test]

**Comment by tbielawa** [comment]
aos-ci-test

**Comment by sdodson** [comment]
aos-ci-test

**Comment by tbielawa** [comment]
[merge]

**Pull request merged**
