### PR TITLE
Templates for CloudForms 4.7

### PR DESCRIPTION
**Pull request by simaishi**
CloudForms 4.7 is supported on 3.9 and later.

I'm not sure if `openshift_examples` still need to be updated with the latest templates. Please let me know if needed.

cc @sdodson @Loicavenel @carbonin

### CODE REVIEW

**Comment by carbonin** [comment]
@vrutkovs I think that's what @simaishi was referencing when she said:

> I'm not sure if `openshift_examples` still need to be updated with the latest templates. Please let me know if needed.

Are those used?

**Comment by carbonin** [comment]
@patrickdillon From our perspective, it would be easier to keep this all in one place. If someone wants to deploy the templates they can use the ones in this directory. All the ansible is really just a wrapper around directly deploying the templates.

@simaishi want to remove those in this PR or a followup?

**Comment by simaishi** [comment]
> @patrickdillon From our perspective, it would be easier to keep this all in one place. If someone wants to deploy the templates they can use the ones in this directory. All the ansible is really just a wrapper around directly deploying the templates.
> 
> @simaishi want to remove those in this PR or a followup?

Opened https://github.com/openshift/openshift-ansible/pull/11166 to remove them.

**Comment by simaishi** [comment]
@patrickdillon @sdodson We'd like the templates to go to 3.9 and 3.10 branches as well. Is there anything I need to do?

**Comment by patrickdillon** [comment]
@simaishi 
/cherrypick release-3.10
/cherrypick release-3.9

**Comment by patrickdillon** [comment]
@simaishi As there are merge conflicts, you will need to open a new pr for the older branches.

**Comment by simaishi** [comment]
@patrickdillon Thank you. Created https://github.com/openshift/openshift-ansible/pull/11296 (for 3.10) and https://github.com/openshift/openshift-ansible/pull/11297 (for 3.9).

**Pull request merged**
