### PR TITLE
Additional overrides for cloud provider playbooks

### PR DESCRIPTION
**Pull request by detiber**
- sdn overrides
- allow overrides for use_flannel and use_fluentd

### CODE REVIEW

**Comment by detiber** [comment]
depends on https://github.com/openshift/openshift-ansible/pull/1237

**Comment by arilivigni** [comment]
aos-ci-test

**Comment by detiber** [comment]
@twiest @wshearn add additional overrides for cloud provider playbooks.

**Comment by twiest** [comment]
@detiber looks good to me.

@lhuard1A @menren please review and make sure this is ok for you.

@detiber I'll wait until I hear back from them and @wshearn before merging.

**Comment by menren** [comment]
This looks good to me.

Is there anywhere we describe all the options we can pass with oo_option (-o in bin/cluster) ?

**Comment by detiber** [comment]
@menren we do not currently list them...  the only way I know to gather them all is to do a `git grep oo_option` on the repo.

**Comment by twiest** [comment]
This looks like it's ready for merging.

@wshearn Please review to make sure you're ok with it, and if so, please merge it.

**Comment by menren** [comment]
@detiber ok. I think it's worth to gather oo_options and describe each one in bin/cluster's help for example or/and in another doc.
It will expose clearly all the customizations we can do on a cluster

Anyways :+1:  for this PR

**Comment by twiest** [comment]
I'm going to go ahead and merge this since we've gotten multiple +1s.

**Pull request merged**
