### PR TITLE
Remove vars_files for byo, scaleup and restart playbooks.

### PR DESCRIPTION
**Pull request by abutcher**
Working towards #686.

Testing
- :white_check_mark: byo
- ✅  master scaleup
- :white_check_mark: node scaleup
- ✅  master restart

Upgrade playbooks have been removed from this PR and will be addressed separately.

### CODE REVIEW

**Comment by detiber** [comment]
@abutcher would it be worth breaking these out into 4 different PRs? Or at least handle master/node scaleup separately?

**Comment by abutcher** [comment]
aos-ci-test

**Comment by abutcher** [comment]
aos-ci-test

**Comment by abutcher** [comment]
aos-ci-test

**Comment by abutcher** [comment]
Containerized failure is suspicious but is passing locally for me.

**Comment by abutcher** [comment]
aos-ci-test

**Comment by detiber** [comment]
lgtm

**Pull request merged**
