### PR TITLE
OWNERS Update

### PR DESCRIPTION
**Pull request by mtnbikenc**

### CODE REVIEW

**Review by vrutkovs — APPROVED** [review]

**Comment by mtnbikenc** [comment]
Added valid-bug as this is not a code change.

**Comment by mtnbikenc** [comment]
Needs https://github.com/openshift/openshift-ansible/pull/12334

**Comment by mtnbikenc** [comment]
Triggering Travis retest.

**Comment by mtnbikenc** [comment]
OWNERS only update.  Test has already passed.
/override ci/prow/e2e-aws-workers-rhel7

**Pull request merged**
