### PR TITLE
Adding defaults for the gcp variables to fix an undefined ansible exception.

### PR DESCRIPTION
**Pull request by kwoodson**
Fix for bz: https://bugzilla.redhat.com/show_bug.cgi?id=1538581

Default variables for gcp.  Check to ensure defaults are set to something other than '' to ensure this works.

### CODE REVIEW

**Comment by kwoodson** [comment]
Fixed tox.

**Comment by kwoodson** [comment]
Yet another tox fix. @smarterclayton  @sdodson, mind adding lgtm?

**Comment by kwoodson** [comment]
I'm not sure these are related.  @sdodson  @smarterclayton, ideas?  I think these changes are pretty safe.

```
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/router/scoped.go:42
Expected error:
    <*errors.errorString | 0xc4212f00b0>: {
        s: "last response from server was not 200:\n",
    }
    last response from server was not 200:
    
not to have occurred
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/router/scoped.go:79
```

**Comment by sdodson** [comment]
Just your run of the mill e2e flakes.
/test gcp

**Pull request merged**
