### PR TITLE
Add EAP 7.2.0.GA imagestreams and templates

### PR DESCRIPTION
**Pull request by luck3y**
Add EAP 7.2.0 GA release to imagestreams and templates.
Signed-off-by: Ken Wills <kwills@redhat.com>

NOTICE
======

Master branch is closed! A major refactor is ongoing in devel-40.
Changes for 3.x should be made directly to the latest release branch they're
relevant to and backported from there.

### CODE REVIEW

**Comment by luck3y** [comment]
@sdodson Thanks Scott, will update it.

> BTW, I assume this content is only available for ppc64le?

It should be available for x64 only.

**Comment by luck3y** [comment]
@sdodson Updated to just be in the x86_64 subdir.

**Comment by luck3y** [comment]
@sdodson Oh, I didn't know that existed ... I suspect nobody else did either, since theres no EAP stuff at all in there ;)

**Comment by luck3y** [comment]
@sdodson FYI, examples.sh updated / fixed up a bit here: https://github.com/openshift/openshift-ansible/pull/11080

**Comment by luck3y** [comment]
@sdodson Sorry to be a pest, but I'm not sure why the e2-aws test is failing, is it unrelated to the PR?

**Comment by sdodson** [comment]
/ok-to-test

Yeah, that looks like a flake, the bot should automatically retest any lgtm'd pr but perhaps it doesn't implicitly set ok-to-test?

**Pull request merged**
