### PR TITLE
Deprecate openshift_sanitize_inventory

### PR DESCRIPTION
**Pull request by mtnbikenc**
This role is no longer necessary.

### CODE REVIEW

**Comment by mtnbikenc** [comment]
Tested scaleup successfully.

**Comment by mtnbikenc** [comment]
```
Failing tests:

[Conformance][Area:Networking][Feature:Router] The default ClusterIngress should support default wildcard reencrypt routes through external DNS [Suite:openshift/conformance/parallel/minimal]
[Feature:Platform] Managed cluster should have no crashlooping pods in core namespaces over two minutes [Suite:openshift/conformance/parallel]
[sig-api-machinery] Namespaces [Serial] should ensure that all pods are removed when a namespace is deleted [Conformance] [Suite:openshift/conformance/serial/minimal] [Suite:k8s]
[sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should perform rolling updates and roll backs of template modifications with PVCs [Suite:openshift/conformance/parallel] [Suite:k8s]
```
/retest

**Comment by mtnbikenc** [comment]
```
Failing tests:

[sig-storage] In-tree Volumes [Driver: aws] [Testpattern: Dynamic PV (default fs)] subPath should support existing directories when readOnly specified in the volumeSource [Suite:openshift/conformance/parallel] [Suite:k8s]
```
/retest

**Comment by mtnbikenc** [comment]
```
level=error msg="\t* aws_iam_instance_profile.bootstrap: Error deleting IAM instance profile ci-op-wjpnjtg7-5eb04-bootstrap-profile: NoSuchEntity: Instance Profile ci-op-wjpnjtg7-5eb04-bootstrap-profile cannot be found."
```
/retest

**Comment by mtnbikenc** [comment]
```
fatal: [localhost]: FAILED! => 
  msg: 'The conditional check ''svc.results.results[0].status.loadBalancer.ingress | length > 0'' failed. The error was: error while evaluating conditional (svc.results.results[0].status.loadBalancer.ingress | length > 0): ''dict object'' has no attribute ''ingress'''
```
/retest

**Comment by vrutkovs** [comment]
```
Failing tests:

[Feature:Builds][Conformance] oc new-app  should succeed with a --name of 58 characters [Suite:openshift/conformance/parallel/minimal]
[Feature:DeploymentConfig] deploymentconfigs when run iteratively [Conformance] should only deploy the last deployment [Suite:openshift/conformance/parallel/minimal]
[Feature:DeploymentConfig] deploymentconfigs with revision history limits [Conformance] should never persist more old deployments than acceptable after being observed by the controller [Suite:openshift/conformance/parallel/minimal]
[Feature:Platform] Managed cluster should have no crashlooping pods in core namespaces over two minutes [Suite:openshift/conformance/parallel]
[k8s.io] EquivalenceCache [Serial] validates pod affinity works properly when new replica pod is scheduled [Suite:openshift/conformance/serial] [Suite:k8s]
[k8s.io] EquivalenceCache [Serial] validates pod anti-affinity works properly when new replica pod is scheduled [Suite:openshift/conformance/serial] [Suite:k8s]
[sig-api-machinery] Garbage collector should support orphan deletion of custom resources [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-scheduling] PodPriorityResolution [Serial] validates critical system priorities are created and resolved [Suite:openshift/conformance/serial] [Suite:k8s]
[sig-scheduling] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run  [Conformance] [Suite:openshift/conformance/serial/minimal] [Suite:k8s]
[sig-scheduling] SchedulerPredicates [Serial] validates that NodeAffinity is respected if not matching [Suite:openshift/conformance/serial] [Suite:k8s]
[sig-scheduling] SchedulerPredicates [Serial] validates that NodeSelector is respected if matching  [Conformance] [Suite:openshift/conformance/serial/minimal] [Suite:k8s]
[sig-scheduling] SchedulerPredicates [Serial] validates that NodeSelector is respected if not matching  [Conformance] [Suite:openshift/conformance/serial/minimal] [Suite:k8s]
[sig-scheduling] SchedulerPredicates [Serial] validates that required NodeAffinity setting is respected if matching [Suite:openshift/conformance/serial] [Suite:k8s]
[sig-scheduling] SchedulerPredicates [Serial] validates that taints-tolerations is respected if matching [Suite:openshift/conformance/serial] [Suite:k8s]
[sig-scheduling] SchedulerPredicates [Serial] validates that taints-tolerations is respected if not matching [Suite:openshift/conformance/serial] [Suite:k8s]
[sig-scheduling] SchedulerPreemption [Serial] validates basic preemption works [Suite:openshift/conformance/serial] [Suite:k8s]
[sig-scheduling] SchedulerPreemption [Serial] validates lower priority pod preemption by critical pod [Suite:openshift/conformance/serial] [Suite:k8s]
[sig-scheduling] SchedulerPreemption [Serial] validates pod anti-affinity works in preemption [Suite:openshift/conformance/serial] [Suite:k8s]
[sig-storage] In-tree Volumes [Driver: azure] [Testpattern: Inline-volume (default fs)] subPath should fail for new directories when readOnly specified in the volumeSource [Suite:openshift/conformance/parallel] [Suite:k8s]
```
/retest

**Comment by mtnbikenc** [comment]
```
Failing tests:

[Conformance][Area:Networking][Feature:Router] The HAProxy router converges when multiple routers are writing status [Suite:openshift/conformance/parallel/minimal]
[Feature:Platform] Managed cluster should have no crashlooping pods in core namespaces over two minutes [Suite:openshift/conformance/parallel]
```

**Comment by mtnbikenc** [comment]
[327](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/11195/pull-ci-openshift-openshift-ansible-devel-40-e2e-aws-scaleup/327/build-log.txt)
```
fatal: [localhost]: FAILED! => 
  msg: 'The conditional check ''svc.results.results[0].status.loadBalancer.ingress | length > 0'' failed. The error was: error while evaluating conditional (svc.results.results[0].status.loadBalancer.ingress | length > 0): ''dict object'' has no attribute ''ingress'''
```
Needs #11236

**Comment by mtnbikenc** [comment]
333
```
Failing tests:

[Feature:Platform] Managed cluster should have no crashlooping pods in core namespaces over two minutes [Suite:openshift/conformance/parallel]
```

**Comment by mtnbikenc** [comment]
Known issue with crashlooping pods fixed by https://github.com/openshift/machine-config-operator/pull/495.  Merging.

**Pull request merged**
