### PR TITLE
fixes #10386 - cluster-monitoring: Adds storageclass name variable

### LINKED ISSUE #10386: openshift-monitoring should support storageclass name variable
#### Description

In the current state, `openshift-cluster-monitoring` role can create PVC without StorageClass definition. This works fine in environment with a single StorageClass definition, which is set as default, but it causes problems in environment with multiple StorageClasses or without default class annotation configured.

The idea is that administrators could set the StorageClass used by `prometheus` and `alertmanager` by using variables in the inventory file, that will take affect when storage provisioning is enabled for those components. For example:

```
openshift_cluster_monitoring_operator_prometheus_storage_enabled=true
openshift_cluster_monitoring_operator_alertmanager_storage_enabled=true
(...)
openshift_cluster_monitoring_operator_prometheus_storage_class_name=glusterfs-storage
openshift_cluster_monitoring_operator_alertmanager_storage_class_name=glusterfs-storage
```

##### Version

Affects `release-3.11` and `master` branches.

##### Extra information

I'll send the PR in a few minutes with a patch.

### PR DESCRIPTION
**Pull request by davivcgarcia**
This PR is a proposal to implement feature described at #10386.

### CODE REVIEW

**Comment by brancz** [comment]
/lgtm

@sdodson @vrutkovs can we already cherry-pick changes into the 3.11 release branch? If so this would be a candidate for 3.11.z.

**Comment by vrutkovs** [comment]
Sure
/cherrypick release-3.11

**Comment by brancz** [comment]
@davivcgarcia could you have a look at the test failures. Given it failed so often, maybe there's a true failure :slightly_smiling_face: . I don't know ansible well so maybe @sdodson or @vrutkovs can spot an obvious mistake :slightly_smiling_face: .

**Comment by davivcgarcia** [comment]
@brancz I checked the build logs and the error seems to be related to the test infrastructure and not related to the feature implemented on this PR. The error is caused by problems installing package `ansible-2.6.5`:

```
package ansible-2.6.5 is not installed
error: build error: running 'INSTALL_PKGS="python-lxml python-dns pyOpenSSL python2-cryptography openssl python2-passlib httpd-tools openssh-clients origin-clients iproute patch"  && yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS  && EPEL_PKGS="ansible-2.6.5 python2-boto python2-boto3 python2-crypto which python2-pip.noarch python2-scandir python2-packaging azure-cli"  && yum install -y epel-release  && yum install -y --setopt=tsflags=nodocs $EPEL_PKGS  && if [ "$(uname -m)" == "x86_64" ]; then yum install -y https://sdodson.fedorapeople.org/google-cloud-sdk-183.0.0-3.el7.x86_64.rpm ; fi  && yum install -y java-1.8.0-openjdk-headless  && rpm -V $INSTALL_PKGS $EPEL_PKGS $EPEL_TESTING_PKGS  && pip install 'apache-libcloud~=2.2.1' 'SecretStorage<3' 'ansible[azure]'  && yum clean all' failed with exit code 1
2018/10/15 16:09:20 Ran for 4m27s
error: could not run steps: could not wait for build: the build ansible failed after 2m54s with reason DockerBuildFailed: Docker build strategy has failed.
```

**Comment by vrutkovs** [comment]
PR is fine, CI is flaking a lot though. We're working on it, ideally It should resolve itself fairly soon

**Pull request merged**
