### PR TITLE
Place-holder for prerequisites.yml

### PR DESCRIPTION
**Pull request by michaelgugino**
We need this file to be in place to add an additional step
to the CI jobs.

In subsequent PRs, we can add steps into this file.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
What will live here? Are these steps we intend to manage for customers? Is this just to set up the CI environment? If the latter, let's do it in the AMI.

**Comment by michaelgugino** [comment]
@stevekuznetsov 
We're going to migrate some one-time tasks that users will need to perform to this play.

Namely, installing and configuring docker to start with.  We might also add the network manager pieces, and other 'once before install' type tasks.

**Comment by kwoodson** [comment]
@michaelgugino, I thought byo was going away.  Do we want to move this somewhere else?

**Comment by michaelgugino** [comment]
@kwoodson I'm not sure where we are in that process.  I know there was a script that used to complain if an entry point was outside of byo.

**Comment by mtnbikenc** [comment]
I agree this should not be placed in byo, but I'd like to discuss the overall flow in relation to the playbook consolidation work.  Also, I'd like to see how this fits with https://github.com/openshift/openshift-ansible/issues/6012.  I'm not saying it doesn't, it's just a matter of the layout of where everything goes.

**Comment by stevekuznetsov** [comment]
@kargakis check out that robot doing work for us :)

**Comment by kargakis** [comment]
eager to help

**Pull request merged**
