### PR TITLE
Atomic command workarounds

### PR DESCRIPTION
**Pull request by ashcrow**
These are workarounds related to minor bugs found in the ``atomic`` command/package.

### CODE REVIEW

**Comment by sdodson** [comment]
3.6 blocker?

**Comment by ashcrow** [comment]
@sdodson it might be. I'm double checking now.

**Comment by ashcrow** [comment]
@sdodson yes, blocker.

**Comment by ashcrow** [comment]
aos-ci-test

**Comment by sdodson** [comment]
travis is happy and none of the ci jobs trigger systemcontainer based installs, so merged

**Pull request merged**
