### PR TITLE
Removing clear_facts from 3.10 upgrade

### LINKED ISSUE #7722: Ansible 2.5 causes unexpected facts error in openshift_health_checker.py when trying to upgrade
I had been testing changes to v3.10 upgrades when I ended up having to rebuild my local Ansible image with 2.5 (which showed up in epel testing yesterday).  After that, I'm getting the following error trying to run the upgrade playbooks, specifically when openshift_health_checker runs:

```
PLAY [Update repos on upgrade hosts] *******************************************

TASK [openshift_repos : openshift_repos detect ostree] *************************
Saturday 31 March 2018  03:46:00 +0000 (0:00:00.357)       0:00:23.657 ********
ok: [ci-claytontest2-ig-m-k9x5]

TASK [openshift_repos : Ensure libselinux-python is installed] *****************
Saturday 31 March 2018  03:46:01 +0000 (0:00:00.372)       0:00:24.030 ********
ok: [ci-claytontest2-ig-m-k9x5]

TASK [openshift_repos : Remove openshift_additional.repo file] *****************
Saturday 31 March 2018  03:46:01 +0000 (0:00:00.665)       0:00:24.695 ********
^[[Aok: [ci-claytontest2-ig-m-k9x5]

TASK [openshift_repos : Create any additional repos that are defined] **********
Saturday 31 March 2018  03:46:02 +0000 (0:00:00.595)       0:00:25.291 ********
changed: [ci-claytontest2-ig-m-k9x5] => (item={u'gpgcheck': 0, u'enabled': 1, u'name': u'origin-pr', u'baseurl': u'https://storage.googleapis.com/origin-ci-test/logs/test_branch_origin_extended_conformance_gce/2787/artifacts/rpms'})
ok: [ci-claytontest2-ig-m-k9x5] => (item={u'gpgcheck': 0, u'enabled': 1, u'name': u'origin-pr-dependencies', u'baseurl': u'http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/'})

TASK [openshift_repos : include_tasks] *****************************************
Saturday 31 March 2018  03:46:03 +0000 (0:00:00.928)       0:00:26.220 ********
skipping: [ci-claytontest2-ig-m-k9x5]

TASK [openshift_repos : include_tasks] *****************************************
Saturday 31 March 2018  03:46:03 +0000 (0:00:00.088)       0:00:26.308 ********
included: /usr/share/ansible/openshift-ansible/roles/openshift_repos/tasks/centos_repos.yml for ci-claytontest2-ig-m-k9x5

TASK [openshift_repos : Configure origin gpg keys] *****************************
Saturday 31 March 2018  03:46:03 +0000 (0:00:00.134)       0:00:26.442 ********
ok: [ci-claytontest2-ig-m-k9x5]

TASK [openshift_repos : Configure correct origin release repository] ***********
Saturday 31 March 2018  03:46:04 +0000 (0:00:00.995)       0:00:27.438 ********
ok: [ci-claytontest2-ig-m-k9x5] => (item=/usr/share/ansible/openshift-ansible/roles/openshift_repos/templates/CentOS-OpenShift-Origin.repo.j2)

TASK [openshift_repos : Ensure clean repo cache in the event repos have been changed manually] ***
Saturday 31 March 2018  03:46:05 +0000 (0:00:01.023)       0:00:28.461 ********
changed: [ci-claytontest2-ig-m-k9x5] => {
    "msg": "First run of openshift_repos"
}

TASK [openshift_repos : Record that openshift_repos already ran] ***************
Saturday 31 March 2018  03:46:05 +0000 (0:00:00.118)       0:00:28.580 ********
ok: [ci-claytontest2-ig-m-k9x5]

RUNNING HANDLER [openshift_repos : refresh cache] ******************************
Saturday 31 March 2018  03:46:05 +0000 (0:00:00.183)       0:00:28.764 ********
changed: [ci-claytontest2-ig-m-k9x5]

PLAY [Set openshift_no_proxy_internal_hostnames] *******************************

TASK [set_fact] ****************************************************************
Saturday 31 March 2018  03:46:06 +0000 (0:00:00.856)       0:00:29.621 ********
skipping: [ci-claytontest2-ig-m-k9x5]

PLAY [OpenShift Health Checks] *************************************************

TASK [Run health checks (upgrade)] *********************************************
Saturday 31 March 2018  03:46:06 +0000 (0:00:00.080)       0:00:29.702 ********
fatal: [ci-claytontest2-ig-m-k9x5]: FAILED! => {"changed": false, "msg": "'openshift' is undefined, did 'openshift_facts' run?", "playbook_context": "upgrade"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
ci-claytontest2-ig-m-k9x5  : ok=37   changed=3    unreachable=0    failed=1
localhost                  : ok=16   changed=4    unreachable=0    failed=0

Saturday 31 March 2018  03:46:06 +0000 (0:00:00.080)       0:00:29.782 ********
===============================================================================
Gathering Facts --------------------------------------------------------- 3.45s
Ensure openshift-ansible installer package deps are installed ----------- 3.36s
Gathering Facts --------------------------------------------------------- 2.28s
Gather Cluster facts ---------------------------------------------------- 1.35s
Initialize openshift.node.sdn_mtu --------------------------------------- 1.13s
openshift_repos : Configure correct origin release repository ----------- 1.02s
openshift_repos : Configure origin gpg keys ----------------------------- 1.00s
openshift_repos : Create any additional repos that are defined ---------- 0.93s
get openshift_current_version ------------------------------------------- 0.89s
Gathering Facts --------------------------------------------------------- 0.88s
openshift_repos : refresh cache ----------------------------------------- 0.86s
Detecting Operating System from ostree_booted --------------------------- 0.69s
openshift_repos : Ensure libselinux-python is installed ----------------- 0.67s
openshift_repos : Remove openshift_additional.repo file ----------------- 0.60s
Check if iptables is running -------------------------------------------- 0.47s
check for node already bootstrapped ------------------------------------- 0.47s
openshift_repos : openshift_repos detect ostree ------------------------- 0.37s
Evaluate oo_nodes_to_upgrade -------------------------------------------- 0.36s
openshift_sanitize_inventory : conditional_set_fact --------------------- 0.35s
openshift_sanitize_inventory : conditional_set_fact --------------------- 0.32s


Failure summary:


  1. Hosts:    ci-claytontest2-ig-m-k9x5
     Play:     OpenShift Health Checks
     Task:     Run health checks (upgrade)
     Message:  'openshift' is undefined, did 'openshift_facts' run?
```

The facts are set, but it looks like something about the module interface is different in 2.5 where the module isn't seeing the appropriate facts but 2.4 was.

### PR DESCRIPTION
**Pull request by mtnbikenc**
`clear_facts` removes the custom `openshift` facts

Fixes #7722

### CODE REVIEW

**Comment by sdodson** [comment]
That was only relevant to double upgrades and even there it's dubious if it worked as intended.

**Comment by michaelgugino** [comment]
@mtnbikenc @sdodson back-port to 3.9?  Uncertain if this is needed (I vote no) and will break anyone that upgrades to ansible 2.5 in the future, which would be a valid configuration according to our spec.

**Comment by mtnbikenc** [comment]
@michaelgugino I think we should remove it from the 3.9 upgrade as well.  But I'd like to test it more with other versions of Ansible before making that change.

**Comment by mtnbikenc** [comment]
bot, retest this please

**Pull request merged**
