### PR TITLE
updated dynamic storage section for openshift metrics

### PR DESCRIPTION
**Pull request by ekuric**
updated dynamic storage section for openshift metrics to support storage class name

Signed-off-by: Elvir Kuric <elvirkuric@gmail.com>

### CODE REVIEW

**Comment by ewolinetz** [comment]
Does the scenario where were do not provide a storage class still work as it previously did, or should the template be updated?

@kwoodson what was the logic around dynamic pvcs and storage classes again?

**Comment by ekuric** [comment]
@ewolinetz regarding  defaults/main.yml would it be reasonable to have some defaults for 
openshift_metrics_cassanda_pvc_storage_class_name parameter? I think it should be left without any default value and expect to be set based on storage class present on system 

In origin-metrics it has value "dynamic" thought 
https://github.com/openshift/origin-metrics/blob/master/deployer/templates/hawkular-cassandra-node-dynamic-pv.yaml#L47

**Comment by ekuric** [comment]
@ewolinetz I can create default value for storageclass name in defaults/main.yml, but in my opinion it will be just unusable as there is not predefined "apply to all" storage class name which will applicable and be used for all if none is given, do we still need it?

**Comment by ewolinetz** [comment]
@ekuric sorry, I lost track of this. That makes sense to me that we would have it as it is here.
/retest
/lgtm

**Pull request merged**
