### PR TITLE
Move all-in-one fail check to evaluate_groups.yml

### PR DESCRIPTION
**Pull request by mtnbikenc**
Moving the new `fail` test for `etcd` group to evaluate groups where the rest of these tests reside.

### CODE REVIEW

**Comment by kwoodson** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
Fixed improper use of groups.

**Comment by mtnbikenc** [comment]
aos-ci-test

**Comment by mtnbikenc** [comment]
[merge]

**Pull request merged**
