### PR TITLE
[3.7] retry package operations

### PR DESCRIPTION
**Pull request by sosiouxme**
Cherry-pick of https://github.com/openshift/openshift-ansible/pull/6302

When a package install/update fails due to network blips or other spotty
availability, retry it. If the failure is a real failure (e.g. package
is really not there) it still fails after 3 tries (Ansible default).

### CODE REVIEW

**Comment by sosiouxme** [comment]
bot, retest this please

**Comment by sosiouxme** [comment]
@stevekuznetsov CI env looks slightly borkinated

```
Error: Package: 1:skopeo-0.1.24-1.dev.git28d4e08.el7.x86_64 (oso-rhui-rhel-server-extras)
           Requires: skopeo-containers = 1:0.1.24-1.dev.git28d4e08.el7
           Installed: 1:skopeo-containers-0.1.26-2.dev.git2e8377a.el7.x86_64 (@httpsmirroropenshiftcomenterpriserheldockertestedx8664os)
               skopeo-containers = 1:0.1.26-2.dev.git2e8377a.el7
```

**Comment by sosiouxme** [comment]
Hm, my bad, I was confused by the results summary. Those skopeo version failures were left over from 12/2. Current failure is just the repo disablement failing (quite quickly) for some reason.

**Comment by sosiouxme** [comment]
It would be really helpful if @openshift-ci-robot would include the timestamp in its summary since it's reporting old results while the new ones are still running. Or it could just not report old results when the next iteration is running. Or I could just ignore the bot and read the github summary which seems to be more accurate.

**Comment by sdodson** [comment]
docker flake, install job passed, merging.

**Comment by stevekuznetsov** [comment]
@sosiouxme we have an issue upstream for that

**Pull request merged**
