### PR TITLE
Fix BZ#1422541 BZ#1440586 BZ#1440612 BZ#1440617 on master branch

### PR DESCRIPTION
**Pull request by wkshi**

### CODE REVIEW

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[merge]

**Comment by ingvagabund** [comment]
aos-ci-test

**Comment by wkshi** [comment]
@sdodson Hi, are we still going to merge it?

**Comment by ingvagabund** [comment]
aos-ci-test

**Comment by ingvagabund** [comment]
@wkshi can you backport it to the release-3.6 branch as well?

**Comment by wkshi** [comment]
Okay

**Comment by ingvagabund** [comment]
@sdodson  This can be merged, the `OS_3.6_containerized_e2e_tests` reports `e2e tests passed`

**Pull request merged**
