### PR TITLE
Fix nsupdate var chec, checks for .

### PR DESCRIPTION
**Pull request by erj826**

### CODE REVIEW

**Comment by vrutkovs** [comment]
Looks like #8849 is related

**Comment by tomassedovic** [comment]
The bug got into the 3.10 branch, we'll have to cherry-pick it there :-(.

**Comment by vrutkovs** [comment]
/lgtm cancel

Commits need to be squashed

**Comment by tomassedovic** [comment]
Ah okay, sorry about that. @erj826 would you please squash the commits into one?

**Pull request merged**
