### PR TITLE
Add CentOS PaaS SIG repos for RHEL

### PR DESCRIPTION
**Pull request by sdodson**
Fixes https://github.com/openshift/origin/issues/9589

### CODE REVIEW

**Comment by sdodson** [comment]
@tdawson is there a more sane way to make this work?

**Comment by sdodson** [comment]
aos-ci-test

**Comment by tdawson** [comment]
LGTM
:+1:

**Comment by tdawson** [comment]
That is the most sane way to do it.  If you try to install the centos-release-openshift-origin rpm, you start going down a rpm dependency hole.

**Pull request merged**
