### PR TITLE
[Release 3.10] Disable examples for power (ppc64le) installs

### PR DESCRIPTION
**Pull request by jeffdyoung**
Adding ppc64le supported imagestream/template definitions.
If the installer detects ppc64le, then the default streams are not installed. The user has the option to add content manually. 

Will be properly addressed in release 4

### CODE REVIEW

**Comment by sdodson** [comment]
/lgtm
/retest
master branch PR https://github.com/openshift/openshift-ansible/pull/9683

**Comment by sdodson** [comment]
@bparees Can you tell if the e2e failures here are potentially related to this PR? I can't think of any reason this PR would cause failures on non ppc64le but I'm apprehensive about assuming those are just flakes.

**Comment by bparees** [comment]
@sdodson as long a you mean the two build timing test failures seen here:
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/9720/test_pull_request_openshift_ansible_extended_conformance_install_310/430/

those flakes are fine.  looks like you're hitting something that was fixed in 3.11, i'm now backporting it to 3.10 here:
https://github.com/openshift/origin/pull/20762

**Comment by sdodson** [comment]
Yes those, thanks.

**Pull request merged**
