### PR TITLE
We require docker 1.9 for the 3.2 upgrade

### PR DESCRIPTION
**Pull request by brenton**

### CODE REVIEW

**Comment by brenton** [comment]
We can't merge this until we confirm QE has access to an ostree with docker 1.9.

**Comment by detiber** [comment]
lgtm

**Comment by brenton** [comment]
We should be able to merge this later today or tomorrow.

**Comment by detiber** [comment]
@brenton if the ostree with Docker 1.9 is now available for QE, I say we merge this now. Will still be a few days before I have the rest of the commits for the parallel pulls work broken up, reviewed and merged.

**Comment by brenton** [comment]
I sent an email this morning to find out if the ostree is ready.

**Pull request merged**
