### PR TITLE
Fix serviceaccounts' secrets for Metrics

### PR DESCRIPTION
**Pull request by jmartisk**
https://bugzilla.redhat.com/show_bug.cgi?id=1688642

### CODE REVIEW

**Comment by patrickdillon** [comment]
/skip
e2e-aws-scaleup-rhel7 should not be run on release-3.9

**Comment by patrickdillon** [comment]
I think the e2e-aws-scaleup-rhel7 test is correctly being ignored. 

@jsanda can you take a look and give lgtm?

**Comment by jmartisk** [comment]
John is no longer working on this AFAIK, perhaps @rubenvp8510 could review?

**Comment by patrickdillon** [comment]
If @rubenvp8510  could review that would be great. We need someone with domain knowledge to give a lgtm

**Comment by rubenvp8510** [comment]
e2e-aws-scaleup-rhel7 test failure is not related to the PR. The changes LGTM.

**Comment by mtnbikenc** [comment]
Not applicable to release-3.9
/override ci/prow/e2e-aws-scaleup-rhel7

**Pull request merged**
