### PR TITLE
Add EAP 7.2.beta to xpass imagestreams and templates

### PR DESCRIPTION
**Pull request by luck3y**
Signed-off-by: Ken Wills <kwills@redhat.com>

### CODE REVIEW

**Comment by luck3y** [comment]
@vrutkovs Any update on this one? Can it be merged? Thanks!

**Comment by luck3y** [comment]
Squashed, thanks!

**Comment by vrutkovs** [comment]
@luck3y this needs another update :(

While this PR was has been under review `roles/openshift_examples/files/examples/` has been changed to be unversioned, so instead of `v3_11` the files should be put in `latest` folder. This would simplify cherrypicks in the future

**Comment by vrutkovs** [comment]
Master branch is closed! A major refactor is ongoing in devel-40. Changes for 3.x should be made directly to the latest release branch they're relevant to and backported from there.

**Pull request closed without merging**
