### PR TITLE
add subnet param in azure.conf.j2

### PR DESCRIPTION
**Pull request by zipper97412**
Just add some more parameters in `roles/openshift_cloud_provider/templates/azure.conf.j2`
I added one parameter from [this](https://github.com/kubernetes/kubernetes/issues/49577#issuecomment-333499492) (`subnet`) and it works for me but i am not sure for the other ones.

Tell me which one I should add

### CODE REVIEW

**Comment by mjudeikis** [comment]
I would add LB SKUS and securityGroup as a minimal set to what exists now. Example:
```
LoadBalancerSku:   "standard",
SecurityGroupName: "nsg-worker",
```
At best if we want to cover all use-cases, we need to add all from: 
https://github.com/kubernetes/cloud-provider-azure/blob/master/docs/cloud-provider-config.md

In example if somebody would user VMScaleSets instead of AvailabilitySet (I dont see any reason anybody should do this with current openshift-ansible due our code limitation how we boostrap nodes, but still, this might come later as Openshift On Azure is using those) they would need other parameters from the list in the url

**Comment by sdodson** [comment]
/lgtm
accept minimal change rather than re-factoring due to the lifecycle of this code (ie: it's going away in 4.x)

**Comment by sdodson** [comment]
/lgtm cancel
Please base this off of release-3.11 branch

**Comment by mtnbikenc** [comment]
Please rebase this PR or open a new PR against the release-3.11 branch.
/close

**Pull request closed without merging**
