### PR TITLE
Infrastructure - Set OpenShift Registry

### PR DESCRIPTION
**Pull request by jwhonce**
* TODO: update to secure when 'add volume' feature available in origin

### CODE REVIEW

**Comment by jwhonce** [comment]
@wshearn @tdawson Please review

**Comment by tdawson** [comment]
Looks good. to me :+1:

**Comment by tdawson** [comment]
Just did a cluster build with this patch.  Works great.

**Comment by tdawson** [comment]
Just did another test with the updated patch.  Still works great. :+1:

**Pull request merged**
