### PR TITLE
Switch the default network mode to ovs-networkpolicy

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by danwinship** [comment]
Is this for all users or just for our CI clusters? We don't want to change the default for customers yet

**Comment by smarterclayton** [comment]
Ci primarily.  Is it not ready in 3.10?

**Comment by danwinship** [comment]
No, it's just that given that the eventual plan is to move people to OVN anyway, it didn't seem worth changing the default twice and dealing with differences in documentation between versions, etc.

**Comment by smarterclayton** [comment]
I’d want at least one environment on it in tests since it’s tectonic equivalent.  If there are no other comments or concerns I’m going to tag it.

**Pull request merged**
