### PR TITLE
Correct default sdn_mtu setting

### PR DESCRIPTION
**Pull request by mtnbikenc**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1568017

### CODE REVIEW

**Comment by mtnbikenc** [comment]
I ran a test in AWS and it still picked up the interface MTU of 8951, so it is confirmed to pull it from the interface if not set in inventory.

**Comment by mtnbikenc** [comment]
bot, retest this please

**Comment by sdodson** [comment]
My local install also got bad MTU, nothing in networking was working. I bet this will fix many issues.

**Pull request merged**
