### PR TITLE
Update imagestreams and quickstarts from origin

### PR DESCRIPTION
**Pull request by sdodson**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1274199

### CODE REVIEW

**Comment by sdodson** [comment]
@brenton just syncing examples with origin

**Comment by brenton** [comment]
Unless this is urgent let's wait for QE to verify this one since there's a BZ involved.  I've added myself as CC to that bug.

**Comment by sdodson** [comment]
Not urgent, but necessary before 1.1/3.1

**Comment by sdodson** [comment]
@brenton QE has marked the bug verified, ready for merge

**Pull request merged**
