### PR TITLE
Updating CI repo URL

### PR DESCRIPTION
**Pull request by mtnbikenc**

### CODE REVIEW

**Comment by mtnbikenc** [comment]
The unit test fix has not yet merged. https://github.com/openshift/release/pull/15423

**Comment by mtnbikenc** [comment]
The workers-rhel7 job needed https://github.com/openshift/release/pull/15413.

**Comment by mtnbikenc** [comment]
CI only change, overriding bugzilla/valid-bug.

**Comment by sdodson** [comment]
Seems like install is at least successful, feel free to override if you wish.

**Comment by mtnbikenc** [comment]
Scaleup succeed but some tests are failing.  Opening bugs on failing tests.
/override ci/prow/e2e-aws-workers-rhel7

**Pull request merged**
