### PR TITLE
Ensure we're running with admin kubeconfig in several locations

### PR DESCRIPTION
**Pull request by sdodson**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1576527

Probably several candidates for things that could be moved to oc_* modules which handle this automatically but we'll get that later.

### CODE REVIEW

**Comment by sdodson** [comment]
bot, retest this please

**Comment by vrutkovs** [comment]
bot, retest this please

**Comment by vrutkovs** [comment]
bot, retest this please

**Pull request merged**
